### ISSUE TITLE
Work-around for .find().sort() and QueryExceededMemoryLimitNoDiskUseAllowed

### ISSUE THREAD

**Issue by bluepuma77** [Automattic/mongoose#10177]
When using a `.find().sort().exec()` on a large table I get a `QueryExceededMemoryLimitNoDiskUseAllowed` exception:

```
MongoError: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.
    at MessageStream.messageHandler (/Users/server/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (node:events:369:20)
    at MessageStream.emit (node:domain:470:12)
    at processIncomingData (/Users/server/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/Users/server/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:395:12)
    at MessageStream.Writable.write (node:internal/streams/writable:340:10)
    at Socket.ondata (node:internal/streams/readable:750:22)
    at Socket.emit (node:events:369:20)
    at Socket.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 7, high_: 1619430623 },
  ok: 0,
  code: 292,
  codeName: 'QueryExceededMemoryLimitNoDiskUseAllowed',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 7, high_: 1619430623 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
```

I read that for aggregations I can just use `.allowDiskUse(true)`. Is this not available for `.find().sort()` ?

mongodb 4.4
node v15.14.0
mongoose 5.12.5

```
{
    "compilerOptions": {
        "module": "commonjs",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "target": "es2017",
        "noImplicitAny": false,
        "moduleResolution": "node",
        "sourceMap": true,
        "types": ["jest", "supertest", "node"],
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": ["node_modules/*"]
        }
    },
    "include": ["src/**/*"]
}
```

**Comment by IslandRhythms** [comment]
Can't say more without a repro script, did you use `.allowDiskUsage(true)` when you ran that operation?

**Comment by vkarpov15** [comment]
Right now the workaround is to use the [`setOptions()` function](https://mongoosejs.com/docs/api/query.html#query_Query-setOptions):

```javascript
await Test.find().sort({ name: 1 }).setOptions({ allowDiskUse: true }).exec();
```

We'll add a `allowDiskUse` method in v5.12.8.
