### ISSUE TITLE
Populate seems to jump down to previous .dot level if value does not exist in Types.Mixed.

### ISSUE THREAD

**Issue by EmilsWebbod** [Automattic/mongoose#10191]
Trying to upgrade one of my project to newest mongoose. its been a while since I had time on this.

I have a mixed Value in my Schema that looks like this:
![image](https://user-images.githubusercontent.com/27885660/116546582-13a40380-a8f2-11eb-922c-1ec5bbccc72c.png)

And the I want to populate some values down the tree. params.value.optionLabels
```
OptionLabels.populate(category, {
  path: 'sections.products.params.value.optionLabels',
  select: '_id name',
  options: { lean: true }
})
```
In mongoose@5.10.2 this works fine and populates the optionLabels with _id and name from correct Model.

In mongoose@5.10.3 i get this error message
```
TypeError: Cannot create property 'optionLabels' on string 'asd'
    at lookupLocalFields (C:\Ludens\options\options-api\node_modules\mongoose\lib\helpers\populate\lookupLocalFields.js:13:15)
    at Object.exports.set (C:\Ludens\options\options-api\node_modules\mpath\lib\index.js:273:7)
    at Object.exports.set (C:\Ludens\options\options-api\node_modules\mpath\lib\index.js:222:19)
    at Object.exports.set (C:\Ludens\options\options-api\node_modules\mpath\lib\index.js:222:19)
    at Object.exports.set (C:\Ludens\options\options-api\node_modules\mpath\lib\index.js:222:19)
    at assignVals (C:\Ludens\options\options-api\node_modules\mongoose\lib\helpers\populate\assignVals.js:164:11)
    at _assign (C:\Ludens\options\options-api\node_modules\mongoose\lib\model.js:4588:3)
    at _done (C:\Ludens\options\options-api\node_modules\mongoose\lib\model.js:4437:7)
    at _next (C:\Ludens\options\options-api\node_modules\mongoose\lib\model.js:4426:7)
    at C:\Ludens\options\options-api\node_modules\mongoose\lib\model.js:4504:5
    at C:\Ludens\options\options-api\node_modules\mongoose\lib\model.js:4838:16
    at C:\Ludens\options\options-api\node_modules\mongoose\lib\helpers\promiseOrCallback.js:24:16
    at C:\Ludens\options\options-api\node_modules\mongoose\lib\model.js:4861:21
    at C:\Ludens\options\options-api\node_modules\mongoose\lib\query.js:4406:11
    at C:\Ludens\options\options-api\node_modules\kareem\index.js:135:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on Function instance at:
    at C:\Ludens\options\options-api\node_modules\mongoose\lib\model.js:4840:13
    at C:\Ludens\options\options-api\node_modules\mongoose\lib\helpers\promiseOrCallback.js:24:16
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

```

Looks like it try to create optionLabels to the 'asd' string (Image from DB end of post). Expected it to ignore this and move on to the next param items.

And this crashes my whole app, even if I have a try catch. Need to restart the server.

Added some images of how the content looks in my DB. 
![image](https://user-images.githubusercontent.com/27885660/116546311-c162e280-a8f1-11eb-9049-9e3722e5b65e.png)
![image](https://user-images.githubusercontent.com/27885660/116546459-ebb4a000-a8f1-11eb-968b-6151b551aaab.png)

**Comment by vkarpov15** [comment]
Thanks for reporting, fix will be in v5.12.8 :+1:
