### ISSUE TITLE
Cannot create Model called "Map"

### ISSUE THREAD

**Issue by jvargeaux** [Automattic/mongoose#10262]
I'm trying to create a Model for a new collection called "Maps", my model code looks like this:

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;


const MapSchema = new Schema({
  parentID: {
    type: String
  },
  authorID: {
    type: String
  },
  images: {
    type: Array
  },
  title: {
    type: String
  },
  description: {
    type: String
  },
  points: {
    type: Object
  },
  createdOn: {
    type: Date,
    default: Date.now
  },
  lastUpdated: {
    type: Date,
    default: Date.now
  },
  deletedOn: {
    type: Date
  }
});


module.exports = Map = mongoose.model('Maps', MapSchema);
```

However, I got the following error from a node module dependency called kareem:
```
if (map.has(key)) {
[0]           ^
[0] 
[0] TypeError: map.has is not a function
[0]     at get (/project/node_modules/kareem/index.js:474:11)
[0]     at Kareem.pre (/project/node_modules/kareem/index.js:391:16)
[0]     at module.exports (/project/node_modules/mongoose/lib/plugins/saveSubdocs.js:11:18)
[0]     at Schema.plugin (/project/node_modules/mongoose/lib/schema.js:1430:3)
[0]     at applyPlugins (/project/node_modules/mongoose/lib/helpers/schema/applyPlugins.js:11:14)
[0]     at Mongoose._applyPlugins (/project/node_modules/mongoose/lib/index.js:661:3)
[0]     at Mongoose.model (/project/node_modules/mongoose/lib/index.js:532:15)
[0]     at Object.<anonymous> (/project/server/models/Report.js:28:36)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0]     at Module.require (internal/modules/cjs/loader.js:952:19)
[0]     at require (internal/modules/cjs/helpers.js:88:18)
[0]     at Object.<anonymous> (/project/server/api/v1/support/newReport.js:3:16)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

Notice how above, the model is Report.js, which is a different model I'm using. However, deleting that model does nothing, so I'm not sure why it's related to this Map.js model.

Changing the name of the model to UserMap in this line solves the error:
`module.exports = UserMap = mongoose.model('Maps', MapSchema);`

Can I not name a model (not the collection) "Map"?

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');
const {Schema} = mongoose;


const MapSchema = new Schema({
  parentID: {
    type: String
  },
  authorID: {
    type: String
  },
  images: {
    type: Array
  },
  title: {
    type: String
  },
  description: {
    type: String
  },
  points: {
    type: Object
  },
  createdOn: {
    type: Date,
    default: Date.now
  },
  lastUpdated: {
    type: Date,
    default: Date.now
  },
  deletedOn: {
    type: Date
  }
});

const Map = mongoose.model('Maps', MapSchema);

async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
      });
    
    await mongoose.connection.dropDatabase();

   const entry = await Map.create({title: "Hello World"});
   console.log(entry);
}

test();
```

**Comment by jvargeaux** [comment]
@IslandRhythms Try exporting the mongoose model and using it in another module.

**Comment by IslandRhythms** [comment]
still can't reproduce, could be something else you're doing.

**Comment by vkarpov15** [comment]
@jvargeaux I think the issue is that `Map` isn't defined in this line: `module.exports = Map = mongoose.model('Maps', MapSchema)`, so this assignment overwrites the global [JavaScript `Map` class](https://masteringjs.io/tutorials/fundamentals/map). If you overwrite a core JavaScript class odds are you'll break something. Using a linter like [ESLint](https://masteringjs.io/eslint) can help catch errors like this.
