### ISSUE TITLE
Pushing a Subdocument to a Parent Document's Subdocument Array does not mark the Parent as Modified, nor apply defaults to the Subdocument

### ISSUE THREAD

**Issue by dannybster** [Automattic/mongoose#10319]
**Do you want to request a *feature* or report a *bug*?**
Bug (based on my possibly limited understanding)

**What is the current behavior?**
When creating a Parent Document with an array of Subdocuments I am not seeing behaviour consistent with my understanding of the documentation at: https://mongoosejs.com/docs/subdocs.html:
1. Pushing a child onto the Subdocument Array of an existing (just saved or just fetched) Parent Document does not mark the Parent Document as modified, meaning the updated Subdocument Array will not be saved when the Parent Document is saved
2. Pushing a child onto the Subdocument Array of a Parent Document does not apply defaults to the newly pushed Subdocument until the Parent Document is saved e.g. no _id property
3. Pushing a child onto the Subdocument Array of a Parent Document does not apply timestamps even if defined in the Subdocument Schema

**If the current behavior is a bug, please provide the steps to reproduce.**
```
// account.js
const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const apiKeySchema = require('./apikey');

const emailAddressValidationRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

const schema = new mongoose.Schema({
  emailAddress: {
    type: String,
    unique: true,
    required: true,
    match: [emailAddressValidationRegex, 'Path `emailAddress` was not in the required format.'],
  },
  password: {
    type: String,
    required: true,
    minlength: 8,
  },
  apiKeys: {
    type: [apiKeySchema],
  },
}, { timestamps: true });

schema.methods.toJSON = function toJSON() {
  const {
    id,
    emailAddress,
    createdAt,
    updatedAt,
  } = this;

  return {
    id: id.toString(),
    emailAddress,
    createdAt,
    updatedAt,
  };
};

schema.statics.authenticate = async function authenticate(emailAddress, password) {
  const account = await this.findOne({ emailAddress });
  if (account && bcrypt.compareSync(password, account.password)) {
    return account;
  }
  return null;
};

schema.pre('save', async function hashPassword() {
  const saltRounds = 10;
  this.password = await bcrypt.hash(this.password, saltRounds);
});

module.exports = schema;
```
```
// apikey.js
const mongoose = require('mongoose');
const { v4 } = require('uuid');

const schema = new mongoose.Schema({
  tag: {
    type: String,
    default: '',
  },
  key: {
    type: String,
    default: () => {
      const uuid = v4();
      return Buffer.from(uuid).toString('base64');
    },
  },
}, {
  timestamps: true,
});

schema.methods.toJSON = function toJSON() {
  const {
    id,
    tag,
    key,
    createdAt,
    updatedAt,
  } = this;

  return {
    id,
    tag,
    key,
    createdAt,
    updatedAt,
  };
};

module.exports = schema;
```
```
// example.integration.js
const mongoose = require('mongoose');
const accountSchema = require('../../src/schemas/account');

const Account = mongoose.model('account', accountSchema);

beforeEach(async () => {
  await mongoose.connect(process.env.DATABASE_CONNECTION_STRING, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    bufferCommands: false,
    bufferMaxEntries: 0,
  });
});

afterEach(async () => {
  await mongoose.disconnect();
});

it('Push example', async () => {
  const newAccount = new Account({
    emailAddress: 'ellen.ripley@weyland-yutani.space',
    password: 'Password1234',
  });

  console.log('New account', newAccount.toObject(), 'Is new:', newAccount.isNew, 'Is modified:', newAccount.isModified());

  newAccount.apiKeys.push({ tag: 'My first API Key' });

  console.log('New account', newAccount.toObject(), 'Is new:', newAccount.isNew, 'Is modified:', newAccount.isModified());

  await newAccount.save();

  console.log('Saved account', newAccount.toObject(), 'Is new:', newAccount.isNew, 'Is modified:', newAccount.isModified());

  newAccount.apiKeys.push({ tag: 'My second API Key' });

  console.log('Saved account', newAccount.toObject(), 'Is new:', newAccount.isNew, 'Is modified:', newAccount.isModified());

  await newAccount.save();

  console.log('Saved account again', newAccount.toObject(), 'Is new:', newAccount.isNew, 'Is modified:', newAccount.isModified());

  const loadedAccount = await Account.findById(newAccount.id);

  console.log('Loaded account', loadedAccount.toObject(), 'Is new:', loadedAccount.isNew, 'Is modified:', loadedAccount.isModified());
});

```
```
Console output from example.integration.js

 console.log
    New account {
      _id: 60b89a6f9375f75232cb22a0,
      emailAddress: 'ellen.ripley@weyland-yutani.space',
      password: 'Password1234',
      apiKeys: []
    } Is new: true Is modified: true

      at Object.<anonymous> (__integrations__/schemas/example.integration.js:26:11)

  console.log
    New account {
      _id: 60b89a6f9375f75232cb22a0,
      emailAddress: 'ellen.ripley@weyland-yutani.space',
      password: 'Password1234',
      apiKeys: [ { tag: 'My first API Key' } ]
    } Is new: true Is modified: true

      at Object.<anonymous> (__integrations__/schemas/example.integration.js:27:11)

  console.log
    Saved account {
      _id: 60b89a6f9375f75232cb22a0,
      emailAddress: 'ellen.ripley@weyland-yutani.space',
      password: '$2b$10$iV4xNpCGr97t1KiG5v0jueO.tgzcDgqyBXvbeMe1rGGnBIR/jiZz.',
      apiKeys: [
        {
          tag: 'My first API Key',
          _id: 60b89a6f9375f75232cb22a1,
          key: 'MTM0NjM5ZDUtMzNhOS00MWIwLWIyZWUtNzUwYzhiNDEzMDBk'
        }
      ],
      createdAt: 2021-06-03T09:01:35.958Z,
      updatedAt: 2021-06-03T09:01:35.958Z,
      __v: 0
    } Is new: false Is modified: false

      at Object.<anonymous> (__integrations__/schemas/example.integration.js:29:11)

  console.log
    Saved account {
      _id: 60b89a6f9375f75232cb22a0,
      emailAddress: 'ellen.ripley@weyland-yutani.space',
      password: '$2b$10$iV4xNpCGr97t1KiG5v0jueO.tgzcDgqyBXvbeMe1rGGnBIR/jiZz.',
      apiKeys: [
        {
          tag: 'My first API Key',
          _id: 60b89a6f9375f75232cb22a1,
          key: 'MTM0NjM5ZDUtMzNhOS00MWIwLWIyZWUtNzUwYzhiNDEzMDBk'
        },
        { tag: 'My second API Key' }
      ],
      createdAt: 2021-06-03T09:01:35.958Z,
      updatedAt: 2021-06-03T09:01:35.958Z,
      __v: 0
    } Is new: false Is modified: false

     Saved account again {
      _id: 60b89a6f9375f75232cb22a0,
      emailAddress: 'ellen.ripley@weyland-yutani.space',
      password: '$2b$10$jKy2lvj6jjkO7e42zawfPe/yevmPTyyF18Ezbmu5jdklbJS4MxOY.',
      apiKeys: [
        {
          tag: 'My first API Key',
          _id: 60b89a6f9375f75232cb22a1,
          key: 'MTM0NjM5ZDUtMzNhOS00MWIwLWIyZWUtNzUwYzhiNDEzMDBk'
        },
        { tag: 'My second API Key' }
      ],
      createdAt: 2021-06-03T09:01:35.958Z,
      updatedAt: 2021-06-03T09:01:35.958Z,
      __v: 0
    } Is new: false Is modified: false

      at Object.<anonymous> (__integrations__/schemas/example.integration.js:35:11)

  console.log
    Loaded account {
      _id: 60b89a6f9375f75232cb22a0,
      emailAddress: 'ellen.ripley@weyland-yutani.space',
      password: '$2b$10$jKy2lvj6jjkO7e42zawfPe/yevmPTyyF18Ezbmu5jdklbJS4MxOY.',
      apiKeys: [
        {
          tag: 'My first API Key',
          _id: 60b89a6f9375f75232cb22a1,
          key: 'MTM0NjM5ZDUtMzNhOS00MWIwLWIyZWUtNzUwYzhiNDEzMDBk'
        }
      ],
      createdAt: 2021-06-03T09:01:35.958Z,
      updatedAt: 2021-06-03T09:01:35.958Z,
      __v: 0
    } Is new: false Is modified: false

      at Object.<anonymous> (__integrations__/schemas/example.integration.js:37:11)
```

**What is the expected behavior?**
I would expect (again based upon my understanding of https://mongoosejs.com/docs/subdocs.html) that pushing to a Subdocument Array:
- Marks the Parent as modified
- Applies the defaults to the newly pushed Subdocument
- Applies the _id property to the newly pushed Subdocument
- Applies timestamps (if defined in the Subdocument Schema) to the Subdocument when saved

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose version: 5.12.12
Node version: 12.16.2
MongoDB version: 4.2.8

**Comment by dannybster** [comment]
I appreciate there might be more than one issue here so I am happy to raise multiple issues (if my understanding is correct and this is indeed a bug). Also given the complicated nature of the report above if you require a Docker image including the single test case above I can provide that.

**Comment by dannybster** [comment]
Possibly also worth noting that is I console log whether the subdoc is new after pushing it i.e.
```
console.log('Is subdoc new', newAccount.apiKeys[0].isNew);
```
I get
```
Is subdoc new undefined
```

Suggesting that the push just pushed a plain old object?

**Comment by dannybster** [comment]
I've resolved this, it was a problem in my test environment:

Because I perform some caching in some of my modules under test I was resetting the module cache before each test which was causing the check `if (doc && doc instanceof Document)` in documentarray.js to fail as Document was an instance of a Document from a previous time hence the parent and schema symbols were never being set in 

```
  if (doc && doc instanceof Document) {
    arr[arrayParentSymbol] = doc;
    arr[arraySchemaSymbol] = doc.schema.path(path);
```

Apologies for the spurious bug report and keep up the good work!
