### ISSUE TITLE
this error is showing while saving data in contacts model

### ISSUE THREAD

**Issue by arunsingh28** [Automattic/mongoose#10341]
## code

```
const _contact = require('../Models/Contact')
const Mailer = require('../utils/Mailer')
const { contact } = require('../utils/message')

/*
    @method   : POST
    @desc     : handle contact query module
    @address: : /api/contact  
*/
exports.Contact = async (req, res, next) => {
    const { name, message, email } = req.body
    try {
        if (name === '' || email === '' || message === '') {
            return res.status(404).json({ status: 'error', msg: 'Please fill all detail' })
        }
        const query = await _contact({
            name, message, email
        })
        try {
            await query.save()
            await Mailer(email, contact, name).then(() => {
                console.log('mail send')
            })
            return res.status(200).json({ status: 'ok', msg: 'Query Submited' })
        } catch (error) {
            return res.status(404).json({ status: 'error', msg: error })
        }
    } catch (error) {
        console.log('From catch blog:', error)
        return res.status(404).json({ status: 'error', msg: 'Server Error' + error })
    }
}
```

## error 

```
MongooseError: Operation `contacts.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/arun.singh28/Documents/Alpha/help-strtup/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by IslandRhythms** [comment]
locally or on a server?

**Comment by arunsingh28** [comment]
this error is showing on both

**Comment by IslandRhythms** [comment]
are you connected to a mongodb cluster?

**Comment by arunsingh28** [comment]
**YES**

**Comment by IslandRhythms** [comment]
Did you whitelist your ip?

**Comment by arunsingh28** [comment]
No 
it always work fine without whitelisting the ip but this time it is not working i'll try to whitelisting my ip and thanks for your help.

**Comment by tbhaxor** [comment]
@arunsingh28 I was checking your code, it has `await _contact` rather than `new _contact`. A model is a class and it must be instantiated using `new` keyword. Confirm it at your end. Here you can see the diffed changed

```diff
- const query = await _contact({
+ const query = new _contact({
```

It is on line number 16 in the snippet you have provided

**Comment by arunsingh28** [comment]
thanks @tbhaxor now its working👍
