### ISSUE TITLE
mongoose.createConnection TypeError: Cannot read property 'prepare' of undefined

### ISSUE THREAD

**Issue by speedtreammanga** [Automattic/mongoose#10377]
**Do you want to request a *feature* or report a *bug*?** bug
bug

**What is the current behavior?**
I'm getting this error:
```
/app/express/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:182
nodejs_1         |     authProvider.prepare(handshakeDoc, authContext, callback);
nodejs_1         |                  ^
nodejs_1         | TypeError: Cannot read property 'prepare' of undefined
nodejs_1         |     at prepareHandshakeDocument (/app/express/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:182:18)
nodejs_1         |     at performInitialHandshake (/app/express/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:87:3)
nodejs_1         |     at /app/express/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:36:5
nodejs_1         |     at callback (/app/express/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:280:5)
nodejs_1         |     at Socket.connectHandler (/app/express/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:325:5)
nodejs_1         |     at Object.onceWrapper (node:events:513:28)
nodejs_1         |     at Socket.emit (node:events:394:28)
nodejs_1         |     at Socket.emit (node:domain:470:12)
nodejs_1         |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1119:10)
```
on this call: [https://github.com/speedtreammanga/read-latte/blob/7947c7ef29667d681ffdc60dc377b7ab4781d15e/express/src/config/connection/connection.ts#L21](https://github.com/speedtreammanga/read-latte/blob/7947c7ef29667d681ffdc60dc377b7ab4781d15e/express/src/config/connection/connection.ts#L21)

**If the current behavior is a bug, please provide the steps to reproduce.**
repo: [https://github.com/speedtreammanga/read-latte](https://github.com/speedtreammanga/read-latte)
steps: 
- clone repo;
- create a .env file at the root of the project with the environment variables used in my [docker-compose file](https://github.com/speedtreammanga/read-latte/blob/master/docker-compose.yml);
- run `cd <project root>`;
- run `docker-compose build`;
- run `docker-compose run`;

My [tsconfig.json](https://github.com/speedtreammanga/read-latte/blob/master/express/tsconfig.json) file

**What is the expected behavior?**
mongoose should be able to connect to my mongodb without any issue.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- nodejs: using docker image [node:16-alpine](https://github.com/nodejs/docker-node/blob/8d77359e4f20c45829f7d7399b76a5eb99eff4da/16/alpine3.13/Dockerfile)
- mongoose: `package.json => 5.12.14` | `console.log(mongoose.verison) => 5.12.13`
- mongodb: using the [mongo docker image](https://hub.docker.com/_/mongo?tab=description&page=1&ordering=last_updated)

**Comment by speedtreammanga** [comment]
@IslandRhythms did you try with an `.env` file with these variables?

```.env
NODE_ENV=development
NODE_PORT=8080
NODE_SECRET=dev_demo_node_secret
NODE_SESSION_SECRET=dev_demo_node_session_secret

MONGO_DB_PORT=27017
MONGO_DB_MAIN=readlatte
MONGO_DB_URI=mongodb://mongo:27017/
MONGO_ROOT_USERNAME=dev_demo_user
MONGO_ROOT_PASSWORD=dev_demo_pwd

MONGO_EXPRESS_ADMINUSERNAME=dev_demo_user
MONGO_EXPRESS_ADMINPASSWORD=dev_demo_pwd
```

**Comment by IslandRhythms** [comment]
I connected to a live database just fine, something is wrong with your setup. I think specifically it is your connection string.

**Comment by speedtreammanga** [comment]
How did you managed to connect, do you have mongodb installed on your machine or ran `docker run ... mongo` ?
Did you do anything different than my reproduce steps ?

**Comment by speedtreammanga** [comment]
@IslandRhythms I have found the issue, it's a mistake on my part.
In my `config.ts` file I'm referencing `process.env.MONGO_USERNAME` and  `process.env.MONGO_PASSWORD` but in my docker-compose I declare them as `MONGO_ROOT_USERNAME` & `MONGO_ROOT_PASSWORD`
jeez, took me forever.

**Comment by vkarpov15** [comment]
We'll see if we can improve this error message, this error message is quite unhelpful.

**Comment by vkarpov15** [comment]
Opened an issue in the MongoDB driver :point_up: Going to remove this from our milestones but keep it open so we remember to make a note when the MongoDB driver team makes a new release.

**Comment by Uzlopak** [comment]
@vkarpov15 
I guess this issue can be closed.
