### ISSUE TITLE
[Bug] updateOne validator throws an error with ESM but not CommonJS

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#10384]
In mongoose 5.12.14
### 10384.js
```js
import mongoose from 'mongoose';
const { Schema } = mongoose;


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  mongoose.set('runValidators', true);

  const userSchema = new Schema({
    age: {
      type: Number,
      required () {
        return this.countryCode;
      }
    },
    countryCode: String
  });

  const User = mongoose.model('User', userSchema);

  const user = await User.create({ age: 26 });
  await User.updateOne({ _id: user._id }, { age: 20 });

  console.log(mongoose.version);
  console.log('All assertions passed.');
}
```
### Output
```
> node 10384.js
Error: Validation failed: age: Cannot read property 'countryCode' of null
    at ValidationError.inspect (.\node_modules\mongoose\lib\error\validation.js:47:26)
    at internal/per_context/primordials.js:23:32
    at formatValue (internal/util/inspect.js:775:19)
    at inspect (internal/util/inspect.js:337:10)
    at formatWithOptionsInternal (internal/util/inspect.js:2008:40)
    at formatWithOptions (internal/util/inspect.js:1890:10)
    at console.value (internal/console/constructor.js:330:14)
    at console.warn (internal/console/constructor.js:363:61)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errors: {
    age: ValidatorError: Cannot read property 'countryCode' of null
        at validate (.\node_modules\mongoose\lib\schematype.js:1270:13)
        at .\node_modules\mongoose\lib\schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaNumber.SchemaType.doValidate (.\node_modules\mongoose\lib\schematype.js:1198:14)
        at .\node_modules\mongoose\lib\helpers\updateValidators.js:159:22
        at module.exports (.\node_modules\mongoose\lib\helpers\updateValidators.js:210:7)
        at .\node_modules\mongoose\lib\query.js:3919:9
        at promiseOrCallback (.\node_modules\mongoose\lib\helpers\promiseOrCallback.js:10:12)
        at model.Query.validate (.\node_modules\mongoose\lib\query.js:3914:10)
        at .\node_modules\kareem\index.js:370:33
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      properties: [Object],
      kind: 'required',
      path: 'age',
      value: 20,
      reason: TypeError: Cannot read property 'countryCode' of null
          at required (file:///E:/Info/localhost/Web%20Development/NodeJS/speero-backend/test.js:21:21)
          at requiredValidator (.\node_modules\mongoose\lib\schematype.js:1001:23)
          at .\node_modules\mongoose\lib\schematype.js:1233:24
          at Array.forEach (<anonymous>)
          at SchemaNumber.SchemaType.doValidate (.\node_modules\mongoose\lib\schematype.js:1198:14)
          at .\node_modules\mongoose\lib\helpers\updateValidators.js:159:22
          at module.exports (.\node_modules\mongoose\lib\helpers\updateValidators.js:210:7)
          at .\node_modules\mongoose\lib\query.js:3919:9
          at promiseOrCallback (.\node_modules\mongoose\lib\helpers\promiseOrCallback.js:10:12)
          at model.Query.validate (.\node_modules\mongoose\lib\query.js:3914:10)
          at .\node_modules\kareem\index.js:370:33
          at processTicksAndRejections (internal/process/task_queues.js:75:11),
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Validation failed'
}
```

However, this passes successfully with CommonJS, just by changing the first line and the file extension to .cjs, things pass (I think false-positive)
10384.cjs
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  mongoose.set('runValidators', true);

  const userSchema = new Schema({
    age: {
      type: Number,
      required () {
        return this.countryCode;
      }
    },
    countryCode: String
  });

  const User = mongoose.model('User', userSchema);

  const user = await User.create({ age: 26 });
  await User.updateOne({ _id: user._id }, { age: 20 });

  console.log(mongoose.version);
  console.log('All assertions passed.');
}
```

### Output
```
> node 10384.cjs
5.12.14
All assertions passed.
```

**Comment by IslandRhythms** [comment]
**.mjs**
```javascript
import mongoose from 'mongoose';
const { Schema } = mongoose;


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  mongoose.set('runValidators', true);

  const userSchema = new Schema({
    age: {
      type: Number,
      required () {
        return this.countryCode;
      }
    },
    countryCode: String
  });

  const User = mongoose.model('User', userSchema);

  const user = await User.create({ age: 26 });
  await User.updateOne({ _id: user._id }, { age: 20 });

  console.log(mongoose.version);
  console.log('All assertions passed.');
}
```

**.js**
```
const mongoose = require('mongoose');
const { Schema } = mongoose;


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  mongoose.set('runValidators', true);

  const userSchema = new Schema({
    age: {
      type: Number,
      required () {
        return this.countryCode;
      }
    },
    countryCode: String
  });

  const User = mongoose.model('User', userSchema);

  const user = await User.create({ age: 26 });
  await User.updateOne({ _id: user._id }, { age: 20 });

  console.log(mongoose.version);
  console.log('All assertions passed.');
}
```

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior. The issue is that, in your CommonJS script, you're not setting ['use strict'](https://masteringjs.io/tutorials/fundamentals/strict#this-defaults-to-undefined), which means `this` is set to `global` in your update validator. Read more about [update validators and `this`](https://mongoosejs.com/docs/validation.html#update-validators-and-this).

Our recommended workaround is to set `context: 'query'` and use `this.get('countryCode')` instead of `this.countryCode` as shown below:

```javascript
  const userSchema = new Schema({
    age: {
      type: Number,
      required () {
        return this.get('countryCode'); // <-- In query middleware, this will check if `$set.countryCode` is truthy
      }
    },
    countryCode: String
  });

  const User = mongoose.model('User', userSchema);

  const user = await User.create({ age: 26 });
  await User.updateOne({ _id: user._id }, { age: 20 }, { context: 'query' }); // <-- Make `this` equal to the query in `updateOne()` middleware
```

Here's a little more about the [`Query#get()` function](https://mongoosejs.com/docs/api/query.html#query_Query-get).

I know the `context: 'query'` thing is annoying. We're getting rid of that in 6.0 with #8395.
