### ISSUE TITLE
model.collection.aggregate(...).explain is not a function

### ISSUE THREAD

**Issue by sorin21** [Automattic/mongoose#10521]
I searched a lot and I tried a lot, but still I got the same error for explain() in aggregation: explain si not a function.

"mongoose": "^5.13.5"

On this little code I put explain() in the end.

```
const mongoose = require("mongoose");
const Schema = mongoose.Schema;
mongoose.set("debug", true);

mongoose
  .connect("mongodb://localhost:27017/mongooseDatabase", {
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false,
    useUnifiedTopology: true,
  })
  .then(() => console.log("MongoDB Connected!"))
  .catch((error) => console.log("There was an error: ", error));

let schema = new mongoose.Schema(
  {
    name: String,
    sales: Number,
    month: Number,
  },
  {}
);

let Sales = mongoose.model("Sales", schema);

Sales.find({}).exec((err, res) => {
  if (err) throw err;
  console.log(res);
});

Sales.aggregate([
  { $match: { name: "Tom" } },
  { $project: { _id: 0, name: 1, sales: 1 } },
  {
    $group: {
      _id: "$name",
      avg_sales: { $avg: "$sales" },
      total_sales: { $sum: "$sales" },
    },
  },
]).explain();
```

Or like this:

```
Sales.aggregate()
  .match({ name: "Jerry" })
  .project({ _id: 0, name: 1, sales: 1 })
  .group({
    _id: "$name",
    total_sales: { $sum: "$sales" },
    avg_sales: { $avg: "$sales" },
  })
.explain();
```

And I got the same error:

```
D:\Programming\myCode\01.mongoose\node_modules\mongoose\lib\aggregate.js:723
        explain((error, result) => {
        ^

TypeError: model.collection.aggregate(...).explain is not a function
    at D:\Programming\myCode\01.mongoose\node_modules\mongoose\lib\aggregate.js:723:9
    at D:\Programming\myCode\01.mongoose\node_modules\kareem\index.js:23:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

On mongoose docs, for aggregate you have this example:
`Model.aggregate(..).explain(callback)`

I tried to add a call back inside explain but I got the same error.

Please tell me, where is the problem?

**Comment by IslandRhythms** [comment]
```
const mongoose = require("mongoose");
const Schema = mongoose.Schema;
mongoose.set("debug", true);

let schema = new mongoose.Schema(
    {
      name: String,
      sales: Number,
      month: Number,
    },
    {}
  );

  
  let Sales = mongoose.model("Sales", schema);
async function run() {
    await mongoose
    .connect("mongodb://localhost:27017/mongooseDatabase", {
      useNewUrlParser: true,
      useCreateIndex: true,
      useFindAndModify: false,
      useUnifiedTopology: true,
    })
    .then(() => console.log("MongoDB Connected!"))
    .catch((error) => console.log("There was an error: ", error));
  
  await Sales.create({
      name: 'Hello',
      sales: 23,
      month: 11
  });

  await Sales.create({
    name: 'Tom',
    sales: 23,
    month: 11
});

  
  await Sales.find({}).exec((err, res) => {
    if (err) throw err;
    console.log(res);
  });

  await Sales.aggregate([
    { $match: { name: "Tom" } },
    { $project: { _id: 0, name: 1, sales: 1 } },
    {
      $group: {
        _id: "$name",
        avg_sales: { $avg: "$sales" },
        total_sales: { $sum: "$sales" },
      },
    },
  ]).explain();
  
  await Sales.aggregate([]).match({name: 'Hello'}).explain();
}
run();
```

**Comment by sorin21** [comment]
@IslandRhythms  I commented this find()

```
// await Sales.find({}).exec((err, res) => {
  //   if (err) throw err;
  //   console.log(res);
  // });
```

to see better the output and in the terminat I don't see anythig beside this:
```
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node 07.agg4.js`
MongoDB Connected!
```

For example in this code
```
let schema = mongoose.Schema(
  {
    brand: String,
    model: String,
    year: Number,
    location: String,
  },
  {}
);

let Car = mongoose.model("Car", schema);

Car.insertMany([
  { brand: "Mercedez", model: "Benz", year: 2018 },
  { brand: "Toyota", model: "Camry", year: 2012 },
]);


Car
  .where("brand")
  .in(["Toyota", "Lexus"])
  .select("-_id -__v")
  .sort({ year: 1 })
  .explain("executionStats")
  .exec((err, res) => {
    console.log(res);
  });
```

I get this in terminal:

```
MongoDB Connected!
[
  {
    explainVersion: '1',
    queryPlanner: {
      namespace: 'mongooseDatabase.cars',
      indexFilterSet: false,
      parsedQuery: [Object],
      maxIndexedOrSolutionsReached: false,
      maxIndexedAndSolutionsReached: false,
      maxScansToExplodeReached: false,
      winningPlan: [Object],
      rejectedPlans: [Array]
    },
    executionStats: {
      executionSuccess: true,
      nReturned: 2,
      executionTimeMillis: 0,
      totalKeysExamined: 3,
      totalDocsExamined: 2,
      executionStages: [Object]
    },
    command: {
      find: 'cars',
      filter: [Object],
      sort: [Object],
      projection: [Object],
      returnKey: false,
      showRecordId: false,
      '$db': 'mongooseDatabase'
    },
    serverInfo: {
      host: 'LAPTOP-1BAGBCKA',
      port: 27017,
      version: '5.0.0',
      gitVersion: '1184f004a99660de6f5e745573419bda8a28c0e9'
    },
    serverParameters: {
      internalQueryFacetBufferSizeBytes: 104857600,
      internalQueryFacetMaxOutputDocSizeBytes: 104857600,
      internalLookupStageIntermediateDocumentMaxSizeBytes: 104857600,
      internalDocumentSourceGroupMaxMemoryBytes: 104857600,
      internalQueryMaxBlockingSortMemoryUsageBytes: 104857600,
      internalQueryProhibitBlockingMergeOnMongoS: 0,
      internalQueryMaxAddToSetBytes: 104857600,
      internalDocumentSourceSetWindowFieldsMaxMemoryBytes: 104857600
    },
    ok: 1
  }

```

Because I want to see this part:
     ```
 nReturned: 2,
      executionTimeMillis: 0,
      totalKeysExamined: 3,
      totalDocsExamined: 2,
```

With the code that you modified I don't see anything like this. If I say, did something wrong please correct me.

**Comment by IslandRhythms** [comment]
> executionStats: {
      executionSuccess: true,
      nReturned: 2,
      executionTimeMillis: 0,
      totalKeysExamined: 3,
      totalDocsExamined: 2,
      executionStages: [Object]
    },

**Comment by sorin21** [comment]
You got this

```
executionStats: {
executionSuccess: true,
nReturned: 2,
executionTimeMillis: 0,
totalKeysExamined: 3,
totalDocsExamined: 2,
executionStages: [Object]
},
```

on this query?

```
await Sales.aggregate([
    { $match: { name: "Tom" } },
    { $project: { _id: 0, name: 1, sales: 1 } },
    {
      $group: {
        _id: "$name",
        avg_sales: { $avg: "$sales" },
        total_sales: { $sum: "$sales" },
      },
    },
  ]).explain();
```

**Comment by sorin21** [comment]
Everything that I put here was from mongoose not mongodb. The second code with Cars is still from mongoose, but I didn't repeat the top code with require mongoose, connections, etc.

So all the code and each output is from mongoose code. I don't understand how come you thing that is just mongo. 

If you mean the database, yes, database is locally, not on cloud, but beside that everything si pure mongoose code.

In each code that I put, you have:
require mongoose
mongoose connect
create schema
create model

and then a just a query, 1st with aggregate and then, in 2nd example with where().

And yes, this ouput is from running the Car model, that is pure mongoose code:

```
[
  {
    explainVersion: '1',
    queryPlanner: {
      namespace: 'mongooseDatabase.cars',
      indexFilterSet: false,
      parsedQuery: [Object],
      maxIndexedOrSolutionsReached: false,
      maxIndexedAndSolutionsReached: false,
      maxScansToExplodeReached: false,
      winningPlan: [Object],
      rejectedPlans: [Array]
    },
    executionStats: {
      executionSuccess: true,
      nReturned: 2,
      executionTimeMillis: 0,
      totalKeysExamined: 3,
      totalDocsExamined: 2,
      executionStages: [Object]
    },
    command: {
      find: 'cars',
      filter: [Object],
      sort: [Object],
      projection: [Object],
      returnKey: false,
      showRecordId: false,
      '$db': 'mongooseDatabase'
    },
    serverInfo: {
      host: 'LAPTOP-1BAGBCKA',
      port: 27017,
      version: '5.0.0',
      gitVersion: '1184f004a99660de6f5e745573419bda8a28c0e9'
    },
    serverParameters: {
      internalQueryFacetBufferSizeBytes: 104857600,
      internalQueryFacetMaxOutputDocSizeBytes: 104857600,
      internalLookupStageIntermediateDocumentMaxSizeBytes: 104857600,
      internalDocumentSourceGroupMaxMemoryBytes: 104857600,
      internalQueryMaxBlockingSortMemoryUsageBytes: 104857600,
      internalQueryProhibitBlockingMergeOnMongoS: 0,
      internalQueryMaxAddToSetBytes: 104857600,
      internalDocumentSourceSetWindowFieldsMaxMemoryBytes: 104857600
    },
    ok: 1
  }
```


Believe me I put this question, that I that you don't understand it, to a lot of people, professors, that teach mongoose and each one told me that explain() function, for mongoose, on aggregation doesn't work.

That is why I put you a little code thinking that you can help me.

Please tell me if I made myself clear, or if you need more details.

**Comment by IslandRhythms** [comment]
```
  console.log(await Sales.aggregate([
    { $match: { name: "Tom" } },
    { $project: { _id: 0, name: 1, sales: 1 } },
    {
      $group: {
        _id: "$name",
        avg_sales: { $avg: "$sales" },
        total_sales: { $sum: "$sales" },
      },
    },
  ]).explain());
  
  console.log(await Sales.aggregate([]).match({name: 'Hello'}).explain());
```
Just wrap those statements in console.logs and it will show up

**Comment by sorin21** [comment]
Ooo, I see, with console.log I have an output for explain(). I thought that explain() will show something exactly like exec(). 

This is realy strange that nobody, from who I asked, thought about this way, to put in console the whole code, to have the ouput from explain(). 

I mean even if you search on internet explain() in aggregation, for mongosee is like... non-existent. Beside that single line on mongoose documentation
Model.aggregate(..).explain(callback)

you don't find anyone saying something good.

Thank you :).
