### ISSUE TITLE
Issue connecting to localhost mongod replica set from dockerized nodejs app on macOS

### ISSUE THREAD

**Issue by smathema** [Automattic/mongoose#10534]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm having issue connecting to localhost mongodb replica set from a dockerized nodejs app on MacOS. The connection was successful when connection string used was *mongodb://host.docker.internal:27017/test*, but as soon as I change the connection string  to replica set , using the *replicaSet* option I get an error in connection with the connection string *mongodb://host.docker.internal:27017/test?replicaSet=rs1* OR *mongodb://host.docker.internal:27017,host.docker.internal:27018/test*

**If the current behavior is a bug, please provide the steps to reproduce.**
Step1. Create two *mongod* process
*shell command for mongod*
```
mkdir -p /tmp/data/db1
mkdir -p /tmp/data/db2

mongod --port 27017 --dbpath /tmp/data/db1 --logpath /tmp/data/db1.log --fork --replSet rs1
mongod --port 27018 --dbpath /tmp/data/db2 --logpath /tmp/data/db2.log --fork --replSet rs1
```

Step2. Create a replica set with it.
*shell command for creating replica set*
```mongo --port 27017
rs.initiate()
rs.add("127.0.0.1:27018")
exit
```

Step3. Connect to the replica set from a dockerized nodejs app using mongoose with connection string 
*app.js*
```
const mongoose = require("mongoose");

// PASS message with running just `node app.js`
// const connString = "mongodb://localhost:27017/test?replicaSet=rs1"

// PASS message in docker logs
// const connString = "mongodb://host.docker.internal:27017/test"

// FAIL message in docker logs
const connString = "mongodb://host.docker.internal:27017/test?replicaSet=rs1"

mongoose.connect(connString);

mongoose.connection.on("connected", () => {
    console.log(`\nConnected to ${connString}.\n`);
});

mongoose.connection.on("error", (err) => {
    console.log(`\nConnection to ${connString} failed: ${err}.\n`);
});

mongoose.connection.on("disconnected", () => {
    console.log(`\nDisconnected from ${connString}.\n`);
});
```

*app.js dependency*
```
npm init -y
npm install mongoose --save
```

*Dockerfile*
```
FROM node:14
COPY . .
RUN npm install
CMD ["node", "app.js"]
```

*Build and run docker*
```
docker build . -t sample_app:latest && docker run --network="host" --name sample_app -d sample_app

docker logs --follow sample_app
```

**What is the expected behavior?**
It should connect successfully with message:
`Connected to mongodb://host.docker.internal:27017/test?replicaSet=rs1`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js 14
Mongoose 5.13.5
MongoDB v3.6.3
Docker version 20.10.7

**Comment by IslandRhythms** [comment]
If I remember correctly you can't use replica set locally.

**Comment by smathema** [comment]
> If I remember correctly you can't use replica set locally.

@IslandRhythms I'm able to connect to the replica set running locally using the connection string `mongodb://localhost:27017/test?replicaSet=rs1` by running the node app directly without a docker but it's inside docker that it is not willing to take the `replicaSet` option to connect to replica set but is successfully connecting to individual replica member.

**Comment by Rossh87** [comment]
@smathema host.docker.internal appears to be a [workaround for Windows](https://docs.docker.com/docker-for-windows/networking/#use-cases-and-workarounds).  On Linux, since you're specifying the Docker container's network as "host", you can just use "localhost" in the connection string.  I would assume it's the same on MacOS.  I've duplicated your setup as closely as possible (see discrepancies below), swapping out "host.docker.internal" for "localhost", and my container connects to the replica set without any trouble.

Discrepancies:
OS: Ubuntu 18.04.5 LTS
Docker: 20.10.08

Here's the docker log:
```
(node:1) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

Connected to mongodb://localhost:27017/test?replicaSet=rs1.
```

And here's the relevant database log:
```
2021-08-05T13:17:10.808-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:51696 #6 (3 connections now open)
2021-08-05T13:17:10.809-0500 I NETWORK  [conn6] received client metadata from 127.0.0.1:51696 conn: { driver: { name: "nodejs", version: "3.6.10" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.0-80-generic" }, platform: "'Node.js v14.17.4, LE (legacy)" }
2021-08-05T13:17:32.481-0500 I NETWORK  [thread3] Starting new replica set monitor for rs1/localhost:27017,localhost:27018
2021-08-05T13:17:32.483-0500 I NETWORK  [thread3] Successfully connected to localhost:27017 (37 connections now open to localhost:27017 with a 0 second timeout)
2021-08-05T13:17:32.483-0500 I NETWORK  [thread3] scoped connection to localhost:27017 not being returned to the pool
etc...
```

**Comment by smathema** [comment]
@Rossh87 I think this could be macOS specific, as building the docker without --network="host", I'm able to connect with to individual mongod node with `host.docker.internal` in connection string but not to the `replicaSet=rs1`. Also `host.docker.internal` is also a [workaround for mac](https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds) for connecting to localhost services.

`docker build . -t sample_app:latest && docker run --name sample_app -d sample_app`

```(node:1) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

Connected to mongodb://host.docker.internal:27017/test.
```

But using `localhost` with or without --network="host" doesn't work:

```(node:1) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

Disconnected from mongodb://localhost:27017/test.


Connection to mongodb://localhost:27017/test failed: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  name: 'MongoNetworkError'
}].

(node:1) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (events.js:400:28)
    at /node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /node_modules/mongodb/lib/core/connection/pool.js:999:11
    at /node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/node_modules/mongodb/lib/core/connection/connect.js:283:5)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:313:7)
    at Object.onceWrapper (events.js:520:26)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And yes I'm trying to connect to a correct replicaSetName:

```sample-app $ mongo --host "rs1/127.0.0.1:27017"
MongoDB shell version v3.6.3
connecting to: mongodb://127.0.0.1:27017/?replicaSet=rs1
2021-08-05T14:50:28.739-0700 I NETWORK  [thread1] Starting new replica set monitor for rs1/127.0.0.1:27017
2021-08-05T14:50:28.742-0700 I NETWORK  [thread1] Successfully connected to 127.0.0.1:27017 (1 connections now open to 127.0.0.1:27017 with a 5 second timeout)
2021-08-05T14:50:28.742-0700 I NETWORK  [thread1] changing hosts to rs1/127.0.0.1:27018,localhost:27017 from rs1/127.0.0.1:27017
2021-08-05T14:50:28.743-0700 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:27017 (1 connections now open to localhost:27017 with a 5 second timeout)
2021-08-05T14:50:28.744-0700 I NETWORK  [thread1] Successfully connected to 127.0.0.1:27018 (1 connections now open to 127.0.0.1:27018 with a 5 second timeout)
MongoDB server version: 3.6.3
Server has startup warnings: 
2021-08-05T14:25:47.149-0700 I CONTROL  [initandlisten] 
2021-08-05T14:25:47.149-0700 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] 
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2021-08-05T14:25:47.150-0700 I CONTROL  [initandlisten] 
rs1:PRIMARY> 
```

I've seen one other person asking about this issue on stackoverflow too but there's no solution/response to it

**Comment by Rossh87** [comment]
@smathema You're right re: the host name workaround, I should have checked if that was a thing for Mac too.  What do the Mongo logs in `/tmp/data` say about failed attempts to connect to the replicas?  Does it make a difference if you specify both Mongo instances in the connection string, [like this](https://docs.mongodb.com/drivers/node/fundamentals/connection/#connect-to-a-replica-set)?  Finally, does it make a difference if you remove Mongoose from the containerized app and try connecting with the [nodejs driver](https://docs.mongodb.com/drivers/node/current/quick-start/#add-mongodb-as-a-dependency)?

**Comment by vkarpov15** [comment]
With replica sets, you need to make sure the `hostname` that each MongoDB server is on is something that your app server can resolve. See [docs](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). When you're connecting to `mongodb://host.docker.internal:27017/test`, Mongoose treats that as connecting to a standalone, not a replica set.

To figure out what the self-reported host names are, connect to your replica set using the MongoDB shell and run `rs.status()`.
