### ISSUE TITLE
 Can't set discriminator key "__t"

### ISSUE THREAD

**Issue by Enado95** [Automattic/mongoose#10540]
Node version `14.15.0`
Mongoose version `5.13.5`

I get the error below when trying to save a discriminator, any idea as to what could be the root cause? 

**Model**
```
const mongoose = require('mongoose')
const formSchema = new mongoose.Schema(
  {
    requestedBy: String,
    receiver: String,
    sla: String
  },
  {
    collation: { locale: 'en_US', strength: 1 },
    timestamps: { createdAt: 'dateReceived', updatedAt: 'updateAt' }
  }
)
const options = { discriminatorKey: 'kind' }

const analyticsRequestSchema = new mongoose.Schema({
  formType: Joi.string(),
  status: { type: String, default: 'Received' },
  dateActioned: { type: Date, default: '' },
  priority: { type: String, default: '' },
  assignedTo: { type: String, default: '' },
  reason: String,
  username: String,
  value: String,
  fullName: String,
  location: String,
  email: String,
  users: String,
  expectedResolutionDate: { type: Date, default: '' },
  adminComment: { type: String, default: '' }
})

exports.AnalyticsRequest = Form.discriminator(
  'analyticsRequest',
  analyticsRequestSchema,
  options
)
```

```
 validation failed: __t: Can't set discriminator key "__t"
    at ValidationError.inspect (/app/node_modules/mongoose/lib/error/validation.js:47:26)
    at internal/per_context/primordials.js:23:32
    at formatValue (internal/util/inspect.js:774:19)
    at inspect (internal/util/inspect.js:336:10)
    at formatWithOptionsInternal (internal/util/inspect.js:2006:40)
    at formatWithOptions (internal/util/inspect.js:1888:10)
    at console.value (internal/console/constructor.js:320:14)
    at console.warn (internal/console/constructor.js:353:61)
    at /app/src/controllers/form.js:81:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async exports.createForm (/app/src/controllers/form.js:31:3) {
  errors: {
    __t: Error: Can't set discriminator key "__t"
        at model.set (/app/node_modules/mongoose/lib/helpers/model/discriminator.js:132:15)
        at SchemaString.SchemaType._applySetters (/app/node_modules/mongoose/lib/schematype.js:1093:20)
        at SchemaString.SchemaType.applySetters (/app/node_modules/mongoose/lib/schematype.js:1117:16)
        at SchemaString.SchemaType.getDefault (/app/node_modules/mongoose/lib/schematype.js:1070:25)
        at $__applyDefaults (/app/node_modules/mongoose/lib/document.js:438:24)
        at model.Document (/app/node_modules/mongoose/lib/document.js:138:7)
        at model.Model (/app/node_modules/mongoose/lib/model.js:105:12)
        at new model (/app/node_modules/mongoose/lib/model.js:4911:15)
        at exports.createForm (/app/src/controllers/form.js:30:23)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at next (/app/node_modules/express/lib/router/route.js:137:13)
        at module.exports (/app/src/utils/checkFormType.js:5:5)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        at next (/app/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
  },

```

**Comment by Enado95** [comment]
Had the options in the wrong place
