### ISSUE TITLE
Deprecation warnings of mongodb driver

### ISSUE THREAD

**Issue by fluidblue** [Automattic/mongoose#10650]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Deprecation warnings are printed to the node output.

**If the current behavior is a bug, please provide the steps to reproduce.**

It is not clear, from where the bug is triggered, because it is not directly triggered from my code. However, stack traces are given:

```
(node:5206) [MONGODB DRIVER] Warning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
    at emitWarning (/[...]/node_modules/mongodb/lib/utils.js:1109:20)
    at Object.emitWarningOnce (/[...]/node_modules/mongodb/lib/utils.js:1122:16)
    at Collection.update (/[...]/node_modules/mongodb/lib/collection.js:457:17)
    at NativeCollection.<computed> [as update] (/[...]/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:191:33)
    at NodeCollection.update (/[...]/node_modules/mquery/lib/collection/node.js:64:19)
    at model.Query._updateThunk (/[...]/node_modules/mongoose/lib/query.js:3993:23)
    at model.Query.<anonymous> (/[...]/node_modules/mongoose/lib/query.js:4031:23)
    at model.Query._wrappedThunk [as _execUpdate] (/[...]/node_modules/mongoose/lib/helpers/query/wrapThunk.js:27:8)
    at /[...]/node_modules/kareem/index.js:370:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
```
(node:5206) [MONGODB DRIVER] Warning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
    at emitWarning (/[...]/node_modules/mongodb/lib/utils.js:1109:20)
    at Object.emitWarningOnce (/[...]/node_modules/mongodb/lib/utils.js:1122:16)
    at Collection.remove (/[...]/node_modules/mongodb/lib/collection.js:472:17)
    at NativeCollection.<computed> [as remove] (/[...]/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:191:33)
    at NodeCollection.remove (/[...]/node_modules/mquery/lib/collection/node.js:112:19)
    at model.Query.Query.remove (/[...]/node_modules/mquery/lib/mquery.js:2566:20)
    at model.Query.<anonymous> (/[...]/node_modules/mongoose/lib/query.js:2898:28)
    at model.Query._wrappedThunk [as _remove] (/[...]/node_modules/mongoose/lib/helpers/query/wrapThunk.js:27:8)
    at /[...]/node_modules/kareem/index.js:370:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**What is the expected behavior?**
No deprecation warnings should be printed on the node output.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v16.8.0
Mongoose: v6.0.3
MongoDB: v3.6.23

**Comment by IslandRhythms** [comment]
It is going to be very hard to reproduce this without seeing what is going on in your code. Can you please include a code sample that reproduces the problem you are experiencing?

**Comment by vkarpov15** [comment]
Replace `remove()` with `deleteOne()`, and `update()` with `updateOne()` to get rid of the deprecation warning.

**Comment by fluidblue** [comment]
I looked into it in more detail and found that the warnings are originating from calls to [Model.update()](https://mongoosejs.com/docs/api.html#model_Model.update) and [Model.remove()](https://mongoosejs.com/docs/api.html#model_Model.remove).

When replacing those calls with updateOne, updateMany resp. deleteOne, deleteMany, the warnings are gone.

Thanks @vkarpov15 for the hints.

Regarding the mongoose documentation:
Shouldn't there be a deprecation warning for `Model.update()` and `Model.remove()`?

**Comment by fluidblue** [comment]
I think it makes sense to mark `Model.update()` and `Model.remove()` deprecated, as `Model.count()` is.

I created a [PR](https://github.com/Automattic/mongoose/pull/10666) for this.
