### ISSUE TITLE
arrayFilters not working on nested array 6.0.4

### ISSUE THREAD

**Issue by gompa** [Automattic/mongoose#10675]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
In 6.0.4
I get an error : Error: Could not find path "comments.0.comments.0._id" in schema
In 5.18.8
It updates the nested document as expected 

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const CommentSchema = new mongoose.Schema({
  comment: String,
  comments:[this],

}, { timestamps: true });

const Comment = mongoose.model('Comment', CommentSchema);

const PostSchema = new mongoose.Schema({
  title: String,
  comments: [CommentSchema]

const Post = mongoose.model('Post', PostSchema);

  var comment = new Comment({ 
      comment: posttext,
  });

{
      "_id": "6132574321979200f70c64b0",
      "title": "sad times",
      "comments": [
              {
                      "comment": "wont work dude",
                      "comments": [
                              {
                               "comment": "you can do this, but thats it",
                               "comments": [],
                               "_id": "6132575d21979200f70c64dd"
                              }
                      ],
                      "_id": "6132574f21979200f70c64cd",
                      "updatedAt": "2021-09-03T17:11:43.102Z",
                      "createdAt": "2021-09-03T17:11:43.102Z"
              }
      ],
      "createdAt": "2021-09-03T17:11:31.968Z",
      "updatedAt": "2021-09-03T17:11:57.064Z",
      "__v": 0,
  }
  var parrentid=mongoose.Types.ObjectId('6132574f21979200f70c64cd')
  var childid=mongoose.Types.ObjectId('6132575d21979200f70c64dd')

Post.updateOne({_id:'6132574321979200f70c64b0',"comments._id":parrentid},{$addToSet:{ 'comments.$[s].comments.$[n].comments': comment} },
{arrayFilters: [{'s._id':parrentid} ,{'n._id':childid}],multi:true },
(err,result) => {
      if (err) { console.log(err); }
      console.log(result)
      console.log('saved:',comment)
   
    });
```

**What is the expected behavior?**
update the nested document in the nested array  not error on:
```
Error: Could not find path "comments.0.comments.0._id" in schema
    at castArrayFilters (/starter/node_modules/mongoose/lib/helpers/update/castArrayFilters.js:49:15)
    at _castArrayFilters (/starter/node_modules/mongoose/lib/query.js:2071:5)
    at model.Query._updateThunk (/starter/node_modules/mongoose/lib/query.js:3929:3)
    at model.Query.<anonymous> (/starter/node_modules/mongoose/lib/query.js:4053:23)
    at model.Query._wrappedThunk [as _updateOne] (/starter/node_modules/mongoose/lib/helpers/query/wrapThunk.js:27:8)
    at /starter/node_modules/kareem/index.js:279:20
    at _next (/starter/node_modules/kareem/index.js:103:16)
    at /starter/node_modules/kareem/index.js:508:38
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
 node --version v16.7.0
mongoose 6.0.4 broken
mongoose 5.13.8 works
mongo 5.0.2 , also tested 4.4.8 but doesn't seem to make difference

I thought it might have to do something with the fact that the comments aren't always set on all the nested comments objects so when searching the nested documents it fails when it cant read out the none existing nested comments ?
But I have no idea if this is actually what's happening
It does work on 5.13.8 doh

the example is a simplified version sorry for any errors
sorry for my english I'm not a native speaker and i'm dyslexic 
I hope this is enough information, if more information is needed please let me know

**Comment by vkarpov15** [comment]
I took a closer look and the issue isn't with array filters, but with how your comment schema is structured. The `[this]` syntax in the below code means `comments` is an array of arbitrary elements in v5.x:

```javascript
const CommentSchema = new mongoose.Schema({
  comment: String,
  comments:[this], // <-- array of arbitrary elements in Mongoose 5, array of specific objects in Mongoose 6

}, { timestamps: true });
```

The correct way to define a recursive schema like this is shown below:

```javascript
const CommentSchema = new mongoose.Schema({
  comment: String,
}, { timestamps: true });
CommentSchema.add({ comments: [CommentSchema] });
```
