### ISSUE TITLE
TypeError [ERR_INVALID_URL] when trying to `Model.syncIndexes()` on a replicaset.

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#10697]
Whenever we try to do `Model.syncIndexes(...)` on the production replicaset, we always get the error below.
I changed the IPs and kept the ports as is.
```
TypeError [ERR_INVALID_URL]: Invalid URL: mongodb://100.50.70.244:55009,139.50.71.233:55009,137.53.21.144:55009
    at onParseError (internal/url.js:279:9)
    at parse (<anonymous>)
    at new URL (internal/url.js:355:5)
    at getInstanceAttributeParameters (node_modules\newrelic\lib\instrumentation\mongodb\common.js:141:36)
    at Collection.queryDescFunc (node_modules\newrelic\lib\instrumentation\mongodb\common.js:80:24)
    at Collection.queryRecord (node_modules\newrelic\lib\shim\datastore-shim.js:725:29)
    at Collection.wrapper (node_modules\newrelic\lib\shim\shim.js:929:33)
    at NativeCollection.<computed> [as createIndex] (node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:33)
    at create (node_modules\mongoose\lib\model.js:1746:22)
    at node_modules\mongoose\lib\model.js:1765:7
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  input: 'mongodb://100.50.70.244:55009,139.50.71.233:55009,137.53.21.144:55009',
  code: 'ERR_INVALID_URL'
}
```

Here's how my connection looks like, what's interesting is that the connection promise resolved, while trying to `createIndex` as a side effect for `syncIndexes` throws an error.
```js
await mongoose.connect('mongodb://100.50.70.244:55009,139.50.71.233:55009,137.53.21.144:55009', {
  maxPoolSize: 10,
  dbName: DB_NAME,
  authSource: 'admin',
  readPreference: 'primaryPreferred',
  replicaSet: 'replica0',
  auth: {
    username: DB_USER,
    password: DB_PASS
  }
});
```

I couldn't come up with a reproduction script isolated from my production DB, `model.syncIndexes` works fine with a standalone, and even with a local replica-set by a docker-compose, I'll try to come up with a repro script.

This issue only appeared after upgrading to v6.0.0, and is still present until v6.0.5.

**Comment by AbdelrahmanHafez** [comment]
It seems like this issue happens only when I enable [newrelic](https://github.com/newrelic/node-newrelic), the error doesn't happen when I disable it. That explains why I was unable to reproduce it isolated from my production setup.

I'll open an issue there, and keep this one open as well. Perhaps there is something we can do to prevent the issue from happening.

**Comment by AbdelrahmanHafez** [comment]
Newrelic's team are pushing a fix to this on Monday. https://github.com/newrelic/node-newrelic/issues/860
