### ISSUE TITLE
MongooseError: Operation `inventories.find()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by Diegorandom** [Automattic/mongoose#10698]
I want to report a bug.

When trying to update the database,
This error appears intermittently:

`[error] inventory: MongooseError: Operation `inventories.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/var/task/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)`

This is the connection code:

`exports.createConnection = async (uri, app) => {
  if (!connections[app]) {
    // log.debug('getting NEW conn for ', app)
    let conn = await mongoose.createConnection(uri, {
      appname: app,
      // bufferCommands: false, // Disable mongoose buffering
      // bufferMaxEntries: 0, // and MongoDB driver buffering
      useNewUrlParser: true, // https://mongoosejs.com/docs/deprecations.html
      useUnifiedTopology: true, // https://mongoosejs.com/docs/deprecations.html
      poolSize: process.env.DB_POOL_SIZE && parseInt(process.env.DB_POOL_SIZE) || 50
    })
    conn.on('connected', () => {
      // log.debug('OnConnected activeConnection', app)
      // log.debug('OnConnected activeConnection', activeConnection)
    })
    conn.once("open", () => {
      // log.debug('OnConnection OPEN ', app)
    })
    conn.on('error', (error) => {
      // log.debug('OnError error', error)
    })
    conn.on('reconnected', () => {
      // log.debug('Reconnected', app)
    })
    connections[app] = conn
    activeConnection = conn
  }
  else {
    // log.debug(`Found cached connection for, ${app}. Setting it to active`)
    activeConnection = connections[app]
  }
}`

Connected listener never get hit.

Node version: 14.17.5
"mongodb": "3.6.11"
"mongoose": "5.12.14"

**Comment by IslandRhythms** [comment]
That usually pops up when you haven't connected to mongodb.  Make sure your connection string is correct, you have a mongodb instance running, etc.

**Comment by Diegorandom** [comment]
The connection string is okay, it is an intermittent error, sometimes the database responds with no problem and sometimes it fails.

**Comment by IslandRhythms** [comment]
do you have a mongodb instance running?

**Comment by Diegorandom** [comment]
yes

**Comment by Diegorandom** [comment]
Do you think this would work?
https://stackoverflow.com/questions/61800062/error-querytxt-etimeout-when-connecting-to-mongodb-atlas-using-mongoose
[
<img width="682" alt="Captura de Pantalla 2021-09-09 a la(s) 18 51 49" src="https://user-images.githubusercontent.com/6525329/132777096-b6d9674b-02cc-4cf5-b664-cbc634ff6f93.png">
](url)

**Comment by IslandRhythms** [comment]
I don't think an `appname` option is supported with mongoose connect.

**Comment by vkarpov15** [comment]
@IslandRhythms `appname` is a supported option, it's used primarily for debugging. The MongoDB server logs print out `appname`, which is helpful for figuring out issues when there's multiple apps.

@Diegorandom are you using AWS Lambda or some other serverless framework?

The fact that the connected listener doesn't hit combined with the error message you're seeing makes it seem like your app isn't able to connect to MongoDB.

**Comment by adamreisnz** [comment]
@vkarpov15 I ran into a similar problem today when deploying our release to staging.

The errors reported were also regarding the buffering timeout, but the underlying problem was that mongoose couldn't connect. It reported the following error: `MongoParseError: option poolsize is not supported`

However, we don't use poolsize or maxPoolSize and have never used this in our options, so that seems a bit odd. Nor is this present in our connection URI string.

We did however still have the setting `useNewUrlParser` set to `true`, which I think is now no longer used. I removed this as well but still no luck.

This is on Node 16, running on Heroku.
Running locally in our dev environment does not produce this issue.

**Comment by IslandRhythms** [comment]
@adamreisnz try `maxPoolSize` instead https://mongoosejs.com/docs/connections.html#connection_pools

**Comment by vkarpov15** [comment]
You're right @adamreisnz , the issue may very well be due to the `poolSize` option. We already got rid of the `poolSize` option in our lambda docs: https://mongoosejs.com/docs/lambda.html and made a note in the 6.0 migration guide (https://mongoosejs.com/docs/migrating_to_6.html), so I think we can close this issue.
