### ISSUE TITLE
Why Mongoose (or MongoDb ) is treating a String as an Object Id

### ISSUE THREAD

**Issue by samuelmaina** [Automattic/mongoose#10700]
I am using mongoose to add products to MongoDb. I don't know why it is treating a string (imageUrl) 
as an ObjectID.
It is kind of a strange behavour. The code is working fine but I am getting a validation error that does not stop a product from being saved to the database(the Error is thrown and the product is saved).

Here is the schema

```
const Product = new Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
      minlength: ranges.title.minlength,
      maxlength: ranges.title.maxlength,
    },
    imageUrl: {
      type: String,
      required: true,
      trim: true,
      minlength: ranges.imageUrl.minlength,
      maxlength: ranges.imageUrl.maxlength,
    },
    public_id: {
      type: String,
      required: true,
      trim: true,
      minlength: ranges.imageUrl.minlength,
      maxlength: ranges.imageUrl.maxlength,
    },
    buyingPrice: {
      type: Number,
      required: true,
      min: ranges.buyingPrice.min,
      max: ranges.buyingPrice.max,
    },
    percentageProfit: {
      type: Number,
      required: true,
      min: ranges.percentageProfit.min,
      max: ranges.percentageProfit.max,
    },
    //this one is always calculated by
    //the server so no need
    //to specify it in the schema.
    sellingPrice: {
      type: Number,
    },

    description: {
      type: String,
      required: true,
      trim: true,
      minlength: ranges.description.minlength,
      maxlength: ranges.description.maxlength,
    },
    quantity: {
      type: Number,
      required: true,
      min: ranges.quantity.min,
      max: ranges.quantity.max,
    },
    adminId: {
      type: Schema.Types.ObjectId,
      ref: "Admin",
      required: true,
      minlength: mongooseId,
      maxlength: mongooseId,
    },
    category: {
      type: String,
      minlength: ranges.category.minlength,
      maxlength: ranges.category.maxlength,
      required: true,
    },
    brand: {
      type: String,
      minlength: ranges.brand.minlength,
      maxlength: ranges.brand.maxlength,
      required: true,
    },
  },
  {
    timestamps: true,
  }
);
```
 I have my own custom insert function (createOne) which looks like this
```
const { statics, methods } = Product;

statics.createOne = async function (productData) {
  const Product = mongoose.model("Product");
  const product = new Product(productData);
  await product.save();
  return product;
};
```
 I have passed the following object to createOne for insertion
```
       {
        title: 's2s0s',
        imageUrl: 's8s8s',
        public_id: 's2s6s',
        buyingPrice: 169979.02603187307,
        percentageProfit: 251.1510241253014,
        description: 's2s3s5s5s8',
        quantity: 8428,
        adminId: '6139d66933eab8f49493845b',
        category: 's2s4s',
        brand: 's6s8s'
      }
```
 After logging the product saved from the above object I got the following.
```
       {
        title: 's2s0s',
        imageUrl: 's8s8s',
        public_id: 's2s6s',
        buyingPrice: 169979.02603187307,
        percentageProfit: 251.1510241253014,
        sellingPrice: 596883.09,
        description: 's2s3s5s5s8',
        quantity: 8428,
        adminId: new ObjectId("6139d66933eab8f49493845b"),
        category: 's2s4s',
        brand: 's6s8s',
        _id: new ObjectId("6139d66e33eab8f494938465"),
        createdAt: 2021-09-09T09:39:58.366Z,
        updatedAt: 2021-09-09T09:39:58.366Z,
        __v: 0
      }

```
The product also exists in the database-as can be seen in 
[MongoDbCompass Image][1].

but I am getting a validation Error. (which stems from imageUrl Validation-imageUrl is the only field with  string "s8s8s".)

```
  CastError: Cast to ObjectId failed for value "s8s8s" (type string) at path "_id" for model "Product"
          at model.Query.exec (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\query.js:4498:21)
          at model.Query.Object.<anonymous>.Query.then (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\query.js:4592:15)
          at processTicksAndRejections (internal/process/task_queues.js:95:5) {
        messageFormat: undefined,
        stringValue: '"s8s8s"',
        kind: 'ObjectId',
        value: 's8s8s',
        path: '_id',
        reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
            at new ObjectID (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\bson\lib\bson\objectid.js:59:11)
            at castObjectId (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\cast\objectid.js:25:12)
            at ObjectId.Object.<anonymous>.ObjectId.cast (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\schema\objectid.js:245:12)
            at ObjectId.Object.<anonymous>.SchemaType.applySetters (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\schematype.js:1123:12)
            at ObjectId.Object.<anonymous>.SchemaType._castForQuery (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\schematype.js:1601:15)
            at ObjectId.Object.<anonymous>.SchemaType.castForQuery (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\schematype.js:1591:15)
            at ObjectId.Object.<anonymous>.SchemaType.castForQueryWrapper (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\schematype.js:1568:20)
            at cast (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\cast.js:331:32)      
            at model.Query.Object.<anonymous>.Query.cast (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\query.js:4937:12)
            at model.Query.Object.<anonymous>.Query._castConditions (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\query.js:1975:10)
            at model.Query.<anonymous> (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\query.js:2232:8)
            at model.Query._wrappedThunk [as _findOne] (C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
            at C:\Users\SAM\Desktop\folders\Academic\Projects\Online_Shop\node_modules\kareem\index.js:370:33
            at processTicksAndRejections (internal/process/task_queues.js:77:11),
        valueType: 'string'
      }
```
What I am I doing wrong? Why is it addressing imageUrl as '_id' field? Why is the imageUrl being interpreted as an ObjectId when I have specified it to be string in the schema? It is it a mongoose (or MongoDB) bug?

  [1]: https://i.stack.imgur.com/7ogik.png

**node version v14.17.5**
**mongoose  version 6.0.5**
**MongoDB  version 5.0**

**Comment by IslandRhythms** [comment]
Does this error happen in earlier versions?

**Comment by IslandRhythms** [comment]
I modified the script as I didn't have your `ranges` object. include it and I'll try again and see if maybe that is causing the error.
```javascript
const mongoose = require('mongoose');
const {Schema} = mongoose;


const Product = new Schema(
    {
      title: {
        type: String,
        required: true,
        trim: true,
      },
      imageUrl: {
        type: String,
        required: true,
        trim: true,
      },
      public_id: {
        type: String,
        required: true,
        trim: true,
      },
      buyingPrice: {
        type: Number,
        required: true,
      },
      percentageProfit: {
        type: Number,
        required: true,
      },
      //this one is always calculated by
      //the server so no need
      //to specify it in the schema.
      sellingPrice: {
        type: Number,
      },
  
      description: {
        type: String,
        required: true,
        trim: true,
      },
      quantity: {
        type: Number,
        required: true,
      },
      adminId: {
        type: Schema.Types.ObjectId,
        ref: "Admin",
        required: true
      },
      category: {
        type: String,
        required: true,
      },
      brand: {
        type: String,
        required: true,
      },
    },
    {
      timestamps: true,
    }
  );

const PModel = mongoose.model('PModel', Product);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    await PModel.create({
        title: 's2s0s',
        imageUrl: 's8s8s',
        public_id: 's2s6s',
        buyingPrice: 169979.02603187307,
        percentageProfit: 251.1510241253014,
        description: 's2s3s5s5s8',
        quantity: 8428,
        adminId: '6139d66933eab8f49493845b',
        category: 's2s4s',
        brand: 's6s8s'
    });
    console.log(await PModel.find());
    console.log('done');
}

run();
```

**Comment by samuelmaina** [comment]
The error happened in my earlier version (I can remember exactly but I
think it 5.x.x) . I upgraded to the latest version but the problem still
persists

**Comment by samuelmaina** [comment]
the ranges was a file that contains  the constraints(lengths of the
fields)  and their errors of the database.  It looks like this
exports.product = {
  title: {
    minlength: 5,
    maxlength: 20,
    error: stringErrorGenerator("Title", 5, 20),
  },
  //does not need error message.
  imageUrl: {
    minlength: 5,
    maxlength: 100,
  },
  buyingPrice: {
    min: 100,
    max: 200000,
    error: currencyErrorGenerator("Buying price", 100, 200000),
  },
  percentageProfit: {
    min: 0,
    max: 300,
    error: floatErrorGenerator("Percentage profit", 0, 300),
  },
  description: {
    minlength: 10,
    maxlength: 400,
    error: stringErrorGenerator("Description", 10, 40),
  },
  quantity: {
    min: 0,
    max: 20000,
    error: intErrorGenerator("Quantity", 0, 20000),
  },
  category: {
    minlength: 5,
    maxlength: 20,
    error: stringErrorGenerator("Category", 5, 20),
  },
  brand: {
    minlength: 5,
    maxlength: 20,
    error: stringErrorGenerator("Brand", 5, 20),
  },
};

**Comment by samuelmaina** [comment]
> Does this error happen in earlier versions?

Yeah. I happened in my previous version (5.x.x) . The error persists in the latest update

**Comment by vkarpov15** [comment]
@samuelmaina can you please modify the script in https://github.com/Automattic/mongoose/issues/10700#issuecomment-916468547 to demonstrate your issue? Without a repro script, it will be difficult for us to provide any meaningful insight.

**Comment by IslandRhythms** [comment]
Still can't reproduce it, somethings have been omitted like the generators attacked to your ranges object as well as `mongooseId`
