### ISSUE TITLE
Mongoose can't connect to mongodb 4.4.4 replica set inside a docker container

### ISSUE THREAD

**Issue by omarwaleed** [Automattic/mongoose#10718]
**What is the expected behavior?**
Mongoose should be able to connect to local replica set inside a docker container.
When I updated my mongoose version from 5.x to 6.0.5 mongoose stopped connecting to my local replica set. When I tried to connecting to a normal non replica set container it worked fine. 
I reverted back my mongoose version to 5.13.9 and it connected to the RS with no problem.
Here's the stack trace for the error trying to connect with version 6.0.5, mongodb version 4.4.4 and node 14.17.0

```
MongooseServerSelectionError: getaddrinfo ENOTFOUND 508be0425c52
    at NativeConnection.Connection.openUri (/projectPath/node_modules/mongoose/lib/connection.js:798:32)
    at /projectPath/node_modules/mongoose/lib/index.js:330:10
    at promiseOrCallback (/projectPath/node_modules/mongoose/lib/helpers/promiseOrCallback.js:10:12)
    at Mongoose._promiseOrCallback (/projectPath/node_modules/mongoose/lib/index.js:1151:10)
    at Mongoose.connect (/projectPath/node_modules/mongoose/lib/index.js:329:20)
    at Object.<anonymous> (/projectPath/app.js:25:10)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/projectPath/bin/www:7:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(1) { '508be0425c52:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'rs0',
    maxSetVersion: 2,
    maxElectionId: new ObjectId("7fffffff0000000000000009"),
    commonWireVersion: 9,
    logicalSessionTimeoutMinutes: undefined
  }
}
```

**Comment by vkarpov15** [comment]
This seems like it might be a [replica set hostname issue](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). MongoDB isn't able to reconcile `508be0425c52` as a domain name. Can you please provide what your connection string looks like, and what the output of running `rs.status()` when connected to your cluster using the MongoDB shell is?

**Comment by omarwaleed** [comment]
Here's the connection string (that works with v5.x) `mongodb://127.0.0.1:27017/my-project`
Here's what running `rs.status()` yields
```
rs0:PRIMARY> rs.status()
{
	"set" : "rs0",
	"date" : ISODate("2021-09-20T12:24:46.885Z"),
	"myState" : 1,
	"term" : NumberLong(10),
	"syncSourceHost" : "",
	"syncSourceId" : -1,
	"heartbeatIntervalMillis" : NumberLong(2000),
	"majorityVoteCount" : 1,
	"writeMajorityCount" : 1,
	"votingMembersCount" : 1,
	"writableVotingMembersCount" : 1,
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1632140685, 1),
			"t" : NumberLong(10)
		},
		"lastCommittedWallTime" : ISODate("2021-09-20T12:24:45.246Z"),
		"readConcernMajorityOpTime" : {
			"ts" : Timestamp(1632140685, 1),
			"t" : NumberLong(10)
		},
		"readConcernMajorityWallTime" : ISODate("2021-09-20T12:24:45.246Z"),
		"appliedOpTime" : {
			"ts" : Timestamp(1632140685, 1),
			"t" : NumberLong(10)
		},
		"durableOpTime" : {
			"ts" : Timestamp(1632140685, 1),
			"t" : NumberLong(10)
		},
		"lastAppliedWallTime" : ISODate("2021-09-20T12:24:45.246Z"),
		"lastDurableWallTime" : ISODate("2021-09-20T12:24:45.246Z")
	},
	"lastStableRecoveryTimestamp" : Timestamp(1632140625, 1),
	"electionCandidateMetrics" : {
		"lastElectionReason" : "electionTimeout",
		"lastElectionDate" : ISODate("2021-09-20T12:22:55.210Z"),
		"electionTerm" : NumberLong(10),
		"lastCommittedOpTimeAtElection" : {
			"ts" : Timestamp(0, 0),
			"t" : NumberLong(-1)
		},
		"lastSeenOpTimeAtElection" : {
			"ts" : Timestamp(1631870629, 1),
			"t" : NumberLong(9)
		},
		"numVotesNeeded" : 1,
		"priorityAtElection" : 1,
		"electionTimeoutMillis" : NumberLong(10000),
		"newTermStartDate" : ISODate("2021-09-20T12:22:55.220Z"),
		"wMajorityWriteAvailabilityDate" : ISODate("2021-09-20T12:22:55.230Z")
	},
	"members" : [
		{
			"_id" : 0,
			"name" : "508be0425c52:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 114,
			"optime" : {
				"ts" : Timestamp(1632140685, 1),
				"t" : NumberLong(10)
			},
			"optimeDate" : ISODate("2021-09-20T12:24:45Z"),
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "Could not find member to sync from",
			"electionTime" : Timestamp(1632140575, 1),
			"electionDate" : ISODate("2021-09-20T12:22:55Z"),
			"configVersion" : 2,
			"configTerm" : 10,
			"self" : true,
			"lastHeartbeatMessage" : ""
		}
	],
	"ok" : 1,
	"$clusterTime" : {
		"clusterTime" : Timestamp(1632140685, 1),
		"signature" : {
			"hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
			"keyId" : NumberLong(0)
		}
	},
	"operationTime" : Timestamp(1632140685, 1)
}
```

**Comment by louisnow** [comment]
Use `directConnection: true` while connecting via `mongoose.connect()`
[Driver Option](https://github.com/mongodb/node-mongodb-native/pull/2349)
[MongoDB Docs](https://docs.mongodb.com/drivers/node/current/fundamentals/connection/#direct-connection)

**Comment by omarwaleed** [comment]
@louisnow thanks that helped

**Comment by Vinayjinugu-gep** [comment]
> @omarwaleed Use `directConnection: true` while connecting via `mongoose.connect()` [Driver Option](https://github.com/mongodb/node-mongodb-native/pull/2349) [MongoDB Docs](https://docs.mongodb.com/drivers/node/current/fundamentals/connection/#direct-connection)

what if the connection is srv. We can't use directConnection what to do then?

**Comment by vkarpov15** [comment]
@Vinayjinugu-gep https://mongoosejs.com/docs/connections.html#replicaset-hostnames
