### ISSUE TITLE
SSL Credentials Documentation Out of Date

### ISSUE THREAD

**Issue by keymandll** [Automattic/mongoose#10787]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The SSL tutorial at https://mongoosejs.com/docs/tutorials/ssl.html says that sslCA (and sslKey, sslCert) are supposed to be read and the contents of the files to be passed as value. However, Mongoose 6.0.7 expects these options to be the path to the files as string.

**If the current behavior is a bug, please provide the steps to reproduce.**

Can be reproduced by following what is included in the documentation:

```
await mongoose.connect('mongodb://localhost:27017/test', {
  ssl: true,
  sslValidate: true,
  // For example, see https://medium.com/@rajanmaharjan/secure-your-mongodb-connections-ssl-tls-92e2addb3c89
  // for where the `rootCA.pem` file comes from
  sslCA: require('fs').readFileSync(`${__dirname}/rootCA.pem`)
});
```

Result:

```
service        |     at Object.openSync (fs.js:498:3)
service        |     at Object.readFileSync (fs.js:394:35)
service        |     at transform (/home/gateway/node_modules/mongodb/lib/connection_string.js:806:23)
service        |     at setOption (/home/gateway/node_modules/mongodb/lib/connection_string.js:394:36)
service        |     at Object.parseOptions (/home/gateway/node_modules/mongodb/lib/connection_string.js:287:9)
service        |     at new MongoClient (/home/gateway/node_modules/mongodb/lib/mongo_client.js:62:46)
service        |     at /home/gateway/node_modules/mongoose/lib/connection.js:779:16
service        |     at new Promise (<anonymous>)
service        |     at NativeConnection.Connection.openUri (/home/gateway/node_modules/mongoose/lib/connection.js:776:19)
service        |     at /home/gateway/node_modules/mongoose/lib/index.js:328:10 {
service        |   errno: -36,
service        |   syscall: 'open',
service        |   code: 'ENAMETOOLONG',
service        |   path: '-----BEGIN CERTIFICATE-----\n' +
service        |     'MIIFdjCCA16gAw.......
```

The below works perfectly:

```
        await mongoose.connect(process.env.DATABASE_URL, {
            useNewUrlParser: true,
            useUnifiedTopology: true,
            ssl: true,
            sslValidate: true,
            sslCA: '/credentials/cabundle.crt',
            sslKey: '/credentials/client/service_bundled.pem',
            sslCert: '/credentials/client/service_bundled.pem'
        });
```

**What is the expected behavior?**

Preferably the documentation to be updated with working examples and this breaking change to be documented in the change log/migration guide.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v14.17.6
Mongoose: 6.0.7

**Comment by vkarpov15** [comment]
This was fixed in https://github.com/Automattic/mongoose/commit/a4f2ecad6402928e12dec2a9a8ae5faa25227e68 and released with 6.0.8 earlier today, sorry for the confusion!
