### ISSUE TITLE
MongoParseError: All values of ssl must be the same.

### ISSUE THREAD

**Issue by Gr8z** [Automattic/mongoose#10800]
How do I solve this error:
```
Sep 28 12:56:47 ip-172-31-8-244 web: (node:1439) UnhandledPromiseRejectionWarning: MongoParseError: All values of ssl must be the same.
Sep 28 12:56:47 ip-172-31-8-244 web: at Object.parseOptions (/var/app/current/node_modules/mongodb/lib/connection_string.js:319:19)
Sep 28 12:56:47 ip-172-31-8-244 web: at new MongoClient (/var/app/current/node_modules/mongodb/lib/mongo_client.js:62:46)
Sep 28 12:56:47 ip-172-31-8-244 web: at /var/app/current/node_modules/mongoose/lib/connection.js:779:16
Sep 28 12:56:47 ip-172-31-8-244 web: at new Promise (<anonymous>)
Sep 28 12:56:47 ip-172-31-8-244 web: at NativeConnection.Connection.openUri (/var/app/current/node_modules/mongoose/lib/connection.js:776:19)
Sep 28 12:56:47 ip-172-31-8-244 web: at /var/app/current/node_modules/mongoose/lib/index.js:328:10
Sep 28 12:56:47 ip-172-31-8-244 web: at /var/app/current/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
Sep 28 12:56:47 ip-172-31-8-244 web: at new Promise (<anonymous>)
Sep 28 12:56:47 ip-172-31-8-244 web: at promiseOrCallback (/var/app/current/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
Sep 28 12:56:47 ip-172-31-8-244 web: at Proxy.Mongoose._promiseOrCallback (/var/app/current/node_modules/mongoose/lib/index.js:1149:10)
```

I am using Mongoose v6.0.7

My connection string: 
```
mongodb://username:password@mongodb-name.cluster.us-east-1.docdb.amazonaws.com:27017/db?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
```

My connect() options: 

```js
mongoose
  .connect(process.env.DATABASE_URL, {
    ssl: true,
    sslCA: `${__dirname}/rootCA.pem`
  })
```

**Comment by vkarpov15** [comment]
Try removing `ssl=true` in your connection string _or_ `ssl: true` in your connection options, I suspect that's the issue. But we'll investigate and see if this is a bug in the MongoDB node driver.

**Comment by IslandRhythms** [comment]
The `done` print does not execute when `ssl:true` is present in the connection string. It doesn't throw any error either but the fact that it prints `done` when `ssl:true` is not present is odd.

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true)

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {ssl:true});
    await mongoose.connection.dropDatabase();
    console.log('done');

}

run();
console.log('hello');
```

**Comment by Gr8z** [comment]
> Try removing `ssl=true` in your connection string _or_ `ssl: true` in your connection options, I suspect that's the issue. But we'll investigate and see if this is a bug in the MongoDB node driver.

I removed `ssl: true` from my connection options and it starts working. Thank you.
