### ISSUE TITLE
Populate with array of fields throws TypeError: Invalid select() argument. Must be a string or object.

### ISSUE THREAD

**Issue by ghost** [Automattic/mongoose#1087]
This works well in `mongoose@3.0.3`:

```
schema.statics.findGlobal = function(cb) {
  this.find({}).populate('user', 'login').limit(20).exec(cb);
}
```

But when I try:

```
schema.statics.findGlobal = function(cb) {
  this.find({}).populate('user', ['login']).limit(20).exec(cb);
}
```

It fails with:

```
TypeError: Invalid select() argument. Must be a string or object.
    at Query.select (/Users/rav/MF/instarest/node_modules/mongoose/lib/query.js:1061:11)
    at Function.findOne (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:970:46)
    at Model.populate [as _populate] (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:139:6)
    at next (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:265:14)
    at next (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:228:57)
    at next (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:228:57)
    at next (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:228:57)
    at next (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:228:57)
    at next (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:228:57)
    at next (/Users/rav/MF/instarest/node_modules/mongoose/lib/model.js:228:57)
```

Is it intended? How can I populate multiple fields?

**Comment by Djisu** [comment]
Thanks, that solved my problem
