### ISSUE TITLE
 MongoGridFSChunkError: ExtraChunk: Got unexpected n: 1

### ISSUE THREAD

**Issue by sh4d0q** [Automattic/mongoose#10907]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

We have attachments from REST API and sometimes, this is not the deterministic issue, that "socket is hang out", but this is not the source problem after investigating this on our API, I found the problem in `GridFSBucket` from MongoDB.  Earlier we used `gridfs-stream` now we swap places with implementation Gridfs stream with Moongose/Mongo 

Please see stack trace:
```
error: MongoGridFSChunkError: ExtraChunk: Got unexpected n: 1
        at /home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/gridfs/download.ts:265:11
        at /home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/utils.ts:649:5
        at next (/home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/cursor/abstract_cursor.ts:651:5)
        at /home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/cursor/abstract_cursor.ts:307:7
        at Object.maybePromise (/home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/utils.ts:634:3)
        at FindCursor.next (/home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/cursor/abstract_cursor.ts:302:12)
        at doRead (/home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/gridfs/download.ts:212:19)
        at /home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/gridfs/download.ts:146:29
        at waitForFile (/home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/gridfs/download.ts:388:12)
        at GridFSBucketReadStream._read (/home/shadoq/IdeaProjects/ccms/node_modules/mongodb/src/gridfs/download.ts:146:5),
    level: 'error',
```

**If the current behavior is a bug, please provide the steps to reproduce.**

We have displayed the list with attachments (images) and sometimes this problem exists sometimes not. We cannot say that this problem exists for smaller file or big.

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": true,
    "target": "es2018",
    "lib": ["es2018"]
  },
  "include": [],
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```
../../tsconfig.json (base)
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "baseUrl": ".",
    "target": "es2015",
    "module": "es2020",
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "importHelpers": true,
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "typeRoots": ["libs/content-builder/types", "node_modules/@types"],
  },
}
```
**What is the expected behavior?**

This kind of error shouldn't appear.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Nodejs: v16.5.0
Mongoose: 6.0.10
MongoDB: 5.0.3, but on GitLab pipelines (4.0 so doesn't make matter)

**Comment by vkarpov15** [comment]
This error means you have a corrupted file in GridFS where the recorded file `length` is less than the actual number of chunks associated with the file. For example, the below script prints the given error message:

```javascript
'use strict';

const mongoose = require('mongoose');
const mongodb = mongoose.mongo;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  const client = mongoose.connection.client;
  await mongoose.connection.dropDatabase();

  const _id = new mongoose.Types.ObjectId();
  await client.db().collection('fs.files').insertOne({
    _id,
    length: 1, // <-- expecting that there's only 1 chunk...
    uploadDate: new Date(),
    chunkSize: 1
  });
  await client.db().collection('fs.chunks').insertOne({
    files_id: _id,
    n: 0,
    data: Buffer.from('h')
  });
  await client.db().collection('fs.chunks').insertOne({
    files_id: _id,
    n: 1, // <-- but there's a 2nd chunk associated with this file
    data: Buffer.from('i')
  });

  const bucket = new mongodb.GridFSBucket(client.db(), { bucketName: 'fs' });
  const stream = bucket.openDownloadStream(_id);

  // Throws 'MongoGridFSChunkError: ExtraChunk: Got unexpected n: 1'
  await new Promise((resolve, reject) => {
    stream.on('data', () => {});
    stream.on('end', resolve);
    stream.on('error', reject);
  });

  console.log('Done');
}
```

We'll improve this error message for readability, but the issue is fundamentally that there's a dangling chunk on one or more of your files, and you need to clean up those files. See [MongoDB GridFS docs](https://docs.mongodb.com/manual/core/gridfs/) for more info on chunks.
