### ISSUE TITLE
Error using find command

### ISSUE THREAD

**Issue by otaciobarbosa** [Automattic/mongoose#10953]
**Do you want to request a *feature* or report a *bug*?**
**R: Bug**

**What is the current behavior?**
**R: My query is normally using findOne, however when I use only find ({}) it returns an error.**

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const mongoose = require('mongoose');

exports.get = async (req, res) => {

    const mongoDB = 'mongodb://192.168.0.1:27017/teste';
    mongoose.connect(mongoDB, {
        useNewUrlParser: true,
        useUnifiedTopology: true
    });

    const db = mongoose.connection;

    db.on('error', (erro) => {
        console.log('Mongoose! Erro na conexao em ' + erro);
    });

    db.on('connected', () => {
        console.log('Mongoose! Conectado em ' + mongoDB);
    });

    db.on('disconected', () => {
        console.log('Mongoose! Desconectado em ' + mongoDB);
    });


    try {

        const docs = await db.collection('nfce').find({
            num_loj: 1
        });

        console.log(docs);

        res.status(200).json({
            status: 'success',
            results: docs.length,
            data: {
                docs
            },
        });
    } catch (error) {
        console.log(error);
        res.status(404).json({
            status: 'fail',
            err: error,
        });
    }
}
```

**What is the expected behavior?**
**R: Let all information be returned where { num_loj: 1 }**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```
"nodejs":" 14.18.1"
"mongoose": "5.13.12"
"mongodb": "4.1.3"

```

Error:

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'NativeTopology'
    |     property 's' -> object with constructor 'Object'
    |     property 'sessionPool' -> object with constructor 'ServerSessionPool'
    --- property 'topology' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (C:\server\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (C:\server\node_modules\express\lib\response.js:260:14)
    at exports.get (C:\server\src\controllers\notasFiscaisController.js:34:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by IslandRhythms** [comment]
do `docs: docs` and see if that fixes it

**Comment by otaciobarbosa** [comment]
@IslandRhythms retur error:
```
{
"status": "fail",
"err": {}
}
```


```
ypeError: Converting circular structure to JSON
    --> starting at object with constructor 'NativeTopology'
    |     property 's' -> object with constructor 'Object'
    |     property 'sessionPool' -> object with constructor 'ServerSessionPool'
    --- property 'topology' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (C:\server\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (C:\server\node_modules\express\lib\response.js:260:14)
    at exports.get (C:\server\src\controllers\notasFiscaisController.js:32:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by vkarpov15** [comment]
This is expected behavior, you're using `collection().find()` without waiting for Mongoose to connect. 2 workarounds:

1) `await mongoose.connect(mongoDB, { ... })`

2) Create a model around the `nfce` collection and use `Model.find()`:

```javascript
// Outside of `async (req, res)`
const Model = mongoose.model('nfce', new mongoose.Schema({}), 'nfce');

// In `async (req, res)`
const docs = await Model.find();
```

On a related note, we strongly recommend not calling `mongoose.connect()` in route handlers, you shouldn't create a new connection for every request.
