### ISSUE TITLE
Mongoose SSL ERR_INTERNAL_ASSERTION since 6+ 

### ISSUE THREAD

**Issue by PierreBrisorgueil** [Automattic/mongoose#11019]
Hello, since the 6+ version and the change about ssl configuration i got an error on connexion, on a Kube cluster (rancher) in a docker container. 

Ok in 5.x 

```
/**
 * Connect to the MongoDB server
 */
module.exports.connect = async () => {
  const mongoOptions = config.db.options;

  if (mongoOptions.sslCA) mongoOptions.sslCA = fs.readFileSync(mongoOptions.sslCA);
  if (mongoOptions.sslCert) mongoOptions.sslCert = fs.readFileSync(mongoOptions.sslCert);
  if (mongoOptions.sslKey) mongoOptions.sslKey = fs.readFileSync(mongoOptions.sslKey);

  try {
    mongoose.Promise = Promise;
    await mongoose.connect(config.db.uri, mongoOptions);
    mongoose.set('debug', config.db.debug);
    return mongoose;
  } catch (err) {
    // Log Error
    console.error(chalk.red('Could not connect to MongoDB!'));
    console.error(chalk.yellow(JSON.stringify(mongoOptions)));
    console.log(err);
    throw err;
  }
};
```

Not Ok in 6.x

```
/**
 * Connect to the MongoDB server
 */
module.exports.connect = async () => {
  const mongoOptions = config.db.options;

  if (mongoOptions.sslCA) mongoOptions.sslCA = path.resolve(mongoOptions.sslCA);
  if (mongoOptions.sslCert) mongoOptions.sslCert = path.resolve(mongoOptions.sslCert);
  if (mongoOptions.sslKey) mongoOptions.sslKey = path.resolve(mongoOptions.sslKey);

  try {
    mongoose.Promise = Promise;
    await mongoose.connect(config.db.uri, mongoOptions);
    mongoose.set('debug', config.db.debug);
    return mongoose;
  } catch (err) {
    // Log Error
    console.error(chalk.red('Could not connect to MongoDB!'));
    console.error(chalk.yellow(JSON.stringify(mongoOptions)));
    console.log(err);
    throw err;
  }
};
```

fs.readFileSync(mongoOptions.sslCA); -> path.resolve(mongoOptions.sslCA);

node Error 

```
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
--
Sat, Nov 27 2021 11:05:09 am | Please open an issue with this stack trace at https://github.com/nodejs/node/issues
Sat, Nov 27 2021 11:05:09 am |  
Sat, Nov 27 2021 11:05:09 am | at new NodeError (node:internal/errors:371:5)
Sat, Nov 27 2021 11:05:09 am | at assert (node:internal/assert:14:11)
Sat, Nov 27 2021 11:05:09 am | at Object.connect (node:_tls_wrap:1614:3)
Sat, Nov 27 2021 11:05:09 am | at makeConnection (/home/node/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:246:31)
Sat, Nov 27 2021 11:05:09 am | at connect (/home/node/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:16:5)
Sat, Nov 27 2021 11:05:09 am | at checkServer (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/monitor.js:200:27)
Sat, Nov 27 2021 11:05:09 am | at /home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/monitor.js:230:9
Sat, Nov 27 2021 11:05:09 am | at executeAndReschedule (/home/node/node_modules/mongoose/node_modules/mongodb/lib/utils.js:789:9)
Sat, Nov 27 2021 11:05:09 am | at makeInterruptibleAsyncInterval (/home/node/node_modules/mongoose/node_modules/mongodb/lib/utils.js:796:9)
Sat, Nov 27 2021 11:05:09 am | at Monitor.connect (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/monitor.js:86:71)
Sat, Nov 27 2021 11:05:09 am | at Server.connect (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:94:28)
Sat, Nov 27 2021 11:05:09 am | at createAndConnectServer (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:561:12)
Sat, Nov 27 2021 11:05:09 am | at /home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:573:24
Sat, Nov 27 2021 11:05:09 am | at Array.reduce (<anonymous>)
Sat, Nov 27 2021 11:05:09 am | at connectServers (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:572:45)
Sat, Nov 27 2021 11:05:09 am | at Topology.connect (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:201:9) {
Sat, Nov 27 2021 11:05:09 am | code: 'ERR_INTERNAL_ASSERTION'
Sat, Nov 27 2021 11:05:09 am | }
Sat, Nov 27 2021 11:05:09 am | server failed: Error: unable to initialize Mongoose or ExpressJS : Error: Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Sat, Nov 27 2021 11:05:09 am | Please open an issue with this stack trace at https://github.com/nodejs/node/issues

```

The kube + docker environment seems not to be responsible of it because a redeploy with version 5 works perfectly. 
However, I cannot reproduce the problem locally for the moment. 

Any idea?

**Comment by vkarpov15** [comment]
No ideas. Without a more detailed repro, this will be hard to debug, because SSL connections work fine in Mongoose 6 as far as we know.

Perhaps try following the instructions in the stack trace and open an issue on https://github.com/nodejs/node/issues?

**Comment by PierreBrisorgueil** [comment]
@vkarpov15 Yes I understand... thx for your time.

Do you have an indication on where to add logs into mongoose in order to test the reading of CRT more precisely, add catch, double check path etc ... ? 
Before going back to the Node side, I would like to investigate on your side, if I can find something ...

**Comment by vkarpov15** [comment]
@PierreBrisorgueil Mongoose doesn't do anything with the CRT directly, Mongoose just passes the SSL options to the MongoDB node driver, which in turn passes them directly to Node's built-in tls module: https://github.com/mongodb/node-mongodb-native/blob/43300c393a190c00f174bc5be0b3fc6d0906e970/src/cmap/connect.ts#L334-L342 .

One thing to try might be to call `tls.connect();` with your SSL options directly and see if you get the same error.

**Comment by PierreBrisorgueil** [comment]
@vkarpov15 It cannot come from the SSL configuration or from Node, everything works perfectly on the same environment  (node/linux) and the same configuration (SSL) in mongoose 5. It does come from the mongoose 6 upgrade or from the upgrade of its Deps.

However, in mongoose 5, we had to pass to mongoose the SSL conf in buffer, with fs.readfileSync. In mongoose 6 we only pass the strings of paths, and I think the problem comes from this. 

To test I generated two connections, one with mongoose, one directly with the MongoDB Client. No error when passing the buffers to the client MongoDB. An error passing the strings of the paths to Mongoose. 🤷‍♂️ can this help?


```js
/**
 * Connect to the MongoDB server
 */
module.exports.connect = async () => {

  const mongoDBOptions = _.cloneDeep(config.db.options);

  if (mongoDBOptions.sslCA) mongoDBOptions.sslCA = fs.readFileSync(mongoDBOptions.sslCA);
  if (mongoDBOptions.sslCert) mongoDBOptions.sslCert = fs.readFileSync(mongoDBOptions.sslCert);
  if (mongoDBOptions.sslKey) mongoDBOptions.sslKey = fs.readFileSync(mongoDBOptions.sslKey);
  delete mongoDBOptions.useUnifiedTopology;
  delete mongoDBOptions.useNewUrlParser;

  try {
    var MongoClient = require('mongodb').MongoClient;
    const test = await MongoClient.connect(String(config.db.uri), mongoDBOptions);
    console.log(chalk.green('MongoDb connect'), test)
    await MongoClient.disconnect;
    console.log(chalk.green('MongoDb disconnect'))
  } catch (err) {
    console.error(chalk.red('Could not connect to MongoDB!'));
    console.log(err);
    throw err;
  }

  const mongooseOptions = _.clone(config.db.options);

  if (mongooseOptions.sslCA) mongooseOptions.sslCA = path.resolve(mongooseOptions.sslCA);
  if (mongooseOptions.sslCert) mongooseOptions.sslCert = path.resolve(mongooseOptions.sslCert);
  if (mongooseOptions.sslKey) mongooseOptions.sslKey = path.resolve(mongooseOptions.sslKey);

  try {
    mongoose.Promise = Promise;
    await mongoose.connect(config.db.uri, mongooseOptions);
    mongoose.set('debug', config.db.debug);
    return mongoose;
  } catch (err) {
    console.error(chalk.red('Could not connect to Mongoose!'));
    console.error(chalk.yellow(JSON.stringify(mongooseOptions)));
    console.log(err);
    throw err;
  }
};

```

result =>

```
MongoDb connect Db {
--
Wed, Dec 8 2021 2:58:05 pm | _events: [Object: null prototype] {},
Wed, Dec 8 2021 2:58:05 pm | _eventsCount: 0,
Wed, Dec 8 2021 2:58:05 pm | _maxListeners: undefined,
Wed, Dec 8 2021 2:58:05 pm | s: {
Wed, Dec 8 2021 2:58:05 pm | databaseName: 'mydatabase',
Wed, Dec 8 2021 2:58:05 pm | dbCache: {},
Wed, Dec 8 2021 2:58:05 pm | children: [],
Wed, Dec 8 2021 2:58:05 pm | topology: ReplSet {
Wed, Dec 8 2021 2:58:05 pm | _events: [Object: null prototype],
Wed, Dec 8 2021 2:58:05 pm | _eventsCount: 8,
Wed, Dec 8 2021 2:58:05 pm | _maxListeners: undefined,
Wed, Dec 8 2021 2:58:05 pm | clientInfo: [Object],
Wed, Dec 8 2021 2:58:05 pm | s: [Object],
Wed, Dec 8 2021 2:58:05 pm | [Symbol(kCapture)]: false
Wed, Dec 8 2021 2:58:05 pm | },
Wed, Dec 8 2021 2:58:05 pm | options: {
Wed, Dec 8 2021 2:58:05 pm | readPreference: [ReadPreference],
Wed, Dec 8 2021 2:58:05 pm | promiseLibrary: [Function: Promise]
Wed, Dec 8 2021 2:58:05 pm | },
Wed, Dec 8 2021 2:58:05 pm | logger: Logger { className: 'Db' },
Wed, Dec 8 2021 2:58:05 pm | bson: BSON {},
Wed, Dec 8 2021 2:58:05 pm | authSource: undefined,
Wed, Dec 8 2021 2:58:05 pm | readPreference: ReadPreference {
Wed, Dec 8 2021 2:58:05 pm | _type: 'ReadPreference',
Wed, Dec 8 2021 2:58:05 pm | mode: 'primary',
Wed, Dec 8 2021 2:58:05 pm | tags: undefined,
Wed, Dec 8 2021 2:58:05 pm | options: undefined
Wed, Dec 8 2021 2:58:05 pm | },
Wed, Dec 8 2021 2:58:05 pm | bufferMaxEntries: -1,
Wed, Dec 8 2021 2:58:05 pm | parentDb: null,
Wed, Dec 8 2021 2:58:05 pm | pkFactory: undefined,
Wed, Dec 8 2021 2:58:05 pm | nativeParser: undefined,
Wed, Dec 8 2021 2:58:05 pm | promiseLibrary: [Function: Promise],
Wed, Dec 8 2021 2:58:05 pm | noListener: false,
Wed, Dec 8 2021 2:58:05 pm | readConcern: undefined
Wed, Dec 8 2021 2:58:05 pm | },
Wed, Dec 8 2021 2:58:05 pm | serverConfig: [Getter],
Wed, Dec 8 2021 2:58:05 pm | bufferMaxEntries: [Getter],
Wed, Dec 8 2021 2:58:05 pm | databaseName: [Getter],
Wed, Dec 8 2021 2:58:05 pm | [Symbol(kCapture)]: false
Wed, Dec 8 2021 2:58:05 pm | }
Wed, Dec 8 2021 2:58:05 pm | MongoDb disconnect
Wed, Dec 8 2021 2:58:05 pm | Could not connect to Mongoose!
Wed, Dec 8 2021 2:58:05 pm | {"useUnifiedTopology":true,"useNewUrlParser":true,"sslCA":"/home/node/mongo/crt","sslKey":"/home/node/mongo/pem","sslValidate":false,"ssl":true,"checkServerIdentity":true,"sslCert":"/home/node/mongo/pem"}
Wed, Dec 8 2021 2:58:05 pm | Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Wed, Dec 8 2021 2:58:05 pm | Please open an issue with this stack trace at https://github.com/nodejs/node/issues
Wed, Dec 8 2021 2:58:05 pm |  
Wed, Dec 8 2021 2:58:05 pm | at new NodeError (node:internal/errors:371:5)
Wed, Dec 8 2021 2:58:05 pm | at assert (node:internal/assert:14:11)
Wed, Dec 8 2021 2:58:05 pm | at Object.connect (node:_tls_wrap:1614:3)
Wed, Dec 8 2021 2:58:05 pm | at makeConnection (/home/node/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:246:31)
Wed, Dec 8 2021 2:58:05 pm | at connect (/home/node/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:16:5)
Wed, Dec 8 2021 2:58:05 pm | at checkServer (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/monitor.js:200:27)
Wed, Dec 8 2021 2:58:05 pm | at /home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/monitor.js:230:9
Wed, Dec 8 2021 2:58:05 pm | at executeAndReschedule (/home/node/node_modules/mongoose/node_modules/mongodb/lib/utils.js:789:9)
Wed, Dec 8 2021 2:58:05 pm | at makeInterruptibleAsyncInterval (/home/node/node_modules/mongoose/node_modules/mongodb/lib/utils.js:796:9)
Wed, Dec 8 2021 2:58:05 pm | at Monitor.connect (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/monitor.js:86:71)
Wed, Dec 8 2021 2:58:05 pm | at Server.connect (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:94:28)
Wed, Dec 8 2021 2:58:05 pm | at createAndConnectServer (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:561:12)
Wed, Dec 8 2021 2:58:05 pm | at /home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:573:24
Wed, Dec 8 2021 2:58:05 pm | at Array.reduce (<anonymous>)
Wed, Dec 8 2021 2:58:05 pm | at connectServers (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:572:45)
Wed, Dec 8 2021 2:58:05 pm | at Topology.connect (/home/node/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:201:9) {
Wed, Dec 8 2021 2:58:05 pm | code: 'ERR_INTERNAL_ASSERTION'
Wed, Dec 8 2021 2:58:05 pm | }
Wed, Dec 8 2021 2:58:05 pm | server failed: Error: unable to initialize Mongoose or ExpressJS : Error: Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Wed, Dec 8 2021 2:58:05 pm | Please open an issue with this stack trace at https://github.com/nodejs/node/issues

```

**Comment by b-sirakov** [comment]
I also got the same error, it seems that it occurs when the "checkServerIdentity" is passed in the db options. So if you don't want to explicitly pass it to "true", i think it defaults to it. As far as i know this is for the hostname verification.

**Comment by PierreBrisorgueil** [comment]
I don't understand why, but it does the trick 🤔
Well done, I hadn't thought of testing this. 

_There is maybe a point to dig, the option isn't a problem with require('mongodb') from my tests @vkarpov15 _

**Comment by vkarpov15** [comment]
@PierreBrisorgueil it looks `checkServerIdentity` should be a function, not a boolean. See https://nodejs.org/api/tls.html#tlscheckserveridentityhostname-cert . The MongoDB Node driver passes this option down to Node.js without modification.

Looks like the MongoDB Node driver dropped support for setting `checkServerIdentity` to a boolean here: https://github.com/mongodb/node-mongodb-native/blob/HEAD/docs/CHANGES_4.0.0.md#check-server-identity-inconsistency

**Comment by saver711** [comment]
if u are using mongoose downgrade to v 7
