### ISSUE TITLE
Bug when having null as default value for an array of objects

### ISSUE THREAD

**Issue by sadokmtir** [Automattic/mongoose#11058]
Using a null for default array cause a strange error:  `ValidationError: User validation failed: comments: Cannot read property '_id' of null`

```
new Schema({
	comments: {
		type: [
			{
				language: {
					type: Schema.Types.String,
					required: true,
				},
				text: {
					type: Schema.Types.String,
					required: true,
				},
			},
		],
		default: () => null, //happens when i use this
	},
});
```
Digging more into the source code, i found the source of the error:

```
Document.prototype.$__init = function(doc, opts) {
  this.isNew = false;
  this.$init = true;
  opts = opts || {};

  // handle docs with populated paths
  // If doc._id is not null or undefined
  if (doc._id != null && opts.populated && opts.populated.length) { // this line throws. as _id does not exist.
```
Which turns out that the doc is a `null` of the default array value. The culprit code is the check down here, when using `default: () => null,` an array is returned with one element being null: `[null]`
```
if (!('defaultValue' in this) || fn !== void 0) {
    this.default(function() {
      let arr = fn.call(this);
      if (!Array.isArray(arr)) {
        arr = [arr];  // this line creates an array of one element null because of the default function that returns null.
      }
      // Leave it up to `cast()` to convert this to a documentarray
      return arr;
    });
  }
```
which happens when we have `default: () => null,`

}

**Stacktrace**:
'TypeError: Cannot read property '_id' of null
    at EmbeddedDocument.Object.<anonymous>.Document.$__init (node_modules/mongoose/lib/document.js:574:11)
    at EmbeddedDocument.syncWrapper [as $__init] (node_modules/kareem/index.js:235:23)
    at EmbeddedDocument.Object.<anonymous>.Document.init (node_modules/mongoose/lib/document.js:554:8)
    at DocumentArrayPath.Object.<anonymous>.DocumentArrayPath.getDefault (node_modules/mongoose/lib/schema/documentarray.js:347:13)
    at $__applyDefaults (node_modules/mongoose/lib/document.js:439:24)
    at SingleNested.Document (node_modules/mongoose/lib/document.js:166:5)
    at SingleNested.Subdocument (node_modules/mongoose/lib/types/subdocument.js:39:12)
    at new SingleNested (node_modules/mongoose/lib/schema/SingleNestedPath.js:66:17)
    at SingleNestedPath.Object.<anonymous>.SingleNestedPath.cast (node_modules/mongoose/lib/schema/SingleNestedPath.js:181:12)
    at SingleNestedPath.Object.<anonymous>.SchemaType.applySetters (ode_modules/mongoose/lib/schematype.js:1106:12)
    at model.$set (node_modules/mongoose/lib/document.js:1280:20)
    at model.$set (node_modules/mongoose/lib/document.js:1024:16)
    at model.Document (node_modules/mongoose/lib/document.js:148:12)
    at model.Model (node_modules/mongoose/lib/model.js:105:12)
    at new model (node_modules/mongoose/lib/model.js:4727:15)

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
The expected behaviour, is to have no validation

**What is the expected behavior?**
I expect the array to be null and no validation being run.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose@5.12.5
mongodb@3.6.6
nodejs: v12.22.5

**Comment by IslandRhythms** [comment]
Please include the `isValidComments()` validator

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');
const {Schema} = mongoose;

const testSchema = new Schema({
	comments: {
		type: [
			{
				language: {
					type: Schema.Types.String,
					required: true,
				},
				text: {
					type: Schema.Types.String,
					required: true,
				},
			},
		],
		default: () => null, //happens when i use this
	},
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    await Test.create({

    });
}

run();
```
