### ISSUE TITLE
Strict flag possibly ignored when using arrayFilters

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#11062]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
We’re running a query to migrate a data structure, which generally works fine as long as we use `strict: false` to have Mongoose ignore unknown (old) schema data.

However, in this case we’re using arrayFilters and it seems Mongoose doesn’t like it when we use paths that are no longer defined on the schema, even with `strict: false`.

This is the query in question:

```
await mongoose
    .model('Foo')
    .updateMany({}, {
      $set: {'items.$[m].newProp': 'bar'},
    }, {
      strict: false,
      arrayFilters: [{
        'm.oldProp': false,
      }],
    })
```

So we’re basically changing any sub doc in the `items` array with `oldProp: false` to `newProp: 'bar'`

However, the query throws the following error:

```
Error: Could not find path "items.0.oldProp" in schema
  at _castArrayFilters (/node_modules/mongoose/lib/helpers/update/castArrayFilters.js:61:15)
  at castArrayFilters (/node_modules/mongoose/lib/helpers/update/castArrayFilters.js:15:3)
  at _castArrayFilters (/node_modules/mongoose/lib/query.js:2069:5)
  at model.Query._updateThunk (/node_modules/mongoose/lib/query.js:3917:3)
  at model.Query.<anonymous> (/node_modules/mongoose/lib/query.js:4030:23)
  at model.Query._wrappedThunk [as _updateMany] (/node_modules/mongoose/lib/helpers/query/wrapThunk.js:27:8)
  at /node_modules/kareem/index.js:279:20
  at _next (/node_modules/kareem/index.js:103:16)
  at /node_modules/kareem/index.js:508:38
  at processTicksAndRejections (node:internal/process/task_queues:78:11)
From previous event:
  at promiseOrCallback (/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
  at model.Query.exec (/node_modules/mongoose/lib/query.js:4562:10)
  at model.Query.Query.then (/node_modules/mongoose/lib/query.js:4645:15
```

It seems that the strict flag is perhaps not working properly with arrayFilters?
Possibly related to #10696?

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const mongoose = require('mongoose')
const {Schema} = mongoose
const uri = `mongodb://localhost:27017/test`
console.log(`Mongoose version: ${mongoose.version}`)

const ItemSchema = new Schema({
  newProp: {
    type: String,
  },
})

//Schema
const FooSchema = new Schema({
  foo: {
    type: String,
  },
  items: [ItemSchema],
})

//Model
const Foo = mongoose.model('Foo', FooSchema)

//Test function
async function test() {

  //Connect to database
  await mongoose.connect(uri)

  //Create new item
  const foo = {
    items: [
      {
        oldProp: false,
      },
      {
        oldProp: false,
      },
    ],
  }
  await Foo.create(foo, {strict: false})

  await Foo
    .updateMany({}, {
      $set: {'items.$[m].newProp': 'test'},
    }, {
      strict: false,
      arrayFilters: [{
        'm.oldProp': false,
      }],
    })
}

test()
```

**What is the expected behavior?**
Expecting for the script to update the items despite the `oldProp` not being present on the schema anymore, because we're using `strict: false`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 16.13.1
MongoDB 5.0.3
Mongoose 6.0.14

**Comment by adamreisnz** [comment]
Thanks for the fix!
