### ISSUE TITLE
Suddenly started to get this error

### ISSUE THREAD

**Issue by soroushBgm** [Automattic/mongoose#11379]
```
/root/project/node_modules/mongoose/lib/cursor/QueryCursor.js:144
QueryCursor.prototype.map = function(fn) {
                          ^

TypeError: Cannot assign to read only property 'map' of object '#<QueryCursor>'
    at Object.<anonymous> (/root/project/node_modules/mongoose/lib/cursor/QueryCursor.js:144:27)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/project/node_modules/mongoose/lib/query.js:12:21)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)

Node.js v17.5.0

```

I'm using the last version of mongoose.

**Comment by faradaytrs** [comment]
Same here, problem on node 17.5.0

**Comment by Maximusya** [comment]
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md#2022-01-18-version-1740-current-targos:
> [[9f5a873965](https://github.com/nodejs/node/commit/9f5a873965)] - (SEMVER-MINOR) stream: add map method to Readable (Benjamin Gruenbaum, Robert Nagy) [#40815](https://github.com/nodejs/node/pull/40815)

**Comment by Maximusya** [comment]
Ah, sorry, it duplicates https://github.com/Automattic/mongoose/issues/11377

**Comment by benjamingr** [comment]
@Maximusya I actually broke this in another change due to spec compliance rather in the change adding map https://github.com/nodejs/node/pull/41775

There is a revert PR open for Node and a Mongoose PR open to make mongoose still work with the tc39 iterator-helpers spec

**Comment by soroushBgm** [comment]
> Ah, sorry, it duplicates #11377

Yes this is the problem. Changing node version to latest LTS solved my problem.
