### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'defaults' in undefined

### ISSUE THREAD

**Issue by divomen** [Automattic/mongoose#11394]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

It crashes on validator when I run findOneAndUpdate with a nested field
```
TypeError: Cannot use 'in' operator to search for 'defaults' in undefined
    at SingleNested.Subdocument (/Users/dim/Projects/reps/mongoose_bug/node_modules/mongoose/lib/types/subdocument.js:23:20)
    at new SingleNested (/Users/dim/Projects/reps/mongoose_bug/node_modules/mongoose/lib/schema/SubdocumentPath.js:67:17)
    at SubdocumentPath.doValidate (/Users/dim/Projects/reps/mongoose_bug/node_modules/mongoose/lib/schema/SubdocumentPath.js:243:13)
    at /Users/dim/Projects/reps/mongoose_bug/node_modules/mongoose/lib/helpers/updateValidators.js:158:22
    at module.exports (/Users/dim/Projects/reps/mongoose_bug/node_modules/mongoose/lib/helpers/updateValidators.js:209:7)
    at /Users/dim/Projects/reps/mongoose_bug/node_modules/mongoose/lib/query.js:4093:9
    at promiseOrCallback (/Users/dim/Projects/reps/mongoose_bug/node_modules/mongoose/lib/helpers/promiseOrCallback.js:10:12)
    at model.Query.validate (/Users/dim/Projects/reps/mongoose_bug/node_modules/mongoose/lib/query.js:4088:10)
    at /Users/dim/Projects/reps/mongoose_bug/node_modules/kareem/index.js:375:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a repo to reproduce: https://github.com/divomen/mongoose_bug
Just run 
git clone https://github.com/divomen/mongoose_bug.git
yarn
yarn start

**What is the expected behavior?**

It mustn't crash.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

It looks like this bug appears in mongoose 6.1.4. Version 6.1.3 works fine
Current test environment:
nodejs 16.14.0
mongoose 6.2.1
mongodb 4.2.18

**Comment by IslandRhythms** [comment]
`InvalidTypeError: "TestDoc.myID"'s Type is invalid! Type is: "undefined"`

**Comment by divomen** [comment]
I have just tested it on another machine with the same result
```
macmini:Projects dim$ git clone https://github.com/divomen/mongoose_bug.git
Cloning into 'mongoose_bug'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 0), reused 11 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.

macmini:Projects dim$ cd mongoose_bug/

macmini:mongoose_bug dim$ yarn
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 14.37s.

macmini:mongoose_bug dim$ yarn start
yarn run v1.22.17
$ yarn build; node build/index
$ tsc
TypeError: Cannot use 'in' operator to search for 'defaults' in undefined
    at SingleNested.Subdocument (/Users/dim/Projects/mongoose_bug/node_modules/mongoose/lib/types/subdocument.js:23:20)
    at new SingleNested (/Users/dim/Projects/mongoose_bug/node_modules/mongoose/lib/schema/SubdocumentPath.js:67:17)
    at SubdocumentPath.doValidate (/Users/dim/Projects/mongoose_bug/node_modules/mongoose/lib/schema/SubdocumentPath.js:243:13)
    at /Users/dim/Projects/mongoose_bug/node_modules/mongoose/lib/helpers/updateValidators.js:158:22
    at module.exports (/Users/dim/Projects/mongoose_bug/node_modules/mongoose/lib/helpers/updateValidators.js:209:7)
    at /Users/dim/Projects/mongoose_bug/node_modules/mongoose/lib/query.js:4093:9
    at promiseOrCallback (/Users/dim/Projects/mongoose_bug/node_modules/mongoose/lib/helpers/promiseOrCallback.js:10:12)
    at model.Query.validate (/Users/dim/Projects/mongoose_bug/node_modules/mongoose/lib/query.js:4088:10)
    at /Users/dim/Projects/mongoose_bug/node_modules/kareem/index.js:375:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
✨  Done in 6.14s.
```

**Comment by divomen** [comment]
> InvalidTypeError: "TestDoc.myID"'s Type is invalid! Type is: "undefined"

this can happen if you don't add
```
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
```
to your tsconfig.json

**Comment by AbdelrahmanHafez** [comment]
Welcome @divomen 👋

This seems to be an issue that's not caused by the TypeScript types.
Can you simplify the reproduction script to a JS script that does not use typegoose?

Here's [an example](https://github.com/Automattic/mongoose/issues/11421#issuecomment-1043835312) of a reproduction script that might make it easier for us to find the root cause.

Thanks.

**Comment by divomen** [comment]
Yes, I will do it

**Comment by divomen** [comment]
Added js version also.
```
git clone https://github.com/divomen/mongoose_bug.git
yarn
yarn start
```

**Comment by AbdelrahmanHafez** [comment]
Thanks @divomen 
### 11394.js
```js
it('deeply nested fields with `type` (gh-11394)', async() => {
    const userSchema = new mongoose.Schema({
      myId: Number,
      address: {
        _id: false,
        type: {
          city: {
            type: {
              zipCode: {
                type: { value: { type: Number } }
              }
            }
          }
        }
      }
    });

    const User = db.model('User', userSchema);

    const err = await User.findOneAndUpdate(
      { myId: 1 },
      { myId: 1, address: { city: { zipCode: { value: 1 } } } },
      { runValidators: true }
    ).then(() => null, err => err);

    console.log(err);

    assert.ok(err === null);
  });
```
### Output:
```
TypeError: Cannot use 'in' operator to search for 'defaults' in undefined
    at SingleNested.Subdocument (\mongoose\lib\types\subdocument.js:23:20)
    at new SingleNested (\mongoose\lib\schema\SubdocumentPath.js:66:17)
    at SubdocumentPath.doValidate (\mongoose\lib\schema\SubdocumentPath.js:242:13)
    at \mongoose\lib\helpers\updateValidators.js:158:22
    at module.exports (\mongoose\lib\helpers\updateValidators.js:209:7)
    at \mongoose\lib\query.js:4105:9
    at promiseOrCallback (\mongoose\lib\helpers\promiseOrCallback.js:10:12)
    at model.Query.validate (\mongoose\lib\query.js:4100:10)
    at \mongoose\node_modules\kareem\index.js:372:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
