### ISSUE TITLE
Cast to Number failed for value "{ money: { name: 'money', type: 'NUMBER', value: 10000 } }" (type Object) at path "money"

### ISSUE THREAD

**Issue by Darksimus1** [Automattic/mongoose#11440]
I have a function
```js
async function updateUserDB(userId, guildId, moneyId) {
  try {
    await getUserDB(guildId, userId);

    await UserModel.findOneAndUpdate({ guild_id: guildId, user_id: userId, money: moneyId });
  } catch (error) {
    logger.error("UPDATE_USER_DB", error);
  }
}
```

And code: 

```js
await bot.utils.updateUserDB(interaction.guildId, member.user.id, {
	money: amount
});
```

Mongoose gives me this error:
```
Cast to Number failed for value "{ money: { name: 'money', type: 'NUMBER', value: 10000 } }" (type Object) at path "money"
```

Can anyone help me?

**Comment by AbdelrahmanHafez** [comment]
Welcome @Darksimus1 

The error here is saying that you're trying to assign `{ money: { name: 'money', type: 'NUMBER', value: 10000 } }` to a field where it's expecting a number.

It's not clear yet without the stack trace which line of the two snippets you added is the culprit.
Try changing one or both of the following:

### First snippet
#### From 
```js
await UserModel.findOneAndUpdate({ guild_id: guildId, user_id: userId, money: moneyId });
```
#### To
```js
await UserModel.findOneAndUpdate({ guild_id: guildId, user_id: userId, money: moneyId.money.value });
```

### Second snippet
#### From
```js
await bot.utils.updateUserDB(interaction.guildId, member.user.id, {
	money: amount
});
```
#### To
```js
await bot.utils.updateUserDB(interaction.guildId, member.user.id, {
	money: amount.money.value
});
```

I'll close this issue, for now, let me know if this doesn't solve the issue you're facing.

**Comment by Darksimus1** [comment]
Hello, @AbdelrahmanHafez

I tried changing code snippets, but nothing worked. Mongoose doesn't throw errors, but the database doesn't update either. The first snippet didn't work, it threw an error:
`TypeError: Cannot read properties of undefined (reading 'value')`
Second snippet of code with no errors worked, but the problem did not change.
![image](https://user-images.githubusercontent.com/50050567/155081679-b7ca6dcd-f542-4124-9dba-f151efb33c48.png)

**Comment by AbdelrahmanHafez** [comment]
Can you revert both snippets to the old version, and paste the full error, including the error stack?

**Comment by Darksimus1** [comment]
```
CastError: Cast to Number failed for value "{ money: { name: 'money', type: 'NUMBER', value: 1000 } }" (type Object) at path "money"
    at model.Query.exec (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\query.js:4650:21)
    at model.Query.Query.then (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\query.js:4749:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  messageFormat: undefined,
  stringValue: `"{ money: { name: 'money', type: 'NUMBER', value: 1000 } }"`,
  kind: 'Number',
  value: { money: { name: 'money', type: 'NUMBER', value: 1000 } },
  path: 'money',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

    assert.ok(!isNaN(val))

      at castNumber (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\cast\number.js:27:10)
      at SchemaNumber.cast (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\schema\number.js:380:12)
      at SchemaNumber.SchemaType.applySetters (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\schematype.js:1179:12)
      at SchemaNumber.SchemaType._castForQuery (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\schematype.js:1614:15)
      at SchemaNumber.castForQuery (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\schema\number.js:434:14)
      at SchemaNumber.SchemaType.castForQueryWrapper (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\schematype.js:1581:20)
      at castUpdateVal (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\helpers\query\castUpdate.js:527:19)
      at walkUpdatePath (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\helpers\query\castUpdate.js:260:22)
      at castUpdate (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\helpers\query\castUpdate.js:96:7)
      at model.Query._castUpdate (C:\Users\Darksim\Documents\Projects\shiny-fiesta\node_modules\mongoose\lib\query.js:4859:10) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  },
  valueType: 'Object'
}
```

**Comment by Darksimus1** [comment]
```js
const { model, Schema, models } = require("mongoose");

const userSchema = new Schema({
	guild_id: { type: String, required: true },
	user_id: { type: String, required: true },
	money: { type: Number }
});
```

**Comment by Uzlopak** [comment]
It really seems that you pass an Object to the money field. And then mongoose can not cast it to a number.

I also dont understand why you call getUserDb. Seems actually quite scary as it seems that you provoke a race condition there, if you switch the database in an async function, while maybe another async function also switches the database at the same time?

please provide the console log of moneyId and the result of findOneAndUpdate

```javascript
async function updateUserDB(userId, guildId, moneyId) {
  try {
    await getUserDB(guildId, userId);
    console.log(moneyId);

    const result = await UserModel.findOneAndUpdate({ guild_id: guildId, user_id: userId, money: moneyId });
    console.log(result);
  } catch (error) {
    logger.error("UPDATE_USER_DB", error);
  }
}

```

**Comment by Darksimus1** [comment]
moneyId:
```
{ money: { name: 'money', type: 'NUMBER', value: 1000 } }
```
result is empty
I call a function getUserDB to check if the user is in the database:
```js
async function getUserDB(guildId, userId, moneyId) {
  try {
    let db = await UserModel.findOne({ guild_id: guildId, user_id: userId, money: moneyId });

    if (!db) {
      db = await addUserDB(guildId, userId);
    }

    return db;
  } catch (error) {
    logger.error("GET_USER_DB", error);
  }
}
```

**Comment by Uzlopak** [comment]
Then it should be actually:

```javascript
async function updateUserDB(userId, guildId, moneyId) {
  try {
    await getUserDB(guildId, userId);
    console.log(moneyId);

    const result = await UserModel.findOneAndUpdate({ guild_id: guildId, user_id: userId, money: moneyId.money.value });
    console.log(result);
  } catch (error) {
    logger.error("UPDATE_USER_DB", error);
  }
}
```

**Comment by Darksimus1** [comment]
result:
```js
{
  _id: new ObjectId("62137c0928a5f79a2514c887"),
  guild_id: '538986721484865536',
  user_id: '899717238876168212',
  money: 1000,
  __v: 0
}```

**Comment by Uzlopak** [comment]
So it is correct now?

**Comment by Darksimus1** [comment]
No
![image](https://user-images.githubusercontent.com/50050567/155409259-ad131c35-9243-406e-87f2-52e5ba013f5f.png)

**Comment by Uzlopak** [comment]
Well what is the code of your test then?

**Comment by Darksimus1** [comment]
I got an error. For some reason the guildId and userId data are sent to Mongoose mixed up

**Comment by Darksimus1** [comment]
but I don't understand why

**Comment by Uzlopak** [comment]
How does your balance code look like?

**Comment by Darksimus1** [comment]
```js
const { MessageEmbed } = require("discord.js");

module.exports = {
  name: "balance",
  description: "Your (or user's) balance.",
  category: "games",
  options: [{
    type: 6,
    name: "user",
    description: "Mention user.",
    required: false	
  }],
  async execute(bot, interaction) {
	let userId = interaction.options.get("user") || interaction
	let userBalance = await bot.utils.getUserDB(interaction.guildId, userId.user.id);
    const embed = new MessageEmbed()
        .setTitle(`Balance`)
        .addField(`User`, `<@${userBalance.user_id}>`)
        .addField(`Balance`, '$' + userBalance.money)
        .setColor("RANDOM")
        .setTimestamp();
		
    return interaction.reply({ embeds: [embed], ephemeral: true });
  }
}
```

**Comment by Uzlopak** [comment]
Ok, this gets really really into the deep... I dont think that we can help you further without having the full code.

**Comment by Darksimus1** [comment]
OK, I think this problem no longer applies to Mongoose. Thanks for your help!
