### ISSUE TITLE
Jest tests failing after updating to 6.2.4

### ISSUE THREAD

**Issue by thebishaldeb** [Automattic/mongoose#11525]
**Do you want to request a *feature* or report a *bug*?**

*Bug* 

**What is the current behavior?**

Jest Tests are not running not running in typescript.
It shows the following error after updating to 6.2:

```
node_modules\mongoose\node_modules\mongodb\src\bson.ts:1
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import type {
                                                                                        ^^^^^^
SyntaxError: Cannot use import statement outside a module
at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
at Object.<anonymous> (node_modules/mongoose/node_modules/mongodb/src/bson.ts:10:12)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

It started happening after updating to mongoose 6.2.4 
The jest tests are throwing the above error on runnig jest command.

`tsconfig.json` 

```
{
  "include": ["src", "typings/*.d.ts", "__tests__", "migrate-mongo-config.js"],
  "exclude": ["node_modules", "build"],
  "noImplicitAny": false,
  "compilerOptions": {
    "baseUrl": "./src",
    "module": "esnext",
    "esModuleInterop": true,
    "target": "esnext",
    "noImplicitAny": false,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "removeComments": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "types": ["jest", "node"],
    "typeRoots": ["./src/types", "node_modules/@types"]
  }
}
```

**What is the expected behavior?**

Successful tests run.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose - 6.2.4
Node - v12.19.0
MongoDB - 3.6.11 (for tests)

**Comment by vkarpov15** [comment]
What version did you upgrade from? Also, can you please provide a GitHub repo that demonstrates this issue?

Also worth mentioning: [we strongly recommend using any testing framework _other than_ Jest](https://mongoosejs.com/docs/jest.html). Jest is an extremely buggy runtime and we don't test against Jest, so bugs may happen. And Jest is so different from Node that tests that work in Jest may fail in Node or vice versa.

**Comment by Sotatek-LocNguyen3** [comment]
i have the same issue, do you have the solution? thanks

**Comment by Uzlopak** [comment]
This is imho not a typescript bug. 

Mongoose is not requiring the typescript files of bson package. I think you are importing somewhere the typescript files in your code by requiring from mongoose/node_modules/bson
