### ISSUE TITLE
Cast to string failed for value "BSONRegExp { pattern: 'xxxxx', options: 'i' }

### ISSUE THREAD

**Issue by robert-nash** [Automattic/mongoose#11597]
Hello,

I have an internal tool where (trusted) users can enter queries to select groups of users to send notifications to which works like this using EJSON from the bson package.

```
const usersQuery = UserModel.find(EJSON.deserialize(query));
```

This works well normally but I have a problem when trying to enter regex like below I get an error.

```
{"email":{"$regex":"@foo.com", "$options":"i"}}
```

```
CastError: Cast to string failed for value \"BSONRegExp { pattern: '@food.com', options: 'i' }\" (type BSONRegExp) at path \"email\" for model \"User\"\n    at model.Query.exec (/app/node_modules/mongoose/lib/query.js:4641:21)\n    at model.Query.Query.then (/app/node_modules/mongoose/lib/query.js:4740:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Should it be possible to do this using the bson package? Am I doing something wrong or is BSONRegExp not supported?

Thanks!

**Comment by IslandRhythms** [comment]
Please modify the script below to demonstrate your issue.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({name: '@foo.com'});
    await Test.create({ name: 'adfadfasdf' });

    const result = await Test.findOne({name: {$regex: '@foo.com', $options: 'i'}});
    console.log(result);
}

run();
```

**Comment by robert-nash** [comment]
Hi @IslandRhythms, thanks for your help.

Here is a script showing the problem:

```
const mongoose = require("mongoose");
const { EJSON } = require("bson");

const testSchema = new mongoose.Schema({
  name: String,
});

const Test = mongoose.model("Test", testSchema);

async function run() {
  await mongoose.connect("mongodb://localhost:27017");
  await mongoose.connection.dropDatabase();

  const document_1 = await Test.create({ name: "@foo.com" });
  const document_2 = await Test.create({ name: "adfadfasdf" });

  // Works
  const result_1 = await Test.find({
    name: { $regex: "@foo.com", $options: "i" },
  });
  console.log("result_1", result_1);

  // Works
  const result_2 = await Test.find(EJSON.deserialize({ name: "@foo.com" }));
  console.log("result_2", result_2);

  // Works
  const result_3 = await Test.find(
    EJSON.deserialize({ _id: { $oid: document_1._id.toString() } })
  );
  console.log("result_3", result_3);

  // Does not work
  const result_4 = await Test.find(
    EJSON.deserialize({ name: { $regex: "@foo.com", $options: "i" } })
  );
  console.log("result_4", result_4);
}

run();

```

Thanks!

**Comment by robert-nash** [comment]
Thanks!
