### ISSUE TITLE
[BUG] 使用事务时DeleteMany方法报错

### ISSUE THREAD

**Issue by CodeDreamfy** [Automattic/mongoose#11726]
**情景描述**
当我使用`Model`进行`deleteMany()`操作的时候，传入了`{ session }`报错了,当不加`session`时候可以正常执行

**使用的`Node.js`、`Mongoose`和`MongoDB`的版本**
* `Mac OS 10.15.7`
* `Nodejs v14.15`
* `MongoDB v5.0.6`
* `Mongoose  v6.3.1`

控制台报错如下：
```bash
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Topology'
    |     property 's' -> object with constructor 'Object'
    |     property 'sessionPool' -> object with constructor 'ServerSessionPool'
    --- property 'topology' closes the circle
    at JSON.stringify (<anonymous>)
    at /Users/CodeDream/github/node-project/koaDemo/src/middleware/mongoose_log.js:21:23
    at Immediate.wrapperCallback (/Users/github/node-project/koaDemo/node_modules/mquery/lib/mquery.js:2822:23)
    at Immediate.<anonymous> (/Users/github/node-project/koaDemo/node_modules/mquery/lib/utils.js:127:16)
    at processImmediate (internal/timers.js:461:21)
```

**预期行为**
类似于`insertMany`一样正常执行

部分代码如下：
```js
//  Model
const mongoose = require('mongoose');
const BaseModel = require('./base_model')
const Schema = mongoose.Schema

const MappingSchema = new Schema({
  bookmarks_id: { type: String, ref: 'Bookmarks'},
  tag_id: { type: String, ref: 'Tags'},
})

MappingSchema.plugin(BaseModel)

MappingSchema.pre('save', function(next){
  next();
});

mongoose.model('TagsMapping', MappingSchema);

```
```js
// proxy
const TagsMappingModel = mongoose.model('TagsMapping')

exports.updatedBookmarks = async obj => {
  const session = await mongoose.startSession()
  try {
    await session.startTransaction()
    await BookmarksModel.findOneAndUpdate({
      id: obj.id
    }, {
      bookmark_name: obj.name,
      bookmark_desc: obj.desc,
      url: obj.url
    }, { session })
    // 这里报错 Error
    await TagsMappingModel.deleteMany({
      bookmarks_id: obj.id
    }, { session })
    if(Array.isArray(obj.tags)) {
      const insertMany = obj.tags.map(tagId => ({
        bookmarks_id: obj.id,
        tag_id: tagId
      }))
      await TagsMappingModel.insertMany(insertMany, { session }) 
    }
    await session.commitTransaction()
    await session.endSession()
  } catch (e) {
    await session.abortTransaction()
    session.endSession()
    logger.error(e)
  }
}
```

**Comment by IslandRhythms** [comment]
We need the `BaseModel` file to be able to attempt to reproduce this.

**Comment by CodeDreamfy** [comment]
> We need the `BaseModel` file to be able to attempt to reproduce this.

基础model实际上是给schema上加的方法
```js
var tools = require('../utils/tools');

module.exports = function (schema) {
  schema.methods.create_at_ago = function () {
    return tools.formatDate(this.create_at, true);
  };

  schema.methods.update_at_ago = function () {
    return tools.formatDate(this.update_at, true);
  };
};
```

**Comment by vkarpov15** [comment]
Hard to tell without `BookmarksModel`. But the below script executes without error, so please modify the below script to demonstrate your issue.

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema

const MappingSchema = new Schema({
  bookmarks_id: { type: String, ref: 'Bookmarks'},
  tag_id: { type: String, ref: 'Tags'},
});

const TagsSchema = new Schema({
});

const TagsMappingModel = mongoose.model('TagsMapping', MappingSchema);
const Tags = mongoose.model('Tags', TagsSchema);
const BookmarksModel = mongoose.model('Bookmarks', Schema({
  bookmark_name: String,
  bookmark_desc: String,
  url: String,
  tags: ['ObjectId']
}));

run().catch(err => {
  console.error(err);
  process.exit(-1);
});

async function run() {
  await mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=rs');
  await BookmarksModel.deleteMany({});
  await TagsMappingModel.deleteMany({});

  await BookmarksModel.create({});
  const obj = { tags: [new mongoose.Types.ObjectId] };
  const session = await mongoose.startSession()
  try {
    await session.startTransaction()
    await BookmarksModel.findOneAndUpdate({
    }, {
      bookmark_name: 'test',
      bookmark_desc: 'test',
      url: 'test'
    }, { session })
    /*await TagsMappingModel.deleteMany({
      bookmarks_id: obj.id
    }, { session })*/
    if(Array.isArray(obj.tags)) {
      const insertMany = obj.tags.map(tagId => ({
        bookmarks_id: obj.id,
        tag_id: tagId
      }))
      await TagsMappingModel.insertMany(insertMany, { session })
      console.log('Insert many completed');
    }
    await session.commitTransaction()
    await session.endSession()
  } catch (e) {
    console.error(e);
    await session.abortTransaction()
    session.endSession()
  }

  console.log('Done');
}
```
