### ISSUE TITLE
Error with overlapping updates under array and map "Updating the path [..] would create a conflict at [..]"

### ISSUE THREAD

**Issue by johnpeb** [Automattic/mongoose#11764]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Assigning fields of an object under an array as well as assigning the object itself fails to save. See script below
```
 % npx ts-node scripts/mongoose
MongoServerError: Updating the path 'list.0.quantity' would create a conflict at 'list.0.quantity'
    at [..]/node_modules/mongodb/src/operations/update.ts:174:44
    at [..]/node_modules/mongodb/src/cmap/connection_pool.ts:482:13
    at handleOperationResult ([..]/node_modules/mongodb/src/sdam/server.ts:538:14)
    at Connection.onMessage ([..]/node_modules/mongodb/src/cmap/connection.ts:452:5)
    at MessageStream.<anonymous> ([..]/node_modules/mongodb/src/cmap/connection.ts:267:56)
    at MessageStream.emit (node:events:390:28)
    at MessageStream.emit (node:domain:475:12)
    at processIncomingData ([..]/node_modules/mongodb/src/cmap/message_stream.ts:168:12)
    at MessageStream._write ([..]/node_modules/mongodb/src/cmap/message_stream.ts:65:5)
    at writeOrBuffer (node:internal/streams/writable:389:12) {
  index: 0,
  code: 40,
  [Symbol(errorLabels)]: Set(0) {}
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
import { Schema } from 'mongoose';
import * as mongoose from 'mongoose'

run().catch(err => console.log(err));

async function run(): Promise<void> {
  await mongoose.connect('mongodb://localhost:27017/test-mongoose', {});
  await mongoose.connection.dropDatabase();

  const Test = mongoose.model('Test', new Schema({
    list: [{
      quantity: {
        value: Number,
        unit: String
      }
    }]
  }));

  await Test.create({list: [{quantity: {value: 1, unit: 'case'}}]});

  let doc = await Test.findOne();
  doc.list[0].quantity.value = null
  doc.list[0].quantity.unit = null
  doc.list[0].quantity = null // < If this is omitted there is no problem
  await doc.save();

  process.exit()
}
```

**What is the expected behavior?**
Save() does not throw error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 6.3.2
mongo v4.2.8
node v16.13.1

**Comment by johnpeb** [comment]
The same issue occurs under a map too. Let me know if I should create a separate issue.
```
import { Schema } from 'mongoose';
import * as mongoose from 'mongoose'

run().catch(err => console.log(err));

async function run(): Promise<void> {
  await mongoose.connect('mongodb://localhost:27017/test-mongoose', {});
  await mongoose.connection.dropDatabase();
  mongoose.set('debug', true)

  const Test = mongoose.model('Test', new Schema({
    map: {
      type: Map,
      of: {
        _id: false,
        quantity: {
          value: Number,
          unit: String
        },
      }
    }
  }));

  await Test.create({map: {key: {quantity: {value: 1, unit: 'case'}}}});

  let doc = await Test.findOne();
  doc.get('map.key').quantity.value = null
  doc.get('map.key').quantity.unit = null
  doc.get('map.key').quantity = null // < If this is omitted there is no problem
  await doc.save();

  process.exit()
}
```
