### ISSUE TITLE
UNCAUGHT_EXCEPTION: MongoServerSelectionError: connection <monitor> to 127.0.0.1:27017 closed

### ISSUE THREAD

**Issue by briankariuki** [Automattic/mongoose#11783]
**What is the current behavior?**

I'm using mongoose with socketIO, i'm broadcasting a user's cursor on a webpage to other connected clients. After a while when server is running the following error is thrown in the console. It crashes the server.

``` 
UNCAUGHT_EXCEPTION: MongoServerSelectionError: connection <monitor> to 127.0.0.1:27017 closed
    at Timeout._onTimeout (/Users/brian/Documents/Work/transcribe/transcribe-service/node_modules/mongodb/src/sdam/topology.ts:606:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  [stack]: 'MongoServerSelectionError: connection <monitor> to 127.0.0.1:27017 closed\n' +
    '    at Timeout._onTimeout (/Users/brian/Documents/Work/transcribe/transcribe-service/node_modules/mongodb/src/sdam/topology.ts:606:30)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)',
  [message]: 'connection <monitor> to 127.0.0.1:27017 closed',
  reason: TopologyDescription {
    type: 'Single',
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        _hostAddress: new HostAddress('localhost:27017'),
        address: 'localhost:27017',
        type: 'Unknown',
        hosts: [ [length]: 0 ],
        passives: [ [length]: 0 ],
        arbiters: [ [length]: 0 ],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 142917417,
        lastWriteDate: 0,
        error: MongoNetworkError: connection <monitor> to 127.0.0.1:27017 closed
            at Connection.onClose (/Users/brian/Documents/Work/transcribe/transcribe-service/node_modules/mongodb/src/cmap/connection.ts:355:13)
            at Socket.<anonymous> (/Users/brian/Documents/Work/transcribe/transcribe-service/node_modules/mongodb/src/cmap/connection.ts:269:42)
            at Socket.emit (node:events:526:28)
            at Socket.emit (node:domain:475:12)
            at TCP.<anonymous> (node:net:687:12) {
          [stack]: 'MongoNetworkError: connection <monitor> to 127.0.0.1:27017 closed\n' +
            '    at Connection.onClose (/Users/brian/Documents/Work/transcribe/transcribe-service/node_modules/mongodb/src/cmap/connection.ts:355:13)\n' +
            '    at Socket.<anonymous> (/Users/brian/Documents/Work/transcribe/transcribe-service/node_modules/mongodb/src/cmap/connection.ts:269:42)\n' +
            '    at Socket.emit (node:events:526:28)\n' +
            '    at Socket.emit (node:domain:475:12)\n' +
            '    at TCP.<anonymous> (node:net:687:12)',
          [message]: 'connection <monitor> to 127.0.0.1:27017 closed',
          [Symbol(errorLabels)]: Set(0) {},
          [name]: [Getter],
          [errmsg]: [Getter],
          [errorLabels]: [Getter]
        },
        [hostAddress]: [Getter],
        [allHosts]: [Getter],
        [isReadable]: [Getter],
        [isDataBearing]: [Getter],
        [isWritable]: [Getter],
        [host]: [Getter],
        [port]: [Getter]
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined,
    [error]: [Getter],
    [hasKnownServers]: [Getter],
    [hasDataBearingServers]: [Getter]
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {},
  [name]: [Getter],
  [errmsg]: [Getter],
  [errorLabels]: [Getter]
}
```

**Here's my mongoose connection function**

```
mongoURI = 'mongodb://localhost:27017/transcribe'
export async function initDb(): Promise<void> {
  await mongoose.connect(config.mongoURI, {
   
    // useUnifiedTopology: true,
    // useNewUrlParser: true,
    // useCreateIndex: true,
    // useFindAndModify: false,
  
  });

  const connection = mongoose.connection;

  connection.on('error', () => {
    console.log(`unable to connect to database: ${config.mongoURI}`);
  });

 
  connection.once('open', () => {
    console.log('MongoDB database connection established successfully');
  });
}
```

**What is the expected behavior?**

Error should be thrown in the connection.on('error', ()={}) handler.

**What are the versions of Node.js, Mongoose and MongoDB you are using?**

```
Mongoose v6.3.1
Nodejs v16.14.2
mongodb v5.0.6
macOS Monterey v12.3.1 
```

``` 
//tsconfig.json

{
    "compilerOptions": {
      "target": "es6",
      "lib": ["es6", "esnext.asynciterable"],
      "typeRoots": ["./node_modules/@types", "src/types"],
      "types": [],
      "allowSyntheticDefaultImports": true,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "forceConsistentCasingInFileNames": true,
      "moduleResolution": "node",
      "module": "commonjs",
      "pretty": true,
      "sourceMap": true,
      "outDir": "./build",
      "allowJs": true,
      "noEmit": false,
      "esModuleInterop": true,
      "resolveJsonModule": true,
      "skipLibCheck": true
    },
    "include": ["./src/**/*"],
    "exclude": ["./node_modules", "./.history", ".env"],
    "rules": {
      "prefer-const": [true, {
        "destructuring": "any"
      }],
    },
    "ts-node": {
      "compilerOptions": {
        "module": "CommonJS",
        "esModuleInterop": true,
        "resolveJsonModule": true,
      }
    }
  }

```

**Comment by briankariuki** [comment]
> ```ts
> const mongoose = require('mongoose');
> mongoose.connection.on('error', () => {
>     console.log(`unable to connect to database`);
>   });
> 
>  
>   mongoose.connection.once('open', () => {
>     console.log('MongoDB database connection established successfully');
>   });
> async function initDb(): Promise<void> {
>   await mongoose.connect('mongodb://localhost:27017', {
>    
>     // useUnifiedTopology: true,
>     // useNewUrlParser: true,
>     // useCreateIndex: true,
>     // useFindAndModify: false,
>   
>   });
> 
>   
>   console.log('done');
> }
> 
> initDb()
> ```

This block of code looks similar to what I have.

**Comment by IslandRhythms** [comment]
The `open` event handler won't fire with the way you have yours set up. You call connect, and then the event handlers, so the only thing that will fire is the `error` handler if there is an error. I could not reproduce your bug with your version of the script, and my version of the script. You can try and modify my script to reproduce the bug. If you are still experiencing the bug on your machine with my script, then it is a problem with your set up, and therefore not a mongoose bug.
