### ISSUE TITLE
arrayFilters do not capture the filter

### ISSUE THREAD

**Issue by LordLucass** [Automattic/mongoose#11992]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.0

### Node.js version

18.3.0

### MongoDB version

5.0.9

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

5.18.6-arch

### Issue

Whenever I try to use a function that contains arrayFilters I get a stacktrace and don't know how to proceed, so I require your help.

```js
// Function:

  async decreaseDurability (itemID, amount = 1) {
    if ((await this.itemData(itemID))?.durability - amount <= 0) return (await this.breakTool(itemID), false);
    console.log(itemID) // 0e85fe4b
    return this._users.update(this.user,
      { $inc: { "inventory.items.$[item].durability": -amount } },
      { arrayFilters: [{ "item._id": itemID }] }
    );
  }

// The code snippet that executes the decreaseDurability() function
        if (!await ToolManager.decreaseDurability(item._id, 1))
          return this.client.createMessage(message, t("commands:Wood.BrokenAxe"));
```
```js
// The error
// The itemID exists and it always returns, but arrayFilters doesn't get it, and replaces it with 0.
[26/06/2022 19:32:45] [Uncaught Promise Error] - Error: Could not find path "inventory.items.0._id" in schema
    at _castArrayFilters (/home/lucas/Bots/Isis/node_modules/mongoose/lib/helpers/update/castArrayFilters.js:74:15)
    at castArrayFilters (/home/lucas/Bots/Isis/node_modules/mongoose/lib/helpers/update/castArrayFilters.js:28:3)
    at _castArrayFilters (/home/lucas/Bots/Isis/node_modules/mongoose/lib/query.js:2186:5)
    at model.Query._updateThunk (/home/lucas/Bots/Isis/node_modules/mongoose/lib/query.js:4141:3)
    at model.Query.<anonymous> (/home/lucas/Bots/Isis/node_modules/mongoose/lib/query.js:4265:23)
    at model.Query._wrappedThunk [as _updateOne] (/home/lucas/Bots/Isis/node_modules/mongoose/lib/helpers/query/wrapThunk.js:27:8)
    at /home/lucas/Bots/Isis/node_modules/kareem/index.js:426:25
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by LordLucass** [comment]
I forgot to mention it, but this occurs with all functions that have an arrayFilter.

**Comment by LordLucass** [comment]
I have located the error, the `strict` option in the schema must be set to `false` to avoid this problem. Closing now.
