### ISSUE TITLE
"Can't extract geo keys: ... Point must only contain numeric elements"

### ISSUE THREAD

**Issue by haosmos** [Automattic/mongoose#12025]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.0

### Node.js version

18.2.0

### MongoDB version

Atlas

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Issue

I'm trying to create a document where there is a location property - it should be an object on the map. Just a dot on the map.
Here is my schema:

```
const mongoose = require('mongoose');

const tourSchema = new mongoose.Schema(
    {
      // some properties .... 
      startLocation: {
        // GeoJSON
        type: {
          type: String,
          default: 'Point',
          enum: [ 'Point' ]
        },
        coordinates: [ Number ],
        address: String,
        description: String
      },
      locations: [
        {
          type: {
            type: String,
            default: 'Point',
            enum: [ 'Point' ]
          },
          coordinates: [ Number ],
          address: String,
          description: String,
          day: Number
        }
      ],
      guides: [
        {
          // type: mongoose.Schema.Types.ObjectId,
          type: mongoose.Schema.ObjectId,
          ref: 'User'
        }
      ]
    },
    {
      toJSON: { virtuals: true },
      toObject: { virtuals: true }
    }
);
```

I gave the coordinates the type "Number" as you can see.

Here is the object I want to create:

```
{
    "name": "new test tour",
    "maxGroupSize": 1,
    "duration": 1,
    "difficulty": "easy",
    "price": 260,
    "summary": "Test tour pre",
    "imageCover": "tour-3-cover.jpg" 
}
```
And here is the error I'm getting:

```
{
    "status": "error",
    "error": {
        "index": 0,
        "code": 16755,
        "statusCode": 500,
        "status": "error"
    },
    "message": "Can't extract geo keys: { _id: ObjectId('62be0376a21a4971eb1570be'), 
name: \"new test tour\", rating: 4.5, duration: 1, maxGroupSize: 1, difficulty: \"easy\", 
ratingsAverage: 4.5, ratingsQuantity: 0, price: 260, summary: \"Test tour pre\", 
imageCover: \"tour-3-cover.jpg\", images: [], createdAt: new Date(1656619871324), 
startDates: [], secretTour: false, startLocation: { type: \"Point\", coordinates: [] }, guides: [], 
locations: [], slug: \"new-test-tour\", __v: 0 }  Point must only contain numeric elements",
    "stack": "MongoServerError: Can't extract geo keys: { _id: ObjectId('62be0376a21a4971eb1570be'), 
name: \"new test tour\", rating: 4.5, duration: 1, maxGroupSize: 1, difficulty: \"easy\", ratingsAverage: 4.5, 
ratingsQuantity: 0, price: 260, summary: \"Test tour pre\", imageCover: \"tour-3-cover.jpg\", images: [], 
createdAt: new Date(1656619871324), startDates: [], secretTour: false, startLocation: { type: \"Point\", 
coordinates: [] }, guides: [], locations: [], slug: \"new-test-tour\", __v: 0 }  
Point must only contain numeric elements\n    at /home/chaosmos/projects/natours/node_modules/mongodb/lib/operations/insert.js:53:33\n    at /home/chaosmos/projects/natours/node_modules/mongodb/lib/cmap/connection_pool.js:277:25\n    at /home/chaosmos/projects/natours/node_modules/mongodb/lib/sdam/server.js:212:17\n    
at handleOperationResult (/home/chaosmos/projects/natours/node_modules/mongodb/lib/sdam/server.js:335:20)\n   
 at Connection.onMessage (/home/chaosmos/projects/natours/node_modules/mongodb/lib/cmap/connection.js:222:9)\n    
at MessageStream.<anonymous> 
(/home/chaosmos/projects/natours/node_modules/mongodb/lib/cmap/connection.js:63:60)\n    
at MessageStream.emit (node:events:527:28)\n    at processIncomingData (/home/chaosmos/projects/natours/node_modules/mongodb/lib/cmap/message_stream.js:132:20)\n    
at MessageStream._write (/home/chaosmos/projects/natours/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    
at writeOrBuffer (node:internal/streams/writable:390:12)"
}
```
Judging by the mistake: "Can't extract geo keys: ... Point must only contain numeric elements", - I should give the coordinates the type "Number", but I already gave the coordinates the type "Number".

When I import an array of objects (tours) with a script:

```
// Read JSON file
const tours = JSON.parse(fs.readFileSync(`${__dirname}/tours.json`, 'utf-8'));

// import data into DB
const importData = async () => {
  try {
    await Tour.create(tours);
    console.log('Database of tours, users and reviews loaded successfully: ');
  } catch (err) {
    console.log(err);
  }
  process.exit();
};
```
- objects are correctly stored in the database:

![MongoDBCompass_ZeS97gii1E](https://user-images.githubusercontent.com/30666874/176774950-30bfb94b-1065-4d53-b1e7-9a898c002d54.png)

What am I doing wrong and how can I fix this problem?

**Comment by vkarpov15** [comment]
Read the error message. The below object doesn't contain `startLocation`.

```
{
    "name": "new test tour",
    "maxGroupSize": 1,
    "duration": 1,
    "difficulty": "easy",
    "price": 260,
    "summary": "Test tour pre",
    "imageCover": "tour-3-cover.jpg" 
}
```

Make sure `startLocation.coordinates` is an array with 2 numeric elements and this error should go away.
