### ISSUE TITLE
mongoose dosen't throw error when network disconnected

### ISSUE THREAD

**Issue by uuuuuup** [Automattic/mongoose#12063]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.0

### Node.js version

16.13.1

### MongoDB server version

5.0.7

### Description

Mongoose dosen't throw error when network is disconnected.
When I call mongoose find function, I can not get error.
So server is stuck forever and can not send response to user.

When I call mongodb find function with the mongoose connection, and I can get below error.
MongoServerSelectionError: connect ECONNREFUSED x,x,x,x:27017
    at Timeout._onTimeout

I use nest.js framework for server.

### Steps to Reproduce

1. start mongo server
2. start nest.js server
3. nest.js server connect to mongo server
4. stop mongo server
5. I send GET command to nest.js server
6. nest.js server execute find function
7. wait timeout

### Expected Behavior

Mongoose should throw error.

**Comment by vkarpov15** [comment]
Mongoose will throw a `MongooseServerSelectionError` after `serverSelectionTimeoutMS`. `serverSelectionTimeoutMS` is 30000 (30 seconds) by default, which is why it seems like the server is stuck, but it actually isn't.

**Comment by uuuuuup** [comment]
@vkarpov15 

OK, I got error as below.
TypeError: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:563:9)
    at new URL (node:internal/url:643:5)
    at isAtlas (/node_modules/mongoose/lib/helpers/topology/isAtlas.js:17:17)
    at MongooseServerSelectionError.assimilateError (/node_modules/mongoose/lib/error/serverSelection.js:35:35)

It can be caught as below.
process.on('uncaughtException', () => {})

But I could not catch with below code.
    try {
      call.save();
    } catch (err) {
      console.log(err);
    }
Can I catch the error with try / catch?

When I use mongodb api not mongoose api, I could catch the error with try / catch.

**Comment by vkarpov15** [comment]
`try { await call.save(); } catch (err) { ... }`
