### ISSUE TITLE
UpdateOne with upsert on BulkWrite throws a TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by cenowador** [Automattic/mongoose#12261]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.1

### Node.js version

16.15.1

### MongoDB server version

5.0.10 Enterprise

### Description

Using the upsert option of updateOne/updateMany with bulkWrite throws a TypeError [ERR_INVALID_ARG_TYPE]. The same piece of code that throws an error with upsert work just fine without it.

### Steps to Reproduce

Consider the following piece of code:
```
const opBulk = [];
operator.rows.forEach(row =>{
    const parsed = parseOperatorImport(row); //a regular js object that fits the model
    opBulk.push({
        'updateOne':{
            'filter': {uid: parsed.uid},
            'update': {$set: parsed},
            'upsert': true //if this line is removed the operation succeeds
        }
    });
});
await Operator.bulkWrite(opBulk);
```
If not using upsert it works. When you add the `upsert: true` option on the bulkInsert, it throws
```
TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received null
    at randomUUID (node:internal/crypto/random:398:5)
    at SchemaString.SchemaType.getDefault (C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\schematype.js:1123:31)
    at C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\helpers\setDefaultsOnInsert.js:81:28
    at Schema.eachPath (C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\schema.js:1343:5)
    at module.exports (C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\helpers\setDefaultsOnInsert.js:76:10)
    at C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\helpers\model\castBulkWrite.js:68:11
    at C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\model.js:3569:35
    at each (C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\helpers\each.js:11:5)
    at C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\model.js:3569:5
    at C:\Users\santo\Desktop\uppay\uppaybackend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
```

**Comment by cenowador** [comment]
Found the issue (that also happens with single updateOne). The key here, and that is missing on the original post, is that I'm using `randomUUID` from crypto to generate an uid field in the document. a sample model that throws:
```
const {randomUUID} = require('crypto');
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const schema = new Schema({
    uid:{
        type: String,
        default: randomUUID,
    }
});

module.exports = mongoose.model('Machine', schema);
```

however, if I do like this, it works, which implies that Mongoose is calling the method specified in `default` with a null argument, which makes it throw.
```
function generateUid(){
    return randomUUID();
}

const schema = new Schema({
    uid:{
        type: String,
        default: generateUid,
    }
});
```

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');
const { randomUUID } = require('crypto');
const testSchema = new mongoose.Schema({
  name: String
});

const cryptoSchema = new mongoose.Schema({
  uid: {
    type: String,
    default: randomUUID()
  }
});

const Crypto = mongoose.model('Crypto', cryptoSchema);

const Test = mongoose.model('Test', testSchema);
async function withoutCrypto() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  await Test.bulkWrite([{ updateOne: { filter: {name: 'Test'}, update: {$set: {name: 'Testerson'}}, upsert: true }}]);
  console.log('done');
}

withoutCrypto();

async function withCrypto() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  await Crypto.bulkWrite([{ updateOne: { filter: {uid: randomUUID()}, update: {$set: { uid: randomUUID() }}, upsert: true }}]);
  console.log('done');
}

withCrypto();
```

**Comment by cenowador** [comment]
Thanks for the reply!

There is a difference in your example and the problem: you're calling `randomUUID()` directly on the model, which will return a string that will be used as uid for everyone (running your code, it produces a single element that has been repeatedly updated). The problem occurs when you pass the function to the `default`, as in `default: randomUUID`, instead of the result of the function itself. Replace your schema with this one and it should fail.

```
const cryptoSchema = new mongoose.Schema({
  uid: {
    type: String,
    default: randomUUID
  }
});
```

**Comment by vkarpov15** [comment]
@cenowador this is expected behavior, because Mongoose calls your `default()` function with multiple arguments. Mongoose calls the `default()` function with the document being updated.

Correct syntax is as follows:

```javascript
const cryptoSchema = new mongoose.Schema({
  uid: {
    type: String,
    default: () => randomUUID()
  }
});
```

This ensures `randomUUID` gets the arguments you expect, as opposed to what Mongoose passes in.
