### ISSUE TITLE
when querying with $in, array is expected to be all strings when mongo shell excepts objects

### ISSUE THREAD

**Issue by j4ys0n** [Automattic/mongoose#12302]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.2

### Node.js version

16.14.2

### MongoDB server version

4.4.11

### Description

Mongoose expects items in the `$in` array to be strings. Mongo shell accepts objects.

```
/Users/username/Code/attributions-datastore/node_modules/mongoose/lib/query.js:4803
  const castError = new CastError();
                    ^
CastError: Cast to string failed for value "{ '$regex': '100k', '$options': 'i' }" (type Object) at path "attributions" for model "Attribution"
    at model.Query.exec (/Users/username/Code/attributions-datastore/node_modules/mongoose/lib/query.js:4803:21)
    at model.Query.Query.then (/Users/username/Code/attributions-datastore/node_modules/mongoose/lib/query.js:4902:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  messageFormat: undefined,
  stringValue: `"{ '$regex': '100k', '$options': 'i' }"`,
  kind: 'string',
  value: { '$regex': '100k', '$options': 'i' },
  path: 'attributions',
  reason: null,
  valueType: 'Object'
```

### Steps to Reproduce

submit a query with an object in the `$in` array, like `{"attributions":{"$in":[{"$regex":"100k","$options":"i"}]}}`

### Expected Behavior

No error, results returned. This works in the mongo shell.

**Comment by IslandRhythms** [comment]
https://www.mongodb.com/docs/manual/reference/operator/query/in/#use-the--in-operator-with-a-regular-expression
This is expected behavior
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {

  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({ name: 'Test' });

  const result = await Test.find({name: {$in: ['Test']}});
  console.log(result);
}

run();
```

**Comment by j4ys0n** [comment]
right - the docs do say that, but it does actually work in the mongo shell. so either they don't realize that or didn't update the docs.

**Comment by vkarpov15** [comment]
@j4ys0n nesting `$regex` under `$in` doesn't work on any version of the mongo shell AFAIK. For example, the following is the error I get when trying to run your example with MongoDB server v4.4.16 and mongo shell v4.4.16:

```
> db.test.findOne({"attributions":{"$in":[{"$regex":"100k","$options":"i"}]}})
uncaught exception: Error: error: {
	"ok" : 0,
	"errmsg" : "cannot nest $ under $in",
	"code" : 2,
	"codeName" : "BadValue"
} :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DBCommandCursor@src/mongo/shell/query.js:703:15
DBQuery.prototype._exec@src/mongo/shell/query.js:112:28
DBQuery.prototype.hasNext@src/mongo/shell/query.js:287:5
DBCollection.prototype.findOne@src/mongo/shell/collection.js:260:10
@(shell):1:1
> 
```
