### ISSUE TITLE
Throw when setting a key name that match the discriminator key name

### ISSUE THREAD

**Issue by abarriel** [Automattic/mongoose#12517]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.3

### Node.js version

16

### MongoDB server version

4.9.1

### Description

Hello, I have a discriminator key to kind in the root doc  but I also have a subSchema which contains a field name kind.
When I am setting the sub field Kind, it throw an error.

### Steps to Reproduce

```javascript
const mongoose = require("mongoose");

mongoose.set("strict", "throw");

const options = { discriminatorKey: "kind"};

const EventSchema = new mongoose.Schema(
  { name: String, kind: String, animals: { kind: String, world: String } },
  options
);

const Event = mongoose.model("Event", EventSchema);

const ClickedLinkEvent = Event.discriminator(
  "ClickedLink",
  new mongoose.Schema({ url: String }, options)
);

async function main() {
  await mongoose.connect("mongodb://localhost:27017");

  const eventDoc = await Event.findByIdAndUpdate(
    { _id: mongoose.Types.ObjectId() },
    {
      $set: {
        name: "name",
        animals: { kind: "kind", world: "world" },
      },
    },
    {
    }
  );

  console.log(eventDoc);
}

main();

```

**Comment by abarriel** [comment]
We should use prefix imo.
[castUpdate.js#L172](https://github.com/Automattic/mongoose/blob/master/lib/helpers/query/castUpdate.js#L172)

```js
const prefix = pref ? pref + '.' : '';
```

**Comment by abarriel** [comment]
This is an error, I am not changing the discriminator key here @hasezoey

**Comment by hasezoey** [comment]
> I am changing a key which happens to be the same name as a discriminator key on top level.
> I am updating `animals.kind` and not `kind`

didnt see that, thanks for clarifying

**Comment by hasezoey** [comment]
can reproduce

<details>
<summary>Code</summary>

```ts
// NodeJS: 18.8.0
// MongoDB: 5.0 (Docker)
// Typescript 4.8.4
import * as mongoose from 'mongoose'; // mongoose@6.6.3

mongoose.set('strict', 'throw');

const options = { discriminatorKey: 'kind' };

const EventSchema = new mongoose.Schema({ name: String, kind: String, animals: { kind: String, world: String } }, options);

const Event = mongoose.model('Event', EventSchema);

const ClickedLinkEvent = Event.discriminator('ClickedLink', new mongoose.Schema({ url: String }, options));

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, {
    dbName: 'verifyMASTER',
  });

  const eventDoc = await Event.findByIdAndUpdate(
    { _id: new mongoose.Types.ObjectId() },
    {
      $set: {
        name: 'name',
        // error "Can't modify discriminator key "kind" on discriminator model", even though its a different "kind"
        animals: { kind: 'kind', world: 'world' },
      },
    },
    {}
  );

  console.log(eventDoc);

  await mongoose.disconnect();
})();
```

</details>

Reproduction Repository / Branch: https://github.com/typegoose/typegoose-testing/tree/mongooseGh12517

output:

```txt
/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/helpers/query/castUpdate.js:201
        const err = new Error('Can\'t modify discriminator key "' + key + '" on discriminator model');
                    ^

Error: Can't modify discriminator key "kind" on discriminator model
    at walkUpdatePath (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/helpers/query/castUpdate.js:201:21)
    at walkUpdatePath (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/helpers/query/castUpdate.js:307:20)
    at castUpdate (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/helpers/query/castUpdate.js:97:7)
    at model.Query._castUpdate (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/query.js:5104:10)
    at Query._findAndModify (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/query.js:3989:29)
    at model.Query.<anonymous> (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/query.js:3470:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (/mnt/projects/nodejs/typegoose-testing/node_modules/mongoose/lib/helpers/query/wrapThunk.js:29:8)
    at /mnt/projects/nodejs/typegoose-testing/node_modules/kareem/index.js:426:25
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```
