### ISSUE TITLE
TypeError: Invalid URL while migrating from mongoose v5.10.0 to v6.7.2

### ISSUE THREAD

**Issue by pawan-saxena** [Automattic/mongoose#12671]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.2

### Node.js version

16.16.0

### MongoDB version

4.4.17

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

macos Monterey v12.5.1

### Issue

Hi all,
I want to migrate the mongoose from v5.10.0 to v6.7.2
I am following these two migration guides :
https://mongoosejs.com/docs/migrating_to_6.html 
https://github.com/mongodb/node-mongodb-native/blob/HEAD/etc/notes/CHANGES_4.0.0.md

My clusters uses replicaset with 3 nodes.
I am using below config :
```
let options = {
        serverSelectionTimeoutMS: 5000,
        retryWrites : true,
        appName: 'testAppName'
        replicaSet: 'test-replicaset',
        maxIdleTimeMS: 150000, 
        wtimeoutMS: 0, 
        w: "majority", 
        autoIndex: false,
        maxPoolSize: 10,
        keepAlive: true, 
        connectTimeoutMS: 60000
    };
```

`mongoose.connect(mongo_server_uri + '/' + database, options);`

my mongo_server_uri looks like this : 
`mongodb+srv://username:password@development.xyz.mongodb.net`
and database takes the value : 'abc'

so above would become:
`mongoose.connect('mongodb+srv://username:password@development.xyz.mongodb.net/abc',options)`

I am using mongoose : 6.7.2
mongodb server version : 4.4.17
node version : 16.16.0
os : macos Monterey v12.5.1

I get below error : 

```
TypeError: Invalid URL: mongodb+srv://username:password@development.xyz.mongodb.net/abc
      at new URLImpl (/root_path/node_modules/whatwg-url/lib/URL-impl.js:21:13)
      at Object.exports.setup (/root_path/node_modules/whatwg-url/lib/URL.js:54:12)
      at new URL (/root_path/node_modules/whatwg-url/lib/URL.js:115:22)
      at new URLWithoutHost (/root_path/node_modules/mongodb-connection-string-url/lib/index.js:74:1)
      at new ConnectionString (/root_path/node_modules/mongodb-connection-string-url/lib/index.js:126:13)
      at parseOptions (/root_path/node_modules/mongodb/lib/connection_string.js:200:17)
      at new MongoClient (/root_path/node_modules/mongodb/lib/mongo_client.js:45:63)
      at /root_path/node_modules/mongoose/lib/connection.js:801:16
      at Promise._execute (/root_path/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/root_path/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/root_path/node_modules/bluebird/js/release/promise.js:103:10)
      at NativeConnection.Connection.openUri (/root_path/node_modules/mongoose/lib/connection.js:798:19)
      at Mongoose.createConnection (/root_path/node_modules/mongoose/lib/index.js:359:10)
      at module.exports (/root_path/index.js:125:27)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /root_path/bin/something.js:14:15,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined
} reason: TypeError: Invalid URL: mongodb+srv://username:password@development.xyz.mongodb.net/abc
```

Any help would be much appreciated.
Thanks

**Comment by Uzlopak** [comment]
The notation `mongodb+srv` is new to me. Try `mongodb` instead.

**Comment by pawan-saxena** [comment]
@vkarpov15  can you please me out here ?

**Comment by IslandRhythms** [comment]
The docs you linked don't use `mongodb+srv`. Try what Uzlopak suggested

**Comment by pawan-saxena** [comment]
@IslandRhythms  it does please scroll down a bit in docs
https://mongoosejs.com/docs/connections.html#replicaset_connections

**Comment by IslandRhythms** [comment]
Have you tried appending this to the connection string? `?retryWrites=true&w=majority`

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

mongoose.connection.on('connected', function() {
  console.log('I have connected!')
})

async function run() {
  await mongoose.connect('mongodb+srv://MeanITAdmin:admin@cluster0.6esgv.mongodb.net/?retryWrites=true&w=majority');
  console.log('yo')
}

run();
```

**Comment by pawan-saxena** [comment]
Fist of all I am really very sorry that though I resolved the issue but didn't update here.

The issue was another npm library - excel-export : [excel-export](https://www.npmjs.com/package/excel-export).
Though @vkarpov15  pointed that this couldn't be the root cause back in 2019 but I am sure now that it is as when I removed this specific library initialisation from code base (after spending 18 hours and backtracking line by line), I found though this library doesn't have anything to do with MongoDB or Mongoose in general still it gives some issues.

Not sure what is happening, I replaced it with [exceljs](https://www.npmjs.com/package/exceljs).

**Comment by vkarpov15** [comment]
@pawan-saxena I don't have an exact explanation for why this is happening, but you're right that this happens with `excel-export`. Explicitly with one of excel-export's dependencies, the [`collections` package](https://www.npmjs.com/package/collections).

The [collections package adds a lot of custom global properties](https://github.com/montagejs/collections/blob/master/shim-object.js), one of which is likely mixing up the MongoDB Node driver's [whatwg-url URL parser](https://www.npmjs.com/package/whatwg-url).

**Comment by OP-Klaus** [comment]
I think I have a similar problem but I'm not sure how to debug it. The below error happens when I run Jest tests after upgrading from Mongoose 5 to 6. Do you have any tips about how to debug?

```
    TypeError: Cannot convert undefined or null to object
        at Function.getPrototypeOf (<anonymous>)

      at Object.<anonymous> (../../../node_modules/mongodb-connection-string-url/node_modules/whatwg-url/lib/utils.js:34:39)
      at Object.<anonymous> (../../../node_modules/mongodb-connection-string-url/node_modules/whatwg-url/lib/URL.js:4:15)
```

**Comment by vkarpov15** [comment]
@OP-Klaus please open a new issue and follow the issue template. Stack trace isn't very helpful. Best we can do is advise you to not use Jest, or at least make sure you've followed our [Jest testing guide](https://mongoosejs.com/docs/jest.html)

**Comment by jpstotz** [comment]
From my understanding mongoose 5.x did not had this compatibility problem, so wouldn't it be a good idea to mention the `collections` incompatibility in the [Migrating from 5.x to 6.x](https://mongoosejs.com/docs/migrating_to_6.html#migrating-from-5x-to-6x) document? 

I was also running into this problem and because of the very generic error message this issue is hard to find. Thus it took me quite some time to find the cause and to end up here.

**Comment by Taremeh** [comment]
The error mentioned by @OP-Klaus and @jpstotz is still present for me with all mongoose versions except 5.x:

```
/workspaces/my-app/apps/api/dist/index.js:14992
    var AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(function() {
                                        ^

TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at ../../node_modules/mongodb-connection-string-url/node_modules/whatwg-url/lib/utils.js (/workspaces/my-app/apps/api/dist/index.js:14992:41)
    at __require (/workspaces/my-app/apps/api/dist/index.js:34:52)
    at ../../node_modules/mongodb-connection-string-url/node_modules/whatwg-url/lib/URL.js (/workspaces/my-app/apps/api/dist/index.js:17446:17)
    at __require (/workspaces/my-app/apps/api/dist/index.js:34:52)
    at ../../node_modules/mongodb-connection-string-url/node_modules/whatwg-url/webidl2js-wrapper.js (/workspaces/my-app/apps/api/dist/index.js:17792:15)
    at __require (/workspaces/my-app/apps/api/dist/index.js:34:52)
    at ../../node_modules/mongodb-connection-string-url/node_modules/whatwg-url/index.js (/workspaces/my-app/apps/api/dist/index.js:17803:36)
    at __require (/workspaces/my-app/apps/api/dist/index.js:34:52)
    at ../../node_modules/mongodb-connection-string-url/lib/index.js (/workspaces/my-app/apps/api/dist/index.js:17932:24)

Node.js v20.11.1
```

Any idea how to fix it?

**Comment by vkarpov15** [comment]
@Taremeh can you provide a script that demonstrates the issue you're seeing? What build system are you using to compile your app?
