### ISSUE TITLE
MongooseServerSelectionError: connect ECONNREFUSED <not 127.0.0.1>

### ISSUE THREAD

**Issue by Elpistolero131** [Automattic/mongoose#12681]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

18.12.1

### MongoDB server version

5.0.13

### Description

I bought a mongodb server from my host and I have this error: `MongooseServerSelectionError: connect ECONNREFUSED <the ip of the db with the port>`

### Steps to Reproduce

My uri to connect the db is: `mongodb://admin:<the password>@<the ip of the db>:26041/Guilds?retryWrites=true&w=majority` I connect the db like that: `await mongoose.connect(config.MONGODB_GUILDS_URI)`.
And if I connect with a mongodb db not a db of my host it work. and this is all of the error: 
```
MongoServerError: Authentication failed.
    at Connection.onMessage (C:\Users\yassi.ABKAHOME\Documents\Bots-Discord\Bots-Test\UtilityBotTest\node_modules\mongodb\lib\cmap\connection.js:207:30)
    at MessageStream.<anonymous> (C:\Users\yassi.ABKAHOME\Documents\Bots-Discord\Bots-Test\UtilityBotTest\node_modules\mongodb\lib\cmap\connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (C:\Users\yassi.ABKAHOME\Documents\Bots-Discord\Bots-Test\UtilityBotTest\node_modules\mongodb\lib\cmap\message_stream.js:132:20)
    at MessageStream._write (C:\Users\yassi.ABKAHOME\Documents\Bots-Discord\Bots-Test\UtilityBotTest\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:513:28) {
  ok: 0,
  code: 18,
  codeName: 'AuthenticationFailed',
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}
```
I already change the password or other but nothing.

**Comment by IslandRhythms** [comment]
Hard to say without a script

**Comment by vkarpov15** [comment]
All we can really say is that your auth credentials are incorrect. Perhaps you need to set the authentication database, or perhaps you need to run `encodeURIComponent()` on your password because it contains special characters.

**Comment by andreWPatskan3** [comment]
same bug is reproducing without auth credentials at all. the problem occurs on Node.js v18.x.x but works good on v16.x.x

**Comment by Uzlopak** [comment]
@andreWPatskan3 Sounds like https://github.com/nodejs/node/issues/40537

**Comment by andreWPatskan3** [comment]
@Uzlopak it makes sense. thanks for the reply.

**Comment by HamoBoker** [comment]
I got same problem using node 18, i rolled back to 16 and everything works properly
