### ISSUE TITLE
Stack trace is lost when throwing an error

### ISSUE THREAD

**Issue by dudilugasi** [Automattic/mongoose#12792]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.8.0

### Node.js version

16.18.1

### MongoDB server version

6.0.3

### Description

i cannot see the full stack trace when mongoose is throwing an internal exception.

this is a problem for me because i cannot see from which lines the errors are thrown wihch makes it really hard to debug errors

### Steps to Reproduce

this is a simple application that creates an error from mongoose
```
//test.js
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test');

const Cat = mongoose.model('Cat', { name: String });

const express = require('express')
const app = express()
const port = 3434

app.get('/', async (req, res) => {
    try {
        const cat = await Cat.findById("sdfsdf");
        res.json(cat)
    } catch (e) {
        console.log(e)
        res.json(e.message);
    }
})

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
})
```

now if i enter http://localhost:3434 i will see in the console.log this stack trace

```
CastError: Cast to ObjectId failed for value "sdfsdf" (type string) at path "_id" for model "Cat"
    at model.Query.exec (test\node_modules\mongoose\lib\query.js:4897:21)
    at model.Query.Query.then (test\node_modules\mongoose\lib\query.js:4996:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  messageFormat: undefined,
  stringValue: '"sdfsdf"',
  kind: 'ObjectId',
  value: 'sdfsdf',
  path: '_id',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new BSONTypeError (test\node_modules\bson\lib\error.js:41:28)
      at new ObjectId (test\node_modules\bson\lib\objectid.js:67:23)
      at castObjectId (test\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at ObjectId.cast (test\node_modules\mongoose\lib\schema\objectid.js:246:12)
      at ObjectId.SchemaType.applySetters (test\node_modules\mongoose\lib\schematype.js:1201:12)
      at ObjectId.SchemaType._castForQuery (test\node_modules\mongoose\lib\schematype.js:1648:15)
      at ObjectId.SchemaType.castForQuery (test\node_modules\mongoose\lib\schematype.js:1636:15)
      at ObjectId.SchemaType.castForQueryWrapper (test\node_modules\mongoose\lib\schematype.js:1612:20)
      at cast (test\node_modules\mongoose\lib\cast.js:342:32)
      at model.Query.Query.cast (test\node_modules\mongoose\lib\query.js:5325:12),
  valueType: 'string'
}
```

instead of 
at
   test\index.js:12:15

**Comment by dudilugasi** [comment]
is there a reason why in query.js the executionStack is reset to null?

this._executionStack = null;

**Comment by dudilugasi** [comment]
https://mongoosejs.com/docs/promises.html

it seemes that i missed the part that i need to add exec() to get the full stack
