### ISSUE TITLE
Cannot set strictQuery: false globally and have an embedded discriminator

### ISSUE THREAD

**Issue by JavaScriptBach** [Automattic/mongoose#12796]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.8.0

### Node.js version

16.17.1

### MongoDB server version

4.4

### Description

Running the following code:
```javascript
const mongoose = require('mongoose');

mongoose.set("strictQuery", false);

const testSchema = new mongoose.Schema({
  test: [{foo: String}]
});

testSchema.path("test").discriminator("Bar", new mongoose.Schema({ bar: String }));

console.log('done');
```

Fails with:
```
Error: Can't customize discriminator option strictQuery (can only modify toJSON, toObject, _id, id, virtuals, methods)
    at merge (/.../node_modules/mongoose/lib/helpers/model/discriminator.js:174:17)
    at discriminator (/.../node_modules/mongoose/lib/helpers/model/discriminator.js:199:3)
    at DocumentArrayPath.discriminator (/.../node_modules/mongoose/lib/schema/documentarray.js:205:12)
...irrelevant stacks omitted
```

### Steps to Reproduce

See above

### Expected Behavior

I should be able to set `strictQuery: false` globally, but I can't because something about this implementation is broken with schemas that create embedded array discriminators.

**Comment by JavaScriptBach** [comment]
A hacky workaround is to add `strictQuery: true` to https://github.com/Automattic/mongoose/blob/master/lib/helpers/model/discriminator.js#L9, but that's likely not the correct long-term approach.

**Comment by IslandRhythms** [comment]
Update to latest and see if that resolves your issue
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  test: [{foo: String}]
});

testSchema.path("test").discriminator("Bar", new mongoose.Schema({ bar: String }));

console.log('done');
```

**Comment by JavaScriptBach** [comment]
Issue is still there on latest. You need to add `mongoose.set("strictQuery", false)` to repro it. So something like:



```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  test: [{foo: String}]
});

testSchema.path("test").discriminator("Bar", new mongoose.Schema({ bar: String }));

console.log('done');
```

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');
mongoose.set('strictQuery', false);
const testSchema = new mongoose.Schema({
  test: [{foo: String}]
});

testSchema.path("test").discriminator("Bar", new mongoose.Schema({ bar: String }));

console.log('done');
```
