### ISSUE TITLE
Documentation Clarification: Reconnection strategy is not clearly documented

### ISSUE THREAD

**Issue by titanism** [Automattic/mongoose#12962]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

There are several options in older versions such as `reconnectTries` and `reconnectIntervals` &ndash; and in newer versions we have `serverSelectionTimeoutMS` among others &ndash; and also over time, the documentation has become quite confusing, especially when some documentation links to blog posts that is related to MongoDB and does not mention Mongoose at all.

We suggest that there be a dedicated, new, and updated section regarding Reconnection Strategy.

The current documentation at <https://mongoosejs.com/docs/connections.html> mentions that `serverSelectionTimeoutMS` and `heartbeatFrequencyMS` is the new approach.   However if you set either to `Number.MAX_VALUE` you get the following error:

```sh
✖  error     MongooseServerSelectionError: Server selection timed out after 1.7976931348623157e+308 ms
    at NativeConnection.Connection.openUri (/Users/user/Projects/mongoose/node_modules/.pnpm/mongoose@6.9.0/node_modules/mongoose/lib/connection.js:825:32)
    at Mongoose.createConnection (/Users/user/Projects/mongoose/node_modules/.pnpm/mongoose@6.9.0/node_modules/mongoose/lib/index.js:351:10)
    at Mongoose.connect (/Users/user/Projects/mongoose/index.js:11:57)
    at /Users/user/Projects/mongoose/test/test.js:32:41
    at ExecutionContext.notThrowsAsync (file:///Users/user/Projects/mongoose/node_modules/.pnpm/ava@5.1.1/node_modules/ava/lib/assert.js:686:14)
    at /Users/user/Projects/mongoose/test/test.js:32:11
    at Test.callFn (file:///Users/user/Projects/mongoose/node_modules/.pnpm/ava@5.1.1/node_modules/ava/lib/test.js:507:21)
    at Test.run (file:///Users/user/Projects/mongoose/node_modules/.pnpm/ava@5.1.1/node_modules/ava/lib/test.js:520:23)
    at Runner.runSingle (file:///Users/user/Projects/mongoose/node_modules/.pnpm/ava@5.1.1/node_modules/ava/lib/runner.js:285:33)
    at Runner.runTest (file:///Users/user/Projects/mongoose/node_modules/.pnpm/ava@5.1.1/node_modules/ava/lib/runner.js:367:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async file:///Users/user/Projects/mongoose/node_modules/.pnpm/ava@5.1.1/node_modules/ava/lib/runner.js:532:21
    at async Runner.start (file:///Users/user/Projects/mongoose/node_modules/.pnpm/ava@5.1.1/node_modules/ava/lib/runner.js:540:15)
(node:58731) TimeoutOverflowWarning: 1.7976931348623157e+308 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

We suggest that the three following questions have clear and documented answers in the docs and elsewhere as needed:

1) What is the default retry strategy?  Specifically, how many retry attempts and what retry interval? 
2) How do you set a retry strategy for infinite retries?  Specifically, how do you have infinite retry attempts with a configurable retry interval?  Do you need to set a low `serverSelectionTimeoutMS` and on `disconnect` event trigger another `connect()` or `createConnection()` call?  Or is there a better command to use for this such as `conn.openUri()` as in `_handleReconnect` function in `lib/connections.js`?
3) Should users set `mongoose.set('bufferCommands', true);` for any of the two cases above?  There was a blog post written regarding `bufferMaxEntries`, but there is nothing else current up to date for latest version as far as we can see.

**Comment by vkarpov15** [comment]
1. In Mongoose 6, there's no longer the notion of being connected or disconnected. The MongoDB node driver will retry each individual operation for up to `serverSelectionTimeoutMS`.
2. Crank up `serverSelectionTimeoutMS` to something very high. Although we don't necessarily recommend doing this, because you may keep a user's request spinning for up to `serverSelectionTimeoutMS` if the database is down.
3. `bufferCommands` is true by default, so no need to set it to true. And `bufferCommands` only applies to the initial database connection anyway, not relevant for reconnects.
