### ISSUE TITLE
UUID "TypeError: Invalid schema configuration"

### ISSUE THREAD

**Issue by jmbldwn** [Automattic/mongoose#13241]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.3

### Node.js version

16.19.1

### MongoDB server version

4.2.0

### Description

Encountering what appears to be a bug in the UUID type.  I have a single field I'm adding via a plugin and it looks like the schema merging is getting confused.  The error message is pretty explanatory:
```
    TypeError: Invalid schema configuration: `00000000-0000-0000-0000-000000000000` is not a valid type at path `NIL`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.

      15 |     // archived flags deleted devices.  GC later
      16 |
    > 17 |     schema.add({
         |            ^
      18 |         documentId: {
      19 |             type: mongoose.Schema.Types.UUID,
      20 |             default: uuidv4,

      at Schema.add (node_modules/mongoose/lib/schema.js:677:13)
      at new Schema (node_modules/mongoose/lib/schema.js:134:10)
      at Schema.add (node_modules/mongoose/lib/schema.js:743:25)
      at add (services/hub/models/syncable.js:17:12)
      at Schema.Object.<anonymous>.Schema.plugin (node_modules/mongoose/lib/schema.js:1884:3)
      at Object.plugin (services/hub/models/circuit.js:10:8)
```

I have no idea why the type is coming across as NIL.  I've stepped through the code quite a bit and it looks like maybe the type definition for UUID is just wrong?

### Steps to Reproduce

Define a schema type UUID and add it to an existing schema:
```
    schema.add({
        documentId: {
            type: mongoose.Schema.Types.UUID,
            default: uuidv4,
            index: true
        },
```

### Expected Behavior

No error.

**Comment by jmbldwn** [comment]
Hmmm.  This appears to only happen when testing with Jest.

**Comment by vkarpov15** [comment]
@jmbldwn can you please create a sample project that demonstrates this issue? We'd need more info, like Jest version, configs, etc. in order to repro this.

We would also strongly recommend using any testing framework other than Jest.

**Comment by jmbldwn** [comment]
I actually solved this with a crafty Jest mock.  See https://stackoverflow.com/questions/73203367/jest-syntaxerror-unexpected-token-export-with-uuid-library/75924883#75924883

I agree on Jest; it's a pain but we're somewhat heavily invested in it.  Any suggestions that would be an easy conversion?
