### ISSUE TITLE
Unable to connect to MongoDB 6.0

### ISSUE THREAD

**Issue by TeodorKolev** [Automattic/mongoose#13270]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.3

### Node.js version

16.20.0

### MongoDB server version

5.2.0

### Typescript version (if applicable)

4.8.0

### Description

Error occurred right after Atlas upgraded to 6.0
Error:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
MongoError: user is not allowed to do action [createIndex] on [casecoach-staging.system.indexes]
    at Function.MongoError.create (C:\server\node_modules\connect-mongo\node_modules\mongodb-core\lib\error.js:31:11)
    at C:\server\node_modules\connect-mongo\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (C:\server\node_modules\connect-mongo\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (C:\server\node_modules\connect-mongo\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at TLSSocket.<anonymous> (C:\server\node_modules\connect-mongo\node_modules\mongodb-core\lib\connection\connection.js:333:22)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Steps to Reproduce

```
const mongoose = require('mongoose');
mongoose.connect(config.connectionString, { useNewUrlParser: true, autoIndex: false });
const db = mongoose.connection;
db.once('open', (err) => {
  if (err) {
    console.log(err);
  } else {
    console.log('Connected to mongoDb!');
  }
});
```

**Comment by vkarpov15** [comment]
Your stack trace shows that this error originates in a very old version of connect-mongo, **not** mongoose.
