### ISSUE TITLE
Comparison Query Operators Causes Find to Fail and Throw CastError When Called on a Mongoose Model

### ISSUE THREAD

**Issue by jmho** [Automattic/mongoose#13525]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.0

### Node.js version

18.16.0

### MongoDB server version

5.0.6

### Typescript version (if applicable)

5.1.3

### Description

I have a typescript module that defines my database functions using mongoose. I compile this module into Javascript using `tsc` and import those functions to use them in a separate module for my server. Database functions that use the `mongoose.model.find(...)` call fails in the server and throws a `CastError` whenever a Comparison Query Operators (`$gt`, `$lt`, `$in`, etc...) is used as apart of a query. This is strange as we follow the provided guidelines [here](https://mongoosejs.com/docs/queries.html) when structuring our query and using comparison operators.

During our investigations we found that calling `find(...)` on the `mongoose.connection.db.collection("...")` fixes this issue and causes the database function to perform as expected and to not throw an error. This has been used as a way to get around the issue but this is not ideal as `find(...)` called on a collection does not properly return types.

A stack trace from the reproduction project below is as follows:
`C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\schema\string.js:604
    throw new CastError('string', value, this.path, null, this);
          ^
CastError: Cast to string failed for value "{ '$in': [ 'test' ] }" (type Object) at path "test" for model "Test"
    at SchemaString.cast (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\schema\string.js:604:11)
    at SchemaString.SchemaType.applySetters (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\schematype.js:1204:12)
    at SchemaString.castForQuery (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\schema\string.js:688:15)
    at SchemaString.handleSingle (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\schematype.js:1546:15)
    at SchemaString.castForQuery (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\schema\string.js:681:20)
    at cast (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\cast.js:334:39)
    at model.Query.Query.cast (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\query.js:4874:12)
    at model.Query.Query._castConditions (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\query.js:2210:10)
    at model.Query._find (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\query.js:2236:8)
    at model.Query.exec (C:\Users\Justin\Desktop\Personal-Documents\Personal-code\mongoose-example\database\node_modules\mongoose\lib\query.js:4404:28)`

### Steps to Reproduce

Link to project reproducing this behavior [here](https://github.com/jmho/potential-mongoose-project-bug).

Main is in `server/src/index.ts`

The problematic find functions are in `database/src/test.ts`

### Expected Behavior

I expect the `find(...)` function to not fail when called on a `mongoose.model` with any comparison query operators.

**Comment by vkarpov15** [comment]
@MohOraby is right, you're getting this error because of [this line](https://github.com/jmho/potential-mongoose-project-bug/blob/4531880c29cc5ada87583634519fc29abf2fb8ef/database/src/setup.ts#L6). [Here's some more info on sanitizeFilter as well](https://thecodebarbarian.com/whats-new-in-mongoose-6-sanitizefilter.html). You would need to use `mongoose.trusted()` if you want to use `sanitizeFilter`.
