### ISSUE TITLE
arrays of arrays of type

### ISSUE THREAD

**Issue by aheckmann** [Automattic/mongoose#1361]
```js
[[]] // array of array of mixed
[[Number]] // array of array of number
[[String]]
[[[Number]]]
// etc
```

Useful for $geoIntersects

**Comment by CalvinScott** [comment]
Status on this? Been an issue lately with geoJson nested arrays

**Comment by vkarpov15** [comment]
No progress made unfortunately. I'll put this on the 4.3 milestone.

**Comment by jakehewitt** [comment]
Very disappointed that this was once again ignored. This has been an issue for 3 years and it's gone from milestone 4.0 -> 4.3 -> 4.5 now.

**Comment by vkarpov15** [comment]
Definitely not ignored, there have just been higher priority items. PRs are most welcome though.

**Comment by Fonger** [comment]
@vkarpov15 

The fix doesn't support custom schema as array of array.

[[CustomSchema]] or [[{ ... }]]

```json
/Users/xxx/yyy/node_modules/mongoose/lib/schema/array.js:59
    this.caster = new caster(null, castOptions);
                  ^

TypeError: caster is not a function
    at new SchemaArray (/Users/xxx/yyy/node_modules/mongoose/lib/schema/array.js:59:19)
    at Function.Schema.interpretAsType (/Users/xxx/yyy/node_modules/mongoose/lib/schema.js:533:12)
    at Schema.path (/Users/xxx/yyy/node_modules/mongoose/lib/schema.js:464:29)
    at Schema.add (/Users/xxx/yyy/node_modules/mongoose/lib/schema.js:348:12)
    at new Schema (/Users/xxxx/yyy/node_modules/mongoose/lib/schema.js:94:10)
```

**Comment by vkarpov15** [comment]
Thanks for testing @Fonger :)
