### ISSUE TITLE
How to resolve TypeError: Undefined type `Map`

### ISSUE THREAD

**Issue by gitparametriks** [Automattic/mongoose#13622]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

^4.13.21

### Node.js version

18.16.1

### MongoDB version

^5.6.0

### Operating system

macOS

### Issue

I'm getting this error when trying to deploy my application on fly.io. 

```
/app/node_modules/mongoose/lib/schema.js:673
      throw new TypeError('Undefined type `' + name + '` at `' + path +
            ^
  TypeError: Undefined type `Map` at `expensesByCategory`
    Did you try nesting Schemas? You can only nest using refs or arrays.
      at Schema.interpretAsType (/app/node_modules/mongoose/lib/schema.js:673:11)
      at Schema.path (/app/node_modules/mongoose/lib/schema.js:529:29)
      at Schema.add (/app/node_modules/mongoose/lib/schema.js:411:12)
      at new Schema (/app/node_modules/mongoose/lib/schema.js:105:10)
      at file:///app/models/KPI.js:51:19
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

This is the schema I'm using

```
const daySchema = new Schema(
  {
    date: String,
    revenue: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
    expenses: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
  },
  { toJSON: { getters: true } }
);

const monthSchema = new Schema(
  {
    month: String,
    revenue: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
    expenses: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
    operationalExpenses: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
    nonOperationalExpenses: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
  },
  { toJSON: { getters: true } }
);

const KPISchema = new Schema(
  {
    totalProfit: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
    totalRevenue: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
    totalExpenses: {
      type: mongoose.Types.Currency,
      currency: "USD",
      get: (v) => v / 100,
    },
    expensesByCategory: {
      type: Map,
      of: {
        type: mongoose.Types.Currency,
        currency: "USD",
        get: (v) => v / 100,
      },
    },
    monthlyData: [monthSchema],
    dailyData: [daySchema],
  },
  { timestamps: true, toJSON: { getters: true } }
);
```

Is there a way to resolve this without changing the behaviour of the schema. It works fine when I run the app locally. But im not able to deploy it on fly.io because of this reason.

**Comment by vkarpov15** [comment]
If you're using Mongoose 4.13 then this schema won't work, because [Map type support was introduced in Mongoose 5.1.0](https://github.com/Automattic/mongoose/blob/master/CHANGELOG.md#510--2018-05-10). You should upgrade to a more recent version of Mongoose - 4.x is no longer supported.
