### ISSUE TITLE
Error with replicaSet and mongoose.connection()

### ISSUE THREAD

**Issue by Noroxi** [Automattic/mongoose#13623]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.3

### Node.js version

19.0.1

### MongoDB version

6.0.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04.2 LTS

### Issue

Hi there, i search everywhere for a this issue but nothing help, i couldn't connect to my replicaSet with mongoose.connection, and i have error after a time of start the server.

This is the code of database conection:
```
mongoose.connect('mongodb://localhost:27017/database?replicaSet=rs0', {
    //useCreateIndex:true,
    //useNewUrlParser: true,
    //useUnifiedTopology: false,
    //useFindAndModify: false
})
    .then(db => {
        var conn = mongoose.connection;
        conn.once('open', function () {
            var gfs = Grid(conn.db, mongoose.mongo);
            gfs.collection('uploads');
        })
        conn.on('error', (err) => {
            console.log(err instanceof Error, err)
        })
        console.log('Database is connected');
    })
    .catch(err => {
        console.log(err)
    });
```
Actually i have tried : 
```
mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/database?replicaSet=rs0', {
    //useCreateIndex:true,
    //useNewUrlParser: true,
    //useUnifiedTopology: false,
    //useFindAndModify: false
})
    .then(db => {
        var conn = mongoose.connection;
        conn.once('open', function () {
            var gfs = Grid(conn.db, mongoose.mongo);
            gfs.collection('uploads');
        })
        conn.on('error', (err) => {
            console.log(err instanceof Error, err)
        })
        console.log('Database is connected');
    })
    .catch(err => {
        console.log(err)
    });
```
But nothing, i wanted to use mongo to try if maybe it is my replica set instance by this code:
```
const MongoClient = require('mongodb').MongoClient;

    let run = async function() {
      console.log('start')
      let opt = { useNewUrlParser: true, useUnifiedTopology: true}
      let conn = await MongoClient.connect(
        'mongodb://localhost:27017/test?authSource=admin&replicaSet=rs0',
        opt)
      console.log('db connected')
      console.log(await conn.db('database').collection('users').findOne())
      conn.close()
      console.log('db closed')
    }().catch(console.error)
```
and actually it works perfectly but after a time i get the error, but it return a object , so i supposed that its a problem related to mongoose
The error i get is: 
```
..../node_modules/mongodb/lib/sdam/topology.js:278
                const timeoutError = new error_1.MongoServerSelectionError(`Server selection timed out after ${serverSelectionTimeoutMS} ms`, this.description);
                                     ^

MongoServerSelectionError: getaddrinfo EAI_AGAIN undefined
    at Timeout._onTimeout (..../node_modules/mongodb/lib/sdam/topology.js:278:38)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'undefined:27017' => ServerDescription {
        address: 'undefined:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 11792434,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo EAI_AGAIN undefined
            at connectionFailureError (..../node_modules/mongodb/lib/cmap/connect.js:367:20)
            at Socket.<anonymous> (..../node_modules/mongodb/lib/cmap/connect.js:290:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: getaddrinfo EAI_AGAIN undefined
              at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
            errno: -3001,
            code: 'EAI_AGAIN',
            syscall: 'getaddrinfo',
            hostname: 'undefined'
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {}
}
```
This is my `rs.status()` return:
```
{
  set: 'rs0',
  date: ISODate("2023-07-18T22:51:39.763Z"),
  myState: 1,
  term: Long("15"),
  syncSourceHost: '',
  syncSourceId: -1,
  heartbeatIntervalMillis: Long("2000"),
  majorityVoteCount: 2,
  writeMajorityCount: 2,
  votingMembersCount: 3,
  writableVotingMembersCount: 3,
  optimes: {
    lastCommittedOpTime: { ts: Timestamp({ t: 1689720699, i: 1 }), t: Long("15") },
    lastCommittedWallTime: ISODate("2023-07-18T22:51:39.614Z"),
    readConcernMajorityOpTime: { ts: Timestamp({ t: 1689720699, i: 1 }), t: Long("15") },
    appliedOpTime: { ts: Timestamp({ t: 1689720699, i: 1 }), t: Long("15") },
    durableOpTime: { ts: Timestamp({ t: 1689720699, i: 1 }), t: Long("15") },
    lastAppliedWallTime: ISODate("2023-07-18T22:51:39.614Z"),
    lastDurableWallTime: ISODate("2023-07-18T22:51:39.614Z")
  },
  lastStableRecoveryTimestamp: Timestamp({ t: 1689720689, i: 1 }),
  electionCandidateMetrics: {
    lastElectionReason: 'electionTimeout',
    lastElectionDate: ISODate("2023-07-18T21:00:49.453Z"),
    electionTerm: Long("15"),
    lastCommittedOpTimeAtElection: { ts: Timestamp({ t: 0, i: 0 }), t: Long("-1") },
    lastSeenOpTimeAtElection: { ts: Timestamp({ t: 1689713792, i: 1 }), t: Long("14") },
    numVotesNeeded: 2,
    priorityAtElection: 1,
    electionTimeoutMillis: Long("10000"),
    numCatchUpOps: Long("0"),
    newTermStartDate: ISODate("2023-07-18T21:00:49.464Z"),
    wMajorityWriteAvailabilityDate: ISODate("2023-07-18T21:00:50.000Z")
  },
  members: [
    {
      _id: 0,
      name: 'localhost:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 6673,
      optime: { ts: Timestamp({ t: 1689720699, i: 1 }), t: Long("15") },
      optimeDate: ISODate("2023-07-18T22:51:39.000Z"),
      lastAppliedWallTime: ISODate("2023-07-18T22:51:39.614Z"),
      lastDurableWallTime: ISODate("2023-07-18T22:51:39.614Z"),
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1689714049, i: 1 }),
      electionDate: ISODate("2023-07-18T21:00:49.000Z"),
      configVersion: 1,
      configTerm: 15,
      self: true,
      lastHeartbeatMessage: ''
    },
    {
      _id: 1,
      name: 'localhost:27018',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 6653,
      optime: { ts: Timestamp({ t: 1689720689, i: 1 }), t: Long("15") },
      optimeDurable: { ts: Timestamp({ t: 1689720689, i: 1 }), t: Long("15") },
      optimeDate: ISODate("2023-07-18T22:51:29.000Z"),
      optimeDurableDate: ISODate("2023-07-18T22:51:29.000Z"),
      lastAppliedWallTime: ISODate("2023-07-18T22:51:39.614Z"),
      lastDurableWallTime: ISODate("2023-07-18T22:51:39.614Z"),
      lastHeartbeat: ISODate("2023-07-18T22:51:39.486Z"),
      lastHeartbeatRecv: ISODate("2023-07-18T22:51:38.483Z"),
      pingMs: Long("0"),
      lastHeartbeatMessage: '',
      syncSourceHost: 'localhost:27017',
      syncSourceId: 0,
      infoMessage: '',
      configVersion: 1,
      configTerm: 15
    },
    {
      _id: 2,
      name: 'localhost:27019',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 6130,
      optime: { ts: Timestamp({ t: 1689720699, i: 1 }), t: Long("15") },
      optimeDurable: { ts: Timestamp({ t: 1689720699, i: 1 }), t: Long("15") },
      optimeDate: ISODate("2023-07-18T22:51:39.000Z"),
      optimeDurableDate: ISODate("2023-07-18T22:51:39.000Z"),
      lastAppliedWallTime: ISODate("2023-07-18T22:51:39.614Z"),
      lastDurableWallTime: ISODate("2023-07-18T22:51:39.614Z"),
      lastHeartbeat: ISODate("2023-07-18T22:51:39.619Z"),
      lastHeartbeatRecv: ISODate("2023-07-18T22:51:38.930Z"),
      pingMs: Long("0"),
      lastHeartbeatMessage: '',
      syncSourceHost: 'localhost:27018',
      syncSourceId: 1,
      infoMessage: '',
      configVersion: 1,
      configTerm: 15
    }
  ],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1689720699, i: 1 }),
    signature: {
      hash: Binary(Buffer.from("0000000000000000000000000000000000000000", "hex"), 0),
      keyId: Long("0")
    }
  },
  operationTime: Timestamp({ t: 1689720699, i: 1 })
}
```

Thanks in advance!!!!

**Comment by vkarpov15** [comment]
One possible explanation is that Mongoose 5.13 doesn't support MongoDB 6. You need to upgrade to at least Mongoose 6.5 for MongoDB 6 support: https://mongoosejs.com/docs/compatibility.html.

Also, what is the `Grid()` class you're using?
