### ISSUE TITLE
Mongoose not connecting after implementing Port forwarding

### ISSUE THREAD

**Issue by Waurick** [Automattic/mongoose#13703]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.4

### Node.js version

18.14.0

### MongoDB server version

6.0.8

### Typescript version (if applicable)

5.1.6

### Description

I get the Error:

```
err = new ServerSelectionError();
          ^
MongooseServerSelectionError: connect ECONNREFUSED **My Server IP/ PORT**
    at _handleConnectionErrors (C:\Users\elias\source\repos\Website-Backend\node_modules\mongoose\lib\connection.js:791:11)
    at NativeConnection.openUri (C:\Users\elias\source\repos\Website-Backend\node_modules\mongoose\lib\connection.js:766:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { '**My Domain/ PORT**' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
```

### Steps to Reproduce

This makes no sense because I connect with Localhost through Port forwarding MongDB Compass uses the Same Connection String and works perfectly.

`mongodb://Username:Password.@localhost:PORT/?authMechanism=DEFAULT`

`ssh -L **PORT**:localhost:**PORT** **User**@**IP**`

I tried allready switching Ports etc. The only Sollution is to open the Port in the Firewall but that is not really practical and secure. I think Mongoose is logging in to then get the IP of the Source and than trying to connect with that IP for some reason? 

### Expected Behavior

It should just connect to the Local Ip/Port and not try to build the Connection with the Source IP.

**Comment by sean-daley** [comment]
Does using 127.0.0.1 instead of localhost work any better?

See the disclaimer about Node 18, IPv6, and localhost vs 127.0.0.1 here https://mongoosejs.com/docs/connections.html

**Comment by Waurick** [comment]
Yes i tried that allready.

**Comment by IslandRhythms** [comment]
Please update the below script to demonstrate your issue.
Also update your issue description to a valid version of mongoose.

```javascript
const mongoose = require('mongoose');

mongoose.connection.on('connected', () => {
  console.log('connected')
});

mongoose.connection.on('error', (err) => {
  console.log('what is the error', err);
})

mongoose.connection.on('disconnected', () => {
  console.log('disconnected');
})

async function run() {
  await mongoose.connect('mongodb://127.0.0.1');
  console.log('done');
  await mongoose.disconnect();
}

run();
```

**Comment by Waurick** [comment]
```
const mongoose = require('mongoose');

mongoose.connection.on('connected', () => {
  console.log('connected')
});

mongoose.connection.on('error', (err) => {
  console.log('what is the error', err);
})

mongoose.connection.on('disconnected', () => {
  console.log('disconnected');
})

async function run() {
  await mongoose.connect('mongodb://Username:Password.@localhost:PORT/?authMechanism=DEFAULT');
  console.log('done');
  await mongoose.disconnect();
}

run();

```

Same Error...

**Comment by IslandRhythms** [comment]
```
what is the error MongoRuntimeError: Unable to parse localhost:PORT with URL
    at new HostAddress (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\utils.js:771:34)
    at fromString (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\utils.js:813:16)
    ... 4 lines matching cause stack trace ...
    at NativeConnection.openUri (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongoose\lib\connection.js:738:34)
    at Mongoose.connect (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongoose\lib\index.js:404:15)
    at run (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\13703.js:16:18)
    at Object.<anonymous> (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\13703.js:21:1) {
  cause: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:371:5)
      at onParseError (node:internal/url:552:9)
      at new URL (node:internal/url:628:5)
      at new HostAddress (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\utils.js:768:19)
      at fromString (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\utils.js:813:16)
      at Array.map (<anonymous>)
      at parseOptions (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\connection_string.js:200:45)
      at new MongoClient (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\mongo_client.js:48:63)
      at NativeConnection.createClient (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:288:14)
      at NativeConnection.openUri (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongoose\lib\connection.js:738:34) {
    input: 'iLoveJS://localhost:PORT',
    code: 'ERR_INVALID_URL'
  },
  [Symbol(errorLabels)]: Set(0) {}
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

MongoRuntimeError: Unable to parse localhost:PORT with URL
    at new HostAddress (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\utils.js:771:34)
    at fromString (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\utils.js:813:16)
    ... 4 lines matching cause stack trace ...
    at NativeConnection.openUri (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongoose\lib\connection.js:738:34)
    at Mongoose.connect (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongoose\lib\index.js:404:15)
    at run (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\13703.js:16:18)
    at Object.<anonymous> (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\13703.js:21:1) {
  cause: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:371:5)
      at onParseError (node:internal/url:552:9)
      at new URL (node:internal/url:628:5)
      at new HostAddress (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\utils.js:768:19)
      at fromString (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\utils.js:813:16)
      at Array.map (<anonymous>)
      at parseOptions (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\connection_string.js:200:45)
      at new MongoClient (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongodb\lib\mongo_client.js:48:63)
      at NativeConnection.createClient (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:288:14)
      at NativeConnection.openUri (C:\Users\Drumm\Desktop\Work\debugging\JavaScript\node_modules\mongoose\lib\connection.js:738:34) {
    input: 'iLoveJS://localhost:PORT',
    code: 'ERR_INVALID_URL'
  },
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by Waurick** [comment]
<img width="544" alt="image" src="https://github.com/Automattic/mongoose/assets/71395103/dc1ec235-038b-4bc5-b5e9-f0cc1db8ee0c">
OK, I am sorry, but I know for a fact It is mongoose. Why is the Source IP/ connected Domain written in the Error? I want it to connect to the local IP. It is just broken. It works when using normal IP and opening the Port in the Firewall. And when I use any other package/ MongoDB Compass Client for connecting with Port Forwarding.

**Comment by vkarpov15** [comment]
"I think Mongoose is logging in to then get the IP of the Source and than trying to connect with that IP for some reason?" <-- most likely due to [replica set host names](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). Try using `directConnection: true`?

```javascript
await mongoose.connect('mongodb://Username:Password.@localhost:PORT/?authMechanism=DEFAULT', { directConnection: true });
```

**Comment by Waurick** [comment]
Yes i tried that allready. Sadly same issue.

**Comment by Waurick** [comment]
> Yes i tried that allready. Sadly same issue.(I will try it again shortly because I am not shure anymore if the error changed with this argument)

So this is funny. I tried this again, but forgot to turn on the SHH Session. I got the same Error. So i fucked up my Typescript and it is not recompiling. I am deeply sorry to bother you.
