### ISSUE TITLE
MongoNetworkTimeoutError RetryableWriteError inside findOneAndUpdate

### ISSUE THREAD

**Issue by mete89** [Automattic/mongoose#13826]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.9.0

### Node.js version

16

### MongoDB version

5.0.20

### Operating system

Linux

### Issue

In my production environment I noticed an error caused throwed MongoNetworkTimeoutError: connection 620 to 34.194.14.134:27017 timed out

See stacktrace below. 

at Timeout._onTimeout (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:148:23)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7) - MongoNetworkTimeoutError: connection 620 to 34.194.14.134:27017 timed out
at Timeout._onTimeout (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:148:23)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7) {
    [Symbol(errorLabels)]: Set(1) { 'RetryableWriteError' },
    [Symbol(beforeHandshake)]: false
}

original query is:
```            const queue = await Queue.findOneAndUpdate({
                shop_name: shop_name, module: module, token_type: token_type
            }, {
                $push: {job_list: {token: token, server_id: global.server_id, cost: estimated_token_needed}}
            }, {upsert: true});
```

Options: 
{keepAlive: true, socketTimeoutMS: 1000000,
        connectTimeoutMS: 1000000, maxPoolSize: 50}

Any idea what could have caused this error?

**Comment by mete89** [comment]
I have seen the same behavior in 4 days interval. One of them was inside .save() so it's not only queries.

**Comment by vkarpov15** [comment]
The most likely explanation in my experience is a very long running query that runs over `socketTimeoutMS`. For example, the below script prints a similar error. Try removing `socketTimeoutMS` and `keepAlive`, that will prevent MongoDB from timing out the socket.

```javascript
const mongoose = require('mongoose');
  
run().catch(error => console.log(error));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    socketTimeoutMS: 5000
  });
  
  const Test = mongoose.model('Test', new mongoose.Schema({ name: String }));
  await Test.deleteMany({});
  await Test.create({ answer: 42 });
  
  const promise = Test.find({ $where: 'sleep(10000) || true' });
  
  // Throws "MongoNetworkTimeoutError: connection 1 to 127.0.0.1:27017 timed out"
  console.log(await promise);
} 

```

**Comment by mete89** [comment]
Hey @vkarpov15 ,

Last week there were so many system upgrades on atlas side so I have seen a bunch of similar logs.

First I see `Mongoose default connection disconnected` logs on my instances. `2023-12-20T16:12:40.871Z`
Then `MongoNetworkError: connection 89 to 192.168.x.x:27017 closed` messages from all running queries  at the same time `2023-12-20T16:12:40.871Z`
Trace includes: 
```Connection.onClose (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:136:19)
at TLSSocket.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:63:46)
at TLSSocket.emit (node:events:526:28)
at TLSSocket.emit (node:domain:475:12)
at node:net:687:12
at TCP.done (node:_tls_wrap:580:7) { [Symbol(errorLabels)]: Set(0) }
```

Then `MongoNetworkError: read ECONNRESET` at `2023-12-20T16:12:40.877Z` with trace:
```
at connectionFailureError (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:387:20)
at TLSSocket.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:310:22)
at Object.onceWrapper (node:events:646:26)
at TLSSocket.emit (node:events:526:28)
at TLSSocket.emit (node:domain:475:12)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21) - MongoNetworkError: read ECONNRESET
at connectionFailureError (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:387:20)
at TLSSocket.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connect.js:310:22)
at Object.onceWrapper (node:events:646:26)
at TLSSocket.emit (node:events:526:28)
at TLSSocket.emit (node:domain:475:12)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
cause: Error: read ECONNRESET
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
errno: -104, code: 'ECONNRESET', syscall: 'read'}, connectionGeneration: 0, [Symbol(errorLabels)]: Set(1) { 'ResetPool' } }
```
Then I see reconnection message `Mongoose default connection reconnected` and `Mongoose default connection open` at `2023-12-20T16:12:43.122Z`

A minute later in the atlas activities I see `Replica set elected a new primary & (Secondary)Host is now primary` message at `2023-12-20T16:13:56`

4 minutes later in the atlas: `Host experienced a rollback` for the old primary along with `Host has restarted` at `2023-12-20T16:17:31`

So I'm on the mongoose 6.12.3 and mongodb 5.0.23 right now. So is it normal that my queries generate errors as soon as it disconnects? It reconnects 2-3 seconds later. I have retryWrites=true&w=majority in the connection string. 

Is there a way to tell mongoose or the underlying driver to wait before closing the sockets?

**Comment by vkarpov15** [comment]
Do you have a `mongoose.connection.on('error')` handler? It looks like you're listening to other events, like 'disconnected' and 'open'. My best guess would be that `MongoNetworkError: read ECONNRESET` comes from `mongoose.connection.on('error')`, because you're right that the MongoDB Node driver should retry queries and writes up to `serverSelectionTimeoutMS` by default

**Comment by mete89** [comment]
Hey @vkarpov15 

I checked all the logs but I can't see any "unable to connect to database" that I shared below. Interestingly I have another app which uses same database & codebase. It successfully disconnected and reconnected when this happens. Other environments with heavy write & read closes all the sockets. 

mongoose.connection.on('error', () => {
    throw new Error(`unable to connect to database: ${mongo_uri}`);
});
mongoose.connection.on('reconnected', () => {
    console.log('Mongoose default connection reconnected' + new Date());
});

mongoose.connection.on('disconnected', function () {
    console.log('Mongoose default connection disconnected: ' + new Date());
});

mongoose.connection.on('connected', function () {
    console.log('Mongoose default connection open');
});

**Comment by mete89** [comment]
It happens when the system is under load (receive webhooks). Yesterday I decreased the maxpool size. Today I have different errors after `disconnected` event, in the catch statement:

```
MongoPoolClearedError: Connection pool for cluster0-shard-00-00-xxxx.mongodb.net:27017 was cleared because another operation failed with: "connection 20 to 192.168.x.x:27017 closed"
at ConnectionPool.processWaitQueue (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:483:82)
at ConnectionPool.clear (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:253:14)
at updateServers (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:497:31)
at Topology.serverUpdateHandler (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:362:9)
at Server.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:480:77)
at Server.emit (node:events:526:28)
at Server.emit (node:domain:475:12)
at markServerUnknown (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:290:12)
at Server.handleError (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:234:17)
at Object.handleOperationResult [as cb] (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:368:16) - PoolClearedError [MongoPoolClearedError]: Connection pool for cluster0-shard-00-00-efpep.mongodb.net:27017 was cleared because another operation failed with: "connection 20 to 192.168.254.8:27017 closed"
at ConnectionPool.processWaitQueue (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:483:82)
at ConnectionPool.clear (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:253:14)
at updateServers (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:497:31)
at Topology.serverUpdateHandler (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:362:9)
at Server.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/topology.js:480:77)
at Server.emit (node:events:526:28)
at Server.emit (node:domain:475:12)
at markServerUnknown (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:290:12)
at Server.handleError (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:234:17)
at Object.handleOperationResult [as cb] (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/sdam/server.js:368:16) {
address: 'cluster0-shard-00-00-xxx.mongodb.net:27017',
[Symbol(errorLabels)]: Set(1) { 'RetryableWriteError' }
}
```

**Comment by vkarpov15** [comment]
Do you have the following in your production code? We don't recommend throwing errors in event handlers like this:

```javascript
mongoose.connection.on('error', () => {
throw new Error(unable to connect to database: ${mongo_uri});
});
```

As for `MongoPoolClearedError: Connection pool for cluster0-shard-00-00-xxxx.mongodb.net:27017 was cleared because another operation failed with: "connection 20 to 192.168.x.x:27017 closed"`, this looks like an intermittent network error due to another operation timing out or experiencing some other error.

Do you have [retryable writes](https://www.mongodb.com/docs/manual/core/retryable-writes/) enabled? Given that this is a `RetryableWriteError` and you're on Mongoose 6.9, retryable writes should be on and the MongoDB driver should automatically retry this operation once.

**Comment by mete89** [comment]
Hello @vkarpov15 ,

I collected more info on this issue this time. https://github.com/Automattic/mongoose/issues/13665 this may be relevant as well.

On the server end I see a restart happens on the primary. I believe it's because of the CPU load. 
`{"t":{"$date":"2024-06-30T06:31:21.703+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"-","msg":"***** SERVER RESTARTED *****"}
`

Right now, I'm on mongoose 6.12.8 and mongodb 6.0.15 on Atlas M40 tier. 

retryWrites=true&w=majority is in the string as well. 

My question is when a server restart happens in a cluster should I expect mongoose and the underlying driver retry my queries or should I wrap them all with a try catch and write my own retry logic?

**Comment by mete89** [comment]
@vkarpov15 Another message I got today while I'm creating new search nodes, "The server is in quiesce mode and will shut down"

**Comment by vkarpov15** [comment]
When a replica set election is in progress, the underlying MongoDB driver will retry up to `serverSelectionTimeoutMS` to connect to a primary (presuming default read preference). Any query that you try to run will get queued by the MongoDB driver until it can find the replica set primary.

However, you may still get an error if you have a query that is being executed on the MongoDB server when the MongoDB server shuts down. In the latter case, you would likely need to retry yourself.
