### ISSUE TITLE
Error: *****Model validation failed: _id: Class constructor ObjectId cannot be invoked without 'new' after updating to 7.5.x

### ISSUE THREAD

**Issue by irnmon** [Automattic/mongoose#13831]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.5.0

### Node.js version

18.x

### MongoDB version

5.8

### Operating system

macOS

### Issue

I recently updated Mongoose to `7.5.0` and started to getting the error below. I could share more information.

```
{
     _id: TypeError: Class constructor ObjectId cannot be invoked without 'new'
         at ObjectId.SchemaType.getDefault (/app/node_modules/mongoose/lib/schematype.js:1143:31)
         at applyDefaults (/app/node_modules/mongoose/lib/helpers/document/applyDefaults.js:99:24)
         at model.Document (/app/node_modules/mongoose/lib/document.js:180:5)
         at model.Model (/app/node_modules/mongoose/lib/model.js:123:12)
         at new model (/app/node_modules/mongoose/lib/model.js:4702:15)
         at /app/node_modules/mongoose/lib/model.js:2913:18
         at Array.map (<anonymous>)
         at Function.create (/app/node_modules/mongoose/lib/model.js:2902:30)
         at ModelRepository.create
(/app/dist/apps/channel/webpack:/src/modules/model/repositories/model.repository.ts:44:52)
         at session.withTransaction.retryWrites (/app/dist/apps/channel/webpack:/src/modules/model/V1/model.service.ts:173:62)
         at attemptTransaction (/app/node_modules/mongodb/src/sessions.ts:587:15)
         at ClientSession.withTransaction (/app/node_modules/mongodb/src/sessions.ts:460:12)
         at ModelServiceV1.create (/app/dist/apps/model/webpack:/src/modules/model/V1/model.service.ts:171:23)
         at processTicksAndRejections (node:internal/process/task_queues:95:5)
         at /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
         at Object.<anonymous> (/app/node_modules/@nestjs/core/router/router-proxy.js:9:17)
   }
```

Here is my function which I was using to create document.
```
 async create(
        data: Omit<Model, '_id' | 'created_at' | 'updated_at'>,
        session: ClientSession,
    ): Promise<Model> {
        const mdl = new this.model(data);
        return mdl.save({ session });
    }
```
Also I tried to use `create()` instead of `save()` and it failed too.

```
    async create(
        data: Omit<Model, '_id' | 'created_at' | 'updated_at'>,
        session: ClientSession,
    ): Promise<Model> {
        const result = await this.model.create([data], { session });
        return result[0];
    }
```

Thanks a lot.

**Comment by vkarpov15** [comment]
It looks like you have a schema that defines a default value for an ObjectId path like this:

```javascript
myPath: {
  type: 'ObjectId',
  default: ObjectId
}
```

Use the following instead:

```javascript
myPath: {
  type: 'ObjectId',
  default: () => new ObjectId()
}
```
