### ISSUE TITLE
$ne Operator Causes CastError for String Field

### ISSUE THREAD

**Issue by yashwason** [Automattic/mongoose#13890]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.5.0

### Node.js version

18.17.1

### MongoDB server version

6.0.0

### Typescript version (if applicable)

5.0.4

### Description

When using the $ne (not equal) operator in a Mongoose query to find documents with a string field that is not equal to a specific value, a CastError is encountered, which should not occur in this context. The issue seems to be related to how Mongoose handles the $ne operator with string fields.

### Steps to Reproduce

**1. Create a Mongoose model with a schema that includes a string field, e.g., `entityId`.**

```typescript
   const mongoose = require('mongoose');

   const defaultStringFieldConfig = {
 	   type: String,
 	   trim: true
   };

   const userSchema = new mongoose.Schema({
		entity: {
			...defaultStringFieldConfig,
			required: true,
			immutable: true,
			default: () => `user`
		},
		entityId: {
			...defaultStringFieldConfig,
			required: true,
			unique: true,
			immutable: true
		}
   });

   const UserModel = mongoose.model('User', userSchema);
```

**2. Attempt to find a document where entityId is not equal to a specific value using the $ne operator.**

```typescript
    UserModel.findOne({
        emailAddress: 'yashwason@example.com',
        entityId: { $ne: 'user_r2jukudyedyi' }
    })
    .then((data) => console.log('data', data))
    .catch(console.log);
```

**3. The query results in a CastError with the following message:**

```typescript
    CastError: Cast to string failed for value "{ '$ne': 'user_r2jukudyedyi' }" (type Object) at path "entityId" for model "user"
```

### Expected Behavior

The $ne operator should work correctly for string fields and should not result in a CastError.

**Comment by IslandRhythms** [comment]
Possibly related to #13880

**Comment by IslandRhythms** [comment]
Please modify the script below to demonstrate your issue.

```javascript
const mongoose = require('mongoose');

const defaultStringFieldConfig = {
  type: String,
  trim: true
};

const userSchema = new mongoose.Schema({
entity: {
  ...defaultStringFieldConfig,
  required: true,
  immutable: true,
  default: () => `user`
},
entityId: {
  ...defaultStringFieldConfig,
  required: true,
  unique: true,
  immutable: true
},
emailAddress: {
  type: String
}
});

const UserModel = mongoose.model('User', userSchema);

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017');
  await mongoose.connection.dropDatabase();

  await UserModel.create({
    entity: 'Hello',
    entityId: 'World',
    emailAddress: 'yashwason@example.com'
  });

  const res = await UserModel.findOne({
    emailAddress: 'yashwason@example.com',
    entityId: { $ne: 'user_r2jukudyedyi' }
  });
  console.log('what is res', res);
}

run();
```

**Comment by yashwason** [comment]
Yup. Your script is working in isolation. Here's my log output.

```
what is res {
 _id: new ObjectId("651f0c3e31b0b3df94258d46"),
   entity: 'Hello',
   entityId: 'World',
   emailAddress: 'yashwason@example.com',
   __v: 0
}
```

It is also working when I import my **own** User model and connect to the DB I was using when I opened this issue.

---

However, my own code **AND** your script both fail in our Express controllers and I can't make sense of why that may be. Here's the error in case you need it.

```CastError: Cast to string failed for value "{ '$ne': 'user_r2jukudyedyi' }" (type Object) at path "entityId" for model "User"```

**Comment by vkarpov15** [comment]
@yashwason can you please provide the stack trace from the `CastError: Cast to string failed for value "{ '$ne': 'user_r2jukudyedyi' }" (type Object) at path "entityId" for model "User"` error as well?

**Comment by yashwason** [comment]
```
CastError: Cast to string failed for value "{ '$ne': 'user_r2jukudyedyi' }" (type Object) at path "entityId" for model "user"
    at SchemaString.cast (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:606:11)
    at model.Query.<anonymous> (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:369:16)
    at SchemaType._applySetters (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1189:20)
    at SchemaType.applySetters (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1214:16)
    at SchemaString.castForQuery (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:690:15)
    at SchemaString.handleSingle (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1562:15)
    at SchemaString.castForQuery (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:683:20)
    at cast (/Users/projectFolder/node_modules/mongoose/lib/cast.js:347:39)
    at Query.cast (/Users/projectFolder/node_modules/mongoose/lib/query.js:4911:12)
    at Query._castConditions (/Users/projectFolder/node_modules/mongoose/lib/query.js:2232:10) {
  stringValue: `"{ '$ne': 'user_r2jukudyedyi' }"`,
  messageFormat: undefined,
  kind: 'string',
  value: { '$ne': 'user_r2jukudyedyi' },
  path: 'entityId',
  reason: null,
  valueType: 'Object',
  model: Model { user }
}
```

**Comment by yashwason** [comment]
Running into the same issue with the ``$in`` operator:

Upon running:
```
StaffPermission.find({
    entityId: { $in: [ 'staffPermission_VHWm2zKYrPBJ' ] }
})
```

The below error is thrown:

```
CastError: Cast to string failed for value "{ '$in': [ 'staffPermission_VHWm2zKYrPBJ' ] }" (type Object) at path "entityId" for model "staffPermission"
    at SchemaString.cast (/Users/projectFolder/mongoose/lib/schema/string.js:606:11)
    at model.Query.<anonymous> (/Users/projectFolder/mongoose/lib/schema/string.js:369:16)
    at SchemaType._applySetters (/Users/projectFolder/mongoose/lib/schematype.js:1189:20)
    at SchemaType.applySetters (/Users/projectFolder/mongoose/lib/schematype.js:1214:16)
    at SchemaString.castForQuery (/Users/projectFolder/mongoose/lib/schema/string.js:690:15)
    at SchemaString.handleSingle (/Users/projectFolder/mongoose/lib/schematype.js:1562:15)
    at SchemaString.castForQuery (/Users/projectFolder/mongoose/lib/schema/string.js:683:20)
    at cast (/Users/projectFolder/mongoose/lib/cast.js:347:39)
    at Query.cast (/Users/projectFolder/mongoose/lib/query.js:4911:12)
    at Query._castConditions (/Users/projectFolder/mongoose/lib/query.js:2232:10) {
  stringValue: `"{ '$in': [ 'staffPermission_VHWm2zKYrPBJ' ] }"`,
  messageFormat: undefined,
  kind: 'string',
  value: { '$in': [ 'staffPermission_VHWm2zKYrPBJ' ] },
  path: 'entityId',
  reason: null,
  valueType: 'Object',
  model: Model { staffPermission }
}
```

**Comment by IslandRhythms** [comment]
Please modify the script below to demonstrate your issue.

```javascript
const mongoose = require('mongoose');

const defaultStringFieldConfig = {
  type: String,
  trim: true
};

const userSchema = new mongoose.Schema({
entity: {
  ...defaultStringFieldConfig,
  required: true,
  immutable: true,
  default: () => `user`
},
entityId: {
  ...defaultStringFieldConfig,
  required: true,
  unique: true,
  immutable: true
},
emailAddress: {
  type: String
}
});

const UserModel = mongoose.model('User', userSchema);

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017');
  await mongoose.connection.dropDatabase();

  await UserModel.create({
    entity: 'Test Testerson',
    entityId: 'id',
    emailAddress: 'test@localhost.com'
  });
  const res = await UserModel.find({
    entityId: { $in: ['id'] }
  });

  const response = await UserModel.find({
    entityId: { $in: ['adskja;lsdfja;sldfj'] }
  });

  console.log('done', res, response);
}

run();
```

**Comment by yashwason** [comment]
Okay maybe it's something weird on my machine if you aren't able to reproduce these issues. Any theories what I should look into to try to debug this?

**Comment by vkarpov15** [comment]
Modify the provided script to more closely match your setup.

**Comment by donoftime2018** [comment]
Might be how the type of defaultStringFieldConfig behaves in $ne operation. Maybe just add the type: String, trim: true in the entitiyId instead of making it its own object?

**Comment by slowbeat92** [comment]
I had the same problem and in my case it was due to another dependency of my project that had a different version of mongoose (6.8.3) instead of the 7.6.3 .
In my case I fixed it by updating the other dependency

**Comment by yashwason** [comment]
@slowbeat92 I deduped my dependency tree and Mongoose wasn't a problem in there. @donoftime2018 rebuilt the DB indexes and tried that too but ending up with the same result.


This time with a findOneAndUpdate call. Uses find underneath of course.

```javascript
const result = await StaffRole.findOneAndUpdate(
    {
        entityId: req.params.entityId,
        organisationId: { $ne: null }
    },
    updatesToDo
);
```

```shell
CastError: Cast to string failed for value "{ '$ne': null }" (type Object) at path "organisationId" for model "staffRole"
    at SchemaString.cast (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:606:11)
    at model.Query.<anonymous> (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:369:16)
    at SchemaType._applySetters (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1189:20)
    at SchemaType.applySetters (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1214:16)
    at SchemaString.castForQuery (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:690:15)
    at SchemaString.handleSingle (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1561:15)
    at SchemaString.castForQuery (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:683:20)
    at cast (/Users/projectFolder/node_modules/mongoose/lib/cast.js:352:39)
    at Query.cast (/Users/projectFolder/node_modules/mongoose/lib/query.js:4910:12)
    at Query._castConditions (/Users/projectFolder/node_modules/mongoose/lib/query.js:2232:10) {
  stringValue: `"{ '$ne': null }"`,
  messageFormat: undefined,
  kind: 'string',
  value: { '$ne': null },
  path: 'organisationId',
  reason: null,
  valueType: 'Object',
  model: Model { staffRole }
}
``` 


```javascript
const StaffRoleSchema = new Schema(
    {
        entityId: {
            type: String,
            trim: true,
            immutable: true,
            default: null
        },

        title: {
            type: String,
            trim: true,
            required: true
        },

        organisationId: {
            type: String,
            trim: true,
            immutable: true,
            default: null
        },
    },
    { timestamps: true }
);

export default model(`staffRole`, StaffRoleSchema);

```

**Comment by yashwason** [comment]
@IslandRhythms The most [recent script](https://github.com/Automattic/mongoose/issues/13890#issuecomment-1765049528) you provided errors too. Here's the output.

```shell
/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:606
    throw new CastError('string', value, this.path, null, this);
          ^

CastError: Cast to string failed for value "{ '$in': [ 'id' ] }" (type Object) at path "entityId" for model "User"
    at SchemaString.cast (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:606:11)
    at model.Query.<anonymous> (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:369:16)
    at SchemaType._applySetters (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1189:20)
    at SchemaType.applySetters (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1214:16)
    at SchemaString.castForQuery (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:690:15)
    at SchemaString.handleSingle (/Users/projectFolder/node_modules/mongoose/lib/schematype.js:1561:15)
    at SchemaString.castForQuery (/Users/projectFolder/node_modules/mongoose/lib/schema/string.js:683:20)
    at cast (/Users/projectFolder/node_modules/mongoose/lib/cast.js:352:39)
    at Query.cast (/Users/projectFolder/node_modules/mongoose/lib/query.js:4910:12)
    at Query._castConditions (/Users/projectFolder/node_modules/mongoose/lib/query.js:2232:10) {
  stringValue: `"{ '$in': [ 'id' ] }"`,
  messageFormat: undefined,
  kind: 'string',
  value: { '$in': [ 'id' ] },
  path: 'entityId',
  reason: null,
  valueType: 'Object',
  model: <ref *2> [Function: model] {
    hooks: Kareem {
      _pres: Map(3) {
        'deleteOne' => [
          {
            document: true,
            query: false,
            fn: [Function: removeSubDocsPreRemove],
            isAsync: undefined
          },
          numAsync: undefined
        ],
        'save' => [
          { fn: [Function: validateBeforeSave], isAsync: false },
          { fn: [Function: saveSubdocsPreSave], isAsync: false },
          { fn: [Function: shardingPluginPreSave], isAsync: false },
          { fn: [Function: trackTransactionPreSave], isAsync: false },
          numAsync: undefined
        ],
        'remove' => [
          { fn: [Function: shardingPluginPreRemove], isAsync: false },
          numAsync: undefined
        ]
      },
      _posts: Map(2) {
        'save' => [
          { fn: [Function: saveSubdocsPostSave] },
          { fn: [Function: shardingPluginPostSave] }
        ],
        'init' => [ { fn: [Function: shardingPluginPostInit] } ]
      }
    },
    base: <ref *1> Mongoose {
      connections: [
        <ref *3> NativeConnection {
          base: [Circular *1],
          collections: {
            users: [Collection],
            staffroles: [Collection],
            staffpermissions: [Collection],
            staffmembers: [Collection]
          },
          models: {
            user: [Function],
            staffRole: [Function],
            staffPermission: [Function],
            staffMember: [Function],
            User: [Circular *2]
          },
          config: {},
          replica: false,
          options: null,
          otherDbs: [],
          relatedDbs: {},
          states: [Object: null prototype] {
            '0': 'disconnected',
            '1': 'connected',
            '2': 'connecting',
            '3': 'disconnecting',
            '99': 'uninitialized',
            disconnected: 0,
            connected: 1,
            connecting: 2,
            disconnecting: 3,
            uninitialized: 99
          },
          _readyState: 1,
          _closeCalled: undefined,
          _hasOpened: true,
          plugins: [],
          id: 0,
          _queue: [],
          _listening: false,
          _connectionOptions: { driverInfo: [Object] },
          _connectionString: 'mongodb://127.0.0.1:27017',
          client: MongoClient {
            _events: [Object: null prototype],
            _eventsCount: 1,
            _maxListeners: 0,
            mongoLogger: [MongoLogger],
            s: [Object],
            topology: [Topology],
            connectionLock: undefined,
            [Symbol(kCapture)]: false,
            [Symbol(options)]: [Object: null prototype]
          },
          '$initialConnection': Promise { [Circular *3] },
          db: Db { s: [Object], client: [MongoClient] },
          host: '127.0.0.1',
          port: 27017,
          name: 'test'
        }
      ],
      nextConnectionId: 1,
      models: <ref *4> {
        user: [Function: model] {
          hooks: Kareem { _pres: [Map], _posts: [Map] },
          base: [Circular *1],
          modelName: 'user',
          model: [Function: model],
          db: <ref *3> NativeConnection {
            base: [Circular *1],
            collections: [Object],
            models: [Circular *4],
            config: {},
            replica: false,
            options: null,
            otherDbs: [],
            relatedDbs: {},
            states: [Object: null prototype],
            _readyState: 1,
            _closeCalled: undefined,
            _hasOpened: true,
            plugins: [],
            id: 0,
            _queue: [],
            _listening: false,
            _connectionOptions: [Object],
            _connectionString: 'mongodb://127.0.0.1:27017',
            client: [MongoClient],
            '$initialConnection': [Promise],
            db: [Db],
            host: '127.0.0.1',
            port: 27017,
            name: 'test'
          },
          discriminators: undefined,
          events: EventEmitter {
            _events: [Object: null prototype] {},
            _eventsCount: 0,
            _maxListeners: undefined,
            [Symbol(kCapture)]: false
          },
          '$appliedMethods': true,
          '$appliedHooks': true,
          _middleware: Kareem { _pres: [Map], _posts: [Map] },
          '$__insertMany': [Function (anonymous)],
          schema: Schema {
            obj: [Object],
            paths: [Object],
            aliases: {},
            subpaths: {},
            virtuals: [Object],
            singleNestedPaths: {},
            nested: {},
            inherits: {},
            callQueue: [],
            _indexes: [],
            methods: [Object],
            methodOptions: {},
            statics:
```

**Comment by yashwason** [comment]
Another thing that might be interesting. The below `countDocuments` call works perfectly. It's calls that '_find_' that behave in the above manner.

```javascript
const dbCount = await Collection.countDocuments({
    entityId: { $in: uniqueCollectionIds }
});
```

**Comment by yashwason** [comment]
@vkarpov15 Here's my output using Mongoose 7.5.0:
```
7.5.0

CastError: Cast to string failed for value "{ '$ne': null }" (type Object) at path "organisationId" for model "staffRole"
    at SchemaString.cast (/projectFolder/node_modules/mongoose/lib/schema/string.js:606:11)
    at model.Query.<anonymous> (/projectFolder/node_modules/mongoose/lib/schema/string.js:369:16)
    at SchemaType._applySetters (/projectFolder/node_modules/mongoose/lib/schematype.js:1189:20)
    at SchemaType.applySetters (/projectFolder/node_modules/mongoose/lib/schematype.js:1214:16)
    at SchemaString.castForQuery (/projectFolder/node_modules/mongoose/lib/schema/string.js:690:15)
    at SchemaString.handleSingle (/projectFolder/node_modules/mongoose/lib/schematype.js:1562:15)
    at SchemaString.castForQuery (/projectFolder/node_modules/mongoose/lib/schema/string.js:683:20)
    at cast (/projectFolder/node_modules/mongoose/lib/cast.js:334:39)
    at Query.cast (/projectFolder/node_modules/mongoose/lib/query.js:4910:12)
    at Query._castConditions (/projectFolder/node_modules/mongoose/lib/query.js:2232:10) {
  stringValue: `"{ '$ne': null }"`,
  messageFormat: undefined,
  kind: 'string',
  value: { '$ne': null },
  path: 'organisationId',
  reason: null,
  valueType: 'Object',
  model: Model { staffRole }
}
```

Below output is from using Mongoose 7.6.5 (which is what I actually use)

```7.6.5

CastError: Cast to string failed for value "{ '$ne': null }" (type Object) at path "organisationId" for model "staffRole"
    at SchemaString.cast (/projectFolder/node_modules/mongoose/lib/schema/string.js:606:11)
    at model.Query.<anonymous> (/projectFolder/node_modules/mongoose/lib/schema/string.js:369:16)
    at SchemaType._applySetters (/projectFolder/node_modules/mongoose/lib/schematype.js:1189:20)
    at SchemaType.applySetters (/projectFolder/node_modules/mongoose/lib/schematype.js:1214:16)
    at SchemaString.castForQuery (/projectFolder/node_modules/mongoose/lib/schema/string.js:690:15)
    at SchemaString.handleSingle (/projectFolder/node_modules/mongoose/lib/schematype.js:1563:15)
    at SchemaString.castForQuery (/projectFolder/node_modules/mongoose/lib/schema/string.js:683:20)
    at cast (/projectFolder/node_modules/mongoose/lib/cast.js:352:39)
    at Query.cast (/projectFolder/node_modules/mongoose/lib/query.js:4909:12)
    at Query._castConditions (/projectFolder/node_modules/mongoose/lib/query.js:2232:10) {
  stringValue: `"{ '$ne': null }"`,
  messageFormat: undefined,
  kind: 'string',
  value: { '$ne': null },
  path: 'organisationId',
  reason: null,
  valueType: 'Object',
  model: Model { staffRole }
}```

**Comment by vkarpov15** [comment]
That is extremely strange, I've tried matching your exact versions of Mongoose and Node.js, but I still don't get any errors. How are you running this script? Are you compiling using TypeScript, and are you importing any other packages?

**Comment by yashwason** [comment]
@vkarpov15 I am using TypeScript v5.0.4 to compile. Although the scripts remain same.

Other than this, I have a couple of other dependencies (Express, Zod, DotEnv etc) but no database related deps.

**Comment by vkarpov15** [comment]
Are you compiling this particular script with TypeScript? Can you try just running the js file through node and see if you get the same result?

**Comment by yashwason** [comment]
I checked. This issue is only occurring when compiling with TypeScript.

I understand this now maybe out of scope of your team? If it is, I would appreciate to hear your thoughts/ideas regarding why this may be happening with TS and what I should look into to try to debug this?

**Comment by vkarpov15** [comment]
What does your tsconfig.json look like and what's the command you're using to compile and run? It is strange that this is only happening with TypeScript, we will investigate and find the root cause to determine if this is a bug we need to fix.

**Comment by vkarpov15** [comment]
Do you know if you're importing any modules that monkeypatch built-in functions, like `Object.keys()` or `Object.prototype.hasOwnProperty()`? That's something that I would look into if I were in your shoes.

**Comment by yashwason** [comment]
I will look into that. Thanks!

**Comment by yashwason** [comment]
I ran a rudimentary check and couldn't find anything. Will explore more in the coming weeks as this seems like a complex check? I will report back if I find something.
