### ISSUE TITLE
ValidatorError not catched by try/catch

### ISSUE THREAD

**Issue by bennaaym** [Automattic/mongoose#14101]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

^7.5.0

### Node.js version

18.18.0

### MongoDB server version

MongoDB Atlas

### Typescript version (if applicable)

^5.2.2

### Description

The ValidatorError  thrown by mongoose is not catched by try/catch block 
```
try {
    const activity = new Activity({
      <object with invalid schema>
    });

    await activity.save();
    return activity;
  } catch (err) {
    console.log(err);
  }
````

Error:
```
ValidatorError: Path `value` is required.
    at validate (***\node_modules\mongoose\lib\schematype.js:1365:13)
    at SchemaString.SchemaType.doValidate (***\node_modules\mongoose\lib\schematype.js:1349:7)
    at ***\node_modules\mongoose\lib\document.js:2968:18
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
[ERROR] 09:23:29 ValidatorError: Path `value` is required.
```

### Steps to Reproduce

```
try {
    const activity = new Activity({
      <object with invalid schema>
    });

    await activity.save();
    return activity;
  } catch (err) {
    console.log(err);
  }
````

### Expected Behavior

The error should be catched by the closest try/catch block

**Comment by bennaaym** [comment]
The Validator error is not catched when there is an array of arrays .

````
options: {
    type: [[optionSchema]],
    required: true
  }
````

if there is an error in one of the element a Validator error is thrown and is not catched by the try/catch block around it

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const optionsSchema = new mongoose.Schema({
  val: {
    type: Number,
    required: true
  }
});

const testSchema = new mongoose.Schema({
  name: String,
  options: {
    type: [[optionsSchema]],
    required: true
  }
});



const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({ name: 'Test' });
  console.log(await Test.findOne())
  console.log('done');
  
}
run();
```

**Comment by mcfriend99** [comment]
I don't have an array or array in my schema and I still can't catch any error.

**Comment by vkarpov15** [comment]
@mcfriend99 please open a new issue and follow the issue template
