### ISSUE TITLE
Can't access to my mongodb atlas since today.

### ISSUE THREAD

**Issue by justoverclockl** [Automattic/mongoose#14157]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0

### Node.js version

18.17.0

### MongoDB server version

atlas

### Description

today without touching the code my digitalocean app stopped to work, in the pm2 log i see 

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|app  | MongooseError: Operation `utenti.findOne()` buffering timed out after 10000ms
0|app  |     at Timeout.<anonymous> (/home/marco/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)
0|app  |     at listOnTimeout (node:internal/timers:569:17)
0|app  |     at process.processTimers (node:internal/timers:512:7)
0|app  | Errore di connessione:  MongoServerSelectionError: Server selection timed out after 30000 ms
0|app  |     at EventTarget.<anonymous> (/home/marco/node_modules/mongodb/lib/sdam/topology.js:276:34)
0|app  |     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
0|app  |     at EventTarget.dispatchEvent (node:internal/event_target:683:26)
0|app  |     at abortSignal (node:internal/abort_controller:368:10)
0|app  |     at TimeoutController.abort (node:internal/abort_controller:402:5)
0|app  |     at Timeout.<anonymous> (/home/marco/node_modules/mongodb/lib/utils.js:1010:92)
0|app  |     at listOnTimeout (node:internal/timers:569:17)
0|app  |     at process.processTimers (node:internal/timers:512:7) {
0|app  |   reason: TopologyDescription {
0|app  |     type: 'ReplicaSetNoPrimary',
0|app  |     servers: Map(3) {
0|app  |       'ac-luzptfw-shard-00-02.svn9sb8.mongodb.net:27017' => [ServerDescription],
0|app  |       'ac-luzptfw-shard-00-01.svn9sb8.mongodb.net:27017' => [ServerDescription],
0|app  |       'ac-luzptfw-shard-00-00.svn9sb8.mongodb.net:27017' => [ServerDescription]
0|app  |     },
0|app  |     stale: false,
0|app  |     compatible: true,
0|app  |     heartbeatFrequencyMS: 10000,
0|app  |     localThresholdMS: 15,
0|app  |     setName: 'atlas-eosskd-shard-0',
0|app  |     maxElectionId: null,
0|app  |     maxSetVersion: null,
0|app  |     commonWireVersion: 0,
0|app  |     logicalSessionTimeoutMinutes: null
0|app  |   },
0|app  |   code: undefined,
0|app  |   [Symbol(errorLabels)]: Set(0) {}
0|app  | }
0|app  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|app  | MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
0|app  |     at _handleConnectionErrors (/home/marco/node_modules/mongoose/lib/connection.js:809:11)
0|app  |     at NativeConnection.openUri (/home/marco/node_modules/mongoose/lib/connection.js:784:11)
0|app  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|app  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|app  | MongooseError: Operation `utenti.findOne()` buffering timed out after 10000ms
0|app  |     at Timeout.<anonymous> (/home/marco/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)
0|app  |     at listOnTimeout (node:internal/timers:569:17)
0|app  |     at process.processTimers (node:internal/timers:512:7)
0|app  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|app  | MongooseError: Operation `utenti.findOne()` buffering timed out after 10000ms
0|app  |     at Timeout.<anonymous> (/home/marco/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)
0|app  |     at listOnTimeout (node:internal/timers:569:17)
0|app  |     at process.processTimers (node:internal/timers:512:7)
```

locally works fine. why?

### Steps to Reproduce

can't call any api.

**Comment by vkarpov15** [comment]
`ReplicaSetNoPrimary` is indicative that one or more of your Atlas cluster's machines are down or unreachable. Can you please log in to Atlas and confirm 1) that your cluster is operating normally, 2) confirm your exact version of MongoDB server? "Atlas" isn't a valid version number, should be something like 6.0.1 or 5.0.7.

**Comment by justoverclockl** [comment]
the issue persist and i can see correctly my atlas db online.
