### ISSUE TITLE
log : import_mongoose.default.connect is not a function

### ISSUE THREAD

**Issue by kaushiksahu18** [Automattic/mongoose#14613]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.0

### Node.js version

20.11.1

### MongoDB server version

7.0.8

### Description

i was trying to use mongodb with honojs and i have installed mongoos but 
`connectDB`  function is showing the error `import_mongoose.default.connect is not a function`
```
import { z } from "zod";
import mongoose from "mongoose";

import { USERS } from "./index.js";

// this function
async function connectDB(url: string) {
  await mongoose.connect(String(url));
}
```

log
```
Error in connecting to DB TypeError: import_mongoose.default.connect is not a function
    at connectDB (file:///home/user/hono_tododb/src/utils.ts:7:18)
    at null.<anonymous> (file:///home/user/hono_tododb/src/index.ts:26:13)
    at dispatch (file:///home/user/hono_tododb/node_modules/hono/dist/compose.js:29:23)
    at null.<anonymous> (file:///home/user/hono_tododb/node_modules/hono/dist/compose.js:30:20)
    at cors2 (file:///home/user/hono_tododb/node_modules/hono/dist/middleware/cors/index.js:65:11)
    at dispatch (file:///home/user/hono_tododb/node_modules/hono/dist/compose.js:29:23)
    at null.<anonymous> (file:///home/user/hono_tododb/node_modules/hono/dist/compose.js:6:12)
    at null.<anonymous> (file:///home/user/hono_tododb/node_modules/hono/dist/hono-base.js:188:31)
    at Hono2.dispatch (file:///home/user/hono_tododb/node_modules/hono/dist/hono-base.js:198:5)
    at Hono2.fetch (file:///home/user/hono_tododb/node_modules/hono/dist/hono-base.js:201:17)
```

### Steps to Reproduce

```
import { z } from "zod";
import mongoose from "mongoose";

import { USERS } from "./index.js";

// this function
async function connectDB(url: string) {
  await mongoose.connect(String(url));
}
```

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script works fine with Node.js. Please modify the following script to demonstrate your issue. Also, can you please clarify whether you're using Next.js or some environment other than Node.js, and also which version of TypeScript you're using and your TypeScript config? I see you have an `src/utils.ts` file.

```javascript
import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import mongoose from 'mongoose';

const app = new Hono()
app.get('/', async (c) => {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  return c.text('Hono meets Node.js')
})

serve(app, (info) => {
  console.log(`Listening on http://localhost:${info.port}`) // Listening on http://localhost:3000
})

```

Output:

```
$ node gh-14613.mjs 
Listening on http://localhost:3000

```

Curl command:

```
$ curl http://localhost:3000
Hono meets Node.js
$
```

**Comment by kaushiksahu18** [comment]
> the following script works fine with Node.js.
### I have used for cloudflare workers (wrangler)
**TS version - latest**

**Comment by vkarpov15** [comment]
The easiest way to fix this particular error is to add the following to your `wrangler.toml` file:

```
node_compat = true
```

However, with that, we still get the following errors:

```
▲ [WARNING] The package "node:async_hooks" wasn't found on the file system but is built into node.

  Your Worker may throw errors at runtime unless you enable the "nodejs_compat" compatibility flag.
  Refer to https://developers.cloudflare.com/workers/runtime-apis/nodejs/ for more details. Imported
  from:
   - node_modules/mongoose/lib/mongoose.js


✘ [ERROR] Could not resolve "fs/promises"

    node_modules/mongodb/lib/client-side-encryption/state_machine.js:4:19:
      4 │ const fs = require("fs/promises");
        ╵                    ~~~~~~~~~~~~~

  The package "fs/promises" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

I'm investigating a fix. But it's worth mentioning that we haven't tested Mongoose with Cloudflare Workers at all.

**Comment by vkarpov15** [comment]
I took some time to play whack-a-mole with all the build issues that pop up with Cloudflare Workers, but still no luck, Mongoose can't connect. It looks like Cloudflare Workers has [some support for TCP sockets](https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases), but looks like that doesn't quite work with the MongoDB driver.

![image](https://github.com/Automattic/mongoose/assets/1620265/37fa2b04-19c9-45cc-a53a-4db53aad2a29)

It looks like the MongoDB driver doesn't support Cloudflare Workers, [the officially supported way to connect to MongoDB from Cloudflare Workers is Realm](https://developers.cloudflare.com/workers/databases/connecting-to-databases/). Mongoose doesn't have a Realm driver, so we can't quite use that yet. But we may consider adding a Realm driver in the future.

![image](https://github.com/Automattic/mongoose/assets/1620265/7c4d9535-4499-4830-ad45-d5fae57655ed)

**Comment by jdgamble555** [comment]
Cloudflare doesn't support TCP protocol, there would need to be an HTTP implementation using REST API. Is this something mongoose can do, connect differently?

Firebase has a `lite` version for this.

J

**Comment by vkarpov15** [comment]
Yes, Mongoose can in theory use HTTP or some alternative protocol via the Driver API.

**Comment by ceddybi** [comment]
> It looks like the MongoDB driver doesn't support Cloudflare Workers, [the officially supported way to connect to MongoDB from Cloudflare Workers is Realm](https://developers.cloudflare.com/workers/databases/connecting-to-databases/). Mongoose doesn't have a Realm driver, so we can't quite use that yet. But we may consider adding a Realm driver in the future.

@vkarpov15 Well Realm is deprecated soon

**Comment by vkarpov15** [comment]
In that case, we will update the issue title to remove reference to Realm: https://www.mongodb.com/products/updates/product-support-deprecation?tck=notice_product_deprecation_2024.

**Comment by ceddybi** [comment]
> In that case, we will update the issue title to remove reference to Realm: https://www.mongodb.com/products/updates/product-support-deprecation?tck=notice_product_deprecation_2024. 

@vkarpov15 Okok, so how will mongo run in cloudflare workers?

**Comment by jdgamble555** [comment]
It's not just Cloudflare works, it is Vercel Edge, Deno, Bun, and other non-node environments fwi. This is the new norm.

**Comment by ceddybi** [comment]
@jdgamble555 no mongoose doesn't work on cloudflare, but others where there's a full nodejs environment it works, e.g Vercel (not edge, vercel edge is just like cloudflare), Bun, Deno

**Comment by jdgamble555** [comment]
Right, Vercel Edge uses Cloudflare under the hood. What I'm saying is the new normal is multiple environments. Mongoose should work in ALL JavaScript environments. 

The only way to do this is to have on option that uses HTTP under-the-hood. This is how `firestore/lite` works, and there should be an option for Mongoose to work that way as well.

J

**Comment by ceddybi** [comment]
@jdgamble555
> Vercel Edge uses Cloudflare under the hood

You mean they are re-selling the cloudflare workers platform ? i thought they were using something from aws/gcp.

I used the full Vercel functions (without edge) and it works. 

anyways mongo is cooked! without a light weight HTTP client (Realm) 

who ever deprecated realm shouldn't get promoted.

**Comment by vkarpov15** [comment]
We won't run MongoDB in cloudflare workers, but Mongoose's driver API makes it possible for Mongoose to speak HTTP under the hood. For example, that's how [stargate-mongoose](https://www.npmjs.com/package/stargate-mongoose) works: subs out default MongoDB driver for an HTTP-based driver that talks to DataStax's Data API.

**Comment by mohit-singh-13** [comment]
Hey buddies, is there any way to use MongoDB (with Mongoose) with CloudFlare Workers?

**Comment by vkarpov15** [comment]
@mohit-singh-13 as far as I know, there's no way to run Mongoose on Cloudflare Workers currently. Sorry.

**Comment by mohit-singh-13** [comment]
@vkarpov15 alright, thanks a lot

**Comment by Rahul-codoffer** [comment]
Now we can use the mongodb with the cloudflare. 
I have tested it's working fine.

https://github.com/jchoi2x/cf-mongodb-polyfills

**Comment by ceddybi** [comment]
> Now we can use the mongodb with the cloudflare. I have tested it's working fine.

Thank you very much Sir 🙏🙏🙏

**Comment by ceddybi** [comment]
> Now we can use the mongodb with the cloudflare. I have tested it's working fine.

@Rahul-codoffer  Thank you very much sir 🙏🙏🙏

**Comment by visibait** [comment]
> Now we can use the mongodb with the cloudflare. I have tested it's working fine.
> 
> https://github.com/jchoi2x/cf-mongodb-polyfills
> 
> But still unable to use the mongobd. We have to use the mondodb client.

That package will make the native MongoDB Driver work on cloudflare workers correct. 

However, Mongoose will throw an error when calling mongoose.connect() because it's loading its browser version (which lacks that method). To resolve this, update your import statement as follows:

``
import mongoose from "mongoose";

to

// @ts-expect-error
import mongoose from "mongoose/lib/index.js";
``

**Comment by Rahul-codoffer** [comment]
> > Now we can use the mongodb with the cloudflare. I have tested it's working fine.
> > https://github.com/jchoi2x/cf-mongodb-polyfills
> > But still unable to use the mongobd. We have to use the mondodb client.
> 
> There is no need to use that polyfills anymore. Workerd had an update today ([cloudflare/workerd#2721 (comment)](https://github.com/cloudflare/workerd/discussions/2721#discussioncomment-11983650)) that makes MongoDB Native Driver work natively. Just put the `nodejs_compat` compatibility flag in your wrangler.toml and update wrangler to >= 3.106.
> 
> However, Mongoose will throw an error when calling mongoose.connect() because it's loading its browser version (which lacks that method). To resolve this, update your import statement as follows:
> 
> import mongoose from "mongoose";
> to
> 
> // @ts-expect-error
> import mongoose from "mongoose/lib/index.js";
> It's worth noting that, for example, if we want to create a schema or use other features like `Schema` or `model`, we must also use the `mongoose/lib/index.js` import instead of the default `mongoose` import. Here's how this could look in practice:
> 
> // @ts-expect-error
> import { Schema, model } from "mongoose/lib/index.js";
> 
> interface User {
>   name: string;
>   username: string;
>   createdAt: Date;
> }
> 
> const userSchema = new Schema<User>({
>   name: { type: String, required: true },
>   username: { type: String, required: true },
>   createdAt: { type: Date, default: Date.now },
> });
> 
> const User = model("User", userSchema);
> export default User;
> If anyone has a better approach or an alternative way to address this issue, feel free to reply to this comment!

Yes, we can now use the Mongoose with the Cloudflare worker but I'm facing the issue while testing the Mongoose connection.

```
Error: The script will never generate a response.
    at async Object.fetch (file:///XXXXXXXXXXX/node_modules/miniflare/dist/src/workers/core/entry.worker.js:1029:22)
```

May be I this this error is related to the this thread.
https://github.com/cloudflare/workerd/issues/210

**Comment by huw** [comment]
@visibait Yep, the issue here is that Mongoose defines a `package.json#browser` key, and by default, Wrangler’s esbuild will pick that over the `main` key:

https://github.com/Automattic/mongoose/blob/9180d0272066deeda0cb926af567061b55c35f8d/package.json#L113-L126

Instead, Mongoose should use `package.json#exports`. Here’s my patch file (for use with `npm patch` etc.):

```diff
diff --git a/package.json b/package.json
index 46468fcb6a56ecd494c5a590b2940746a29c57ba..29a1a366f9e2adbdac15ee3dc3d43648d40eb3cd 100644
--- a/package.json
+++ b/package.json
@@ -112,6 +112,15 @@
   },
   "main": "./index.js",
   "types": "./types/index.d.ts",
+  "exports": {
+    ".": {
+      "workerd": "./index.js",
+      "node": "./index.js",
+      "browser": "./dist/browser.umd.js",
+      "types": "./types/index.d.ts",
+      "default": "./index.js"
+    }
+  },
   "engines": {
     "node": ">=16.20.1"
   },
```

The `workerd` key instructs Cloudflare Workers to use the Node bundle, rather than the browser bundle.

(I can also confirm Mongoose now fully works with Cloudflare Workers in `nodejs_compat` mode, so arguably, this issue should be closed once this small issue is patched over)

**Comment by huw** [comment]
The other footgun I experienced is that you have to remember to disconnect once you’re done with Mongo. Otherwise you’ll get:

```
[wrangler:inf] GET / 200 OK (4799ms)
✘ [ERROR] A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise's I/O context have already finished.

[wrangler:inf] GET / 500 Internal Server Error (7ms)
✘ [ERROR] Uncaught (in response) Error: The script will never generate a response.
```

Here’s the Hono middleware I use that fixes it, as an example:

```js
const db = createMiddleware(async (_, next) => {
  const db = await mongoose.connect(process.env.MONGO_DB_URI);
  await next();
  await db.disconnect();
});
```

**Comment by RaschidJFR** [comment]
It's been a while since the last update on this thread, so I just want to confirm that I'm able to query **MongoDB** using **Mongoose v9** on Cloudflare Workers by setting `"compatibility_flags": ["nodejs_compat"]` in `wrangler.jsonc`. 

Here's my working repo:
https://github.com/RaschidJFR/mongodb-cloudflare-workers/tree/mongoose

**Comment by jdgamble555** [comment]
Your repo is private fwi

**Comment by RaschidJFR** [comment]
> Your repo is private fwi

Tnx @jdgamble555 . Fixed

**Comment by xlogix** [comment]
> It's been a while since the last update on this thread, so I just want to confirm that I'm able to query **MongoDB** using **Mongoose v9** on Cloudflare Workers by setting `"compatibility_flags": ["nodejs_compat"]` in `wrangler.jsonc`.
> 
> Here's my working repo: https://github.com/RaschidJFR/mongodb-cloudflare-workers/tree/mongoose

I'm using Mongoose v8 and it doesn't work

**Comment by vkarpov15** [comment]
@xlogix have you tried Mongoose 9? What error are you getting?

**Comment by vkarpov15** [comment]
I'm going to close this since it seems like Mongoose 9 works with Cloudflare Workers.
