### ISSUE TITLE
MongoServerError: cannot create a new collection -- already using 527 collections of 500

### ISSUE THREAD

**Issue by PRANAY6201** [Automattic/mongoose#14625]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.0

### Node.js version

18

### MongoDB version

4.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11.3

### Issue

MongoServerError: cannot create a new collection -- already using 527 collections of 500
    at Connection.onMessage (/home/container/node_modules/mongodb/lib/cmap/connection.js:210:30)
    at MessageStream.<anonymous> (/home/container/node_modules/mongodb/lib/cmap/connection.js:63:60)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/home/container/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/home/container/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at TLSSocket.ondata (node:internal/streams/readable:809:22)
    at TLSSocket.emit (node:events:517:28) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  [Symbol(errorLabels)]: Set(0) {}
}

**Comment by vkarpov15** [comment]
[MongoDB Atlas M0, M2/M5 clusters only allow a maximum of 500 collections](https://www.mongodb.com/docs/atlas/reference/free-shared-limitations/?_ga=2.64883432.672284490.1656188568-609201914.1633727913#operational-limitations). Try deleting some collections to free up some room, or upgrade to the next cluster tier, or run MongoDB on your own hardware. There's nothing Mongoose can do about this limitation.

![image](https://github.com/Automattic/mongoose/assets/1620265/a02d0e75-3555-45bb-98fe-069c4d6cd11c)
