### ISSUE TITLE
URI options parsing not spec compliant

### ISSUE THREAD

**Issue by alexbevi** [Automattic/mongoose#14997]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.x

### Node.js version

16.x

### MongoDB server version

7.x

### Description

The MongoDB [Connection String specification](https://github.com/mongodb/specifications/blob/e26b8cdff55ec33c28cc0fbb2b4eeba004093c1e/source/connection-string/connection-string-spec.md) outlines handling rules for lists (such as [read preference tag sets](https://www.mongodb.com/docs/manual/core/read-preference-tags)) such as:

> ?readPreferenceTags=dc:ny,rack:1&readPreferenceTags=dc:ny&readPreferenceTags=

When a connection string with `readPreferenceTags` that can contain an empty tag value are passed to `mongoose.connect`, a URI parsing failure is thrown - which does not reproduce when using the Node driver directly.

### Steps to Reproduce

With Mongoose:

```js
const mongoose = require('mongoose');
const url = 'mongodb+srv://xxx:xxx@aaa.pnobe.mongodb.net/nodejs?readPreferenceTags=nodeType:READ_ONLY&readPreferenceTags=';

mongoose.connect(url)
.then (async () => run())
.catch(console.dir)
.finally(()=> {
    mongoose.disconnect();
});

async function run() {  
    console.log("Connected");
};
```
```
MongoAPIError: URI cannot contain options with no value
    at parseOptions (/home/ubuntu/tour/node_modules/mongoose/node_modules/mongodb/lib/connection_string.js:220:19)
    at new MongoClient (/home/ubuntu/tour/node_modules/mongoose/node_modules/mongodb/lib/mongo_client.js:48:63)
    at NativeConnection.createClient (/home/ubuntu/tour/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:288:14)
    at NativeConnection.openUri (/home/ubuntu/tour/node_modules/mongoose/lib/connection.js:738:34)
    at Mongoose.connect (/home/ubuntu/tour/node_modules/mongoose/lib/index.js:404:15)
    at Object.<anonymous> (/home/ubuntu/tour/QuickTourMongoose.js:6:10)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
  [Symbol(errorLabels)]: Set(0) {}
}
```

### Expected Behavior

With the Node driver:

```js
const MongoClient = require('mongodb').MongoClient;
const url = 'mongodb+srv://xxx:xxx@aaa.pnobe.mongodb.net/nodejs?readPreferenceTags=nodeType:READ_ONLY&readPreferenceTags=';

const client = new MongoClient(url);
run()
.catch(console.dir)
.finally(async () => {await client.close();})

async function run() {
	console.log("Connected");
}
```

```
Connected
```

**Comment by alexbevi** [comment]
Not sure if there's a workaround to this in the meantime. I tried something like the following, but it doesn't work:
```js
const options =  Object.create(null);
options["readPreference"] = Object.create(null);
options.readPreference["tags"] = [ { "nodeType": "READ_ONLY" }, {} ];

mongoose.connect(url, options)
```
```
MongoParseError: Unknown ReadPreference value: [object Object]
    at transform (/home/ubuntu/tour/node_modules/mongoose/node_modules/mongodb/lib/connection_string.js:827:19)
    at setOption (/home/ubuntu/tour/node_modules/mongoose/node_modules/mongodb/lib/connection_string.js:460:36)
    at parseOptions (/home/ubuntu/tour/node_modules/mongoose/node_modules/mongodb/lib/connection_string.js:288:13)
    at new MongoClient (/home/ubuntu/tour/node_modules/mongoose/node_modules/mongodb/lib/mongo_client.js:48:63)
    at NativeConnection.createClient (/home/ubuntu/tour/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:288:14)
    at NativeConnection.openUri (/home/ubuntu/tour/node_modules/mongoose/lib/connection.js:738:34)
    at Mongoose.connect (/home/ubuntu/tour/node_modules/mongoose/lib/index.js:404:15)
    at Object.<anonymous> (/home/ubuntu/tour/QuickTourMongoose.js:12:10)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10) {
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by vkarpov15** [comment]
I'm able to repro this with Mongoose 7, but not Mongoose 8. What version of the Node driver are you using that connects successfully?

**Comment by alexbevi** [comment]
This issue actually appears to be in the 5.x Node.js driver (fixed in 6.0)

**Comment by vkarpov15** [comment]
Then that would make sense. Mongoose 7 uses Node.js driver 5.x, Mongoose 8 uses Node.js driver 6.x. So the answer here is to upgrade to Mongoose 8.

I double checked and Mongoose 7+8 don't do any connection string manipulation: the string you pass to `mongoose.connect()` is the string that ends up in `MongoClient.prototype.connect()`.

**Comment by alexbevi** [comment]
Thanks for clarifying @vkarpov15. Closing this out.
