### ISSUE TITLE
 Property 'id' of object is not a function v3.6.19

### ISSUE THREAD

**Issue by jspears** [Automattic/mongoose#1682]
When using the mpath notation to update an array of subdocuments, it blows up.
Attached is a nodeunit test case 

```javascript

var mongoose = require('mongoose'),
    Schema = mongoose.Schema ;

var CommentSchema = new Schema({
    title:{type: String}, body: {type:String}
});


var BlogPostSchema = new Schema({
    title: String, body: String, comments: [CommentSchema]
});
var BlogPost = mongoose.model('BlogPost', BlogPostSchema);
var Comment = mongoose.model('Comment', CommentSchema);
var connection = mongoose.connection;
var blog = new BlogPost({
    title: 'Hello',
    body: 'goodbye',
    comments: [
        {title: 'Comment 1', body: 'Body Comment 1'},
        {title: 'Comment 2', body: 'Body Comment 2'}
    ]
});

var id;
module.exports.setUp = function (done) {
    connection.on('open', function () {
        connection.db.dropDatabase(function () {
            console.log('dropped database [' + connection.name + ']');
            blog.save(function (err, obj) {
                console.log('all done with saving user', obj);
                id = obj._id;
                done();
            });
        });
    })
    mongoose.connect('mongodb://localhost/deepexample', function () {
        console.log('connected');

    });
}
module.exports.tearDown = function (done) {
    mongoose.disconnect(function () {
        console.log('disconnecting');
        done();

    });
}

module.exports['findById and update using set'] = function (test) {
    BlogPost.findOne({_id:id}, function (err, obj) {
        if (err) {
            console.log('err ' + id, err)
            test.done(err);
        }
//If you switch these two lines it works.
//       obj.comments[1].title = 'Nope';
        obj.set('comments.1', {title: 'Nope'})
        obj.save(function (err, obj) {
            if (err) {
                console.log('Error', err.message, err.stack);
                test.ok(false);
                return test.done();
            }
            console.log('got', obj);
            test.equals(obj.comments[1].title, 'Nope');
            test.done();

        })
    })

}

```

Stack Trace looks like
```
Error Property 'id' of object { title: 'Comment 2',
  body: 'Body Comment 2',
  _id: 5227ee26e182586d15000003 } is not a function TypeError: Property 'id' of object { title: 'Comment 2',
  body: 'Body Comment 2',
  _id: 5227ee26e182586d15000003 } is not a function
    at DocumentArray.cast (path/node_modules/mongoose/lib/schema/documentarray.js:137:36)
    at DocumentArray.cast (path/node_modules/mongoose/lib/schema/documentarray.js:121:17)
    at DocumentArray.SchemaType.applySetters (path/node_modules/mongoose/lib/schematype.js:477:17)
    at path/node_modules/mongoose/lib/document.js:545:18
    at model.Document.$__try (path/node_modules/mongoose/lib/document.js:758:8)
    at model.Document.set (path/node_modules/mongoose/lib/document.js:544:24)
    at Promise.<anonymous> (path/test/deepmongoose-test.js:60:13)
    at Promise.<anonymous> (path/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (path/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
    at Promise.fulfill (path/node_modules/mongoose/node_modules/mpromise/lib/promise.js:92:20)
    at path/node_modules/mongoose/lib/query.js:1823:13
    at model.Document.init (path/node_modules/mongoose/lib/document.js:251:11)
    at completeOne (path/node_modules/mongoose/lib/query.js:1821:10)
    at path/node_modules/mongoose/lib/query.js:1789:11
    at path/node_modules/mongoose/lib/utils.js:414:16
    at path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:953:5
    at Cursor.nextObject (path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:678:5)
    at commandHandler (path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:658:14)
    at path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1670:9
    at Server.Base._callHandler (path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
    at path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
    at MongoReply.parseBody (path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (path/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:699:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:382:10)
    at emitReadable (_stream_readable.js:377:5)
    at readableAddChunk (_stream_readable.js:142:7)
    at Socket.Readable.push (_stream_readable.js:112:10)
    at TCP.onread (net.js:511:21)
disconnecting

  

```

**Comment by vkarpov15** [comment]
Don't think this is still an issue, but re-open if its still a problem. Issue's been stale for a long time.
