### ISSUE TITLE
Cannot write to a secondary

### ISSUE THREAD

**Issue by habicm** [Automattic/mongoose#1711]
I have a web server connecting to mongolab, I have been developing without any issue, however my server is going to QA and after one day I am getting following error know that I am using just single server.

Error: Cannot write to a secondary
at canCheckoutWriter (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:756:12)
at Server.checkoutWriter (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:771:16)
at __executeInsertCommand (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1651:38)
at Db._executeInsertCommand (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1772:5)
at insertAll (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:330:13)
at Collection.insert (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:92:3)
at NativeCollection.(anonymous function) [as insert](/var/node/ci/fieldevent-website/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:129:21)
at model.save (/var/node/ci/fieldevent-website/node_modules/mongoose/lib/model.js:173:21)
at model._done (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/hooks/hooks.js:59:24)
at _next (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/hooks/hooks.js:52:28)
at fnWrapper (/var/node/ci/fieldevent-website/node_modules/mongoose/node_modules/hooks/hooks.js:159:8)

I am connecting to mongoDB using this:

var options =  {
                        server:  { poolSize:  5,
                                   socketOptions: { keepAlive: 1 }
                        }
                    }

var connection = mongoose.createConnection(db.url, options, function(err) {
   if (err) {
       Logger.error("Could not connect to database with error: " + err);
   }
})

Thanks in advance for your help

**Comment by slashsteiner** [comment]
We've also encountered this error just yesterday. Anyone found a fix to it?

**Comment by vkarpov15** [comment]
MongoDB doesn't allow you to write to secondaries. No way around it at the moment. Either way, not a mongoose issue.

**Comment by lpuccini** [comment]
Why do I get this error without a replica set then? It sounds a bit strange to me

**Comment by vkarpov15** [comment]
You shouldn't get this error without a replica set, unless mongoose somehow
thinks you are. How are you connecting to mongodb?

**Comment by waltonryan** [comment]
What worked for me was updating the mongodb connection url coming from MongoLab. In your MongoLab account, you'll see the `MONGODB URI` something like `mongodb://<dbuser>:<dbpassword>@<db>:<port>,<db>:<port>/<dbname>?replicaSet=rs-ds023524` You'll see this has a comma separated list which allows for the replica set. Update that and the `cannot write to secondary` error goes away.

**Comment by joeyfigaro** [comment]
Is there any reason Mongoose might be attempting to connect to/use a repl set with a connection string that has no params? Our production builds are blowing up with the following: 
```shell
Error: Cannot write to a secondary
    at canCheckoutWriter (/var/local/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:730:13)
    at Server.checkoutWriter (/var/local/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:752:16)
    at Collection.update (/var/local/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:651:63)
    at /var/local/www/node_modules/connect-mongo/lib/connect-mongo.js:340:18
    at MongoStore.getCollection (/var/local/www/node_modules/connect-mongo/lib/connect-mongo.js:210:11)
    at MongoStore.set (/var/local/www/node_modules/connect-mongo/lib/connect-mongo.js:338:10)
    at Session.save (/var/local/www/node_modules/express-session/session/session.js:63:25)
    at ServerResponse.res.end (/var/local/www/node_modules/express-session/index.js:194:28)
    at Array.write (/var/local/www/node_modules/express/node_modules/finalhandler/index.js:126:9)
^C    at listener (/var/local/www/node_modules/express/node_modules/on-finished/index.js:164:15)
    at onFinish (/var/local/www/node_modules/express/node_modules/on-finished/index.js:95:5)
    at callback (/var/local/www/node_modules/express/node_modules/on-finished/node_modules/ee-first/index
```

Also may be worth mentioning that this is how our session store is set up: 
```js
app.use(session({
		secret: process.env.SESSION_SECRET || config.keys.session.secret,
		key: process.env.SESSION_IDENTIFIER || config.keys.session.identifier,
		proxy: true,
		store: new store({ mongooseConnection: app.get('connection') }),
		resave: true,
		saveUninitialized: true
	}));
```

**Comment by vkarpov15** [comment]
No idea, looks like a connect-mongo issue, one of many. I would strongly recommend not using connect-mongo and instead using connect-mongodb-session
