### ISSUE TITLE
schema.path.options is coming as undefined

### ISSUE THREAD

**Issue by jintoppy** [Automattic/mongoose#1824]
I am getting the following error while trying to save. This works fine locally. When I upload it on AWS only this issue happens. 

Error is in mongoose/lib/document.js line 449

this.schema.paths[key] && this.schema.paths[key].options.ref 

Full error is given below.

TypeError: Cannot read property 'ref' of undefined
    at model.Document.set (/home/arjun/public_html/ecinta/node_modules/mongoose/lib/document.js:449:74)
    at model.Document (/home/arjun/public_html/ecinta/node_modules/mongoose/lib/document.js:60:10)
    at model.Model (/home/arjun/public_html/ecinta/node_modules/mongoose/lib/model.js:43:12)
    at new model (/home/arjun/public_html/ecinta/node_modules/mongoose/lib/model.js:2491:11)
    at exports.create (/home/arjun/public_html/ecinta/app/controllers/users.js:59:13)
    at callbacks (/home/arjun/public_html/ecinta/node_modules/express/lib/router/index.js:164:37)
    at param (/home/arjun/public_html/ecinta/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/arjun/public_html/ecinta/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/arjun/public_html/ecinta/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/arjun/public_html/ecinta/node_modules/express/lib/router/index.js:33:10)

**Comment by ignasg** [comment]
Still reproduced the issue with all packages and node updated now. Added a workaround to ignore ref if options is not defined.

**Comment by vkarpov15** [comment]
@ignasg please provide repro instructions

**Comment by ignasg** [comment]
I dont have simple instructions as it involves upgrading node from v10 to v12 and upgrading all npm packages on our in-house software.

**Comment by vkarpov15** [comment]
which version of mongoose?

**Comment by ignasg** [comment]
"version": "3.8.0"
