### ISSUE TITLE
$rename throws cast error

### ISSUE THREAD

**Issue by klimashkin** [Automattic/mongoose#1845]
Hello!
When I try to do simple $rename update I get "Cast to number error".
```Photo.update({r2: 167}, {$rename: {r2: 'r1'}}, {multi: true})``` 

But if I do this through Model.collection.update or through mongo console all ok.
```Photo.collection.update({r2: 167}, {$rename: {r2: 'r1'}}, {multi: true})```

**Comment by jrvidal** [comment]
Apparently, `Query.prototype._castUpdate` casts the new field name to the corresponding type for `$rename` queries. Here is a simple test case:

```javascript
var mongoose = require('mongoose'),

	User = mongoose.model('User', new mongoose.Schema({
		cool: Boolean
	}));

User.update({}, {
	$rename: {
		cool: 'awesome'
	}
}, function (err) {
	console.log(err.stack);
});
```

It failed for me in `3.8.25`.

**Comment by sitegui** [comment]
It also seems to fail in mongoose@4.0.2

```js
Order.update({
	ETA: {
		$ne: null
	}
}, {
	$rename: {
		ETA: 'deliveryETA'
	}
}, {
	multi: true
}, done)
```

```
CastError: Cast to date failed for value "deliveryETA" at path "ETA"
    at SchemaDate.cast (node_modules\mongoose\lib\schema\date.js:232:9)
    at SchemaDate.castForQuery (node_modules\mongoose\lib\schema\date.js:277:17)
    at Query._castUpdateVal (node_modules\mongoose\lib\query.js:2241:17)
    at Query._walkUpdatePath (node_modules\mongoose\lib\query.js:2190:25)
    at Query._castUpdate (node_modules\mongoose\lib\query.js:2075:23)
    at Query.update (node_modules\mongoose\lib\query.js:1916:22)
    at Function.update (node_modules\mongoose\lib\model.js:1730:13)
```

Using `Order.collection.update()` works.

Is this intended? If yes, mongoose may want to warn about this in the docs.
