### ISSUE TITLE
checkKey fails a $ne filter on executeDbCommand

### ISSUE THREAD

**Issue by wshaver** [Automattic/mongoose#1876]
Recently updated to mongoose 3.8.4 and started seeing this issue. 

This issue happens when using text search on a defined index. 

``` javascript

var searchText = '';//user supplied
var filter = {published: true, deleted: {$ne : true}};
Books.db.db.executeDbCommand({'text': 'books',
            search: searchText,
            filter: filter,
        }, function(err, results){
//use them
});
```

Here's the stack trace:

```
unknown errors: Error: key $ne must not start with '$'
    at Error (unknown source)
    at Function.checkKey (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:1442:13)
    at serializeObject (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:356:14)
    at packElement (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:855:23)
    at serializeObject (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:360:15)
    at packElement (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:855:23)
    at serializeObject (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:360:15)
    at Function.serializeWithBufferAndIndex (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:332:10)
    at BSON.serializeWithBufferAndIndex (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:1526:15)
    at QueryCommand.toBinary (C:\projects\Books\node_modules\mongoose\node_modules\mongodb\lib\mongodb\commands\query_command.js:223:35)
```

**Comment by EdwardStudy** [comment]
Thank you for the tips: use command() function is a good way.
