### ISSUE TITLE
populate with elemMatch throwing "where" error

### ISSUE THREAD

**Issue by RonaldJerez** [Automattic/mongoose#2022]
When using populate with the elemMatch option under version > 3.6.20 I get the following error.  I am assuming it is expecting a where option, however given that it is a populate I am assuming the where should be that populate's path value
#### Stack Trace @ 3.8.8:

```
Error: elemMatch() must be used after where() when called with these arguments
    at Query._ensurePath (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2341:11)
    at Query.elemMatch (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/node_modules/mquery/lib/mquery.js:639:10)
    at Query.setOptions (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/node_modules/mquery/lib/mquery.js:182:20)
    at Query.setOptions (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/lib/query.js:860:32)
    at Query (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/node_modules/mquery/lib/mquery.js:55:10)
    at new Query (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/lib/query.js:66:10)
    at Function.find (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/lib/model.js:936:12)
    at populate (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/lib/model.js:2172:9)
    at Function.Model.populate (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/lib/model.js:2036:5)
    at model.populate (/Volumes/ramdisk/Ronald/Temporary/test/node_modules/mongoose/lib/document.js:1726:22)
```
#### Test code:

note that this works as expected under 3.6.20

``` javascript
var mongoose        = require("mongoose");
var Schema          = mongoose.Schema;
var oid             = Schema.Types.ObjectId

mongoose.connect("mongodb://localhost:27017/test1");

// schemas
var user_schema = new Schema({name : String, company : oid});
var company_schema = new Schema({name : String, users : [oid] });

// models
var User = mongoose.model('Users', user_schema);
var Company = mongoose.model('Company', company_schema);

// add some data
var new_comp = Company({name : "Acme"});
var new_user = User({name : "Coyote", company : new_comp.id });
new_comp.users.push(new_user.id);

new_comp.save(function(err){
    // test populate
    new_user.populate({
        path : 'company',
        model : 'Company',
        options : { elemMatch : {'users' : new_user.id} }
    }, 
    function(err, output) {
        if (err)
            console.log(err);
        else
            console.log(output);
    });
});
```

Using
mongoose v. 3.8.8
mongodb v. 2.2.2
node  v. 0.10.15

**Comment by akarshsatija** [comment]
@dlanor15 It isn't showing error but its not working.

**Comment by vkarpov15** [comment]
What do you mean by "not working"?

**Comment by vkarpov15** [comment]
Show some code samples please
