### ISSUE TITLE
TypeError: Cannot call method 'test' of undefined

### ISSUE THREAD

**Issue by TangMonk** [Automattic/mongoose#2189]
my user schema:
```javascript
var UserSchema = new Schema({
    username: { type: String, required: true, unique: true },
    password: { type: String },
    nickname: { type: String },
    profile:  { type: String },
    city:     { type: String },
    sex:      { type: String, enum: 'male female'.split(' ') },
    phone:    { type: String, match:  phoneLengthValidate },
    create_at:{ type: Number },
    update_at:{ type: Number }
});

/*phone length validate*/
function phoneLength(val){
    return 13 == val.length;
}

var phoneLengthValidate = [ phoneLength, "invalid phone length" ];
```
then i create a user
```javascript
user.create({
    "username": "12sss3",
    "password": "123",
    "phone": 1234567890123
}, function(err, user) {
    if (err) console.log(err)

    console.log(user)
})
```
but throw my an error:
```bash
Users/tangmonk/mygit/nodejs/miccity/node_modules/mongoose/lib/schema/string.js:221
      ? regExp.test(v)
               ^
TypeError: Cannot call method 'test' of undefined
    at model.matchValidator (/Users/tangmonk/mygit/nodejs/miccity/node_modules/mongoose/lib/schema/string.js:221:16)
    at /Users/tangmonk/mygit/nodejs/miccity/node_modules/mongoose/lib/schematype.js:627:28
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/Users/tangmonk/mygit/nodejs/miccity/node_modules/mongoose/lib/schematype.js:614:19)
    at /Users/tangmonk/mygit/nodejs/miccity/node_modules/mongoose/lib/document.js:956:9
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by vkarpov15** [comment]
A few issues with the above code:

1) `phoneLengthValidate` is undefined when you declare the schema, so that won't work.
2) `match` takes [a regular expression](http://mongoosejs.com/docs/api.html#schema_string_SchemaString-match), not a function.

The fact that match crashes when its given an undefined value is a small problem, and is fixed in the above commits.
