### ISSUE TITLE
Allow saving of new embedded ref prior to saving master doc

### ISSUE THREAD

**Issue by fiznool** [Automattic/mongoose#2228]
Here is my schema setup:

``` js
var _ = require('lodash'),
    mongoose = require('mongoose'),
    Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/save-refs-test');

var ClubSchema = new Schema({
  name: String,
  location: String
});

var Club = mongoose.model('Club', ClubSchema);

var PlayerSchema = new Schema({
  name: String,
  club: {
    type: Schema.Types.ObjectId,
    ref: 'Club'
  }
});

PlayerSchema.pre('save', function(next) {
  if(_.isPlainObject(this.club)) {
    Club.create(this.club, function(err, clubDoc) {
      if(err) { return next(err); }
      this.club = clubDoc._id;
      next();
    });
  } else {
    next();
  }
});

var Player = mongoose.model('Player', PlayerSchema);
```

Notice the `PlayerSchema` hook - basically I'd like to be able to catch an instance where I'm saving an embedded reference which doesn't yet exist in the database, and save it first. Something along these lines:

``` js
var player = new Player({
  name: 'Alan Shearer',
  club: {
    name: 'Newcastle United',
    location: 'Newcastle upon Tyne, UK'
  }
});

player.save(function(err, playerDoc) {
  if(err) {
    throw err;
  }
  console.log(playerDoc.name + ' saved successfully');
});
```

But, when this is run, instead of printing out

```
Alan Shearer saved successfully
```

I get an error:

```
CastError: Cast to ObjectId failed for value "[object Object]" at path "club"
    at ObjectId.cast (/home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/schema/objectid.js:116:13)
    at ObjectId.SchemaType.applySetters (/home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/schematype.js:526:17)
    at /home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/document.js:547:18
    at model.Document.$__try (/home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/document.js:760:8)
    at model.Document.set (/home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/document.js:546:24)
    at model.Document.set (/home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/document.js:457:18)
    at model.Document (/home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/document.js:60:10)
    at model.Model (/home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/model.js:42:12)
    at new model (/home/fiznool/mongoose-save-refs/node_modules/mongoose/lib/model.js:2515:11)
    at Object.<anonymous> (/home/fiznool/mongoose-save-refs/server.js:36:14)
```

**Comment by helgeh** [comment]
@nubbel Have you tried the post init solution?

**Comment by souzadevinicius** [comment]
+1

**Comment by Asafb26** [comment]
i can confirm that post init doesnt work, anyone found a solution?

**Comment by vkarpov15** [comment]
@Asafb26 not yet. I'll re-investigate this this week, perhaps recent changes have made this doable.

**Comment by vkarpov15** [comment]
So I took a look and it looks like the below script works fine:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh2228`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const ClubSchema = new Schema({
    name: String,
    location: String
  });

  const Club = mongoose.model('Club', ClubSchema);

  const PlayerSchema = new Schema({
    name: String,
    club: {
      type: Schema.Types.ObjectId,
      ref: 'Club'
    }
  });

  PlayerSchema.pre('save', async function() {
    if(this.club && this.club.isNew) {
      await Club.create(this.club);
    }
  });

  const Player = mongoose.model('Player', PlayerSchema);

  const c = new Club({ name: 'Test1' });
  const p = new Player({ name: 'Test2', club: c });
  await p.save();
}
```

Am I missing something here or is that sufficient to cover this use case?

**Comment by hasezoey** [comment]
@vkarpov15 i think the issue is about embedding it
```js
const p = new Player({ name: 'Test2', club: new Club({ name: 'Test1' }) }); // just creates an id, but not the document itself
```

**Comment by vkarpov15** [comment]
Actually @hasezoey I looked more closely and your suggestion still works. Script:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh2228`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
  
  const ClubSchema = new Schema({
    name: String,
    location: String
  });
  
  const Club = mongoose.model('Club', ClubSchema);
  
  const PlayerSchema = new Schema({
    name: String,
    club: { 
      type: Schema.Types.ObjectId,
      ref: 'Club'
    } 
  });

  PlayerSchema.pre('save', async function() {
    if(this.club && this.club.isNew) {
      await Club.create(this.club);
    }
  });

  const Player = mongoose.model('Player', PlayerSchema);

  const p = new Player({ name: 'Test2', club: new Club({ name: 'Test1' }) });
  await p.save();
}
```

Output:

```
$ node gh-2228.js 
(node:26243) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Mongoose: clubs.insertOne({ _id: ObjectId("5d4e2aa51e6ad86683090dda"), name: 'Test1', __v: 0 }, { session: null })
Mongoose: players.insertOne({ _id: ObjectId("5d4e2aa51e6ad86683090ddb"), name: 'Test2', club: ObjectId("5d4e2aa51e6ad86683090dda"), __v: 0 }, { session: null })
done
```

Note that there is a new club inserted in the db.
