### ISSUE TITLE
Cannot run Model.mapReduce on mongoose v3.8.16

### ISSUE THREAD

**Issue by razvanz** [Automattic/mongoose#2293]
I am trying to run mapReduce against my database but It does not work.
Since I couldn't make it work I just used the flowing code for testing purposes:
```javascript
var calculator = {
			mapReduce: 'Chats',
			map: function(){},
			reduce: function(){},
			scope: {
					username: 'test'
			},
			verbose: true
	};

	return Chat.mapReduce(calculator, function (err, result) {
		console.log(err);
		// console.log(result);
		callback(err, result);
	});
```

In mongoose v3.8.16 I am getting the error: 

```javascript
{ [MongoError: exception: ReferenceError: __cov_7k0Fa2zrm5Cgnf4AH0$K5Q is not defined near 'nction (){__cov_7k0Fa2zrm5Cgnf4AH0$K5Q.f[' ]
  name: 'MongoError',
  errmsg: 'exception: ReferenceError: __cov_7k0Fa2zrm5Cgnf4AH0$K5Q is not defined near \'nction (){__cov_7k0Fa2zrm5Cgnf4AH0$K5Q.f[\' ',
  code: 16722,
  ok: 0 }
```

It works in mongoose v3.8.8.

**Comment by dcharbonnier** [comment]
/* istanbul ignore next */
does not prevent from instrumenting the code so it fail, does anybody have a workaround for this problem ?

**Comment by vkarpov15** [comment]
What sort of error are you getting?

**Comment by fyockm** [comment]
Did anyone ever figure this out? Seems to be related to `mapReduce`.

Here is the exact error:

```bash
$ node_modules/.bin/istanbul cover _mocha -- test/statSpec.js

     MongoError: exception: ReferenceError: __cov_9pvzj$DQoPkEFVshRs_FFQ is not defined
    at _funcs1 (_funcs1:1:23) near 'nction (){__cov_9pvzj$DQoPkEFVshRs_FFQ.f['
      at Function.MongoError.create (/Users/drew/Projects/bessemer/engine/node_modules/mongodb-core/lib/error.js:31:11)
      at /Users/drew/Projects/bessemer/engine/node_modules/mongodb-core/lib/topologies/server.js:776:66
      at Callbacks.emit (/Users/drew/Projects/bessemer/engine/node_modules/mongodb-core/lib/topologies/server.js:95:3)
      at null.messageHandler (/Users/drew/Projects/bessemer/engine/node_modules/mongodb-core/lib/topologies/server.js:249:23)
      at Socket.<anonymous> (/Users/drew/Projects/bessemer/engine/node_modules/mongodb-core/lib/connection/connection.js:262:22)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```

All my modules are currently up-to-date, running:

```
├── async@1.5.0
├── istanbul@0.4.1
├── lodash@3.10.1
├── mocha@2.3.4
├── mongoose@4.2.8
└── should@7.1.1
```

**Comment by fyockm** [comment]
@vkarpov15 I've created a simple gist to demonstrate. https://gist.github.com/fyockm/8590e9f02d24ee19aa09

**Comment by vkarpov15** [comment]
Yeah this is entirely due to how mapReduce works with istanbul - mongodb stringifies your functions to pass them to the mongodb server. Istanbul transforms your code in order to do coverage properly, which is bad because mongodb doesn't know what "__cov_9tvxKQzOKv6vn95EmDGJ3A" is. Just define your map/reduce functions as strings rather than as functions and it should work:

```javascript
var o = {
    // Notice the back-ticks below.
    map: `function() {
        emit('name', 1);
    }`,
    reduce: `function(k, vals) {
        return Array.sum(vals);
    }`
};
```
