### ISSUE TITLE
Can't push my embedded documents into my documents.

### ISSUE THREAD

**Issue by jeromegn** [Automattic/mongoose#230]
At first I thought it was because of my dirty attributes, hence the extra test, but both give me errors, exactly the same errors I usually get... Thoughts?

```
'test pushing simple embedded documents into a document': function(){

  var EmbeddedSchema = new Schema({
    title   : String
  });

  var ParentSchema = new Schema({
    embeds : [EmbeddedSchema]
  });

  mongoose.model('Parent', ParentSchema);

  var db = start(),
      Parent = db.model('Parent');

  var parent = new Parent();

  var cleanData = {
    title   : "Some string"
  };

  parent.embeds.push([cleanData, cleanData, cleanData]);

  parent.save(function(err){
    process.nextTick(function(){
      parent.embeds.should.have.length(3);
      db.close();
    })
  });

},

'test pushing embedded documents with dirty attributes into a document': function(){

  var EmbeddedSchema = new Schema({
    title   : String,
    someObj : {}
  });

  var ParentSchema = new Schema({
    embeds : [EmbeddedSchema]
  });

  mongoose.model('Parent', ParentSchema);

  var db = start(),
      Parent = db.model('Parent');

  var parent = new Parent();

  var dirtyData = {
    title   : "Some string",
    someObj : {
      aString : "bleh!",
      aDate   : Date.now()
    }
  };

  parent.embeds.push([dirtyData, dirtyData, dirtyData]);

  parent.save(function(err){
    process.nextTick(function(){
      parent.embeds.should.have.length(3);
      db.close();
    })
  });

}
```

Errors:

```
model.test.js test pushing simple embedded documents into a document: TypeError: Cannot set property 'title' of undefined
 at EmbeddedDocument.<anonymous> (/Users/jgn/Desktop/mongoose/lib/mongoose/document.js:217:25)
 at EmbeddedDocument.set (/Users/jgn/Desktop/mongoose/lib/mongoose/types/document.js:39:17)
 at EmbeddedDocument.<anonymous> (/Users/jgn/Desktop/mongoose/lib/mongoose/document.js:192:14)
 at EmbeddedDocument.set (/Users/jgn/Desktop/mongoose/lib/mongoose/types/document.js:39:17)
 at EmbeddedDocument.<anonymous> (/Users/jgn/Desktop/mongoose/lib/mongoose/document.js:190:14)
 at EmbeddedDocument.set (/Users/jgn/Desktop/mongoose/lib/mongoose/types/document.js:39:17)
 at EmbeddedDocument.Document (/Users/jgn/Desktop/mongoose/lib/mongoose/document.js:29:17)
 at EmbeddedDocument.EmbeddedDocument (/Users/jgn/Desktop/mongoose/lib/mongoose/types/document.js:19:12)
 at new EmbeddedDocument (/Users/jgn/Desktop/mongoose/lib/mongoose/schema/documentarray.js:25:17)
 at MongooseDocumentArray._cast (/Users/jgn/Desktop/mongoose/lib/mongoose/types/documentarray.js:49:13)


model.test.js test pushing embedded documents with dirty attributes into a document: TypeError: Cannot set property 'title' of undefined
 at EmbeddedDocument.<anonymous> (/Users/jgn/Desktop/mongoose/lib/mongoose/document.js:217:25)
 at EmbeddedDocument.set (/Users/jgn/Desktop/mongoose/lib/mongoose/types/document.js:39:17)
 at EmbeddedDocument.<anonymous> (/Users/jgn/Desktop/mongoose/lib/mongoose/document.js:192:14)
 at EmbeddedDocument.set (/Users/jgn/Desktop/mongoose/lib/mongoose/types/document.js:39:17)
 at EmbeddedDocument.<anonymous> (/Users/jgn/Desktop/mongoose/lib/mongoose/document.js:190:14)
 at EmbeddedDocument.set (/Users/jgn/Desktop/mongoose/lib/mongoose/types/document.js:39:17)
 at EmbeddedDocument.Document (/Users/jgn/Desktop/mongoose/lib/mongoose/document.js:29:17)
 at EmbeddedDocument.EmbeddedDocument (/Users/jgn/Desktop/mongoose/lib/mongoose/types/document.js:19:12)
 at new EmbeddedDocument (/Users/jgn/Desktop/mongoose/lib/mongoose/schema/documentarray.js:25:17)
 at MongooseDocumentArray._cast (/Users/jgn/Desktop/mongoose/lib/mongoose/types/documentarray.js:49:13)
```

**Comment by YASHVEER321** [comment]
hi my same program not work its give same error -------TypeError: Cannot read property '$pushAll' of undefined
plz give mi the answer....Thanks

**Comment by vkarpov15** [comment]
Please provide code sample

**Comment by YASHVEER321** [comment]
hi my same program not work its give same error -------TypeError: Cannot read property '$pushAll' of undefined
plz give mi the answer....Thanks

**Comment by YASHVEER321** [comment]
/**
 * Module dependencies.
 */

var mongoose = require('mongoose')
  , Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/testing');

/**
 * Schema definition
 */

var BlogPostSchema = new Schema({
    title     : String
  , slug      : String
  , date      : { type: Date, default: Date.now }
  , comments  : [Comments]
});

// recursive embedded-document schema

var Comments = new Schema();

Comments.add({
    title     : { type: String, index: true }
  , date      : { type: Date, default: Date.now }
  , body      : String
  , comments  : [Comments]
});

/**
 * Define model.
 */

mongoose.model('BlogPost', BlogPostSchema);

var BlogPost = mongoose.model('BlogPost');

var post = new BlogPost({title: "test", slug: "test"});

post.save(function(err){
  if (err)
    console.log(err)
  else {
    post.comments.pushAll([{title: "test", body: "woot woot"}, {title: "test2", body: "woot woot"}]);
    post.save(function(err){console.log(err); console.log(post.comments)});
  }
});
==============================================================
this is the file containt

**Comment by vkarpov15** [comment]
Just use `post.comments.push({title: "test", body: "woot woot"}, {title: "test2", body: "woot woot"})`, `pushAll()` is not a function you can call with mongoose document arrays
