### ISSUE TITLE
Populate does not work when options are passed. v3.8.16

### ISSUE THREAD

**Issue by razvanz** [Automattic/mongoose#2321]
I suppose this is a bug since populate does not work as supposed to: 
The model:
```javascript
{
    _id: 54215354070b4994298ee415,
    _ver: 0,
    created: Tue Sep 23 2014 13:02:44 GMT+0200 (CEST),
    messages: [],
    users: [ 54212a6cdb04e7f301473c40, 54213b989574e55617daf4d1 ] 
}
```

When populating the user array with: `populate: 'users'` everything works fine.

When trying to populate with the `select` option:
```javascript
populate: {
    path: 'users',
    select: '_id username displayName email'
}
```
an error is thrown: 
```javascript
/Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/lib/document.js:242
      this.populated(item.path, item._docs[id], item);
                                          ^
TypeError: Cannot read property '{ _id: 54215354070b4994298ee415,
  _ver: 0,
  created: Tue Sep 23 2014 13:02:44 GMT+0200 (CEST),
  messages: [],
  users: [ 54212a6cdb04e7f301473c40, 54213b989574e55617daf4d1 ] }' of undefined
    at model.Document.init (/Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/lib/document.js:242:43)
    at completeOne (/Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/lib/query.js:1392:10)
    at Promise.<anonymous> (/Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/lib/query.js:1160:11)
    at Promise.<anonymous> (/Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/lib/promise.js:114:23)
    at /Users/razvanz/Documents/workspace/Git repositories/masschat/node_modules/mongoose/lib/model.js:2029:23
    at process._tickCallback (node.js:419:13)
```

I also tried with the `path: 'users.$'`, but I still get the error.

**Comment by bglaz** [comment]
I encountered this issue as well. My populate options did not even include a `select`

**Comment by vkarpov15** [comment]
@bglaz can you provide a code example please?

**Comment by bglaz** [comment]
Sure, this is the query I was trying to run:

```javascript
db.Person.find({}, '-projects -access_token -refresh_token', {
        sort: {
          'department.name': 1,
          'active': -1,
          'name': 1
        },
        populate: {
          'path': 'department',
          'model': 'Department'
       }
      }, 
      function (err, docs) {
          //
       });
```

Here are the relevant parts of the Schema:

```javascript
var PersonSchema = new Schema({
  department: {type: Schema.Types.ObjectId, ref: 'Department'},
});
```

And here is the error:

```
/staging/webshares/paul-cup/node_modules/mongoose/lib/document.js:269
      this.populated(item.path, item._docs[id], item);
                                          ^

TypeError: Cannot read property '556ef990336238cb39365678' of undefined
```

That property is a valid `ObjectId` of a Person document:

```javascript
> db.people.find({'_id': ObjectId('556ef990336238cb39365678')}).pretty()
{
	"_id" : ObjectId("556ef990336238cb39365678"),
	"department" : ObjectId("5568a33cc7de854a156ec972"),
	...
}
```

I hope this is helpful!
