### ISSUE TITLE
Cannot add a virtual getter or setter to a schema, Object #<Object> has no method 'get'

### ISSUE THREAD

**Issue by eytanbiala** [Automattic/mongoose#2470]
I'm using version 3.8.19.

Code:

```
var UserSchema = new mongoose.Schema({
   username: {
      type: String,
   }
});
UserSchema.virtual('username').get(function() {
    return this.username;
}).set(function(username) {
    this.usernameLower = username.toLowerCase();
});
```

Error:

```
/project/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:296
          throw err;
                ^
TypeError: Object #<Object> has no method 'get'
    at Object.<anonymous> (/project/models/user.js:115:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by henriquecustodia** [comment]
Thank you @k10der, great answer!

**Comment by polyclick** [comment]
Would be great if @k10der's answer was in the docs here: http://mongoosejs.com/docs/guide.html
I had the same problem. I wanted to update a date when a specific field in my schema changed. Made the same mistake by making a virtual that had the same name as the schema property.
