### ISSUE TITLE
Inheritance with multiple levels

### ISSUE THREAD

**Issue by maelvis** [Automattic/mongoose#2845]
Hi,

I want to create an inheritance with multiple levels
Question inherits from Item
SimpleQuestion, OpenQuestion inherits from Question

but I have this error
```
Error: Discriminator "SimpleQuestion" can only be a discriminator of the root model
    at Function.discriminator (/home/mael-fosso/www/questan/node.js/node_modules/mongoose/lib/model.js:712:11)
    at Object.<anonymous> (/home/mael-fosso/www/questan/node.js/models/question/simple-question.js:7:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/mael-fosso/www/questan/node.js/controllers/survey.js:5:22)
    at Module._compile (module.js:456:26)
```

How to solve it please ?

**Comment by vkarpov15** [comment]
Multi-level inheritance is not currently supported with discriminators, and not planned for the near future. You can track the feature in issue #2851.
