### ISSUE TITLE
[4.0.1]Cannot assign to read only property 'length' of Error

### ISSUE THREAD

**Issue by throrin19** [Automattic/mongoose#2846]
Hi, i've test to migrate my application into 3.8.x to 4.0.1 and I have this error if i try to launch my project : 

```
Cannot assign to read only property 'length' of Error
TypeError: Cannot assign to read only property 'length' of Error
    at Object.<anonymous> (/home/throrin19/Development/Web/goomeoeventsapi/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/errors.js:84:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/home/throrin19/Development/Web/goomeoeventsapi/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/promise.js:34:14)
    at Object.<anonymous> (/home/throrin19/Development/Web/goomeoeventsapi/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/bluebird.js:24:38)
    at Module._compile (module.js:456:26)
```

I used MongoDB in version 2.6.9 and NodeJS in 0.10.38

**Comment by vkarpov15** [comment]
It's an issue with the bluebird promises library, see petkaantonov/bluebird#291 . I'm not particularly thrilled with the fact that mquery includes bluebird by default, but that's here to stay for now. I upgraded mquery's version of bluebird to fix this: https://github.com/aheckmann/mquery/commit/66e9ce16e3443c06e37bf71f552ef8c45b2e79b2

However, I'd generally agree with @petkaantonov that this is more of a problem with your JS environment than with bluebird, mquery, or mongoose - some other library (perhaps an old version of JSdom?) that you're using is doing something sketchy by making a read-only property on the `Error` or `Object` prototype.

**Comment by throrin19** [comment]
Thanks, I found the proble. In my project, we used an oldest version of `email-templates` and this version used and old version of `jsdom`.
