### ISSUE TITLE
Post save event not triggered, undefined is not a function thrown

### ISSUE THREAD

**Issue by ablankenship10** [Automattic/mongoose#2847]
I have a model with a post save hook which when a new document is created, mongoose throws an error for a callback being undefined. My post save hook is never called but the document is created.

```
index-0 (err): /root/fyre-sync/node_modules/gryd/node_modules/mongoose/lib/utils.js:413
index-0 (err):         throw err;
index-0 (err):               ^
index-0 (err): TypeError: undefined is not a function
index-0 (err):     at model.emit (events.js:98:17)
index-0 (err):     at handleSave (/root/fyre-sync/node_modules/gryd/node_modules/mongoose/lib/model.js:132:10)
index-0 (err):     at /root/fyre-sync/node_modules/gryd/node_modules/mongoose/lib/utils.js:408:16
index-0 (err):     at /root/fyre-sync/node_modules/gryd/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:253:7
index-0 (err):     at /root/fyre-sync/node_modules/gryd/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:640:7
index-0 (err):     at Server.Base._callHandler (/root/fyre-sync/node_modules/gryd/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
index-0 (err):     at /root/fyre-sync/node_modules/gryd/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
index-0 (err):     at MongoReply.parseBody (/root/fyre-sync/node_modules/gryd/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
index-0 (err):     at null.<anonymous> (/root/fyre-sync/node_modules/gryd/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
index-0 (err):     at emit (events.js:107:17)
```

model:
```
var schema = Schema({
    username: {type: String},
    password: {type: String},
    domain: {type: String},
    managed: {type:Boolean, default:false},
    status: {type: String, default: 'new', enum: ['new', 'active', 'failed', 'disabled']},
    createdDate: {
      type: Date, default: function () {
        return new Date();
      }
    },
    updatedDate: {
      type: Date, default: function () {
        return new Date();
      }
    }
  });

  schema.post('save', function (credential) {
    //never called
    console.log("save",arguments);
  });

  schema.set('versionKey', false);
  schema.set('id', false);
  db.model("Credential", schema);
```

Create call
```
        var creds = new Credential({
          username: body.username,
          password: body.password,
          domain: body.domain
        });
        creds.save(function (err, creds) {
          if (err) {
            res.status(500).json({success: false, error: "Unable to create new Credential object"});
          } else {
            creds.password = undefined;
            res.json({success: true, credentials: creds});
          }
        });
```

Offending code in mongoose (callback is not defined for some reason)
```
exports.tick = function tick (callback) {
  if ('function' !== typeof callback) return;
  return function () {
    try {
      callback.apply(this, arguments);
    } catch (err) {
      // only nextTick on err to get out of
      // the event loop and avoid state corruption.
      process.nextTick(function () {
        throw err;
      });
    }
  }
}
```

**Comment by vkarpov15** [comment]
Can you confirm which version of mongoose?

**Comment by ablankenship10** [comment]
3.8.23

**Comment by ablankenship10** [comment]
I found the issue. I have the field 'domain' in this object. There seems to be a collision in Mongoose for this name. Removing the 'domain' field solve the issue.

**Comment by vkarpov15** [comment]
Hi @ablankenship10, yep, that's what #1351 was about. In 3.8 mongoose documents inherit from event emitters, so they have a `domain` field in some versions of NodeJS. In 4.x, mongoose documents no longer inherit from EventEmitter, and so don't have this problem.
