### ISSUE TITLE
Error when trying to clone model

### ISSUE THREAD

**Issue by jeremylevy** [Automattic/mongoose#2909]
Hi,

Just updated from 3.8 to 4.0.2 and got this error when trying to clone a model with [clone](https://www.npmjs.com/package/clone) package   :

```
TypeError: Cannot set property '__v' of undefined
    at StateMachine._changeState (/Users/jeremy/Documents/MongooseTest/node_modules/mongoose/lib/statemachine.js:77:32)
    at StateMachine.ctor.(anonymous function) [as modify] (/Users/jeremy/Documents/MongooseTest/node_modules/mongoose/lib/statemachine.js:55:12)
    at model.Document.markModified (/Users/jeremy/Documents/MongooseTest/node_modules/mongoose/lib/document.js:809:24)
    at model.Document.$__set (/Users/jeremy/Documents/MongooseTest/node_modules/mongoose/lib/document.js:665:10)
    at model.Document.set (/Users/jeremy/Documents/MongooseTest/node_modules/mongoose/lib/document.js:603:10)
    at model.Object.defineProperty.set [as __v] (/Users/jeremy/Documents/MongooseTest/node_modules/mongoose/lib/document.js:1417:45)
    at _clone (/Users/jeremy/Documents/MongooseTest/node_modules/clone/clone.js:99:16)
    at clone (/Users/jeremy/Documents/MongooseTest/node_modules/clone/clone.js:105:10)
    at Object.<anonymous> (/Users/jeremy/Documents/MongooseTest/index.js:16:18)
    at Module._compile (module.js:456:26)
```
Reported (and closed) previously (as [#2802](https://github.com/Automattic/mongoose/issues/2802)).

The code that may trigger the error:

```javascript
var mongoose = require('mongoose');
var clone = require('clone');

mongoose.connect('mongodb://localhost/mongooseTest');

var Schema = mongoose.Schema;

var userSchema = new Schema({
  firstName: String
});

var User = mongoose.model('User', userSchema);

var user = new User({ firstName: 'Joe' });

var clonedUser = clone(user);
```
Not sure, however, if you want to fix a bug that depends on an external module.

**Comment by vkarpov15** [comment]
This is a slightly different issue than #2802. Will investigate more closely.

**Comment by vkarpov15** [comment]
Bug with clone, see pvorb/node-clone#47
