### ISSUE TITLE
toJSON gets subdocument ret, not actual document

### ISSUE THREAD

**Issue by sabrehagen** [Automattic/mongoose#2910]
Hi,

I've been trying to trace this issue with node inspector for a full day, but have had no luck, so I'm posting the issue here.

Firstly, the issue i'm encountering is that when the schema.options.toJSON.transform function gets called, the ret it is supplied with is a sub document of the populated document, not the full/parent document as expected. This only happens when I populate the post property of the schema. No other populated subdocument is supplied to the transform function like post is.

Here is my schema:
```
var notificationSchema = Schema({
    type           : { type : String,   default : ''             },
    owner          : { type : ObjectId, ref     : 'User'         },
    user           : { type : ObjectId, ref     : 'User'         },
    project        : { type : ObjectId, ref     : 'Project'      },
    organisation   : { type : ObjectId, ref     : 'Organisation' },
    field          : { type : ObjectId, ref     : 'Field'        },
    thread         : { type : ObjectId, ref     : 'Thread'       },
    post           : { type : ObjectId, ref     : 'Post'         },
    timestamp      : { type : Date,     default : Date.now       },
    read           : { type : Boolean,  default : false          }
}, {
    strict         : true
});
```

Here is my notification lookup:
```
app.models.notification
.find(data.query)
.populate('user', 'name profile.firstname profile.lastname profile.picture profile.username')
.populate('post', 'body')
.populate('field', 'name stub logo.url picture')
.populate('thread', 'title stub')
.populate('project', 'name picture projectname')
.populate('organisation', 'name stub logo.url picture')
.exec(function(err, notifications) {
    // by design of my test, only one notification is returned
    console.log(notifications[0]);
	res.json(notifications);
});
```

Here is the stripped down transform function:
```
notificationSchema.options.toJSON.transform = function (doc, ret, options) {
    console.log(ret);
}
```

Here is the output of `console.log(notifications[0])` from the model lookup:
```
{
  _id: 553a21508dd23a3c27e8ceb4,
  owner: 54bdd517ec1e7dc41022a05f,
  user:
   { _id: 5498e258a7fbbfcc12c3fa15,
     accounts: { local: [Object] },
     profile:
      { username: 'jacksondelahunt',
        firstname: 'Jackson',
        lastname: 'Delahunt',
        picture: '/uploads/8565e053-d1ef-40a4-97ca-5841b79a3d17.jpg',
        socialLinks: {},
        profileDetails: {},
        banner: {} } },
  post:
   { _id: 5524ef2620e0a2047223bf38,
     body: '<p>Here's my post</p>' },
  thread:
   { _id: 5524c45d2b6a6996231c66d9,
     stub: 'space-station-telemetry-app',
     banner: {},
     title: 'Space Station Telemetry App' },
  __v: 0,
  read: true,
  timestamp: Fri Apr 24 2015 20:56:16 GMT+1000 (AUS Eastern Standard Time),
  type: 'new-project-mention'
}
```

Here is the output of `console.log(ret)` in the transform function:
```
{
  _id: 5524ef2620e0a2047223bf38,
  body: <p>Here's my post</p>
  id: '5524ef2620e0a2047223bf38'
}
```

If I comment out the post populate line in the model lookup so that the post is left unpopulated, the output of `console.log(ret)` is as follows, as expected:

```
{
  _id: 553a21508dd23a3c27e8ceb4,
  owner: 54bdd517ec1e7dc41022a05f,
  user:
   { _id: 5498e258a7fbbfcc12c3fa15,
     profile:
      { username: 'jacksondelahunt',
        firstname: 'Jackson',
        lastname: 'Delahunt',
        picture: '/uploads/8565e053-d1ef-40a4-97ca-5841b79a3d17.jpg',
        socialLinks: {},
        profileDetails: {},
        banner: {},
        name: 'Jackson Delahunt' } },
  post: 5524ef2620e0a2047223bf38,
  thread:
   { _id: 5524c45d2b6a6996231c66d9,
     stub: 'space-station-telemetry-app',
     title: 'Space Station Telemetry App',
     id: '5524c45d2b6a6996231c66d9' },
  __v: 0,
  read: true,
  timestamp: Fri Apr 24 2015 20:56:16 GMT+1000 (AUS Eastern Standard Time),
  type: 'new-project-mention',
  id: '553a21508dd23a3c27e8ceb4'
}
```

Here is the post schema so you can see that there is no funny business going on there:

```
var postSchema = Schema({
    body      :  { type : String,   default : ''         },
    parent    :  { type : ObjectId, ref     : 'Post'     },

    thread    :  { type : ObjectId, ref     : 'Thread'   },
    owner     :  { type : ObjectId, ref     : 'User'     },
    accepted  :  { type : Boolean,  default : false      },
    timestamp :  { type : Date,     default : Date.now   },
    edited    :  { type : Date,     default : ''         },
    votes     :  { type : Number,   default : 0          },
    flagged   :  { type : Boolean,  default : false      },
    deleted   :  { type : Boolean,  default : false      }
}, {
    strict    : true
});
```

How or why this is happening, I don't know, but I'm reporting it here as a bug as it reproducible and incorrect functionality. Sorry I can't provide you a plunker, but the system has a lot of dependencies to produce this data. Please let me know if there is anything else I can provide to make this clearer to trace.

**Comment by vkarpov15** [comment]
Thanks for the detailed report. Can you let me know what version of mongoose you're using so I can categorize this issue properly?

**Comment by sabrehagen** [comment]
This has been reproduced using 4.0.2 and 3.8.0.

**Comment by vkarpov15** [comment]
Confirmed bug because of how `toJSON()` passes options. As a workaround, set the transformation on `toObject()`:

```javascript
notificationSchema.options.toObject.transform = function (doc, ret, options) {
    console.log(ret);
}
```

and then do `res.json(_.map(notifications, function(n) { return n.toObject(); }));`

**Comment by sabrehagen** [comment]
Thanks Val, your workaround works for now. I checked out the branch you're fixing the bug in and it hasn't fixed the problem. However, what has changed is that I get a different sub-document passed into the toJSON function, not post like before.

**Comment by vkarpov15** [comment]
Hmm which sub-document? As far as I can tell, it should be working now, my standalone script for repro-ing this issue works fine on that branch.

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh2910');

var p = mongoose.Schema({
  c: { type: mongoose.Schema.Types.ObjectId, ref: 'gh-2910-1' }
});

p.options.toJSON = {
  transform: function(doc, ret, options) {
    console.log('--> ' + require('util').inspect(ret));
    return ret;
  }
};

var cSchema = mongoose.Schema({
  name: String
});

var C = mongoose.model('gh-2910-1', cSchema);
var P = mongoose.model('gh-2910-0', p);

C.create({ name: 'test' }, function(error, doc) {
  P.create({ c: doc._id }, function(error, p) {
    P.findOne({ _id: p._id }).populate('c').exec(function(error, p) {
      console.log(require('util').inspect(p.toJSON()));
    });
  });
});
```

Can you run the above script and make sure it works for you? Also, can you do me a favor and print out a stack trace in your transform function?

```javascript
notificationSchema.options.toJSON.transform = function (doc, ret, options) {
    console.log(new Error().stack);
    console.log(ret);
}
```

**Comment by sabrehagen** [comment]
Your code works perfectly for me. I'm now getting the parent toJSON transformed called one time per subdocument. Here's my lookup function:

```
app.models.notification
.find(data.query)
.populate('user', 'name profile.firstname profile.lastname profile.picture profile.username')
.populate('project', 'name picture projectname')
.populate('organisation', 'name stub logo.url picture')
.populate('thread', 'title stub')
.populate('field', 'name stub logo.url picture')
.populate('post', 'body')
.limit(options.size)
.skip(skip)
.sort(options.order === 'asc' ? options.sort : '-'+options.sort)
.exec(function(err, notifications) {
    console.log('notifications.length: ', notifications.length);
    console.log('notification: ', notifications[0]);
    console.log('------------------------------------------------');
    return res.json(notifications);
}));
});
```
Here's the toJSON transform:
```
notificationSchema.options.toJSON.transform = function (doc, ret, options) {
try {
    if (ret.type.match(/new-project-(thread|blog|question|general)/)) {
        // do something
    }
} catch (err) {
    console.log(err);
    console.log(require('util').inspect(ret));
    console.log(new Error().stack);
}
```
Here's the console output:

```
notifications.length:  1
notification:  { _id: 553dda3cd4f78a0c2365922a,
  type: 'new-field-blog',
  owner: 54bdd517ec1e7dc41022a05f,
  thread:
   { _id: 553dda3cd4f78a0c23659229,
     stub: 'a-blog-on-webs',
     banner: {},
     title: 'A blog on webs' },
  project: null,
  organisation: null,
  field:
   { _id: 5521fbe89fbbb77c26244c25,
     banner: {},
     logo: { url: '' },
     stub: 'web-development',
     name: 'Web Development' },
  __v: 0,
  read: true,
  timestamp: Mon Apr 27 2015 16:42:04 GMT+1000 (AUS Eastern Standard Time) }
------------------------------------------------
[TypeError: Cannot read property 'match' of undefined]
{ _id: 553dda3cd4f78a0c23659229,
  stub: 'a-blog-on-webs',
  title: 'A blog on webs',
  id: '553dda3cd4f78a0c23659229' }
Error
    at notificationSchema.options.toJSON.transform (C:\repositories\stemn\server\models\notification.js:228:21)
    at model.Document.$toObject (C:\repositories\stemn\node_modules\mongoose\lib\document.js:1425:19)
    at model.Document.toJSON (C:\repositories\stemn\node_modules\mongoose\lib\document.js:1685:15)
    at clone (C:\repositories\stemn\node_modules\mongoose\lib\utils.js:224:18)
    at cloneObject (C:\repositories\stemn\node_modules\mongoose\lib\utils.js:288:13)
    at clone (C:\repositories\stemn\node_modules\mongoose\lib\utils.js:233:16)
    at model.Document.$toObject (C:\repositories\stemn\node_modules\mongoose\lib\document.js:1393:13)
    at model.Document.toJSON (C:\repositories\stemn\node_modules\mongoose\lib\document.js:1685:15)
    at Object.stringify (native)
    at ServerResponse.json (C:\repositories\stemn\node_modules\express\lib\response.js:233:19)
    at C:\repositories\stemn\server\routes\api\v1\notification.js:13:17
    at tryCatcher (C:\repositories\stemn\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (C:\repositories\stemn\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (C:\repositories\stemn\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (C:\repositories\stemn\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (C:\repositories\stemn\node_modules\bluebird\js\main\async.js:175:16)
[TypeError: Cannot read property 'match' of undefined]
{ _id: 5521fbe89fbbb77c26244c25,
  logo: { url: '' },
  stub: 'web-development',
  name: 'Web Development',
  picture: '',
  id: '5521fbe89fbbb77c26244c25' }
Error
    at notificationSchema.options.toJSON.transform (C:\repositories\stemn\server\models\notification.js:228:21)
    at model.Document.$toObject (C:\repositories\stemn\node_modules\mongoose\lib\document.js:1425:19)
    at model.Document.toJSON (C:\repositories\stemn\node_modules\mongoose\lib\document.js:1685:15)
    at clone (C:\repositories\stemn\node_modules\mongoose\lib\utils.js:224:18)
    at cloneObject (C:\repositories\stemn\node_modules\mongoose\lib\utils.js:288:13)
    at clone (C:\repositories\stemn\node_modules\mongoose\lib\utils.js:233:16)
    at model.Document.$toObject (C:\repositories\stemn\node_modules\mongoose\lib\document.js:1393:13)
    at model.Document.toJSON (C:\repositories\stemn\node_modules\mongoose\lib\document.js:1685:15)
    at Object.stringify (native)
    at ServerResponse.json (C:\repositories\stemn\node_modules\express\lib\response.js:233:19)
    at C:\repositories\stemn\server\routes\api\v1\notification.js:13:17
    at tryCatcher (C:\repositories\stemn\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (C:\repositories\stemn\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (C:\repositories\stemn\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (C:\repositories\stemn\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (C:\repositories\stemn\node_modules\bluebird\js\main\async.js:175:16)
```

**Comment by sabrehagen** [comment]
Also, it seems that the changes in this branch introduced a new issue where virtuals of the populated subdocument are not produced by the toJSON transform for the subdocument.

**Comment by vkarpov15** [comment]
Glad it's working. Re https://github.com/Automattic/mongoose/issues/2910#issuecomment-98330124, are you actually specifying `virtuals: true` in the schema toJSON options? By default, toJSON() won't include virtuals.

**Comment by sabrehagen** [comment]
Yep, virtuals are explicitly specified.

**Comment by whitecolor** [comment]
Waiting a fix published on NPM.

**Comment by vkarpov15** [comment]
@sabrehagen you're going to have to show me how you're getting that virtuals aren't being passed to the `toJSON` transform. On the gh-2910 branch, the below script

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh2910');

var p = mongoose.Schema({
  c: { type: mongoose.Schema.Types.ObjectId, ref: 'gh-2910-1' }
});

p.virtual('test').get(function() {
  return 5;
});

p.options.toJSON = {
  transform: function(doc, ret, options) {
    console.log('--> ' + require('util').inspect(ret));
    return ret;
  },
  virtuals: true
};

var cSchema = mongoose.Schema({
  name: String
});

var C = mongoose.model('gh-2910-1', cSchema);
var P = mongoose.model('gh-2910-0', p);

C.create({ name: 'test' }, function(error, doc) {
  P.create({ c: doc._id }, function(error, p) {
    P.findOne({ _id: p._id }).populate('c').exec(function(error, p) {
      console.log(require('util').inspect(p.toJSON()));
    });
  });
})
```

Gives me the correct output

```
Mongoose: gh-2910-1.insert({ name: 'test', _id: ObjectId("554937859c382eb663221852"), __v: 0 }) {}  
Mongoose: gh-2910-0.insert({ c: ObjectId("554937859c382eb663221852"), _id: ObjectId("554937859c382eb663221853"), __v: 0 }) {}  
Mongoose: gh-2910-0.findOne({ _id: ObjectId("554937859c382eb663221853") }) { fields: undefined }  
Mongoose: gh-2910-1.find({ _id: { '$in': [ ObjectId("554937859c382eb663221852") ] } }) { fields: undefined }  
--> { _id: 554937859c382eb663221853,
  c: { _id: 554937859c382eb663221852, name: 'test', __v: 0 },
  __v: 0,
  test: 5,
  id: '554937859c382eb663221853' }
{ _id: 554937859c382eb663221853,
  c: { _id: 554937859c382eb663221852, name: 'test', __v: 0 },
  __v: 0,
  test: 5,
  id: '554937859c382eb663221853' }
```

**Comment by mbernath** [comment]
Hi there,

maybe this fix causes a new error...

I upgraded from 3.8.27 to 2.8.28 and when JSON.stringifying a document this leads to an error that reproducibly does not occur with 3.8.27.

The relevant stack trace is:

    TypeError: Object #<Object> has no method 'get'
            at Object.nested.toObject (.../node_modules/mongoose/lib/document.js:1214:27)
            at Object.stringify (native)

The document that was JSON.stringified was populated and the populated document contains a nested object (see following example). When I debugged, it seems to me that the error occurs with the nested document.

    // A "normal" Mongoose document
    {
      ...
      profiles: [{      // <-- These documents were populated
        address: {    // <-- Error occurs with this nested object
          street: "...",
          town: "...",
          zip: "...",
          ...
        }
      }
      ]
    }

I haven't found the time yet to write a simplified piece of code to reproduce this error, but will try within the next days. For now I reverted to 3.8.27.

Any thoughts?

**Comment by vkarpov15** [comment]
Hmm strange, does the same thing happen when you call `toObject()`?

Also, can you please open up a new issue? Much easier to track that way.

**Comment by mbernath** [comment]
@vkarpov15 Done. Created #3018. Will try to answer your question and come up with code within the next days.

**Comment by mos-flash** [comment]
I ams being the same issue on latest release (4.4.13).  Namely - if I specify a custom transform function for toObject, the transform function  is passed the populated child doc - not the document being transformed. So I would classify this bug as being unresolved.

**Comment by vkarpov15** [comment]
@mos-flash can you provide some sample code please?

**Comment by mienaikoe** [comment]
I'm also seeing this in 2019

Here's some code, hope it helps:

```javascript
const  BoatSchema = new Schema({
  _id: ObjectId,
  name: { type: String, required: true, trim: true },
},{
  toJSON: {
    transform: (doc, ret, options) => {
      console.log("\n\n\nBOAT=========")
      console.log(doc._id);
    }
  }
});

const Boat = mongoose.model('Boat', BoatSchema);

...

var EventSchema = new Schema({
  _id: ObjectId,
  name: { type: String, required: true, trim: true },
  boats: [
    { type: ObjectId, ref: 'Boat' },
  ],
}, { 
  minimize: false,
  toJSON: {
    transform: (doc, ret, options) => {
      console.log("\n\n\n============= Event")
      console.log(doc._id);
    }
  }
});

const Event = mongoose.Model( 'Event', EventSchema );

...

const boat = await Boat.create({
  name: "A Boat"
});

const event = await Event.create({
  name: "An Event",
  boats: [ boat ]
});

console.log( event.toJSON() );
```

I'm seeing a bunch of logging for the boat subdocuments, and then logging for the event document several times with the boat _id.
