### ISSUE TITLE
Invalid mongodb uri?

### ISSUE THREAD

**Issue by TheEmpty** [Automattic/mongoose#2912]
Running on `mongoose@4.0.1` and I'm getting that my mongo URI is invalid, but it seems formatted fine, is this a bad error message? For reference, trying to get dokku and the `dokku-mongodb-plugin` to play in production.

```
       events.js:85
             throw er; // Unhandled 'error' event
                   ^
       Error: Invalid mongodb uri. Must begin with "mongodb://"
         Received: "mongodb://nowall:passwordRedacted@172.17.0.5:27017/nowall-production"
           at muri (/src/node_modules/mongoose/node_modules/muri/lib/index.js:28:11)
           at NativeConnection.Connection.open (/src/node_modules/mongoose/lib/connection.js:205:16)
           at Mongoose.connect (/src/node_modules/mongoose/lib/index.js:224:15)
           at module.exports (/src/src/middleware/mongoose.js:3:12)
           at Object.<anonymous> (/src/src/app.js:15:51)
           at Module._compile (module.js:460:26)
           at Object.Module._extensions..js (module.js:478:10)
           at Module.load (module.js:355:32)
           at Function.Module._load (module.js:310:12)
           at Function.Module.runMain (module.js:501:10)
```

**Comment by TheEmpty** [comment]
The relevant code. If I remove the `||` it works fine.

```
var mongoose = require('mongoose');
var uri = process.env.MONGO_URI || options.urls[app.env];
mongoose.connect(uri.toString());
```

**Comment by TheEmpty** [comment]
The issue is that `dokku-mongodb-plugin` is wrapping it in quotes. So the quotes after "Received" are part of the string. So issue is with those guys.

**Comment by git-santosh** [comment]
getting an error when deploying application on heroku 

```
State changed from crashed to starting
2017-10-09T17:56:26.560038+00:00 heroku[web.1]: Starting process with command `node app.js`
2017-10-09T17:56:29.374316+00:00 heroku[web.1]: Process exited with status 1
2017-10-09T17:56:29.383145+00:00 heroku[web.1]: State changed from starting to crashed
2017-10-09T17:56:29.316216+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-10-09T17:56:29.316216+00:00 app[web.1]:       ^
2017-10-09T17:56:29.316201+00:00 app[web.1]: events.js:182
2017-10-09T17:56:29.316217+00:00 app[web.1]:
2017-10-09T17:56:29.316217+00:00 app[web.1]: Error: Invalid mongodb uri. Must begin with "mongodb://"
2017-10-09T17:56:29.316221+00:00 app[web.1]:     at Module._compile (module.js:569:30)
2017-10-09T17:56:29.316219+00:00 app[web.1]:     at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:714:18)
2017-10-09T17:56:29.316220+00:00 app[web.1]:     at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:262:17)
2017-10-09T17:56:29.316219+00:00 app[web.1]:     at muri (/app/node_modules/muri/lib/index.js:28:11)
2017-10-09T17:56:29.316220+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:40:10)
2017-10-09T17:56:29.316222+00:00 app[web.1]:     at Function.Module._load (module.js:458:3)
2017-10-09T17:56:29.316222+00:00 app[web.1]:     at tryModuleLoad (module.js:466:12)
2017-10-09T17:56:29.316223+00:00 app[web.1]:     at Function.Module.runMain (module.js:605:10)
2017-10-09T17:56:29.316221+00:00 app[web.1]:     at Module.load (module.js:503:32)
2017-10-09T17:56:29.316221+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:580:10)
2017-10-09T17:56:29.316223+00:00 app[web.1]:     at bootstrap_node.js:575:3
2017-10-09T17:56:29.316223+00:00 app[web.1]:     at startup (bootstrap_node.js:158:16)
2017-10-09T17:56:29.316218+00:00 app[web.1]:   Received: 'mongodb://nodechat:nodechat@ds013405.mlab.com:13405/nodechat'
```

What does that mean ?

This is how I set variables into my application
.env --> 
`mongoURL = mongodb://nodechat:nodechat@ds013405.mlab.com:13405/nodechat`

app.js --> 

```mongoose.connect(process.env.mongoURL, { useMongoClient: true }).then(() => console.log('connected to DB')).catch(err => console.log(err));```

I am using `"mongoose": "^4.11.13",`
`Node version : 8.2.1`
`NPM : 5.4.2`

**Comment by vkarpov15** [comment]
Can you print out `process.env.mongoURL` before calling `mongoose.connect()`?

**Comment by git-santosh** [comment]
Above problem was solved by converting uri to string 
```
mongoose.connect(uri.toString(), { useMongoClient: true }).then(() => console.log('connected to DB'))
.catch(err => console.log(err));
```
