### ISSUE TITLE
Problem with increasing timeout

### ISSUE THREAD

**Issue by MitchK** [Automattic/mongoose#2921]
I would like to increase the connection timeout for mongoose, since my MongoDB takes some time to boot up. 

```
// I have also tried
// var mongooseOptions = { replset: { socketOptions: { connectTimeoutMS : config.mongodb.dbTimeout }}};
var mongooseOptions = { server: { socketOptions: { connectTimeoutMS: config.mongodb.dbTimeout }}};
logger.info('Establishing connection to MongoDB... (Timeout is ' + config.mongodb.dbTimeout + ')');
mongoose.connect(config.mongodb.uri, mongooseOptions, function (error) {
    if (error) {
        logger.error('Connection to MongoDB failed: ' + error);
        return;
    }
    ...
```

Unfortunately, the timeout does not apply. It fails immediately.
```
2015-04-24T10:43:10.156Z - info: Establishing connection to MongoDB... (Timeout is 300000)
2015-04-24T10:43:10.275Z - error: Connection to MongoDB failed: MongoError: connect ECONNREFUSED
```

For testing purpose, MongoDB is not running at all on the test machine.

**Comment by vkarpov15** [comment]
Which version of mongoose?

**Comment by MitchK** [comment]
I'm sorry, I forgot to mention the version. It's ```4.0.1```

**Comment by vkarpov15** [comment]
As a workaround, you can set the connectTimeoutMS in your uri with ?connectTimeoutMS=180000 at the end of the uri

**Comment by vkarpov15** [comment]
So your syntax is actually correct, but the ECONNREFUSED is a feature of how linux / osx work - if there's nothing listening on that port, the os will actively refuse the connection. For instance, the below script:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

var mongooseOptions = { server: { socketOptions: { connectTimeoutMS: 10 }}};

mongoose.connect('mongodb://bad.domain:27017/test', mongooseOptions);
```

Will timeout, at least on my machine.

```
MongoError: connection 0 to bad.domain:27017 timed out
    at Function.MongoError.create (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:128:20)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:104:17)
    at Socket._onTimeout (net.js:348:8)
    at _makeTimerTimeout (timers.js:467:11)
    at Timer.unrefTimeout (timers.js:531:5)
```

But if you up the timeout to say 180000 you get a DNS failure rather than a timeout

```
Error: getaddrinfo ENOTFOUND bad.domain
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```
