### ISSUE TITLE
Error using References with --use_strict

### ISSUE THREAD

**Issue by AJCStriker** [Automattic/mongoose#2934]
When using io.js in strict mode, I get the following error when attempting to create a Model with a reference.

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at new MongooseError (/node_modules/mongoose/lib/error.js:11:69)
    at MongooseError.CastError (/node_modules/mongoose/lib/error/cast.js:17:17)
    at model.Document.set (/node_modules/mongoose/lib/document.js:598:7)
    at model.Document.set (/node_modules/mongoose/lib/document.js:492:18)
    at model.Document (/node_modules/mongoose/lib/document.js:62:10)
    at model.Model (/node_modules/mongoose/lib/model.js:45:12)
    at new model (/node_modules/mongoose/lib/model.js:2726:11)
    at Object.createNew (EventController.js:102:44)
    at GeneratorFunctionPrototype.next (native)
    at onFulfilled (/node_modules/koa/node_modules/co/index.js:64:19)
    at process._tickCallback (node.js:353:9)

Any guidance or help appreciated. I can't find the call that would cause this at the noted location, so I would be interested to see what community insight can shine on this.

**Comment by AJCStriker** [comment]
The error itself was actually caused by the ObjectID being read incorrectly in some of our code. It appears to trigger the validation logic inside the ref: handling code.

Interesting that the error came through as a TypeError though.

**Comment by vkarpov15** [comment]
Can you show me some actual code that repros this issue? I'm not sure I understand what you're trying to do.
