### ISSUE TITLE
use aggregate error when the data big than 100,000 documents

### ISSUE THREAD

**Issue by link5209** [Automattic/mongoose#2964]
/home/link/miner/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error
    at Object.<anonymous> (/home/link/miner/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:42:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/link/miner/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/index.js:2:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
exception in nodemon killing node
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at Pipe.onread (net.js:559:26)

**Comment by vkarpov15** [comment]
Are you using an aggregation cursor? You might be running over the 16mb aggregation size limit or the sort size limit with that many docs. What does your aggregate() call look like?

**Comment by link5209** [comment]
yes, my I have  over the 16mb aggregation size limit, but I added {allowDiskuse: true} ,but it's not work

**Comment by link5209** [comment]
var aggregation = Point.aggregate([
        {$match: {
            createdBy: {$gte: req.body.startDate,$lt: req.body.endDate},
            user: {$nin: cache.oldUsers(req.body.startDate)}
        }},
        {$group: {
            _id: '$user',
            events: {$addToSet: {$cond: [  // exlude clickSignup event not from home page
                {$and: [
                    {$eq: ['$eventKey', 'clickSignup']},
                    {$ne: ['eventValue.fromUrl', '/home']}]
                },
                null, '$eventKey']}}}}
                ]);

    aggregation.options = { allowDiskUse: true };
    aggregation.exec(function(err, result) {
        if (err) {
            throw err; // how to catch 
            return res.status(500).json({error: err});
        }

        console.log(result.length) // > enterHome count why???

        result.forEach(function(item) {
            
        })

**Comment by vkarpov15** [comment]
So `allowDiskUse` is not sufficient - that will just let you use sort when your data is large. I'd recommend you use the [aggregation cursor](http://mongoosejs.com/docs/api.html#aggregate_Aggregate-cursor) form if your data will be > 16mb.

**Comment by link5209** [comment]
thank you so much, aggregation cursor  can be work
