### ISSUE TITLE
mongoose.collection.initializeUnorderedBulkOp crashed when upgraded to 4.0

### ISSUE THREAD

**Issue by sirhoe** [Automattic/mongoose#2982]
we had a running environment which crashed when we upgrade the package from 3.8.x to 4.0.2. The code looks something like this.

    var bulk = Model.collection.initializeUnorderedBulkOp({useLegacyOps: true});
    bulk.find({'merchant': {$ne: null}, 'merchant._id': merchant._id})
        .update({$set: {'merchant': merchant}})
        .execute(function (err, results) {
            ...
        });

**Comment by vkarpov15** [comment]
`initializeUnorderedBulkOp()` is a bit of a problem right now because it's a synchronous operation and mongoose specifically wraps underlying collection operations for buffering.

Can you show me what the crash looks like?

**Comment by sirhoe** [comment]
it looks like this, not sure if it helps.

    ..../node_modules/newrelic/lib/transaction/tracer/index.js:162
      throw err
            ^
    TypeError: Object [object Object] has no method 'execute'
    at merchantUpdatedEventHandler (..../helpers/db/location.js:191:10)
    at emit (events.js:117:20)
    at Object.merchant.update (..../helpers/utilities/events.js:10:19)
    at model.exports.MerchantSchema (..../db/main/schema/merchant.js:14:21)
    at model.<anonymous> (..../node_modules/mongoose/lib/schema.js:674:10)
    at _next (..../node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (..../node_modules/mongoose/node_modules/hooks-fixed/hooks.js:171:15)
    at model.exports.MerchantSchema (..../db/main/schema/merchant.js:10:5)
    at _next (..../node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at EventEmitter.fnWrapper (..../node_modules/mongoose/node_modules/hooks-fixed/hooks.js:171:15)
    at EventEmitter.<anonymous> (..../node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
    at EventEmitter.emit (events.js:92:17)
    at Promise.safeEmit (..../node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
    at Promise.fulfill (..../node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
    at complete (..../node_modules/mongoose/lib/document.js:1049:15)
    at ..../node_modules/mongoose/lib/document.js:1017:27

Process finished with exit code 8

**Comment by alejandromagnorsky** [comment]
We discovered that it works if we change the code to:

    var bulk = Model.collection.initializeUnorderedBulkOp({useLegacyOps: true});
    bulk.find({'merchant': {$ne: null}, 'merchant._id': merchant._id})
        .update({$set: {'merchant': merchant}});
    bulk.execute(function (err, results) {
            ...
        });
    
So basically, no chaining.

**Comment by vkarpov15** [comment]
@alejandromagnorsky is right. This is due to the [quirks of the old-style bulk API](http://mongodb.github.io/node-mongodb-native/2.0/api/UnorderedBulkOperation.html) - `bulk.find()` doesn't actually return the original bulk object, it returns [a different type called FindOperatorsUnordered](http://mongodb.github.io/node-mongodb-native/2.0/api/FindOperatorsUnordered.html) that enables you to build up the bulk op. v1.4 of the driver didn't do this correctly, but v2.0 does.

Also, the fluent-style bulk API (`initializeUnorderedBulkOp`, etc.) is [currently considered deprecated, see "Q: Didn't we just build a bulk API?" in this page](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#q--a). It will remain in the mongodb driver for the foreseeable future but I wouldn't recommend using it :)
