### ISSUE TITLE
Errors with browserify of lib/browser.js

### ISSUE THREAD

**Issue by dmeehan1968** [Automattic/mongoose#3042]
If I try to do a straightforward `browserify` of the Mongoose browser module using:

```
./node_modules/.bin/browserify -o bundle.js node_modules/mongoose/lib/browser.js
```

I get:

```
Error: Cannot find module '../build/Release/kerberos' from '/Users/dmeehan/Documents/Dropbox/Projects/Wavetrend/Cloud-Service/angular/dashboard/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/lib'
    at /Users/dmeehan/Documents/Dropbox/Projects/Wavetrend/Cloud-Service/angular/dashboard/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/dmeehan/Documents/Dropbox/Projects/Wavetrend/Cloud-Service/angular/dashboard/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/dmeehan/Documents/Dropbox/Projects/Wavetrend/Cloud-Service/angular/dashboard/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/dmeehan/Documents/Dropbox/Projects/Wavetrend/Cloud-Service/angular/dashboard/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

I looked into how its done within the `Makefile`, and tried the following:

```
./node_modules/.bin/browserify -u "**/mongodb/**" -o bundle.js node_modules/mongoose/lib/browser.js 
```

This builds cleanly, but when I try to load the module via a `<script>` tag, I get:

```
Uncaught Error: Cannot find module 'mongodb's 
@ bundle.js:1(anonymous function) 
@ bundle.js:1(anonymous function) 
@ bundle.js:1181646../document 
@ bundle.js:12600s 
@ bundle.js:1(anonymous function) 
@ bundle.js:1(anonymous function) 
@ bundle.js:589327../schema/index
@ bundle.js:6915s 
@ bundle.js:1(anonymous function) 
@ bundle.js:1(anonymous function) 
@ bundle.js:1846170../document_provider.js 
@ bundle.js:18537s @ bundle.js:1e 
@ bundle.js:1(anonymous function) @ bundle.js:1
```

I downloaded the release ZIP from Github for 4.0.2, and stored it locally, and it works fine.

Documentation for the correct process of browserify-ing mongoose, either standalone or as part of other sources would be most helpful.

**Comment by vkarpov15** [comment]
Thanks for pointing this out, there were some quirks introduced in the browserify build  in recent versions.  As a workaround, use browserify's `-u` flag to ignore the mongodb module:

```
-u "**/mongodb/**"
```

**Comment by dmeehan1968** [comment]
As I said, I tried with `-u "**/mongodb/**"`, the `browseify`completed successfully, but when I tried to load the module via a script tag, it complain about missing `mongodb`.

**Comment by vkarpov15** [comment]
```
$ cat gh-3042.js 
var mongoose = require('mongoose');
$ ./node_modules/.bin/browserify gh-3042.js > test.js
$ head test.js 
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var mongoose = require('mongoose');

},{"mongoose":11}],2:[function(require,module,exports){
/*!
 * The buffer module from node.js, for the browser.
 *
 * @author   Feross Aboukhadijeh <feross@feross.org> <http://feross.org>
 * @license  MIT
 */
```

looks like 4.0.5 works. Re-open if this is still an issue.
