### ISSUE TITLE
Breaking change 3.8->4.0: Without populate arrays of object ids with refs don't get loaded at all

### ISSUE THREAD

**Issue by gunters63** [Automattic/mongoose#3050]
I am currently trying to convert our backend from MongoDB 2.6/Mongoose 3.8 to MongoDB 3.0/Mongoose 4.0.

We have some failing tests, one cause being:

We have a schema referencing another collection:

        jobs: [{type: Schema.Types.ObjectId, ref: 'Job'}],

Sometimes we only need the array with the object ids from the referenced collection (i.e. just the jobs array with ObjectIds), so we don't populate on 'jobs' when querying. One use case is when we just want to append/remove some jobs.

But with Mongoose 4 it seems that the array with the ids is not retrieved anymore, you explicitly have to populate it. This was not the case with Mongoose 3.8. Is this an intended change?

We could populate on jobs now everytime, selecting the id only But this still requires quite some changes, because we don't have a simple array of object ids anymore, but an array of objects each containing an id (we could use populated() for this is think).

**Comment by gunters63** [comment]
In an other test, we get a document (JobSearch) containing two jobs refs with findById and without populating and save it again after modifying some other properties. This fails with a strange error:

    JobSearch validation failed
    ValidationError: Cast to non_object_property_load failed for value "556efe3eb7a5cd842b608916,556efe3eb7a5cd842b608917" at path "jobs"
        at model.Document.invalidate (C:\proj\_SVN\Dispatcher\NodeExpressServer\node_modules\mongoose\lib\document.js:1156:32)
        at init (C:\proj\_SVN\Dispatcher\NodeExpressServer\node_modules\mongoose\lib\document.js:317:18)
        at model.Document.init (C:\proj\_SVN\Dispatcher\NodeExpressServer\node_modules\mongoose\lib\document.js:273:3)
        at completeOne (C:\proj\_SVN\Dispatcher\NodeExpressServer\node_modules\mongoose\lib\query.js:1469:10)
        at Object.<anonymous> (C:\proj\_SVN\Dispatcher\NodeExpressServer\node_modules\mongoose\lib\query.js:1204:13)
        at Object._onImmediate (C:\proj\_SVN\Dispatcher\NodeExpressServer\node_modules\mongoose\node_modules\mquery\lib\utils.js:137:16)

This also worked with Mongoose 3.8 and MongoDB 2.6.

**Comment by Jeff-Lewis** [comment]
@gunters63 Does your issue sound like this one? https://github.com/Automattic/mongoose/issues/3020

**Comment by gunters63** [comment]
Absolutely, thank you!

**Comment by vkarpov15** [comment]
Sorry about that, working on fixing it :)
