### ISSUE TITLE
BUG: $all throw CastError, but was passed when using raw mongo shell query

### ISSUE THREAD

**Issue by lyfeyaj** [Automattic/mongoose#3163]
Error throw out when using `$all` query operator with `$elemMatch` on an array field `acls`

ModelSchema

``` javascripts
mongoose.model('Role', {
  name: { type: 'String', required: true },
  description: { type: 'String' },
  acls: [{ type: 'String' }]
});
```

Code:

```javascript
models.Role.findOne({
  acls: { 
    $all: [
      { "$elemMatch" : { $regex: /index/g } }
    ]
  }
}).then(console.log)
```

Stack Trace: 

``` bash
Unhandled rejection CastError: Cast to string failed for value "[object Object]" at path "acls"
at SchemaString.cast (/my-project/node_modules/mongoose/lib/schema/string.js:422:9)
at SchemaString.castForQuery (/my-project/node_modules/mongoose/lib/schema/string.js:472:17)
at /my-project/node_modules/mongoose/lib/schema/array.js:202:32
at Array.map (native)
at SchemaArray.castForQuery (/my-project/node_modules/mongoose/lib/schema/array.js:201:17)
at SchemaArray.cast$all (/my-project/node_modules/mongoose/lib/schema/array.js:323:15)
at SchemaArray.castForQuery (/my-project/node_modules/mongoose/lib/schema/array.js:191:19)
at module.exports (/my-project/node_modules/mongoose/lib/cast.js:196:39)
at Query.cast (/my-project/node_modules/mongoose/lib/query.js:2350:10)
at Query.findOne (/my-project/node_modules/mongoose/lib/query.js:1153:10)
at Query.exec (/my-project/node_modules/mongoose/lib/query.js:1984:17)
at /my-project/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2348:10
at tryCatcher (/my-project/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/util.js:24:31)
at Promise._resolveFromResolver (/my-project/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/promise.js:427:31)
at new Promise (/my-project/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/promise.js:53:37)
at Query.then (/my-project/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2347:17)
at repl:1:175
at REPLServer.defaultEval (repl.js:132:27)
at bound (domain.js:254:14)
at REPLServer.runBound [as eval] (domain.js:267:12)
at REPLServer.<anonymous> (repl.js:279:12)
at REPLServer.emit (events.js:107:17)
```

But it was passed when using mongo shell directly.

``` javascripts
db.roles.find({ acls: { $all: [{ "$elemMatch" : { $regex: /index/g } }] } })
```

And I looked into source code, found that <https://github.com/Automattic/mongoose/blob/master/lib/schema/array.js#L309-L324> function `cast$all` will cast value by its type directly without checking whether there are nested `$elemMatch` condition

**Comment by lyfeyaj** [comment]
The example above are from the official document of Mongodb <http://docs.mongodb.org/manual/reference/operator/query/all/#use-all-with-elemmatch>

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate later.
