### ISSUE TITLE
MongoError: auth failed

### ISSUE THREAD

**Issue by gowthaman-i2i** [Automattic/mongoose#3196]
my code
```
var mongoose = require('mongoose');
var db =  'mongodb://abc:1234@localhost:27017/myDB'
mongoose.connect(db);
```
**mongoose version   ^4.0.8**
i get below error

```
/home/gowthaman/sampleProj/node_modules/connect-mongo/node_modules/mongodb/lib/mongo_client.js:428
              throw err
                    ^
MongoError: auth failed
    at Function.MongoError.create (/home/gowthaman/sampleProj/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/gowthaman/sampleProj/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:804:66
    at Callbacks.emit (/home/gowthaman/sampleProj/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/home/gowthaman/sampleProj/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:246:23)
    at Socket.<anonymous> (/home/gowthaman/sampleProj/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by vkarpov15** [comment]
Are your credentials correct and is the user `abc` defined on `myDB`? That is, can you go to the mongodb shell and do:

```
use myDB;
db.auth('abc', '1234');
```

**Comment by gowthaman-i2i** [comment]
yes my credentials correct
```
gowthaman@gowthaman:~$ mongo
MongoDB shell version: 2.6.10
connecting to: test
> use myDB
switched to db myDB
> db.auth("abc","1234");
1
> show users
{
	"_id" : "myDB.abc",
	"user" : "abc",
	"db" : "myDB",
	"roles" : [
		{
			"role" : "dbOwner",
			"db" : "myDB"
		}
	]
}
> 
```

**Comment by vkarpov15** [comment]
What's the mongodb server version?

**Comment by gowthaman-i2i** [comment]
mongodb server version  **v2.6.10**
```
gowthaman@gowthaman:~$ mongod --version
db version v2.6.10
2015-07-27T09:38:39.240+0530 git version: 5901dbfb49d16eaef6f2c2c50fba534d23ac7f6c
```

**Comment by gowthaman-i2i** [comment]
When I can expect this to get fixed.

**Comment by vkarpov15** [comment]
Actually, if you look at the stack trace, this error is in connect-mongo and has nothing to do with mongoose. I suspect this has something to do with the fact that older versions of connect-mongo do some really nasty hacks to re-use mongoose connections. I'd recommend you switch over to [connect-mongodb-session](https://github.com/mongodb-js/connect-mongodb-session), which is a drop-in replacement with fewer rough edges.
