### ISSUE TITLE
Error: Cannot find module './drivers'

### ISSUE THREAD

**Issue by PedroEsperanca** [Automattic/mongoose#3231]
on 4.x.x I get this error in the server:

```javascript
Error: Cannot find module './drivers'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/html/WTV.com/node_modules/mongoose/lib/schema.js:5:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
````

on 3.x.x I get:
````
Error: Cannot find module './mongodb'
````

this doesn't happen on the computer though

**Comment by PedroEsperanca** [comment]
Error: Cannot find module './lib/topologies/server' with 4.1.0

**Comment by vkarpov15** [comment]
The stack trace shows the crash is in pm2, which is [doing some weird monkey-patching of `require()`](https://github.com/keymetrics/pmx/blob/master/lib/transaction.js). This is extremely dangerous and we can't guarantee mongoose will work correctly, if at all, if you change the semantics of `require()`. Open up an issue with pm2.

**Comment by Jeff-Lewis** [comment]
@PedroEsperanca I just noticed in the very latest development version of pm2, [they added an option](https://github.com/Unitech/PM2/compare/development) to not use/load pmx. Maybe give that a shot.

**Comment by nawazdhandala** [comment]
Any updates on this. I'm still having this issue. Its strange, it doesnt happen on my local dev machine.

**Comment by vkarpov15** [comment]
Ask pm2. If `require()` is broken, mongoose won't work.
