### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by kobezzza** [Automattic/mongoose#3264]
Is it bug?

**Shema**

```js
var mongoose = require('mongoose');

var s = new mongoose.Schema({
  photos: {
    type: [{
      type: {
        uuid: {
          type: String,
          required: true
        },

        name: {
          type: String,
          required: true
        },

        url: {
          type: String,
          required: true
        }
      }
    }]
  }
});
```

**Example**

```js
{photos: [{
  uuid: 'foo',
  name: 'bar',
  url: 'bar'
}]}
```

**Stacktrace**

```
node_modules/mongoose/lib/schema/array.js:57
    this.caster = new caster(null, castOptions);
                  ^
TypeError: object is not a function
    at new SchemaArray (/Users/andrejkobec/Documents/dev/iConnCore/iconn-core/node_modules/mongoose/lib/schema/array.js:57:19)
    at Function.Schema.interpretAsType (/Users/andrejkobec/Documents/dev/iConnCore/iconn-core/node_modules/mongoose/lib/schema.js:506:12)
    at Schema.path (/Users/andrejkobec/Documents/dev/iConnCore/iconn-core/node_modules/mongoose/lib/schema.js:457:29)
    at Schema.add (/Users/andrejkobec/Documents/dev/iConnCore/iconn-core/node_modules/mongoose/lib/schema.js:352:12)
    at new Schema (/Users/andrejkobec/Documents/dev/iConnCore/iconn-core/node_modules/mongoose/lib/schema.js:91:10)
    at Object.<anonymous> (/Users/andrejkobec/Documents/dev/iConnCore/iconn-core/foo.js:3:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by trikadin** [comment]
+1

**Comment by vkarpov15** [comment]
Don't use `type` as a top-level key. 

```javascript
var mongoose = require('mongoose');

var s = new mongoose.Schema({
  photos: {
    kind: [{
      kind: {
        uuid: {
          type: String,
          required: true
        },

        name: {
          type: String,
          required: true
        },

        url: {
          type: String,
          required: true
        }
      }
    }]
  }
});
```
