### ISSUE TITLE
Unable to save documents

### ISSUE THREAD

**Issue by ceeser** [Automattic/mongoose#3276]
Issue seen in 4.1.3 and 4.1.2. Confirmed that it isn't a problem in 4.1.0.

When calling the save method on a new model, the following error is returned:

439770823366 - error:  TypeError: Cannot assign to read only property 'checkKeys' of true
    at Collection.insertMany (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/collection.js:427:23)
    at Collection.insert (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/collection.js:668:15)
    at NativeCollection.(anonymous function) [as insert] (/var/app/current/node_modules/mongoose/lib/drivers/node-mongodb-native/colle$    at /var/app/current/node_modules/mongoose/lib/model.js:116:24
    at new Promise.ES6 (/var/app/current/node_modules/mongoose/lib/promise.js:45:5)
    at model.$__handleSave (/var/app/current/node_modules/mongoose/lib/model.js:102:12)
    at model.Model.save (/var/app/current/node_modules/mongoose/lib/model.js:224:16)
    at model._done (/var/app/current/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:101:24)
    at _next (/var/app/current/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:64:28)
    at fnWrapper (/var/app/current/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at model.Object.defineProperty.value.fn (/var/app/current/node_modules/mongoose/lib/schema.js:213:9)
    at _next (/var/app/current/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/var/app/current/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at newTickHandler (/var/app/current/node_modules/mongoose/node_modules/mpromise/lib/promise.js:229:18)
    at process._tickDomainCallback (node.js:381:11)

**Comment by vkarpov15** [comment]
Please provide more context, hard to tell what's going on without some code samples.

**Comment by vkarpov15** [comment]
Issue stale, re-open if you still have a problem.
