### ISSUE TITLE
[Bug] model.create promise bluebird .catch

### ISSUE THREAD

**Issue by tsm91** [Automattic/mongoose#3297]
@vkarpov15 Hi

The following code snippet fails, the problem is, mongoose don't recognize bluebird's `.catch` method. This happens specifically at [Model.create](http://mongoosejs.com/docs/api.html#model_Model.create).
So for example i use a very similar code with `.findById ` and that one works fine.

im using `"version": "4.1.3"` and also applied the bluebird library as its possible since `4.1.0`
``` js
var mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
```

```js
Question
      .create({
        author: req.user._id,
        title: req.body.title,
        body: req.body.body,
        tags: req.body.tags
      })
      .then(function(question) {
        res.format({
          html: function() {
            req.flash('success', 'Successfully created question');
            res.redirect('/q');
          },
          json: function() {
            res.json(question);
          }
        });
      })
      .catch(function(err) {
        return next(err);
      });
```

stack trace:
```
error: undefined is not a function response_time=726, path=/q, page=1, limit=10, body=undefined, , status=302, response_type=text/html; charset=utf-8, type=api_error, message=undefined is not a function, stack=TypeError: undefined is not a function
    at create (/Users/tsm/Sites/dd/app/controllers/questions.js:106:13)
    at Layer.handle [as handle_request] (/Users/tsm/Sites/dd/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tsm/Sites/dd/node_modules/express/lib/router/route.js:131:13)
    at /Users/tsm/Sites/dd/node_modules/connect-ensure-login/lib/ensureLoggedIn.js:50:5
    at Layer.handle [as handle_request] (/Users/tsm/Sites/dd/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tsm/Sites/dd/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/tsm/Sites/dd/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/tsm/Sites/dd/node_modules/express/lib/router/layer.js:95:5)
    at /Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Users/tsm/Sites/dd/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:312:13)
    at /Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:271:10)
    at /Users/tsm/Sites/dd/etc/init/06-views.js:35:5
    at Layer.handle [as handle_request] (/Users/tsm/Sites/dd/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:312:13)
    at /Users/tsm/Sites/dd/node_modules/express/lib/router/index.js:280:7
```

**Comment by vkarpov15** [comment]
Woops looks like .create() doesn't actually use `mongoose.Promise`... Will fix that.

**Comment by tsm91** [comment]
it happens :) thanks

**Comment by BenjaminBini** [comment]
Uh, I guess it should be reopened : Model.create({...}).then(...).catch is still undefined.

**Comment by vkarpov15** [comment]
@BenjaminBini which version?

**Comment by BenjaminBini** [comment]
4.2.2.

I opened #3509
