### ISSUE TITLE
CastError instead of "real"  error

### ISSUE THREAD

**Issue by muka** [Automattic/mongoose#3320]
Dear
using `^4.1.3` when a setter throws an error, mongoose reports wrongly a `ValidationError` / `CastError`, hiding the real error

```
var UserSchema = new Schema({
    username: {
        type: String
    },
    password: {
        type: String,
        set: util.hash // this throw an error
    })
    // connect, setup model
   (new UserModel({ username: "a", password: "b" })).save(console.log)
```
This return a `ValidationError` saying `Cast to String failed for value "b" at path "password"`

But outputting the value of `e` at `https://github.com/Automattic/mongoose/blob/master/lib/document.js#L607` I get a different error (from the `util.hash` function)

Having the real error out would make debugging faster :)

Thank you
Best

**Comment by vkarpov15** [comment]
Unfortunately this behavior is asserted on in tests re: #2832 and has been around for a while, so we can't change it without being backwards breaking. However, in next release `CastError` will have a `.reason` field that will contain the error.

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/gh3320');
mongoose.set('debug', true);

var UserSchema = new Schema({
  username: {
    type: Number
  },
  password: {
    type: String,
    set: function() { throw new Error('oops'); }
  }
});

var User = mongoose.model('gh3320', UserSchema);

(new User({ username: 123, password: "b" })).save(console.log);
```

will output

```
{ [ValidationError: gh3320 validation failed]
  stack: 'Error\n    at MongooseError.ValidationError (/home/val/Workspace/10gen/mongoose/lib/error/validation.js:22:16)\n    at model.Document.invalidate (/home/val/Workspace/10gen/mongoose/lib/document.js:1230:32)\n    at model.Document.set (/home/val/Workspace/10gen/mongoose/lib/document.js:618:10)\n    at model.Document.set (/home/val/Workspace/10gen/mongoose/lib/document.js:502:18)\n    at model.Document (/home/val/Workspace/10gen/mongoose/lib/document.js:62:10)\n    at model.Model (/home/val/Workspace/10gen/mongoose/lib/model.js:43:12)\n    at new model (/home/val/Workspace/10gen/mongoose/lib/model.js:2814:11)\n    at Object.<anonymous> (/home/val/Workspace/10gen/troubleshoot-mongoose/gh-3320.js:21:2)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Function.Module.runMain (module.js:501:10)\n    at startup (node.js:129:16)\n    at node.js:814:3',
  message: 'gh3320 validation failed',
  name: 'ValidationError',
  errors: 
   { password: 
      { [CastError: Cast to String failed for value "b" at path "password"]
        stack: 'Error\n    at MongooseError.CastError (/home/val/Workspace/10gen/mongoose/lib/error/cast.js:18:16)\n    at model.Document.set (/home/val/Workspace/10gen/mongoose/lib/document.js:619:7)\n    at model.Document.set (/home/val/Workspace/10gen/mongoose/lib/document.js:502:18)\n    at model.Document (/home/val/Workspace/10gen/mongoose/lib/document.js:62:10)\n    at model.Model (/home/val/Workspace/10gen/mongoose/lib/model.js:43:12)\n    at new model (/home/val/Workspace/10gen/mongoose/lib/model.js:2814:11)\n    at Object.<anonymous> (/home/val/Workspace/10gen/troubleshoot-mongoose/gh-3320.js:21:2)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Function.Module.runMain (module.js:501:10)\n    at startup (node.js:129:16)\n    at node.js:814:3',
        message: 'Cast to String failed for value "b" at path "password"',
        name: 'CastError',
        kind: 'String',
        value: 'b',
        path: 'password',
        reason: [Error: oops] } } } // <------- here
```

**Comment by muka** [comment]
Excellent, thank you!
