### ISSUE TITLE
Exceptions swallowed by Mongoose

### ISSUE THREAD

**Issue by siboulet** [Automattic/mongoose#3371]
I initially reported this issue as a comment in #3222.

The following no longer works after updating to 4.1 (including the latest 4.1.7)

```
doc.save(function(err) {
if (err) throw err;
...
});
```

The exception is simply ignored.

**Comment by vkarpov15** [comment]
Hmm @siboulet are you setting a promises library for mongoose? Or is your save call wrapped in another function? The below code:

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/gh3371');

var s = new Schema({ test: String });
var M = mongoose.model('m', s);

new M().save(function(error) {
  throw new Error('fail');
});
```

Crashes as expected for me on 4.1.7.

```
$ node gh-3371.js 
Mongoose: ms.insert({ _id: ObjectId("55fc4db6271e464d215eb240"), __v: 0 })   
/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:757
      catch(err) { process.nextTick(function() { throw err}); }
                                                 ^

Error: fail
    at /home/val/Workspace/10gen/troubleshoot-mongoose/gh-3371.js:13:9
    at model.<anonymous> (/home/val/Workspace/10gen/mongoose/lib/document.js:1667:20)
    at next_ (/home/val/Workspace/10gen/mongoose/node_modules/hooks-fixed/hooks.js:89:34)
    at fnWrapper (/home/val/Workspace/10gen/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at /home/val/Workspace/10gen/mongoose/lib/model.js:269:13
    at /home/val/Workspace/10gen/mongoose/lib/model.js:127:7
    at /home/val/Workspace/10gen/mongoose/node_modules/mongodb/lib/collection.js:449:5
    at /home/val/Workspace/10gen/mongoose/node_modules/mongodb/lib/collection.js:593:5
    at /home/val/Workspace/10gen/mongoose/node_modules/mongodb/lib/bulk/unordered.js:457:9
    at resultHandler (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/lib/bulk/unordered.js:409:5)
    at /home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:756:13
    at Callbacks.emit (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/home/val/Workspace/10gen/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

**Comment by ksullivan** [comment]
@vkarpov15 Something odd is going on here. I'm experiencing the same issue.

I've used the code you provided above except I added this:

    console.log('version = ' + require('mongoose/package.json').version);

This is the output I get using mongoose@4.0.7:

    node mongoose_bug.js 
    version = 4.0.7
    Mongoose: ms.insert({ _id: ObjectId("560297a501adf17d689ce9c7"), __v: 0 })   
    /mongoose_bug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:108
      if (this.ended && !this.hasRejectListeners()) throw reason;
                                                          ^
    Error: fail
        at EventEmitter.<anonymous> (/mongoose_bug/mongoose_bug.js:28:9)
        at EventEmitter.<anonymous> (/mongoose_bug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
        at EventEmitter.emit (events.js:110:17)
        at Promise.safeEmit (/mongoose_bug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
        at Promise.fulfill (/mongoose_bug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
        at Promise.resolve (/mongoose_bug/node_modules/mongoose/lib/promise.js:113:23)
        at model.<anonymous> (/mongoose_bug/node_modules/mongoose/lib/document.js:1578:39)
        at next_ (/mongoose_bug/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:89:34)
        at EventEmitter.fnWrapper (/mongoose_bug/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:171:15)
        at EventEmitter.<anonymous> (/mongoose_bug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
        at EventEmitter.emit (events.js:110:17)
        at Promise.safeEmit (/mongoose_bug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
        at Promise.fulfill (/mongoose_bug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
        at p1.then.then.self.isNew (/mongoose_bug/node_modules/mongoose/lib/model.js:254:27)
        at newTickHandler (/mongoose_bug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:229:18)
        at process._tickCallback (node.js:355:11)

This is the output I get using mongoose@4.1.7 or mongoose@4.1.8:

    node mongoose_bug.js 
    version = 4.1.7
    Mongoose: ms.insert({ _id: ObjectId("560297c0c63bbc1e6add23ac"), __v: 0 })   

I'm using node v0.12.7.

**Comment by vkarpov15** [comment]
You're not getting any error at all in the second case? That's weird, I get the exception on mongoose 4.1.8. Which OS?

**Comment by ksullivan** [comment]
@vkarpov15 I noticed that
mongoose@4.0.7 depends on mongodb@2.0.34
and
mongoose@4.1.8 depends on mongodb@2.0.42
.

If I use mongoose@4.1.8 but make it to use mongodb@2.0.34, the error is printed.

**Comment by vkarpov15** [comment]
4.1.8 is not expected to work with 2.0.34...

**Comment by ksullivan** [comment]
@vkarpov15 Looking into it further I think it's going to be something to do with the fact that I'm using MongoDB 2.4.

The exception is caught here:

https://github.com/christkv/mongodb-core/blob/5b49740860642c3750ac5c7f802edc9fc219b881/lib/topologies/server.js#L244

Then the error doesn't get passed anywhere because there's no callbacks in the callbacks object.

**Comment by vkarpov15** [comment]
Are you loading a big document? At first glance, it looks like you should only trip that try/catch if you're loading a malformed or > 16MB bson doc.

**Comment by siboulet** [comment]
Using MongoDB 3.0.6 here and small document of a few KB. I'm not using promise. However, my calls are wrapped in async waterfall.

**Comment by ksullivan** [comment]
@vkarpov15 It should be a tiny document because the code I'm running is the code you posted.

**Comment by vkarpov15** [comment]
I'll double-check with 2.4 later and see if I can repro.

**Comment by ksullivan** [comment]
@vkarpov15 This seems to fix it though I have no idea if it's the appropriate fix: https://gist.github.com/ksullivan/13d7d81ba50377868c7d

**Comment by vkarpov15** [comment]
@christkv what do you think of https://gist.github.com/ksullivan/a3c4af174355f647f132?

**Comment by christkv** [comment]
Without testing it I do not know if this will solve it. and I would need a test case for this using the driver before exploring.
