### ISSUE TITLE
Running into error throw new TypeError('Not a RegExp');

### ISSUE THREAD

**Issue by spruce** [Automattic/mongoose#3389]
This as a new inserted line 288 in lib/utils.js (not included while creating stacktrace)
```
console.log('utils', k, obj[k], exports.getFunctionName(obj[k].constructor), obj[k].constructor.name, Object.prototype.toString.call(obj[k]));
```

When trying to save the following gets written to the console: (created by my new line)
```
utils $set { expired_at: 1443198500212, seen_at: 1442766500212 } Object Object [object Object]
utils seen_at 1442766500212 Number Number [object Number]
utils expired_at 1443198500212 Number Number [object Number]
utils regexp {} RegExp RegExp [object Object]
/project/node_modules/mongoose/node_modules/regexp-clone/index.js:11
    throw new TypeError('Not a RegExp');
          ^
TypeError: Not a RegExp
    at module.exports.exports (/project/node_modules/mongoose/node_modules/regexp-clone/index.js:11:11)
    at clone (/project/node_modules/mongoose/lib/utils.js:237:16)
    at cloneObject (/project/node_modules/mongoose/lib/utils.js:288:13)
    at Object.clone (/project/node_modules/mongoose/lib/utils.js:233:16)
    at /project/node_modules/mongoose/lib/schematype.js:665:37
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/project/node_modules/mongoose/lib/schematype.js:658:19)
    at /project/node_modules/mongoose/lib/document.js:1102:11
    at doNTCallback0 (node.js:415:9)
    at process._tickCallback (node.js:344:13)
```

What is to notice is the last line the RegExp are the tests for the whether it is a regular expression inside mongoose and the last one inside regexp-clone which then throws the error.

it is a mongoose model for a session.

This happens with v 4.1.7 and not version 4.0.2.
Will be investigating further

**Comment by spruce** [comment]
It did break between 4.0.8 and 4.1.0 for me

**Comment by vkarpov15** [comment]
Can you show me a more thorough code example? Hard to tell what's causing this issue.

**Comment by spruce** [comment]
From what? The session model?

**Comment by vkarpov15** [comment]
Ah I see, this issue only happens when you insert that line into mongoose code? I would really not recommend inserting code into mongoose, there's no way for us to support that. I'll take a look and see if it's indicative of a larger bug though :)

**Comment by spruce** [comment]
No it always happens. What I wanted to say is that the codelines are without the inserted code to have the correct line numbers.

Model:
```
var fs = require('fs');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var config = require('../../../config');

var schema = new Schema({
  authToken: String,
  user: {
    type: Schema.Types.ObjectId,
    ref: 'User'
  },
  created_at: {
    type: Date,
    default: Date.now
  },
  expired_at: {
    type: Date,
    default: function() {
      return Date.now() + config.session.duration /* Hours */ * 60 /* Minutes */ * 60 /* Seconds */ * 1000 /* Miliseconds */
    }
  },
  seen_at: {
    type: Date,
    default: Date.now
  }
});

var filenameParts = __filename.split('/');
if(fs.existsSync(__dirname + '/../extensions/' + filenameParts[filenameParts.length - 1])) {
  schema = require(__dirname + '/../extensions/' + filenameParts[filenameParts.length - 1])(schema);
}


module.exports = schema;

```

Updating Code:
```
var mongoose = require('mongoose');

var config = require(__dirname + '/../../../config.js');
module.exports = function(schema) {
  schema.statics.authenticated = function(authToken, cb) {
    // check whether there is a session for this authToken and then update it if it exists

    this.model('Session').findOneAndUpdate({
      authToken: authToken
    }, {
      $set: {
        expired_at: Date.now() + config.session.duration /* Hours */ * 60 /* Minutes */ * 60 /* Seconds */ * 1000 /* Miliseconds */ ,
        seen_at: Date.now()
      }
    }, function(err, item) {
      if(err) return config.error(err, cb);
      if(item) {
        return cb(null, item.user.toString())
      }
      return cb(null, false);
    });
  };
  return schema
}

```

**Comment by vkarpov15** [comment]
So the `findOneAndUpdate()` fails with the above stack trace?

**Comment by vkarpov15** [comment]
The below script executes for me without error. Please provide additional context.

```javascript
var fs = require('fs');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/gh3389');

var schema = new Schema({
  authToken: String,
  user: {
    type: Schema.Types.ObjectId,
    ref: 'User'
  },
  created_at: {
    type: Date,
    default: Date.now
  },
  expired_at: {
    type: Date,
    default: function() {
      return Date.now() + 5 /* Hours */ * 60 /* Minutes */ * 60 /* Seconds */ * 1000 /* Miliseconds */
    }
  },
  seen_at: {
    type: Date,
    default: Date.now
  }
});

var Model = mongoose.model('gh3389', schema);

Model.findOneAndUpdate({
      authToken: 'test'
    }, {
      $set: {
        expired_at: Date.now() + 5 /* Hours */ * 60 /* Minutes */ * 60 /* Seconds */ * 1000 /* Miliseconds */ ,
        seen_at: Date.now()
      }
    },
    function(error) {
      console.log(error);
      process.exit(0);
    });
```

**Comment by vkarpov15** [comment]
Issue is stale and can't repro, re-open if this is still a problem.

**Comment by spruce** [comment]
I think I found a way to repro. Problem is that with mongoose-schema-extend it breaks on regexp somehow

**Comment by vkarpov15** [comment]
@spruce open up an issue on mongoose-schema-extend if you think there's a bug there :)
