### ISSUE TITLE
release 4.1.11 breaks existing code that worked on 4.1.10

### ISSUE THREAD

**Issue by facultymatt** [Automattic/mongoose#3466]
Just updated to 4.1.11 and code which was working previously now fails.  

Stacktrace: 

```
Uncaught MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: project-db.clients.$secret_1  dup key: { : "shh" }
      at Function.MongoError.create (/Project/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
      at toError (/Project/node_modules/mongoose/node_modules/mongodb/lib/utils.js:114:22)
      at /Project/node_modules/mongoose/node_modules/mongodb/lib/collection.js:587:23
      at /Project/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:472:9
      at resultHandler (/Project/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:419:5)
      at /Project/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:756:13
      at Callbacks.emit (/Project/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
      at null.messageHandler (/Project/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
      at Socket.<anonymous> (/Project/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)
```

Not sure exactly why this is happening yet but will update if I make any discoveries.

**Comment by vkarpov15** [comment]
Show your code, there's not enough information in this report for me to provide any useful information.
