### ISSUE TITLE
Cannot save document with single embeded document

### ISSUE THREAD

**Issue by xyleen** [Automattic/mongoose#3535]
Might be related to #3534.

Test snippet:
```javascript
'use strict';

var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/testtt',  { server: { poolSize: 20 } });


var ChildSchema = new mongoose.Schema({
	foo: String,
});
ChildSchema.methods.bar = function () {
	return 'BAR + ' + this.foo;
};
var Child = mongoose.model('Child', ChildSchema);

var ParentSchema = new mongoose.Schema({
	inner: ChildSchema,
});
var Parent = mongoose.model('Parent', ParentSchema);



var child = new Child({ foo: 'foo' });
console.log(child.bar())
var parent = new Parent({ inner: child });

parent.save().then(console.log, function (err) { console.error(err.stack) });
```
results in:
```
BAR + foo
{ [MongoError: key $__ must not start with '$']
  name: 'MongoError',
  message: 'key $__ must not start with \'$\'' }
Error: key $__ must not start with '$'
    at Error (<anonymous>)
    at serializeInto (/test/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:680:19)
    at serializeObject (/test/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/test/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (/test/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/test/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject (/test/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/test/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serialize (/test/node_modules/mongoose/node_modules/bson/lib/bson/bson.js:47:27)
    at Query.toBin (/test/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/commands.js:123:25)
    at executeSingleOperation (/test/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:750:28)
    at Server.command (/test/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:830:12)
    at executeWrite (/test/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:52:12)
    at WireProtocol.insert (/test/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:60:3)
    at Server.insert (/test/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:949:37)
    at Server.insert (/test/node_modules/mongoose/node_modules/mongodb/lib/server.js:324:17)
```

mongoose 4.2.4 + node v0.10.38 + mongo version 2.6.9

**Comment by vkarpov15** [comment]
As a workaround, you should be able to just do `var parent = new Parent({ inner: child.toObject() });`. Mongoose is getting confused because `child` is a fully-fledged mongoose doc rather than a POJO
