### ISSUE TITLE
FindById causes two unhandled rejection errors using bluebird

### ISSUE THREAD

**Issue by numbnut** [Automattic/mongoose#3543]
node.js: 0.12.7
mongodb: 3.0.6
mongoose: 4.2.4
bluebird: 3.0.5

When using bluebird as the mongoose promise implementation FindById results in two unhandled rejection errors when querying with a malformed mongo id. The following example reproduces the behaviour.

```javascript
var mongoose = require('mongoose'); 
mongoose.Promise = require('bluebird');
mongoose.connect('mongodb://localhost/test');

var db = mongoose.connection;  
var kittySchema = mongoose.Schema({ 
  name: String                 
});
var Kitten = mongoose.model('Kitten', kittySchema);
//var id = "573b7fb34b236b943251bd63";
var id = "123";
Kitten
  .findById(id)                
  .then(function(kitten){      
    console.log(kitten);
  });
```
Output:
```
Unhandled rejection Error
    at MongooseError.CastError (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/error/cast.js:18:16)
    at ObjectId.cast (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/schema/objectid.js:134:13)
    at ObjectId.castForQuery (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/schema/objectid.js:173:17)
    at module.exports (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/cast.js:205:32)
    at Query.cast (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2504:10)
    at Query.findOne (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:1237:10)
    at /home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2125:21
    at Promise._execute (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:76:14)
    at Query.exec (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2118:10)
    at /home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2348:10
    at Promise._execute (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:76:14)
    at Query.then (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2347:17)
    at Object.<anonymous> (/home/niklas/projects/skybus/platform/mongoose-bug/mongoose-error.js:14:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

Unhandled rejection Error
    at MongooseError.CastError (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/error/cast.js:18:16)
    at ObjectId.cast (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/schema/objectid.js:134:13)
    at ObjectId.castForQuery (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/schema/objectid.js:173:17)
    at module.exports (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/cast.js:205:32)
    at Query.cast (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2504:10)
    at Query.findOne (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:1237:10)
    at /home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2125:21
    at Promise._execute (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:76:14)
    at Query.exec (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2118:10)
    at /home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2348:10
    at Promise._execute (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:76:14)
    at Query.then (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2347:17)
    at Object.<anonymous> (/home/niklas/projects/skybus/platform/mongoose-bug/mongoose-error.js:14:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Adding a catch only catches one of them. 

```javascript
var mongoose = require('mongoose'); 
mongoose.Promise = require('bluebird');
mongoose.connect('mongodb://localhost/test');

var db = mongoose.connection;  
var kittySchema = mongoose.Schema({ 
  name: String                 
});
var Kitten = mongoose.model('Kitten', kittySchema);
//var id = "573b7fb34b236b943251bd63";
var id = "123";
Kitten
  .findById(id)                
  .then(function(kitten){      
    console.log(kitten);       
  }).catch(function(err){
    console.log(err.stack);
  });
```
Output:
```
Error
    at MongooseError.CastError (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/error/cast.js:18:16)
    at ObjectId.cast (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/schema/objectid.js:134:13)
    at ObjectId.castForQuery (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/schema/objectid.js:173:17)
    at module.exports (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/cast.js:205:32)
    at Query.cast (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2504:10)
    at Query.findOne (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:1237:10)
    at /home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2125:21
    at Promise._execute (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:76:14)
    at Query.exec (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2118:10)
    at /home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2348:10
    at Promise._execute (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:76:14)
    at Query.then (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2347:17)
    at Object.<anonymous> (/home/niklas/projects/skybus/platform/mongoose-bug/mongoose-error.js:14:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
Unhandled rejection Error
    at MongooseError.CastError (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/error/cast.js:18:16)
    at ObjectId.cast (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/schema/objectid.js:134:13)
    at ObjectId.castForQuery (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/schema/objectid.js:173:17)
    at module.exports (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/cast.js:205:32)
    at Query.cast (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2504:10)
    at Query.findOne (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:1237:10)
    at /home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2125:21
    at Promise._execute (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:76:14)
    at Query.exec (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/lib/query.js:2118:10)
    at /home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2348:10
    at Promise._execute (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/bluebird/js/release/promise.js:76:14)
    at Query.then (/home/niklas/projects/skybus/platform/mongoose-bug/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2347:17)
    at Object.<anonymous> (/home/niklas/projects/skybus/platform/mongoose-bug/mongoose-error.js:14:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Maybe there is a second promise, not connected to the chain created by FindById?

**Comment by vkarpov15** [comment]
Yeah confirmed, this is an issue. As a workaround, just use `.exec()`:

```javascript
Kitten
  .findById(id)
  .exec()
  .then(function(kitten){      
    console.log(kitten);
  })
  .catch(handleError);
```

**Comment by RyuuGan** [comment]
Looks like this fix broke all catch statements. That is what I get in 4.2.6:
```
TypeError: Realm.findOne(...).exec(...).then(...).catch is not a function
```

But if you write then with 2 params then it works fine, looks like now only `A+` promises supported, but not `ES6`?

By the way it is not only with `findOne`, all other queries behave like that.

**Comment by vkarpov15** [comment]
@RyuuGan it didn't break catch statements, we have tests in place for that. Can you show me a standalone example that reproduces the issue you're seeing?

**Comment by RyuuGan** [comment]
@vkarpov15 I've created a [repository](https://github.com/RyuuGan/Mongoose-4.2.6-Test) to reproduce an issue.

**Comment by vkarpov15** [comment]
You're not setting `mongoose.Promise`. You need to explicitly set [the `mongoose.Promise` property to get bluebird or your favorite ES6 promises lib of choice](http://mongoosejs.com/docs/promises.html#plugging-in-your-own-promises-library). The fact that `.catch()` worked with `.exec()` before is indicative of a bug in mongoose. Getting `.catch()` back is a one-liner though, and mongoose will consistently use whichever promise library you want.

**Comment by RyuuGan** [comment]
@vkarpov15, Thanks a lot. It helped.
