### ISSUE TITLE
Using a custom typeKey doesn't work within arrays

### ISSUE THREAD

**Issue by bnord01** [Automattic/mongoose#3560]
## Using a custom typeKey doesn't work inside arrays. 

An undefined 'type' error is thrown. 

See the following examples and the error below:

- mongoose version: 4.2.4
- node version: 4.2.1

### This doesn't work:
```javascript
new mongoose.Schema({
  type: String,
  things: [{
    subthing: {
      $type: String,
      match: /^[a-z]*$/
    }
  }]
}, {
  typeKey: '$type'
});
``` 
#### The following error is thrown: 
```
/Users/bnord/test/node_modules/mongoose/lib/schema.js:573
    throw new TypeError('Undefined type `' + name + '` at `' + path +
    ^

TypeError: Undefined type `undefined` at `subthing.match`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/bnord/test/node_modules/mongoose/lib/schema.js:573:11)
    at Schema.path (/Users/bnord/test/node_modules/mongoose/lib/schema.js:498:29)
    at Schema.add (/Users/bnord/test/node_modules/mongoose/lib/schema.js:393:12)
    at Schema.add (/Users/bnord/test/node_modules/mongoose/lib/schema.js:388:14)
    at new Schema (/Users/bnord/test/node_modules/mongoose/lib/schema.js:92:10)
    at Function.Schema.interpretAsType (/Users/bnord/testnode_modules/mongoose/lib/schema.js:547:52)
    at Schema.path (/Users/bnord/test/node_modules/mongoose/lib/schema.js:498:29)
    at Schema.add (/Users/bnord/test/node_modules/mongoose/lib/schema.js:393:12)
    at new Schema (/Users/bnord/test/node_modules/mongoose/lib/schema.js:92:10)
    at Object.<anonymous> (/Users/bnord/test/MongooseType.js:29:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
```
### Using the default 'type' it works:
```javascript
new mongoose.Schema({
  some: String,
  things: [{
    subthing: {
      type: String,
      match: /[^a-z$]/
    }
  }]
});
```

### Removing the array makes it work also:
```javascript
new mongoose.Schema({
  type: String,
  thing: {
    subthing: {
      $type: String,
      match: /^[a-z]*$/
    }
  }
}, {
  typeKey: '$type'
});
```

**Comment by vkarpov15** [comment]
Thanks for reporting this, will fix ASAP.
