### ISSUE TITLE
"MongoError: topology was destroyed" in aws EC2 Container

### ISSUE THREAD

**Issue by kostuyn** [Automattic/mongoose#3561]
In my aws EC2 Containers works two service mongodb and nodejs(REST API). Occasionally in nodejs service occurs "MongoError: topology was destroyed". mongodb and nodejs services works under the load balancer (aws EC2 LoadBalancers).

```
MongoError: topology was destroyed
    at Server.update (/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:966:49)
    at Server.update (/app/node_modules/mongoose/node_modules/mongodb/lib/server.js:331:17)
    at updateDocuments (/app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:967:19)
    at Collection.update (/app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1005:44)
    at /app/node_modules/connect-mongo/lib/connect-mongo.js:360:18
    at MongoStore.getCollection (/app/node_modules/connect-mongo/lib/connect-mongo.js:216:11)
    at MongoStore.set (/app/node_modules/connect-mongo/lib/connect-mongo.js:358:10)
    at Session.save (/app/node_modules/express-session/session/session.js:71:25)
    at Session.save (/app/node_modules/express-session/index.js:331:15)
    at ServerResponse.end (/app/node_modules/express-session/index.js:289:21)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:195:10)
    at /app/routes/index.js:16:13
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
    at next (/app/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.header (/app/node_modules/express/lib/response.js:700:10)
    at ServerResponse.json (/app/node_modules/express/lib/response.js:237:10)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:142:21)
    at app.use.res.send.message (/app/app.js:80:13)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:300:13)
    at /app/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)
    at next (/app/node_modules/express/lib/router/index.js:261:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:54:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:300:13)
    at /app/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)
    at Object.next (/app/node_modules/express/lib/router/index.js:261:10)
    at Object.immediate._onImmediate (timers.js:381:16)
```

Strange that at /app/routes/index.js:16:13 not have operation with mongodb:
```
15:   router.get('/heartbeat', function (req, res) {
16:           res.send();
17:   });
```
Before this error was call another route with code:
```
// JWT-Passport, get user
User.findById(jwtPayload.userId, function (err, user) {
            if (err) {
                return done(err, false);
            }
            if (user) {
                req.token = jwtPayload.token;
                done(null, user);
            } else {
                done(null, false);
            }
        });
...
//Edit user
...
//Save changes
req.user.save(function (err) {
        if (err)
            return next(err);

        next();
    });
```
Nodejs application have single connection for all query, without closes:
```
var options = {
    server: {
        socketOptions: {
            keepAlive: 1,
            connectTimeoutMS: 30000
        }
    },
    replset: {
        socketOptions: {
            keepAlive: 1,
            connectTimeoutMS: 30000
        }
    }
};
mongoose.connect(config.get('mongodb:connection'), options);
```

**Comment by vkarpov15** [comment]
Are you running mongodb behind ELB? That's probably not a very good idea...

Also, the "topology is destroyed" error typically means there was a hiccup in your connection to mongodb - did mongodb go down around the time when you ran the query?

**Comment by kostuyn** [comment]
Yes, mongodb behind ELB.
Mongodb worked stable all the time

**Comment by vkarpov15** [comment]
I'm reasonably sure that running 2 independent mongodb's behind ELB is not supported behavior. It's [already tricky to run a mongodb sharding router behind a load balancer](http://craiggwilson.com/2013/10/21/load-balanced-mongos/). I'm not sure how ELB works with long-lived socket connections, but I wouldn't be surprised that the driver gets disconnected occasionally given this setup.
