### ISSUE TITLE
Exception when validating sub-docs

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [Automattic/mongoose#3562]
Hello,

I have a Schema that has a required subdoc. When I validate an object if it does not contain the key of the subdoc, instead of sending a validation error a JavaScript exception is thrown.

```
var priceSchema = mongoose.Schema({
  value: {
    type: 'Number',
    required: true,
    min: 0
  }, currency: {
    type: 'String',
    required: true
  }
});

var bedSchema = mongoose.Schema({
  price: {
    type: priceSchema,
    required: true
  },
});
```

Running : `new Bed({}).save().then(...)` return this trace : 
```
/home/guillaume/dev/papayopods/node_modules/mongoose/lib/schema/embedded.js:82
  value.validate(fn, { __noPromise: true });
       ^

TypeError: Cannot read property 'validate' of undefined
    at SchemaType.Embedded.doValidate (/home/guillaume/dev/papayopods/node_modules/mongoose/lib/schema/embedded.js:82:8)
    at /home/guillaume/dev/papayopods/node_modules/mongoose/lib/document.js:1139:9
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

But running `new Bed({price:{}}).save().then(...)` runs fine

Mongoose version : 4.25
Nodejs version: 5.00
MongoDb version : Mongolabs

Best,

Guillaume Leclerc

**Comment by GuillaumeLeclerc** [comment]
Whoa, that was quick, thank you so much !
