### ISSUE TITLE
regression in v4.2.6: Cannot read property 'model' of undefined in array.js

### ISSUE THREAD

**Issue by RBLU** [Automattic/mongoose#3579]
When I update my project from 4.2.5 to 4.2.6 I get the following error. Downgrading to 4.2.5 solves the issue. The code causing this simply tries to pull an object from an array:

                challenge.pendingUsers.pull(req.user._id);

I looked through the commits in 4.2.6, maybe this here is responsible: https://github.com/Automattic/mongoose/commit/47f6806918babea58fc6f8c2d4bb5029040b3ad3

TypeError: Cannot read property 'model' of undefined
        at Array.MongooseArray.mixin._cast (/Volumes/SourceDev2/yp/haw-backend/node_modules/ypbackendlib/node_modules/mongoose/lib/types/array.js:105:32)
        at Object.map (native)
        at Array.MongooseArray.mixin.pull (/Volumes/SourceDev2/yp/haw-backend/node_modules/ypbackendlib/node_modules/mongoose/lib/types/array.js:506:25)
        at /Volumes/SourceDev2/yp/haw-backend/src/handlers/teamChallenge_handlers.js:65:38
        at Query.<anonymous> (/Volumes/SourceDev2/yp/haw-backend/node_modules/ypbackendlib/node_modules/mongoose/lib/query.js:2138:28)
        at /Volumes/SourceDev2/yp/haw-backend/node_modules/ypbackendlib/node_modules/mongoose/node_modules/kareem/index.js:177:19
        at /Volumes/SourceDev2/yp/haw-backend/node_modules/ypbackendlib/node_modules/mongoose/node_modules/kareem/index.js:109:16
        at doNTCallback0 (node.js:417:9)
        at process._tickDomainCallback (node.js:387:13)

**Comment by vkarpov15** [comment]
Thanks for reporting, will push a fix later this week.
