### ISSUE TITLE
Removing field with single subdocument fails

### ISSUE THREAD

**Issue by andrenarchy** [Automattic/mongoose#3596]
Removing a field that holds a single subdocuments yields an error. Example:
```js
var jobSchema = new mongoose.Schema({
  title: {type: String}
});

var personSchema = new mongoose.Schema({
  name: {type: String},
  job: jobSchema,
});

var Person = mongoose.model('Person', personSchema);
Person.create({name: 'bob', job: { title: 'chef'}}, function(err, bob) {
  bob.job = undefined;
  bob.save(function(err, bobUnemployed) {
    console.log(err);
  });
});
```
Error message:
```javascript
TypeError: Cannot read property 'validate' of undefined
    at /home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/schema/embedded.js:92:10
    at SchemaType.doValidate (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/schematype.js:654:22)
    at SchemaType.Embedded.doValidate (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/schema/embedded.js:88:35)
    at /home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/document.js:1152:9
    at doNTCallback0 (node.js:428:9)
    at process._tickDomainCallback (node.js:398:13)
```

**Comment by nschloe** [comment]
Bumped into the same issue just now. Thanks for adding it to the milestone!

**Comment by andrenarchy** [comment]
@vkarpov15 thx for fixing!
