### ISSUE TITLE
TypeError: val.toObject is not a function

### ISSUE THREAD

**Issue by sitegui** [Automattic/mongoose#3623]
Hello,

In mongoose `4.1` and `4.2` I get the error:
```
TypeError: val.toObject is not a function
    at EmbeddedDocument.docReducer (/home/guilherme/Programs/oss/mongoose/lib/document.js:1623:17)
    at Array.reduce (native)
    at EmbeddedDocument.Document.$__getAllSubdocs (/home/guilherme/Programs/oss/mongoose/lib/document.js:1631:40)
    at EmbeddedDocument.Object.defineProperty.value.fn (/home/guilherme/Programs/oss/mongoose/lib/schema.js:246:26)
    at _next (/home/guilherme/Programs/oss/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/home/guilherme/Programs/oss/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at EmbeddedDocument.Object.defineProperty.value.fn (/home/guilherme/Programs/oss/mongoose/lib/schema.js:209:16)
    at EmbeddedDocument._next (/home/guilherme/Programs/oss/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at EmbeddedDocument.proto.(anonymous function) [as $__original_save] (/home/guilherme/Programs/oss/mongoose/node_modules/hooks-fixed/hooks.js:108:20)
    at /home/guilherme/Programs/oss/mongoose/lib/document.js:1735:23
    at new Promise.ES6 (/home/guilherme/Programs/oss/mongoose/lib/promise.js:45:3)
    at EmbeddedDocument.wrappedPointCut [as save] (/home/guilherme/Programs/oss/mongoose/lib/document.js:1717:14)
    at async.each.i (/home/guilherme/Programs/oss/mongoose/lib/schema.js:257:18)
    at /home/guilherme/Programs/oss/mongoose/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/guilherme/Programs/oss/mongoose/node_modules/async/lib/async.js:46:24)
```

In the following code:
```js
'use strict'

let mongoose = require('mongoose'),
	assert = require('assert')

mongoose.connect('mongodb://localhost:27017/test')

var schema = new mongoose.Schema({
	array: [{
		1: {
			date: Date
		},
		2: {
			date: Date
		},
		3: {
			date: Date
		}
	}]
})

let Order = mongoose.model('Order', schema, 'Order'),
	doc = {
		array: [{
			2: {}
		}]
	}

Order.collection.insertOne(doc, function (err) {
	assert.ifError(err)

	Order.findOne({
		_id: doc._id
	}, function (err, order) {
		assert.ifError(err)

		order.array.push({
			2: {}
		})

		order.save(function (err) {
			assert.ifError(err)
			mongoose.disconnect()
		})
	})
})
```

This seems to be related to pushing to an array of subdocuments with numeric keys.

Any idea?

**Comment by vkarpov15** [comment]
Confirmed the bug but not entirely sure why it's happening. Probably due to numeric keys but no ideas yet.
