### ISSUE TITLE
Overwriting "pre" hook condition error on find.

### ISSUE THREAD

**Issue by mcteo** [Automattic/mongoose#3626]
Not 100% sure should this be reported here, or to mquery directly.

This error was evident with mongoose v4.2.8, node v0.12.7, and mongodb v3.0.4.

Stacktrace of error:
```
C:\workspace\node\mongoose-bug>node index.js
C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:779
      catch(err) { process.nextTick(function() { throw err}); }
                                                       ^
TypeError: Cannot assign to read only property '$ne' of true
    at merge (C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\mquery\lib\utils.js:158:15)
    at Object.merge (C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\mquery\lib\utils.js:161:9)
    at Query.merge (C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\mquery\lib\mquery.js:1583:9)
    at Query.where (C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\mquery\lib\mquery.js:276:17)
    at Query.<anonymous> (C:\workspace\node\mongoose-bug\index.js:21:14)
    at next (C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\kareem\index.js:82:14)
    at Kareem.execPre (C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\kareem\index.js:99:3)
    at Kareem.wrap (C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\kareem\index.js:146:8)
    at Query._find (C:\workspace\node\mongoose-bug\node_modules\mongoose\node_modules\kareem\index.js:188:11)
    at Query.find (C:\workspace\node\mongoose-bug\node_modules\mongoose\lib\query.js:1099:8)
    at Function.find (C:\workspace\node\mongoose-bug\node_modules\mongoose\lib\model.js:1138:13)
    at C:\workspace\node\mongoose-bug\index.js:52:19
    at C:\workspace\node\mongoose-bug\node_modules\async\lib\async.js:721:13
    at C:\workspace\node\mongoose-bug\node_modules\async\lib\async.js:52:16
    at done (C:\workspace\node\mongoose-bug\node_modules\async\lib\async.js:246:17)
    at C:\workspace\node\mongoose-bug\node_modules\async\lib\async.js:44:16
```

I'm using the async library to keep things tidy:
```javascript
"use strict";

var mongoose = require("mongoose");
var async = require("async");

mongoose.connect("mongodb://localhost/blah");

mongoose.connection.on("open", function() {
    runTest();
});

function runTest() {

    var test_schema = mongoose.Schema({
        name    : String,
        deleted : { type: Boolean, default: false }
    });

    // normally we want to hide deleted documents
    test_schema.pre("find", function(next) {
        this.where({
            "deleted": {
                "$ne": true
            }
        });

        next();
    });

    var TestModel = mongoose.model("TestModel", test_schema);

    async.parallel([
        function(callback) {

            TestModel.create({
                "name": "Undeleted Model"
            }, callback);

        },

        function(callback) {

            TestModel.create({
                "name": "Deleted Model",
                "deleted": true
            }, callback);

        }

    ], function(errors, results) {

        // this should return the deleted items
        TestModel.find({
            "deleted": true
        }, function(error, results) {

            console.log(results);

            // for some reason node hangs for me when using mongoose, so have to exit manually.
            TestModel.remove(process.exit);

        });
    });
}
```

So the underlying cause seems to be, the mquery library tries to merge conditions `{ deleted: { "$ne": true } }` with `{ deleted: true }`, I believe in the wrong order.

I think the condition passed to find should overwrite a condition set in a pre-hook?

**Comment by vkarpov15** [comment]
Actually this is correct behavior, pre find executes _after_ your conditions have been merged into the query object, so the right way to do this would be to check for the presence of `deleted` in the query:

```javascript
    test_schema.pre("find", function(next) {
        if (!('deleted' in this.getQuery())) {
          this.where({
            "deleted": {
              "$ne": true
            }
          });
        }

        next();
    });
```
