### ISSUE TITLE
MissingSchemaError: Schema hasn't been registered for model "Article"

### ISSUE THREAD

**Issue by loyogo** [Automattic/mongoose#3659]
a simple populate cause error. any commens? thanks
```
var mongoose = require('mongoose');
mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/demo');
var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function (callback) {
  console.log("connected");
});

var ArticleSchema = new mongoose.Schema({
    title: String,
});
var Article = mongoose.model('article', ArticleSchema);

var CommentSchema = new mongoose.Schema({
    content: String,
    article:{type:mongoose.Schema.Types.ObjectId,ref: 'Article'}
});
var Comment = mongoose.model('comment', CommentSchema);

Comment.findOne({content:"comment1"}).populate("article").exec(function (err, comment) {
 if (err) return handleError(err);
 console.log(comment);
});
```

node test.js 
Mongoose: comments.findOne({ content: 'comment1' }) { fields: undefined }  
connected

/home/dev/node_modules/mongoose/lib/connection.js:664
    throw new MongooseError.MissingSchemaError(name);
    ^
MissingSchemaError: Schema hasn't been registered for model "Article".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (/home/dev/node_modules/mongoose/lib/connection.js:664:11)
    at getModelsMapForPopulate (/home/dev/node_modules/mongoose/lib/model.js:2602:26)
    at populate (/home/dev/ny/es7/node_modules/mongoose/lib/model.js:2443:15)
    at Function.Model.populate (/home/dev/node_modules/mongoose/lib/model.js:2356:5)
    at Immediate.<anonymous> (/home/dev/node_modules/mongoose/lib/query.js:1167:16)
    at Immediate._onImmediate (/home/dev/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by vkarpov15** [comment]
Try `var Article = mongoose.model('Article', ArticleSchema);`, notice the upper-case 'A' in the model name. The `ref` must match the model name.

**Comment by loyogo** [comment]
great it works. thank you. I thought that is collection name.

**Comment by loyogo** [comment]
@vkarpov15 great it works. thank you. I thought that is collection name.
