### ISSUE TITLE
Mongoose + Bluebird: invalidate() causes "Unhandled rejection" warning

### ISSUE THREAD

**Issue by geronime** [Automattic/mongoose#3669]
Simplified code to reproduce the issue:

```javascript
'use strict';

var mongoose = require('mongoose'),
    bluebird = require('bluebird');

mongoose.Promise = bluebird;

mongoose.connect('mongodb://localhost/test');

var someSchema = mongoose.Schema({someKey: String});
someSchema.pre('validate', function (next) {
    this.invalidate('someKey', 'invalid', 'someVal');
    next();
});

var SomeModel = mongoose.model('SomeModel', someSchema, 'test');

mongoose.connection.once('open', function (err) {
    if (err) {
        throw err;
    }

    SomeModel.create({}, function(err, doc) {
        if (err) {
            console.log('Error: %j', err.message);
        } else {
            console.log('Saved: %j', doc);
        }
        mongoose.connection.close();
    });
});
```

I get:
```bash
$ node index.js
Error: "SomeModel validation failed"
Unhandled rejection ValidationError: SomeModel validation failed
    at MongooseError.ValidationError (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/lib/document.js:1280:32)
    at model.<anonymous> (/private/tmp/mongoose-invalidate-test/index.js:12:10)
    at model._next (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at model.proto.(anonymous function) [as $__original_validate] (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:108:20)
    at model.Object.defineProperty.value.fn (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/lib/schema.js:229:16)
    at model._next (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at model.proto.(anonymous function) [as $__original_save] (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:108:20)
    at /private/tmp/mongoose-invalidate-test/node_modules/mongoose/lib/model.js:1755:18
    at /private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:570:21
    at /private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:249:17
    at /private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:46:24)
    at async.each (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:248:13)
    at Object.map (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:219:23)
    at _parallel (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:568:20)
    at Object.async.parallel (/private/tmp/mongoose-invalidate-test/node_modules/mongoose/node_modules/async/lib/async.js:598:9)
    at /private/tmp/mongoose-invalidate-test/node_modules/mongoose/lib/model.js:1762:11
    at Promise._execute (/private/tmp/mongoose-invalidate-test/node_modules/bluebird/js/release/debuggability.js:159:9)
    at Promise._resolveFromExecutor (/private/tmp/mongoose-invalidate-test/node_modules/bluebird/js/release/promise.js:460:18)
```

Commenting out `mongoose.Promise = bluebird` I get:
```bash
$ node index.js
Error: "SomeModel validation failed"
```

I found some issues related to "Unhandled rejection Error" warnings but not exactly this one. Is this an error on my side, issue in mongoose or bluebird?

Node.js v4.2.3, mongoose 4.3.1, bluebird 3.0.6.

**Comment by vkarpov15** [comment]
IMO it's expected behavior: `.create()` returns a bluebird promise even if you pass a callback, so if that promise is rejected, bluebird will give you its usual "unhandled rejection" warning. You should just do `SomeModel.create({}).then().catch()` and then you won't get this warning.

**Comment by geronime** [comment]
Alright, thanks for explanation.

**Comment by geronime** [comment]
I may have found an issue related to Bluebird and unhandled rejection: In [schema/documentarray](https://github.com/Automattic/mongoose/blob/master/lib/schema/documentarray.js#L100) the validate is done using callback, therefore Bluebird will scream about unhandled rejection.

**Comment by ReedD** [comment]
I'm having a similar issue regarding `invalidate`. Below is a simplified example but basically if `invalidate` is called anywhere within the promise chain "Unhandled rejection" warnings show up in the console regardless of what I do (`catch` doesn't help). 

```
Schema.pre('validate', function (next) {
    return new Bluebird(function (resolve, reject) {
        self.invalidate(path, 'Error message');
        // .. More code 
    }).asCallback(next);
});
```

**Comment by vkarpov15** [comment]
Because when you return a value from `pre('validate');`, that is **not** the value that will be returned from `validate()`. Don't return bluebird promises from hooks and expect them to be caught.

**Comment by ReedD** [comment]
@vkarpov15 My previous example turns out to be a poor example, I have since figured out what causes my issue (but not why or how to fix it). It occurs when I add a nested schema to a parent schema. If validation fails within the nested schema, simply by _having_ the pre validate middleware present on the nested schema causes "Unhandled rejection" warnings. If I comment out that middleware then the warning goes away. Do you have any insight on why this happens?


```
var NestedSchema = new Schema({
    name: {
        type: String,
        required: 'Item name required',
        trim: true
    }
});

NestedSchema.pre('validate', function (next) {
    // By simply existing, this middleware causes
    // an "Unhandled rejection" output
    next();
});

var ContainerSchema = new Schema({
    name: {
        type: String,
        required: 'Name required',
        trim: true
    },
    items: [NestedSchema]
});

ContainerSchema.pre('validate', function (next) {
    // .. Some code
    // This middleware causes no issue
    next();
});
```

**Comment by vkarpov15** [comment]
Can you confirm which version of mongoose you're using @ReedD ?

**Comment by ReedD** [comment]
@vkarpov15 I'm using 4.3.6

**Comment by vkarpov15** [comment]
@ReedD the below script executes without error or warning for me on mongoose 4.3.6. Please modify it to reproduce your issue.

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');

mongoose.promise = require('bluebird');

mongoose.connect('mongodb://localhost:27017/gh3669');
var Schema = mongoose.Schema;
var NestedSchema = new Schema({
    name: {
        type: String,
        required: 'Item name required',
        trim: true
    }
});


NestedSchema.pre('validate', function (next) {
    // By simply existing, this middleware causes
    // an "Unhandled rejection" output
    next();
});

var Nested = mongoose.model('test', NestedSchema);

Nested.create({ name: 'test' }, function(error) {
  assert.ifError(error);
  process.exit(0);
});
```

**Comment by ReedD** [comment]
I believe your line `mongoose.promise = require('bluebird');` should actually be `mongoose.Promise = require('bluebird');` with a capital "P" in promise and in your example the nested schema isn't actually nested within another schema. Also, in order for the error to appear there must be a validation failure within the nested schema. Here is my modified example script:

```
'use strict';

var assert   = require('assert');
var mongoose = require('mongoose');
var Schema   = mongoose.Schema;

mongoose.Promise = require('bluebird');
mongoose.connect('mongodb://localhost:27017/gh3669');

var NestedSchema = new Schema({
  name: {
    type: String,
    required: 'Item name required',
    trim: true
  }
});

// ===========================================//
// Comment out this block to eliminate error
NestedSchema.pre('validate', function (next) {
  // By simply existing, this middleware causes
  // an "Unhandled rejection" output
  next();
});
// ===========================================//

var ContainerSchema = new Schema({
  name: {
    type: String,
    required: 'Name required',
    trim: true
  },
  items: [NestedSchema]
});

var Container = mongoose.model('test', ContainerSchema);

Container.create({
  name: 'name',
  items: [{
    name: null // Intentional Error
  }]
}).then(function () {
  console.log('Success');
}).catch(function (err) {
  console.error('Error', err);
}).finally(function () {
  mongoose.disconnect();
});
```
This will produce the following output to appear in the console:
```
Unhandled rejection ValidationError: test validation failed
    at MongooseError.ValidationError (/Users/reed/Dev/Playground/mongoose-bluebird-test/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/Users/reed/Dev/Playground/mongoose-bluebird-test/node_modules/mongoose/lib/document.js:1298:32)
    at EmbeddedDocument.invalidate (/Users/reed/Dev/Playground/mongoose-bluebird-test/node_modules/mongoose/lib/types/embedded.js:180:19)
    at /Users/reed/Dev/Playground/mongoose-bluebird-test/node_modules/mongoose/lib/document.js:1173:16
    at validate (/Users/reed/Dev/Playground/mongoose-bluebird-test/node_modules/mongoose/lib/schematype.js:662:7)
    at /Users/reed/Dev/Playground/mongoose-bluebird-test/node_modules/mongoose/lib/schematype.js:693:9
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/Users/reed/Dev/Playground/mongoose-bluebird-test/node_modules/mongoose/lib/schematype.js:667:19)
    at /Users/reed/Dev/Playground/mongoose-bluebird-test/node_modules/mongoose/lib/document.js:1171:9
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3
```
If you comment out lines 20 to 24, this error will disappear.
