### ISSUE TITLE
Better stack trace for async errors

### ISSUE THREAD

**Issue by liudangyi** [Automattic/mongoose#3692]
Currently when an error happens during async operations, mongoose throws an Error with stack trace like this

```
WriteError(...)
    at Function.MongoError.create (./node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (./node_modules/mongoose/node_modules/mongodb/lib/utils.js:114:22)
    at ./node_modules/mongoose/node_modules/mongodb/lib/collection.js:597:23
    at ./node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:469:9
    at resultHandler (./node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:416:5)
    at ./node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:778:13
    at [object Object].Callbacks.emit (./node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at [object Object].messageHandler (./node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (./node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

Which is totally useless. It would be better to show an application stack trace where the async function is called.

**Comment by vkarpov15** [comment]
One of the quirks of async code - stack traces for errors reported from a server are not terribly useful. IMO long stack traces are outside of the scope of mongoose, but you can use a module like [longjohn](https://www.npmjs.com/package/longjohn) to help you out.
