### ISSUE TITLE
"Cast to ObjectId failed" for custom ID and $elemMatch/$not

### ISSUE THREAD

**Issue by parisholley** [Automattic/mongoose#3719]
Here is an example schema

```
var child = new mongoose.Schema({
	_id: {type: String}
});

var parent = new mongoose.Schema({
	children: [child]
});

```
The following query has been abbreviated to exclude the non-relevant info (my query is quite large). When $elemMatch is used without $not, it works fine and can cast the _id. However, when placed within a $not{} tag, it tries to cast as ObjectID and fails.

```
model.find({
	$and: [{
		$or: [{
			$and: [
				{
					myField: {
						$not: {
							$elemMatch: {
								_id: 'customString'
							}
						}
					}
				}
			]
		}]
	}]
})
```

**Comment by vkarpov15** [comment]
Hmm that's strange, the below script executes without error for me against 4.3.4:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/gh3719');

var child = new mongoose.Schema({
    _id: {type: String}
});

var parent = new mongoose.Schema({
    children: [child]
});

var Parent = mongoose.model('Parent', parent);

Parent.create({ children: [{ _id: 'customString' }] }, function(error) {
  assert.ifError(error);
  test();
});

function test() {
  Parent.find({
      $and: [{
          $or: [{
              $and: [
                  {
                      myField: {
                          $not: {
                              $elemMatch: {
                                  _id: 'customString'
                              }
                          }
                      }
                  }
              ]
          }]
      }]
  }, function(error, docs) {
    assert.ifError(error);
    assert.ok(docs.length > 0);
    process.exit(0);
  });
}
```

```
$ node gh-3719.js 
Mongoose: parents.insert({ _id: ObjectId("568c46067ab8da0728640c4d"), children: [ { _id: 'customString' } ], __v: 0 })   
Mongoose: parents.find({ '$and': [ { '$or': [ { '$and': [ { myField: { '$not': { '$elemMatch': { _id: 'customString' } } } } ] } ] } ] }) { fields: undefined }
```

Can you check if the above script works for you and confirm which version of mongoose you're using?

**Comment by vkarpov15** [comment]
Issue's gone stale. Re-open if this is still an issue.

**Comment by timbowhite** [comment]
I'm able to reproduce this issue.  Popped up after upgrading from 3.28.x to 4.6.0.  Node v.6.5.0.  Example:

```js
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/gh3719');

var child = new mongoose.Schema({
    _id: {type: String}
}, {_id: false});

var parent = new mongoose.Schema({
  children: [child]
});

var Parent = mongoose.model('Parent', parent);

Parent.create({children: [{ _id: 'customString' }] }, function(error) {
  assert.ifError(error);
  test();
});

function test() {
  Parent.find({
      $and: [{children: {$not: {$elemMatch: {_id: 'foobar'}}}}]
  }, function(error, docs) {
    assert.ifError(error);
    assert.ok(docs.length > 0);
    process.exit();
  });
}
```
Yields:
```
Mongoose: parents.insert({ _id: ObjectId("57db6b41f3c2cb191aee60a1"), children: [ { _id: 'customString' } ], __v: 0 })
events.js:160
      throw er; // Unhandled 'error' event
      ^
CastError: Cast to ObjectId failed for value "foobar" at path "_id"
    at MongooseError.CastError (/.../node_modules/mongoose/lib/error/cast.js:26:11)
    at ObjectId.cast (/.../node_modules/mongoose/lib/schema/objectid.js:147:13)
    at ObjectId.castForQuery (/.../node_modules/mongoose/lib/schema/objectid.js:187:15)
    ...
```
The query works if the ```$not``` is removed, ie:
```js
$and: [{children: {$elemMatch: {_id: 'foobar'}}}]
```

**Comment by timbowhite** [comment]
Seems like possible fix could be changing line 206 of lib/cast.js from
```js
if ($cond === '$not') {
  cast(schema, nested);
} else {
```
to
```js
if ($cond === '$not') {
  cast(schematype.caster.schema, nested);
} else {
```

**Comment by timbowhite** [comment]
I think #4531 fixes this.
