### ISSUE TITLE
server socket closed

### ISSUE THREAD

**Issue by Grandiz** [Automattic/mongoose#3760]
About half year was everything ok, but today suddenly i get error sockets closed. 
I tried connect directly to db via command line, and connected successfully. 
Restart node forever process helps me, but still, i'm confused why it happened.
Would it be any change to fix this issue, reconnect how some or inform me about this issue via text notification

MongoError: server ds051602-a0.mongolab.com:51602 sockets closed
    at null.<anonymous> (/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:330:47)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:105:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:145:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:476:12)

**Comment by vkarpov15** [comment]
Take a look at #3588, there's a bunch of information related to this issue.
