### ISSUE TITLE
Got `No _id found on document!` when I save an ref.

### ISSUE THREAD

**Issue by linkeo** [Automattic/mongoose#3776]
I'm using population, and cannot saving refs.

Schema:

```js
var personSchema = Schema({
	_id: Number,
	name: String,
	age: Number,
	friends: [ {type: Number, ref: 'Person'} ]
});
var Person = mongoose.model('Person', personSchema);
```

Insert 2 people first: 

```js
var createOne = co.wrap(function* (person){
	var doc = new Person(person);
	yield doc.save();
});
co(function* (){
	yield createOne({_id: 0, name: 'Linkeo', age: 23});
	yield createOne({_id: 1, name: 'Danis', age: 24});
}).then(...)
```

And I got problem here:

```js
var addFriend = co.wrap(function* (usersId, friendsId) {
	var user = yield Person.findOne({_id: usersId}).exec();
	var friend = yield Person.findOne({_id: friendsId}).exec();
//      user.friends.push(friend._id); // A
	user.friends.push(friend); // B, but the same result as A
	log.debug(user.friends); // [1]
	yield user.save();
});

addFriend(0, 1).catch((err)=>{console.log('Internal error:', err, '\n', err.stack);});
```

Error output:
```
Internal error: [Error: No _id found on document!]
 Error: No _id found on document!
    at model._where [as $__where] (/Users/Linkeo/Project/checklist/node_modules/mongoose/lib/model.js:652:12)
    at model.Model.$__handleSave (/Users/Linkeo/Project/checklist/node_modules/mongoose/lib/model.js:158:24)
    at model.Model.$__save (/Users/Linkeo/Project/checklist/node_modules/mongoose/lib/model.js:189:9)
    at /Users/Linkeo/Project/checklist/node_modules/mongoose/lib/model.js:288:11
    at new Promise.ES6 (/Users/Linkeo/Project/checklist/node_modules/mongoose/lib/promise.js:45:3)
    at model.Model.save (/Users/Linkeo/Project/checklist/node_modules/mongoose/lib/model.js:287:10)
    ......
```

I think the reason is that `user.friends` should hold documents instead of numbers, but the code B above still cannot insert a document into `user.friends`

And this code works:

```js
var addFriend = co.wrap(function* (usersId, friendsId) {
	var user = yield Person.findOne({_id: usersId}).exec();
	var friend = yield Person.findOne({_id: friendsId}).exec();
	Array.prototype.push.call(user.friends, friend); // <- use Array's push function.
	log.debug(user.friends); // [ { friends: [], __v: 0, age: 24, name: 'Danis', _id: 1 } ]
	yield user.save();
});
addFriend(0, 1).catch((err)=>{console.log('Internal error:', err, err.stack);});
```

Obviously, it's not the correct usage.

Is there anyone can tell me the correct one?

**Comment by linkeo** [comment]
Ehh... if I use the last code above, I got no errors, but `user.save()` seems not works.

I call `Person.findOne({_id: 0})` later, and got: 

```js
{ friends: [], __v: 0, age: 23, name: 'Linkeo', _id: 0 }
```

**Comment by linkeo** [comment]
I tried to change type of `_id` to `ObjectId` and `String`, both worked.

Seems problem occurs only when call `push` from `Number` ref array.

BTW, I'm sorry that I have forgotten tell you the version:

```
node.js: v5.4.0
...
├─┬ mongoose@4.3.5
│ ├─┬ mongodb@2.1.2
...
```
