### ISSUE TITLE
Error when creating a partial index with an expression based on $ operators like $exists

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#3864]
```
summarySchema.index(
    { language: 1, author: 'text', tags: 'text', title: 'text', description:'text' },
    {
        partialFilterExpression: { published: { $exists: true }, discarded: { $exists: false } },
        weights: { author: 8, tags: 4, title: 2, description: 1 }
    }
);
```

throws:

```
Error: key $exists must not start with '$'
    at Error (native)
    at serializeInto (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:680:19)
    at serializeObject (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:280:18)
    at serializeInto (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:705:17)
    at serializeObject (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:280:18)
    at serializeInto (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:705:17)
    at serializeObject (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:280:18)
    at serializeInto (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:551:17)
    at serializeObject (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:280:18)
    at serializeInto (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\parser\serializer.js:705:17)
    at serialize (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\bson\lib\bson\bson.js:47:27)
    at Query.toBin (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\mongodb-core\lib\connection\commands.js:143:25)
    at executeSingleOperation (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\mongodb-core\lib\topologies\server.js:955:31)
    at Server.command (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\mongodb-core\lib\topologies\server.js:1038:3)
    at executeWrite (d:\WebStorm\Kidoju\Kidoju.Server\node_modules\mongodb-core\lib\wireprotocol\3_2_support.js:60:12)
```

but the following works:

```
summarySchema.index(
    { language: 1, author: 'text', tags: 'text', title: 'text', description:'text' },
    {
        partialFilterExpression: { published: { $exists: true } },
        weights: { author: 8, tags: 4, title: 2, description: 1 }
    }
);
```

It seems the culprit is ```{ $exists: false }```

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix

**Comment by jlchereau** [comment]
The issue seems to be with mongoDB (TBC), which for whatever reason, would not accept a partialFilterExpression on the non-existence of a field. Considering this is not documented, it is difficult to assess whether this is a bug or a limitation by design.

**Comment by vkarpov15** [comment]
Yep, looks like this also only affects mongodb 3.2. 3.0 works just fine.

**Comment by vkarpov15** [comment]
So this is indicative of a small bug in mongodb-core, however, even if we fix that, this won't work. MongoDB doesn't support `$exists: false` for partial indexes in 3.2: https://jira.mongodb.org/browse/SERVER-17853

**Comment by vkarpov15** [comment]
I opened up https://jira.mongodb.org/browse/DOCS-7122 to track this for the mongodb server docs

**Comment by vkarpov15** [comment]
Will bump to mongodb node driver 2.1.8 when its released for the above fix. Thanks for reporting. Just to clarify, you'll still get an error because [you can't use `$exists: false` in a partial index filter in 3.2](https://docs.mongodb.org/manual/core/index-partial/), but the error will actually clarify that it was an index build failure rather than an invalid insert.

**Comment by jlchereau** [comment]
Thx. J
