### ISSUE TITLE
update and $push causes RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by aartiles** [Automattic/mongoose#3890]
update and $push causes error `RangeError: Maximum call stack size exceeded` when the model has  embedded documents array with a property of type `Buffer`.

Test Case:
```
'use strict';
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var InfoSchema = new Schema({
  prop: {type: Buffer}
});

var ModelASchema = new Schema({
  info_list: {type : [InfoSchema]}
});

var ModelA = mongoose.createConnection('mongodb://localhost/test').model('ModelA', ModelASchema);

var propValue = new Buffer('aa267824dc1796f265ab47870e279780', 'base64');

ModelA.update(
  {
    _id: '55bba9056e17802c454af434'
  },
  {
    $push: {
      info_list: { prop: propValue }
    }
  },
  function(err) {
    if (err) console.log('Error', err);
    console.log('done!');
    process.exit();
  }
);
```

Stack trace:
```
node_modules/mongoose/lib/utils.js:0
(function (exports, require, module, __filename, __dirname) { /*!
^
RangeError: Maximum call stack size exceeded
```

Just changing the `prop` type to `String` makes it work
```
var InfoSchema = new Schema({
  prop: {type: String}
});
```

It fails with mongoose 4.4.4. It has been working until 4.1.2.
node version: 0.10.24
mongodb: 2.6

**Comment by vkarpov15** [comment]
On it, thanks for repro instructions.

**Comment by floriansimon1** [comment]
I'm using Mongoose 4.4.6 and I still have that exact same problem. Will downgrade for now.

Node: v5.7.0
Mongoose: 4.4.6
Mongodb: 2.1.7 
Server: 3.2.3

**Comment by aartiles** [comment]
It's working in my case with v4.4.6

**Comment by floriansimon1** [comment]
I don't have the same problem actually. Up to version 4.4.5 (just tested this now), my program works fine. If I upgrade to v4.4.6, I have this:

`/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:821
          obj = obj.toObject({ virtuals: false });
                   ^

RangeError: Maximum call stack size exceeded
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:821:20)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/vbk-web/node_modules/mongoose/lib/utils.js:823:17)
`

Not the same problem, but I think that the fix for this github issue caused my problem.

**Comment by floriansimon1** [comment]
I forgot to add: I have a buffer property in the model I'm trying to update. It's at the root level, not nested. I have a virtual property that refers to that buffer, though.

To be fair, I haven't tested all versions between 4.2.something all the way up to 4.4.6 manually, but since we have continous integration for this app, and I have manually observed the issue to occur between 4.4.5 and 4.4.6, I'm pretty confident in saying that the problem was created with 5b0fffd

**Comment by vkarpov15** [comment]
@floriansimon1 can you please open up a separate issue with a code sample?

**Comment by floriansimon1** [comment]
I can't promise anything but I'll try :)


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Valeri Karpov <notifications@github.com> 
Date : 08/03/2016  17:51  (GMT+01:00) 
À : Automattic/mongoose <mongoose@noreply.github.com> 
Cc : Florian Simon <florian@tentwentyfour.lu> 
Objet : Re: [mongoose] update and $push causes RangeError: Maximum call stack
  size exceeded (#3890) 

@floriansimon1 can you please open up a separate issue with a code sample?
