### ISSUE TITLE
A `post` attribute conflicts with an asynchronous post middleware

### ISSUE THREAD

**Issue by moongrate** [Automattic/mongoose#3902]
If I define a Schema with a `post` property and with an asynchronous post middleware, and then attempt to create a model instance, it fails with the following error:
```
TypeError: _this.post.apply is not a function
    at node_modules/mongoose/lib/document.js:1832:18
    at Array.forEach (native)
    at node_modules/mongoose/lib/document.js:1830:27
    at Array.forEach (native)
    at model.Document.$__registerHooksFromSchema (node_modules/mongoose/lib/document.js:1792:23)
    at model.Document (node_modules/mongoose/lib/document.js:76:8)
    at model.Model (node_modules/mongoose/lib/model.js:42:12)
    at new model (node_modules/mongoose/lib/model.js:3069:11)
    at node_modules/mongoose/lib/model.js:1758:22
```
Because the `_this.post` contains a `post` property value, not a middleware.

**Comment by vkarpov15** [comment]
Please provide a code sample, converting prose to code is error prone.

**Comment by moongrate** [comment]
```
var Schema = new mongoose.Schema({
    post: String
});

Schema.post('save', function(document, next) {
    return next();
});

var Model = mongoose.model('Model', Schema);

Model.create({post: 'test'}); // <-- TypeError: _this.post.apply is not a function
```
