### ISSUE TITLE
Can't debug CastError to save my life

### ISSUE THREAD

**Issue by brandonros** [Automattic/mongoose#3922]
```
CastError: Cast to embedded failed for value "[object Object]" at path "shipments"
    at MongooseError.CastError (/Users/Marketing/Desktop/node_modules/mongoose/lib/error/cast.js:19:11)
    at DocumentArray.cast (/Users/Marketing/Desktop/node_modules/mongoose/lib/schema/documentarray.js:244:19)
    at Query._castUpdateVal (/Users/Marketing/Desktop/node_modules/mongoose/lib/query.js:2423:22)
    at Query._walkUpdatePath (/Users/Marketing/Desktop/node_modules/mongoose/lib/query.js:2319:25)
    at Query._castUpdate (/Users/Marketing/Desktop/node_modules/mongoose/lib/query.js:2265:23)
    at Query.update (/Users/Marketing/Desktop/node_modules/mongoose/lib/query.js:2075:22)
    at Function.update (/Users/Marketing/Desktop/node_modules/mongoose/lib/model.js:1967:13)
```

```
var query = {
	'store_id': 'redacted',
	'order_number': 'redacted'
};

var update = {
	'$push': {
		'shipments': { 
			'$each': shipments 
		}
	}
};
```

**Comment by brandonros** [comment]
I'd include schema but any changes I make to it yield no difference. Changing the offending line to Mixed fixes everything, which isn't exactly what I'd want. How can I debug the CastError to be more verbose?

**Comment by vkarpov15** [comment]
Can you show me your schema please?

**Comment by vkarpov15** [comment]
Suspect this may be an issue with $each

**Comment by vkarpov15** [comment]
@brandonros below script executes without error for me. Can you please modify the below script to reproduce your error?

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/gh3922');

var storeSchema = mongoose.Schema({
  store_id: String,
  order_number: String,
  shipments: [{ to: String }]
}, {strict: "throw"});

var Store = mongoose.model('Store', storeSchema);

var shipments = [{ to: 'home' }, { to: 'work' }];

var update = {
  $push: {
    shipments: {
      $each: shipments
    }
  }
};

Store.update({ store_id: '1', order_number: '2' }, update, function(error) {
  assert.ifError(error);
  process.exit(0);
});
```

**Comment by vkarpov15** [comment]
Issue's been stale for a while, closing.
