### ISSUE TITLE
Passing model to aggregate $match clause causes RangeError

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#3947]
If one passes a model as a parameter for the `$match` clause for aggregation (as one could do for a Mongoose `find()` operation), Mongoose chokes with a RangeError.

E.g.

```js
User.aggregate([
   {$match: {club: club}}
]);
```

Causes:

```
RangeError: Maximum call stack size exceeded
    at Buffer.write (buffer.js:543:34)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:276:37)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject (node_modules/bson/lib/bson/parser/serializer.js:280:18)
```

To fix, one has to specify the ID explicitly, e.g.:

```js
User.aggregate([
   {$match: {club: club._id}}
]);
```

Took a while to figure this out, as the documentation is not clear on this and there is no clear error message. Perhaps Mongoose should handle this case and either throw a warning or just use the `_id` if the schema contains a reference to the model being passed in, as is done with `find()`.

**Comment by vkarpov15** [comment]
Call '.toObject()' before putting the object in the aggregation pipeline. A mongoose object is not just the fields you define in your schema, it has circular references. Also, mongoose does not cast any aggregation pipeline stages.

**Comment by adambuczynski** [comment]
Ok, thanks
