### ISSUE TITLE
 please print out connection stting in case of connection error

### ISSUE THREAD

**Issue by Ykid** [Automattic/mongoose#3958]
This is a feature request. I am using mongoose 4.3.4. My project contains multiple mongoose connections to different DBs. It would have helped a lot in debugging if the error log contains the connection string to indicate which connection goes wrong.

**Comment by vkarpov15** [comment]
What error are you seeing? Many connection errors are generated by the mongodb driver, so mongoose has no control over them.

**Comment by Ykid** [comment]
Does this mean it is from mongodb driver ?
```javascript
/www/node_modules/mongoose/node_modules/mongodb/lib/server.js:236
        process.nextTick(function() { throw err; })
                                            ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

**Comment by vkarpov15** [comment]
That error actually comes from core node. We can probably do a better job of attaching useful information to that error though.

**Comment by Ykid** [comment]
Thank you!

**Comment by Himanshu197200** [comment]
@vkarpov15 I know this is an older issue, but if it's still relevant, I'm interested in implementing it. could you please assign it to me?

**Comment by vkarpov15** [comment]
@Himanshu197200 thinking more about it, I'm going to close this issue as a won't fix. Including the connection string in error messages by default is a security risk, I don't think the benefits outweigh the potential risk of leaked connection strings via API or Sentry.
