### ISSUE TITLE
4.4.6 - $set-ting a buffer causes infinite recursion

### ISSUE THREAD

**Issue by floriansimon1** [Automattic/mongoose#3961]
Probably related to #3890 and its fix:

```javascript
const mongoose = require('mongoose');

const Schema   = mongoose.Schema;
const ObjectId = mongoose.Types.ObjectId;

const schema = {
  name: Buffer
};

const Model = mongoose.createConnection('mongodb://localhost/test').model('Model', schema);

const id       = ObjectId('55bba9056e17802c454af434');
const value    = new Buffer('aa267824dc1796f265ab47870e279780', 'base64');
const instance = new Model({ _id: id, name: null });

instance
.save()
.then(() => Model.update({ _id: id }, { $set: { name: value } }))
.then(
    () => console.log('OK!'),
    error => console.log('Error:', error, error.stack)
);
```
Here's what I get:

```
florian@zanzibar:/stuff/projects/test$ node ./test.js 
/stuff/projects/test/node_modules/mongoose/lib/utils.js:821
          obj = obj.toObject({ virtuals: false });
                   ^

RangeError: Maximum call stack size exceeded
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:821:20)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
    at Object.exports.mergeClone (/stuff/projects/test/node_modules/mongoose/lib/utils.js:823:17)
```

This was working up to version 4.4.5

**Comment by vkarpov15** [comment]
That's strange, this issue only happens if you use promises with `Model.update()`. If you want a quick workaround, the callback form seems to work...
