### ISSUE TITLE
Pushing nested doc into doc array set isNew to true

### ISSUE THREAD

**Issue by marchah** [Automattic/mongoose#3982]
Hi,

When push a nested doc into other doc array `isNew` automatically set to isNew === true

````javascript
'use strict';

const chai = require('chai');
const mongoose = require('mongoose');
const expect = chai.expect;

describe('creating wrapped model test case', () => {
  let NestedModel;
  let Model;

  let nestedModel;

  before((done) => {
    const NestedModelSchema = new mongoose.Schema({
      'field': String,
    });

    NestedModel = mongoose.model('NestedModel', NestedModelSchema);

    const ModelSchema = new mongoose.Schema({
      'field': String,
      'array': [{
        'type': mongoose.Schema.ObjectId,
        'ref': 'NestedModel',
        'required': true,
      }],
    });

    Model = mongoose.model('Model', ModelSchema);

    nestedModel = new NestedModel({
      'field': 'nestedModel',
    });

    nestedModel.save(done);
  });

  after(() => {
  });

  it('should be nestedModel.isNew === false (before)', () => {
    expect(nestedModel.isNew).to.be.false;
  });

  it('should copy data into new Model object and keep', () => {
    const model = new Model();

    model.field = 'model';
    model.array.push(nestedModel);

    expect(model.array[0].isNew).to.be.false;
  });

  it('should be nestedModel.isNew === false (after)', () => {
    expect(nestedModel.isNew).to.be.false;
  });
});
````

```
✓ should be nestedModel.isNew === false (before)
1) should copy data into new Model object and keep
✓ should be nestedModel.isNew === false (after)


  2 passing (93ms)
  1 failing

  1) Unit Testing -> Other -> creating wrapped model test case should copy data into new Model object and keep:
     AssertionError: expected undefined to be false
      at Context.<anonymous> (test/server/other/mongoose.isNew.spec.js:51:39)
```

When you call `push` Mongoose create a new doc to do a copy i guess but it doesn't copy everything.

Thanks for your help

**Comment by vkarpov15** [comment]
Actually if you take a look at the stack trace you'll see that mongoose doesn't copy the document at all:

```
AssertionError: expected undefined to be false
      at Context.<anonymous> (test/server/other/mongoose.isNew.spec.js:51:39)
```

`isNew` is undefined because if you take a look at the value of `model`, you'll see mongoose casts `nestedModel` to an ObjectId:

```
{ array: [ 56f4124b4cdb6bb07b590b41 ],
  _id: 56f4124b4cdb6bb07b590b42,
  field: 'model' }
```

See [the "Setting Populated Fields" section in the populate docs](http://mongoosejs.com/docs/populate.html) - `push()` on a document array converts the document to an objectid unless the array is already populated.

That being said, there's still a bug, and it's fixed in the above commit :)
