### ISSUE TITLE
TypeError: _this.collections[i].onOpen is not a function

### ISSUE THREAD

**Issue by muxahuk** [Automattic/mongoose#3987]
my code:
```
this.db = mongoose.createConnection( this.uri, this.configs.options );
```
error i'm getting: ( mongoose 4.4.7 )
```
TypeError: _this.collections[i].onOpen is not a function
    at open (C:\Projects\ragar-web-server\node_modules\mongoose\lib\connection.js:507:28)
    at NativeConnection.Connection.onOpen (C:\Projects\ragar-web-server\node_modules\mongoose\lib\connection.js:520:5)
    at C:\Projects\ragar-web-server\node_modules\mongoose\lib\connection.js:476:11
    at C:\Projects\ragar-web-server\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:60:5
    at C:\Projects\ragar-web-server\node_modules\mongodb\lib\db.js:227:5
    at connectHandler (C:\Projects\ragar-web-server\node_modules\mongodb\lib\server.js:286:7)
    at g (events.js:273:16)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\topologies\server.js:504:23
    at commandCallback (C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\topologies\server.js:936:9)
    at Callbacks.emit (C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\topologies\server.js:116:3)
    at null.messageHandler (C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\topologies\server.js:282:23)
    at Socket.<anonymous> (C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\connection\connection.js:273:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
C:\Projects\ragar-web-server\node_modules\mongodb\lib\server.js:289
      process.nextTick(function() { throw err; })
                                    ^

TypeError: _this.collections[i].onOpen is not a function
    at open (C:\Projects\ragar-web-server\node_modules\mongoose\lib\connection.js:507:28)
    at NativeConnection.Connection.onOpen (C:\Projects\ragar-web-server\node_modules\mongoose\lib\connection.js:520:5)
    at C:\Projects\ragar-web-server\node_modules\mongoose\lib\connection.js:476:11
    at C:\Projects\ragar-web-server\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:60:5
    at C:\Projects\ragar-web-server\node_modules\mongodb\lib\db.js:227:5
    at connectHandler (C:\Projects\ragar-web-server\node_modules\mongodb\lib\server.js:286:7)
    at g (events.js:273:16)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\topologies\server.js:504:23
    at commandCallback (C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\topologies\server.js:936:9)
    at Callbacks.emit (C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\topologies\server.js:116:3)
    at null.messageHandler (C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\topologies\server.js:282:23)
    at Socket.<anonymous> (C:\Projects\ragar-web-server\node_modules\mongodb-core\lib\connection\connection.js:273:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
```

mongod log:
```
2016-03-16T17:08:16.008+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:65173 #27 (1 connection now open)
2016-03-16T17:08:16.064+0200 I NETWORK  [conn27] end connection 127.0.0.1:65173 (0 connections now open)
```
Not sore what happened, updated modules to latest version. Tryed to connect, but forgot to open monod process. After opening - these error shows.

**Comment by muxahuk** [comment]
I found a bug.. I'm extending Object prototype globaly.. so the `i` is my custom function for Object.prototype...

**Comment by muxahuk** [comment]
if someone would have same problem here's my problem and how i solved it:
```
// crashed these:
Object.prototype.getClassNames = function() {
if( this._classNames ) return this._classNames;
		let names = [ this.constructor.name ];
		let test = Object.getPrototypeOf( this.constructor );
		while( test.name ) {
			names.push( test.name );
			test = Object.getPrototypeOf( test )
		}
		this._classNames = names;
		return names;
}
// fixed works:
// note that enumerable should be false here!
Object.defineProperty( Object.prototype, 'getClassNames', {
	value: function() {
		if( this._classNames ) return this._classNames;
		let names = [ this.constructor.name ];
		let test = Object.getPrototypeOf( this.constructor );
		while( test.name ) {
			names.push( test.name );
			test = Object.getPrototypeOf( test )
		}
		this._classNames = names;
		return names;
	}
} );
```

**Comment by BlazeSahlzen** [comment]
@muxahuk Thanks! I was facing the same issue.

I have one question: why does this happen? As in, why can't I extend `Object` in the other  way?

**Comment by muxahuk** [comment]
becouse in these library they are using something like `for( var i in obj )` and if u extend Object with custom function, these function becomes enumerable and in `for in` loop it's name is returned as `i`.
And they have bunch of code doing somthing with `i`.. Making function not enumerable hides it from `for in` loop,
