### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by justincy** [Automattic/mongoose#4000]
I can't tell if this warning, being raised by bluebird, is caused by me or Mongoose. So far as I can tell, I'm handling all promises and Mongoose appears to be too. I'm using the latest version of Mongoose `4.4.8`.

Stacktrace:

```
Warning: a promise was created in a handler but was not returned from it
    at Query.exec (/home/ubuntu/workspace/node_modules/mongoose/lib/query.js:2157:10)
    at module.exports.loadEntries (/home/ubuntu/workspace/middleware/middleware.js:108:18)
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:312:13)
    at /home/ubuntu/workspace/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:271:10)
    at /home/ubuntu/workspace/middleware/middleware.js:21:13
    at /home/ubuntu/workspace/services/cache.js:58:21
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /home/ubuntu/workspace/services/cache.js:42:11
    at NodeCache.module.exports.NodeCache.get (/home/ubuntu/workspace/node_modules/node-cache/lib/node_cache.js:82:13)
    at NodeCache.get (/home/ubuntu/workspace/node_modules/node-cache/lib/node_cache.js:3:59)
    at Object.module.exports.getContest (/home/ubuntu/workspace/services/cache.js:27:9)
    at module.exports.commonLocals (/home/ubuntu/workspace/middleware/middleware.js:11:15)
    at Layer.handle [as handle_request] (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:312:13)
    at /home/ubuntu/workspace/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:330:12)
    at Context.next (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:271:10)
    at Context.actions.pass (/home/ubuntu/workspace/node_modules/passport/lib/passport/context/http/actions.js:77:8)
    at /home/ubuntu/workspace/node_modules/passport/lib/passport/strategies/session.js:61:12
    at pass (/home/ubuntu/workspace/node_modules/passport/lib/passport/index.js:321:31)
    at /home/ubuntu/workspace/node_modules/passport/lib/passport/index.js:332:35
    at Query.<anonymous> (/home/ubuntu/workspace/config/passport.js:20:9)
    at /home/ubuntu/workspace/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /home/ubuntu/workspace/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

Relevant lines from `loadEntries`:

```js
Entry
    .find({
        user: req.session.passport.user,
        contest: res.locals.contest._id
    })
    .exec()
    .then(function(entries){
        console.log('entries', entries);
        req.session.entries = entries;
        next();
    })
    .catch(function(error){
        // TODO: how can we more gracefully handle this error?
        next(error);
    });
```

I can't tell if the "From previous event" part of the stack trace is relevant, so just in case here's the code from `cache.js`:

```js
Contest
  .find({
    start: { $lte: now },
    end: { $gte: now }
  })
  .populate('adGroups')
  .exec()
  .then(function(data){
    if(data && data.length > 0){
      
      // Use the smaller of the two: time to end of contest or default TTL
      // TTL is in seconds, contest end timestamp is in ms
      
      var ttl = CONTEST_TTL,
          contest = data[0],
          secondsToContestEnd = Math.floor((contest.end - Date.now())/1000);
      
      if(secondsToContestEnd < CONTEST_TTL){
        ttl = secondsToContestEnd;
      }
      
      cache.set('contest', contest, ttl);
      
      return callback(null, contest);
    } else {
      return callback(new Error('Unable to load contest'));
    }
  })
  .catch(function(error){
    callback(error);
  });
```

**Comment by Jeff-Lewis** [comment]
@justincy Make sure _every_ code path in a .then() and .catch() returns something or throws an _Error_. Calling just next() or callback() do nothing with the promise. Bluebird will give you that message until you return or throw an Error object instance.

Also, Bluebird's [asCallback](http://bluebirdjs.com/docs/api/ascallback.html) method is pretty useful if you are using promises inside regular callback functions.

``` javascript
Entry
    .find({
        user: req.session.passport.user,
        contest: res.locals.contest._id
    })
    .exec()
    .then(function(entries){
        console.log('entries', entries);
        req.session.entries = entries;
        return;  // it can be nothing, but you have to return.
    })
    .catch(function(error){
        // TODO: how can we more gracefully handle this error?
        // Throwing here will get turned into the next(error) by Bluebird 
        // when using .asCallback() at the end of your promise chain.
        console.error(error)
        throw error;
    }).asCallback(next);
```

**Comment by vkarpov15** [comment]
@justincy Jeff's insights are pretty spot on, as usual. Be careful about mixing callbacks and promises, things can get very hairy very quickly.

**Comment by justincy** [comment]
Thanks. I didn't really realize bluebird was being so picky. I figured that attaching a .then() or catch() was sufficient to handle a promise.

**Comment by vkarpov15** [comment]
Yeah bluebird is very defensive, which is why I usually don't like to use it except for maybe testing
