### ISSUE TITLE
TypeError: Cannot read property 'modify' of undefined

### ISSUE THREAD

**Issue by thebigredgeek** [Automattic/mongoose#4034]
This happened after bumping to the latest mongoose...

```
2016-04-01T17:07:41.496223+00:00 app[web.1]: Trace: [TypeError: Cannot read property 'modify' of undefined]
2016-04-01T17:07:41.496255+00:00 app[web.1]:     at /app/app/controllers/signups.js:125:13
2016-04-01T17:07:41.496256+00:00 app[web.1]:     at model.<anonymous> (/app/node_modules/mongoose/lib/document.js:1818:20)
2016-04-01T17:07:41.496257+00:00 app[web.1]:     at next_ (/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:89:34)
2016-04-01T17:07:41.496258+00:00 app[web.1]:     at fnWrapper (/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
2016-04-01T17:07:41.496259+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:292:13
2016-04-01T17:07:41.496259+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:227:5
2016-04-01T17:07:41.496260+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:167:9
2016-04-01T17:07:41.496261+00:00 app[web.1]:     at wrappedCallback (/app/node_modules/newrelic/lib/instrumentation/mongodb.js:215:25)
2016-04-01T17:07:41.496261+00:00 app[web.1]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
2016-04-01T17:07:41.496262+00:00 app[web.1]:     at wrappedCallback (/app/node_modules/newrelic/lib/transaction/tracer/index.js:417:66)
2016-04-01T17:07:41.496263+00:00 app[web.1]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
2016-04-01T17:07:41.496264+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:96:12)
2016-04-01T17:07:41.496264+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/collection.js:1006:5
2016-04-01T17:07:41.496265+00:00 app[web.1]:     at commandCallback (/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:936:9)
2016-04-01T17:07:41.496266+00:00 app[web.1]:     at Callbacks.emit (/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:116:3)
2016-04-01T17:07:41.496267+00:00 app[web.1]:     at null.messageHandler (/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:282:23)
2016-04-01T17:07:41.496267+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:273:22)
2016-04-01T17:07:41.496268+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-04-01T17:07:41.496269+00:00 app[web.1]:     at Socket.emit (events.js:169:7)
2016-04-01T17:07:41.496270+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:146:16)
2016-04-01T17:07:41.496270+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:110:10)
2016-04-01T17:07:41.496271+00:00 app[web.1]:     at TCP.onread (net.js:523:20)
```

The first point in the stack trace looks like this (`analytics-node#track`, from segment), where candidate is a model instance:

```
analytics.track({
  userId: candidate._id.toString(),
  event: 'API_CANDIDATE_COMPLETE_SIGNUP',
  properties: {
    _source: 'API',
    email: candidate.email,
    location: candidate.location,
    desired_locations: candidate.desired_locations,
    entered_linkedin: !!candidate.linkedin_url,
    desired_location_remote: !!candidate.desired_location_remote,
    desired_location_agnostic: !!candidate.desired_location_agnostic,
    desired_salary: candidate.desired_salary,
    uscis_authorized: !!candidate.uscis_authorized
  }
});
```

If I comment this block out, I the error doesn't occur... I almost feel like it is coming from `candidate._id.toString()`...

It looks like, on our most recent heroku deploy (last night), we probably pulled down this:

https://github.com/Automattic/mongoose/commit/b12d4efa2a687cb7695d0a23add59ee9778df574#diff-f412f4722a52cf22ed3d0a9a694b837dR710

Which clearly has something to do with the language "modify" haha.  Any ideas?

**Comment by vkarpov15** [comment]
I don't see how that commit could contribute to this issue. I also don't really see how that track call could be contributing to this issue, there's no reference to a modify property there...

**Comment by stephengardner** [comment]
+1 @thebigredgeek I'm getting this error, were you able to clarify what happened?

**Comment by vkarpov15** [comment]
@stephengardner please provide code samples or any additional info you may have

**Comment by samheutmaker** [comment]
I was able to solve this error by making a copy of the object whose properties are used as values in the traits object with Object.assign()
