### ISSUE TITLE
When collection has field "pre" or "post", an Exception occurred.

### ISSUE THREAD

**Issue by iniyk** [Automattic/mongoose#4045]
A document like this:
```javascript
{
                pre:
                    [

                        ["ASIAN"],
                        ["BLACK"],
                        ["Brooklyn"],
                        ["HISPANIC"],
                        ["New York"],
                        ["New York"],
                        ["NON-MINORITY"],
                        ["NON-MINORITY"],
                        ["WBE"],
                        ["WBE"]
                    ],
                post:
                    [
                        ["MBE"],
                        ["MBE"],
                        ["MBE"],
                        ["MBE"],
                        ["MBE"],
                        ["WBE"],
                        ["WBE"],
                        ["WBE"],
                        ["NON-MINORITY"],
                        ["NON-MINORITY"]
                    ],
                confidence:
                    [
                        '0.577565632458234',
                        '0.594272076372315',
                        '0.628318584070796',
                        '0.674698795180723',
                        '0.740740740740741',
                        '0.989547038327526',
                        '1',
                        '1',
                        '1',
                        '1'
                    ]
            }
```
Will raise an exception:

```javascript
/Users/iniyk/Desktop/git/blask/node_modules/mongoose/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: _this.pre.apply is not a function
    at /Users/iniyk/Desktop/git/blask/node_modules/mongoose/lib/document.js:1827:17
    at Array.forEach (native)
    at /Users/iniyk/Desktop/git/blask/node_modules/mongoose/lib/document.js:1825:26
    at Array.forEach (native)
    at model.Document.$__registerHooksFromSchema (/Users/iniyk/Desktop/git/blask/node_modules/mongoose/lib/document.js:1791:23)
    at model.Document (/Users/iniyk/Desktop/git/blask/node_modules/mongoose/lib/document.js:76:8)
    at model.Model (/Users/iniyk/Desktop/git/blask/node_modules/mongoose/lib/model.js:44:12)
    at new model (/Users/iniyk/Desktop/git/blask/node_modules/mongoose/lib/model.js:3024:11)
```

It seems like the name "pre" and "post" are used as a function name in mongoose Model, could it be fixed?

**Comment by vkarpov15** [comment]
Which version of mongoose are you using? This was fixed in 4.4.7 with #3902.
