### ISSUE TITLE
Model.update with overwrite:true throws an error from versions 4.1.10 to 4.4.11

### ISSUE THREAD

**Issue by luileito** [Automattic/mongoose#4054]
It seems there has been a regression issue. Now `Model.findByIdAndUpdate(id, obj, { overwrite: true })` throws an error when updating properties that are array of objects.

The document sample I'm using is the following:

```
var res = {
  user: "John"
  resources: [{
    foo: 1
  }, {
    bar: 2
  }]
}
```

Then `Model.findByIdAndUpdate(doc._id, res, { overwrite: true })`  throws:

```
"MongoError: exception: Invalid modifier specified: resources"
```

This is happening from versions 4.1.11 to the latest release (4.4.11).

**Comment by vkarpov15** [comment]
@luileito can you provide some more insight into what your schema looks like? The below script works fine for me in 4.4.11 and 4.4.12:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4054');
mongoose.set('debug', true);

var testSchema = new mongoose.Schema({
  user: String,
  resources: [{ foo: String, bar: String }]
});   

var TestModel = mongoose.model('gh4054', testSchema);
var options = { overwrite: true };
var update = {
  user: 'John',
  resources: [
    { foo: 1 },
    { bar: 2 }
  ]     
};    

TestModel.create({ user: 'Val' }, function(error, doc) {
  assert.ifError(error);

  TestModel.findByIdAndUpdate(doc._id, update, options).
    exec(function(error) {
      assert.ifError(error);

      process.exit(0);
    });   
});
```

**Comment by luileito** [comment]
Hi, the thing is that `resources` can hold an arbitrary number of objects, so the Schema looks like:
```
var testSchema = new mongoose.Schema({
  user: String,
  resources: Array
});
```
Also the problem arises when replacing the whole `resources` array, so your script should test for:
```
TestModel.create({ user: 'Val', resources: [{ hi: "There" }] }, ...
```
Thanks for looking into this.

**Comment by vkarpov15** [comment]
Hmm can you clarify which version of mongodb you're using? The below script also works fine for me:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4054');
mongoose.set('debug', true);

var testSchema = new mongoose.Schema({
  user: String,
  resources: Array
});

var TestModel = mongoose.model('gh4054', testSchema);
var options = { overwrite: true };
var update = {
  user: 'John',
  resources: [
    { foo: 1 },
    { bar: 2 }
  ]
};

TestModel.create({ user: 'Val', resources: [{ hi: 'there' }] }, function(error, doc) {
  assert.ifError(error);

  TestModel.findByIdAndUpdate(doc._id, update, options).
    exec(function(error) {
      assert.ifError(error);
      console.log('done');
      process.exit(0);
    });
});
```

**Comment by luileito** [comment]
I'm using MongoDB 2.6.10. 

FYI, for some reason your example works fine for me, too. Then I guess the problem should be elsewhere.

**Comment by vkarpov15** [comment]
That's strange. Let me know if you manage to reproduce the issue - I suspect you're re-using a query somewhere or accidentally putting a key that starts with `$` somewhere.

**Comment by vkarpov15** [comment]
Issue's gone stale, re-open if there is still an issue.

**Comment by fiws** [comment]
traced this issue down to the root of the problem. 
`overwrite` breaks if you use the `timestamps` option for a Schema.

Example:
```js
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4054');
mongoose.set('debug', true);

var testSchema = new mongoose.Schema({
  user: String,
  something: Number
}, { timestamps: true }); // ← that's the problem

var TestModel = mongoose.model('gh4054', testSchema);
var options = { overwrite: true, upsert: true };
var update = {
  user: 'John',
  something: 1,
};

TestModel.update({ name: 'test' }, update, options, function(error, doc) {
  assert.ifError(error);
  console.log(doc);
});
```

## Result

```shell
❯ node test
Mongoose: gh4054.update({ name: 'test' }, { '$set': { updatedAt: new Date("Thu, 24 Nov 2016 20:23:26 GMT") }, '$setOnInsert': { createdAt: new Date("Thu, 24 Nov 2016 20:23:26 GMT") }, user: 'John', something: 1 }, { upsert: true, overwrite: true })

events.js:160
      throw er; // Unhandled 'error' event
      ^
MongoError: Unknown modifier: user
    at Function.MongoError.create (/opt/exthome/fiws/Projects/hapi-forest/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/opt/exthome/fiws/Projects/hapi-forest/node_modules/mongodb/lib/utils.js:115:22)
    at /opt/exthome/fiws/Projects/hapi-forest/node_modules/mongodb/lib/collection.js:1046:67
    at /opt/exthome/fiws/Projects/hapi-forest/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
🔚  
```

**Comment by guischdi** [comment]
This error still happens if the `overwrite`, `upsert` and `setDefaultsOnInsert` options are present at `.update()` options:

## Example
```
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4054');
mongoose.set('debug', true);

var testSchema = new mongoose.Schema({
  name: String,
  something: { type: Number, default: 2 },
});

var TestModel = mongoose.model('gh4054', testSchema);
var options = { overwrite: true, upsert: true, setDefaultsOnInsert: true }; // ← this combination is the problem
var update1 = {
  name: 'test',
  something: 1,
};
var update2 = {
  name: 'test',
};

TestModel.update({ name: 'a' }, update1, options, function (error, raw) {
  assert.equal(raw.ok, 1);
  assert.equal(raw.nModified, 0);
  assert.equal(raw.n, 1);
  assert.equal(raw.upserted.length, 1);
  TestModel.update({ name: 'b'}, update2, options, function (error, raw) {
    assert.ifError(error);
  });
});
```

## Result

```
❯ node test
Mongoose: gh4054.update({ name: 'a' }, { name: 'test', something: 1, __v: 0 }, { setDefaultsOnInsert: true, upsert: true, overwrite: true })
Mongoose: gh4054.update({ name: 'b' }, { '$setOnInsert': { something: 2 }, name: 'test', __v: 0 }, { setDefaultsOnInsert: true, upsert: true, overwrite: true })

events.js:182
      throw er; // Unhandled 'error' event
      ^
MongoError: Unknown modifier: name
    at Function.MongoError.create (/Users/guischdi/mongoosetest/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/Users/guischdi/mongoosetest/node_modules/mongoose/node_modules/mongodb/lib/utils.js:139:22)
    at /Users/guischdi/mongoosetest/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1060:67
    at /Users/guischdi/mongoosetest/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```
