### ISSUE TITLE
'mangoose' is not in the npm registry.

### ISSUE THREAD

**Issue by alikhil** [Automattic/mongoose#4110]
When I am trying to install mangoose I am getting this error:
```
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "B:\\Program Files\\nodejs\\node.exe" "B:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mangoose"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/mangoose
npm ERR! 404
npm ERR! 404  'mangoose' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     M:\GitFiles\nodejs\project\npm-debug.log
```
npm-debug.log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'B:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'B:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'mangoose' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData mangoose
8 silly fetchNamedPackageData mangoose
9 silly mapToRegistry name mangoose
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/mangoose
13 verbose request uri https://registry.npmjs.org/mangoose
14 verbose request no auth needed
15 info attempt registry request try #1 at 09:54:39
16 verbose request id 47acac5c6994f6bf
17 http request GET https://registry.npmjs.org/mangoose
18 http 404 https://registry.npmjs.org/mangoose
19 verbose headers { 'content-type': 'application/json',
19 verbose headers   'cache-control': 'max-age=0',
19 verbose headers   'content-length': '2',
19 verbose headers   'accept-ranges': 'bytes',
19 verbose headers   date: 'Sat, 30 Apr 2016 06:54:39 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   age: '0',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-ams4126-AMS',
19 verbose headers   'x-cache': 'MISS',
19 verbose headers   'x-cache-hits': '0',
19 verbose headers   'x-timer': 'S1461999279.149462,VS0,VE679',
19 verbose headers   vary: 'Accept-Encoding' }
20 silly get cb [ 404,
20 silly get   { 'content-type': 'application/json',
20 silly get     'cache-control': 'max-age=0',
20 silly get     'content-length': '2',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Sat, 30 Apr 2016 06:54:39 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     age: '0',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-ams4126-AMS',
20 silly get     'x-cache': 'MISS',
20 silly get     'x-cache-hits': '0',
20 silly get     'x-timer': 'S1461999279.149462,VS0,VE679',
20 silly get     vary: 'Accept-Encoding' } ]
21 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/mangoose
21 silly fetchPackageMetaData     at makeError (B:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
21 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (B:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:242:14)
21 silly fetchPackageMetaData     at Request._callback (B:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
21 silly fetchPackageMetaData     at Request.self.callback (B:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
21 silly fetchPackageMetaData     at emitTwo (events.js:100:13)
21 silly fetchPackageMetaData     at Request.emit (events.js:185:7)
21 silly fetchPackageMetaData     at Request.<anonymous> (B:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1035:10)
21 silly fetchPackageMetaData     at emitOne (events.js:95:20)
21 silly fetchPackageMetaData     at Request.emit (events.js:182:7)
21 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (B:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:962:12)
21 silly fetchPackageMetaData  error for mangoose { [Error: Registry returned 404 for GET on https://registry.npmjs.org/mangoose] pkgid: 'mangoose', statusCode: 404, code: 'E404' }
22 silly rollbackFailedOptional Starting
23 silly rollbackFailedOptional Finishing
24 silly runTopLevelLifecycles Starting
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/mangoose
27 verbose stack     at makeError (B:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (B:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:242:14)
27 verbose stack     at Request._callback (B:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
27 verbose stack     at Request.self.callback (B:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
27 verbose stack     at emitTwo (events.js:100:13)
27 verbose stack     at Request.emit (events.js:185:7)
27 verbose stack     at Request.<anonymous> (B:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1035:10)
27 verbose stack     at emitOne (events.js:95:20)
27 verbose stack     at Request.emit (events.js:182:7)
27 verbose stack     at IncomingMessage.<anonymous> (B:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:962:12)
28 verbose statusCode 404
29 verbose pkgid mangoose
30 verbose cwd M:\GitFiles\nodejs\debts-telegram-bot
31 error Windows_NT 10.0.10240
32 error argv "B:\\Program Files\\nodejs\\node.exe" "B:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mangoose"
33 error node v5.6.0
34 error npm  v3.6.0
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/mangoose
37 error 404
38 error 404 'mangoose' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]

```

**Comment by nasr18** [comment]
its not `mangoose`. It's `mongoose`. @alikhil

**Comment by alikhil** [comment]
@nasr18 Thank you! XD

**Comment by baggavarinder** [comment]
**when I am trying to install bitgo using " npm install -D @types/bitgo it gives me following error:**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@types/bitgo' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 59b48fa9f7cb3d6e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@types%2fbitgo 1568ms
8 silly fetchPackageMetaData error for @types/bitgo@latest 404 Not Found: @types/bitgo@latest
9 verbose stack Error: 404 Not Found: @types/bitgo@latest
9 verbose stack     at fetch.then.res (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd E:\NicolasApi\Api
11 verbose Windows_NT 10.0.15063
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@types/bitgo"
13 verbose node v8.9.1
14 verbose npm  v5.5.1
15 error code E404
16 error 404 Not Found: @types/bitgo@latest
17 verbose exit [ 1, true ]

**Comment by sabaikanwal** [comment]
i don't understand this how can i solve this problem
