### ISSUE TITLE
Cannot read property 'getters', 'models', 'states' of undefined

### ISSUE THREAD

**Issue by stephengardner** [Automattic/mongoose#4123]
Here's an example error I received:
`TypeError: Cannot read property 'getters' of undefined
    at model.Object.defineProperty.get [as searches] (C:\....\node_modules\mongoose\lib\document.js:1576:22)
at assignValue (C:\....\node_modules\lodash\lodash.js:2311:28)
at C:\....\node_modules\lodash\lodash.js:2460:9
at arrayEach (C:\....\node_modules\lodash\lodash.js:498:11)
at baseClone (C:\....\node_modules\lodash\lodash.js:2455:7)
at C:\....\node_modules\lodash\lodash.js:2460:34
at arrayEach (C:\....\node_modules\lodash\lodash.js:498:11)
at baseClone (C:\....\node_modules\lodash\lodash.js:2455:7)
at C:\....\node_modules\lodash\lodash.js:2460:34
at arrayEach (C:\....\node_modules\lodash\lodash.js:498:11)
at baseClone (C:\....\node_modules\lodash\lodash.js:2455:7)
at C:\....\node_modules\lodash\lodash.js:2460:34
at arrayEach (C:\....\node_modules\lodash\lodash.js:498:11)
at baseClone (C:\....\node_modules\lodash\lodash.js:2455:7)
at C:\....\node_modules\lodash\lodash.js:2460:34
at arrayEach (C:\....\node_modules\lodash\lodash.js:498:11)
at baseClone (C:\....\node_modules\lodash\lodash.js:2455:7)
at C:\....\node_modules\lodash\lodash.js:2460:34
at arrayEach (C:\....\node_modules\lodash\lodash.js:498:11)
at baseClone (C:\....\node_modules\lodash\lodash.js:2455:7)
at baseMergeDeep (C:\....\node_modules\lodash\lodash.js:3283:24)
at C:\....\node_modules\lodash\lodash.js:3218:11
at arrayEach (C:\....\node_modules\lodash\lodash.js:498:11)
at baseMerge (C:\....\node_modules\lodash\lodash.js:3211:7)
at C:\....\node_modules\lodash\lodash.js:12486:7
at Function.<anonymous> (C:\....\node_modules\lodash\lodash.js:4280:13)
at Function.merge (C:\....\node_modules\lodash\lodash.js:9873:31)
at C:\....\server\my_module:84:22)`

Though in the past I've received the error for `states`, and 'models'.

I'm running Mongoose 4.4.14, Mongodb 2.1.11, and lodash 4.11.1 (All upt--date version as of today's date).

The problem occurs when I attempt to use lodash to `merge` from a mongoose document into a new object, _without_ calling document.toObject().

ex:
```javascript
	function doSomething(populatedUserDocument) {
		return new Promise(function(resolve, reject){
			var newParams = {
				data : {
                    // error occurs here
					name : _.merge({}, populatedUserDocument.name) // { first : 'something', last : 'somethingElse'}
				}
			};
			var newDocument = new someOtherModel(newParams);
			newDocument.save(function(err, saved) {
				if(err) return reject(err);
				return resolve(saved)
			});
		})
	}
```

The problem can be rectified by calling `document.toObject()` before performing the `_.merge`
ex: `populatedUserDocument = populatedUserDocument.toObject()`

I believe this is a new issue as I've kept the same code and have not run into this issue before.  This brought down a significant portion of our app.  I saw someone else with a similar recent issue open but they needed more clarification.

**Comment by vkarpov15** [comment]
Yeah mongoose documents have a lot of internal state that really doesn't lend itself well to copying. Use .toObject()
