### ISSUE TITLE
CastError on findOneAndUpdate

### ISSUE THREAD

**Issue by spamguy** [Automattic/mongoose#4130]
Assume this schema: https://github.com/spamguy/diplomacy/blob/master/server/models/region.js

I ran this:

```
mongoose.model('Season').findOneAndUpdate({
        _id: ObjectId(...),
        'regions.r': 'WAR'
    }, { $set: { 'regions.$.unit.order': { action: 'hold' } } }, { new: true }, callback);
```

I've executed the equivalent in shell with no complaints. In mongoose, the result was this error:

```
error:  CastError: Cast to undefined failed for value "[object Object]" at path "regions"
    at MongooseError.CastError (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/error/cast.js:19:11)
    at SchemaArray.cast (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/schema/array.js:161:15)
    at SchemaArray.cast (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/schema/array.js:172:15)
    at Query._castUpdateVal (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/query.js:2454:22)
    at Query._walkUpdatePath (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/query.js:2365:27)
    at Query._castUpdate (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/query.js:2296:23)
    at castDoc (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/query.js:2500:18)
    at Query._findAndModify (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/query.js:1755:17)
    at Query._findOneAndUpdate (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/query.js:1622:8)
    at /Users/spamguy/src/diplomacy/node_modules/kareem/index.js:156:8
    at args (/Users/spamguy/src/diplomacy/node_modules/kareem/index.js:71:20)
    at Query.<anonymous> (/Users/spamguy/src/diplomacy/node_modules/mongoose-timestamp/index.js:67:2)
    at next (/Users/spamguy/src/diplomacy/node_modules/kareem/index.js:82:14)
    at Kareem.execPre (/Users/spamguy/src/diplomacy/node_modules/kareem/index.js:99:3)
    at Kareem.wrap (/Users/spamguy/src/diplomacy/node_modules/kareem/index.js:146:8)
    at Query._findOneAndUpdate (/Users/spamguy/src/diplomacy/node_modules/kareem/index.js:188:11)
    at Query.findOneAndUpdate (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/query.js:1611:15)
    at Function.Model.findOneAndUpdate (/Users/spamguy/src/diplomacy/node_modules/mongoose/lib/model.js:1491:13)
    at SeasonCore.setOrder (/Users/spamguy/src/diplomacy/server/cores/season.core.js:183:30)
    at /Users/spamguy/src/diplomacy/server/controllers/season.controller.js:82:33
    at fn (/Users/spamguy/src/diplomacy/node_modules/async/lib/async.js:746:34)
    at /Users/spamguy/src/diplomacy/node_modules/async/lib/async.js:1213:16
```

Now, I don't think this error is quite accurate. When I debug, the actual throw is triggered in array.js, line 161, and the real error is 'TypeError: this.caster.cast is not a function'.

**Comment by vkarpov15** [comment]
What does a SeasonSchema look like again?

**Comment by spamguy** [comment]
Oops, sorry.

https://github.com/spamguy/diplomacy/blob/master/server/models/season.js

**Comment by vkarpov15** [comment]
Hmm that's odd, below script works fine for me with mongoose 4.4.15:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4130');
mongoose.set('debug', true);

var ts = require('mongoose-timestamp');

var OrderSchema = new mongoose.Schema({
    source: String,
    target: String,
    action: String,
    failed: {
        type: Boolean,
        default: false
    },
    details: String
}, { _id: false });

var UnitSchema = new mongoose.Schema({
    type: {
        type: String
    },
    owner: String,
    order: OrderSchema
}, { _id: false });

var RegionSchema = new mongoose.Schema({
    r: String,
    unit: UnitSchema,
    dislodged: UnitSchema,
    sc: String
}, { _id: false });
RegionSchema.add({ sr: [ RegionSchema ] });

var SeasonSchema = new mongoose.Schema({
        game_id: mongoose.Schema.Types.ObjectId,
        year: Number,
        season: String,
        deadline: Date,
        regions: [ RegionSchema ]
    });

SeasonSchema.plugin(ts);

var Season = mongoose.model('Season', SeasonSchema);

Season.findOneAndUpdate({ 'regions.r': 'WAR' }, { $set: { 'regions.$.unit.order': { action: 'hold' } } }, { new: true }, function(error) {
  assert.ifError(error);
  console.log('done');
  process.exit(0);
});
```

```
$ node gh-4130.js 
Mongoose: seasons.findAndModify({ 'regions.r': 'WAR' }) [] { '$setOnInsert': { createdAt: new Date("Mon, 09 May 2016 15:36:01 GMT") }, '$set': { 'regions.$.unit.order': { action: 'hold', failed: false }, updatedAt: new Date("Mon, 09 May 2016 15:36:01 GMT") } } { new: true, upsert: false, remove: false }
done
$
```

Can you see if you can modify the above script to repro your issue?

**Comment by spamguy** [comment]
Deleted node_modules and reinstalled before retrying.

The only difference I see is the absence of '_id' in the selection constraints. Commenting that out didn't fix anything. This is dataset-agnostic, right?

I'll start commenting out schema bits until it goes away, then report back. The path 'regions' wouldn't be referencing the query constraint or the $set object, right?

Thanks for taking a look.

**Comment by spamguy** [comment]
Got it. Whatever I was exporting in region.js was not a region schema. Consolidating schemata into one file fixed the problem. This isn't a problem, since the season schema will be the only one using it really. Sorry for the extra ticket!

**Comment by vkarpov15** [comment]
Np glad you found the issue :)
