### ISSUE TITLE
Document Javascript type can be undefined in utils.toObject

### ISSUE THREAD

**Issue by brundonsmith** [Automattic/mongoose#4152]
Here's the stack trace:
```
TypeError: Expecting a function in instanceof check, but got undefined
    at Object.toObject (/Users/brundon/git/material-cms/node_modules/mongoose/lib/utils.js:419:22)
    at Query.find (/Users/brundon/git/material-cms/node_modules/mongoose/lib/query.js:1078:22)
    at new Query (/Users/brundon/git/material-cms/node_modules/mongoose/lib/query.js:68:10)
    at Function.find (/Users/brundon/git/material-cms/node_modules/mongoose/lib/model.js:1147:12)
    at module.exports.search (/Users/brundon/git/material-cms/rest-routes/collections.js:45:78)
    at Layer.handle [as handle_request] (/Users/brundon/git/material-cms/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/brundon/git/material-cms/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/brundon/git/material-cms/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/brundon/git/material-cms/node_modules/express/lib/router/layer.js:95:5)
    at /Users/brundon/git/material-cms/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/brundon/git/material-cms/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/brundon/git/material-cms/node_modules/express/lib/router/index.js:271:10)
    at Immediate.<anonymous> (/Users/brundon/git/material-cms/node_modules/express-session/index.js:432:7)
    at Immediate.immediate._onImmediate (timers.js:440:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

And `collections.js:45`:
```
var query = mongooseConnections[req.sessionID].models[req.query.modelName].find( { } );
```

As you can see I'm doing something a little funky, which is probably why I find myself in this edge case. I'm creating Mongoose connections per user session and storing them in `mongooseConnections[req.sessionID].connection`, with its models stored in `mongooseConnections[req.sessionID].models`, keyed by their names.

I believe this is a bug because I was able to fix it with what seems pretty clearly to be a nondestructive change. Copying the line:
```
Document || (Document = require('./document'));
```
from `utils.isMongooseObject`, and adding it at the top of `utils.toObject`, fixes the issue as far as I can tell. The only reason I'm not making a pull request is because I've never looked at the mongoose codebase before an hour ago, and don't know for sure there won't be unexpected side effects from this change.

Mongoose v4.4.10, Mongo v3.0.10

**Comment by vkarpov15** [comment]
Thanks for pointing this out, that's a silly bug on mongoose's part.
