### ISSUE TITLE
Wrong error returned when creating subdocument with empty _id

### ISSUE THREAD

**Issue by ztrange** [Automattic/mongoose#4156]
having a subschema defined like this:

```
let Subdocument = new Schema({
  name: String
})

export default Subdocument
```

and using it on a schema like this:

```
import Subdocument from './sub'

let MainSchema = new Schema({
  name: Name,
  subdocs: {
    type: [Subdocument]
  }
})
export default mongoose.model('Customer', MainSchema)
```

And then trying to insert a subdocument like this: 

```
let sub = customer.subdocs.create(this.req.body)
```

where this.req.body contains: 
```
{
"_id": "",
"name": "Alice"
}
```

the reported error is:
```
  Error: Unable to invalidate a subdocument that has not been added to an array.
      at EmbeddedDocument.invalidate (C:\Users\me\github\myproject\node_modules\mongoose\lib\types\embedded.js:178:11)
      at EmbeddedDocument.Document.set (C:\Users\me\github\myproject\node_modules\mongoose\lib\document.js:677:10)
      at EmbeddedDocument.Document.set (C:\Users\me\github\myproject\node_modules\mongoose\lib\document.js:526:18)
      at EmbeddedDocument.Document (C:\Users\me\github\myproject\node_modules\mongoose\lib\document.js:62:10)
      at new EmbeddedDocument (C:\Users\me\github\myproject\node_modules\mongoose\lib\types\embedded.js:30:12)
      at EmbeddedDocument (C:\Users\me\github\myproject\node_modules\mongoose\lib\schema\documentarray.js:26:17)
      at Array.MongooseDocumentArray.mixin.create (C:\Users\me\github\myproject\node_modules\mongoose\lib\types\documentarray.js:204:12)
      at Object.add (customer.js:11:44)
      at [object Generator].next (native)
      at onFulfilled (C:\Users\me\github\myproject\node_modules\koa\node_modules\co\index.js:65:19)
      at process._tickCallback (node.js:401:9)
```

I commented lines 628, 672 - 680 of mongoose/lib/document.js (basically the try.. catch block structure) and the error I get is:

```
  app:error CastError: Cast to ObjectId failed for value "" at path "_id"
    at MongooseError.CastError (C:\Users\me\github\myproject\node_modules\mongoose\lib\error\cast.js:19:11)
    at ObjectId.cast (C:\Users\me\github\myproject\node_modules\mongoose\lib\schema\objectid.js:147:13)
    at ObjectId.SchemaType.applySetters (C:\Users\me\github\myproject\node_modules\mongoose\lib\schematype.js:616:12)
    at EmbeddedDocument.Document.set (C:\Users\me\github\myproject\node_modules\mongoose\lib\document.js:665:18)
    at EmbeddedDocument.Document.set (C:\Users\me\github\myproject\node_modules\mongoose\lib\document.js:526:18)
    at EmbeddedDocument.Document (C:\Users\me\github\myproject\node_modules\mongoose\lib\document.js:62:10)
    at new EmbeddedDocument (C:\Users\me\github\myproject\node_modules\mongoose\lib\types\embedded.js:30:12)
    at EmbeddedDocument (C:\Users\me\github\myproject\node_modules\mongoose\lib\schema\documentarray.js:26:17)
    at Array.MongooseDocumentArray.mixin.create (C:\Users\me\github\myproject\node_modules\mongoose\lib\types\documentarray.js:204:12)
    at Object.add (customer.js:11:44)
    at [object Generator].next (native)
    at onFulfilled (C:\Users\me\github\myproject\node_modules\koa\node_modules\co\index.js:65:19)
    at process._tickCallback (node.js:401:9) +184ms
```

So basically I'm reporting that the try..catch block obfuscates the error happening. Hope it helps

Im using mongoose "version": "4.4.6"

**Comment by vkarpov15** [comment]
@ztrange sorry for delay in responding, the below script works fine for me in 4.4.6:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4156');
mongoose.set('debug', true);

let Subdocument = new Schema({
  name: { type: String, required: true }
});

let MainSchema = new Schema({
  name: String,
  subdocs: {
    type: [Subdocument]
  }
})

let Main = mongoose.model('gh4156', MainSchema);

Main.create({ name: 'test', subdocs: [{ name: 'val' }] }, function(error, doc) {
  assert.ifError(error);
  Main.findById(doc._id).exec(function(error, doc) {
    assert.ifError(error);
    doc.subdocs.push(doc.subdocs.create({}));
    doc.save(function(error) {
      assert.ifError(error);
      console.log('done');
      process.exit(0);
    });
  });
});
```

Output:

```
$ node gh-4156.js 
Mongoose: gh4156.insert({ name: 'test', _id: ObjectId("57685912317781ae74645b39"), subdocs: [ { name: 'val', _id: ObjectId("57685912317781ae74645b3a") } ], __v: 0 })   
Mongoose: gh4156.findOne({ _id: ObjectId("57685912317781ae74645b39") }) { fields: undefined }  

assert.js:362
assert.ifError = function(err) { if (err) throw err; };
                                          ^
ValidationError: gh4156 validation failed
    at MongooseError.ValidationError (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/error/validation.js:22:11)
    at model.Document.invalidate (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:1324:32)
    at EmbeddedDocument.invalidate (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/types/embedded.js:185:19)
    at /home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:1193:17
    at validate (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/schematype.js:693:7)
    at /home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/schematype.js:724:9
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/schematype.js:698:19)
    at /home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:1191:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
$
```

No "Unable to invalidate a subdocument that has not been added to an array." error. Can you modify the above script and see if you can reproduce your issue?

**Comment by ztrange** [comment]
I'm sorry I didn't take the time to check this earlier. I just tried this in a new version and works, However and just for science I tried reproducing the issue on 4.5.0 and managed to reproduce it:

Spoiler alert: I tried reproducing it on 4.5.8 and it was no longer there. So, YOU FIXED IT! THANKS!
In advance, thanks for taking the time to check this.

The modified test script:
```
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4156');
mongoose.set('debug', true);

let Subdocument = new Schema({
  name: String
});

let MainSchema = new Schema({
  name: String,
  subdocs: {
    type: [Subdocument]
  }
})

let Main = mongoose.model('gh4156', MainSchema);

Main.create({ name: 'test' }, function(error, doc) {
  assert.ifError(error);
  Main.findById(doc._id).exec(function(error, doc) {
    assert.ifError(error);
    let subdoc = doc.subdocs.create({_id: '', name: 'foo'})
    doc.subdocs.push(subdoc);
    doc.save(function(error) {
      assert.ifError(error);
      console.log('done');
      process.exit(0);
    });
  });
});
```

The result on 4.5.0:
```
ztrange@HOME:~/github/test-api$ node test.js
Mongoose: gh4156.insert({ name: 'test', _id: ObjectId("57c9bef24956b798060d9e7e"), subdocs: [], __v: 0 })
Mongoose: gh4156.findOne({ _id: ObjectId("57c9bef24956b798060d9e7e") }) { fields: undefined }
/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/types/embedded.js:179
    throw new Error(msg);
    ^

Error: Unable to invalidate a subdocument that has not been added to an array.
    at EmbeddedDocument.invalidate (/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/types/embedded.js:179:11)
    at EmbeddedDocument.Document.set (/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/document.js:688:10)
    at EmbeddedDocument.Document.set (/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/document.js:540:18)
    at EmbeddedDocument.Document (/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/document.js:66:10)
    at new EmbeddedDocument (/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/types/embedded.js:30:12)
    at EmbeddedDocument (/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/schema/documentarray.js:26:17)
    at Array.MongooseDocumentArray.mixin.create (/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/types/documentarray.js:204:12)
    at /mnt/c/Users/ztran/github/test-api/test.js:27:30
    at Query.<anonymous> (/mnt/c/Users/ztran/github/test-api/node_modules/mongoose/lib/query.js:2181:28)
    at /mnt/c/Users/ztran/github/test-api/node_modules/kareem/index.js:244:21
    at /mnt/c/Users/ztran/github/test-api/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The result on 4.5.8:
```
ztrange@HOME:~/github/test2$ node test.js
Mongoose: gh4156.insert({ name: 'test', _id: ObjectId("57c9bf175f0893a40602c62f"), subdocs: [], __v: 0 })
Mongoose: gh4156.findOne({ _id: ObjectId("57c9bf175f0893a40602c62f") }) { fields: undefined }

/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/types/embedded.js:183
    throw err;
    ^
CastError: Cast to ObjectID failed for value "" at path "_id"
    at MongooseError.CastError (/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/error/cast.js:19:11)
    at EmbeddedDocument.Document.set (/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/document.js:704:7)
    at EmbeddedDocument.Document.set (/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/document.js:548:18)
    at EmbeddedDocument.Document (/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/document.js:67:10)
    at new EmbeddedDocument (/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/types/embedded.js:30:12)
    at EmbeddedDocument (/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/schema/documentarray.js:27:17)
    at Array.MongooseDocumentArray.mixin.create (/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/types/documentarray.js:209:12)
    at /mnt/c/Users/ztran/github/test2/test.js:27:30
    at Query.<anonymous> (/mnt/c/Users/ztran/github/test2/node_modules/mongoose/lib/query.js:2233:28)
    at /mnt/c/Users/ztran/github/test2/node_modules/kareem/index.js:259:21
    at /mnt/c/Users/ztran/github/test2/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by vkarpov15** [comment]
Perfect, glad it works :+1:
