### ISSUE TITLE
Hitting RangeError: Maximum call stack size exceeded when the app is loaded

### ISSUE THREAD

**Issue by sinqinc** [Automattic/mongoose#4163]
Hi,

We are getting errors calling our API multiple times rapidly. Is it a bug or we are doing it wrong ?

Code Description 
Receiving a file with the muster module and updating a subdocument with a Buffer().

Code that fail randomly if we "POST" a few time rapidly
`//Create a new FileSystem Object to the the uploaded file.
			        var fs = require('fs');
			        var binaryFile = fs.readFileSync(req.file.path);
			        
			        //Create a new Buffer from the binary file
			        var fileBuffer = new Buffer(binaryFile);
			        console.log("UUID "+ req.body.uuid);
			        //Add the Cleaned file to the Job document
			        options.Jobs.update({ _id: req.body.uuid }, { $set: { 
				        status: "clean_uploaded",
				        clean: { 
					      	  fieldname: req.file.fieldname,
						      originalname: req.file.originalname,
						      mimetype: req.file.mimetype,
						      destination: 	req.file.destination,
						      filename: 	req.file.filename,
						      path: 	req.file.path,
						      size: 	req.file.size,
						      filedata:	fileBuffer
						    } 
				        }},  function (err, raw) {
								  if (err) {
								      //Send Error to the Client
									  res.json({success: false, msg: err});
							      }
							      else {
								      	console.log("CLEAN POST responded and updated");
								      	//Unlink the Temp File
									  	fs.unlink(req.file.path);
								  	    //Send SUCCESS to the client
								  		res.json({success: true, msg: 'Successfully uploaded clean file.', uuid: req.body.uuid, metadata: req.file});
								  }
							}
					);  `

SCHEMA 
```
/*!
 * Jobs Schema
 * Copyright(c) 2016 SINQ inc.
 */

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var fileSchema   = new Schema({
  fieldname: {type: String},
  originalname: {type: String},
  encoding: {type: String},
  mimetype: {type: String},
  destination: {type: String},
  filename: {type: String},
  path: {type: String},
  size: {type: String},
  filedata: {type: Buffer}
});
 
// set up a mongoose model
var JobsSchema = new Schema({
  jobid: {type: String},
  status: {type: String},
  raw : fileSchema,
  clean: fileSchema
});
 
module.exports = mongoose.model('Jobs', JobsSchema);
```

CONSOLE LOG 

```
 May 19 20:46:34 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: CLEAN POST received
May 19 20:46:34 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: UUID 573e262a6fb1ea1200796586
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: /usr/src/app/node_modules/mongoose/lib/utils.js:239
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: exports.clone = function clone(obj, options) {
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: ^
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: RangeError: Maximum call stack size exceeded
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at clone (/usr/src/app/node_modules/mongoose/lib/utils.js:239:31)
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at cloneObject (/usr/src/app/node_modules/mongoose/lib/utils.js:315:13)
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at clone (/usr/src/app/node_modules/mongoose/lib/utils.js:258:16)
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Document.$toObject (/usr/src/app/node_modules/mongoose/lib/document.js:1945:13)
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Document.toObject (/usr/src/app/node_modules/mongoose/lib/document.js:2108:15)
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:822:21)
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:35 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:36 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:36 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:36 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:36 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:36 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:36 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 20:46:36 590b9018-67f1-46ec-809e-589d09012e33 docker[20496]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
```

Another Try

```
ay 19 18:52:14 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: CLEAN POST received
May 19 18:52:14 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: UUID 573e0b5e14e037130062f5ba
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: /usr/src/app/node_modules/mongoose/node_modules/bson/lib/bson/objectid.js:28
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: var ObjectID = function ObjectID(id) {
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: ^
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: RangeError: Maximum call stack size exceeded
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at new ObjectID (/usr/src/app/node_modules/mongoose/node_modules/bson/lib/bson/objectid.js:28:33)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at clone (/usr/src/app/node_modules/mongoose/lib/utils.js:270:12)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at cloneObject (/usr/src/app/node_modules/mongoose/lib/utils.js:315:13)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at clone (/usr/src/app/node_modules/mongoose/lib/utils.js:258:16)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Document.$toObject (/usr/src/app/node_modules/mongoose/lib/document.js:1945:13)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Document.toObject (/usr/src/app/node_modules/mongoose/lib/document.js:2108:15)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:822:21)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
May 19 18:52:15 590b9018-67f1-46ec-809e-589d09012e33 docker[20364]: at Object.exports.mergeClone (/usr/src/app/node_modules/mongoose/lib/utils.js:824:17)
```

**Comment by sinqinc** [comment]
using "findOneAndUpdate" instead of "update" seems to do the trick. I would like to understand my error.

Thank you

**Comment by vkarpov15** [comment]
Nothing looks glaringly wrong, but what is the binaryFile you're putting into a buffer?

**Comment by sinqinc** [comment]
The mongo document is composed of two bin file created by a 3D software. They are arround ~500k each. The first file is saved without any error . The second One is "updated " in a second API call. I've tested with a smaller file and I hit The problem after fewer call. FindOneAndUpdate is working well and faster than update.

**Comment by vkarpov15** [comment]
Weird. Well if `findOneAndUpdate` works then that's good enough for me :+1:
