### ISSUE TITLE
error: HELP!

### ISSUE THREAD

**Issue by alisyed96** [Automattic/mongoose#4197]
I'm getting error below at npm start :

```
 throw new mongoose.Error.MissingSchemaError(name);
 ^
MissingSchemaError: Schema hasn't been registered for model "Post".
ongoose.model(name, schema)
at Mongoose.model (C:\Users\SyedSaeedulHassan\Documents\Softwares\bootstrap-3.3.6-dist\chirp\module-1\start\node_modules\mongoose\lib
at Object.<anonymous> (C:\Users\SyedSaeedulHassan\Documents\Softwares\bootstrap-3.3.6-dist\chirp\module-1\start\routes\api.js:5:22)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Users\SyedSaeedulHassan\Documents\Softwares\bootstrap-3.3.6-dist\chirp\module-1\start\app.js:9:11)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.require (module.js:468:17)
```

**This is the Code at api.js:**

```javascript
var express = require('express');
var router = express.Router();
var mongoose = require( 'mongoose' );
var Post = mongoose.model('Post');

router.use(function(req, res, next){

	if(req.method === "GET"){
		//continue to the next middleware or request handler
		return next();
	}

	if(!req.isAuthenticated()){
		//user not authenticated,  redirected to login
		return res.redirect('/#login');
	}

	//user authenticated continue to next middleware
	return next();
});
router.route('/posts')

	//returns all posts
	.get(function(req, res){

		Post.find(function(err, data){

			if(err){
				return	res.send(500,err);
			}
			return res.send(data);

		});
		//temporary solution
		//res.send({message:'TODO return all posts'});
	})
	//Create a new post
	.post(function(req, res){

		 var post = new Post();
        post.text = req.body.text;
        post.username = req.body.created_by;
        post.save(function(err, post) {
            if (err){
                return res.send(500, err);
            }
            return res.json(post);
        });

		//res.send({message:'TODO Create new post'});
	});
router.route('/posts/:id')

	//return a particular post

		.get(function(req, res){
        Post.findById(req.params.id, function(err, post){
            if(err)
                res.send(err);
            res.json(post);
        });
	})

	//update existing post
	.put(function(req, res){
		Post.findById(req.params.id, function(err, post){
            if(err)
                res.send(err);

            post.username = req.body.created_by;
            post.text = req.body.text;

            post.save(function(err, post){
                if(err)
                    res.send(err);

                res.json(post);
            });
        });
	
	})

	//delete existing post
	.delete(function(req, res){
		 Post.remove({
            _id: req.params.id
        }, function(err) {
            if (err)
                res.send(err);
            res.json("deleted :(");
        });
	});	

module.exports = router;
```

**and this is at models.js :** 

```javascript
var mongoose = require('mongoose');

var userSchema = new mongoose.Schema({
    username: String,
    password: String, //hash created from password
    created_at: {type: Date, default: Date.now}
});

var postSchema = new mongoose.Schema({
	text: String,
	username: String,
	created_at: {type: Date, default: Date.now}
});

//declare a model called user using userSchema
mongoose.model("User",userSchema);
//declare a model called post using postSchema
mongoose.model("Post",postSchema);
```

**Comment by JasonCust** [comment]
This looks more like a StackOverflow post than a bug/feature request.

**Comment by vkarpov15** [comment]
@alisyed96 you're not requiring `models.js` anywhere

**Comment by alisyed96** [comment]
Thank you! @vkarpov15
It worked!
I'll be needing your help, I'm new in it.

**Comment by JasonCust** [comment]
@alisyed96 for questions like this, you should use one a more appropriate forum (a lot of your questions might have answers already) http://stackoverflow.com/questions/tagged/mongoose
