### ISSUE TITLE
Misleading error message when index name length exceeding the 128 char limit

### ISSUE THREAD

**Issue by chenliu0831** [Automattic/mongoose#4198]
I could be wrong without diving too deep into the mongoose code but it seems when we create a compound index that contains too many fields and the final index name exceeding the limit, mongoose throw a misleading message on `.` not permitted in the key name. However, I don't think that's true because if we omit just one fields and make the length within the range the index creation will success. Also if we use `ensureIndex` with a custom index name it also works perfectly. Just wondering if the length check is not happening in the correct place or the error is somehow mishandled. 

We are using `mongoose@4.3.7` under Node `v5.8.0`

```
11:55:07 web.1    | /Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongoose/lib/utils.js:459
11:55:07 web.1    |         throw err;
11:55:07 web.1    |         ^
11:55:07 web.1    | Error: key input.files must not contain '.'
11:55:07 web.1    |     at Error (native)
11:55:07 web.1    |     at serializeInto (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/bson/lib/bson/parser/serializer.js:682:19)
11:55:07 web.1    |     at serializeObject (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/bson/lib/bson/parser/serializer.js:280:18)
11:55:07 web.1    |     at serializeInto (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/bson/lib/bson/parser/serializer.js:705:17)
11:55:07 web.1    |     at serializeObject (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/bson/lib/bson/parser/serializer.js:280:18)
11:55:07 web.1    |     at serializeInto (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/bson/lib/bson/parser/serializer.js:551:17)
11:55:07 web.1    |     at serializeObject (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/bson/lib/bson/parser/serializer.js:280:18)
11:55:07 web.1    |     at serializeInto (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/bson/lib/bson/parser/serializer.js:705:17)
11:55:07 web.1    |     at serialize (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/bson/lib/bson/bson.js:47:27)
11:55:07 web.1    |     at Query.toBin (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/connection/commands.js:143:25)
11:55:07 web.1    |     at executeSingleOperation (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/topologies/server.js:765:28)
11:55:07 web.1    |     at Server.command (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/topologies/server.js:847:12)
11:55:07 web.1    |     at executeWrite (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:52:12)
11:55:07 web.1    |     at WireProtocol.insert (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:60:3)
11:55:07 web.1    |     at Server.insert (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/topologies/server.js:967:37)
11:55:07 web.1    |     at Server.insert (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb/lib/server.js:325:17)
11:55:07 web.1    |     at /Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb/lib/db.js:1004:21
11:55:07 web.1    |     at handleCallback (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb/lib/utils.js:96:12)
11:55:07 web.1    |     at /Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb/lib/db.js:1684:20
11:55:07 web.1    |     at handleCallback (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb/lib/utils.js:96:12)
11:55:07 web.1    |     at /Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb/lib/db.js:299:20
11:55:07 web.1    |     at /Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/topologies/server.js:778:46
11:55:07 web.1    |     at Callbacks.emit (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/topologies/server.js:95:3)
11:55:07 web.1    |     at null.messageHandler (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/topologies/server.js:249:23)
11:55:07 web.1    |     at Socket.<anonymous> (/Users/chenyangliu/bodylabs_services/guts-orchestrator/node_modules/mongodb-core/lib/connection/connection.js:265:22)
11:55:07 web.1    |     at emitOne (events.js:90:13)
11:55:07 web.1    |     at Socket.emit (events.js:182:7)
11:55:07 web.1    |     at readableAddChunk (_stream_readable.js:153:18)
11:55:07 web.1    |     at Socket.Readable.push (_stream_readable.js:111:10)
11:55:07 web.1    |     at TCP.onread (net.js:529:20)
```

**Comment by vkarpov15** [comment]
This looks like it stems from the same underlying issue as #3864. Upgrade [to `>= 4.4.8` for the fix](https://github.com/Automattic/mongoose/blob/master/History.md#448--2016-03-18)
