### ISSUE TITLE
Model.find() Not Resolving inside Jest Test

### ISSUE THREAD

**Issue by danielstern** [Automattic/mongoose#4206]
I have an application in which Mongoose is used to create a User model. I am testing it with Jest. When the actual file runs within the context of the test, Model.find() works, but then directly after while running inside the test file, it never resolves.

Link to repro:
https://github.com/danielstern/express-rest-api/tree/implement-tests-2

Excerpt:

```
// after connecting to db

describe('POST /api/cities', function() {
	it('Adds the specified city',(done)=>{
			User.find({},function(err,all){
				console.log("All results..",all);
                                // never resolves
			});
       })
})
```

Is something relating to Jest mocking at work here?

**Comment by azjkjensen** [comment]
This doesn't appear to be an issue with mongoose. You are never calling done() in your test framework.

**Comment by vkarpov15** [comment]
Yeah it looks like you're not calling done. I'm not familiar with jest but I'd imagine that's the problem

**Comment by nodkz** [comment]
@danielstern same problem, did you solve it?

I even can not construct schema in jest test:
```js
jest.disableAutomock();

import mongoose from 'mongoose';

describe('findById()', () => {
  it('should find records by id', (done) => {
    const schema = new mongoose.Schema({
      title:  String,
      author: String,
      body:   String,
    });
    console.log('??Where is schema??', schema);
  });
});
```

in console i get following error
```
 - TypeError: Expecting a function in instanceof check, but got [object Object]
        at exports.isMongooseObject (node_modules/mongoose/lib/utils.js:512:23)
        at Object.clone (node_modules/mongoose/lib/utils.js:248:7)
        at Schema.path (node_modules/mongoose/lib/schema.js:462:24)
        at Schema.add (node_modules/mongoose/lib/schema.js:348:12)
        at new Schema (node_modules/mongoose/lib/schema.js:94:10)

        at Object.eval (src/resolvers/__tests__/findById-test.js:22:18)
        at jasmine2 (node_modules/jest-jasmine2/src/index.js:253:7)
        at Test.run (node_modules/jest-cli/src/Test.js:44:12)
        at handle (node_modules/worker-farm/lib/child/index.js:41:8)
        at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
        at emitTwo (events.js:106:13)
        at process.emit (events.js:191:7)
        at handleMessage (internal/child_process.js:718:10)
        at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by nodkz** [comment]
Not the same problem! 

How I understood problem with jest-monkey-patch of `Object.create`.

Opened issue in jest repo: https://github.com/facebook/jest/issues/1204
Runnable repo with problem: https://github.com/nodkz/jest_mocha_mongoose
