### ISSUE TITLE
Unhandled rejection ValidationError with schema.pre('save')

### ISSUE THREAD

**Issue by turkingj** [Automattic/mongoose#4235]
Using Mongoose 4.5.0, Bluebird 3.4.0

Getting following error on console every time the below pre save hook is run

```
Unhandled rejection ValidationError: One or more invalid keywords have been specified: 
    at MongooseError.ValidationError (/recruit-sys-api/node_modules/mongoose/lib/error/validation.js:22:11)
    at EmbeddedDocument.<anonymous> (/recruit-sys-api/app/models/mongodb/requirement.js:185:18)
    at _next (/recruit-sys-api/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/recruit-sys-api/node_modules/hooks-fixed/hooks.js:186:18)
    at EmbeddedDocument.Object.defineProperty.value.fn (/recruit-sys-api/node_modules/mongoose/lib/schema.js:219:11)
    at _next (/recruit-sys-api/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper...
```

And the code, strangely it works with no errors output to console if i change it to a pre 'validate' ?
```
  /**
   * Pre-save hook
   */
  specialismSchema.pre('save', function (next) {
    let errors = new ValidationError();
    const properties = {
      type: 'user defined',
      message: 'One or more invalid keywords have been specified: ',
      path: 'keywords',
      value: 'value of keywords'
    };
    errors.errors.keywords = new ValidatorError(properties);
    next(errors);
  });
```

**Comment by vkarpov15** [comment]
The below script gives me the expected result, no unhandled rejections from bluebird. Can you try modifying the below script to see if you can reproduce your issue?

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4235');
mongoose.set('debug', true);

mongoose.Promise = require('bluebird');

var ValidationError = mongoose.Error.ValidationError;
var ValidatorError = mongoose.Error.ValidatorError;

var specialismSchema = new Schema({
  keywords: [String]
});

  /**
   * Pre-save hook
   */
  specialismSchema.pre('save', function (next) {
    let errors = new ValidationError();
    const properties = {
      type: 'user defined',
      message: 'One or more invalid keywords have been specified: ',
      path: 'keywords',
      value: 'value of keywords'
    };
    errors.errors.keywords = new ValidatorError(properties);
    next(errors);
  });

var Specialism = mongoose.model('Test', specialismSchema);
(new Specialism()).save().then(res => console.log(res), err => console.error(err));
```

Output:

```
$ node gh-4235.js 
{ ValidationError: Validation failed
    at MongooseError.ValidationError (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/error/validation.js:22:11)
    at model.<anonymous> (/home/val/Workspace/10gen/troubleshoot-mongoose/gh-4235.js:23:18)
    at _next (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at model.Object.defineProperty.value.fn (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/schema.js:219:11)
    at _next (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at /home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/schema.js:200:17
    at /home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
  message: 'Validation failed',
  name: 'ValidationError',
  errors: 
   { keywords: 
      { ValidatorError: One or more invalid keywords have been specified: 
          at MongooseError.ValidatorError (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/error/validator.js:24:11)
          at model.<anonymous> (/home/val/Workspace/10gen/troubleshoot-mongoose/gh-4235.js:30:30)
          at _next (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/hooks-fixed/hooks.js:62:30)
          at fnWrapper (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/hooks-fixed/hooks.js:186:18)
          at model.Object.defineProperty.value.fn (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/schema.js:219:11)
          at _next (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/hooks-fixed/hooks.js:62:30)
          at fnWrapper (/home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/hooks-fixed/hooks.js:186:18)
          at /home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/lib/schema.js:200:17
          at /home/val/Workspace/10gen/troubleshoot-mongoose/node_modules/mongoose/node_modules/kareem/index.js:127:16
          at _combinedTickCallback (internal/process/next_tick.js:67:7)
          at process._tickCallback (internal/process/next_tick.js:98:9)
          at Function.Module.runMain (module.js:577:11)
          at startup (node.js:159:18)
          at node.js:444:3
        message: 'One or more invalid keywords have been specified: ',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'user defined',
        path: 'keywords',
        value: 'value of keywords' } } }
^C
$
```
