### ISSUE TITLE
strange issue with mongoose and cloning

### ISSUE THREAD

**Issue by amit777** [Automattic/mongoose#4260]
(node 6.2.2, mongoose 4.5.2, node-sassl 3.7.0 works)
When updated my node-sass to 3.8.0, i get the following mongoose error.  It seems like node-sass change something with the way it deals with objects by doing a clone of some sort.  I'm not sure if this a bug with node-sass or if the change in node-sass has exposed a bug in mongoose:  Here is a link to the issue (it has a stack trace in it).

https://github.com/sass/node-sass/issues/1606

Stack trace is here for simplicity:
```
TypeError: Cannot read property 'states' of undefined
    at model.Document.$__shouldModify (/opt/app/node_modules/mongoose/lib/document.js:765:35)
    at model.Document.$__set (/opt/app/node_modules/mongoose/lib/document.js:785:27)
    at model.Document.set (/opt/app/node_modules/mongoose/lib/document.js:705:10)
    at model.Object.defineProperty.set [as domainname] (/opt/app/node_modules/mongoose/lib/document.js:1712:25)
    at assignValue (/opt/app/node_modules/lodash._baseclone/index.js:758:17)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:5
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at /opt/app/node_modules/lodash._baseclone/index.js:863:30
    at arrayEach (/opt/app/node_modules/lodash._baseclone/index.js:164:9)
    at baseClone (/opt/app/node_modules/lodash._baseclone/index.js:858:3)
    at cloneDeep (/opt/app/node_modules/lodash.clonedeep/index.js:28:10)
    at getOptions (/opt/app/node_modules/node-sass/lib/index.js:175:17)
    at Object.module.exports.render (/opt/app/node_modules/node-sass/lib/index.js:268:17)
    at /opt/app/node_modules/email-templates/lib/template-manager.js:124:10
    at Promise._execute (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:77:14)
    at renderSass (/opt/app/node_modules/email-templates/lib/template-manager.js:123:10)
    at /opt/app/node_modules/email-templates/lib/template-manager.js:63:22
    at Promise._execute (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:77:14)
    at render (/opt/app/node_modules/email-templates/lib/template-manager.js:45:10)
    at renderFile (/opt/app/node_modules/email-templates/lib/util.js:53:38)
    at /opt/app/node_modules/email-templates/lib/email-template.js:200:38
    at Promise._execute (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:77:14)
    at EmailTemplate._renderStyle (/opt/app/node_modules/email-templates/lib/email-template.js:188:14)
    at /opt/app/node_modules/email-templates/lib/email-template.js:146:97
    at tryCatcher (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at MappingPromiseArray.PromiseArray._resolve (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/map.js:97:18)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/opt/app/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:630:18)
    at /opt/app/node_modules/email-templates/node_modules/bluebird/js/release/nodeback.js:42:21
```

**Comment by vkarpov15** [comment]
Hmm can you show me the code that triggers this error? Are you passing a mongoose document in to a function as options?

**Comment by amit777** [comment]
It's a little difficult to get the code for the environment because of a bunch of context.  I've also tried the toObject() method already.   Although, I just realized, does toObject() only convert a parent schema's attributes?  My schema multiple nested schemas within arrays.  Maybe the lower level schema's are not getting their .toObjects() called as well?  Here is an example of my schema.  
```
var settingsSchema = new Schema({
   name: String,
   value: String,
});

var settingsSchema = new Schema(
var userSchema = new Schema({
   settings: [settingsSchema],
   params: [ Schema({name: String, default: String, allowoverride: Number, forceoverride: Number}, {_id: false}) ]
});

```

Here is the basic structure of the code that is having the issue with, and without .toObject().

```
var user = userfromsomewhere; // a Mongoose User object
var templateVars = {user: user.toObject()}
//this function is from the email-templates library to render a template which uses user info
template(templateVars, function(err, html,text){ ...});  //this is where the clone is happening.
```

**Comment by amit777** [comment]
SOrry for the trouble.  I think I found a place where I forgot to put .toObject().  It seems to work now with the latest version of node-sass.  Though I'm still curious if .toObject() is supposed to recursively enumerate the mongoose object's schemas?

**Comment by vkarpov15** [comment]
What do you mean by "recursively enumerate the mongoose object's schemas"?

**Comment by vkarpov15** [comment]
Re: https://github.com/Automattic/mongoose/issues/4260#issuecomment-228498841, yes, it should output the entire document by default, including nested schemas and populated docs. If mongoose does not, it's a bug, so please open up an issue if you have any trouble with that :beers:

**Comment by simonepri** [comment]
I don't know if could be useful but the problem seems to be still here (using _.CloneDeep()):

"lodash": "^4.17.2"
"mongoose": "^4.7.1"

```
TypeError: Cannot read property 'states' of undefined
    at model.Document.$__shouldModify (\node_modules\mongoose\lib\document.js:802:56)
    at model.Document.$__set (\node_modules\mongoose\lib\document.js:842:27)
    at model.Document.set (\node_modules\mongoose\lib\document.js:758:10)
    at model.Object.defineProperty.set [as supplier_id] (\node_modules\mongoose\lib\document.js:1787:25)
    at baseAssignValue (\node_modules\lodash\lodash.js:2599:21)
    at assignValue (\node_modules\lodash\lodash.js:2515:9)
    at \node_modules\lodash\lodash.js:2721:9
    at arrayEach (\node_modules\lodash\lodash.js:537:11)
    at baseClone (\node_modules\lodash\lodash.js:2715:7)
    at \node_modules\lodash\lodash.js:2721:34
    at arrayEach (\node_modules\lodash\lodash.js:537:11)
    at baseClone (\node_modules\lodash\lodash.js:2715:7)
    at \node_modules\lodash\lodash.js:2721:34
    at arrayEach (\node_modules\lodash\lodash.js:537:11)
    at baseClone (\node_modules\lodash\lodash.js:2715:7)
    at \node_modules\lodash\lodash.js:2721:34
```

**Comment by vkarpov15** [comment]
If you're doing `_.cloneDeep()` on a document, please don't, that will not work at all. Just use `doc.toObject()`.

**Comment by simonepri** [comment]
@vkarpov15 
Yes is exactly what i've already done, I've converted it to an object, and everything works as expected. Thanks.

However, what i was doing is to use _.cloneDeep() on an Object that is built with some references on a document:

E.g:
```
var doc; //mongose document

var obj = {
  someData: doc.someObject,
  { ... }
}
var newObj = _.cloneDeep(obj);  //error
```

**Comment by vkarpov15** [comment]
You really shouldn't use `_.cloneDeep()` on any part of a mongoose object. `someData: doc.someObject.toObject()` is the way to go. Mongoose documents don't do well when you copy them because of all the work we do to track changes.

**Comment by vkarpov15** [comment]
Also, `.toObject()` creates a new object every time so it's effectively a clone operation.

**Comment by DarkKnight1992** [comment]
toObject() doesn't work with findOne() :(

**Comment by vkarpov15** [comment]
@DarkKnight1992 can you please clarify?
