### ISSUE TITLE
can't specify model for virtual population

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#4261]
Thank you so much, this feature is great and already saved me a lot of code and time
but there is a bug with populating using a model field

here is a test case

```js
var mongoose = require("mongoose");

var db1 = mongoose.createConnection();
db1.open("mongodb://localhost/issue-123");

mongoose.set("debug", true);


var YSchema = new mongoose.Schema({
	name: String,
	x: [{
		type: mongoose.Schema.Types.ObjectId,
		ref: "X"
	}]
});

var Y = db1.model("Y", YSchema);

var XSchema = new mongoose.Schema({
	name: String
});

XSchema.virtual("y", {
	ref: "Y",
	localField: "_id",
	foreignField: "x"
});

var X = db1.model("X", XSchema);

var x = new X({
	name: "X"
});

x.save(function (err, x) {

	console.log(x)

	var y = new Y({
		name: "Y",
		x: [x._id]
	});
	y.save(function (err, y) {
		console.log(y)
		X.findById(x)
			.populate({path: "y"})
			.exec(function (err, xx) {
				console.log(err);
				console.log(xx);
				console.log(xx.y);
			});
	});
});
```

```
Mongoose: xes.insert({ name: 'X', _id: ObjectId("576cf5c04c6a614d8fe0d2b9"), __v: 0 })   
Mongoose: ys.insert({ name: 'Y', _id: ObjectId("576cf5c04c6a614d8fe0d2ba"), x: [ ObjectId("576cf5c04c6a614d8fe0d2b9") ], __v: 0 })   
Mongoose: xes.findOne({ _id: ObjectId("576cf5c04c6a614d8fe0d2b9") }) { fields: undefined }  
Mongoose: ys.find({ x: { '$in': [ ObjectId("576cf5c04c6a614d8fe0d2b9") ] } }) { fields: undefined }  
```

this example works good, you can see all queries it sends to db

however if i want specify `model`, it doesn't send last query

```js
var mongoose = require("mongoose");

var db1 = mongoose.createConnection();
db1.open("mongodb://localhost/issue-123");

mongoose.set("debug", true);


var YSchema = new mongoose.Schema({
	name: String,
	x: [{
		type: mongoose.Schema.Types.ObjectId,
		ref: "X"
	}]
});

var Y = db1.model("Y", YSchema);

var XSchema = new mongoose.Schema({
	name: String
});

XSchema.virtual("y", {
	ref: "Y",
	localField: "_id",
	foreignField: "x"
});

var X = db1.model("X", XSchema);

var x = new X({
	name: "X"
});

x.save(function (err, x) {

	console.log(x)

	var y = new Y({
		name: "Y",
		x: [x._id]
	});
	y.save(function (err, y) {
		console.log(y)
		X.findById(x)
			.populate({path: "y", model: db1.model("Y")}) // <-- here
			.exec(function (err, xx) {
				console.log(err);
				console.log(xx);
				console.log(xx.y);
			});
	});
});
```

```
Mongoose: xes.insert({ name: 'X', _id: ObjectId("576cf5b0c9b28bf68ee4650b"), __v: 0 })   
Mongoose: ys.insert({ name: 'Y', _id: ObjectId("576cf5b0c9b28bf68ee4650c"), x: [ ObjectId("576cf5b0c9b28bf68ee4650b") ], __v: 0 })   
Mongoose: xes.findOne({ _id: ObjectId("576cf5b0c9b28bf68ee4650b") }) { fields: undefined }  
```

I need this to populate across different connections but it also doesn't work for one connection

also it would be good to set model directly on virtual definition
```js
XSchema.virtual("y", {
	ref: "Y",
	localField: "_id",
	foreignField: "x",
	model: "Y" // or db1.model("Y")
});
```

**Comment by TrejGun** [comment]
so i have found a reason for bug
https://github.com/Automattic/mongoose/blob/master/lib/model.js#L2685
the model `Y` passed in `populate` comes to getModelsMapForPopulate
but it can't find virtual `y` on this model so returns nothing
the workaround is to add `y` on `Y` model too

```
YSchema.virtual("y", {
    ref: "Y",
    localField: "_id",
    foreignField: "x"
});
```

this looks dirty but works

**Comment by TrejGun** [comment]
this looks like line
https://github.com/Automattic/mongoose/blob/master/lib/model.js#L2980
should be
```
virtual = (options.model ? (options.model.schema ? options.model : model.db.model(options.model)) : model).schema.virtuals[options.path];
```

**Comment by TrejGun** [comment]
unfortunately things are a bit more complicated, i can't fix this

**Comment by TrejGun** [comment]
unfortunately this commit breaks something else

```
log:mocha TypeError: Cannot read property '_doc' of null
at Object.exports.get (./common/node_modules/mpath/lib/index.js:72:27)
at Object.exports.getValue (./common/node_modules/mongoose/lib/utils.js:626:16)
at _assign (./common/node_modules/mongoose/lib/model.js:2774:26)
at next (./common/node_modules/mongoose/lib/model.js:2755:5)
at Query.<anonymous> (./common/node_modules/mongoose/lib/model.js:3361:16)
at ./common/node_modules/kareem/index.js:244:21
at ./common/node_modules/kareem/index.js:127:16
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickDomainCallback (internal/process/next_tick.js:122:9) +8s
```

**Comment by TrejGun** [comment]
@vkarpov15 looks like the second level is broken

```
X.findById(x)
            .populate({
                        path: "y", 
                        model: db1.model("Y"),
                        populate: [{
                                    path: "z",
                                    model: db1.model("Z"),
                        }]
            })
```

says `can't find model Y`

**Comment by vkarpov15** [comment]
Ah woops, good catch. Will take a closer look tomorrow

**Comment by TrejGun** [comment]
can you please take a look at this? i can help you with tests :)

**Comment by vkarpov15** [comment]
Yup on it right now :)

**Comment by vkarpov15** [comment]
@TrejGun added a test case above that seems to work - can you modify it to more closely match your use case? My understanding is that you're trying to do virtual populate with a deep conventional populate?

**Comment by vkarpov15** [comment]
Can you open up a separate issue for the deep populate issue? I'm gonna mark this one as closed for now.
