### ISSUE TITLE
error sizeOfMessage when running mongodb/mongoose behind haproxy

### ISSUE THREAD

**Issue by Aksum** [Automattic/mongoose#4287]
Receive error message below when using haproxy to load balance between mongodb instances. Do not get error running mongodb/mongoose without haproxy.

connecting
Server is running @ port 3010

/opt/node/core-channel-manager/node_modules/mongoose/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
MongoError: server mongodb.triggi.int:27017 received an error {"err":"socketHandler","trace":"","parseState":{"sizeOfMessage":1347703880}}
    at null.<anonymous> (/opt/node/core-channel-manager/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:372:40)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at null.<anonymous> (/opt/node/core-channel-manager/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:156:10)
    at g (events.js:273:16)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at Socket.<anonymous> (/opt/node/core-channel-manager/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:263:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
error: Forever detected script exited with code: 1
error: Script restart attempt #660
error: Forever detected script was killed by signal: SIGKILL

**Comment by vkarpov15** [comment]
Can you successfully connect using the mongodb shell to your HAProxy+mongodb setup? I've never actually tried putting mongodb behind HAProxy, wouldn't be surprised if there where more than a few difficulties there.

**Comment by Aksum** [comment]
Hi,
sorry for late reply. Have not tested it yet, but will do so as soon as possible.

Thanks.

**Comment by vkarpov15** [comment]
@Aksum let me know if you have some time, I haven't had a chance to take a look yet.

**Comment by Aksum** [comment]
Issue resolved. Always use TCP mode in haproxy. Closing ticket.
