### ISSUE TITLE
Error in populate function

### ISSUE THREAD

**Issue by alexanderknapstein** [Automattic/mongoose#4331]
I get a TypeError: Cannot read property 'exec' of undefined at populate. see stack strace below:

This happens only in version 4.5.4, in 4.5.3 it works.

Please tell me if you need more details. At the moment I can't figure out my call signature for populate.

(/var/node/node_modules/mlcl_database/node_modules/mongoose/lib/model.js:2676:12)
    at _populate (/var/node/node_modules/mlcl_database/node_modules/mongoose/lib/model.js:2574:5)
    at Function.Model.populate (/var/node/node_modules/mlcl_database/node_modules/mongoose/lib/model.js:2534:5)
    at model.populate (/var/node/node_modules/mlcl_database/node_modules/mongoose/lib/document.js:2386:22)
    at populateReferences (/var/node/node_modules/mlcl_elastic/node_modules/mongolastic/index.js:102:15)
    at /var/node/node_modules/mlcl_elastic/node_modules/mongolastic/index.js:130:9
    at /var/node/node_modules/mlcl_elastic/node_modules/async/lib/async.js:122:13
    at _each (/var/node/node_modules/mlcl_elastic/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/var/node/node_modules/mlcl_elastic/node_modules/async/lib/async.js:121:9)
    at populate (/var/node/node_modules/mlcl_elastic/node_modules/mongolastic/index.js:110:9)
    at /var/node/node_modules/mlcl_elastic/node_modules/mongolastic/index.js:643:15
    at Query.<anonymous> (/var/node/node_modules/mlcl_database/node_modules/mongoose/lib/model.js:3331:16)
    at /var/node/node_modules/mlcl_database/node_modules/mongoose/node_modules/kareem/index.js:259:21
    at /var/node/node_modules/mlcl_database/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)

Thanks in advance, 
Alex

**Comment by vkarpov15** [comment]
I'm gonna need a code sample and whatever info you can provide, I don't quite see how that can be happening because it's calling `.exec()` on the result of `Model.find()`, which should always return a value. We also have tests in place that execute this code and they're passing.
