### ISSUE TITLE
Mongoose require failed

### ISSUE THREAD

**Issue by ArnaudParant** [Automattic/mongoose#4360]
Hello,

I am trying to use Mongoose in my React project.
But the require line is crashing at the run time, even without mongo connection.
If I comment the require line, it works.

**Configuration**
```
    "node": "0.12.15",
    "react": "^0.12.2", 
    "react-hot-loader": "^0.5.0",
    "react-router": "^0.12.0",
    "mongoose": "4.5.5"
```
My node version is pretty old, I have to upgrade it, but it is a huge project...

**Code**
``` var Mongoose = require('mongoose'); ```

**Error**
```
/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:22
        if(err) throw err;
                ^
Error: Cannot resolve file or directory ../../package in /home/toto/dashboard/node_modules/mongoose/node_modules/mongodb/lib/mongodb
    at /home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:63:31
    at /home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:166:15
    at /home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:59:4
    at /home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/DirectoryDefaultFilePlugin.js:16:51)
    at Storage.provide (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.stat (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:126:20)
    at Tapable.<anonymous> (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/DirectoryDefaultFilePlugin.js:15:6)
    at Tapable.applyPluginsParallelBailResult (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:139:14)
    at Tapable.<anonymous> (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:57:8)
    at Tapable.Resolver.forEachBail (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:171:3)
    at Tapable.doResolve (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:56:7)
    at Tapable.resolve (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:41:14)
    at Tapable.resolveSync (/home/toto/dashboard/node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:16:7)
    at ModuleFactory.createSync (/home/toto/dashboard/node_modules/enhanced-require/lib/ModuleFactory.js:50:40)
    at RequireContext.theRequire (/home/toto/dashboard/node_modules/enhanced-require/lib/RequireContext.js:114:40)
```

Do you have any idea ?

Kind regards,
Arnaud

**Comment by vkarpov15** [comment]
Is this a purely server-side project or are you using some sort of transpiler? Also, does it work if you use regular `require()` rather than enhanced-require?
