### ISSUE TITLE
Error validation crashing heroku app

### ISSUE THREAD

**Issue by panagorn** [Automattic/mongoose#4372]
Hello when i try do create a new user that exist i get error.

This is the validation

```javascript
// Validate email is not taken
UserSchema
  .path('email')
  .validate(function(value, respond) {
    var self = this;
    this.constructor.findOne({'email': value}, function (err, user) {
      if(err) throw err;
      if(user) {
        if(self.id === user.id) return respond(true);
        return respond(false);
      }
      respond(true);
    });
  }, 'The specified email address is already in use.');
```

This is the create endpoint

```javascript
exports.create = function (req, res, next) {
  var use={name: req.body.name, email: req.body.email,password:req.body.password};
  var newUser = new User(use);
  newUser.provider = 'local';
  newUser.role = 'user';
  newUser.save(function(err, user) {
    if (err) return res.status(400).json(err);
    var token = jwt.sign({_id: user._id }, config.secrets.session, { expiresIn: 60*5 });
    res.json({ token: token });
  });
};
```

Line 81 at user model is the return respond(false);

```
{
    "stack": "Error\n    at MongooseError.ValidationError (/Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/lib/error/validation.js:22:16)\n    at model.Document.invalidate (/Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/lib/document.js:1162:32)\n    at /Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/lib/document.js:1037:16\n    at validate (/Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/lib/schematype.js:653:7)\n    at /Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/lib/schematype.js:678:11\n    at Query.<anonymous> (/Users/panayiotis/WebstormProjects/SmartHome/server/api/user/user.model.js:81:16)\n    at /Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/node_modules/kareem/index.js:177:19\n    at /Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/node_modules/kareem/index.js:109:16\n    at nextTickCallbackWith0Args (node.js:420:9)\n    at process._tickCallback (node.js:349:13)",
    "message": "User validation failed",
    "name": "ValidationError",
    "errors": {
        "email": {
            "properties": {
                "type": "user defined",
                "message": "The specified email address is already in use.",
                "path": "email",
                "value": "test1@test.com"
            },
            "stack": "Error\n    at MongooseError.ValidatorError (/Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/lib/error/validator.js:25:16)\n    at validate (/Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/lib/schematype.js:652:13)\n    at /Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/lib/schematype.js:678:11\n    at Query.<anonymous> (/Users/panayiotis/WebstormProjects/SmartHome/server/api/user/user.model.js:81:16)\n    at /Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/node_modules/kareem/index.js:177:19\n    at /Users/panayiotis/WebstormProjects/SmartHome/node_modules/mongoose/node_modules/kareem/index.js:109:16\n    at nextTickCallbackWith0Args (node.js:420:9)\n    at process._tickCallback (node.js:349:13)",
            "message": "The specified email address is already in use.",
            "name": "ValidatorError",
            "kind": "user defined",
            "path": "email",
            "value": "test1@test.com"
        }
    }
}
```

**Comment by vkarpov15** [comment]
I don't understand what the error is, it looks like you wrote a validator that's supposed to fail when there's already user with the given email, and as far as I can tell it looks like it's doing what it is supposed to. Can you clarify what the issue is?

**Comment by panagorn** [comment]
i fix the issue updating the mongoose version that my app is using
