### ISSUE TITLE
"Cannot read property '$__' of undefined" while validation

### ISSUE THREAD

**Issue by qwemaze** [Automattic/mongoose#4390]
MongooseJS v4.5.8
```
return !this.__parent.$__.validationError ||
                         ^

TypeError: Cannot read property '$__' of undefined
    at EmbeddedDocument.$isValid (/home/qwemaze/projects/repos/kholodilnik/node_modules/mongoose/lib/types/embedded.js:235:26)
    at /home/qwemaze/projects/repos/kholodilnik/node_modules/mongoose/lib/document.js:1284:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

Schema:
```js
const schema = {
    states: [ {
			label: {
				type: "String",
				trim: true,
				index: true,
				enum: [ "error", "done", "processing", "denied", "approved", "confirmed", "registered" ],
                required: true
			},
			at: {
				type: "Date",
				default: Date.now,
				set: function ( d ) {
					if ( this.at ) throw new Error( 'state.at is constant' );
					else return d;
				},
				required: true
			}
        } ]
}

const states = schema.path( 'states' );

    states.required( true );
	states.default( [ {
		label: 'registered'
	} ] );
	states.validate( function ( val ) {
		const allStatesN = val.length;
		const uniqStatesN = new Set( val.map( s => s.label ) ).size;
		if ( allStatesN !== uniqStatesN ) return false;
		return true;
	} );
```

Reproduce:
```js
model.create({});
```

**Comment by qwemaze** [comment]
Fixed by replacing
```js
states.default( [ {
        label: 'registered'
    } ] );
```
with
```js
states.default( () => [ {
		label: 'registered'
	} ] );
```
But just a value should work, right?

**Comment by vkarpov15** [comment]
It should, thanks for the detailed repro instructions, will take a look asap
