### ISSUE TITLE
Using hydrated embedded document for within geography query leads to RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by kmpm** [Automattic/mongoose#4392]
This is probably like #1918 but since that issue was fairly old and without any comments I decided to create a new one.

When trying to use a embedded document for a query it throws an RangeError if I don't call .toJSON() on it first.
This is on Windows 10 x64 with mongod version 3.2.8, and node v4.4.7, mongoose 4.5.8.

The testcase below will show something like this...
```
node testcase.js
find using polygon
got list of 3
find using loc.toJSON, this works
got list of 3
find using loc, this causes the bug
c:\testcase\node_modules\mongoose\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

RangeError: Maximum call stack size exceeded
    at Buffer.write (buffer.js:517:34)
    at serializeBoolean (C:\testcase\node_modules\mongoose\node_modules\bson\lib\bson\parser\serializer.js:135:37)
...
```

```javascript
var mongoose = require('mongoose');
var assert = require('assert');

mongoose.Promise = global.Promise;
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/testcase');

var polygon = {
    name: 'Limmen',
    loc: {
        "type": "Polygon",
        "coordinates": [[
            [12.356185913085938, 59.114741425081775],
            [12.356185913085938, 59.13764426569856],
            [12.427425384521484, 59.13764426569856],
            [12.427425384521484, 59.114741425081775],
            [12.356185913085938, 59.114741425081775]
          ]
        ]
      }
};

var areaSchema = new Schema({
    name: {type: String},
    loc: {
        'type': {type: String, enum: ['Polygon'], default: 'Polygon'},
        coordinates: [[[Number]]]
    }
});
areaSchema.index({loc: '2dsphere'});

var observationSchema = new Schema({
    geometry: {
        'type': {type: String, enum: ['Point'], default: 'Point'},
        coordinates: {type: [Number]}
    },
    properties: {
        temperature: {type: Number}
    }
});
observationSchema.index({geometry: '2dsphere'});

var Area = mongoose.model('Area', areaSchema);
var Observation = mongoose.model('Observation', observationSchema);
var gArea;

Promise.all([
    Area.remove(),
    Observation.remove()
])
.then(function () {
    return Observation.insertMany([
        {"properties" : {"temperature" : 10.1}, "geometry": { "type" : "Point", "coordinates" : [12.3708003269788, 59.1240178630772]}},
        {"properties" : {"temperature" : 10.2}, "geometry": { "type" : "Point", "coordinates" : [12.3708183537247, 59.1240317395636]}},
        {"properties" : {"temperature" : 10.3}, "geometry": { "type" : "Point", "coordinates" : [12.3708183537247, 59.1240317395636]}},
        {"properties" : {"temperature" : -15}, "geometry": { "type" : "Point", "coordinates" : [0, 0]}}
    ]);
})
.then(function () {
    console.log('find using polygon');
    return Observation.find().where('geometry').within().geometry(polygon.loc);
})
.then(function (list) {
    console.log('got list of %d', list.length);
    assert.equal(list.length, 3, 'wrong number of observations returned');
    var a1 = new Area(polygon);
    return a1.save();
})
.then(function (area) {
    gArea = area;
    console.log('find using loc.toJSON, this works');
    return Observation.find().where('geometry').within().geometry(gArea.loc.toJSON());
})
.then(function (list) {
    //this should work
    console.log('got list of %d', list.length);
    assert.equal(list.length, 3, 'wrong number of observations returned');

    console.log('find using loc, this causes the bug');
    return Observation.find().where('geometry').within().geometry(gArea.loc);
})
.then(function (list) {
    //this will probably never happen....
    console.log('got list of %d', list.length);
    assert.equal(list.length, 3, 'wrong number of observations returned');
})
.catch(function (reason) {
    console.error('Bad', reason);
});
```

**Comment by vkarpov15** [comment]
Thanks for the detailed repro, will look into this asap
