### ISSUE TITLE
markModified throws unexpected error

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#4438]
```
     TypeError: Cannot read property 'modify' of undefined
      at model.Document.markModified (node_modules/mongoose/lib/document.js:945:23)
      at model.Document.$__set (node_modules/mongoose/lib/document.js:798:10)
      at model.Document.set (node_modules/mongoose/lib/document.js:713:10)
      at model.Object.defineProperty.set [as _id] (node_modules/mongoose/lib/document.js:1712:25)
      at assignValue (node_modules/lodash/_assignValue.js:23:17)
      at node_modules/lodash/_baseClone.js:134:5
      at arrayEach (node_modules/lodash/_arrayEach.js:15:9)
      at baseClone (node_modules/lodash/_baseClone.js:128:3)
      at node_modules/lodash/_baseClone.js:134:30
      at arrayEach (node_modules/lodash/_arrayEach.js:15:9)
      at baseClone (node_modules/lodash/_baseClone.js:128:3)
      at node_modules/lodash/_baseClone.js:134:30
      at arrayEach (node_modules/lodash/_arrayEach.js:15:9)
      at baseClone (node_modules/lodash/_baseClone.js:128:3)
      at node_modules/lodash/_baseClone.js:134:30
      at arrayEach (node_modules/lodash/_arrayEach.js:15:9)
      at baseClone (node_modules/lodash/_baseClone.js:128:3)
      at node_modules/lodash/_baseClone.js:134:30
      at arrayEach (node_modules/lodash/_arrayEach.js:15:9)
      at baseClone (node_modules/lodash/_baseClone.js:128:3)
      at baseMergeDeep (node_modules/lodash/_baseMergeDeep.js:63:20)
      at node_modules/lodash/_baseMerge.js:35:7
      at arrayEach (node_modules/lodash/_arrayEach.js:15:9)
      at baseMerge (node_modules/lodash/_baseMerge.js:28:3)
      at node_modules/lodash/merge.js:36:3
      at node_modules/lodash/_createAssigner.js:30:9
      at apply (node_modules/lodash/_apply.js:15:25)
      at node_modules/lodash/_baseRest.js:31:12
      at prepare (message.js:144:9)
      at getTemplate.then.template (mail-template.js:23:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

if this stack doesn't help will try to find more

**Comment by TrejGun** [comment]
the reason is `lodash.merge` cant merge objects with models

```
_.merge({a:1}, {b:Model});
```

**Comment by vkarpov15** [comment]
Yeah use `toObject()`, mongoose models really don't handle copying very well
