### ISSUE TITLE
TypeError: Promise.ES6 is not a constructor

### ISSUE THREAD

**Issue by minibear0523** [Automattic/mongoose#4445]
* OS: Mac OS X
* Node: V6.4.0 & V5.4.1
* mongoose: V4.5.9

var promise = new Promise.ES6(function(resolve, reject) {
                ^

TypeError: Promise.ES6 is not a constructor
    at NativeConnection.Connection.open (/Users/MiniBear0523/Projects/DIY_Travel_Server/node_modules/mongoose/lib/connection.js:282:17)
    at Mongoose.connect (/Users/MiniBear0523/Projects/DIY_Travel_Server/node_modules/mongoose/lib/index.js:241:47)
    at Object.<anonymous> (/Users/MiniBear0523/Projects/DIY_Travel_Server/app.js:16:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/MiniBear0523/Projects/DIY_Travel_Server/bin/www:7:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Program node ./bin/www exited with code 1

**Comment by vkarpov15** [comment]
Are you setting `mongoose.Promise` anywhere?

**Comment by McStuffins** [comment]
I am having the same issue. Here is a code example: 
-Typescript:
import * as bluebird from "bluebird";
(<any>mongoose).Promise = bluebird.Promise; 


Call Stack: 
TypeError: Promise.ES6 is not a constructor
    at NativeConnection.Connection.openUri (C:\Users\rober\Documents\Projects\Scanunlimited\news-feed-server\node_modules\mongoose\lib\connection.js:819:17)
    at Mongoose.connect (C:\Users\rober\Documents\Projects\Scanunlimited\news-feed-server\node_modules\mongoose\lib\index.js:262:17)
    at Object.<anonymous> (C:\Users\rober\Documents\Projects\Scanunlimited\news-feed-server\dist\index.js:11:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
