### ISSUE TITLE
Cannot read property 'createdAt' of undefined

### ISSUE THREAD

**Issue by barczaG** [Automattic/mongoose#4447]
Since release 4.5.8 I got this error whenever I try to update a document with timestamps enabled.

```
TypeError: Cannot read property 'createdAt' of undefined
    at applyTimestampsToChildren (.../node_modules/mongoose/lib/schema.js:867:33)
    at Query.<anonymous> (.../node_modules/mongoose/lib/schema.js:816:7)
    at next (.../node_modules/kareem/index.js:82:14)
    at Kareem.execPre (.../node_modules/kareem/index.js:99:3)
    at Kareem.wrap (.../node_modules/kareem/index.js:231:8)
    at Query._execUpdate (.../node_modules/kareem/index.js:271:11)
    at Query.update (.../node_modules/mongoose/lib/query.js:2189:17)
    at .../node_modules/mongoose/lib/query.js:2230:21
    at Promise._execute (.../node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (.../node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (.../node_modules/bluebird/js/release/promise.js:77:14)
    at Query.exec (.../node_modules/mongoose/lib/query.js:2223:10)
    at Query.then (.../node_modules/mongoose/lib/query.js:2253:15)
    at next (.../node_modules/co/index.js:100:51)
    at onFulfilled (.../node_modules/co/index.js:69:7)
    at tryCatcher (.../node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (.../node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (.../node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (.../node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (.../node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (.../node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (.../node_modules/bluebird/js/release/async.js:148:10)
```

If I downgrade to 4.5.7 everything works correctly

**Comment by TrejGun** [comment]
same #4421 ?

**Comment by vkarpov15** [comment]
Yep same as those. Upgrade to 4.5.10 and that issue should go away

**Comment by varunjayaraman** [comment]
@barczaG can you confirm your issue disappeared after mongoose 4.5.10?
