### ISSUE TITLE
Error when trying to change existing text index

### ISSUE THREAD

**Issue by djanowski** [Automattic/mongoose#4459]
```
Error: key name.first must not contain '.'
    at Error (native)
    at serializeInto (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:682:19)
    at serializeObject (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serialize (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/bson/lib/bson/bson.js:47:27)
    at Query.toBin (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/commands.js:146:25)
    at executeSingleOperation (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1214:31)
    at Server.command (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1295:3)
    at executeWrite (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:61:12)
    at WireProtocol.insert (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:69:3)
    at Server.insert (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1323:37)
    at Server.insert (/private/tmp/30c4196e58d47d07499cf6403833b2bd/node_modules/mongoose/node_modules/mongodb/lib/server.js:351:17)
```

Reproduce with: 

```js
const Mongoose = require('mongoose');

Mongoose.Promise = Promise;
Mongoose.connect(`mongodb://localhost/test-${Date.now()}`);

const PersonSchema = new Mongoose.Schema({
  name: {
    first: { type: String },
    last:  { type: String }
  }
});

// Set up first version of the text index.
PersonSchema.index({ 'name.first': 'text' });

const Person = Mongoose.model('Person', PersonSchema);

Person.ensureIndexes()
  .then(() => {
    // Set up new version of text index.
    PersonSchema.index({ 'name.first': 'text', 'name.last': 'text' });
    return Person.ensureIndexes();
  })
  .then(() => {
    console.log('It worked.');
    process.exit();
  })
  .catch(error => {
    console.error(error.stack);
    process.exit(1);
  });
```

Also in this [gist](https://gist.github.com/djanowski/30c4196e58d47d07499cf6403833b2bd).

In the script I declare `Model.index()` twice, calling `Model.ensureIndexes()` in between. It emulates what you do when you are changing an existing index. Running this as separate steps in separate scripts yields the same result.

Mongoose: 4.5.10
MongoDB: 3.2.9
Node.js: 4.4.6

**Comment by vkarpov15** [comment]
The real error message is this:

```
{ MongoError: exception: Index with pattern: { _fts: "text", _ftsx: 1 } already exists with different options
    at Function.MongoError.create (/home/val/Workspace/10gen/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at commandCallback (/home/val/Workspace/10gen/mongoose/node_modules/mongodb-core/lib/topologies/server.js:1187:66)
    at Callbacks.emit (/home/val/Workspace/10gen/mongoose/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/home/val/Workspace/10gen/mongoose/node_modules/mongodb-core/lib/topologies/server.js:358:23)
    at Socket.<anonymous> (/home/val/Workspace/10gen/mongoose/node_modules/mongodb-core/lib/connection/connection.js:292:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
  name: 'MongoError',
  message: 'exception: Index with pattern: { _fts: "text", _ftsx: 1 } already exists with different options',
  createdCollectionAutomatically: false,
  numIndexesBefore: 2,
  errmsg: 'exception: Index with pattern: { _fts: "text", _ftsx: 1 } already exists with different options',
  code: 85,
  ok: 0 }
```

Re: https://github.com/mongodb/node-mongodb-native/pull/1398, the underlying mongodb driver is swallowing the actual error message because it thinks it needs to fall back to a legacy method for creating indexes. Will bump mongoose's version of the mongodb driver when this issue is fixed.

**Comment by vkarpov15** [comment]
Waiting on changes from https://github.com/mongodb/node-mongodb-native/commit/052b2e3f6f30a797f0cd44c14c89d80b5796b73b to get released

**Comment by vkarpov15** [comment]
This was fixed as of 4.6.4

**Comment by elena-dev** [comment]
i have this problem 

ReviewsSchema.index({message: 'text', name: 'text', email: 'text'}, {name: 'message_text'});

Index with name: message_text already exists with different options

i did ensureIndexes this command not resolve this problem

**Comment by lineus** [comment]
@elena-dev, If you are trying to add an index to an existing collection, it must have a unique name.

You can use the `Model.syncIndexes()` command to remove all indexes from your collection that don't match the ones in your schema, or if you want to keep both indexes you can rename the new one.

for example:

### 4459_before.js
```js
#!/usr/bin/env node
'use strict';

const { MongoClient } = require('mongodb');
const URI = 'mongodb://localhost:27017/gh4459';
const OPTS = { useNewUrlParser: true };

async function run() {
  let client = await MongoClient.connect(URI, OPTS);
  let Tests = client.db('gh4459').collection('tests');
  await client.db('gh4459').dropDatabase();
  await Tests.createIndex({ name: 1 }, { name: 'blarghfooey' });
  return client.close();
}

run().catch(console.error);
```
### 4459.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
mongoose.connect('mongodb://localhost:27017/gh4459', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  message: String,
  name: String,
  email: String
});

const index = { message: 'text', name: 'text', email: 'text' };
const iOpts = { name: 'blarghfooey', background: false };

schema.index(index, iOpts);

async function run() {
  const Test = mongoose.model('test', schema);
  await Test.syncIndexes().catch(console.error);
  let indexes = await Test.listIndexes();
  console.log(indexes);
  return conn.close();
}

run();
```
### Output:
```
issues: ./4459_before.js
issues: ./4459.js
[ { v: 2, key: { _id: 1 }, name: '_id_', ns: 'gh4459.tests' },
  { v: 2,
    key: { _fts: 'text', _ftsx: 1 },
    name: 'blarghfooey',
    ns: 'gh4459.tests',
    background: false,
    weights: { email: 1, message: 1, name: 1 },
    default_language: 'english',
    language_override: 'language',
    textIndexVersion: 3 } ]
issues:
```
*if you change syncIndexes() to createIndexes() this example will fail as you described* 
**CAUTION: syncIndexes() will remove all indexes not defined in your schema**
