### ISSUE TITLE
Defining method on a schema with same name as property causes vague error

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4475]
When you try to define a method on a schema (e.g. `OrderSchema.methods.isPaid = ...`) while the schema already has a property defined with the same name (e.g. `isPaid: Boolean`), Mongoose will fail with a vague error:

```
/Users/Adam/Sites/clients/jolinejolink/server/node_modules/mongoose/lib/document.js:1712
        return this.set.call(this.$__.scope || this, path, v);
                                     ^

TypeError: Cannot read property 'scope' of undefined
    at model.Object.defineProperty.set [as isPaid] (/Users/Adam/Sites/clients/jolinejolink/server/node_modules/mongoose/lib/document.js:1712:38)
    at applyMethods (/Users/Adam/Sites/clients/jolinejolink/server/node_modules/mongoose/lib/model.js:3243:31)
    at Function.compile (/Users/Adam/Sites/clients/jolinejolink/server/node_modules/mongoose/lib/model.js:3188:3)
    at Mongoose.model (/Users/Adam/Sites/clients/jolinejolink/server/node_modules/mongoose/lib/index.js:392:17)
    at Object.<anonymous> (/Users/Adam/Sites/clients/jolinejolink/server/app/components/order/order.model.js:83:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at glob.sync.forEach.modelPath (/Users/Adam/Sites/clients/jolinejolink/server/app/services/db.js:79:5)
    at Array.forEach (native)
    at module.exports (/Users/Adam/Sites/clients/jolinejolink/server/app/services/db.js:77:36)
    at module.exports (/Users/Adam/Sites/clients/jolinejolink/server/app/app.js:57:3)
    at Object.<anonymous> (/Users/Adam/Sites/clients/jolinejolink/server/scripts/server.js:51:32)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

I think it'd be a good idea to check for this scenario and fail with a more descriptive error like `Cannot define method 'isPaid' as a property with the same name exists`.

**Comment by vkarpov15** [comment]
Good suggestion, thanks, will implement asap.

**Comment by adambuczynski** [comment]
🎉
