### ISSUE TITLE
connect.js error int ubuntu

### ISSUE THREAD

**Issue by youxikaifa** [Automattic/mongoose#4508]
var promise = new Promise.ES6(function(resolve, reject) {

var promise = new Promise.ES6(function(resolve, reject) {
                ^
TypeError: undefined is not a function
    at NativeConnection.Connection.open (/gitres/express/activeCompus/node_modules/mongoose/lib/connection.js:282:17)
    at Mongoose.connect (/gitres/express/activeCompus/node_modules/mongoose/lib/index.js:241:47)

**Comment by youxikaifa** [comment]
it's  mongodb not connect ?  node not update? what can i do?

**Comment by vkarpov15** [comment]
code sample please? Also, what node version?
