### ISSUE TITLE
v4.5.9+ findOneAndUpdate with $push throws TypeError: Cannot read property '$isMongooseDocumentArray'...

### ISSUE THREAD

**Issue by joaoreynolds** [Automattic/mongoose#4514]
After upgrading from v4.5.8 I found a bug starting with v4.5.9 and with v4.6.0:

Here's my schema:
```
const permitSchema = new mongoose.Schema(
  {
    ...
    orders: [
      new mongoose.Schema(
        {
          _deleted: Date,
          orderNumber: { type: String, required: true },
          termId: mongoose.Schema.Types.ObjectId,
          transactions: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Transaction' }],
          items: [
            new mongoose.Schema({
              name: { type: String, required: true },
              description: String,
              amount: { type: Number, required: true },
              internalNotes: String
            })
          ]
        },
        {
          timestamps: { createdAt: '_created', updatedAt: '_updated' },
          minimize: true
        }
      )
    ]
    ...
  }
)
```
Trying to do this:
```
    const updatePermitPromise = Permit.findOneAndUpdate(
      { _id: permitId, 'orders._id': orderId },
      {
        $push: { 'orders.$.transactions': newTransaction._id }
      },
      {new: true, runValidators: true, context: 'query'}
    ).populate('organization').exec()
```

And here's the first part of the stacktrace:
```
Cannot read property '$isMongooseDocumentArray' of undefined TypeError: Cannot read property '$isMongooseDocumentArray' of undefined
    at applyTimestampsToChildren (/Users/johnreynolds/.../node_modules/mongoose/lib/schema.js:843:29)
    at Query.<anonymous> (/Users/johnreynolds/.../node_modules/mongoose/lib/schema.js:810:7)
```
Worked in 4.5.8, but doesn't anymore.

**Comment by vkarpov15** [comment]
Below script works fine for me:

```javascript
'use strict';

Error.stackTraceLimit = Infinity;

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4514');
mongoose.set('debug', true);

const permitSchema = new mongoose.Schema(
  {
    orders: [
      new mongoose.Schema(
        {
          _deleted: Date,
          orderNumber: { type: String, required: true },
          termId: mongoose.Schema.Types.ObjectId,
          transactions: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Transaction' }],
          items: [
            new mongoose.Schema({
              name: { type: String, required: true },
              description: String,
              amount: { type: Number, required: true },
              internalNotes: String
            })
          ]
        },
        {
          timestamps: { createdAt: '_created', updatedAt: '_updated' },
          minimize: true
        }
      )
    ]
  }
);

var Permit = mongoose.model('Permit', permitSchema);
var orderId = new mongoose.Types.ObjectId();
var newTransactionId = new mongoose.Types.ObjectId();

const updatePermitPromise = Permit.findOneAndUpdate(
  { 'orders._id': orderId },
  {
    $push: { 'orders.$.transactions': newTransactionId }
  },
  {new: true, runValidators: true, context: 'query'}
).populate('organization').exec(function(error) {
  assert.ifError(error);
})
```

with 4.5.9, 4.6.0, and master. Can you see if you can modify the above script to repro your issue?

**Comment by SergeyCherman** [comment]
The same issue is occurring for me. I think that in schema.js applyTimestampsToChildren needs to check that the key is found in the case of update.$push, the same way it is done for $set.
```

path = schema.path(key);
        if (!path) {
          continue;
        }

```
@vkarpov15 if you agree then I can submit a PR. My regex is weak, what is
`return /\.\d+\.?.*$/.test(path)
        ? getPositionalPath(this, path)
        : undefined;`
in the path function is meant to find? As I am guessing the fix suggested is just a workaround and not the root cause.

**Comment by vkarpov15** [comment]
It's meant to find if there's something like `.<digits>.<other stuff>` in the string. Although `applyTimestampsToChildren` already checks for $push, so what you're talking about shouldn't be necessary. Can you provide a code sample demonstrating your issue?

**Comment by SergeyCherman** [comment]
Sample that causes error:
```javascript
'use strict';

Error.stackTraceLimit = Infinity;

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4514');
mongoose.set('debug', true);

var sampleSchema = new mongoose.Schema(
  {        
    name: { type: String, required: true },
    sampleArray: [{
            name: { type: String, required: false, trim: true },
            values: [{ type: String, required: false, trim: true }],
          }]
  },
  {
    timestamps: { createdAt: '_created', updatedAt: '_updated' },
    minimize: true
  }
   
);

var sampleModel = mongoose.model('sampleTable', sampleSchema);
var newRecord = new sampleModel({name:'testname', sampleArray: [{name:'rec1', values:['record1']}]});

newRecord.save(function(err, result){
  sampleModel.update( { 'sampleArray.name': 'rec1' },
    {
      $push: {'sampleArray.$.values': 'another record'}
    },
    {new: true, runValidators: true, context: 'query'},
    function(err, result){
      console.log(done)
      exit(1)
    }
  );
});
```


In applyTimestampsToChildren, the $set performs a check that path exists, however $push does not do the same check. I propose: modifying the $push logic to be:
```javascript
if (update.$push) {
      for (key in update.$push) {

        path = schema.path(key);
        if (!path) {
          continue;
        }

        if (update.$push[key] &&
            schema.path(key).$isMongooseDocumentArray &&
            schema.path(key).schema.options.timestamps) {
          timestamps = schema.path(key).schema.options.timestamps;
          createdAt = timestamps.createdAt || 'createdAt';
          updatedAt = timestamps.updatedAt || 'updatedAt';
          update.$push[key][updatedAt] = now;
          update.$push[key][createdAt] = now;
        }
      }
    }
```
