### ISSUE TITLE
TypeError: this.model is not a function

### ISSUE THREAD

**Issue by mitchellporter** [Automattic/mongoose#4533]
Getting the following error on both my older version of mongoose `4.4.20` and latest version `4.6.0` when trying to update a document (via PUT request for context):

`TypeError: this.model is not a function`

Here's the code I use to try and update the user document when a PUT req comes in:
```
var User = require('../users/userModel');
....
User.update({_id: user._id}, user, { runValidators: true }, function(err) {
        if (err) logger.error(err);
    });

```
I get the same error when trying to use `findOneAndUpdate`. I thought I might be exporting my model wrong or something but I don't think I am. Here is my userModel.js file in it's entirety. It's fairly large but didn't want to cut anything out if it is indeed causing the problem:

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var bcrypt = require('bcrypt');

// Enum
var avatar_names = {
    values: ['astronaut', 'godzilla', 'swat', 'surgeon'],
    message: 'Please choose a valid avatar'
}

var UserSchema = new Schema({
    created_at: {
        type: Date,
        required: true
    },
    updated_at: {
        type: Date,
        required: true
    },
    username: {
        type: String,
        required: [true, 'Please enter a username'],
        unique: true,
        minlength: [3, 'Username must be longer than 3 characters'],
        maxlength: [20, 'Username must be 20 characters or less'],
        match: [/^[a-z0-9]+$/i, 'Username can only contain letters and numbers'] // My guess is that this won't work
    },
    lowercase_username: {
        type: String,
        required: true
    },
    password: {
        type: String,
        required: [true, 'Please enter a password'],
        minlength: [4, 'Password must be 4 digits long'],
        maxlength: [4, 'Password must be 4 digits long'],
        match: [/^\d+$/, 'Password can only contain numbers']
    },
    about_me: {
        type: String,
        maxlength: [10, 'About me cant be longer than 10 characters']
    },
    avatar_name: {
        type: String,
        required: true,
        enum: avatar_names
    },
    avatar_url: {
        type: String,
    },
    following_count: {
        type: Number,
        required: true,
        default: 0
    },
    followers_count: {
        type: Number,
        required: true,
        default: 0
    },
    views_count: {
        type: Number,
        required: true,
        default: 0
    },
    apns_token: {
        type: String,
    },
    apns_notifications_enabled: {
        type: Boolean,
        default: true
    }
});

// Custom error for unique username
UserSchema.path('username').validate(function(value, done) {
    this.model('User').count({ username: value }, function(err, count) {
        if (err) {
            return done(err);
        } 
        // If `count` is greater than zero, "invalidate"
        done(!count);
    });
}, 'Sorry but this username is already taken');

// Pre-validation
UserSchema.pre('validate', function(next) {
    if (!this.created_at) this.created_at = new Date();
    this.lowercase_username = this.username.toLowerCase();
    this.updated_at = new Date();
    next();
});

// middleware that runs before the document is saved
UserSchema.pre('save', function(next) {

	if (this.isModified('password')) // If the pw has been modified, then encrypt it again
	this.password = this.encryptPassword(this.password);
  
  next();
})

// Add custom methods to our User schema
UserSchema.methods = {
	// Check the passwords on signin
	authenticate: function(plainTextPassword) {
		return bcrypt.compareSync(plainTextPassword, this.password);
	},

	// Hash the passwords
	encryptPassword: function(plainTextPassword) {
		if (!plainTextPassword) {
			return ''
		} else {
			var salt = bcrypt.genSaltSync(10);
			return bcrypt.hashSync(plainTextPassword, salt);
		}
	}
};

module.exports = mongoose.model('User', UserSchema);
```

**Comment by mitchellporter** [comment]
If I use the following I can update my User document:

```
User.findByIdAndUpdate(originalUser._id, { $set: { username: originalUser.username }}, { new: true }, function (err, user) {
        if (err) logger.error(err);
});
```

However, if I add the `runValidators` option and set it to `true`, it will throw the same error:

```
User.findByIdAndUpdate(originalUser._id, { $set: { username: originalUser.username }}, { new: true, runValidators: true }, function (err, user) {
        if (err) logger.error(err);
});
```

**Comment by mitchellporter** [comment]
I figured it out. I had the following in my `userModel.js` file:

```
UserSchema.path('username').validate(function(value, done) {
    this.model('User').count({ username: value }, function(err, count) {
        if (err) {
            logger.error('custom username path error: ' + err);
            return done(err);
        } 
        // If `count` is greater than zero, "invalidate"
        done(!count);
    });
}, 'Sorry but this username is already taken');
```

I had to use the above instead of simply setting `required: true` for the schema's `username` path because I wanted to use a custom error message when the username had already been taken by another user. This code works when calling a method like `save` on a document of the schema, but when calling a method like `findByIdAndUpdate` on the model itself the error `TypeError: this.model is not a function` was being thrown which is expected.

**Comment by vkarpov15** [comment]
Glad you found the issue. Here's the relevant docs on your issue: http://mongoosejs.com/docs/validation.html#update-validators-and-this

**Comment by mitchellporter** [comment]
Thanks for the link @vkarpov15.

**Comment by zeyadShapan** [comment]
@vkarpov15 I'm getting the same error
My Schema
```
UserSchema.methods.getProfile = function () {
    console.log('CALLED GETTING PROFILE...')
    return 'SUCCESS INTEGRATION'
}
```

How I call it

```

router.put('/experience', authMid, async (req, res) => {
    req.user.getProfile()
    res.send('Adding experiences')
})
```

And I tried without the auth middleware and got the same error
```
const user = await User.find({_id: req.user._id})
user.getProfile()
```
For some reason, I get this error in the console
```
TypeError: user.getProfile is not a function
    at /Users/nehmado/Documents/Programming/projects/PortfolioItems/PortfolioItems/DevHall/routes/profile.js:45:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Also I have working methods such as genAuthToken method which makes me even more confused

**Comment by vkarpov15** [comment]
@zeyadShapan please make sure you're defining `getProfile()` _before_ calling `mongoose.model()`. Otherwise, your issue has nothing to do with OP's issue, so please open a new issue and follow the issue template.
