### ISSUE TITLE
_markModified is not a function

### ISSUE THREAD

**Issue by ignasg** [Automattic/mongoose#4540]
Was getting the following error after upgrading to latest mongoose:
```
\node_modules\mongoose\lib\types\embedded.js:68
    this.__parentArray._markModified();
                       ^
TypeError: undefined is not a function
    at EmbeddedDocument.markModified (\node_modules\mongoose\lib\types\embedded.js:68:24)
    at SchemaArray.cast (\node_modules\mongoose\lib\schema\array.js:180:9)
    at SchemaArray.SchemaType.getDefault (\node_modules\mongoose\lib\schematype.js:587:23)
    at EmbeddedDocument.Document.$__buildDoc (\node_modules\mongoose\lib\document.js:243:22)
    at EmbeddedDocument.Document (\node_modules\mongoose\lib\document.js:61:20)
    at new EmbeddedDocument (\node_modules\mongoose\lib\types\embedded.js:30:12)
    at EmbeddedDocument (\node_modules\mongoose\lib\schema\documentarray.js:27:17)
    at DocumentArray.SchemaArray (\node_modules\mongoose\lib\schema\array.js:61:21)
    at new DocumentArray (\node_modules\mongoose\lib\schema\documentarray.js:46:13)
    at Function.Schema.interpretAsType (\node_modules\mongoose\lib\schema.js:582:14)
    at Schema.path (\node_modules\mongoose\lib\schema.js:527:29)
    at Schema.add (\node_modules\mongoose\lib\schema.js:411:12)
    at new Schema (\node_modules\mongoose\lib\schema.js:98:10)
    at Object.<anonymous> (\modules\project\server\models\project.server.model.js:71:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at \config\lib\mongoose.js:15:5
    at Array.forEach (native)
```

Changing 
```
EmbeddedDocument.prototype.markModified = function(path) {
  this.$__.activePaths.modify(path);
  if (!this.__parentArray) {
    return;
  }
```

to
```
EmbeddedDocument.prototype.markModified = function(path) {
  this.$__.activePaths.modify(path);
  if (!this.__parentArray || !this.__parentArray._markModified) {
    return;
  }
```
on node_modules\mongoose\lib\types\embedded.js
seems to do the trick

**Comment by bhishp** [comment]
We have seen this too. Can confirm that @ignasg solution works for me

**Comment by vkarpov15** [comment]
Good catch, but can you show me a code sample that reproduces this issue? In that code if `__parentArray` is defined then it should have an `_markModified` function, otherwise something's wrong

**Comment by ignasg** [comment]
Sorry I cant work out a simple test case for this as it happens on production code and cant dedicate time to debug this, however __parentArray is not really an array but some messed up empty object bubbling up from higher level. 
This is the bit of schema it fails on:
```
  documents: { type: [Document.schema] },
```
Where Document is just another simple model.
Considering the complexity of debugging this it might be easier to just accept the simple workaround as posted above.

**Comment by vkarpov15** [comment]
Workaround is good and all, but the workaround would just hide a potentially insidious bug. @bhishp do you have any additional code samples that can help?

**Comment by bhishp** [comment]
It wasn't clear why this was happening as we don't even use markModified in the app. It was complaining at the mongoose.Schema() function (line 3) for our Task model:

```
var mongoose = require('mongoose');

var taskSchema = mongoose.Schema({
  name: {
    type: String,
    index: {unique: true},
    required: true
  },
  title: String,
  information: {
    description: String,
    instructions: String
  },
  category: {
    type: String
  },
  tags: {
    type: Array,
    default: []
  },
  type: {
    type: String,
    required: true,
    default: 'quiz'
  },
  provider: {
    type: String,
    required: true
  },
  level: {
    type: Number,
    required: true,
    default: 1
  },
  playerInfo: [{
    information: {
      description: String,
      instructions: String
    },
    languages: {
      type: Array,
      default: ['english']
    },
    imports: {
      type: Array,
      default: []
    },
    tests: {
      type: Array,
      default: []
    },
    required: {
      type: String
    },
    skeleton: {
      type: Array,
      default: []
    },
    solution: {
      type: Array,
      default: []
    }
  }],
  shared: {
    type: Boolean,
    required: true,
    default: false
  },
  totalStars: {
    type: Number,
    required: true,
    default: 0
  },
  totalAttempts: {
    type: Number,
    required: true,
    default: 0
  },
  totalCompleted: {
    type: Number,
    required: true,
    default: 0
  },
  averageTime: {
    type: Number,
    required: true,
    default: 0
  },
  createdOn: {
    type: Date,
    required: true,
    default: Date.now
  },
  updatedOn: {
    type: Date,
    required: true,
    default: Date.now
  },
  createdBy: {
    type: String,
    required: true,
  }
});

module.exports = mongoose.model('Task', taskSchema);
```

Doesn't seem anything out of the ordinary to me..

I have reverted to a known working version of mongoose in our system but will try 2.6 again and let you know full stack trace.

**Comment by vkarpov15** [comment]
Thanks for the repro instructions @bhishp , turns out there was a subtle bug with how mongoose handled non-empty default arrays when the array was nested in another array. Instrumental in fixing the issue :+1:

**Comment by rubenstolk** [comment]
I'm still getting this in `4.8.5` ...

**Comment by vkarpov15** [comment]
@rubenstolk please provide repro instructions

**Comment by rubenstolk** [comment]
@vkarpov15 can't say exactly anymore, happened in the "hydration" from json to models with subdocuments.

**Comment by beeplin** [comment]
I got this in 4.9.2 too. 

schema: 

```js
  schema: {
    _id: {
      type: String,
      required: true,
      unique: true
    },
    communication: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      validate: isCommunication
    },
    password: {
      type: String,
      required: true
    },
    history: {
      type: [
        {
          recordedAt: {
            type: Date,
            required: true
          },
          docId: {
            type: String,
            validate: isDocId
          }
        }
      ]
    }
```
then try to `$push` to `history` with the following update:

```js
    {
        $push: {
          history: {
            $each: [{type: 'a', recordedAt: Date.now(), docId: 'xxx'}],
            $slice: 100
        }
      }
```

@ignasg 's working-around trick works for this.

**Comment by vkarpov15** [comment]
@beeplin can you open up a separate issue for this please?

**Comment by ashishdommety** [comment]
Was this pulled into the latest mongoose? I still seem to be getting this issue

**Comment by vkarpov15** [comment]
@ashishdommety can you please open up a separate issue with code samples?
