### ISSUE TITLE
Cannot populate sub documents defined with refs

### ISSUE THREAD

**Issue by slamuu** [Automattic/mongoose#4552]
Not sure if this is even a bug, but defining a `ref` object in an sub-document will still have the `.populate()` method but calling it will result in an error. The error seems to be that it is trying to invoke the sub-document's `Model.populate()` method

```
'use strict';

const mongoose = require('mongoose');
const ObjectId = mongoose.Types.ObjectId;

const ReferenceSchema = new mongoose.Schema({
  field: String,
});

const EmbeddedSchema = new mongoose.Schema({
  reference: {
    type: mongoose.Schema.ObjectId,
    ref: 'Reference',
  },
});

const ModelSchema = new mongoose.Schema({
  embedded: EmbeddedSchema,
});

mongoose.model('Reference', ReferenceSchema);
const Model = mongoose.model('Model', ModelSchema);

const model = new Model();

model.embedded = {};
model.embedded.reference = new ObjectId();

model.embedded.populate('reference').execPopulate();
```

Results in this stack
```
this.constructor.populate(this, paths, fn);
                     ^

TypeError: this.constructor.populate is not a function
    at Document.populate (/node_modules/mongoose/lib/document.js:2416:22)
    at /node_modules/mongoose/lib/document.js:2452:11
    at new Promise.ES6 (/node_modules/mongoose/lib/promise.js:45:3)
    at Document.execPopulate (/node_modules/mongoose/lib/document.js:2451:10)
    at Object.<anonymous> (/test.js:30:38)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by vkarpov15** [comment]
Unfortunately that's not really something we can support atm without a lot of work. Just do `model.populate('embedded.reference').execPopulate()` instead
