### ISSUE TITLE
error on reconnection

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#4565]
I have an error when mongoose trying to reconnect

```
TypeError: db.close is not a function
    at NativeConnection.db.on.error (~/source/utils/mongoose.js:2:1821)
    at emitOne (events.js:96:13)
    at NativeConnection.emit (events.js:188:7)
    at ~/node_modules/mongoose/lib/connection.js:288:17
    at NativeConnection.Connection.error (~/node_modules/mongoose/lib/connection.js:451:12)
    at ~/node_modules/mongoose/lib/connection.js:482:15
    at ~/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:69:21
    at ~/node_modules/mongoose/node_modules/mongodb/lib/db.js:229:14
    at Server.<anonymous> (~/node_modules/mongoose/node_modules/mongodb/lib/server.js:259:9)
    at Server.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (~/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:313:21)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (~/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (~/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:172:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:334:8)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

here is my setup

``` js
let db = mongoose.createConnection();
db.on("close", () => {
    console.log("connection closed");
});
db.on("open", () => {
    console.log("Connected to mongo server.");
});
db.on("error", error => {
    console.log(error);
    db.close();
});

db.open(url, {
    url: URI,
    user: USER,
    pass: PASS,
    options: {
        server: {
            socketOptions: {
                keepalive: 1
            }
        }
    }
});
```

and my attempt to fix
https://github.com/Automattic/mongoose/pull/4564/files

which actually fixes error but breaks some other stuff i'm unaware of
can you please take a look?

**Comment by TrejGun** [comment]
sorry for that pr, i thought you will see this issue first

**Comment by vkarpov15** [comment]
Hmm @TrejGun can you clarify your setup? If I run your script without a mongod running, I get the below output:

```javascript
$ node gh-4565.js 
{ Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017' }
^C
$
```

**Comment by vkarpov15** [comment]
Issue's gone stale, re-open if it's still an issue.
