### ISSUE TITLE
Cryptic error if you try to populate a virtual field

### ISSUE THREAD

**Issue by aiguofer** [Automattic/mongoose#4602]
I just spent a while debugging an error that ultimately turned out to be that I had moved a property of a model to a virtual but forgot to update the populate string (so it was in essence trying to populate a virtual). However, here's what the error says:

```
<project_path>/node_modules/mpath/lib/index.js:49
    throw new TypeError('Invalid `path`. Must be either string or array');
    ^

TypeError: Invalid `path`. Must be either string or array
  at Object.exports.get (<project_path>/node_modules/mpath/lib/index.js:49:11)
  at Object.exports.getValue (<project_path>/node_modules/mongoose/lib/utils.js:626:16)
  at getModelsMapForPopulate (<project_path>/node_modules/mongoose/lib/model.js:2963:34)
  at populate (<project_path>/node_modules/mongoose/lib/model.js:2606:15)
  at _populate (<project_path>/node_modules/mongoose/lib/model.js:2574:5)
  at Function.Model.populate (<project_path>/node_modules/mongoose/lib/model.js:2534:5)
  at Immediate.<anonymous> (<project_path>/node_modules/mongoose/lib/query.js:1211:17)
  at Immediate.<anonymous> (<project_path>/node_modules/mquery/lib/utils.js:137:16)
  at runCallback (timers.js:574:20)
  at tryOnImmediate (timers.js:554:5)
  at processImmediate [as _immediateCallback] (timers.js:533:5)

Stopping Express server
```

Not sure if it's plausible, but it'd be nice if it could give a better reason of why the `path` is invalid.

**Comment by vkarpov15** [comment]
Thanks for reporting :+1:
