### ISSUE TITLE
Error with setting mongoose promise

### ISSUE THREAD

**Issue by swrocket** [Automattic/mongoose#4604]
Based on the deprecation warning, I'm trying to set the mongoose.Promise to global.Promise

`mongoose.Promise = global.Promise;
mongoose.connect(connectionString);`

when the connect is executed, I get an error as follows
`TypeError: undefined is not a function
    at NativeConnection.Connection.open (D:\home\site\wwwroot\node_modules\mongoose\lib\connection.js:282:17)
    at Mongoose.connect (D:\home\site\wwwroot\node_modules\mongoose\lib\index.js:242:47)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:142:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Program Files (x86)\iisnode\interceptor.js:451:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3`

Any ideas?

**Comment by zbjornson** [comment]
What global promise library are you using? (Sorry if it's a dumb question, but what does `console.log(global.Promise)` show?)

**Comment by vkarpov15** [comment]
Which version of node? The global.Promise property doesn't exist before node v4

**Comment by swrocket** [comment]
Thanks Valeri. I realized that the Azure server was not runing the correct version of Node. I updated that version and also switched to 'q' as the promise library and all works well now.
