### ISSUE TITLE
Array child schema $push throws RangeError

### ISSUE THREAD

**Issue by acrazing** [Automattic/mongoose#4609]
The test code as follow:

```ts


import { connect } from 'mongoose';
import { Schema } from 'mongoose';
import { SchemaTypes } from 'mongoose';
import { model } from 'mongoose';
import { toBuffer } from 'ip';
import { Document } from 'mongoose';

const arrSchema = new Schema({
  ip  : SchemaTypes.Buffer,
  date: SchemaTypes.Date,
  str : SchemaTypes.String,
})
const schema    = new Schema({
  arr: [arrSchema]
})

const Model = model<any>('PushArray', schema)

connect('mongodb://localhost:27017/test').then(() => {
  const doc = new Model({
    arr: [
      {
        ip  : toBuffer('127.0.0.1'),
        str : 'Unknown',
        date: new Date,
      }
    ]
  }).save().then((doc: any) => {
    console.log('saved doc', JSON.stringify(doc))
    return doc
  }).then((doc: Document) => doc.update({
    $push: {
      arr: {
        ip  : toBuffer('127.0.0.1'),
        date: new Date,
        str : 'Unknown',
      }
    }
  }).exec())
    .catch((err: any) => {
      console.error(`error`, err)
    })
})

```

Execute this will throw the follow error:

```bash
RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at formatPrimitive (util.js:429:47)
    at formatValue (util.js:227:19)
    at formatProperty (util.js:581:15)
    at util.js:465:12
    at Array.map (native)
    at formatObject (util.js:464:15)
    at formatValue (util.js:410:16)
    at formatProperty (util.js:581:15)
    at util.js:465:12
    at Array.map (native)
    at formatObject (util.js:464:15)
    at formatValue (util.js:410:16)
    at formatProperty (util.js:581:15)
    at util.js:465:12
    at Array.map (native)
    at formatObject (util.js:464:15)
    at formatValue (util.js:410:16)
    at formatProperty (util.js:581:15)
    at util.js:465:12
    at Array.map (native)
```

The version is `4.6.2`

**Comment by acrazing** [comment]
I found this is caused by the type of `Buffer`, if I remove the `ip` field, this will work

**Comment by acrazing** [comment]
I found this to be caused by `Buffer` type field. If I remove the `ip` field from the upon code, everything is all right.
