### ISSUE TITLE
Upgrading from 4.2.4 -> 4.3.6 causes maximum stack error when doing toObject()

### ISSUE THREAD

**Issue by iq-dot** [Automattic/mongoose#4613]
Schema;

```
var MySchema = new Schema({
	created: {
		type: Date,
		default: Date.now
	},
    uId: {
        type: String,
        index: true,
        default: uuid.v4
    },
    appMessage: {
        type: Boolean,
        default: false
    },
	fromUser: {
		type: Schema.ObjectId,
		ref: 'User',
        index: true
	},
    toUser: {
        type: Schema.ObjectId,
        ref: 'User',
        required: 'Must specify the user this message should be sent to',
        index: true
    },
    message: {
        type: String,
        required: 'Must set a message text'
    },
    viewed: {
        type: Boolean,
        default: false
    },
    request: {
        requestType: {
            type: String,
            enum: ['document', 'generic']
        },
        status: {
            type: String,
            default: 'pending',
            enum: ['pending', 'void', 'completed']
        },
        token: String,
        info: {
            type: Schema.ObjectId,
            ref: 'Info'
        },
        property: {
            type: Schema.ObjectId,
            ref: 'Property'
        }
    }
});
```

If I do:

```
         model = new MySchema({
                toUser: userReceiver.id,
                message: 'Message Text',
                request: {
                    requestType: 'document',
                    documentRequested: 'P45'
                }
            });

user.mySchemaList.push(model);
user.save();

model.toObject() // error maximum stack size

```

Here is the error in stack trace:

```
    at model.Document.$toObject (node_modules/mongoose/lib/document.js:2035:13)
    at model.Document.toObject (node_modules/mongoose/lib/document.js:2200:15)
    at clone (node_modules/mongoose/lib/utils.js:252:16)
    at cloneObject (node_modules/mongoose/lib/utils.js:315:13)
    at clone (node_modules/mongoose/lib/utils.js:258:16)
    at EmbeddedDocument.Document.$toObject (node_modules/mongoose/lib/document.js:2035:13)
    at EmbeddedDocument.Document.toObject (node_modules/mongoose/lib/document.js:2200:15)
    at clone (node_modules/mongoose/lib/utils.js:252:16)
    at cloneArray (node_modules/mongoose/lib/utils.js:334:14)
    at clone (node_modules/mongoose/lib/utils.js:245:12)
    at cloneObject (node_modules/mongoose/lib/utils.js:315:13)
    at clone (node_modules/mongoose/lib/utils.js:258:16)
    at model.Document.$toObject (node_modules/mongoose/lib/document.js:2035:13)
    at model.Document.toObject (node_modules/mongoose/lib/document.js:2200:15)
    at clone (node_modules/mongoose/lib/utils.js:252:16)
    at cloneObject (node_modules/mongoose/lib/utils.js:315:13)
    at clone (node_modules/mongoose/lib/utils.js:258:16)
    at model.Document.$toObject (node_modules/mongoose/lib/document.js:2035:13)
    at model.Document.toObject (node_modules/mongoose/lib/document.js:2200:15)
    at model.Document.inspect (node_modules/mongoose/lib/document.js:2309:15)
    at model.Document.toString (node_modules/mongoose/lib/document.js:2320:23)
    at errLogger (app/controllers/errors.server.controller.js:79:19)
    at node_modules/mongoose/lib/model.js:3343:16
    at node_modules/mongoose/lib/document.js:1947:18
```

**Comment by vkarpov15** [comment]
@iq-dot what does `mySchemaList` look like in your user schema? Is it an embedded field or a populated field?

**Comment by iq-dot** [comment]
@vkarpov15 Sorry I forgot to reply.

mySchemaList is basically an array of mySchema which gets populated:

```mySchemaList: [MySchema]```

**Comment by vkarpov15** [comment]
Hmm have you tried upgrading to 4.6.4? Issue might have been fixed in the interim

**Comment by vkarpov15** [comment]
Also, can you double check your version and stack trace? The [line numbers referenced in your original stack trace are way off from mongoose v4.3.6](https://github.com/Automattic/mongoose/blob/e17e233affcde0ec6564f62e65e06001a35b9d5e/lib/document.js#L2200)

**Comment by iq-dot** [comment]
I actually did upgrade to a newer version and had pretty much the same issue and then so reverted back.

I could try to get the stack trace again if required?

**Comment by vkarpov15** [comment]
If you could get me the new stack trace that would help, if I don't know what version then the stack trace is largely useless.
