### ISSUE TITLE
Problem with replicaSet after upgrade to 4.6.3

### ISSUE THREAD

**Issue by roneichiarandi** [Automattic/mongoose#4617]
After upgrade mongoose to 4.6.3 and mongodb to 2.2.10, I'm have problems with the replicaSet connections...

```
/project/node_modules/mongodb/lib/replset.js:360
          process.nextTick(function() { throw err; })
                                        ^
MongoError: no primary found in replicaset
    at /project/node_modules/mongodb-core/lib/topologies/replset.js:631:32
    at null.<anonymous> (/project/node_modules/mongodb-core/lib/topologies/replset.js:421:24)
    at g (events.js:260:16)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/project/node_modules/mongodb-core/lib/topologies/server.js:313:21)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/project/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/project/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

And when I use just the primary database, i have another error

```
/project/node_modules/mongodb/lib/server.js:261
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [database:port] on first connect
    at null.<anonymous> (/project/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/project/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/project/node_modules/mongodb-core/lib/connection/connection.js:172:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:318:8)
    at _runOnTimeout (timers.js:515:11)
    at _makeTimerTimeout (timers.js:506:3)
    at Timer.unrefTimeout (timers.js:575:5)
```

Please, someone can help me?

Thanks

**Comment by vkarpov15** [comment]
Can you connect to the replica set using the mongodb shell? If you can connect using the shell then it might be a mongoose issue, if you can't then it's probably a network issue

**Comment by roneichiarandi** [comment]
@vkarpov15, yes, I connect in mongodb shell, the problem is when I insert the options after the uri servers `mongoose.connect('host:port','host2:port/database', options)`

I resolve this passing the options directly on the URI
`mongoose.connect('host:port','host2:port/database?options')`

But I belive that is a mongoose issue.

Thanks.

**Comment by vkarpov15** [comment]
What options are you passing?

**Comment by roneichiarandi** [comment]
Sorry, I created a new options and now has connected.
