### ISSUE TITLE
4.6.4 Cannot read property 'commandsTakeWriteConcern' of null

### ISSUE THREAD

**Issue by Amri91** [Automattic/mongoose#4634]
This is almost the same as issue #4490 
I am still having the same issue even after updating to 4.6.4

4.5.9 works fine.

TypeError: Cannot read property 'commandsTakeWriteConcern' of null
      at decorateWithWriteConcern (node_modules\mongodb\lib\db.js:485:55)
      at Db.dropDatabase (node_modules\mongodb\lib\db.js:874:3)
      at Function.module.exports.reset (node_modules\mockgoose\Mockgoose.js:159:32)
      at Context.<anonymous> (out\test\testUtilities\mockGooseInit.js:55:13)

Using 4.6.4, I was able to make it work by modifying line 485 in mongoose/node_modules/mongodb/lib/db.js
to
if(self.s.topology && self.s.topology.capabilities() && self.s.topology.capabilities().commandsTakeWriteConcern) {

Update: I was unable to reproduce the issue on linux

**Comment by vkarpov15** [comment]
Use this instead:

```javascript
mongoose.connection.dropDatabase(error => {
  console.log('Error', error);
  process.exit(0);
});
```
