### ISSUE TITLE
Dynamic refs in an array of subdocuments raise an error if some refs aren't set

### ISSUE THREAD

**Issue by n-rook** [Automattic/mongoose#4637]
In a schema, I have an array of subdocuments. The subdocument schema being used contains a dynamic ref. If I try to save an instance of the parent document, and some of the subdocuments in the array don't have the dynamic ref value set, I get this error:

```
Unhandled rejection MissingSchemaError: Schema hasn't been registered for model "undefined".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (/Users/nrook/code/mongoose-minimal-error/node_modules/mongoose/lib/connection.js:758:11)
    at getModelsMapForPopulate (/Users/nrook/code/mongoose-minimal-error/node_modules/mongoose/lib/model.js:2996:18)
    at populate (/Users/nrook/code/mongoose-minimal-error/node_modules/mongoose/lib/model.js:2636:15)
    at _populate (/Users/nrook/code/mongoose-minimal-error/node_modules/mongoose/lib/model.js:2604:5)
    at Function.Model.populate (/Users/nrook/code/mongoose-minimal-error/node_modules/mongoose/lib/model.js:2564:5)
    at model.populate (/Users/nrook/code/mongoose-minimal-error/node_modules/mongoose/lib/document.js:2451:22)
    at /Users/nrook/code/mongoose-minimal-error/node_modules/mongoose/lib/document.js:2487:11
    at Promise._execute (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/promise.js:77:14)
    at model.Document.execPopulate (/Users/nrook/code/mongoose-minimal-error/node_modules/mongoose/lib/document.js:2486:10)
    at /Users/nrook/code/mongoose-minimal-error/index.js:42:42
    at tryCatcher (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/nrook/code/mongoose-minimal-error/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Script used to reproduce:
```
const mongoose = require('mongoose');
const Promise = require('bluebird');

mongoose.Promise = Promise;
const connection = mongoose.connect('mongodb://localhost/minimal', {});

const baseballSchema = mongoose.Schema({
  seam: String,
});
const Baseball = mongoose.model('Baseball', baseballSchema);

const ballSchema = mongoose.Schema({
  league: String,
  kind: String,
  ball: {
    type: mongoose.Schema.Types.ObjectId,
    refPath: 'balls.kind'
  }
});

const basketSchema = mongoose.Schema({
  balls: [ballSchema]
});
const Basket = mongoose.model('Basket', basketSchema);

new Baseball({seam: 'yarn'}).save()
  .then((baseball) => {
    return new Basket({
      balls: [
        {
          league: 'MLB',
          kind: 'Baseball',
          ball: baseball._id,
        },
        {
          league: 'NBA'
        }  // This subdocument is the one causing the exception
      ]
    }).save();
  })
  .then((basket) => {
    return basket.populate('balls.ball').execPopulate();
  })
  .then((basket) => {
    console.log('Success!');
  });
```

**Comment by vkarpov15** [comment]
Thanks for the detailed repro, will be fixed in next release :+1:

**Comment by umimehar** [comment]
I have same error. i am using 5.0.5 Mongoose. Can anyone tell me the solution. i am also using refPath as dynamic ref.

**Comment by lineus** [comment]
@umimehar please open a new issue with a reproducible code sample that shows the problem you are experiencing. Thanks!
