### ISSUE TITLE
How to set 'setCurrentLogger' as in the native driver

### ISSUE THREAD

**Issue by tomgrossman** [Automattic/mongoose#4677]
I'm trying to change the mongoose console log printing using the `setCurrentLogger` function as described [here](http://mongodb.github.io/node-mongodb-native/2.2/api/Logger.html#.setCurrentLogger) and in the tutorial for older mongo driver [here](http://mongodb.github.io/node-mongodb-native/2.0/tutorials/logging/#custom-logger:3f3af53408cff75953b33723c0b061bb). I didn't find any instructions to do that with mongoose only with the native mongodb driver.

In order to test it, I just tried changing only the printed `msg`:
```javascript
var mongoose        = require("mongoose");
var MongooseLogger  = mongoose.mongo.Logger;

MongooseLogger.setCurrentLogger(function(msg, context) {
    console.log("aaaaaa", context);
});
```

But it doesn't seems to work, I'm still getting the full error stack priting on console, instead of the expected `aaaaaa`.

The question is, how to change the logger function in `mongoose` like the `setCurrentLogger` function described for the native driver

**Comment by vkarpov15** [comment]
Below script works fine for me:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4677');
mongoose.set('debug', true);

var MongooseLogger  = mongoose.mongo.Logger;

MongooseLogger.setLevel('debug');

MongooseLogger.setCurrentLogger(function(msg, context) {
    console.log("aaaaaa", context);
});

var M = mongoose.model('Test', { name: String });

M.findOne({}, function(error) {
  assert.ifError(error);
  process.exit(0);
});
```

```
$ node gh-4677.js 
aaaaaa { type: 'info',
  message: 'server localhost:27017 fired event connect out with message [object Object]',
  className: 'Server',
  pid: 28683,
  date: 1478539346499 }
aaaaaa { type: 'debug',
  message: 'writing buffer [0b0100000100000000000000d40700000400000061646d696e2e24636d640000000000ffffffff] to localhost:27017',
  className: 'Connection',
  pid: 28683,
  date: 1478539346507 }
aaaaaa { type: 'debug',
  message: 'writing buffer [e40000000869736d6173746572000103636c69656e7400cc00000003647269766572002a000000026e616d6500070000006e6f64656a73000276657273696f6e0007000000322e322e31310000036f73005a000000027479706500060000004c696e757800026e616d6500060000006c696e757800026172636869746563747572650004000000783634000276657273696f6e0012000000332e31362e302d34332d67656e65726963000002706c6174666f726d00290000004e6f64652e6a732076362e392e302c204c452c206d6f6e676f64622d636f72653a20322e302e3133000000] to localhost:27017',
  className: 'Connection',
  pid: 28683,
  date: 1478539346508 }
aaaaaa { type: 'debug',
  message: 'message [c2000000ce220000010000000100000008000000000000000000000000000000010000009e0000000869736d61737465720001106d617842736f6e4f626a65637453697a650000000001106d61784d65737361676553697a65427974657300006cdc02106d61785772697465426174636853697a6500e8030000096c6f63616c54696d65004c02d03f58010000106d61785769726556657273696f6e0004000000106d696e5769726556657273696f6e0000000000016f6b00000000000000f03f00] received from localhost:27017',
  className: 'Pool',
  pid: 28683,
  date: 1478539346510 }
aaaaaa { type: 'info',
  message: 'server localhost:27017 connected with ismaster [{"ismaster":true,"maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":1000,"localTime":"2016-11-07T17:22:26.508Z","maxWireVersion":4,"minWireVersion":0,"ok":1}]',
  className: 'Server',
  pid: 28683,
  date: 1478539346514 }
Mongoose: tests.findOne({}, { fields: undefined })
aaaaaa { type: 'debug',
  message: 'issue initial query [{"find":"gh4677.tests","limit":-1,"skip":0,"query":{},"slaveOk":false,"batchSize":1,"virtual":false}] with flags [{"bson":{},"ns":"gh4677.$cmd","query":{"find":"tests","filter":{},"limit":1,"batchSize":1,"singleBatch":true},"options":{"numberToSkip":0,"numberToReturn":1,"checkKeys":false,"returnFieldSelector":null,"serializeFunctions":false,"ignoreUndefined":false},"numberToSkip":0,"numberToReturn":1,"returnFieldSelector":null,"requestId":2,"serializeFunctions":false,"ignoreUndefined":false,"maxBsonSize":16777216,"checkKeys":false,"batchSize":1,"tailable":false,"slaveOk":false,"oplogReplay":false,"noCursorTimeout":false,"awaitData":false,"exhaust":false,"partial":false,"documentsReturnedIn":"firstBatch"}]',
  className: 'Cursor',
  pid: 28683,
  date: 1478539346522 }
aaaaaa { type: 'debug',
  message: 'writing buffer [720000000200000000000000d4070000000000006768343637372e24636d64000000000001000000] to localhost:27017',
  className: 'Connection',
  pid: 28683,
  date: 1478539346524 }
aaaaaa { type: 'debug',
  message: 'writing buffer [4a0000000266696e6400060000007465737473000366696c746572000500000000106c696d6974000100000010626174636853697a6500010000000873696e676c654261746368000100] to localhost:27017',
  className: 'Connection',
  pid: 28683,
  date: 1478539346525 }
aaaaaa { type: 'debug',
  message: 'message [b7000000cf2200000200000001000000080000000000000000000000000000000100000093000000127761697465644d5300000000000000000003637572736f720068000000046669727374426174636800360000000330002e000000075f6964005820b7ec5f80326fcf9e0bfd026e616d6500050000007465737400105f5f7600000000000000126964000000000000000000026e73000d0000006768343637372e74657374730000016f6b00000000000000f03f00] received from localhost:27017',
  className: 'Pool',
  pid: 28683,
  date: 1478539346526 }
$ 
```

Are you setting the log level with `setLevel()` as recommended in the 2nd post you linked to?

**Comment by tomgrossman** [comment]
No, But I don't want the logs on debug, I just want the info logs not to show on the console. If I have to set on debug for it to work, I'll do it.

**Comment by vkarpov15** [comment]
Not sure I understand, can you clarify?

**Comment by tomgrossman** [comment]
You asked if I set the log level as recommended, but I didn't since I don't understand why it is needed to change the log level in order to change the logger function. But if you say it's required, I'll do it.

**Comment by tomgrossman** [comment]
@vkarpov15 I tried it, but I'm still getting error logs printing on console. Let's say for example I don't have a connection to the db, and my code is as you suggested:
```javascript
var MongooseLogger  = mongoose.mongo.Logger;
MongooseLogger.setLevel('debug');
MongooseLogger.setCurrentLogger(function(msg, context) {
    console.log("aaaaaa", context);
});
```

I'm getting the following error printing on console without any `aaaaa`:

> Unhandled rejection MongoError: failed to connect to server [localhost:1236] on first connect
    at eventHandler (/home/dashboard/src/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)

**Comment by vkarpov15** [comment]
Umm because that error is an exception thrown because of a failed connection. That doesn't go through the logger. Also, as an aside, that's the mongodb driver's logger, not the mongoose logger.

**Comment by tomgrossman** [comment]
so there is no way to handle it?

**Comment by vkarpov15** [comment]
Sure, `mongoose.connect(uri, function(error) {});` or `mongoose.connect(uri).catch(error => {});` or use co to catch the uncaught exception and log it wherever you want. Or `process.on('uncaughtException')` as a catch-all if you want to log any unhandled errors.
