### ISSUE TITLE
Populate to string field isn't working

### ISSUE THREAD

**Issue by vatex** [Automattic/mongoose#4686]
When I try to populate field which is string, it fails : message: 'Cast to ObjectId failed for value "37888F" at path "_id". I don't have _id field.
this is my one model:
Model 1 
field1: { type:String, ref: 'Model2' }

Model 2
field1: { type: String }

and my query looks like this:
Model1.populate(data, { path: 'field1', model: 'Model2' })

Full error log:
{ CastError: Cast to ObjectId failed for value "37888F" at path "_id"
    at MongooseError.CastError (/home/valeri/projects/123/server/node_modules/mongoose/lib/error/cast.js:19:11)
    at ObjectId.cast (/home/valeri/projects/123/server/node_modules/mongoose/lib/schema/objectid.js:147:13)
    at ObjectId.castForQuery (/home/valeri/projects/123/server/node_modules/mongoose/lib/schema/objectid.js:187:15)
    at /home/valeri/projects/123/server/node_modules/mongoose/lib/schematype.js:866:18
    at Array.map (native)
    at ObjectId.handleArray (/home/valeri/projects/123/server/node_modules/mongoose/lib/schematype.js:865:14)
    at ObjectId.castForQuery (/home/valeri/projects/123/server/node_modules/mongoose/lib/schema/objectid.js:185:20)
    at cast (/home/valeri/projects/123/server/node_modules/mongoose/lib/cast.js:177:39)
    at Query.cast (/home/valeri/projects/123/server/node_modules/mongoose/lib/query.js:2650:10)
    at Query.find (/home/valeri/projects/123/server/node_modules/mongoose/lib/query.js:1130:10)
    at /home/valeri/projects/123/server/node_modules/mongoose/lib/query.js:2227:21
    at new Promise.ES6 (/home/valeri/projects/123/server/node_modules/mongoose/lib/promise.js:45:3)
    at Query.exec (/home/valeri/projects/123/server/node_modules/mongoose/lib/query.js:2220:10)
    at populate (/home/valeri/projects/123/server/node_modules/mongoose/lib/model.js:2670:11)
    at _populate (/home/valeri/projects/123/server/node_modules/mongoose/lib/model.js:2576:5)
    at /home/valeri/projects/123/server/node_modules/mongoose/lib/model.js:2540:7
  message: 'Cast to ObjectId failed for value "37888F" at path "_id"',
  name: 'CastError',
  kind: 'ObjectId',
  value: '37888F',
  path: '_id',
  reason: undefined }

**Comment by ddennis** [comment]
I have something similar. 

```
TicketModel.findById(ticketId).populate({ path: 'tiles', populate: { path: 'bonusId', model: 'Bonus' }})
```

```
var bonusSchema = new Schema({
    advertiserName:String,
    title: String,
    description: String,  
    active: {type: Boolean, default: false},
    startDate: Date,
    endDate: Date  
});
```

```

var tilesSchema = new Schema( {
    advertiser:     {type: mongoose.Schema.Types.ObjectId, ref: 'Advertiser'},
    bonusId:   {type: mongoose.Schema.Types.ObjectId, ref: 'Bonus'},
    selected:   {type: Boolean, default: false},
    coin:   {type: Boolean, default: false},
    at: Date,
    name:String
});


var ticketSchema = new Schema( {
    userId: {type: mongoose.Schema.Types.ObjectId, ref: 'User'},
    createdOn: {type: Date, default: Date.now},
    completed: {type: Boolean, default: false},
    tiles: [tilesSchema] 
});


```
in version 4.5.2 it actually populates the **bonusId** with the full model object. In version **4.6.6** it only sets **bonusId** to the _id.

**Comment by vatex** [comment]
@ddennis Thank you! I'll try 4.5.2 version

**Comment by vkarpov15** [comment]
@ddennis why are you calling `populate()` on `tiles`? That's completely absurd, `tiles` is embedded, you should **not** call populate on it because you don't need to. `TicketModel.findById(ticketId).populate('tiles.bonusId')` is the right way to do it
