### ISSUE TITLE
Use prefixed internal properties to allow more freedom for schema path names

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4688]
This is likely going to be something for a next major release, but I'd like to see the limitations that are currently in place for restricted schema path names lifted, by using internal properties which are prefixed with `_` or `$` or anything else, so that users are free to use any non-prefixed path name they like.

I've run into this limitation twice now, where I wanted to have `isNew` and `collection` as my document properties. (It's surprisingly hard to find a synonym for `isNew` that is as concise and to the point.)

So I'm throwing it up here for discussion, what do you think?

**Comment by vkarpov15** [comment]
Yeah that's definitely something I want to see, `isNew` -> `$isNew` and `save` -> `$save` because mongodb doesn't let you save keys that start with `$` anyway.

**Comment by adamreisnz** [comment]
Just got bugged by this again. Apparently `isImmediate` is also a restricted property.
Threw some vague error like:

```
Mongoose: transactions.remove({ isImmediate: true, _id: { '$in': [ ObjectId("59e2b84ed5d15523343dc238") ] } }, {})
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: callback.apply is not a function
    at Immediate.<anonymous> (node_modules/mongoose/lib/model.js:3919:16)
    at Immediate._onImmediate (node_modules/mquery/lib/utils.js:137:16)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
```

**Comment by adamreisnz** [comment]
If it'll take a while for this to be released, could Mongoose issue a warning when "reserved" property names are detected in a schema?

**Comment by vkarpov15** [comment]
It already does, mongoose throws an error if you try to use reserved property names like 'set'. If mongoose doesn't throw an error in that case, please let me know what property name you're getting an error with and we'll fix it.

**Comment by adamreisnz** [comment]
Sorry, it was my own fail in the end, which I mistakenly took for a reserved schema name error 🤦‍♂️
