### ISSUE TITLE
Closing #4602 led to unexpected exception being thrown

### ISSUE THREAD

**Issue by backmeupplz** [Automattic/mongoose#4702]
In our project we don't use virtuals at all, and everything works great on 4.6.6. However when we try to populate a nested field on our object on 4.6.7, we get this error thrown:
```
/home/deploy/arbeit-bot-1478849774002/node_modules/mongoose/lib/model.js:3002
Nov 11 08:15:59 arbeit-bot-ams node[6588]:       throw new Error('If you are populating a virtual, you must set the ' +
Nov 11 08:15:59 arbeit-bot-ams node[6588]:       ^
Nov 11 08:15:59 arbeit-bot-ams node[6588]: Error: If you are populating a virtual, you must set the localField and foreignField options
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at getModelsMapForPopulate (/home/deploy/arbeit-bot-1478849774002/node_modules/mongoose/lib/model.js:3002:13)
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at populate (/home/deploy/arbeit-bot-1478849774002/node_modules/mongoose/lib/model.js:2647:15)
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at _populate (/home/deploy/arbeit-bot-1478849774002/node_modules/mongoose/lib/model.js:2615:5)
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at Function.Model.populate (/home/deploy/arbeit-bot-1478849774002/node_modules/mongoose/lib/model.js:2575:5)
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at Immediate.<anonymous> (/home/deploy/arbeit-bot-1478849774002/node_modules/mongoose/lib/query.js:1276:17)
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at Immediate.<anonymous> (/home/deploy/arbeit-bot-1478849774002/node_modules/mquery/lib/utils.js:137:16)
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at runCallback (timers.js:570:20)
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at tryOnImmediate (timers.js:550:5)
Nov 11 08:15:59 arbeit-bot-ams node[6588]:     at processImmediate [as _immediateCallback] (timers.js:529:5)
```
which I suppose wasn't intended :)

It can also be the case that this commit caused the issue: https://github.com/Automattic/mongoose/commit/1ec902212d1f943909cb0cf3c71f7efa4570c87d.

I'm just letting you know :) We are using 4.6.6 and pretty happy with it so far. Thank you!

**Comment by backmeupplz** [comment]
Please excuse me for this code, but I decided to attach the exact method that is causing the issue and the schemas used to complete the picture:
```js
function getSupercategories(language) {
  const match = (language) ?
  {
    $and: [
      { busy: false },
      { bio: { $exists: true } },
      { hourly_rate: { $exists: true } },
      { languages: { $in: [language._id || language] } },
    ],
  } :
  {
    $and: [
      { busy: false },
      { bio: { $exists: true } },
      { hourly_rate: { $exists: true } },
    ],
  };

  return new Promise((fullfill) => {
    Supercategory.find({})
      .sort('title')
      .populate({
        path: 'categories',
        populate: {
          path: 'freelancers',
          match,
          options: {
            sort: {
              name: -1,
            },
          },
        },
      })
      .exec((err, categories) => {
        if (err) throw err;
        else fullfill(categories);
      });
  });
}
```

```js
const mongoose = require('mongoose');

/** Schema */
const Schema = mongoose.Schema;
const supercategorySchema = new Schema({
  title: String,
  categories: [{
    type: Schema.ObjectId,
    ref: 'category',
    required: true,
    default: [],
  }],
});

module.exports = mongoose.model('supercategory', supercategorySchema);
```

```js
const mongoose = require('mongoose');

/** Schema */
const Schema = mongoose.Schema;
const categorySchema = new Schema({
  title: String,
  freelancers: [{
    type: Schema.ObjectId,
    ref: 'user',
    required: true,
    default: [],
  }],
});

module.exports = mongoose.model('category', categorySchema);
```

```js
const mongoose = require('mongoose');
const strings = require('../helpers/strings');

/** Schema */
const Schema = mongoose.Schema;
const userSchema = new Schema({
  id: Number,
  first_name: String,
  last_name: String,
  username: String,
  bio: String,
  hourly_rate: String,
  input_state: String,
  input_state_data: String,
  ban_state: {
    type: Boolean,
    default: false,
  },
  rate: {
    type: Number,
    required: true,
    default: 0,
  },
  positiveRate: {
    type: Number,
    required: true,
    default: 0,
  },
  sortRate: {
    type: Number,
    required: true,
    default: 0,
  },
  reports: [{
    type: Schema.ObjectId,
    ref: 'report',
  }],
  reportedBy: [{
    type: Schema.ObjectId,
    ref: 'user',
  }],
  reviews: [{
    type: Schema.ObjectId,
    ref: 'review',
    required: true,
    default: [],
  }],
  writeReview: [{
    type: Schema.ObjectId,
    ref: 'review',
    required: true,
    default: [],
  }],
  busy: {
    type: Boolean,
    required: true,
    default: false,
  },
  categories: [{
    type: Schema.ObjectId,
    ref: 'category',
    required: true,
    default: [],
  }],
  languages: [{
    type: Schema.ObjectId,
    ref: 'language',
  }],
  jobs: [{
    type: Schema.ObjectId,
    ref: 'job',
    required: true,
    default: [],
  }],
  job_drafts: [{
    type: Schema.ObjectId,
    ref: 'job',
    requred: true,
    default: [],
  }],
  current_job_draft: {
    type: Schema.ObjectId,
    ref: 'job',
  },
  report_draft: {
    type: Schema.ObjectId,
    ref: 'job',
  },
  specialSymbol: String,
});

module.exports = mongoose.model('user', userSchema);
```

**Comment by baldercm** [comment]
We are facing the same issue with version 4.6.7 and confirm it was working on version 4.6.6.

**Comment by vkarpov15** [comment]
@baldercm below script works just fine. Please make sure your repro script actually reproduces your issue next time.

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4702');
mongoose.set('debug', true);

const orderSchema = new mongoose.Schema({
  comments:   { type: String },
  products:   [{
    name:         { type: String, required: true },
    description:  { type: String },
    price:        { type: Number, required: true },
    extras:       [{ type: Schema.Types.ObjectId, ref: 'Extra' }],
    options:      [{ type: Schema.Types.ObjectId, ref: 'Option' }],
    comments:     { type: String },
  }],
})
const extraSchema = new mongoose.Schema({
  name:       { type: String, required: true },
  price:      { type: Number, required: true },
})

var Order = mongoose.model('Order', orderSchema);
var Extra = mongoose.model('Extra', extraSchema);
var Option = mongoose.model('Option', new Schema({ name: String }));

Promise.all([ Extra.create({ name: 'test', price: 5 }), Option.create({ name: 'test' }) ]).
  then(res => Order.create({ products: [{ name: 'test', price: 5, extras: [res[0]._id], options: [res[1]._id] }] })).
  then(order => Order.findById(order._id).populate('products.extras products.options').exec()).
  then(order => {
    console.log(require('util').inspect(order, { depth: 10 }));
    process.exit(0);
  }).
  catch(error => {
    console.error(error);
    process.exit(-1);
  });
```

```
$ node gh-4702.js 
(node:6804) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Mongoose: extras.insert({ name: 'test', price: 5, _id: ObjectId("58290e429245d41a9400eea4"), __v: 0 })
Mongoose: options.insert({ name: 'test', _id: ObjectId("58290e429245d41a9400eea5"), __v: 0 })
Mongoose: orders.insert({ _id: ObjectId("58290e429245d41a9400eea6"), products: [ { name: 'test', price: 5, _id: ObjectId("58290e429245d41a9400eea7"), options: [ ObjectId("58290e429245d41a9400eea5") ], extras: [ ObjectId("58290e429245d41a9400eea4") ] } ], __v: 0 })
Mongoose: orders.findOne({ _id: ObjectId("58290e429245d41a9400eea6") }, { fields: undefined })
Mongoose: extras.find({ _id: { '$in': [ ObjectId("58290e429245d41a9400eea4") ] } }, { fields: undefined })
Mongoose: options.find({ _id: { '$in': [ ObjectId("58290e429245d41a9400eea5") ] } }, { fields: undefined })
{ _id: 58290e429245d41a9400eea6,
  __v: 0,
  products: 
   [ { name: 'test',
       price: 5,
       _id: 58290e429245d41a9400eea7,
       options: [ { _id: 58290e429245d41a9400eea5, name: 'test', __v: 0 } ],
       extras: [ { _id: 58290e429245d41a9400eea4, name: 'test', price: 5, __v: 0 } ] } ] }
$ 
```

**Comment by vkarpov15** [comment]
@backmeupplz please modify the below script to repro your issue, works fine for me on 4.6.7:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4702');
mongoose.set('debug', true);

const supercategorySchema = new Schema({
  title: String,
  categories: [{
    type: Schema.ObjectId,
    ref: 'category',
    required: true,
    default: [],
  }],
});

const Supercategory = mongoose.model('supercategory', supercategorySchema);

const categorySchema = new Schema({
  title: String,
  freelancers: [{
    type: Schema.ObjectId,
    ref: 'user',
    required: true,
    default: [],
  }],
});

const Category = mongoose.model('category', categorySchema);

const userSchema = new Schema({
  id: Number,
  name: String
});

const User = mongoose.model('user', userSchema);

User.create({ name: 'Val' }).
  then(user => Category.create({ title: 'JS', freelancers: [user._id] })).
  then(category => Supercategory.create({ title: 'Programming', categories: [category._id] })).
  then(supercat => {
    return Supercategory.find({ _id: supercat._id })
      .sort('title')
      .populate({
        path: 'categories',
        populate: {
          path: 'freelancers',
          options: {
            sort: {
              name: -1,
            },
          },
        }
      })
  }).
  then(supercat => {
    console.log(require('util').inspect(supercat, { depth: 10 }));
    process.exit(0);
  }).
  catch(error => {
    console.error(error);
    process.exit(-1);
  });
```

Output:

```
$ node gh-4702-2.js 
(node:6975) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Mongoose: users.insert({ name: 'Val', _id: ObjectId("5829107fbd26d91b3f22a428"), __v: 0 })
Mongoose: categories.insert({ title: 'JS', _id: ObjectId("5829107fbd26d91b3f22a429"), freelancers: [ ObjectId("5829107fbd26d91b3f22a428") ], __v: 0 })
Mongoose: supercategories.insert({ title: 'Programming', _id: ObjectId("5829107fbd26d91b3f22a42a"), categories: [ ObjectId("5829107fbd26d91b3f22a429") ], __v: 0 })
Mongoose: supercategories.find({ _id: ObjectId("5829107fbd26d91b3f22a42a") }, { sort: { title: 1 }, fields: undefined })
Mongoose: categories.find({ _id: { '$in': [ ObjectId("5829107fbd26d91b3f22a429") ] } }, { fields: undefined })
Mongoose: users.find({ _id: { '$in': [ ObjectId("5829107fbd26d91b3f22a428") ] } }, { sort: { name: -1 }, fields: undefined })
[ { _id: 5829107fbd26d91b3f22a42a,
    title: 'Programming',
    __v: 0,
    categories: 
     [ { _id: 5829107fbd26d91b3f22a429,
         title: 'JS',
         __v: 0,
         freelancers: [ { _id: 5829107fbd26d91b3f22a428, name: 'Val', __v: 0 } ] } ] } ]
$ 
```

------------------------------

Unrelated, but can you please do me a favor and fix the below code? It's some of the most soul-crushingly awkward promise code I've ever seen.

```javascript
return new Promise((fullfill) => {
    Supercategory.find({})
      .sort('title')
      .populate({
        path: 'categories',
        populate: {
          path: 'freelancers',
          match,
          options: {
            sort: {
              name: -1,
            },
          },
        },
      })
      .exec((err, categories) => {
        if (err) throw err;
        else fullfill(categories);
      });
  });
```

Really should be more like:

```javascript
return Supercategory.find({})
      .sort('title')
      .populate({
        path: 'categories',
        populate: {
          path: 'freelancers',
          match,
          options: {
            sort: {
              name: -1,
            },
          },
        },
      })
      .exec();
```

Or if you really want to wrap it in your own promise, at least make sure you use `reject(err)` and don't throw an exception in the callback because you'll just crash your server and miss the whole point of using promises.

**Comment by baldercm** [comment]
@vkarpov15 Sorry for the misleading example. As you say, your complete example works fine.

After some more tests I've found our issue, we were using a dynamic population path, using empty string for no population: ```.populate('')``` worked on 4.6.6 and throws error on 4.6.7.

The following example will throw error on 4.6.7

```javascript
'use strict';

var mongoose = require('mongoose');
mongoose.Promise = require('bluebird')
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4702');
mongoose.set('debug', true);

const orderSchema = new mongoose.Schema({
  comments:   { type: String },
  products:   [{
    name:         { type: String, required: true },
    description:  { type: String },
    price:        { type: Number, required: true },
    extras:       [{ type: Schema.Types.ObjectId, ref: 'Extra' }],
    options:      [{ type: Schema.Types.ObjectId, ref: 'Option' }],
    comments:     { type: String },
  }],
})

const extraSchema = new mongoose.Schema({
  name:       { type: String, required: true },
  price:      { type: Number, required: true },
})

const optionSchema = new Schema({
  name: String
})

var Order = mongoose.model('Order', orderSchema);
var Extra = mongoose.model('Extra', extraSchema);
var Option = mongoose.model('Option', optionSchema);

Promise.all([
    Extra.create({ name: 'test', price: 5 }),
    Option.create({ name: 'test' })
  ])
  .then(res => Order.create({ products: [{ name: 'test', price: 5, extras: [res[0]._id], options: [res[1]._id] }] }))
  .then(order => Order.find().populate('').exec())
  .then(order => {
    console.log(require('util').inspect(order, { depth: 10 }));
    process.exit(0);
  })
  .catch(error => {
    console.error(error);
    process.exit(-1);
  });
```

Output using 4.6.7:

```
Mongoose: extras.insert({ name: 'test', price: 5, _id: ObjectId("5829e7e3f16c0d4b110e1a6f"), __v: 0 })
Mongoose: options.insert({ name: 'test', _id: ObjectId("5829e7e3f16c0d4b110e1a70"), __v: 0 })
Mongoose: orders.insert({ _id: ObjectId("5829e7e3f16c0d4b110e1a71"), products: [ { name: 'test', price: 5, _id: ObjectId("5829e7e3f16c0d4b110e1a72"), options: [ ObjectId("5829e7e3f16c0d4b110e1a70") ], extras: [ ObjectId("5829e7e3f16c0d4b110e1a6f") ] } ], __v: 0 })
Mongoose: orders.find({}, { fields: undefined })
/Users/balder/git/orders/node_modules/mongoose/lib/model.js:3002
      throw new Error('If you are populating a virtual, you must set the ' +
      ^

Error: If you are populating a virtual, you must set the localField and foreignField options
    at getModelsMapForPopulate (/Users/balder/git/orders/node_modules/mongoose/lib/model.js:3002:13)
    at populate (/Users/balder/git/orders/node_modules/mongoose/lib/model.js:2647:15)
    at _populate (/Users/balder/git/orders/node_modules/mongoose/lib/model.js:2615:5)
    at Function.Model.populate (/Users/balder/git/orders/node_modules/mongoose/lib/model.js:2575:5)
    at Immediate.cb (/Users/balder/git/orders/node_modules/mongoose/lib/query.js:1103:17)
    at Immediate.<anonymous> (/Users/balder/git/orders/node_modules/mquery/lib/utils.js:137:16)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
```

Output using 4.6.6:
```
Mongoose: extras.insert({ name: 'test', price: 5, _id: ObjectId("5829e8357dd0e14b2c5fd278"), __v: 0 })
Mongoose: options.insert({ name: 'test', _id: ObjectId("5829e8357dd0e14b2c5fd279"), __v: 0 })
Mongoose: orders.insert({ _id: ObjectId("5829e8357dd0e14b2c5fd27a"), products: [ { name: 'test', price: 5, _id: ObjectId("5829e8357dd0e14b2c5fd27b"), options: [ ObjectId("5829e8357dd0e14b2c5fd279") ], extras: [ ObjectId("5829e8357dd0e14b2c5fd278") ] } ], __v: 0 })
Mongoose: orders.find({}, { fields: undefined })
[ { _id: 5829e8357dd0e14b2c5fd27a,
    __v: 0,
    products: 
     [ { name: 'test',
         price: 5,
         _id: 5829e8357dd0e14b2c5fd27b,
         options: [ 5829e8357dd0e14b2c5fd279 ],
         extras: [ 5829e8357dd0e14b2c5fd278 ] } ] } ]
```
