### ISSUE TITLE
Error message unclear for cast failures

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4729]
I get the following:

```
MongooseError: Cast to ObjectId failed for value "0" at path "_id"
    at CastError (node_modules/mongoose/lib/error/cast.js:26:11)
    at ObjectId.cast (node_modules/mongoose/lib/schema/objectid.js:147:13)
    at ObjectId.castForQuery (node_modules/mongoose/lib/schema/objectid.js:187:15)
    at cast (node_modules/mongoose/lib/cast.js:218:32)
    at model.Query.Query.cast (node_modules/mongoose/lib/query.js:2741:10)
    at castQuery (node_modules/mongoose/lib/query.js:2648:18)
    at model.Query.Query._findAndModify (node_modules/mongoose/lib/query.js:1857:17)
    at model.Query.Query._findOneAndUpdate (node_modules/mongoose/lib/query.js:1748:8)
    at node_modules/kareem/index.js:239:8
    at node_modules/kareem/index.js:18:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Since all of my 20 odd models and sub document schema's have an `_id` field, I have no idea where to even begin debugging this. There's no reference in the trace to any of my actual app files, and the trace ends here despite me having infinite stack traces enabled.

Could the error message be updated to indicate what model is involved? That would at least narrow it down quite a bit :)

**Comment by adambuczynski** [comment]
For this particular case, I discovered the error came from a `findByIdAndUpdate` call where `0` was passed as the ID.

**Comment by vkarpov15** [comment]
Yeah one of the odd quirks of async hooks is that even if you don't use a hook the actual `findOneAndUpdate()` happens asynchronously, which makes stack traces confusing. Would it be helpful if an error kept a reference to the mongoose doc?

**Comment by adambuczynski** [comment]
It might be. Is it possible for Mongoose to print the class name of the document with the error message?

**Comment by vkarpov15** [comment]
Good suggestion

**Comment by adambuczynski** [comment]
🎉
