### ISSUE TITLE
Schema's field can't have name `prototype`

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#4746]
```js
new Schema({
	prototype: {
		type: String
	}
});
```

```
TypeError: Cannot read property 'numAsyncPres' of undefined
	at model._lazySetupHooks (~/node_modules/hooks-fixed/hooks.js:177:49)
	at model.pre [as $pre] (~/node_modules/hooks-fixed/hooks.js:125:10)
	at ~/node_modules/mongoose/lib/document.js:2004:18
	at Array.forEach (native)
	at ~/node_modules/mongoose/lib/document.js:2002:26
	at Array.forEach (native)
	at model.Document.$__registerHooksFromSchema (~/node_modules/mongoose/lib/document.js:1942:23)
	at model.Document (~/node_modules/mongoose/lib/document.js:82:8)
	at model.Model (~/node_modules/mongoose/lib/model.js:48:12)
	at new model (~/node_modules/mongoose/lib/model.js:3229:13)
	at ~/node_modules/mongoose/lib/model.js:1864:51
	at ~/node_modules/mongoose/node_modules/async/internal/parallel.js:27:9
	at eachOfArrayLike (~/node_modules/mongoose/node_modules/async/eachOf.js:57:9)
	at exports.default (~/node_modules/mongoose/node_modules/async/eachOf.js:9:5)
	at _parallel (~/node_modules/mongoose/node_modules/async/internal/parallel.js:26:5)
	at parallelLimit (~/node_modules/mongoose/node_modules/async/parallel.js:85:26)
	at ~/node_modules/mongoose/lib/model.js:1882:5
	at Function.create (~/node_modules/mongoose/lib/model.js:1852:17)
	at AbstractModel.abstractModelWrapper [as create] (~/server/models/abstract/abstract.js:131:10)
	at VehicleController.wrapper [as create] (~/server/controllers/abstract/abstract.js:107:10)
	at ~/server/controllers/main/vehicle.js:46:17
	at _combinedTickCallback (internal/process/next_tick.js:67:7)
	at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by TrejGun** [comment]
also it appears i can't have virtual field because of this

```js
Model
	.virtual("prototype")
	.get(function getPrototype() {
		return this.xPrototype;
	})
	.set(function setPrototype(prototype) {
		this.xPrototype = prototype;
	});
```

probably virtual population doesn't work too
