### ISSUE TITLE
TypeError: schematype.castForQuery is not a function

### ISSUE THREAD

**Issue by OuyangQianba** [Automattic/mongoose#4776]
Hi,
it seems there is a bug that  you will get this error if you had added a function to Object.prototype.
```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var Cat = mongoose.model('Cat', { name: String  });

var kitty = new Cat({ name: 'Zildjian'  });
kitty.save(function (err) {
    if (err) {
            console.log(err);
    } else {
            console.log('meow');
    }
});

Object.prototype.foo = ()=>1

Cat.find({},function(err,doc){
    if(err){
        console.log('err',err)
    }else {
      console.log("doc",doc)
    }
});
```
Error stack
```
err TypeError: schematype.castForQuery is not a function
    at cast (/tmp/mongoose/node_modules/mongoose/lib/cast.js:218:32)
    at Query.cast (/tmp/mongoose/node_modules/mongoose/lib/query.js:2742:12)
    at Query.find (/tmp/mongoose/node_modules/mongoose/lib/query.js:1144:10)
    at Function.find (/tmp/mongoose/node_modules/mongoose/lib/model.js:1212:13)
    at Object.<anonymous> (/tmp/mongoose/test.js:24:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

```

Mongoose version:4.7.1

if you delete Objecct.prototype.foo = ()=>1 , nothing goes wrong.

**Comment by vkarpov15** [comment]
As a workaround, use:

```javascript
Object.defineProperty(Object.prototype, 'foo', {
  enumerable: false,
  value: () => 1
});
```

Mongoose doesn't do a good job of using `hasOwnProperty()` to avoid inherited properties, so to be safe I'd recommend using `enumerable: false`

**Comment by harryac07** [comment]
I have kind of same error. But, in my case it occured during the passport authentication using local-passport. The strange part is, it only occured sometimes. Rest of the time, login is successful.

Here is my code : 

    passport.use('local',new LocalStrategy({
		usernameField: 'email'
	},
	function(username, password, done) {
		console.log('username in line 17 passport  : '+username);
		// Upto here, it gives email as a username successfully
		User.findOne({
			email: username
		}).exec(function(err, user) {
			console.log(user); // prints undefined and gives error
			if (err) {
				// gives error here
				return done(err);
			}
			if (!user) {
				return done(null, false, {
					"message": "Incorrect Username."
				});
			}
			if (!user.validPassword(password)) {
				return done(null, false, {
					"message": "Incorrect Password." + password
				});
			}
			console.log(user);
			return done(null, user);

		});
	}
    ));

But it works fine until and unless I started sending message in my clientside inside input field. I have used jQuery keyPress event with e.which=13. If I trigger this event I failed logging in using passport and following errors appear.

    TypeError: schematype.castForQuery is not a function
    at cast (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/cast.js:229:32)
    at Query.cast (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/query.js:2753:12)
    at Query.findOne (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/query.js:1353:10)
    at /Users/Harry/Desktop/socketio/node_modules/mongoose/lib/query.js:2310:21
    at new Promise.ES6 (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/promise.js:45:3)
    at Query.exec (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/query.js:2304:17)
    at Strategy._verify (/Users/Harry/Desktop/socketio/app_api/config/passport.js:20:6)
    at Strategy.authenticate (/Users/Harry/Desktop/socketio/node_modules/passport-local/lib/strategy.js:90:12)
    at attempt (/Users/Harry/Desktop/socketio/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/Users/Harry/Desktop/socketio/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at module.exports.login (/Users/Harry/Desktop/socketio/app_api/controllers/authentication.js:303:4)
    at Layer.handle [as handle_request] (/Users/Harry/Desktop/socketio/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Harry/Desktop/socketio/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/Harry/Desktop/socketio/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Harry/Desktop/socketio/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Harry/Desktop/socketio/node_modules/express/lib/router/index.js:277:22

**Comment by giokara** [comment]
Getting the same error as harryac07 with passport and basic strategy. The authentication worked for a while, but now is broken. Another app using the same authentication strategy and mongo library still works though...
