### ISSUE TITLE
Simple Mongoose progarm doesn't connect to MongoDB  - Redhat Linux 7.1

### ISSUE THREAD

**Issue by raviinder** [Automattic/mongoose#4787]
Following environment for Mongoose application. 
OS Linux :- Red hat 7.1
NodeJs version :- v7.2.0
MongoDB community verion :- 3.2

//Simple Mongoose application 
var mongoose = require('mongoose');
mongoose.set ('debug',true);
mongoose.connect('mongodb://localhost/test');
var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function callback () {
  console.log("h");
});

exports.test = function(req,res) {
  res.render('test');
};

************************ 
When i run this program by following command 
  node app.js 
Output of program is :- 
node app.js 
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/temptest/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

It does nothing it will keep on waiting for connection, altough from MongoDB console output i could see connection is setup. 
Enabled debug logs from Mongoose but luck nothing is happened not even logs are getting printed.

Here is output for Mongo DB output console. 
**********************************************************************************************
2016-12-08T16:04:48.442-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:50950 #21 (1 connection now open)
2016-12-08T16:04:48.444-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:50951 #22 (2 connections now open)
2016-12-08T16:04:48.444-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:50952 #23 (3 connections now open)
2016-12-08T16:04:48.444-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:50953 #24 (4 connections now open)
2016-12-08T16:04:48.445-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:50954 #25 (5 connections now open)
2016-12-08T16:04:48.448-0500 I COMMAND  [conn21] command test.$cmd command: isMaster { ismaster: 1 } keyUpdates:0 writeConflicts:0 numYields:0 reslen:178 locks:{} protocol:op_query 0ms
*******************************************************************************************************

Is something broken with latest Mongoose on Redhat ( just guessing ) or any help to debug further would be appreciated.

**Comment by raviinder** [comment]
I tried on Redhat 7.2 which i had to do anyways . It worked. So closing this issue.
