### ISSUE TITLE
Error while casting date

### ISSUE THREAD

**Issue by alejandroAtArterisk** [Automattic/mongoose#4798]
I'm getting an error while trying to retrieve data with a field which type is date, the field in model looks like this `fecha: {type: Date, default: Date.now}`. I decided to update all values through the console, maybe one of those was corrupted and now the fields value is **"fecha" : ISODate("2016-12-12T20:34:05.485Z")** but when i query I'm getting the same error.
The trace:
`Cast to date failed for value "{}" at path "fecha" for model "Marca"↵    at MongooseError.CastError (/var/www/html/panxter-back/node_modules/mongoose/lib/error/cast.js:26:11)↵    at SchemaDate.cast (/var/www/html/panxter-back/node_modules/mongoose/lib/schema/date.js:246:9)↵    at SchemaDate.castForQuery (/var/www/html/panxter-back/node_modules/mongoose/lib/schema/date.js:280:17)↵    at cast (/var/www/html/panxter-back/node_modules/mongoose/lib/cast.js:192:34)↵    at Query.cast (/var/www/html/panxter-back/node_modules/mongoose/lib/query.js:2742:12)↵    at Query.find (/var/www/html/panxter-back/node_modules/mongoose/lib/query.js:1144:10)↵    at /var/www/html/panxter-back/node_modules/mongoose/lib/query.js:2300:21↵    at Promise._execute (/var/www/html/panxter-back/node_modules/bluebird/js/release/debuggability.js:299:9)↵    at Promise._resolveFromExecutor (/var/www/html/panxter-back/node_modules/bluebird/js/release/promise.js:481:18)↵    at new Promise (/var/www/html/panxter-back/node_modules/bluebird/js/release/promise.js:77:14)↵    at Query.exec (/var/www/html/panxter-back/node_modules/mongoose/lib/query.js:2294:17)↵`

**Comment by alejandroAtArterisk** [comment]
My bad
