### ISSUE TITLE
Mongoose not recognize option authSource

### ISSUE THREAD

**Issue by rbiruel** [Automattic/mongoose#4818]
I have a replicaset on MongoDB Atlas with a production database (MY_DATABASE) and other admin database (MY_ADMIN_DATABASE) to authorize connections. 

I have connect with mongo shell perfectly using the following connection string:

```
$ mongo "mongodb://MY_SERVER-shard-00-00-clv3h.mongodb.net:27017,MY_SERVER-shard-00-01-clv3h.mongodb.net:27017,MY_SERVER-shard-00-02-clv3h.mongodb.net:27017/MY_DATABASE?replicaSet=MY_REPLICASET-NAME-shard-0" --ssl --username MY_USERNAME --password MY_PASSWORD --authenticationDatabase MY_ADMIN_DATABASE
```

When I use mongojs, it connects without problem using the following code:

```
// connection string using mongojs:
  var uri = 'mongodb://MY_USER:MY_PASSWORD@' +
    'MY_SERVER-shard-00-00-clv3h.mongodb.net:27017,' +
    'MY_SERVER-shard-00-01-clv3h.mongodb.net:27017,' +
    'MY_SERVER-shard-00-02-clv3h.mongodb.net:27017/MY_DATABASE';

  var options = {
    ssl: true,
    authSource: 'MY_ADMIN_DATABASE',
    replicaSet: 'MY_REPLICASET_NAME-shard-0'
  };

  var db = mongojs(uri,'', options);
```

When I use mongoose, I receive authentication fail message, this is my code:

```
// connection string using mongoose:
  var uri = 'mongodb://MY_USER:MY_PASSWORD@' +
    'MY_SERVER-shard-00-00-clv3h.mongodb.net:27017,' +
    'MY_SERVER-shard-00-01-clv3h.mongodb.net:27017,' +
    'MY_SERVER-shard-00-02-clv3h.mongodb.net:27017/MY_DATABASE';

  var options = {
    replset: {
      ssl: true,
      authSource: 'MY_ADMIN_DATABASE',
      rs_name: 'MY_REPLICASET_NAME-shard-0'
    }
  };

  mongoose.connect(uri, options);
  var db = mongoose.connection;
```

I've tried including user: and pass: on options, removing MY_USER:MY_PASSWORD@ from uri, change rs_name to replicaSet, every unsuccessful attempt. It seems that mongoose is not considering the authSource option.

This is the error log:
```
Unhandled rejection MongoError: authentication fail
    at Function.MongoError.create (/Users/Biruel/Dropbox/dev/projetos/jarvis/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/Biruel/Dropbox/dev/projetos/jarvis/node_modules/mongodb-core/lib/topologies/replset.js:1188:54
    at /Users/Biruel/Dropbox/dev/projetos/jarvis/node_modules/mongodb-core/lib/connection/pool.js:724:7
    at /Users/Biruel/Dropbox/dev/projetos/jarvis/node_modules/mongodb-core/lib/connection/pool.js:700:20
    at /Users/Biruel/Dropbox/dev/projetos/jarvis/node_modules/mongodb-core/lib/auth/scram.js:191:18
    at /Users/Biruel/Dropbox/dev/projetos/jarvis/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

If you need my real connection string, databases, replicaset name, user and password  from MongoDB Atlas to replicate the error, let me know.

Thanks so much
@RicardoBiruel

**Comment by rbiruel** [comment]
I resolved this issue putting the 'options' in 'uri' according to documentation ([http://mongoosejs.com/docs/connections.html]) on section 'Replica Set Connections'

```
  // connection string using mongoose:
  var uri = 'mongodb://MY_USER:MY_PASSWORD@' +
    'MY_SERVER-shard-00-00-clv3h.mongodb.net:27017,' +
    'MY_SERVER-shard-00-01-clv3h.mongodb.net:27017,' +
    'MY_SERVER-shard-00-02-clv3h.mongodb.net:27017/MY_DATABASE' +
    'ssl=true&replicaSet=MY_REPLICASET_NAME-shard-0&authSource=MY_ADMIN_DATABASE';

  mongoose.connect(uri);
  var db = mongoose.connection;
```

Now, it is working fine!
