### ISSUE TITLE
error in querying schematype.castForQuery is not a function

### ISSUE THREAD

**Issue by msxenon** [Automattic/mongoose#4863]
return new Promise(function(res,reject){
	
	Order_s.find({'added_by':userId,'status':{ $in :[o_added,o_packaged,o_picked,o_taken]}}).sort({created_in:"descending"}).populate({ 
						   path: 'taken_by'
					}).exec().then(function(err,res){
						if(err) return console.error('err getsorder',err);
					
						res('x')
					
				   		
					}).catch(function(e){
						console.error(e);
					})
});
returns error : 
TypeError: schematype.castForQuery is not a function
    at cast (/Users/mac/node_modules/mongoose/lib/cast.js:229:32)
    at Query.cast (/Users/mac/node_modules/mongoose/lib/query.js:2752:12)
    at Query.find (/Users/mac/node_modules/mongoose/lib/query.js:1143:10)
    at /Users/mac/node_modules/mongoose/lib/query.js:2310:21
    at tryCatcher (/Users/mac/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/mac/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/mac/node_modules/bluebird/js/main/promise.js:70:37)
    at Query.exec (/Users/mac/node_modules/mongoose/lib/query.js:2304:17)
    at /Users/mac/WebstormProjects/untitled/app.js:2394:9
    at tryCatcher (/Users/mac/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/mac/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/mac/node_modules/bluebird/js/main/promise.js:70:37)
    at get_s_orders_ (/Users/mac/WebstormProjects/untitled/app.js:2374:10)
    at get_s_orders (/Users/mac/WebstormProjects/untitled/app.js:2366:2)
    at Socket.<anonymous> (/Users/mac/WebstormProjects/untitled/app.js:2757:7)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (/Users/mac/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/mac/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/mac/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/mac/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/mac/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/Users/mac/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onPacket (/Users/mac/node_modules/socket.io/node_modules/engine.io/lib/socket.js:101:14)
    at emitOne (events.js:77:13)
    at WebSocket.emit (events.js:169:7)
    at WebSocket.Transport.onPacket (/Users/mac/node_modules/socket.io/node_modules/engine.io/lib/transport.js:104:8)
    at WebSocket.Transport.onData (/Users/mac/node_modules/socket.io/node_modules/engine.io/lib/transport.js:115:8)
    at WebSocket.onData (/Users/mac/node_modules/socket.io/node_modules/engine.io/lib/transports/websocket.js:76:30)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/Users/mac/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/mac/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/mac/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/mac/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/mac/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/Users/mac/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.<anonymous> (/Users/mac/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:493:33)
 
note:all npm and their models are up to date;

**Comment by varunjayaraman** [comment]
This is hard to reproduce with the current code snippet.

Could you post a reproduceable script or atleast give me the values those variables represent inside the query?

**Comment by varunjayaraman** [comment]
@msxenon any update on the repro script? Otherwise I'm going to close this as stale.
