### ISSUE TITLE
Unknown encoding: 1 (v.4.7.6)

### ISSUE THREAD

**Issue by ypanyukov** [Automattic/mongoose#4864]
TypeError: Unknown encoding: 1
    at Buffer.slowToString (buffer.js:487:17)
    at Buffer.toString (buffer.js:500:27)
    at ObjectID.toString (/node_modules/mongoose/node_modules/bson/lib/bson/objectid.js:174:20)
    at formatValue (util.js:352:36)
    at formatProperty (util.js:794:15)
    at util.js:654:12
    at Array.map (native)
    at formatObject (util.js:653:15)
    at formatValue (util.js:592:16)
    at formatValue (util.js:358:17)
    at inspect (util.js:186:10)
    at exports.format (util.js:72:24)
   .....
    at nextTask (/node_modules/async/dist/async.js:5070:14)
    at /node_modules/async/dist/async.js:5064:13
    at apply (/node_modules/async/dist/async.js:21:25)
    at /node_modules/async/dist/async.js:56:12
    at /node_modules/async/dist/async.js:840:16
    ...
    at /node_modules/mongoose/lib/query.js:2323:18
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

NodeJS - 7.3.0
Mongoose - 4.7.6

**Comment by kyrylkov** [comment]
Same problem

**Comment by kyrylkov** [comment]
Seems to be related to bson upgrade https://github.com/Automattic/mongoose/commit/8f39e1b8741b89caa605d24ccca081b54fdfbd94

**Comment by kyrylkov** [comment]
@ypanyukov there was a bug introduce in bson 1.0.2 which was fixed a couple of hours ago in 1.0.3 https://github.com/mongodb/js-bson/commit/35f5264446fb74e475ecf25f94ce7b177b5b35fd

Re-intstall all dependencies and see if it works now

**Comment by adammpolak** [comment]
@harangue updating to the latest mongo and mongoose had this "magically taken care of" :)

**Comment by vkarpov15** [comment]
Tbh the best solution would just be to deprecate bson 1.0.2 . mongoose needs to have the same package.json entry for bson as mongodb-core to avoid potential conflicts
