### ISSUE TITLE
query.limit() does not work in combination with .cursor()

### ISSUE THREAD

**Issue by fiws** [Automattic/mongoose#4902]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
Debug: internal, implementation, error 
    MongoError: unknown top level operator: $limit
    at Function.MongoError.create (/home/project/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/project/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /home/project/node_modules/mongodb-core/lib/connection/pool.js:457:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const query = Model.find({}).lean();
query.limit(1);
query.cursor().pipe(process.stdout);
```

**What is the expected behavior?**
limit the query, no error

**Please mention your node.js, mongoose and MongoDB version.**
* node 7
* mongoose 4.7.7
* mongodb 3.x

**Comment by fiws** [comment]
sorry, invalid. I had $limit in my query... hehehe
