### ISSUE TITLE
Null embedded doc with findOneAndUpdate and setDefaults fails

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#4911]
https://github.com/Automattic/mongoose/issues/2593#issuecomment-272169745

**Comment by yoadsn** [comment]
@vkarpov15 Thanks.
Is it OK if I will add all my comments here as well to give context to this Issue? Otherwise little chance it would get any attention/PR's thrown at it.

**Comment by vkarpov15** [comment]
Yep, please do so :+1:

**Comment by yoadsn** [comment]
Thanks for the fix!!

For future reference - Here is a simple repro of this issue:
```
 var EmbeddedSchema = mongoose.Schema({
      embeddedField: String
  }, { _id : true})

  var ParentSchema = mongoose.Schema({
      embedded: EmbeddedSchema
  })
  
  var Parent = mongoose.model('User', ParentSchema);

  var newDoc = {
      _id: new mongoose.Types.ObjectId(),
      embedded: null
  }

  Parent.findOneAndUpdate({ _id: newDoc._id }, newDoc, { upsert: true, setDefaultsOnInsert: true })
  .then(() => console.log('done'))
  .catch(err => console.error(err));
```
Would print out:
```
{ MongoError: Cannot update 'embedded._id' and 'embedded' at the same time
    at Function.MongoError.create (...\node_modules\mongodb-core\lib\error.js:31:11)
    at ...\node_modules\mongodb-core\lib\connection\pool.js:483:72
    at authenticateStragglers (...\node_modules\mongodb-core\lib\connection\pool.js:429:16)
    at Connection.messageHandler (...\node_modules\mongodb-core\lib\connection\pool.js:463:5)
    at Socket.<anonymous> (...\node_modules\mongodb-core\lib\connection\connection.js:317:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'MongoError',
  message: 'Cannot update \'embedded._id\' and \'embedded\' at the same time',
  ok: 0,
  errmsg: 'Cannot update \'embedded._id\' and \'embedded\' at the same time',
  code: 16836 }
```
