### ISSUE TITLE
Error no geo indices for geoNear

### ISSUE THREAD

**Issue by root-io** [Automattic/mongoose#4917]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```
const mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
const { Schema } = mongoose;

const GITHUB_ISSUE = `gh-4917`;
const connect = () => {
  mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);

  mongoose.connection.on('error', (err) => {
    console.error('Error', err);
  });
};

connect();

const UserSchema = new Schema({
  name: { $type: String },
  location: {
    type: { $type: String, default: 'Point' },
    coordinates: { $type: Array, default: [2.3488000, 48.8534100] }
  }
}, { typeKey: '$type' });
UserSchema.index({ location: '2dsphere' });

const User = mongoose.model('User', UserSchema);

const userId = '586d3620f6da431b4aec1a12';

let user = new User({
  _id: userId,
  name: 'test'
});

function getUserLocation() {
  return User.findById(userId)
    .then((user) => {
      return new Promise((resolve, reject) => {
        if (user && user.location) {
          resolve(user.location);
        } else {
          reject();
        }
      });
    });
}

function myAwesomeFunction(userLocation) {
  return User.aggregate([{
    $geoNear: {
      near: userLocation,
      distanceField: 'distance',
      maxDistance: 1000,
      spherical: true
    }
  }
  ]);
}

user.save()
  .then(getUserLocation)
  .then(myAwesomeFunction)
  .then(docs => console.log('docs', docs))
  .catch(error => console.error('error', error));
```

Error:
```
error { MongoError: geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: "no geo indices for geoNear" }
    at Function.MongoError.create (/project/node_modules/mongodb-core/lib/error.js:31:11)
    at /project/node_modules/mongodb-core/lib/connection/pool.js:485:72
    at authenticateStragglers (/project/node_modules/mongodb-core/lib/connection/pool.js:431:16)
    at Connection.messageHandler (/project/node_modules/mongodb-core/lib/connection/pool.js:465:5)
    at Socket.<anonymous> (/project/node_modules/mongodb-core/lib/connection/connection.js:319:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'MongoError',
  message: 'geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: "no geo indices for geoNear" }',
  ok: 0,
  errmsg: 'geoNear command failed: { waitedMS: 0, ok: 0.0, errmsg: "no geo indices for geoNear" }',
  code: 16604 }
```

**Please mention your node.js, mongoose and MongoDB version.**

Node.js 6.9.3
MongoDB 3.2.11
Mongoose 4.7.7

**Comment by vkarpov15** [comment]
You need to wait for the index to build:

```javascript
function getUserLocation() {
  return User.findById(user._id)
    .then((user) => {
      return new Promise((resolve, reject) => {
        if (user && user.location) {
          resolve(user.location);
        } else {
          reject();
        }
      });
    });
}

function myAwesomeFunction(userLocation) {
  return User.aggregate([{
    $geoNear: {
      near: userLocation,
      distanceField: 'distance',
      maxDistance: 1000,
      spherical: true
    }
  }
  ]);
}

function waitForIndex() {
  return new Promise((resolve, reject) => {
    User.on('index', error => error ? reject(error) : resolve());
  });
}

user.save()
  .then(waitForIndex)
  .then(getUserLocation)
  .then(myAwesomeFunction)
  .then(docs => console.log('docs', docs))
  .catch(error => console.error('error', error));
```

**Comment by sivaprakashg** [comment]
{
    "error": "model.geoNear is not a function"
