### ISSUE TITLE
Exception subclassing a Model

### ISSUE THREAD

**Issue by alexis-y** [Automattic/mongoose#4942]
I'm using ES6 classes to create a subclassed... class. However, when I try to setup the discriminator it throws an exception.

**Repro**
```JavaScript
class Shape extends Model { };
class Circle extends Shape { };
mongoose.model(Shape, new Schema({ color: String }));
Shape.discriminator(Circle, new Schema({ radius: Number })); // <<< Throws here
```

The relevant stack:
```
     Error: Virtual path "__v" conflicts with a real path in the schema
      at Schema.virtual (node_modules\mongoose\lib\schema.js:1483:11)
      at Schema.<anonymous> (node_modules\mongoose\lib\schema.js:1606:12)
      at Array.forEach (native)
      at Schema.loadClass (node_modules\mongoose\lib\schema.js:1595:47)
      at Schema.loadClass (node_modules\mongoose\lib\schema.js:1613:16)
      at Function.compile (node_modules\mongoose\lib\model.js:3243:12)
      at Mongoose.model (node_modules\mongoose\lib\index.js:408:22)
      at NativeConnection.Connection.model (node_modules\mongoose\lib\connection.js:753:23)
      at Function.discriminator (node_modules\mongoose\lib\model.js:884:39)
```

Out of curiosity, I disabled versioning too, to see if it was related to that as the error message implies

```JavaScript
mongoose.model(Shape, new Schema({ color: String }, { versionKey: false }));
Shape.discriminator(Circle, new Schema({ radius: Number }, { versionKey: false }));
```

But the exception remains:
```
     Error: Virtual path "_id" conflicts with a real path in the schema
      at Schema.virtual (node_modules\mongoose\lib\schema.js:1483:11)
      at Schema.<anonymous> (node_modules\mongoose\lib\schema.js:1606:12)
      at Array.forEach (native)
      at Schema.loadClass (node_modules\mongoose\lib\schema.js:1595:47)
      at Schema.loadClass (node_modules\mongoose\lib\schema.js:1613:16)
      at Function.compile (node_modules\mongoose\lib\model.js:3243:12)
      at Mongoose.model (node_modules\mongoose\lib\index.js:408:22)
      at NativeConnection.Connection.model (node_modules\mongoose\lib\connection.js:753:23)
      at Function.discriminator (node_modules\mongoose\lib\model.js:884:39)
```

**Version tested**
node 6.7.0
mongoose 4.7.7
mongodb none (this test is purely disconnected)

**Comment by varunjayaraman** [comment]
can you post your full repro script? There are variables in your schema that don't exist.

That being said, did you mean to pass in a string to `mongoose.model`'s first parameter?

```
const mongoose = require('mongoose')

try {
  class Shape extends mongoose.Model { };
  class Circle extends Shape { };
  const $Shape = mongoose.model('Shape', new mongoose.Schema({ color: String }));
  $Shape.discriminator(Circle, new mongoose.Schema({ radius: Number })); // <<< Throws here

} catch (error) {
  console.error(error);
}
```

**Comment by alexis-y** [comment]
I'm using the recently added ability to use ES6 classes (#4668).

Here's the whole mocha test:
```JavaScript
const assert = require('assert');
const { Model, Schema, Mongoose } = require('mongoose');

describe('this issue', () => {
  it('should allow subclassing', () => {

    let mongoose = new Mongoose();
    class Shape extends Model { };
    class Circle extends Shape { };
    mongoose.model(Shape, new Schema({ color: String }));
    Shape.discriminator(Circle, new Schema({ radius: Number })); // <<< Throws here

    let circle = new Circle();

    assert(circle instanceof Circle);
    assert(circle instanceof Shape);
  });
});
```

**Comment by varunjayaraman** [comment]
Thanks, ok I was able to reproduce with that snippet.
