### ISSUE TITLE
Problem upgrading from 4.5

### ISSUE THREAD

**Issue by mchapman** [Automattic/mongoose#4948]
**What is the current behavior?**
I am using Mongoose with gridform and gridfs-stream.  When I upgrade Mongoose to 4.6 or beyond I get an error

```
/home/mark/Projects/forms-angular/fng-jq-upload/node_modules/gridform/node_modules/gridfs-stream/lib/writestream.js:82
    throw new Error('GridWriteStream is not writable');
    ^

Error: GridWriteStream is not writable
    at Stream.write (/home/mark/Projects/forms-angular/fng-jq-upload/node_modules/gridform/node_modules/gridfs-stream/lib/writestream.js:82:11)
    at Stream.onData (/home/mark/Projects/forms-angular/fng-jq-upload/node_modules/gridform/lib/index.js:92:8)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at MultipartParser.parser.onPartData (/home/mark/Projects/forms-angular/fng-jq-upload/node_modules/gridform/node_modules/formidable/lib/incoming_form.js:378:14)
    at callback (/home/mark/Projects/forms-angular/fng-jq-upload/node_modules/gridform/node_modules/formidable/lib/multipart_parser.js:102:31)
    at MultipartParser.write (/home/mark/Projects/forms-angular/fng-jq-upload/node_modules/gridform/node_modules/formidable/lib/multipart_parser.js:286:11)
    at IncomingForm.write (/home/mark/Projects/forms-angular/fng-jq-upload/node_modules/gridform/node_modules/formidable/lib/incoming_form.js:157:34)
    at IncomingMessage.<anonymous> (/home/mark/Projects/forms-angular/fng-jq-upload/node_modules/gridform/node_modules/formidable/lib/incoming_form.js:123:12)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at IncomingMessage.Readable.push (_stream_readable.js:134:10)
    at HTTPParser.parserOnBody (_http_common.js:123:22)

```

**If the current behavior is a bug, please provide the steps to reproduce.**
So far I have not attempted to isolate a simple case, in the hope that it will not be necessary.  I have isolated the problem to the upgrade to mongodb 2.2.x.

**What is the expected behavior?**
File uploads have been working fine in my projects for several years.

**Please mention your node.js, mongoose and MongoDB version.**
Node 6.9.2
Mongoose >= 4.6.0
MongoDB >= 2.2.0

**Comment by varunjayaraman** [comment]
WIthout a repro script, I have no way of debugging this issue. That being said, if you've isolated the problem to the upgrade to mongodb 2.2.x, that's either a problem with the mongodb node driver or with gridform or gridfs-stream.

My guess is the problem is with gridform, which uses mongodb `1.4.3`, but I've never used the library so I can't be sure. You're better off opening an issue there though.

**Comment by mchapman** [comment]
Thanks for the advice - I think you are right,  Hopefully I will be able to fix it (the project is not maintained, by the looks of it).  You saved me some time with pointing me in the right direction, so thanks again.
