### ISSUE TITLE
TypeError: schematype.castForQuery is not a function

### ISSUE THREAD

**Issue by harryac07** [Automattic/mongoose#5002]
Hello,
I am stuck in one error. It occured during the passport authentication using local-passport. The strange part is, it only occured sometimes. Rest of the time, login is successful.
I made findeOne query to get data from database. Even though I had data with that reference, it shows the error : TypeError: schematype.castForQuery is not a function

I tried to find what the error is, but couldnot suceed.

Here is my code :

    passport.use('local',new LocalStrategy({
	  usernameField: 'email'
    },
    function(username, password, done) {
	   console.log('username in line 17 passport  : '+username);
	   // Upto here, it gives email as a username successfully
	User.findOne({
		email: username
	}).exec(function(err, user) {
		console.log(user); // prints undefined and gives error
		if (err) {
			// gives error here
			return done(err);
		}
		if (!user) {
			return done(null, false, {
				"message": "Incorrect Username."
			});
		}
		if (!user.validPassword(password)) {
			return done(null, false, {
				"message": "Incorrect Password." + password
			});
		}
		console.log(user);
		return done(null, user);

	});
    }
    ));
But it works fine until and unless I started sending message in my clientside inside input field. I have used jQuery keyPress event with e.which=13. If I trigger this event I failed logging in using passport and following errors appear.

    TypeError: schematype.castForQuery is not a function
    at cast (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/cast.js:229:32)
    at Query.cast (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/query.js:2753:12)
    at Query.findOne (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/query.js:1353:10)
    at /Users/Harry/Desktop/socketio/node_modules/mongoose/lib/query.js:2310:21
    at new Promise.ES6     (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/promise.js:45:3)
    at Query.exec (/Users/Harry/Desktop/socketio/node_modules/mongoose/lib/query.js:2304:17)
    at Strategy._verify (/Users/Harry/Desktop/socketio/app_api/config/passport.js:20:6)
    at Strategy.authenticate (/Users/Harry/Desktop/socketio/node_modules/passport-       local/lib/strategy.js:90:12)
    at attempt     (/Users/Harry/Desktop/socketio/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate     (/Users/Harry/Desktop/socketio/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at module.exports.login  (/Users/Harry/Desktop/socketio/app_api/controllers/authentication.js:303:4)
    at Layer.handle [as handle_request] (/Users/Harry/Desktop/socketio/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Harry/Desktop/socketio/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/Harry/Desktop/socketio/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Harry/Desktop/socketio/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Harry/Desktop/socketio/node_modules/express/lib/router/index.js:277:22

**Comment by varunjayaraman** [comment]
@harryac07 do you have no other context for this? And what version of node, mongoose, etc. are you using?

**Comment by harryac07** [comment]
Hello,
I am using Node 6.5.0, Mongoose 4.6.4. Actually I figured out that the error comes when I add function to Object.prototype. I had used this to return object key in my socket io server. But when I replace it with other function, then it works. The question is, why the request did not go through the mongoose findOne method if the request data is successfully reached upto there?

**Comment by harryac07** [comment]
@varunjayaraman I am using Node 6.5.0 and mongoose 4.6.4. Actually, I figured out the problem is with adding function to Object.prototype that I had used to return key from Object. when I replace that with other function, the code works and error does not show up. The question is, why could not  the query data go through mongoose findOne method if it could reach upto there when I use object.prototype.

        Object.prototype.getKey = function(value) {
	       for (var key in this) {
                if (this[key] == value) {
		         return key;
		    }
		}
		return null;
	    };

**Comment by varunjayaraman** [comment]
Hm I'm not sure, I'd need to see the context in which `getKey()` was used. Monkey patching / modifying the `Object` prototype is probably not a good idea, so you'd want to avoid doing that. Since javascript prototypes are singletons, mutating the prototype will have unintended side-effects, so it's usually best practice to just define a function that takes in an object and runs the same operation on it to `getKey` or whatever it is you're trying to do.
