### ISSUE TITLE
topology was destroyed

### ISSUE THREAD

**Issue by aniinprni** [Automattic/mongoose#5011]
Hi All, 
   i am using mongoose and node js . Recently we added one scheduler that will call a method every minute. That method is using aggregate function and based on result we are updating those values. 
Recently i am getting below error:
```
 { MongoError: topology was destroyed
     at executeCommand (/app/node_modules/mongoose/node_modules/mongodb/lib/db.js:298:76)
     at Db.command (/app/node_modules/mongoose/node_modules/mongodb/lib/db.js:340:44)
     at Collection.aggregate (/app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:2557:13)
     at NativeCollection.(anonymous function) [as aggregate] (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:125:28)
     at /app/node_modules/mongoose/lib/aggregate.js:576:10
     at new Promise.ES6 (/app/node_modules/mongoose/lib/promise.js:45:3)
     at Aggregate.exec (/app/node_modules/mongoose/lib/aggregate.js:562:10)
     at deAllocateCoupons (/app/my_module/cpMaster/couponsCmsServices/index.js:1296:5)
     at Timeout._onTimeout (/app/my_module/cpMaster/couponsCmsServices/index.js:1352:4) name: 'MongoError', message: 'topology was destroyed' }
```

I know that this question was already raised by so many but none helped me out. So i am again creating a new issue. **This issue causing us to restart the application every time**. 
Kindly Help me out.

**Comment by varunjayaraman** [comment]
Usually the `topology was destroyed` error message is produced when you're trying to run a db operation when you've closed the connection to the database. Is that happening at any point in your code / Can I see the method the scheduler is calling?

**Comment by varunjayaraman** [comment]
I don't think it's an issue with `aggregate()`, there must be something off with the connection. Are you sure you aren't reinitializing the connection to the db or closing it temporarily while this operation is going on? If you try to `.save()` when you do that it will cause a `topology was destroyed` error.

Also, could you specify what version of mongoose and node you're using?

**Comment by aniinprni** [comment]
Hi varun,

   i am using Node js ``7.2.1`` version and mongoose ``4.1.8`` version

**Comment by varunjayaraman** [comment]
4.1.8 or 4.8.1?

**Comment by aniinprni** [comment]
Hai, its 4.1.8 only

**Comment by varunjayaraman** [comment]
Can you try with the latest version of mongoose?

**Comment by varunjayaraman** [comment]
@aniinprni any update on using the latest version of mongoose?

**Comment by aniinprni** [comment]
Hai Varun, Thank you very much that was solved the issue.

   And Sorry i couldn't able to reply you on this.

**Comment by ORESoftware** [comment]
+1
