### ISSUE TITLE
timeout events bubbling up to the uncaughtException handler

### ISSUE THREAD

**Issue by randypuro** [Automattic/mongoose#5026]
We're seeing socket timeout events during inactivity bubbling up to the generic node uncaughtException handler. It is my assumption that the driver should recover from the events somewhat seamlessly.

I opened an issue, https://github.com/christkv/mongodb-core/issues/165, with mongodb-core but they're speculating the mongoose code here:

https://github.com/Automattic/mongoose/blob/bef9d78fac2482a28e33c485842cb1f7fb05837f/lib/drivers/node-mongodb-native/connection.js#L170

may be part of the problem as it's listening for those timeout events and recasting as error events.

Unfortunately, I think this symptom may be indicative of other issues as it sometimes appears the connections are not being recreated in a healthy way (I will subsequently see 120sec response times to simple queries).

Stack trace:

```
Error: connection timeout
        at Db.<anonymous> (./node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
        at emitTwo (events.js:106:13)
        at Db.emit (events.js:191:7)
        at Server.listener (./node_modules/mongodb/lib/db.js:1798:14)
        at emitOne (events.js:96:13)
        at Server.emit (events.js:188:7)
        at Server.<anonymous> (./node_modules/mongodb/lib/server.js:274:14)
        at emitOne (events.js:96:13)
        at Server.emit (events.js:188:7)
        at Pool.<anonymous> (./node_modules/mongodb-core/lib/topologies/server.js:335:12)
        at emitOne (events.js:96:13)
        at Pool.emit (events.js:188:7)
        at Connection.<anonymous> (./node_modules/mongodb-core/lib/connection/pool.js:270:12)
        at Connection.g (events.js:291:16)
        at emitTwo (events.js:106:13)
        at Connection.emit (events.js:191:7)
        at Socket.<anonymous> (./node_modules/mongodb-core/lib/connection/connection.js:185:10)
        at Socket.g (events.js:291:16)
        at emitNone (events.js:86:13)
        at Socket.emit (events.js:185:7)
        at Socket._onTimeout (net.js:339:8)
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
```

Connection details:

connection string:

`mongodb://localhost:27017/{dbname}?poolSize=15` connecting to mongo 3.2.8 running in docker.

with options:

`{server: {socketOptions: {keepAlive: 10000, connectTimeoutMS: 10000, socketTimeoutMS: 30000}}}`

**Comment by vkarpov15** [comment]
Yeah I think we'll switch to just transparently emitting the timeout event instead of changing timeouts to errors. That code is very old (#1006) and doesn't make sense anymore. Will hold off on that until 4.9 because this might be backwards breaking for some apps, but 4.9 should be out next week :+1:

**Comment by sedouard** [comment]
Hitting this too. https://github.com/Automattic/mongoose/commit/341556123a230eade305f67eed93e1a71e0263c6 resolves it. Patching my server with it until 4.9 is out. Thanks!
