### ISSUE TITLE
Array of Arrays stopped working

### ISSUE THREAD

**Issue by khuongduybui** [Automattic/mongoose#5032]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
I have an Activity model with the following schema:
```
const schema = mongoose.Schema({
  name: String,
  triggers: [ String ],
  inputs: [ [ String ] ] // Array of Arrays of Strings
});
```
When I try to run
```
    Activity.findOneAndUpdate({
      name: 'Host Discovery'
    }, {
      triggers: ['boundary-added'],
      inputs: [
        ['ipRange']
      ]
    }, {
      upsert: true
    }).exec()
```
I get the following error:
```
TypeError: Constructor is not a constructor
    at /home/duybui/code/sniper/sniper-master/node_modules/mongoose/lib/schema/array.js:232:15
    at Array.map (native)
    at SchemaArray.castForQuery (/home/duybui/code/sniper/sniper-master/node_modules/mongoose/lib/schema/array.js:223:17)
    at model.Query._castUpdateVal (/home/duybui/code/sniper/sniper-master/node_modules/mongoose/lib/query.js:2879:17)
    at model.Query._walkUpdatePath (/home/duybui/code/sniper/sniper-master/node_modules/mongoose/lib/query.js:2823:25)
    at model.Query._castUpdate (/home/duybui/code/sniper/sniper-master/node_modules/mongoose/lib/query.js:2695:23)
    at castDoc (/home/duybui/code/sniper/sniper-master/node_modules/mongoose/lib/query.js:2902:18)
    at model.Query.Query._findAndModify (/home/duybui/code/sniper/sniper-master/node_modules/mongoose/lib/query.js:1921:17)
    at model.Query.Query._findOneAndUpdate (/home/duybui/code/sniper/sniper-master/node_modules/mongoose/lib/query.js:1777:8)
```
**Please mention your node.js, mongoose and MongoDB version.**
node 7.6.0
mongoose 4.8.5
mongodb 2.6.10

**Comment by khuongduybui** [comment]
Note: I tried with mongodb 3.2, same situation

**Comment by serge-nikitin** [comment]
Are there any plans for date of release 4.8.7? Can't move on with this bug :(

**Comment by vkarpov15** [comment]
Will be released momentarily, thanks for your patience. We usually release patches on Sundays.
