### ISSUE TITLE
Setters of subdoc in array runs twice on update command

### ISSUE THREAD

**Issue by ValYouW** [Automattic/mongoose#5041]
Hi,

I am having an issue where the setters of some subdoc runs twice which causes my setter to throw an error on the 2nd time (as the input is not as expected...).
Here is simple case:
```javascript
var mongoose = require('mongoose');

mongoose.Promise = Promise;

var UserSchema = new mongoose.Schema({
	name: String,
	foos: [{
		_id: false,
		foo: {
			type: Number,
			get: function(val) {
				return val.toString();
			},
			set: function(val) {
				console.log('===>>> Setter called with type: %s, value: %s', typeof val, val);
				if (typeof val !== 'string') {
					throw new Error('Must be called with string');
				}

				var res = parseFloat(val);
				console.log('Returning:', res);
				return res;
			}
		}
	}]
}, {collection: 'users'});

var UserModel = mongoose.model('User', UserSchema);

var connStr = 'mongodb://test:test@127.0.0.1/test';
mongoose.connect(connStr);

console.log('Create some user');
var user = new UserModel({
	name: 'Jay',
	foos: [ {foo: '12.57'} ]
});
user.save().then(res => {
	res = res.toObject();
	console.log('User inserted successfully, User:', res);

	var q = {_id: res._id};
	var user = { foos: [ {foo: '13.57'} ] };
	console.log('Updating user, data:', user);
	UserModel.findOneAndUpdate(q, user, {new: true}).then(res => {
		console.log('User updated');
	}).catch(err => { console.error(err); });
}).catch(err => { console.error(err); });
```

See in the output below that when calling the update command we have to calls for the "setter", one time with "string" as expected but the other is with "number" which is the output of the prev call to the setter.
```
Create some user
===>>> Setter called with type: string, value: 12.57
Returning: 12.57
User inserted successfully, User: { __v: 0,
  name: 'Jay',
  _id: 58bbfe6c95177810f496d3c6,
  foos: [ { foo: 12.57 } ] }
Updating user, data: { foos: [ { foo: '13.57' } ] }
===>>> Setter called with type: string, value: 13.57
Returning: 13.57
===>>> Setter called with type: number, value: 13.57
{ CastError: Cast to Number failed for value "13.57" at path "foo"
    at MongooseError.CastError (C:\temp\mongoosebug\node_modules\mongoose\lib\error\cast.js:26:11)
    at EmbeddedDocument.Document.set (C:\temp\mongoosebug\node_modules\mongoose\lib\document.js:778:7)
```

Looks like the issue is in `Query.prototype._castUpdateVal` where there are 2 calls for cast:
```javascript
Query.prototype._castUpdateVal = function _castUpdateVal(schema, val, op, $conditional) {
  ...
  ...
  var cond = schema.caster && op in castOps &&
      (utils.isObject(val) || Array.isArray(val));
  if (cond) {
    // Cast values for ops that add data to MongoDB.
    // Ensures embedded documents get ObjectIds etc.

    // FIRST CAST
    var tmp = schema.cast(val);
    ...
    ...    
  }

  ...
  ...
  // SECOND CAST
  return schema.castForQuery(val);
};
```

versions:
mongodb: 3.4.0
mongoose ver: 4.8.5
node: 6.9.1

Thanks!

**Comment by vkarpov15** [comment]
Thanks for reporting, fixed :+1:

**Comment by ValYouW** [comment]
Thank you!
