### ISSUE TITLE
Weird promise rejection error

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5062]
My server has a `process.on('warning')` handler

Yet, I get this error from Mongoose:

```
(node:40475) Warning: a promise was rejected with a non-error: [object String]
Warning: a promise was rejected with a non-error: [object String]
    at Query.exec (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/query.js:2551:13)
    at Object.update (/Users/alexamil/WebstormProjects/cisco/cdt-now/routes/controllers/user-ctrl.js:52:37)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/routes/lib/process-import-file-request.js:103:24
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:1007:9
    at replenish (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:881:17)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:885:9
    at _asyncMap (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:1005:5)
    at Object.mapLimit (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:1091:16)
    at usersData (/Users/alexamil/WebstormProjects/cisco/cdt-now/routes/lib/process-import-file-request.js:102:13)
    at runTask (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:1627:13)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:1567:13
    at processQueue (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:1577:13)
    at auto (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:1563:5)
    at Object.autoInject (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:2102:5)
    at processFile (/Users/alexamil/WebstormProjects/cisco/cdt-now/routes/lib/process-import-file-request.js:96:9)
    at Pumpify.<anonymous> (/Users/alexamil/WebstormProjects/cisco/cdt-now/routes/lib/process-import-file-request.js:197:5)
    at Pumpify.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Pumpify.emit (events.js:185:7)
    at finishMaybe (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/readable-stream/lib/_stream_writable.js:485:14)
    at afterWrite (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/readable-stream/lib/_stream_writable.js:367:3)
    at onwrite (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/readable-stream/lib/_stream_writable.js:358:9)
    at Pumpify.WritableState.onwrite (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/readable-stream/lib/_stream_writable.js:122:5)
    at Pumpify.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Pumpify.emit (events.js:185:7)
    at Pumpify.Duplexify.uncork (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/duplexify/index.js:70:50)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/pumpify/index.js:43:12
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/pump/index.js:73:7
    at f (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/once/once.js:25:25)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/pump/index.js:31:5
 => CDT server has caught an "uncaughtException" =>  Error: Uncaught, unspecified "error" event. (Could not find prompt with id => DE-IT-G-1)
    at Function.emit (events.js:163:17)
    at Immediate.<anonymous> (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/query.js:2563:23)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

What's obviously really problematic is that all I see is  [object String]!

Any idea why my `process.on('warning')` handler does not get invoked and why all I see is [object String] instead of the actual string?

**Comment by varunjayaraman** [comment]
@ORESoftware do you have a repro script?

**Comment by ORESoftware** [comment]
I can't remember how I got this error, I don't know how I got this and I don't think I had any more context. 

I don't know who owns this code:

`(node:40475) Warning: a promise was rejected with a non-error: [object String]`

but people are going to want the plain string, not [object String]

not entirely sure what would cause that.

**Comment by varunjayaraman** [comment]
That error is owned by `node`, but without context I can't really debug it

**Comment by ORESoftware** [comment]
Np, I will try to get you more context if I can replicate

**Comment by varunjayaraman** [comment]
@ORESoftware do you have more info or have you not been able to reproduce it?
