### ISSUE TITLE
mongo error

### ISSUE THREAD

**Issue by mmkrishna321** [Automattic/mongoose#5102]
i am using mongoose@4.8.5

MongoError: topology was destroyed
    at executeCommand (C:\resumeBuilder\node_modules\mongodb\lib\db.js:289:76)
    at Db.command (C:\resumeBuilder\node_modules\mongodb\lib\db.js:334:44)
    at findAndModify (C:\resumeBuilder\node_modules\mongodb\lib\collection.js:2481:13)
    at Collection.findAndModify (C:\resumeBuilder\node_modules\mongodb\lib\collection.js:2413:44)
    at NativeCollection.(anonymous function) [as findAndModify] (C:\resumeBuilder\node_modules\mongoose\lib\drivers\node
-mongodb-native\collection.js:126:28)
    at NodeCollection.findAndModify (C:\resumeBuilder\node_modules\mquery\lib\collection\node.js:119:19)
    at Query._findAndModify (C:\resumeBuilder\node_modules\mongoose\lib\query.js:2092:22)
    at Query._findOneAndUpdate (C:\resumeBuilder\node_modules\mongoose\lib\query.js:1856:8)
    at C:\resumeBuilder\node_modules\kareem\index.js:253:8
    at C:\resumeBuilder\node_modules\kareem\index.js:18:7
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by varunjayaraman** [comment]
@mmkrishna321 without context this is impossible to debug. Usually `topology was destroyed` errors relate to trying to run some commands after the connection to the db has been closed or if it was closed during the operation.

**Comment by varunjayaraman** [comment]
@mmkrishna321 Do you have more info? I'm going to close this soon unless not since it's pretty impossible to debug this without more context.
