### ISSUE TITLE
Use cronjob object as custom schema type

### ISSUE THREAD

**Issue by YohannLYD** [Automattic/mongoose#5182]
I am looking for a way to associate a cronjob with each of the documents in my mongoose collection so I can freely edit/stop/restart them while my app is running.

Here's what my non-working code looks like :

```
var CronJob = require('cron').CronJob;

// Custom type
function Cron(key, options) {
	mongoose.SchemaType.call(this, key, options, 'Cron');
}
Cron.prototype = Object.create(mongoose.SchemaType.prototype);

Cron.prototype.cast = function(val) {
	if(!val) return null;
	if(val instanceof CronJob == false){
		throw new Error('Cron: ' + val + ' is not an instance of CronJob');
	}
	return val;
}

mongoose.Schema.Types.Cron = Cron;

// Schema definition

var Schema = mongoose.Schema;
var exampleSchema = new Schema({
  name:  String,
  description: String,
  task: Cron, // Here is the custom schema type
  enabled: Boolean
});
```

The issue is that the Cronjob object doesn't seem to be sticked to the document. If you take the last example, exampleSchema.task is considered as undefined so I am not able edit it or stop it.

I also tried to stringify the CronJob object but it's a JS object with circular reference, would it be why it causes issues when trying to embed it into the document ?

**Comment by varunjayaraman** [comment]
I'm confused, isnt your schema type `Cron`, not the `Cronjob` type from the `cron` dependency? Youve listed your `task` as having the `Cronjob` type but dont you mean `Cron`?

**Comment by YohannLYD** [comment]
My bad, you are right. I indeed meant Cron as the schema type.

**Comment by varunjayaraman** [comment]
are you not setting anything on the `task` property?

this works for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const { CronJob } = require('cron');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5182`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)

    // Custom type
    function Cron(key, options) {
      mongoose.SchemaType.call(this, key, options, 'Cron');
    }

    Cron.prototype = Object.create(mongoose.SchemaType.prototype);

    Cron.prototype.cast = function(val) {
      if (!val) return null;
      if (val instanceof CronJob == false) {
        throw new Error('Cron: ' + val + ' is not an instance of CronJob');
      }
      return val;
    }

    mongoose.Schema.Types.Cron = Cron;

    var exampleSchema = new mongoose.Schema({
      name: String,
      description: String,
      task: Cron, // Here is the custom schema type
      enabled: Boolean
    });

    const Model = db.model('Model', exampleSchema);

    const doc = new Model({ task: new CronJob('* * * * * *', null, true, 'America/New_York')});

    console.log(doc.task); // is defined
  });
}
```

**Comment by YohannLYD** [comment]
Yes I am giving taks some settings.
Your code works well but the issue comes when we try to save the document into the database.
```javascript
    doc.save(function (err, doc){
      if (err) return console.error(err);
      console.log(doc.task); // is defined
    })
```
(Note : I commented `the process.exit(0);` line)

I get this error
```
RangeError: Maximum call stack size exceeded
    at calculateElement (/Users/me/customTypeTest/node_modules/bson/lib/bson/parser/calculate_size.js:74:33)
    at calculateObjectSize (/Users/me/customTypeTest/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
...
```

**Comment by varunjayaraman** [comment]
oh my guess is that you are trying to store the entire `CronJob` object in the database, but a lot of those values arent valid mongodb values.

You also dont need most of that stuff. Just store the stuff you need to construct the CronJob argument and that are valid mongodb values:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const { CronJob } = require('cron');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5182`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
    process.exit(2);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)

    // Custom type
    function Cron(key, options) {
      mongoose.SchemaType.call(this, key, options, 'Cron');
    }

    Cron.prototype = Object.create(mongoose.SchemaType.prototype);

    Cron.prototype.cast = function(val) {
      if (!val) return null;
      return val;
    }

    mongoose.Schema.Types.Cron = Cron;

    var exampleSchema = new mongoose.Schema({
      name: String,
      description: String,
      task: Cron, // Here is the custom schema type
      enabled: Boolean
    });

    const Model = db.model('Model', exampleSchema);
    yield Model.remove({});
    const doc = new Model({ task: { timezone: 'America New York', val: '* * * * * * '}});

    yield doc.save();
    console.log(doc.task); // never runs
  });
}
```

**Comment by vkarpov15** [comment]
Either way, this isn't really how the cron package is meant to work. Underneath the hood cron just sets an in-memory timer using `setTimeout()` and `setInterval()`, so persisting that object to the database doesn't really make sense. If you want to do cron with mongodb for persistence I'd recommend using [agenda](https://www.npmjs.com/package/agenda), check out [this article on my blog for an intro to agenda](http://thecodebarbarian.com/node.js-task-scheduling-with-agenda-and-mongodb.html)
