### ISSUE TITLE
Bug: Assigning modified document arrays causes validation errors

### ISSUE THREAD

**Issue by jhob** [Automattic/mongoose#5189]
This bug looks much like issues #1638 and #3511 but is more general. We're seeing it accidentally introduced in various forms throughout our usage of mongoose.

The issue arises when an array of embedded documents is rearranged in some way and assigned back to its parent, and then embedded documents are modified. A subsequent `validate` or `save` will throw errors in some cases. It appears the `modify` paths created for each modification of an embedded document are incorrect, as the indices of the element paths are not in sync with modified indices.

**Steps to reproduce:**
The following code reproduces the issue.

```
const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/test');
mongoose.Promise = global.Promise;

const Schema = new mongoose.Schema({
  items: [{foo: {type: String, required: true}}]
});
const Model = mongoose.model('TestModel', Schema);

Model.create({
  items: [{foo: 'hi'}, {foo: 'there'}],
}).then(function (model) {
  // directly assign a modified copy of the document array
  model.set({items: model.items.slice(1)})
  // modify the elements
  model.items.forEach((item, index) => {
    item.set({foo: 'bar'});
  });

  return model.save();
}).then(function () {
  console.log('success');
}).catch(function (err) {
  console.log(err);
}).then(function () {
  mongoose.disconnect();
});
```

Here I'm using `Array#slice`, but the issue exists with `Array#filter` and various other native array methods that return a copy rather than mutate the original document array.

Executing this code throws this exception:

```
{ MongooseError: TestModel validation failed
    at ValidationError (/tmp/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/tmp/mongoose/lib/document.js:1599:32)
    at /tmp/mongoose/lib/document.js:1474:17
    at validate (/tmp/mongoose/lib/schematype.js:734:7)
    at /tmp/mongoose/lib/schematype.js:779:11
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/tmp/mongoose/lib/schematype.js:739:19)
    at /tmp/mongoose/lib/document.js:1472:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  errors:
   { 'items.1.foo':
      { MongooseError: Path `foo` is required.
          at ValidatorError (/tmp/mongoose/lib/error/validator.js:24:11)
          at validate (/tmp/mongoose/lib/schematype.js:733:13)
          at /tmp/mongoose/lib/schematype.js:779:11
          at Array.forEach (native)
          at SchemaString.SchemaType.doValidate (/tmp/mongoose/lib/schematype.js:739:19)
          at /tmp/mongoose/lib/document.js:1472:9
          at _combinedTickCallback (internal/process/next_tick.js:73:7)
          at process._tickCallback (internal/process/next_tick.js:104:9)
        message: 'Path `foo` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'foo',
        value: undefined,
        reason: undefined } },
  message: 'TestModel validation failed',
  name: 'ValidationError' }
```

## Expectations
There are various issues at play here. I would expect:
1. no validation errors to be thrown
    1. more specifically, I expect the direct assignment of a `DocumentArray` to sync each elements `__parentArray` reference, so that those element's paths are generated correctly (here I assume that embedded documents cannot be shared across multiple document arrays).
3. no `markModified` on the embedded document paths upon modification as the entire array is already marked

## Workaround

I've found a couple of ugly workarounds:
- iterate through elements and manually update `__parentArray`
- avoid modifying the array with native methods like `Array#filter` and `Array#slice` and use only those with `MongooseArray` overrides (`pull`, `addToSet`) etc. Unfortunately these are all mutating methods.
- avoid `set` on embedded documents altogether. Do all modifications prior to assigning the parent array as to avoid marking individual elements as modified.
- call `MongooseArray#toObject` before modifying any array and then assigning `items` to `[]` before assigning the plain array. This will clear the stale `__parentArray` references. For example:
```
    const newArray = model.items.toObject().slice(1);
    model.items = [];
    model.items = newArray;
```

## Versions

Node **v7.9.0**
Mongoose **v4.9.5**
Mongo **v3.2.9**

**Comment by jhob** [comment]
Fixed in `mongoose@4.9.6`
