### ISSUE TITLE
Bug: using `remove` as a schema property name causes TypeError

### ISSUE THREAD

**Issue by TobyEalden** [Automattic/mongoose#5197]
It looks like `remove` should be added to the reserved keyword list, since using it in a schema causes an error.

See https://github.com/TobyEalden/mongoose-remove-bug

e.g.

```
  const mongoose = require('mongoose');
  mongoose.connect('mongodb://localhost/test');

  const Cat = mongoose.model(
    'Cat',
    {
      name: String,
      remove: String,   // <-- using 'remove' as a schema property name causes the error.
    }
  );

  const kitty = new Cat({ name: 'Zildjian' });
  kitty.save(function (err) {
    if (err) {
      console.log(err);
    } else {
      console.log('meow');
    }
  });
```
gives:
```
/home/nuc/dev/mongoose-remove-bug/node_modules/mongoose/lib/document.js:1898
        return this.get.call(this.$__.scope || this, path);
                                     ^

TypeError: Cannot read property 'scope' of undefined
    at model.Object.defineProperty.get [as remove] (/home/nuc/dev/mongoose-remove-bug/node_modules/mongoose/lib/document.js
:1898:38)
    at applyHooks (/home/nuc/dev/mongoose-remove-bug/node_modules/mongoose/lib/services/model/applyHooks.js:95:25)
    at Function.compile (/home/nuc/dev/mongoose-remove-bug/node_modules/mongoose/lib/model.js:3619:3)
    at Mongoose.model (/home/nuc/dev/mongoose-remove-bug/node_modules/mongoose/lib/index.js:408:22)
    at /home/nuc/dev/mongoose-remove-bug/index.js:7:24
    at Object.<anonymous> (/home/nuc/dev/mongoose-remove-bug/index.js:17:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

nodejs: 4.7.3
mongoose: 4.9.5
mongodb: 3.4.3

**Comment by varunjayaraman** [comment]
yup, this looks like a bug:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5197`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: String,
      remove: String
    });


    const Model = db.model('Model', schema);

    yield Model.create({ remove: 'test' });
  });
}
```
