### ISSUE TITLE
Remove storeSubdocumentValidationError, consistently make subdocs and array subdoc validation only report the leaf error rather than an error for every subdoc path

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5226]
Right now array subdocs don't have an internal error state, see #5208. In particular, the below script will report `child` as having an error but not `children`:

```javascript
'use strict';

var mongoose = require('mongoose');

var childSchema = new mongoose.Schema({
  name: { type: String, required: true }
});
var parentSchema = new mongoose.Schema({
  child: childSchema,
  children: [childSchema]
});

var Parent = mongoose.model('Parent', parentSchema);

var p = new Parent({ child: {}, children: [{}] });
p.validate(error => console.error(error.errors));
```

```
{ 'children.0.name': 
   { MongooseError: Path `name` is required.
       at ValidatorError (/home/val/Workspace/10gen/mongoose/lib/error/validator.js:24:11)
     message: 'Path `name` is required.',
     name: 'ValidatorError',
     properties: 
      { type: 'required',
        message: 'Path `{PATH}` is required.',
        validator: [Function],
        path: 'name',
        value: undefined },
     kind: 'required',
     path: 'name',
     value: undefined,
     reason: undefined },
  'child.name': 
   { MongooseError: Path `name` is required.
       at ValidatorError (/home/val/Workspace/10gen/mongoose/lib/error/validator.js:24:11)
     message: 'Path `name` is required.',
     name: 'ValidatorError',
     properties: 
      { type: 'required',
        message: 'Path `{PATH}` is required.',
        validator: [Function],
        path: 'name',
        value: undefined },
     kind: 'required',
     path: 'name',
     value: undefined,
     reason: undefined },
  child: 
   { MongooseError: Validation failed
       at ValidationError (/home/val/Workspace/10gen/mongoose/lib/error/validation.js:23:11)
     errors: { name: [Object] },
     message: 'Validation failed',
     name: 'ValidationError' } }
```

We should make this more consistent, but reporting an error with `children` will break current guarantees like #4681

**Comment by varunjayaraman** [comment]
the issue here with #4681 is that the subdoc validators are duplicated for the parent doc as well right? can we get the best of both worlds by giving the array its own internal error state but forcing the context to be the individual documents within the array subdoc?

**Comment by vkarpov15** [comment]
No the issue is that array subdocs' internal error state points to the same object as the top-level document. Single nested docs keep their own `validationError` object because that makes it much easier for update validators and other stateless validation, as well as reporting errors recursively. I think array subdocs should switch over to the same approach as single nested docs, and eventually we should really just minimize the distinction between array subdocs and single nested subdocs.
