### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by saurabh2597** [Automattic/mongoose#5267]
*** Reporting a bug: ***

I am trying to find from collection and if it is null I am creating a new document by new Document()
but when I try to save it is showing me an error.
 
Test.find(query, function(err, result){
     if(!result){
           result = new Test()      
}

result.save()
})

RangeError: Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at clone (/mongoose/lib/utils.js:239:31)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (mongoose/lib/utils.js:245:12)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (mongoose/lib/utils.js:245:12)
    at cloneArray (mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)
    at cloneArray (mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)
    at cloneArray (mongoose/lib/utils.js:334:14)
    at clone (mongoose/lib/utils.js:245:12)
    at cloneArray (mongoose/lib/utils.js:334:14)
    at clone (mongoose/lib/utils.js:245:12)
    at cloneArray (mongoose/lib/utils.js:334:14)
    at clone (mongoose/lib/utils.js:245:12)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)
    at cloneArray (/mongoose/lib/utils.js:334:14)
    at clone (/mongoose/lib/utils.js:245:12)

**Comment by markstos** [comment]
This issue could just be deleted. It's empty and clutters search results when searching for actual related bugs.

**Comment by vkarpov15** [comment]
@markstos I wish I could, not possible to delete issues on github :(
