### ISSUE TITLE
findOne().exec().promise() gives Type error 

### ISSUE THREAD

**Issue by zymr-keshav** [Automattic/mongoose#5277]
I want to retrieve the users based on 2 condition

but when I execute below query
User

```
User
                .findOne()
                .and([{ "username": req.body.username}, {"isActive": false}])
                .exec()
                .then((user) => {
                    console.log('user found', user);
                    // match saved and input password
                    if (user.password === req.body.password) {
                        res.status(200).json(user);
                    } else {
                        console.log('else part', user);
                        res.status(404).send({"message": "invalid credentials."});
                    }
                })
                .catch((err) => {
                    console.log('catch error', err);
                    res.status(404).send(err);
                });

```

it failed and gone to first in .then() block then in .catch() block with below error stack

```
user found null
catch error TypeError: Cannot read property 'password' of null
    at User.findOne.and.exec.then (/opt/play/server/controllers/users.js:45:29)
    at tryCatcher (/opt/play/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/play/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/play/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/play/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/play/server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/play/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/play/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/play/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
Please  tell me what is wrong in the query and why it goes to then block even when the condition failed 

nodejs:6.10.3 
mongoDB : 2.4.9
mongoose: 4.10.0
 bluebird : 3.5.0

**Comment by steve-p-com** [comment]
If the conditions are not met, so there is no matching document, then `findOne` returns a null document. Could that be what is happening? You might be expecting that it would throw an error if there's no match, but it doesn't. It only throws an error if there's an actual error, for which 500 might be more suitable. You will need to check inside the `then` and handle a null document (by sending the 404, probably).

**Comment by vkarpov15** [comment]
`user` is null, so accessing `user.password` is an error. `findOne()` will resolve to `null` if no document was found
