### ISSUE TITLE
Error on validation with maxlength and conditional required, for undefined value.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [Automattic/mongoose#5296]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error like below:
```
         TypeError: Cannot read property 'length' of undefined
             at model.validators.push.validator.maxlengthValidator (/Users/tsuneo/gino/cloud/node_modules/mongoose/lib/schema/string.js:306:31)
             at /Users/tsuneo/gino/cloud/node_modules/mongoose/lib/schematype.js:776:26
             at Array.forEach (native)
             at SchemaString.SchemaType.doValidate (/Users/tsuneo/gino/cloud/node_modules/mongoose/lib/schematype.js:750:19)
             at /Users/tsuneo/gino/cloud/node_modules/mongoose/lib/document.js:1461:9
             at _combinedTickCallback (internal/process/next_tick.js:73:7)
             at process._tickCallback (internal/process/next_tick.js:104:9) } },

```

**If the current behavior is a bug, please provide the steps to reproduce.**
Set schema like below, and create a document without name. (i.e. name is undefined)
```
  name: {
    type: String,
    maxlength: 63,
    required: function(){
      return false;
    },
  },
```

**What is the expected behavior?**
No error

**Please mention your node.js, mongoose and MongoDB version.**
Node.js v6.10.2
MongoDB 3.2.7
Mongoose 4.10.2

**Comment by yoshiokatsuneo** [comment]
It looks similar to the fixed issue: https://github.com/Automattic/mongoose/issues/4607

**Comment by yoshiokatsuneo** [comment]
(And, the issue happens on the latest version, now)

**Comment by varunjayaraman** [comment]
hm, this doesnt error for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5296`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const schema = new mongoose.Schema({
      name: {
        type: String,
        maxlength: 63,
        required: function() {
          return false;
        },
      },
    });


    const Model = db.model('Model', schema);

    yield Model.remove({});
    yield Model.create({});
  });
}
```

**Comment by yoshiokatsuneo** [comment]
@varunjayaraman On the above code, if I call create as "Model.create({name: undefined})", I got error below.

```
$ node index.js 
Error: ValidationError: name: Path `name` (`undefined`) is longer than the maximum allowed length (63).?nValidationError: Model validation failed: name: Path `name` (`undefined`) is longer than the maximum allowed length (63).
    at MongooseError.ValidationError (/private/tmp/a/node_modules/mongoose/lib/error/validation.js:26:11)
    at model.Document.invalidate (/private/tmp/a/node_modules/mongoose/lib/document.js:1594:32)
    at /private/tmp/a/node_modules/mongoose/lib/document.js:1466:17
    at validate (/private/tmp/a/node_modules/mongoose/lib/schematype.js:745:7)
    at /private/tmp/a/node_modules/mongoose/lib/schematype.js:790:11
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/private/tmp/a/node_modules/mongoose/lib/schematype.js:750:19)
    at /private/tmp/a/node_modules/mongoose/lib/document.js:1464:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
