### ISSUE TITLE
Error when creating with Subdocuments getting RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mariohmol** [Automattic/mongoose#5302]
**Bug**

**What is the current behavior?**

When i try to create a record with a array with objects (subdocuments) i'm getting `RangeError: Maximum call stack size exceeded`.  

* When i remove the products array from the object to be created, it works.
* If i use `collection.insert` instead of `create` it works
* Checked the id of the reference model is there

i'm using typescript, webpack and angular universal. I had this working before (almost sure), and i guess this start working after changing the build to work with SSR with angula universal.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a model like

```
const OrderSchema = new mongoose.Schema({
  title: {  type: String },
  products: [{
    quantity: { type: Number },
    product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product',unique: false,required: [true,'No product id found']},
    price: { type: Number }
  }]
});
```

And try to create with a object passing an array of objects:

```
{\"title\":\"\",\"products\":[{\"product\":\"58f50198dff70a50a147a55d\",\"quantity\":1}]
```

**What is the expected behavior?**

Should create the object with the nested attributes.

* Stacktrace

```
"RangeError: Maximum call stack size exceeded",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:24:25)",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:44:14)",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:44:14)",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:59:14)",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:44:14)",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:59:14)",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:59:14)",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:44:14)",
    "    at recursiveSearch (/myproject/web/node_modules/source-map/lib/binary-search.js:59:14)",
    "    at Object.search (/myproject/web/node_modules/source-map/lib/binary-search.js:94:15)",
    "    at SourceMapConsumer_findMapping [as _findMapping] (/myproject/web/node_modules/source-map/lib/source-m
ap-consumer.js:547:25)",
    "    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/myproject/web/node_modules/source-m
ap/lib/source-map-consumer.js:604:22)",
    "    at mapSourcePosition (/myproject/web/node_modules/source-map-support/source-map-support.js:195:42)",
    "    at wrapCallSite (/myproject/web/node_modules/source-map-support/source-map-support.js:338:20)",
    "    at /myproject/web/node_modules/source-map-support/source-map-support.js:373:26",
    "    at Array.map (native)",
    "    at Function.prepareStackTrace (/myproject/web/node_modules/source-map-support/source-map-support.js:372
:24)",
    "    at Function.NativeError.prepareStackTrace (/myproject/web/node_modules/zone.js/dist/zone-node.js:1040:3
0)",
    "    at Function.NativeError.prepareStackTrace (/myproject/web/node_modules/zone.js/dist/zone-node.js:1040:3
0)",
    "    at Function.NativeError.prepareStackTrace (/myproject/web/node_modules/zone.js/dist/zone-node.js:1040:3
0)",
    "    at Function.NativeError.prepareStackTrace (/myproject/web/node_modules/zone.js/dist/zone-node.js:1040:3
0)",
    "    at Function.NativeError.prepareStackTrace (/myproject/web/node_modules/zone.js/dist/zone-node.js:1040:3
0)",
    "    at Function.NativeError.prepareStackTrace (/myproject/web/node_modules/zone.js/dist/zone-node.js:1040:3
0)",
    "    at Error.get stack (native)",
    "    at Error.ZoneAwareError (/myproject/web/node_modules/zone.js/dist/zone-node.js:917:59)",
    "    at EmbeddedDocument.wrappedPointCut [as validate] (/myproject/web/dist-server/webpack:/~/mongoose/lib/s
ervices/model/applyHooks.js:109:1)",
    "    at EmbeddedDocument._done (/myproject/web/dist-server/webpack:/~/hooks-fixed/hooks.js:101:1)",
    "    at _asyncsDone (/myproject/web/dist-server/webpack:/~/hooks-fixed/hooks.js:36:1)",
    "    at fnWrapper (/myproject/web/dist-server/webpack:/~/hooks-fixed/hooks.js:186:1)",
    "    at EmbeddedDocument.module.exports.Object.defineProperty.value.fn (/myproject/web/dist-server/webpack:/
~/mongoose/lib/schema.js:252:1)",
```

**Please mention your node.js, mongoose and MongoDB version.**

```
node v6.3.1
 "mongoose": "^4.9.7",
 "mongoose-deep-populate": "^3.0.0",
mongodb version v3.0.7
```

**Comment by vkarpov15** [comment]
I'd also need to see your webpack config and package.json before we can try reproing this, otherwise we're just shooting in the dark

**Comment by mariohmol** [comment]
Hi there, thanks for answering.. my project is based on https://github.com/clbond/angular-ssr

**Comment by eduardosanzb** [comment]
HI there, same issue here:
At my user model, trying to append an `Array` of another schema.
``` javascript
User.js
import mongoose, { Schema } from 'mongoose';
import { PermissionSchema, SpeakerInfoSchema } from './schemas/rootSchemas';
import { getLevels, getHighest } from './lib/utilities';

const UserSchema = new Schema({
  firstName: {
    type: String,
    index: true
  },
  lastName: {
    type: String,
    index: true
  },
  email: {
    type: String,
    index: true,
    required: true
  },
  activated: {
    type: Boolean,
    default: false
  },
  profilePicture: {
    type: String
  },
  birthDate: {
    type: Date
  },
  permissions: [PermissionSchema],
  speakerInfo: [SpeakerInfoSchema],
  children: [{ name: String }]
});

UserSchema.virtual('maxPermission').get(function () {
  return this.permissions.map(getLevels).reduce(getHighest);
});

module.exports = mongoose.model('user', UserSchema);
```
``` javascript
rootSchemas
/* eslint prefer-arrow-callback: 0 */
/* eslint func-names: ["error", "never"] */
import _ from 'lodash';
import { Schema } from 'mongoose';
import { globalPermissions } from '../../config.json';
import { createReference, getMatchLevel } from '../lib/utilities';



const PermissionSchema = new Schema({
  name: {
    type: String,
    enum: _.values(globalPermissions), //return an array of strings
    required: true
  }
});
PermissionSchema.virtual('level').get(function () {
  return _.entries(globalPermissions)
		.reduce(getMatchLevel.bind(null, this.name)); //returns a string
});

const SpeakerInfoSchema = new Schema({
  contributions: [createReference('Contributions')],
  conferences: [createReference('Conferences')]
});

module.exports = {
  PermissionSchema,
  SpeakerInfoSchema
};
```

The error I get using `jest-jasmine`
``` bash
server/node_modules/mongoose/lib/services/model/applyHooks.js:145
          promise.then(
                  ^

RangeError: Maximum call stack size exceeded
    at Promise.then (<anonymous>)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:145:19)
    at EmbeddedDocument._done (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:101:24)
    at _asyncsDone (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:36:36)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:212:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at EmbeddedDocument._next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at EmbeddedDocument.proto.(anonymous function) [as $__original_validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:108:20)
    at /Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:139:27
    at Promise (<anonymous>)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:117:23)
    at EmbeddedDocument._done (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:101:24)
    at _asyncsDone (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:36:36)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:212:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at EmbeddedDocument._next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at EmbeddedDocument.proto.(anonymous function) [as $__original_validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:108:20)
    at /Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:139:27
    at Promise (<anonymous>)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:117:23)
    at EmbeddedDocument._done (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:101:24)
    at _asyncsDone (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:36:36)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:212:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at EmbeddedDocument._next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at EmbeddedDocument.proto.(anonymous function) [as $__original_validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:108:20)
    at /Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:139:27
    at Promise (<anonymous>)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:117:23)
    at EmbeddedDocument._done (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:101:24)
    at _asyncsDone (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:36:36)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:212:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at EmbeddedDocument._next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at EmbeddedDocument.proto.(anonymous function) [as $__original_validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:108:20)
    at /Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:139:27
    at Promise (<anonymous>)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:117:23)
    at EmbeddedDocument._done (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:101:24)
    at _asyncsDone (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:36:36)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:212:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at EmbeddedDocument._next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at EmbeddedDocument.proto.(anonymous function) [as $__original_validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:108:20)
    at /Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:139:27
    at Promise (<anonymous>)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:117:23)
    at EmbeddedDocument._done (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:101:24)
    at _asyncsDone (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:36:36)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:212:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at EmbeddedDocument._next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at EmbeddedDocument.proto.(anonymous function) [as $__original_validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:108:20)
    at /Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:139:27
    at Promise (<anonymous>)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:117:23)
    at EmbeddedDocument._done (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:101:24)
    at _asyncsDone (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:36:36)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:212:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at _next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:186:8)
    at EmbeddedDocument.fn (/Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/schema.js:211:9)
    at EmbeddedDocument._next (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:62:30)
    at EmbeddedDocument.proto.(anonymous function) [as $__original_validate] (/Users/eduardosanzb/projects/thesis/server/node_modules/hooks-fixed/hooks.js:108:20)
    at /Users/eduardosanzb/projects/thesis/server/node_modules/mongoose/lib/services/model/applyHooks.js:139:27
    at Promise (<anonymous>)
```

**Comment by varunjayaraman** [comment]
i dont think this is a mongoose issue. If i do this in a vacuum (without all the other external dependencies) it works fine:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5302`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const productSchema = new mongoose.Schema({
      name: String
    });

    const Product = db.model('Product', productSchema);

    const product = yield Product.create({ name: 'test product' });

    const orderSchema = new mongoose.Schema({
      title: { type: String },
      products: [{
        quantity: { type: Number },
        product: { type: mongoose.Schema.Types.ObjectId, ref: 'products', unique: false, required: [true, 'No product id found'] },
        price: { type: Number }
      }]
    });


    const Order = db.model('Order', orderSchema);

    yield Order.create({
      title: 'Test',
      products: [
        {
          quantity: 20,
          product: product._id,
          price: 50
        }
      ]
    });
  });
}
```

**Comment by eduardosanzb** [comment]
@varunjayaraman you are right, the issue is only in my testing environment.
If I move to development, it works flawless.

Thanks for the response.

**Comment by mariohmol** [comment]
@varunjayaraman my case is different.. no?

**Comment by varunjayaraman** [comment]
how so? I created a document with a subdoc array and it worked fine. If you think there's a difference between what youre doing and I'm doing that might be impacting our different results, I'm all ears

**Comment by mariohmol** [comment]
I said that because @eduardosanzb posted an error with a different stacktrace.. but he removed..

**Comment by varunjayaraman** [comment]
@mariohmol does my script error for you?

**Comment by mariohmol** [comment]
Thanks for answering!

I imagined that it might work by itself. So i ran this in a single .js file and it works, but if i put this in the index.ts of my project, it breaks.

As i'm using the angular-ssr example, what i did was include this example in this project and i could reproduce the error.. 

Here is where i introduced the snippet:

https://github.com/mariohmol/angular-ssr/blob/master/examples/demand-express/server/index.ts#L153


Here is the stacktrace:

```
ValidationError: RangeError: Maximum call stack size exceeded
    at MongooseError.ValidationError (/projetos/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/error/validation.js:23:1
)
    at model.module.exports.Document.invalidate (/projetos/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/document.js:1
606:1)
    at /projetos/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/document.js:1481:1
    at callback (/projetos/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/schema/documentarray.js:158:1)
    at handleError (/projetos/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:40:1)
    at next_ (/projetos/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:75:1)
    at fnWrapper (/projetos/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:186:1)
    at /projetos/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/services/model/applyHooks.js:151:1
    at ZoneDelegate.invokeTask (/projetos/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:398:31)
    at Zone.runTask (/projetos/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:165:47)
    at ZoneTask.invoke (/projetos/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:460:38)
    at data.args.(anonymous function) (/projetos/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:1598:25)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 ```

Thanks

i tested including this call in this project as well..

**Comment by varunjayaraman** [comment]
I haven't use `angular-ssr` before so I'm not too familiar with the internals of what it's doing. If it works outside the context of angular ssr, it looks like this might be an angular-ssr issue instead of a mongoose issue.

I'll keep this open if anyone from the other repo has any ideas why this bug is only reproducible inside `angular-ssr`

**Comment by mariohmol** [comment]
Isn't related with typescript?

I have an app running pretty good with ssr (basicly it uses angular-universal). So i have angular, node and a lot of different modules working good (for angular and node).  Until now this bug in mongoose is the only one that i can see happen.

Maybe if take this repo I made to reproduce and debug might help?

I did some console.log in the code and validation is passing 5 times. The error is coming from `documentarray.js` (so make sense as this happens just when have schema arrays)

I found this stack inside `documentarray.js`, see if that happens

```
RangeError: Maximum call stack size exceeded
    at CallSiteGetTypeName (native)
    at CallSite.Object.getOwnPropertyNames.forEach.object.(anonymous function) [as getTypeName] (/Documents/angular-ssr/examples/demand-express/node_modules/source-map-support/source-map-support.js:313:79)
    at CallSiteToString [as toString] (/Documents/angular-ssr/examples/demand-express/node_modules/source-map-support/source-map-support.js:279:25)
    at /Documents/angular-ssr/examples/demand-express/node_modules/source-map-support/source-map-support.js:373:24
    at Array.map (native)
    at Function.prepareStackTrace (/Documents/angular-ssr/examples/demand-express/node_modules/source-map-support/source-map-support.js:372:24)
    at Function.Object.defineProperty.set.NativeError.prepareStackTrace (/Documents/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:1040:30)
    at Function.Object.defineProperty.set.NativeError.prepareStackTrace (/Documents/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:1040:30)
    at Function.Object.defineProperty.set.NativeError.prepareStackTrace (/Documents/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:1040:30)
    at Function.Object.defineProperty.set.NativeError.prepareStackTrace (/Documents/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:1040:30)
    at Error.get stack (native)
    at Error.ZoneAwareError (/Documents/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:917:59)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/services/model/applyHooks.js:109:1)

at EmbeddedDocument.module.exports.module.exports.$hook.proto.(anonymous function)._done (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:101:1)
    at module.exports.module.exports.$hook.proto.(anonymous function)._asyncsDone (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:36:1)
    at fnWrapper (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:186:1)
    at EmbeddedDocument.module.exports.Object.defineProperty.value.fn (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/schema.js:252:1)
    at module.exports.module.exports.$hook.proto.(anonymous function)._next (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:62:1)
    at fnWrapper (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:186:1)
    at EmbeddedDocument.module.exports.Object.defineProperty.value.fn (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/schema.js:251:1)
    at EmbeddedDocument.module.exports.module.exports.$hook.proto.(anonymous function)._next (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:62:1)
    at EmbeddedDocument.module.exports.module.exports.$hook.proto.(anonymous function) [as $__original_validate] (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:108:1)
    at /Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/services/model/applyHooks.js:137:1
    at new ZoneAwarePromise (/Documents/angular-ssr/examples/demand-express/node_modules/zone.js/dist/zone-node.js:774:29)
    at EmbeddedDocument.wrappedPointCut [as validate] (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/mongoose/lib/services/model/applyHooks.js:117:1)
 at EmbeddedDocument.module.exports.module.exports.$hook.proto.(anonymous function)._done (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:101:1)
    at module.exports.module.exports.$hook.proto.(anonymous function)._asyncsDone (/Documents/angular-ssr/examples/demand-express/dist-server/webpack:/~/hooks-fixed/hooks.js:36:1)
  __zone_symbol__currentTask: 
   ZoneTask {
     _zone: 
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'process.nextTick',
     data: 
      { name: 'process.nextTick',
        args: [Object],
        callbackIndex: 0,
        target: [Object] },
     scheduleFn: [Function: scheduleTask],
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
```

As i'm skipping mongoose and using mongo driver directly, i can keep coding, but it might be usefull to look over this because from now on more and more people will use typescript and ssr.

bests

**Comment by nowke** [comment]
I don't know the context of the original issue, but I'm getting a similar error

```
/node_modules/hooks-fixed/hooks.js:67
        , _done = function () {
                           ^

RangeError: Maximum call stack size exceeded
```

I have a schema called `User` where `documents` is an array of type `documentSchema`,
```js
const documentSchema = new Schema({
  docid: String,
  title: String,
  isPrivate:Boolean,
});

const userSchema = new Schema({
  ...
  documents: [documentSchema],
});
```

I insert values to `documents` for an existing `User` as,

```js
user.documents.push({ title, isPrivate });
```

Now this works perfectly in **development** environment after I made an API above the model. While **testing** using `jest`, I get the above mentioned `RangeError`.

But, I changed `.push` method to `.create` and it worked!

```js
user.documents.create({ title, isPrivate });
```

### Version Info

```
node v8.0.0,
mongoose: ^4.10.4,
mongodb: 3.4.4
```

**Comment by mariohmol** [comment]
@nowke seems to be related, in my case it gives an error on `hooks-fixed` as well. So doing the creation in 2 steps works (create parent and then after create childs.. ) .. good to know.. will make a test in my side next time i got into that

**Comment by varunjayaraman** [comment]
`mongoose` seems to not pair nicely with `jest`, I'm not sure if it's a jest-specific thing or something else in your test config that might be causing that issue

**Comment by nowke** [comment]
@varunjayaraman - you're right. I'm getting the same error in `hooks.js` again. The above-mentioned solution didn't work now! 

I changed `jest` configuration `testEnvironment` to `node` and it started working again (Related: https://github.com/facebook/jest/issues/3045). Not sure what the exact problem is. Temporary workarounds are the only solutions as of now.

**Comment by mariohmol** [comment]
@nowke tested here and the bug appears just in the create .. if I use a `create` to make the the inicial record without subdocs and then after do a `findOneAndUpdate` passing the subdoc it works..

With this bug it makes me impossible to use mongoose.. cause the great thing about mongo is exactly doing subdocs..

**Comment by mariohmol** [comment]
This error is really hard.. try to find a workaround in a new bug that appeared here with same stacktrace

@varunjayaraman is any plans to make mongoose supported by Typescript or in a build system like this SSR? 

This is tagged as `need clarification ` but as we have a repo that reproduces the error, i think this is enought to work on , no?

bests

**Comment by varunjayaraman** [comment]
i use mongoose with typescript regularly, i don't think its a TS issue. if you have evidence to the contrary, I'm all ears. I think it would be worth working together with someone from Jest team to figure out why people get this error with jest all the time. Maybe that will give us some insight as to why you are getting the same error w/ angular-ssr

**Comment by mariohmol** [comment]
I tested with `4.11.6` as it says was fixed for jest... https://github.com/Automattic/mongoose/issues/5513#issuecomment-320529439 

but still not working.

**Comment by mariohmol** [comment]
You know what is weird? I did the changes in the reproduce repo and now its working (maybe after 4.11.6).

https://github.com/mariohmol/angular-ssr/

I had this issue in my project but i did a workaround, if i get this bug again will reopen the issue!

Feel free to reopen if this still happen or if can do a reproduce repo to prove it.

thanks @varunjayaraman
