### ISSUE TITLE
Crash when schema validation fails

### ISSUE THREAD

**Issue by Grmiade** [Automattic/mongoose#5307]
Since Mongoose 4.10.x, when my schema validation fails, mongoose crashes with this error:

```
/Users/jeremy/Development/manager/node_modules/mongoose/lib/error.js:16
  this.message = msg;
               ^

TypeError: Cannot set property message of [object Object] which has only a getter
    at new MongooseError (/Users/jeremy/Development/manager/node_modules/mongoose/lib/error.js:16:16)
    at ValidationError (/Users/jeremy/Development/manager/node_modules/mongoose/lib/error/validation.js:20:19)
    at model.Document.invalidate (/Users/jeremy/Development/manager/node_modules/mongoose/lib/document.js:1590:32)
    at /Users/jeremy/Development/manager/node_modules/mongoose/lib/document.js:1462:17
    at validate (/Users/jeremy/Development/manager/node_modules/mongoose/lib/schematype.js:745:7)
    at /Users/jeremy/Development/manager/node_modules/mongoose/lib/schematype.js:790:11
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/Users/jeremy/Development/manager/node_modules/mongoose/lib/schematype.js:750:19)
    at /Users/jeremy/Development/manager/node_modules/mongoose/lib/document.js:1460:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

If I log the `msg` variable, I have 
```
Path `email` is required. 
Contact validation failed
```

My schema:
```javascript
const { Schema } = require('mongoose')

const db = require('../../../dbs/connectBODB')

const contactSchema = new Schema({
  company: { type: mongoose.Schema.ObjectId, ref: 'Metadata' },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  phoneNumber: String,
  position: String,
  favorite: Boolean,
}, {
  timestamps: true,
})

const Contact = db.model('Contact', contactSchema)

module.exports = Contact
```
and my controller:
```javascript
function create({ body: newContact }, res, next) {
  return Contact.create(newContact)
    .then(contact => res.json(contact))
    .catch(next)
}
```

My catch section should receive a validation error and the controller should return a 404 response with this error.
Not crash :/

If I downgrade Mongoose to 4.9.10, I don't have this issue. Only with Mongoose version >4.10.0
I use Node 7.10.0 and Mongo 3.4.4

**Comment by davebaol** [comment]
Unfortunately, I can confirm this issue.
Not sure but sounds like something related to https://github.com/Automattic/mongoose/issues/5309

**Comment by varunjayaraman** [comment]
what happens when you try this script in the latest version of mongoose (4.10.4 as of writing):

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5307`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const schema = new mongoose.Schema({
      name: { type: String, required: true },
      message: { type: String, maxlength: 5 }
    });

    const Model = db.model('Model', schema);

    yield Model.create({ message: 'asfasdfasdfasdf' });
  });
}

```

**Comment by davebaol** [comment]
@varunjayaraman 
Your script works for me.
In my case the issue raises when you use [boom](https://www.npmjs.com/package/boom) to wrap mongoose `ValidationError` with http status code 400.
To reproduce the issue just add `boom.wrap()` inside the catch like that:
````javascript
exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    error = require('boom').wrap(error, 400, 'A validation error occurred. ');
    console.error(`Error: ${error}\n${error.stack}`);
  });
````
Note that the code above works great with mongoose 4.9.10 while fails with mongoose 4.10.x

**Comment by davebaol** [comment]
BTW, with mongoose 4.10.x if you replace 'boom.wrap()' with this:
````javascript
error.message = 'A validation error occurred: ' + error.message;
````
you still get the original error message: 'Model validation failed: ...'.
You have to set `error._message` like below (notice the underscore character as left value, not needed as right value) to get the modified message
````javascript
error._message = 'A validation error occurred: ' + error.message;
````
Looks like there's a strong correlation with issue https://github.com/Automattic/mongoose/issues/5309

**Comment by varunjayaraman** [comment]
yeah it is related. it's because in 4.10.0, the `message` property was turned into a getter for this._message. Will track this in #5309
