### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by couturecraigj** [Automattic/mongoose#5332]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When assigning a value inside of a virtual I am getting an error previously this was working before updating.
**If the current behavior is a bug, please provide the steps to reproduce.**

I have a virtual called Context with the following 

```javascript
/** tags.js **/
TagSchema.virtual('context').set(function ({ user }) {
    if (this.isNew) {
      const created = new Object()
      created.user = user.displayName
      created.date = this.created.date
      if (!this.created || !(this.created instanceof Object)) {
        this.created = {}
      }
      this.created = created // <<< LINE 45
    }
    if (!this.edited) {
      this.edited = {}
    }
    this.edited = { user: user.displayName, date: this.edited.date }
    this._hiddenUser = user && user.displayName || null
  })
```

The reason for this is to prevent creating this Tag unless the user is signed in.  I throw an `Error` on the validation step when this this._hiddenUser is falsy.  That looks like this

```javascript
TagSchema.pre('validate', function (next) {
    if (!this._hiddenUser) {
      next(new Error('You Need to have `context.user.displayName`'))
    }
    next()
  })
```

Unfortunately I am unable to reach any of this because I am assigning a value at `this.created` and that seems to be triggering the following stacktrace.

```bash
TypeError: Object prototype may only be an Object or null: undefined
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/types/subdocument.js:18:32)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/types/index.js:16:23)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/schema/buffer.js:8:22)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/schema/array.js:15:11)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/schema/documentarray.js:7:17)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/schema/index.js:12:25)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/schema.js:1827:32)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/document.js:8:14)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/document_provider.js:8:16)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at Object.<anonymous> (/$user/mongoose-test/node_modules/mongoose/lib/types/embedded.js:7:16)
 at Runtime._execModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:513:13)
 at Runtime.requireModule (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:329:14)
 at Runtime.requireModuleOrMock (/$user/mongoose-test/node_modules/jest-runtime/build/index.js:405:19)
 at model.Document.$__set (/$user/mongoose-test/node_modules/mongoose/lib/document.js:841:26)
 at model.Document.set (/$user/mongoose-test/node_modules/mongoose/lib/document.js:759:10)
 at model._handleIndex (/$user/mongoose-test/node_modules/mongoose/lib/document.js:587:14)
 at model.Document.set (/$user/mongoose-test/node_modules/mongoose/lib/document.js:547:24)
 at model.Document.set (/$user/mongoose-test/node_modules/mongoose/lib/document.js:617:14)
 at model.Object.defineProperty.set [as created] (/$user/mongoose-test/node_modules/mongoose/lib/document.js:1902:41)
 at model.<anonymous> (/$user/mongoose-test/server/api/models/tags.js:45:20)
 at VirtualType.applySetters (/$user/mongoose-test/node_modules/mongoose/lib/virtualtype.js:94:25)
 at model.Document.set (/$user/mongoose-test/node_modules/mongoose/lib/document.js:656:12)
 at model._handleIndex (/$user/mongoose-test/node_modules/mongoose/lib/document.js:587:14)
 at model.Document.set (/$user/mongoose-test/node_modules/mongoose/lib/document.js:547:24)
 at model.Document (/$user/mongoose-test/node_modules/mongoose/lib/document.js:71:12)
 at model.Model (/$user/mongoose-test/node_modules/mongoose/lib/model.js:46:12)
 at new model (/$user/mongoose-test/node_modules/mongoose/lib/model.js:3614:13)
 at /$user/mongoose-test/server/api/models/tags.js:100:49
 at Array.map (native)
 at /$user/mongoose-test/server/api/models/tags.js:97:97
 at run (/$user/mongoose-test/node_modules/prosperent/index.js:2533:22)
 at /$user/mongoose-test/node_modules/prosperent/index.js:2546:28
 at flush (/$user/mongoose-test/node_modules/prosperent/index.js:2101:9)
 at _combinedTickCallback (internal/process/next_tick.js:67:7)
 at process._tickCallback (internal/process/next_tick.js:98:9)```

**What is the expected behavior?**
Well that would be that it does not throw an error because I am assigning a value based on a virtual

**Please mention your node.js, mongoose and MongoDB version.**
node@6.2.2
npm@3.10.2
mongoose@4.10.5
mongodb -v 3.4.4

**Comment by couturecraigj** [comment]
I also went back to check to see if I was doing something wrong... and changed the code to this

```javascript
TagSchema.virtual('context').set(function ({ user }) {
    if (this.isNew) {
      if (!this.created || !(this.created instanceof Object)) {
        this.created = {}
      }
      this.created.user = user.displayName
    }
    if (!this.edited) {
      this.edited = {}
    }
    this.edited = { user: user.displayName, date: this.edited.date }
    this._hiddenUser = user && user.displayName || null
  })
```

Getting the same error.

**Comment by couturecraigj** [comment]
Also here is my Model

```javascript
const TagSchema = new mongoose.Schema({
    name: { $type: String, index: 'text' },
    type: {
      $type: String,
      enum: [ 'bestUses', 'pros', 'cons' ]
    },
    created: {
      user: { $type: String, required: true },
      date: { $type: Date, default: new Date }
    },
    edited: {
      user: { $type: String, required: true },
      date: Date
    },
    slug: { $type: String, slug: [ 'name', 'type' ], unique: true },
    metric: String
  }, {
    typeKey: '$type',
    collection: 'tag',
    timestamps: {
      createdAt: 'created.date',
      updatedAt: 'edited.date'
    }
  })
```

**Comment by vkarpov15** [comment]
@couturecraigj going to need more details. Based on your stack trace it looks like `TagSchema` is embedded in another schema, can I see that? Also, looks like you're using jest (AKA the test framework that magically makes perfectly functional code not work), can you show your tests?

**Comment by couturecraigj** [comment]
I have dug deeper and deeper into this rabbit hole... It actually appears to be an issue with dealing with Jest testing.  I am going to close this because as far as I can tell right now since it passes in Mocha their testing framework causes issues.  Because I like writing my test next to my code I am just going to try to mock out all of mongoose.

**Comment by vkarpov15** [comment]
Have you figured out what in jest is causing the issue? Any ideas? I've seen more than a few issues with mongoose and jest but haven't been able to figure out heads or tails of any of them because I don't use jest.
