### ISSUE TITLE
runSettersOnQuery breaks if query is on _id

### ISSUE THREAD

**Issue by zbjornson** [Automattic/mongoose#5351]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

The test case below fails. The important features are `runSettersOnQuery: true` on the schema, and the use of `_id` in the `findOneAndUpdate` query.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
  it('runSettersOnQuery works with _id field (gh-XXXX)', function(done) {
    var db = start();

    var testSchema = new Schema({
      val: { type: String }
    }, { runSettersOnQuery: true });

    var Test = db.model('gh-XXXX', testSchema);
    Test.create({ val: "A string" }).
      then(function() {
        return Test.findOne({});
      }).
      then(function(doc) {
        return Test.findOneAndUpdate({_id: doc._id}, {$set: {val: "another string"}}, { new: true });
      }).
      then(function(doc) {
        assert.ok(doc);
        assert.equal(doc.val, "another string");
      }).
      then(done).
      catch(done);
  });
```

The `findOneAndUpdate` part throws

```
     TypeError: Cannot set property '_id' of undefined
      at resetId (lib\schema\objectid.js:204:16)
      at ObjectId.SchemaType._applySetters (lib\schematype.js:637:22)
      at ObjectId.SchemaType.applySetters (lib\schematype.js:661:16)
      at ObjectId.SchemaType._castForQuery (lib\schematype.js:1021:17)
      at ObjectId.castForQuery (lib\schema\objectid.js:189:15)
      at cast (lib\cast.js:232:32)
      at Query.cast (lib\query.js:2933:12)
      at castQuery (lib\query.js:2835:18)
      at Query._findAndModify (lib\query.js:1980:17)
      at Query._findOneAndUpdate (lib\query.js:1858:8)
      at node_modules\kareem\index.js:257:8
      at node_modules\kareem\index.js:23:7
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

**What is the expected behavior?**
Should work! :)

**Please mention your node.js, mongoose and MongoDB version.**
Node 6.10.x, master branch of mongoose, mongodb 2.2.27

**Comment by vkarpov15** [comment]
Fixed in 48d64ad
