### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5362]
I can't tell if this error is from the async library or mongoose, but I don't think it's my code:

```
 => CDT server has caught an "uncaughtException" =>  TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined
    at isAsync (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:175:32)
    at wrapAsync (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:179:12)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:3830:9
    at replenish (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:931:17)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:906:16
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:3835:13
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:3838:9
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:421:16
    at replenish (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:941:25)
    at iterateeCallback (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:931:17)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:906:16
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:3835:13
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:998:13)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/async/dist/async.js:906:16
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/model.js:3755:16
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/model.js:926:19
    at done (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/model.js:940:17)
    at create (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/model.js:968:24)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/model.js:981:7
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/utils.js:532:16
    at handleCallback (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/db.js:1159:49
    at handleCallback (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/db.js:1582:5
    at handleCallback (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:860:16

```

any idea what it might be from?

I was on  "mongoose": "~4.8.4", and the error occurred - then I upgraded to    "mongoose": "^4.10.6", and I still see the error.

**Comment by ORESoftware** [comment]
nevermind! totally my fault, this was because of non-existent import in my codebase

const {x} = require('Z');

where x wasn't event close to existing lol
