### ISSUE TITLE
validateSync with `strict: "throw"` not throwing for child schemas

### ISSUE THREAD

**Issue by ksloan** [Automattic/mongoose#5368]
Why does validateSync() not throw in this situation?

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
validateSync() does not throw if a child has extra attributes, and strict is set to "throw"

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/ksloan/2a2131bb93f8ffecd10fff5260e1a7bd

**What is the expected behavior?**
validateSync() to throw if a child has extra attributes, and strict is set to "throw"

**Please mention your node.js, mongoose and MongoDB version.**
node: v8.1.2
mongoose: 4.10.6

**Comment by ksloan** [comment]
Here is an even simpler example, why doesn't validateSync() throw or report errors for this?

```js
const mongoose = require('mongoose')

const schema = mongoose.Schema({
  list: [{ name: String }]
}, {
  strict: 'throw'
})

const Model = mongoose.model('Model', schema)

const errors = new Model({
  list: [{ name: 'test', extra: 'test' }]
}).validateSync()

console.log(errors) // undefined
```

**Comment by ksloan** [comment]
When you `save()`  the document this throws an error properly for the child document, but is there no way to validate the document first before trying to save it? What is the point of `validateSync()` if not for this purpose?

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix. This is a bug.

**Comment by vkarpov15** [comment]
Hmm so upon further inspection I get the error message when running your script with mongoose 4.10.6:

```
$ node gh-5368.js 
{ ValidationError: Model validation failed: list: Cast to Array failed for value "[ { name: 'test', extra: 'test' } ]" at path "list"
    at ValidationError.inspect (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/node_modules/mongoose/lib/error/validation.js:64:23)
    at formatValue (util.js:369:36)
    at inspect (util.js:203:10)
    at exports.format (util.js:69:24)
    at Console.log (console.js:43:37)
    at Object.<anonymous> (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/gh-5368.js:15:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
  errors: 
   { list: 
      { MongooseError: Cast to Array failed for value "[ { name: 'test', extra: 'test' } ]" at path "list"
          at CastError (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/node_modules/mongoose/lib/error/cast.js:26:11)
          at model.Document.set (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:754:7)
          at model._handleIndex (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:587:14)
          at model.Document.set (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:547:24)
          at model.Document (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:71:12)
          at model.Model (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/node_modules/mongoose/lib/model.js:46:12)
          at new model (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/node_modules/mongoose/lib/model.js:3621:13)
          at Object.<anonymous> (/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose/gh-5368.js:11:16)
          at Module._compile (module.js:571:32)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:488:32)
          at tryModuleLoad (module.js:447:12)
          at Function.Module._load (module.js:439:3)
          at Module.runMain (module.js:605:10)
          at run (bootstrap_node.js:423:7)
          at startup (bootstrap_node.js:147:9)
        message: 'Cast to Array failed for value "[ { name: \'test\', extra: \'test\' } ]" at path "list"',
        name: 'CastError',
        stringValue: '"[ { name: \'test\', extra: \'test\' } ]"',
        kind: 'Array',
        value: [Object],
        path: 'list',
        reason: [Object] } },
  _message: 'Model validation failed',
  name: 'ValidationError' }
$ npm list | grep "mongoose"
/Users/vkarpov15/Workspace/mongodb/troubleshoot-mongoose
└─┬ mongoose@4.10.6
$ 
```

It looks like you're expecting `validateSync()` to throw when there's an error, which it will not do. Otherwise, can you double check your mongoose version and whether the script you posted accurately reproduces your issue?

**Comment by ksloan** [comment]
Ah, I see now that it returns a ValidationError message for extra attributes in child docs, but it throws for extra attributes in the parent. Thanks!
