### ISSUE TITLE
Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by Lionad-Morotar** [Automattic/mongoose#5371]
## my `comments` component structures like this :
user.comment = [ floor one,  floor two, ... ]
floorone = [ comment one , comment sec ... ]

## I try to push a new comment but got an wierd error :
```
user.comment.map((comments, comments_index) => {
	comments.map((comment, comment_index) => {
		if (comment._id == reply_to) { 
			comments.push({ 
					name: 		username,
					date: 		new Date(),
					message: 	message,
			})
			console.log(comments)
			item.save(err=>console.log(err))
			return true
		}
	})
})
```

error like this :
```
Unhandled rejection TypeError: Right-hand side of 'instanceof' is not callable
    at Array._cast (C:\nodejs\myblog\node_modules\mongoose\lib\types\documentarray.js:103:15)
    at Array._mapCast (C:\nodejs\myblog\node_modules\mongoose\lib\types\array.js:296:17)
    at Arguments.map (native)
    at Array.push (C:\nodejs\myblog\node_modules\mongoose\lib\types\array.js:309:25)
    at comments.map (C:\nodejs\myblog\models\UserActions.js:409:20)
    at Array.map (native)
    at item.comment.map (C:\nodejs\myblog\models\UserActions.js:407:18)
    at Array.map (native)
    at User.findOne.then.item (C:\nodejs\myblog\models\UserActions.js:406:21)
    at tryCatcher (C:\nodejs\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\nodejs\myblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\nodejs\myblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\nodejs\myblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\nodejs\myblog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\nodejs\myblog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\nodejs\myblog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\nodejs\myblog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by vkarpov15** [comment]
Can you show your schemas please?

**Comment by Lionad-Morotar** [comment]
:-) Thanks 2333, Here's my Schemas 

Here's my userSchema :
```
var userSchema = new mongoose.Schema({
        ...
	comment: 	[[userCommentSchema]],
	created: 	        {type:Date, 	default:Date.now},
        ...
},{ versionKey: false })
```

And here's my userCommentSchema : 
```
var userCommentSchema = new mongoose.Schema({
	name: 			String,
	date: 			Date,
	message: 		String,
	picture_url: 	        [String],
	like_number:          	Number,
	dislike_number:       Number,
},{ versionKey: false })
```
So ... For example , I am "Lionad" and my db-structure like this : 
```
name        : Lionad,
comment  : [
       [ { comment_first }, { comment_sec } ... ],
       [ { comment_third }, { comment_fourth } ... ],
       ...
] 
```
![image](https://user-images.githubusercontent.com/26913795/27417384-83f610a8-5746-11e7-8a68-b4370e310aab.png)

**Comment by varunjayaraman** [comment]
@Lionad-Morotar this is pretty hard to reason through, especially because you are using `.map` to mutate an array and pushing to the same array you are mutating, also while making an asynchronous `.save` call inside the nested `map` function. 

It looks like all you are trying to do is push an item into a nested array if the `comment._id` is equal to `reply_to`. To do that, all you have to do is do:

```javascript
const comment = user.comments.find(commentArr => commentArr.find(comment => 
  comment._id.toString() === reply_to));
if (comment) {
  user.comments.push({ ... });
}
```

Can you please try a solution like that?

**Comment by Lionad-Morotar** [comment]
@varunjayaraman Wow so thanks for your methods , I have tried this but unfortunately still the same error message occured... 

![image](https://user-images.githubusercontent.com/26913795/27625051-c038679a-5c15-11e7-952f-7c6a7bcca683.png)
![image](https://user-images.githubusercontent.com/26913795/27625055-cb37449a-5c15-11e7-805d-e21a2c629d7d.png)

I have crawl over CNode、Git and SOF , strangely no one else came across the same error before ... So I think maybe the complex structure  of my userSchema caused this problem ... Though it has trapped me for months , Im ready to change my userSchema with new structures and hoping to come across new ideas to get it down at the same time 。。。

**Comment by varunjayaraman** [comment]
can i see how you implemented it?

**Comment by Lionad-Morotar** [comment]
@varunjayaraman I has gave up this method & restructure my DB ：D
