### ISSUE TITLE
mongoose 4.10.7 cannot connect a hidden mongodb node with ssl

### ISSUE THREAD

**Issue by orangemi** [Automattic/mongoose#5380]
node v6.10.2
mongoose v4.10.7

when I call
```
mongoose.createConnection(url, dbOptions)
/*
  url: mongodb://xxxx:xxxx@mongoXXX:27017/xxx?&ssl=true
  dbOptions: {
    auth: { authdb: 'admin' },
    replset:
      { sslCA: <Buffer ... >,
        sslCert: <Buffer  ... >,
        sslKey: <Buffer  ... >,
        socketOptions: {},
        ssl: true }
  }
*/
```

it throws error only 3 lines...
```
{ Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:804:14) name: 'MongoError', message: 'write EPIPE' }
```

Finally I switched `mongoose` to `v4.10.6` it works.

is this bug belong to `mongodb` or `mongoose` ?

**Comment by kevinadi** [comment]
The error you're seeing seems to be consistent with SSL certificate issue.

Using this repro script, I cannot reproduce the error so far with both mongoose 4.10.6 and 4.10.7 with node 6.10.2:

```js
var mongoose = require('mongoose');
var fs = require('fs');

var Person = mongoose.model('person', mongoose.Schema({
    name: String
}));

var mongouri = 'mongodb://myhost.local:27017/test?ssl=true&replicaSet=replset';

var dbOptions = {
    replSet: {
        sslCA: [fs.readFileSync('ca.crt')],
        sslCert: fs.readFileSync('client.pem'),
        sslKey: fs.readFileSync('client.pem')
    }
};

var db = mongoose.connect(mongouri, dbOptions).connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function(){
    var doc = new Person({name:'Bob'});
    doc.save(function(err) {
        if (err) {
            return console.log(err);
        }
        db.close();
    });
});
```

Could you post a full repro script like above, and what the `mongod` logs are showing?
