### ISSUE TITLE
findByIdAndRemove() throws error

### ISSUE THREAD

**Issue by Atomic1999** [Automattic/mongoose#5382]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I want to delete a document, marked by its ID in my Databse. But instead of deleting it it throws an error that it can't set the property '_id' of undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

Code:
```
function removeSeller() {
    Seller.findByIdAndRemove("594801105cb8571868f9cd55",function (err) {
        console.log(err);
    });
}
```
Error:
```
TypeError: Cannot set property '_id' of undefined
    at resetId (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\schema\objectid.js:204:16)
    at ObjectId.SchemaType._applySetters (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\schematype.js:637:22)
    at ObjectId.SchemaType.applySetters (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\schematype.js:661:16)
    at ObjectId.SchemaType._castForQuery (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\schematype.js:1021:17)
    at ObjectId.castForQuery (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\schema\objectid.js:189:15)
    at cast (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\cast.js:232:32)
    at model.Query.Query.cast (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\query.js:2933:12)
    at castQuery (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\query.js:2835:18)
    at model.Query.Query._findAndModify (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\query.js:1980:17)
    at model.Query.Query.findOneAndRemove (Z:\Documents\Programming\Projext XY\repo\node_modules\mquery\lib\mquery.js:2585:15)
    at model.Query.Query._findOneAndRemove (Z:\Documents\Programming\Projext XY\repo\node_modules\mongoose\lib\query.js:1944:31)
    at Z:\Documents\Programming\Projext XY\repo\node_modules\kareem\index.js:257:8
    at Z:\Documents\Programming\Projext XY\repo\node_modules\kareem\index.js:23:7
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Please mention your node.js, mongoose and MongoDB version.**
node.js: 8.1.2
mongoose: 4.10.7
MongoDB: 3.2.13

**Comment by Atomic1999** [comment]
Ok it seems like it is the same issue as this:
#5351
