### ISSUE TITLE
 this.__parentArray._markModified is not a function

### ISSUE THREAD

**Issue by antonpash** [Automattic/mongoose#5430]
I'm getting the following error on push command when updating the array of nested documents with `{runValidators: true}`:
```
TypeError: this.__parentArray._markModified is not a function
    at EmbeddedDocument.markModified (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/types/embedded.js:87:24)
    at EmbeddedDocument.Document.$__set (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/document.js:852:10)
    at EmbeddedDocument.Document.set (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/document.js:763:10)
    at EmbeddedDocument._handleIndex (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/document.js:591:14)
    at EmbeddedDocument.Document.set (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/document.js:551:24)
    at EmbeddedDocument.Document (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/document.js:71:12)
    at EmbeddedDocument [as constructor] (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/types/embedded.js:31:12)
    at new EmbeddedDocument (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/schema/documentarray.js:70:17)
    at /Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/schema/documentarray.js:172:26
    at DocumentArray.SchemaType.doValidate (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/schematype.js:743:12)
    at DocumentArray.doValidate (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/schema/documentarray.js:135:35)
    at /Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/services/updateValidators.js:110:22
    at /Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/node_modules/async/internal/parallel.js:27:9
    at eachOfArrayLike (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/node_modules/async/eachOf.js:57:9)
    at exports.default (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/node_modules/async/eachOf.js:9:5)
    at _parallel (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/node_modules/async/internal/parallel.js:26:5)
    at parallelLimit (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/node_modules/async/parallel.js:85:26)
    at /Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/services/updateValidators.js:145:5
    at model.Query.Query._execUpdate (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/query.js:2267:7)
    at /Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/kareem/index.js:257:8
    at args (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/kareem/index.js:76:20)
    at model.Query.<anonymous> (/Users/antonpash1/PhpstormProjects/addspo/backend/node_modules/mongoose/lib/schema.js:881:7)
POST /api/events/5958e32ce679150ad808e2b2/invite-friends 500 92.338 ms - 52
```

Here is my schemas:
```javascript
//Part of UserSchema
notifications: {
	type: [NotificationSchema]
},

//NotificationSchema
var NotificationSchema = new Schema({
	type: {
		type: String,
		enum: Object.values(NOTIFICATION_TYPES),
		required: true
	},
	message: {
		type: String,
		required: true
	},
	event: {
		type: Schema.Types.ObjectId,
		ref: 'Event',
		required: function () {
			return this.type === NOTIFICATION_TYPES.INVITATION;
		}
	}
}, {
	timestamps: true
});

NotificationSchema.statics.NOTIFICATION_TYPES = NOTIFICATION_TYPES;

exports.Schema = NotificationSchema;
exports.Model = mongoose.model('Notification', NotificationSchema);
```

And this actually the code:
```javascript
User.update(
	{'_id': {'$in': friends_ids}},
	{
		'$push': {
			'notifications': {
				'$each': [notification]
			}
		}
	},
	{multi: true, runValidators: true}
);
```

The error seems to be gone if command would be without `{runValidators: true}` option

Versions:
```
MongoDB: 3.4.1
Node: 7.9.0
Mongoose: 4.11.0
```

**Comment by varunjayaraman** [comment]
yup this looks like a bug:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5430`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    
    const notificationSchema = new mongoose.Schema({
      message: String
    });
    
    const Notification = db.model('Notification', notificationSchema);

    const userSchema = new mongoose.Schema({
      notifications: [notificationSchema]
    });

    const User = db.model('User', userSchema);

    yield [User.remove({})];

    const doc = yield User.create({
      notifications: []
    });

    yield User.update({ _id: doc._id }, {
      $push: {
        notifications: {
          $each: [new Notification({ message: 'test' })]
        }
      }
    }, { multi: true, runValidators: true });
    
  });
}
```
