### ISSUE TITLE
promiseLibrary option is not propagated to Admin in 4.11.1

### ISSUE THREAD

**Issue by tinovyatkin** [Automattic/mongoose#5463]
```js
async function testOpen() {
  await mongoose.connect(MONGOHQ_URL, {
    useMongoClient: true,
    promiseLibrary: global.Promise,
  });
 // getting MongoDB server version
  const admin = new mongoose.mongo.Admin(mongoose.connection.db);
  const info = await admin.buildInfo();
}
```

throws with error:
```
Exception has occurred: TypeError
TypeError: this.s.promiseLibrary is not a constructor
    at Admin.buildInfo (/Users/tino/Repos/engine/node_modules/mongodb/lib/admin.js:104:10)
    at NativeConnection.start (/Users/tino/Repos/engine/server/lib/mongoose.js:105:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by tinovyatkin** [comment]
I've found that Admin constructor accepts `promiseLibrary` as parameter

**Comment by cp4r3z** [comment]
> I've found that Admin constructor accepts `promiseLibrary` as parameter

Thanks @tinovyatkin! Just to save others some time:
```javascript
const admin = new mongoose.mongo.Admin(admindb, undefined, global.Promise);
```
_mongoose v4.12.1_
