### ISSUE TITLE
Error: Cannot find module '../services/cursor/eachAsync

### ISSUE THREAD

**Issue by mariohmol** [Automattic/mongoose#5494]
BUG

When i try to run node in heroku or travis gives me an exception.

Here is the travis build:

* https://travis-ci.org/camillecondrey/mood-boost-api

In heroku i have this error:

```
Error: Cannot find module '../services/cursor/eachAsync' 
2017-07-21T00:28:23.039843+00:00 app[web.1]: at Function.Module._resolveFilename (module.js:469:15) 
2017-07-21T00:28:23.039844+00:00 app[web.1]: at Function.Module._load (module.js:417:25) 
2017-07-21T00:28:23.039844+00:00 app[web.1]: at Module.require (module.js:497:17) 
2017-07-21T00:28:23.039845+00:00 app[web.1]: at require (internal/module.js:20:19) 
2017-07-21T00:28:23.039846+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/mongoose/lib/cursor/QueryCursor.js:7:17) 
2017-07-21T00:28:23.039847+00:00 app[web.1]: at Module._compile (module.js:570:32) 
2017-07-21T00:28:23.039847+00:00 app[web.1]: at Object.Module._extensions..js (module.js:579:10) 
2017-07-21T00:28:23.039848+00:00 app[web.1]: at Module.load (module.js:487:32) 
2017-07-21T00:28:23.039848+00:00 app[web.1]: at tryModuleLoad (module.js:446:12) 
2017-07-21T00:28:23.039849+00:00 app[web.1]: at Function.Module._load (module.js:438:3)
```

It should run and open the express as is running locally

Tryed to use in package json node 7.7.4 , but didnt work.

https://github.com/camillecondrey/mood-boost-api/blob/master/package.json#L30

@camillecondrey

**Comment by varunjayaraman** [comment]
hm, thats a weird one. You aren't using a bundler by any chance are you?

**Comment by mariohmol** [comment]
Hi thanks for answering @varunjayaraman !   

its a pure node/express app, it runs `node server.js` and server.js its like `app.listen`.  

https://github.com/camillecondrey/mood-boost-api/blob/master/server.js#L37

Tested with mongose versions 4.11.1 and 4.11.3

**Comment by varunjayaraman** [comment]
I'll try and reproduce soon on node 8 (i use 6.9.2 still)

**Comment by mariohmol** [comment]
me too.. but i used on package.json `"node": "7.7.4"`but still running over 8 in travis/heroku.. i dont know if is related to some nodejs versions that must no be used regarding security issues.. see this advisor for heroku

* https://kb.heroku.com/node-js-constant-hashtable-seeds-vulnerability-faq

```
 You need to assure your engines section specifies a version that is not vulnerable: 4.8.4, 6.11.1, 7.10.1, or 8.1.4. 
```

**Comment by vkarpov15** [comment]
I took a look at your github repo and yeah looks like that file isn't there for some reason: https://github.com/camillecondrey/mood-boost-api/tree/master/node_modules/mongoose/lib/services . I'd strongly recommend you remove your `node_modules` folder from your repo `git rm node_modules` and stop committing it to GitHub, this might very well fix this particular issue because then travis will get a clean install of mongoose.

**Comment by mariohmol** [comment]
My gosh, make totally sense.. sorry about that.. missed the node_modules folder there!
thanks!
