### ISSUE TITLE
Can't create array property like this children: [{type: childSchema}]

### ISSUE THREAD

**Issue by stas-sl** [Automattic/mongoose#5521]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**
````
const childSchema = mongoose.Schema({
  name: String
})

const parentSchema = mongoose.Schema({
  children: [{type: childSchema}]
})
````
throws:
````
TypeError: Undefined type `undefined` at array `children`
    at Function.Schema.interpretAsType (.../node_modules/mongoose/lib/schema.js:626:15)
    at Schema.path (.../node_modules/mongoose/lib/schema.js:519:29)
    at Schema.add (.../node_modules/mongoose/lib/schema.js:400:12)
````

Though this works well:
````
const parentSchema = mongoose.Schema({
  children: {type: childSchema}
})
````
And this also:
````
const parentSchema = mongoose.Schema({
  children: [childSchema]
})
````
As well as this:
````
const parentSchema = mongoose.Schema({
  children: [{type: mongoose.Schema.Types.ObjectId}]
})
````

**What is the expected behavior?**

I expect
````
const childSchema = mongoose.Schema({
  name: String
})

const parentSchema = mongoose.Schema({
  children: [{type: childSchema}]
})
````
to work as well

**Please mention your node.js, mongoose and MongoDB version**

* node.js v7.8.0
* mongoose v4.11.4
* MongoDB v3.4.4

**Comment by varunjayaraman** [comment]
yup, this looks like a bug:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5521`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const childSchema = new mongoose.Schema({
      name: String
    });

    const schema = new mongoose.Schema({
      children: [{ type: childSchema }]
    });

    const Model = db.model('Model', schema);

    const doc = new Model({ children: [{ name: 'test' }] });
  });
}
```
