### ISSUE TITLE
Saving a model fails with mongo error: MongoError: Unknown modifier: $pushAll

### ISSUE THREAD

**Issue by dyladan** [Automattic/mongoose#5574]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Test passing on local machine but failing on jenkins server with the exact same versions. The only difference is local is macos and jenkins is ubuntu as far as I can tell.

On MacOS Sierra, node 8.4 and 7.11, mongodb 3.4.7, and mongoose 4.11.7 the following test passes, but on our jenkins server with the exact same versions on an ubuntu 16.04 server fails.

```
  it("should successfully allow an alias that matches a service", async () => {
    const aliasTag = "this is a test";
    const appAlias = await AliasController.create(user, appAliasSpec);
    const serviceAlias = await AliasController.create(user, serviceAliasSpec);

    appAlias.aliases.push(aliasTag);
    await appAlias.save(); // This is the line that fails in jenkins

    serviceAlias.aliases.push(aliasTag);
    await serviceAlias.save();

    const confAppAlias = await AliasController.getById(appAlias._id);
    const confServiceAlias = await AliasController.getById(serviceAlias._id);
    expect(confAppAlias.aliases[1]).to.equal(aliasTag);
    expect(confServiceAlias.aliases[1]).to.equal(aliasTag);
  });
```

Here is the exact error that i'm getting:

```
{
	"message": "Unknown modifier: $pushAll",
	"name": "MongoError",
	"stack": "MongoError: Unknown modifier: $pushAll\n    at Function.MongoError.create (/var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb-core/lib/error.js:31:11)\n    at toError (/var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb/lib/utils.js:139:22)\n    at /var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb/lib/collection.js:1060:67\n    at /var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb-core/lib/connection/pool.js:469:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)",
	"code": 9
}
```

edit: Here is a more readable version of the stack trace

```
MongoError: Unknown modifier: $pushAll
    at Function.MongoError.create (/var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb/lib/utils.js:139:22)
    at /var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb/lib/collection.js:1060:67
    at /var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by varunjayaraman** [comment]
can you do `mongoose.set('debug', true)` and paste the mongo output?

**Comment by dyladan** [comment]
```
pushing to app alias
Mongoose: aliases.update({ _id: ObjectId("599d98122b72d12e0ba858b4") }, { '$pushAll': { aliases: [ 'this is a test' ] }, '$set': { updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT") }, '$inc': { __v: 1 } })
{"name":"davis","hostname":"ld-ub-bm980a98v","pid":11787,"level":50,"err":{"message":"Unknown modifier: $pushAll","name":"MongoError","stack":"MongoError: Unknown modifier: $pushAll\n    at Function.MongoError.create (/var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb-core/lib/error.js:31:11)\n    at toError (/var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb/lib/utils.js:139:22)\n    at /var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb/lib/collection.js:1060:67\n    at /var/lib/jenkins/workspace/davis-cloudcontrol/node_modules/mongodb-core/lib/connection/pool.js:469:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","code":9},"msg":"An unhandled Mongo error occurred.","time":"2017-08-23T14:58:26.201Z","v":0}
    1) should successfully allow an alias that matches a service
Mongoose: users.remove({}, {})
Mongoose: aliases.remove({}, {})
Mongoose: tenants.remove({}, {})
Mongoose: filters.remove({}, {})
Mongoose: users.findOne({ email: 'test@test.test' }, { fields: { _id: 1 } })
Mongoose: users.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), email: 'test@test.test', _id: ObjectId("599d98122b72d12e0ba858b6"), customTenants: [], socketToken: 'fd47cc49aef6d1716e9a7fcff4295494a0637ec0ed8594a61082880e4cbfaade', navigationHelp: true, voiceNavigation: true, savedTimezone: 'Etc/UTC', __v: 0 })
Mongoose: tenants.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), name: 'Mocha Tenant', tid: 'fakeid', env: 'prod', _id: ObjectId("599d98122b72d12e0ba858b7"), hooks: { postIntent: [] }, customAdmins: [], access: { tokens: [ 'fakeToken' ], active: 0 }, __v: 0 })
Mongoose: users.findOne({ _id: ObjectId("599d98122b72d12e0ba858b6") }, { fields: {} })
Mongoose: users.update({ _id: ObjectId("599d98122b72d12e0ba858b6") }, { '$set': { tenant: ObjectId("599d98122b72d12e0ba858b7"), updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT") } })
Mongoose: users.findOne({ _id: ObjectId("599d98122b72d12e0ba858b6") }, { fields: {} })
Mongoose: tenants.find({ _id: { '$in': [ ObjectId("599d98122b72d12e0ba858b7") ] } }, { fields: {} })
Mongoose: aliases.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), entityId: 'APPLICATION-59CA712F666CD24D', tenant: ObjectId("599d98122b72d12e0ba858b7"), _id: ObjectId("599d98122b72d12e0ba858b8"), display: { audible: 'Say something about this app', visual: 'Show something about this app' }, aliases: [ 'An app' ], __v: 0 })
Mongoose: aliases.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), entityId: 'APPLICATION-0CB08EBCB23C8D3B', tenant: ObjectId("599d98122b72d12e0ba858b7"), _id: ObjectId("599d98122b72d12e0ba858b9"), aliases: [], __v: 0 })
Mongoose: aliases.findOne({ tenant: ObjectId("599d98122b72d12e0ba858b7"), _id: ObjectId("599d98122b72d12e0ba858b8") }, { fields: {} })
Mongoose: aliases.find({ '$or': [ { aliases: { '$in': [ [31m/^this is a test$/i ] }, entityId: [31m/^APPLICATION/i }, { name: [ [31m/^this is a test$/i ], entityId: [31m/^APPLICATION/i } ], tenant: ObjectId("599d98122b72d12e0ba858b7"), _id: { '$ne': ObjectId("599d98122b72d12e0ba858b8") } }, { fields: {} })
Mongoose: aliases.update({ _id: ObjectId("599d98122b72d12e0ba858b8"), __v: 0 }, { '$set': { aliases: [ 'this is a test' ], display: { audible: [90mundefined, visual: [90mundefined }, updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT") }, '$inc': { __v: 1 } })
Mongoose: aliases.findOne({ tenant: ObjectId("599d98122b72d12e0ba858b7"), _id: ObjectId("599d98122b72d12e0ba858b9") }, { fields: {} })
Mongoose: aliases.find({ '$or': [ { aliases: { '$in': [ [31m/^this is a test$/i ] }, entityId: [31m/^APPLICATION/i }, { name: [ [31m/^this is a test$/i ], entityId: [31m/^APPLICATION/i } ], tenant: ObjectId("599d98122b72d12e0ba858b7"), _id: { '$ne': ObjectId("599d98122b72d12e0ba858b9") } }, { fields: {} })
    ✓ should reject new alias tag due to duplicate entry (22ms)
Mongoose: users.remove({}, {})
Mongoose: aliases.remove({}, {})
Mongoose: tenants.remove({}, {})
Mongoose: filters.remove({}, {})
Mongoose: users.findOne({ email: 'test@test.test' }, { fields: { _id: 1 } })
Mongoose: users.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), email: 'test@test.test', _id: ObjectId("599d98122b72d12e0ba858ba"), customTenants: [], socketToken: '67f9c0650a6eb9471a8a6ad581563c02a294f0ed767f6a749a409729da6dd970', navigationHelp: true, voiceNavigation: true, savedTimezone: 'Etc/UTC', __v: 0 })
Mongoose: tenants.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), name: 'Mocha Tenant', tid: 'fakeid', env: 'prod', _id: ObjectId("599d98122b72d12e0ba858bb"), hooks: { postIntent: [] }, customAdmins: [], access: { tokens: [ 'fakeToken' ], active: 0 }, __v: 0 })
Mongoose: users.findOne({ _id: ObjectId("599d98122b72d12e0ba858ba") }, { fields: {} })
Mongoose: users.update({ _id: ObjectId("599d98122b72d12e0ba858ba") }, { '$set': { tenant: ObjectId("599d98122b72d12e0ba858bb"), updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT") } })
Mongoose: users.findOne({ _id: ObjectId("599d98122b72d12e0ba858ba") }, { fields: {} })
Mongoose: tenants.find({ _id: { '$in': [ ObjectId("599d98122b72d12e0ba858bb") ] } }, { fields: {} })
Mongoose: aliases.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), entityId: 'APPLICATION-59CA712F666CD24D', tenant: ObjectId("599d98122b72d12e0ba858bb"), _id: ObjectId("599d98122b72d12e0ba858bc"), display: { audible: 'Say something about this app', visual: 'Show something about this app' }, aliases: [ 'An app' ], __v: 0 })
Mongoose: aliases.find({ entityId: { '$regex': [31m/^(APPLICATION|MOBILE_APPLICATION)/i }, tenant: ObjectId("599d98122b72d12e0ba858bb") }, { fields: {} })
    ✓ should successfully merge the alias on the entity (11ms)
Mongoose: users.remove({}, {})
Mongoose: aliases.remove({}, {})
Mongoose: tenants.remove({}, {})
Mongoose: filters.remove({}, {})

  Filters
Mongoose: users.findOne({ email: 'test@test.test' }, { fields: { _id: 1 } })
Mongoose: users.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), email: 'test@test.test', _id: ObjectId("599d98122b72d12e0ba858bd"), customTenants: [], socketToken: '3650b341485c020ff4cd5c24bedbbe44b2f03be302f41a21d9521845dfea5c63', navigationHelp: true, voiceNavigation: true, savedTimezone: 'Etc/UTC', __v: 0 })
Mongoose: tenants.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), name: 'Mocha Tenant', tid: 'fakeid', env: 'prod', _id: ObjectId("599d98122b72d12e0ba858be"), hooks: { postIntent: [] }, customAdmins: [], access: { tokens: [ 'fakeToken' ], active: 0 }, __v: 0 })
Mongoose: users.findOne({ _id: ObjectId("599d98122b72d12e0ba858bd") }, { fields: {} })
Mongoose: users.update({ _id: ObjectId("599d98122b72d12e0ba858bd") }, { '$set': { tenant: ObjectId("599d98122b72d12e0ba858be"), updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT") } })
Mongoose: users.findOne({ _id: ObjectId("599d98122b72d12e0ba858bd") }, { fields: {} })
Mongoose: tenants.find({ _id: { '$in': [ ObjectId("599d98122b72d12e0ba858be") ] } }, { fields: {} })
    ✓ should reject new filter due to a missing name (2ms)
Mongoose: users.remove({}, {})
Mongoose: aliases.remove({}, {})
Mongoose: tenants.remove({}, {})
Mongoose: filters.remove({}, {})
Mongoose: users.findOne({ email: 'test@test.test' }, { fields: { _id: 1 } })
Mongoose: users.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), email: 'test@test.test', _id: ObjectId("599d98122b72d12e0ba858c0"), customTenants: [], socketToken: '76ebfe771bccabfd09984fb8bcf6e601e8d4e6c1590ac15c7aba6378c2ef5993', navigationHelp: true, voiceNavigation: true, savedTimezone: 'Etc/UTC', __v: 0 })
Mongoose: tenants.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), name: 'Mocha Tenant', tid: 'fakeid', env: 'prod', _id: ObjectId("599d98122b72d12e0ba858c1"), hooks: { postIntent: [] }, customAdmins: [], access: { tokens: [ 'fakeToken' ], active: 0 }, __v: 0 })
Mongoose: users.findOne({ _id: ObjectId("599d98122b72d12e0ba858c0") }, { fields: {} })
Mongoose: users.update({ _id: ObjectId("599d98122b72d12e0ba858c0") }, { '$set': { tenant: ObjectId("599d98122b72d12e0ba858c1"), updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT") } })
Mongoose: users.findOne({ _id: ObjectId("599d98122b72d12e0ba858c0") }, { fields: {} })
Mongoose: tenants.find({ _id: { '$in': [ ObjectId("599d98122b72d12e0ba858c1") ] } }, { fields: {} })
Mongoose: filters.insert({ updatedAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), createdAt: new Date("Wed, 23 Aug 2017 14:58:26 GMT"), name: 'test filter', owner: ObjectId("599d98122b72d12e0ba858c0"), tenant: ObjectId("599d98122b72d12e0ba858c1"), _id: ObjectId("599d98122b72d12e0ba858c2"), tags: { excludes: [], includes: [] }, excludeEventType: [], entity: [ 'APPLICATION-160363DF4AFFF4A0' ], severityLevel: [], impact: [], status: [], enabled: true, scope: 'global', __v: 0 })
Mongoose: filters.findOne({ _id: ObjectId("599d98122b72d12e0ba858c2") }, { fields: {} })
    ✓ should create a new global filter (9ms)
Mongoose: users.remove({}, {})
Mongoose: aliases.remove({}, {})
Mongoose: tenants.remove({}, {})
Mongoose: filters.remove({}, {})
```

**Comment by dyladan** [comment]
For what it's worth, I checked the debug output in our local development and production environments and they're both using the $pushAll modifier successfully. Mongo is installed from the official packages in all cases. Development machines are windows and MacOS, production machines are amazon linux.

**Comment by vkarpov15** [comment]
Can you connect to your jenkins mongodb instance using the mongo shell and double check the version using `db.version`?

```
$ mongo test
MongoDB shell version v3.4.1
connecting to: mongodb://127.0.0.1:27017/test
MongoDB server version: 3.4.1 
> db.version()
3.4.1
> ^C
bye
```

You can also print the server version out using the `serverStatus()` command using mongoose:

```javascript
const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/test');

mongoose.connection.on('open', function() {
  mongoose.connection.db.admin().serverStatus(function(error, info) {
    console.log(info.version);
  });
});
```

Please double check your version first, official packages tend to fall out of date pretty quickly.

**Comment by Spown** [comment]
yep, have the same error. tried to move from 3.2 to 3.5 (no data migration). I have an array field 
```js
    'liked': {
        'item':[ {
            'id': {'type': Types.ObjectId, 'ref': 'Item'},
            'score': {'type': Number, 'max': 100, 'default': -1},
            'comment': {'type': String, 'maxlength': 65000, 'trim': true, 'default': '', 'set': san.methods.safe}
        } ]
    },
```
I know, ``id`` is not the best field name, but hey, it worked in 3.2. In 3.5 it fails after trying to ``.save()`` the doc after an Item been pushed into the array. I push the items via ``.push()`` and then mark the field ``.markModified('liked.item');``. schould be simple.

**Comment by vkarpov15** [comment]
MongoDB 3.5?

**Comment by Spown** [comment]
yes

```
 targetMinOS: Windows 7/Windows Server 2008 R2
 db version v3.5.13
 git version: 52bbaa007cd84631d6da811d9a05b59f2dfad4f3
 OpenSSL version: OpenSSL 1.0.1u-fips  22 Sep 2016
 allocator: tcmalloc
 modules: none
 build environment:
     distmod: 2008plus-ssl
     distarch: x86_64
     target_arch: x86_64
```

**Comment by vkarpov15** [comment]
Well that's one problem, mongodb 3.5 is an unstable dev release and should not be used. $pushAll has been deprecated for a long time so perhaps they got rid of it in 3.5. @mbroadst can you clarify?

We added a `usePushEach` option to work around this a while back: https://github.com/Automattic/mongoose/issues/4455 , that should be a workaround for this issue:

```javascript
new Schema({ arr: [String] }, { usePushEach: true });
```

**Comment by mbroadst** [comment]
@vkarpov15 yes it's been removed for `featureCompatibilityVersion=3.6`

**Comment by vkarpov15** [comment]
Touche. In which case we'll make sure to get #5670 out.

**Comment by rankitbishnoi** [comment]
i am having the same exact problem i am using mongodb v3.6 on my ubuntu.   if the pushAll is removed from db than how should i save the instance.. please provide me any alternative

**Comment by dyladan** [comment]
@rankitbishnoi You can get around this temporarily by adding the `usePushEach` option on each schema definition in the options.

**Comment by chaddjohnson** [comment]
@vkarpov15 Thanks for the fantastic library sir.

I, too, anm experiencing this issue with Mongoose 4.13.7 and MongoDB 3.6.0.

**Comment by rod-stuchi** [comment]
@dyladan @chaddjohnson really works.
thanks a lot!

**Comment by raphaelbp12** [comment]
please, how can I do this? how can I add this to schema options? thank you!

**Comment by chaddjohnson** [comment]
@raphaelbp12 Here are the docs on using schema options: http://mongoosejs.com/docs/guide.html

**Comment by danieltanfh95** [comment]
Updating the schema does not change this behavior. It's not working for older data in the database already for 3.6.

**Comment by fredericoAlvesJS** [comment]
I was having a similar issue running the code in my machine. I think is because of Mongoose 5 and MongoDB 3.6. Try to revert back:

# Mongoose to version 4.13.8 (`npm install mongoose@4.13.8 --save`), and
# MongoDB to 3.4 (you can check the version typing `db.version()` ).

It worked for me! :)

**Comment by vkarpov15** [comment]
Mongoose 5 should not be affected by this issue, it doesn't use `$pushAll` anywhere. If you get this error with mongoose 5, please open up an issue with code samples :+1:

**Comment by DevJoseWeb** [comment]
PS C:\Users\paula\projetos\apiNode\src> node index.js
{ MongoError: Unknown modifier: $pushAll
    at Function.MongoError.create (C:\Users\paula\projetos\apiNode\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (C:\Users\paula\projetos\apiNode\node_modules\mongodb\lib\utils.js:139:22)
    at C:\Users\paula\projetos\apiNode\node_modules\mongodb\lib\collection.js:1059:67
    at C:\Users\paula\projetos\apiNode\node_modules\mongodb-core\lib\connection\pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'Unknown modifier: $pushAll',
  driver: true,
  index: 0,
  code: 9

**Comment by rivers-lis** [comment]
Всем привет, подскажите пожалуйста как исправить ошибку Неизвестный модификатор: $ pushAll

**Comment by rivers-lis** [comment]
Пробовал вот так не работает 
const mongoose = require ('mongoose') 
const Схема = mongoose.Schema

const UserSchema = new Schema ({ 
telegramId: { 
type: Number, 
required: true, 
usePushEach: true 
},

films: {
    type: [String],
    default: []
}
})

mongoose.model ('users', UserSchema)

**Comment by rivers-lis** [comment]
Как то вот так
const mongoose = require('mongoose')
const Schema = mongoose.Schema

const UserSchema = new Schema({
    telegramId: {
        type: Number,
        required: true
    },

    films: {
        type: [String],
        default: []
    }
})

new Schema({}, {usePushEach: true})

mongoose.model('users', UserSchema)

**Comment by sassy-ankit** [comment]
`new Schema({ ... }, { usePushEach: true });`
This solves the error for me too on version 4.4.12 and 5.0.7

**Comment by DanGDroid** [comment]
> Как то вот так
> const mongoose = require('mongoose')
> const Schema = mongoose.Schema
> 
> const UserSchema = new Schema({
> telegramId: {
> type: Number,
> required: true
> },
> 
> ```
> films: {
>     type: [String],
>     default: []
> }
> ```
> })
> 
> new Schema({}, {usePushEach: true})
> 
> mongoose.model('users', UserSchema)

sorry cannot read Russian

**Comment by vkarpov15** [comment]
@DanGDroid roughly translated "Как то вот так" -> "Something like this"
