### ISSUE TITLE
error message mongoose

### ISSUE THREAD

**Issue by jankoboz** [Automattic/mongoose#5580]
(node:928) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8888
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventEmitter.listen (C:\Users\dillt\Desktop\user_Auth_working_on\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\dillt\Desktop\user_Auth_working_on\app.js:57:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by vkarpov15** [comment]
The mongoose warning has nothing to do with your separate error message. The error message comes from express, which is failing because it can't listen on port 8888 because something else is already listening on port 8888

**Comment by jankoboz** [comment]
Thanks alot. 
i didn't like port 8888 anyway  lol
