### ISSUE TITLE
Exception thrown when Decimal type is used in model.

### ISSUE THREAD

**Issue by gfot** [Automattic/mongoose#5583]
The following snippet:

```
const Promise = require('bluebird');
const mongoose = require('mongoose');

mongoose.Promise = Promise;
mongoose.connect('mongodb://localhost:27017/tutorial', { useMongoClient: true });

var Doc = mongoose.model('Test', new mongoose.Schema({
    x: mongoose.Schema.Types.Decimal
    //x: Number 
}));

Doc.create({ x: '0.1' }).
  then(doc => doc.update({ $inc: { x: '0.2' } }).then(() => doc)).
  then(doc => Doc.findById(doc)).
  then(doc => console.log('doc', doc.toObject())).
  catch(error => console.error(error));
```

throws an error when model's x field type is Decimal, but works if its type is Number.
```
Mongoose: tests.insert({ x: Decimal128 { _bsontype: 'Decimal128', bytes: <Buffer 01 00 00 00 00 00 00 00 00 00 00 00 00 00 3e 30> }, _id: ObjectId("59a053ffe7ce2302e6d92ee3"), __v: 0 })
{ MongoError: connection 0 to localhost:27017 closed
    at Function.MongoError.create (/mongoose-tut/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/mongoose-tut/node_modules/mongodb-core/lib/connection/connection.js:200:22)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
  name: 'MongoError',
  message: 'connection 0 to localhost:27017 closed' }
```

Isn't possible to use the Decimal type yet?

MongoDB server version: 3.4.7
Mongoose version: 4.11.8
Node.js version: 8.3.0

**Comment by gfot** [comment]
Does anyone get the same error on this simple example? I take the same error even I drop the Bluebird promises in favour of native Node.js implementation. I really don't know why this happens. I've tested this both in Linux (Ubuntu) and Mac OS X and the error is the same.

**Comment by gfot** [comment]
I just figured out that if you have a fresh installation of MongoDB v>=3.4  then you have to type in MongoDB shell as 'admin' the command: `db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )`.

**Comment by vkarpov15** [comment]
I've never had to use this command before. I suspect this is because you've upgraded a 3.2 database to 3.4, you shouldn't need to do this with a clean install...
