### ISSUE TITLE
[Bug - Mongoose 4.11.9] CastError using discriminators with _id type String

### ISSUE THREAD

**Issue by derekaspaulding** [Automattic/mongoose#5591]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
CastError
```
{ CastError: Cast to ObjectId failed for value "123456" at path "_id"
    at CastError (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/error/cast.js:27:11)
    at ObjectId.cast (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/schema/objectid.js:154:13)
    at ObjectId.SchemaType._castForQuery (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/schematype.js:1064:15)
    at ObjectId.castForQuery (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/schema/objectid.js:194:15)
    at ObjectId.SchemaType.castForQueryWrapper (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/schematype.js:1021:15)
    at cast (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/cast.js:269:32)
    at model.Query.Query.cast (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/query.js:3104:12)
    at model.Query.Query._castConditions (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/query.js:1145:10)
    at model.Query.Query._findOneAndUpdate (/Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/mongoose/lib/query.js:1977:8)
    at /Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/kareem/index.js:250:8
    at /Users/derek.spaulding/projects/reproduce-mongoose-error/without-discriminator/node_modules/kareem/index.js:23:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Cast to ObjectId failed for value "123456" at path "_id" for model "subModel1"',
  name: 'CastError',
  stringValue: '"123456"',
  kind: 'ObjectId',
  value: '123456',
  path: '_id',
  reason: undefined,
```

**If the current behavior is a bug, please provide the steps to reproduce.**

[Gist to reproduce](https://gist.github.com/derekaspaulding/cd04217478a955bdb1ea9b3d0fb27da0)
running `node test.js` will give the error above

**What is the expected behavior?**

I would expect this to insert successfully. [This Gist](https://gist.github.com/derekaspaulding/6ff2740717e8fe397b457c1513d267ec) doesn't use discriminators and works as I would expect it to when using a discriminator.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 8.2.1
Mongoose: 4.11.9
MongoDB: 3.4.7

**Comment by derekaspaulding** [comment]
Some background on what I am trying to do:
I am pulling data from a public API and storing it in mongo. The data I get back is one of two types which have some unique fields, but have shared ID fields and many other shared fields, so I want to use discriminators. Since the data has an ID which is a string which is unique among both types, I would like to simply use this ID as my _id field to make other tasks easier between the data that I store and the public API.
