### ISSUE TITLE
findOneAndUpdate with upsert: true and overwrite: true inserts null for array values

### ISSUE THREAD

**Issue by mspensieri** [Automattic/mongoose#5631]
When using `findOneAndUpdate` with options `upsert: true` and `overwrite: true`, and the document does not previously exist, mongoose will insert `null` values into an array field. Reproduced with 4.11.10 with the following script:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;

mongoose.connect('mongodb://localhost/test-data');
mongoose.set('debug', true);

var testSchema = new mongoose.Schema({
    customIdentifier: String,
    tags: [String]
});

var TestModel = mongoose.model('test', testSchema);

var identifier = 'does-not-exist';

var update = {
    customIdentifier: identifier,
    tags: ['tag1', 'tag2']
};

TestModel.findOneAndUpdate({
    customIdentifier: identifier
}, update, {
    upsert: true,
    new: true,
    overwrite: true
}, function(err, model) {
    assert.equal(model.tags[0], 'tag1');
    assert.equal(model.tags[1], 'tag2');
    process.exit(0);
});
```

Results in the error

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: null == 'tag1'
    at /.../test.js:31:12
    at Query.<anonymous> (/.../node_modules/mongoose/lib/model.js:3832:16)
    at /.../node_modules/kareem/index.js:273:21
    at /.../node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Without the `overwrite: true` option, the insert is successful. We recently upgraded from 4.5.5 where this was working correctly, not sure in exactly which version this regression occurred.

**Comment by varunjayaraman** [comment]
yeah this looks like a bug, and it also looks like if you remove `overwrite: true`, the problem disappears:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;

mongoose.connect('mongodb://localhost/test-data');
mongoose.set('debug', true);

var testSchema = new mongoose.Schema({
    customIdentifier: String,
    tags: [String]
});

var TestModel = mongoose.model('test', testSchema);

var identifier = 'does-not-exist';

var update = {
    customIdentifier: identifier,
    tags: ['tag1', 'tag2']
};

TestModel.findOneAndUpdate({
    customIdentifier: identifier
}, update, {
    upsert: true,
    new: true,
    overwrite: true // works if you comment this out
}, function(err, model) {
    assert.equal(model.tags[0], 'tag1');
    assert.equal(model.tags[1], 'tag2');
    process.exit(0);
});
```
