### ISSUE TITLE
Regression in 4.11 - Range Error 

### ISSUE THREAD

**Issue by cdaniel** [Automattic/mongoose#5641]
My code worked in 4.9
```
[2017-09-13 09:20:37.714] [ERROR] workspace - RangeError: Maximum call stack size exceeded
    at EmbeddedDocument.Document.$toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2124:40)
    at EmbeddedDocument.Document.toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2337:15)
...........
at model.Document.$toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2172:13)
    at model.Document.toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2337:15)
    at clone (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:254:16)
    at cloneArray (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:362:14)
    at clone (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:247:12)
    at cloneObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:343:13)
    at clone (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:260:16)
    at model.Document.$toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2172:13)
    at model.Document.toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2337:15)
    at clone (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:254:16)
    at cloneObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:343:13)
    at clone (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:260:16)
    at model.Document.$toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2172:13)
    at model.Document.toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2337:15)
    at clone (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:254:16)
    at cloneArray (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:362:14)
    at clone (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:247:12)
    at cloneObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:343:13)
    at clone (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:260:16)
    at model.Document.$toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2172:13)
    at model.Document.toObject (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:2337:15)
    at deepEqual (/Users/kdaniel/atlas2/node_modules/mongoose/lib/utils.js:184:11)
    at model.Document.$__shouldModify (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:825:8)
    at model.Document.$__set (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:852:27)
    at model.Document.set (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:768:10)
    at model.set [as parentMap] (/Users/kdaniel/atlas2/node_modules/mongoose/lib/document.js:1983:25)
    at model._MapSchema.methods.formASubmap (/Users/kdaniel/atlas2/src-server/workspace/model/map-schema.js:525:43)
    at /Users/kdaniel/atlas2/src-server/workspace/workspace-router.js:410:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

The failing line was:
```
transferredNode.parentMap = submap;
```

After it was changed to:
```
transferredNode.parentMap = submap._id;
```

my code started working again.

**Comment by vkarpov15** [comment]
Can you please provide more detailed code samples, like schemas?

**Comment by cdaniel** [comment]
Ah, right, apologies. Not sure if this will be helpful, though.

Node:
```
var NodeSchema = new Schema({
        parentMap: {
            type: Schema.Types.ObjectId,
            ref: 'WardleyMap'
        },
        //... plenty of other fields, rather irrelevant
    });
```
WardleyMap
```   var _MapSchema = new Schema({
        nodes: [{
            type: Schema.Types.ObjectId,
            ref: 'Node'
        }],
        //... plenty of other fields, rather irrelevant
    });
```

The failing WardleyMap method is here https://github.com/cdaniel/atlas2/blob/master/src-server/workspace/model/map-schema.js#L434, and the failing point https://github.com/cdaniel/atlas2/blob/master/src-server/workspace/model/map-schema.js#L525. For some reason, Mongoose was not happy about resolved Map being assigned to the parentMap.

**Comment by varunjayaraman** [comment]
@cdaniel are you sure those highlighted lines are the correct ones? The first is an empty line and the 2nd is inside a `find` operation

**Comment by cdaniel** [comment]
Sorry, my code has changed:
The method https://github.com/cdaniel/atlas2/blob/master/src-server/workspace/model/map-schema.js#L564
The offensive line 
https://github.com/cdaniel/atlas2/blob/master/src-server/workspace/model/map-schema.js#L655
This is possibly related to https://github.com/Automattic/mongoose/issues/5619 and all changes that lead to it (especially those affecting how population in array works when some elements are populated and some are not).
Note the 'fix' - I store _id (unpopulated element) instead of populated one.

**Comment by varunjayaraman** [comment]
sorry, this is a lot of code to sift through, do you think you might be able to condense the problem down to what might be going on? is it that you cant store a populated document in a field that is a foreign reference in the schema?
