### ISSUE TITLE
Using Schema For Multiple Discriminated Embedded Arrays Throws Error

### ISSUE THREAD

**Issue by c1moore** [Automattic/mongoose#5684]
This is a **bug report**.  I am using Mongoose version **4.11.14**.

When using the same (sub)schema in multiple discriminated embedded arrays, I receive the following error:
```
Error: Discriminator "Child" cannot have field with name "__t"
    at discriminator (/home/c1moore/omninox/omnistack/node_modules/mongoose/lib/services/model/discriminator.js:33:11)
    at DocumentArray.discriminator (/home/c1moore/omninox/omnistack/node_modules/mongoose/lib/schema/documentarray.js:107:12)
    at Object.<anonymous> (/home/c1moore/omninox/omnistack/MultipleDiscriminatorTest.js:18:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
It seems Mongoose adds the `__t` field to the schema the first time the schema is used and throws the error on subsequent uses.  The below code is what threw the error (line 18, the one that threw the error, is the last line).

```javascript
'use strict';

const Schema = require('mongoose').Schema;

const ParentSchema = new Schema({});
const ChildSchema = new Schema({});

const FirstContainerSchema = new Schema({
  stuff:  [ParentSchema]
});

FirstContainerSchema.path('stuff').discriminator('Child', ChildSchema);

const SecondContainerSchema = new Schema({
  things: [ParentSchema]
});

SecondContainerSchema.path('things').discriminator('Child', ChildSchema);
```

**Comment by vkarpov15** [comment]
Thanks for the detailed repro script, we've confirmed the bug and will have a fix shortly :+1:
