### ISSUE TITLE
Issue with modifying single nested subdocument

### ISSUE THREAD

**Issue by asabhaney** [Automattic/mongoose#5693]
I would like to report what I believe to be a bug in mongoose `4.12.0`. It is related to the newly-added discriminator support for single nested documents that was added via https://github.com/Automattic/mongoose/commit/a072f8381941a0a8f040e7d94a1e44b5cea31aed (which by the way, thanks for adding!).

It seems using `.set` on a parent mongoose document to modify a subdocument causes an error to be thrown. I have written a test case to exemplify the issue:

```js
it('Single nested subdocs using discriminator can be modified', async () => {
   const eventSchema = new Schema(
      { message: String },
      { discriminatorKey: 'kind', _id: false }
   )

   const trackSchema = new Schema({
      event: eventSchema
   })

   trackSchema.path('event').discriminator('Clicked',
      new Schema({
         element: String
      }, { _id: false })
   )

   trackSchema.path('event').discriminator('Purchased',
      new Schema({
         product: String
      }, { _id: false })
   )

   const MyModel = mongoose.model('track', trackSchema)

   const doc = new MyModel({
      event: {
         message: 'Test',
         kind: 'Clicked',
         element: 'Amazon Link'
      }
   })

   await doc.save()
   assert.equal(doc.event.message, 'Test')
   assert.equal(doc.event.kind, 'Clicked')
   assert.equal(doc.event.element, 'Amazon Link')
   assert.ok(!doc.event.product)

   // ** THIS IS WHERE THE ISSUE IS **

   doc.set('event', {
      kind: 'Purchased',
      product: 'Professional AngularJS'
   })

   await doc.save()

   assert.equal(doc.event.kind, 'Purchased')
   assert.equal(doc.event.product, 'Professional AngularJS')
   assert.ok(!doc.event.element)
   assert.ok(!doc.event.message)
})
```

Here is the error stack trace that is logged when the `set` operation is attempted:

```
track validation failed: event: Cast to Embedded failed for value "{ kind: 'Purchased', product: 'Professional AngularJS' }" at path "event"
  ValidationError: 
      at ValidationError (node_modules/mongoose/lib/error/validation.js:28:11)
      at model.Document.invalidate (node_modules/mongoose/lib/document.js:1632:32)
      at model.Document.set (node_modules/mongoose/lib/document.js:768:10)
      at _callee$ (tests/unit/mongoosebug.js:46:11)
```

This brings up another question relating to what should happen if you had individual `set` operations rather than setting the subdocument all in one go, as was done in the test case above. For example, what would be the expected result of the following operation:

```js
doc.set('event.kind', 'Purchased')
doc.set('event.product', 'Professional AngularJS')
``` 

Or here's an example that reverses the order of the `set`s which might make it harder to anticipate what should happen:

```js
doc.set('event.product', 'Professional AngularJS')
doc.set('event.kind', 'Purchased')
``` 

I hope that's clear. Thanks again.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP :+1:
