### ISSUE TITLE
Updating schema that has runSettersOnQuery and pre update hook causes infinite recursion

### ISSUE THREAD

**Issue by ValYouW** [Automattic/mongoose#5702]
Hi,

The following script causes an error: "RangeError: Maximum call stack size exceeded".
NOTE that if I remove the pre findOneAndUpdate hook it works OK.

```js
var mongoose = require('mongoose'),
    uuid = require('uuid'),
    uuidParse = require('uuid-parse');

mongoose.Promise = Promise;

function toUUID(string) {
	if (!string) {return null;}
	if (Buffer.isBuffer(string) || Buffer.isBuffer(string.buffer)) { return string; }
	var buffer = uuidParse.parse(string);
	return new mongoose.Types.Buffer(buffer).toObject(0x04);
}

function fromUUID(buffer) {
    if (!buffer || buffer.length !== 16) { return null; }
    return uuidParse.unparse(buffer);
}

var UserSchema = new mongoose.Schema({
	name: String,
	lastUpdate: {type: Date},
	friends: [{
		_id: false,
		status: {type: String, required: true},
		id: {
			type: mongoose.Schema.Types.Buffer,
			get: fromUUID,
			set: toUUID,
			ref: 'User'
		}
	}]
}, { collection: 'users', runSettersOnQuery: true });

UserSchema.pre('findOneAndUpdate', function() {
	this.update({},{ $set: {lastUpdate: new Date()} });
});

var UserModel = mongoose.model('User', UserSchema);

var connStr = 'mongodb://test:test@127.0.0.1/test';
mongoose.connect(connStr);

var friendId = uuid.v4();
var user = { name: 'Sean', friends: [{status: 'New', id: friendId}] };
console.log('Inserting first user', user);
var dalUser = new UserModel(user);
dalUser.save().then(() => {
	console.log('User inserted successfully, updating frind status');
	var q = {_id: dalUser._id.toString(), 'friends.id': friendId};
	var upd = {'friends.$.status': 'Active'};
	UserModel.findOneAndUpdate(q, upd, {new: true}).lean().exec().then(res => {
		console.log('success:', res);
	}).catch(err => {
		console.log('ERR:', err)
	});

}).catch(console.error.bind(console));
```
Output:
```
Inserting first user { name: 'Sean',
  friends: [ { status: 'New', id: '1a4d4f8c-a73f-43ff-af91-74988ba2e178' } ] }
User inserted successfully, updating frind status
ERR: RangeError: Maximum call stack size exceeded
    at merge (C:\temp\mongoosebug\node_modules\mongoose\lib\utils.js:432:13)
    at merge (C:\temp\mongoosebug\node_modules\mongoose\lib\utils.js:435:9)
    at merge (C:\temp\mongoosebug\node_modules\mongoose\lib\utils.js:435:9)
    at merge (C:\temp\mongoosebug\node_modules\mongoose\lib\utils.js:435:9)
    ...
```

Mongoose: 4.12.1
Thx.

**Comment by vkarpov15** [comment]
This is a weird quirk that we'll fix, but I recommend you do this instead for your query middleware:

```javascript

UserSchema.pre('findOneAndUpdate', function() {
	this.findOneAndUpdate({},{ $set: {lastUpdate: new Date()} });
});
```

By doing `this.update()` in the middleware you're actually changing your `findOneAndUpdate()` to an `update()`, which I presume is not what you intend to do.

**Comment by ValYouW** [comment]
Thanks
