### ISSUE TITLE
RangeError when using discriminators on multiple connections

### ISSUE THREAD

**Issue by steckerl** [Automattic/mongoose#5721]
Hi,

since updating from 4.10 to 4.12 I am struggling with a "RangeError: Maximum call stack size exceeded".

Finally, I managed to reproduce this issue:

```javascript
var mongoose = require("mongoose");

mongoose.Promise = Promise;
Error.stackTraceLimit = Infinity;

var conA = mongoose.createConnection('mongodb://127.0.0.1/testA');

var schema = new mongoose.Schema({
  name: String
});

var schemaExt = new mongoose.Schema({
  nameExt: String
});

var modelA = conA.model("A", schema);
var modelAExt = modelA.discriminator("AExt", schemaExt);

modelA.findOneAndUpdate({name: "ABC"}, { $set: {name: "ABC"}}).exec().then(x => {
  var conB = mongoose.createConnection('mongodb://127.0.0.1/testB');

  var modelB = conB.model("A", schema.clone());
  var modelBExt = modelB.discriminator("AExt", schemaExt.clone());
}).catch(err => {
  console.log(err);
});
```

Output is:

    RangeError: Maximum call stack size exceeded
    at merge (/root/test/node_modules/mongoose/lib/utils.js:411:31)
    at merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    at merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    at merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    at merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    at merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    at merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    at merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    ...
    at merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    at Object.merge (/root/test/node_modules/mongoose/lib/utils.js:424:9)
    at merge (/root/test/node_modules/mongoose/lib/services/model/discriminator.js:65:11)
    at discriminator (/root/test/node_modules/mongoose/lib/services/model/discriminator.js:123:3)
    at Function.Model.discriminator (/root/test/node_modules/mongoose/lib/model.js:836:12)
    at modelA.findOneAndUpdate.exec.then.x (/root/test/con.js:23:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

Background: We are working on a multi tenant application, each tenant having its own db. The connection is opened on login. When creating all connections at startup there is no error.

I work around this issue now by creating all the schemas per tenant, but its still strange that a findAndUpdate on one connection influences modelling on another connection.

What I can tell, the error starts with mongoose@4.11.10

Thank you!

**Comment by vkarpov15** [comment]
Thanks for the detailed repro, will fix asap :+1:
