### ISSUE TITLE
insertMany throw "Cannot read property 'greaterThan' of undefined"

### ISSUE THREAD

**Issue by cekimy** [Automattic/mongoose#5722]
Use promise find data from Dynamodb, then insertMany(result) to Mongodb. There are 3416 rows, and throw error at 2000th row each time.
```
PRIMARY> db.taskactions.count()
1999
```
code:
```
function insert_action(data) {
    return ActionModel.insertMany(data.map(item => {
        delete item._id;
        return item;
    }));
}
```
trace:
```
/Users/coco/www/openplatform/node_modules/mongodb/lib/bulk/common.js:340
      } else if(opTimeTS.greaterThan(lastOpTS)) {
                        ^

TypeError: Cannot read property 'greaterThan' of undefined
    at mergeBatchResults (/Users/coco/www/openplatform/node_modules/mongodb/lib/bulk/common.js:340:25)
    at resultHandler (/Users/coco/www/openplatform/node_modules/mongodb/lib/bulk/ordered.js:413:23)
    at /Users/coco/www/openplatform/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:422:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
Is there a limit of insertMany?

node: v6.11.0
mongoose: v4.12.2
Mongo: v2.0.4

**Comment by cekimy** [comment]
Too much data. Should control flow by yourself
