### ISSUE TITLE
TypeError: this.__parentArray._markModified is not a function

### ISSUE THREAD

**Issue by florianbepunkt** [Automattic/mongoose#5736]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Manipulating docs with array of embedded subdocs produces the following error
```
TypeError: this.__parentArray._markModified is not a function
      at EmbeddedDocument.markModified (node_modules/mongoose/lib/types/embedded.js:89:24)
      at EmbeddedDocument.Document.$__set (node_modules/mongoose/lib/document.js:853:10)
      at EmbeddedDocument.Document.set (node_modules/mongoose/lib/document.js:778:10)
      at EmbeddedDocument.set [as vatPercent] (node_modules/mongoose/lib/services/document/compile.js:140:25)

```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
let parentDocs = Collection.find({}).populate('foobar');
      parentDocs.map((parent) => {
        // parent.childDocs is an array
        parent.childDocs.map((child) => {
          // child is an object
          child.name = parent.foobar.name;
        });
      })
```

**What is the expected behavior?**
No error should be there

**Please mention your node.js, mongoose and MongoDB version.**
MongoDB 3.49 Mongoose 4.12.4

**Comment by florianbepunkt** [comment]
Never mind: Introduced this error in my unit test by deep cloning the array of parentDocs before running the map function.
