### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by GamertodArk** [Automattic/mongoose#5761]
Node.js => v8.7.0
npm => 5.4.2
mongoose => ^4.12.4

I'm starting to learn about nodejs and mongoDB and of course mongoose. I have the next code 

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var posibles_valores = ['M','F'];

var email_match = [/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/, 'Coloca un email valido'];

var user_schema = new Schema({
	name : String,
	username: {Type: String, required: true, maxlength: [50, "Username muy grande"]},
	password : { Type: String, minlength: [8,'Password demasiado corto']},
	age : { Type: Number, min: [5,'La edad no puede ser menor que 5'], max: [100,'la edad no puede ser mayor que 100']},
	email : { Type :String, required : 'El correo es obligatorio', match: email_match},
	date_of_birth : Date,
	sexo : {Type: String, enum: {values: posibles_valores, message: 'Opcion no valida'}}
});

user_schema.virtual('password_confirmation').get(function () {
	return this.p_c;
}).set(function (password) {
	this.p_c = password;
});

mongoose.Promise = require('bluebird');
mongoose.connect('mongodb://localhost/fotos');

var User = mongoose.model("User",user_schema);

module.exports.User = User;
```

but every time i try to run it i get the next error 
```
C:\node\proyecto\node_modules\mongoose\lib\schema.js:663
    throw new TypeError('Undefined type `' + name + '` at `' + path +
    ^

TypeError: Undefined type `undefined` at `username.required`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (C:\node\proyecto\node_modules\mongoose\lib\schema.js:663:11)
    at Schema.path (C:\node\proyecto\node_modules\mongoose\lib\schema.js:519:29)
    at Schema.add (C:\node\proyecto\node_modules\mongoose\lib\schema.js:400:12)
    at Schema.add (C:\node\proyecto\node_modules\mongoose\lib\schema.js:389:14)
    at new Schema (C:\node\proyecto\node_modules\mongoose\lib\schema.js:104:10)
    at Object.<anonymous> (C:\node\proyecto\model\user.js:8:19)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\node\proyecto\index.js:3:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)

```

i don't know what's happening and i'm freaking out for this error... Please help..

**Comment by vkarpov15** [comment]
Lowercase 't' for type

`username: {Type: String, required: true, maxlength: [50, "Username muy grande"]}` -> `username: {type: String, required: true, maxlength: [50, "Username muy grande"]}`
