### ISSUE TITLE
arr[i].init is not a function

### ISSUE THREAD

**Issue by dkbhadeshiya** [Automattic/mongoose#5832]
I am facing a weird issue with Model.find(). Here is my schema:
```
const configSchema = new Schema({
  global: String,
  dbURL: String,
  dbUser: String
});
module.exports = mongoose.model('config', configSchema);
```

Now, When I try to call find Function: 
```
let Config = mongoose.model('config');
Config.find({}, (err,data) => {
    if (err) res.status(500).send(err);
    res.send(data);
  })
```

I am having following error: 
```
node_modules/mongoose/lib/query.js:1425
    arr[i].init(docs[i], opts, init);
           ^

TypeError: arr[i].init is not a function
    at completeMany (node_modules/mongoose/lib/query.js:1425:12)
    at Immediate.cb (node_modules/mongoose/lib/query.js:1290:13)
    at Immediate._onImmediate (node_modules/mquery/lib/utils.js:137:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
> Logs are trimmed for better readability

My environment setup is: 
```
NodeJS: v8.9.1
MongoDB: 3.4.10
Mongoose: 4.13.4
OS: MacOS 10.13.1
```

**Comment by vkarpov15** [comment]
What does the data you're loading look like?

**Comment by varunjayaraman** [comment]
yeah we're going to need a more dcomplete repro script, including more details on the data you have. Here's a barebones repro script where I used your schema, no errors for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5832`;


exec()
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    yield mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`, { useMongoClient: true });
    const configSchema = new mongoose.Schema({
      global: String,
      dbURL: String,
      dbUser: String
    });

    const Config = mongoose.model('config', configSchema);

    Config.find({}, (err, data) => {
      if (err) {
        console.error(`Error: ${ error }\n${ error.stack }`);
        return process.exit(1);
      }
      
      console.log('no error in find, exiting successful program');
      process.exit(0);
    })
  });
}
```

**Comment by dkbhadeshiya** [comment]
Hi Guys, 
Recently I have been able to fix this issue. It was not the mongoose issue, it was problem with something else. It's been resolved now. 
Thanks.
