### ISSUE TITLE
Error: failed to connect to [localhost:27017]

### ISSUE THREAD

**Issue by Ahmedsaber9** [Automattic/mongoose#5883]
**bug*?**

**What is the current behavior?**
i type : npm start at my code dir   
**If the current behavior is a bug, please provide the steps to reproduce.**
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle passport-mongo@0.0.1~prestart: passport-mongo@0.0.1
6 silly lifecycle passport-mongo@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle passport-mongo@0.0.1~start: passport-mongo@0.0.1
8 verbose lifecycle passport-mongo@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle passport-mongo@0.0.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ahmad/Desktop/DashBord3/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle passport-mongo@0.0.1~start: CWD: /home/ahmad/Desktop/DashBord3
11 silly lifecycle passport-mongo@0.0.1~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle passport-mongo@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle passport-mongo@0.0.1~start: Failed to exec start script
14 verbose stack Error: passport-mongo@0.0.1 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid passport-mongo@0.0.1
16 verbose cwd /home/ahmad/Desktop/DashBord3
17 error Linux 4.4.0-89-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error passport-mongo@0.0.1 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the passport-mongo@0.0.1 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the passport-mongo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs passport-mongo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls passport-mongo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`> passport-mongo@0.0.1 start /home/ahmad/Desktop/DashBord3
> node ./bin/www
---------------------------
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: failed to connect to [localhost:27017]
    at .<anonymous> (/home/ahmad/Desktop/DashBord3/node_modules/mongodb/lib/mongodb/connection/server.js:555:25)
    at emitThree (events.js:116:13)
    at emit (events.js:194:7)
    at .<anonymous> (/home/ahmad/Desktop/DashBord3/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/home/ahmad/Desktop/DashBord3/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
`
`ahmad@indra-PC:~$ mongo
MongoDB shell version: 3.0.15
connecting to: test
2017-12-08T12:59:44.636+0200 W NETWORK  Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: errno:111 Connection refused
2017-12-08T12:59:44.638+0200 E QUERY    Error: couldn't connect to server 127.0.0.1:27017 (127.0.0.1), connection attempt failed
    at connect (src/mongo/shell/mongo.js:179:14)
    at (connect):1:6 at src/mongo/shell/mongo.js:179
exception: connect failed
-----------------------
ip table 

`ahmad@indra-PC:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  localhost.localdomain  anywhere             tcp dpt:27017 state NEW,ESTABLISHED

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             localhost.localdomain  tcp spt:27017 state ESTABLISHED

**Please mention your node.js : npm@3.10.10 , 
mongoose :  passport-mongo@0.0.1 /home/ahmad/Desktop/DashBord3
└── mongoose@3.8.23  invalid
npm ERR! invalid: mongoose@3.8.23 /home/ahmad/Desktop/DashBord3/node_modules/mongoose

MongoDB version. : db version v3.0.15
git version: b8ff507269c382bc100fc52f75f48d54cd42ec3b
**

**Comment by maaz7sky** [comment]
try 127.0.0.1 instead of localhost in your connection string.
i.e.  "mongodb://127.0.0.1:27017/database_name"

**Comment by Ahmedsaber9** [comment]
not help

**Comment by Ahmedsaber9** [comment]
'url' : 'mongodb://127.0.0.1:27017/test'

**Comment by Ahmedsaber9** [comment]
tail -n200 /var/log/mongodb/mongodb.log
 i have no space 
`Sat Dec  9 17:13:47.780 [initandlisten] ERROR: Insufficient free space for journal files
Sat Dec  9 17:13:47.780 [initandlisten] Please make at least 3379MB available in /var/lib/mongodb/journal or use --smallfiles
`
run this :+1: 
mongod --dbpath /data/db --smallfiles 

worked,,so i should use small file argument

**Comment by VeoGarg** [comment]
I am getting this error... Please help me solve this...

**WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
    at handleUseMongoClient (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongoose\lib\connection.js:506:17)
    at NativeConnection.Connection.openUri (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongoose\lib\connection.js:407:7)
    at Mongoose.connect (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongoose\lib\index.js:208:15)
    at Server.app.listen (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\index.js:24:23)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1394:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Database connection Error
{ MongoError: Authentication failed.
    at C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\pool.js:598:61
    at authenticateStragglers (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\pool.js:516:16)
    at Connection.messageHandler (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\pool.js:552:5)
    at emitMessageHandler (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\connection.js:309:10)
    at Socket.<anonymous> (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed' }
(node:7372) UnhandledPromiseRejectionWarning: MongoError: Authentication failed.
    at C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\pool.js:598:61
    at authenticateStragglers (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\pool.js:516:16)
    at Connection.messageHandler (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\pool.js:552:5)
    at emitMessageHandler (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\connection.js:309:10)
    at Socket.<anonymous> (C:\Users\Vikas Garg\Desktop\Edwisor\8 Node JS & Rest APIs\1 Basic Rest API using Express & Mongo DB\Practise\BasicNodeJS\node_modules\mongodb-core\lib\connection\connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
(node:7372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

**Comment by lineus** [comment]
@Ahmedsaber9 can you please include details about the server you are connecting to and the connection options and string you are passing into `mongoose.connect()`?

**Comment by VeoGarg** [comment]
Here is the Code:

app.listen(appconfig.port, () => {
    console.log(`Example app listening on port ${appconfig.port}!`);
    //creating the mongoDB connection here
    let db = mongoose.connect(appconfig.db.uri, { useMongoClient: true });
})

and uri is --- uri: 'mongodb://test:test@127.0.0.1:27017/blogAppDB'

I have already created blogAppDB database

**Comment by lineus** [comment]
@Ahmedsaber9 Have you enabled auth on the server and added the user:password combo that you are attempting to connect with? FYI, you can join us on https://gitter.im/Automattic/mongoose or https://mongoosejsteam.slack.com to get help in real time as well.

**Comment by VeoGarg** [comment]
No, I haven't enabled auth on the server. Actually, I am new to Mongo DB and don't know the concepts clearly.

**Comment by lineus** [comment]
@Ahmedsaber9 you can either 
   1. **remove the user:password@ from your connection string** or
   1. **follow the instructions [here](https://docs.mongodb.com/manual/tutorial/enable-authentication/index.html) from the mongodb docs to enable auth and add a user.**

**Comment by VeoGarg** [comment]
Okay, Thanks Sir

**Comment by vkarpov15** [comment]
Also @VeoGarg remove the `useMongoClient` option from your options, the `useMongoClient` bit in `mongoose.connect(appconfig.db.uri, { useMongoClient: true });` is no longer necessary in mongoose 5.x, so we added a warning to inform people to get rid of it once they've fully upgraded
