### ISSUE TITLE
mongoose / mongodb-core library bug with async - Error: Callback was already called

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5920]
I saw this on my server upon startup (has to do with index creation - when an index fails to be created when there is a duplicate):

```
    CDT server has captured an "uncaughtException" => 
     Error: Callback was already called.
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:955:32
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:4046:16
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:996:19
        at done (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:1033:17)
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:1072:16
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/utils.js:526:16
        at handleCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/lib/utils.js:120:56)
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/lib/db.js:1082:14
        at handleCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/lib/utils.js:120:56)
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/lib/db.js:1669:20
        at handleCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/lib/utils.js:120:56)
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/lib/db.js:314:20
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:469:18
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

looks like something to do with either mongoose or mongodb-core, not sure, please tell your people :)

**Comment by vkarpov15** [comment]
Interesting, any way you can provide some code samples that reproduce this? Also, can you clarify your mongoose version? Its hard to map line numbers to code if I don't know the version...
