### ISSUE TITLE
SendGrid failing due to "Unhandled promise rejection"

### ISSUE THREAD

**Issue by tylerclark** [Automattic/mongoose#5946]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I cannot send an email using [sendgrid-nodejs](https://github.com/sendgrid/sendgrid-nodejs)
```
(node:4862) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
(node:4862) UnhandledPromiseRejectionWarning: Error: Unauthorized
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:4862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4862) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Offending line: https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/client.js#L124

**What is the expected behavior?**
Previous to upgrading mongoose, I was able to send an email

**Please mention your node.js, mongoose and MongoDB version.**
node.js v9.3.0
mongoose 4.13.8
mongodb v3.6.1
sendgrid 6.1.4

**Comment by tylerclark** [comment]
This turned out to be more of an issue with my node situation and nothing to do with mongoose. I was just confused because of all the mongoose console outputs.

I guess "reading between the lines" you can see the `Error: Unauthorized`. For whatever reason, the `process.env.SENDGRID_API_KEY` line does not work for me. When I put the actual key in that line `sgMail.setApiKey(_MYKEY_);` it started working.

Sorry for the false alarm.
