### ISSUE TITLE
Saving a document with a schema option of `safe: false` always fails

### ISSUE THREAD

**Issue by jakesjews** [Automattic/mongoose#6012]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Saving a document with a schema option of `safe: false` always fails with the error `DocumentNotFoundError: No document found for query "undefined"`

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const mongoose = require('mongoose');
Schema = mongoose.Schema

const CatSchema = new Schema({
  name: String
}, { safe: false })

mongoose.connect('mongodb://localhost/test');

const Cat = mongoose.model('Cat', CatSchema);

const kitty = new Cat({ name: 'Zildjian' });
kitty.save().then(() => console.log('meow'));
```

**What is the expected behavior?**
The save should not throw an error.

**Please mention your node.js, mongoose and MongoDB version.**
Node 9.4.0, Mongoose 5.0.0, MongoDB 3.6.2

**Comment by vkarpov15** [comment]
Thanks for identifying this bug, fix will be in 5.0.1 :+1:

**Comment by reduxdj** [comment]
We're having the opposite error now, saving a document doesn't work, but documents are saving, switching safe to false we get a result, but depending on that seems bad
MongoDB 3.6.3 - ReplicaSet
Mongoose 5.0.14
and node 8.5

{ DocumentNotFoundError: No document found for query "undefined"
    at DocumentNotFoundError (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongoose/lib/error/notFound.js:31:11)
    at $__handleSave (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongoose/lib/model.js:279:17)
    at /Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongoose/lib/model.js:170:7
    at result (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:414:17)
    at session.endSession (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:400:37)
    at ClientSession.endSession (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb-core/lib/sessions.js:72:41)
    at executeCallback (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:397:17)
    at /Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/collection.js:659:5
    at result (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/bulk/unordered.js:560:16
    at handleCallback (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:128:55)
    at resultHandler (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/bulk/unordered.js:456:5)
    at handler (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb-core/lib/topologies/replset.js:1209:22)
    at /Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb-core/lib/connection/pool.js:544:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  message: 'No document found for query "undefined"',
  name: 'DocumentNotFoundError',
  query: undefined }

**Comment by vkarpov15** [comment]
@reduxdj I'd recommend just getting rid of the `safe` option, that option is a remnant of the pre-2012 era when mongodb did unacknowledged writes by default and isn't really useful these days
