### ISSUE TITLE
mongoose 4.13.10/5.0.2 breaks certain discriminator functionality

### ISSUE THREAD

**Issue by asabhaney** [Automattic/mongoose#6064]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

After upgrading to `4.13.10` from `4.13.9`, my script began to crash. The issue seems to be when there are 2 or more discriminators that share the same parent path. I have included a script below to recreate the issue (based off the test case from #5970), as well as the ensuing stack trace.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
var assert = require('chai').assert
var mongoose = require('mongoose')
var Schema = require('mongoose/lib/schema');
var getSchemaTypes = require('mongoose/lib/services/populate/getSchemaTypes');

describe('getSchemaTypes', function() {
  it('handles embedded discriminators (gh-5970)', function(done) {
    var ItemSchema = new Schema({
      title: {
        type: String,
        required: true
      }
    }, {discriminatorKey: 'type'});

    var ItemBookSchema = new Schema({
      author: {
        type: String,
        ref: 'Ref1'
      }
    });

    var ItemEBookSchema = new Schema({
      author: {
        type: String,
        ref: 'Ref2'
      }
    });

    var OtherItem = new Schema({ name: String });

    var BundleSchema = new Schema({
      level1: {
         items: [{
           type: ItemSchema,
           required: false
         }]
      },
      level2: {
         items: [{
           type: ItemSchema,
           required: false
         }]
      }
    });

    BundleSchema.path('level1.items').discriminator('Book', ItemBookSchema);
    BundleSchema.path('level1.items').discriminator('EBook', ItemEBookSchema);
    BundleSchema.path('level1.items').discriminator('Other', OtherItem);
   
    // HERE IS THE ADDED DISCRIMINATOR PATH
    BundleSchema.path('level2.items').discriminator('Book', ItemBookSchema);
    BundleSchema.path('level2.items').discriminator('EBook', ItemEBookSchema);
    BundleSchema.path('level2.items').discriminator('Other', OtherItem);

    var doc = {
      level1: {
         items: [
           { type: 'Book', author: 'level 1 test 1' },
           { type: 'EBook', author: 'level 1 test 2' }
         ]
      },
      level2: {
         items: [
           { type: 'EBook', author: 'level 2 test 1' },
           { type: 'Book', author: 'level 2 test 2' },
           { type: 'Other' }
         ]
      }
    }
    var schemaTypes = getSchemaTypes(BundleSchema, doc, 'level2.items.author');

    assert.ok(Array.isArray(schemaTypes));
    // Make sure we only got the schema paths for Book and EBook, and none
    // for the 'Other'
    assert.equal(schemaTypes.length, 2);
    assert.equal(schemaTypes[0].options.ref, 'Ref1');
    assert.equal(schemaTypes[1].options.ref, 'Ref2');

    done();
  });
});
```

Here is the resulting error stack trace:

```
 1) getSchemaTypes handles embedded discriminators (gh-5970):
     RangeError: Maximum call stack size exceeded
      at merge (node_modules/mongoose/lib/utils.js:411:31)
      at merge (node_modules/mongoose/lib/utils.js:424:9)
      at merge (node_modules/mongoose/lib/utils.js:424:9)
      at merge (node_modules/mongoose/lib/utils.js:424:9)
      at merge (node_modules/mongoose/lib/utils.js:424:9)
      ...
      at merge (node_modules/mongoose/lib/utils.js:424:9)
      at merge (node_modules/mongoose/lib/utils.js:424:9)
      at Object.merge (node_modules/mongoose/lib/utils.js:424:9)
      at merge (node_modules/mongoose/lib/services/model/discriminator.js:65:11)
      at discriminator (node_modules/mongoose/lib/services/model/discriminator.js:123:3)
      at DocumentArray.discriminator (node_modules/mongoose/lib/schema/documentarray.js:111:12)
```
**Please mention your node.js, mongoose and MongoDB version.**

node 8.9.4, mongoose 4.13.10, mongo 3.4.10

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap :+1:

**Comment by vkarpov15** [comment]
As a workaround, `clone()` the schema before passing it into `discriminator()`

```javascript
    // HERE IS THE ADDED DISCRIMINATOR PATH
    BundleSchema.path('level2.items').discriminator('Book', ItemBookSchema.clone());
    BundleSchema.path('level2.items').discriminator('EBook', ItemEBookSchema.clone());
    BundleSchema.path('level2.items').discriminator('Other', OtherItem.clone());
```

**Comment by asabhaney** [comment]
Thanks @vkarpov15. That's what I was doing as a workaround, but ran in to an issue with cloning which have just filed here: https://github.com/Automattic/mongoose/issues/6133

Thanks for the quick fix!
