### ISSUE TITLE
Mongoose doesn't return a VersionError when saving

### ISSUE THREAD

**Issue by zpatterson614** [Automattic/mongoose#6112]
**Do you want to request a *feature* or report a *bug*?**
Bug 🐛

**What is the current behavior?**
Mongoose will save a document with an old version number when it should return a VersionError

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');

let TestSchema = mongoose.Schema({
  foo: String,
  bar: Number,
  baz: Array
});

let TestModel = mongoose.model('test', TestSchema);

mongoose.connect('mongodb://localhost/test', (response) => {
  // console.log('response', response);
  let test = new TestModel({
    foo: 'oof',
    bar: 42,
    baz: []
  });

  test.save((err, original_v0) => {
    console.log('original_v0', original_v0);

    TestModel.findOne({ _id: original_v0._id }, (err, copy_v0) => {
      console.log('copy_v0', copy_v0);

      original_v0.baz.push('it');
      delete original_v0.__v;
      original_v0.save((err, original_v1) => {
        console.log('original_v1', original_v1); // .baz === ['it']

        copy_v0.baz.push('real');
        delete copy_v0.__v;
        copy_v0.save((err, copy_v1) => {
          // err.name should be VersionError

          console.log('err', err); // Undefined
          console.log('copy_v1', copy_v1); // .bar === ['real']
          TestModel.deleteMany({}, () => {
            mongoose.connection.close();
          });
        })
      });
    });
  });
});
```
**What is the expected behavior?**
Mongoose should return a VersionError

**Please mention your node.js, mongoose and MongoDB version.**
node.js v6.10.3
mongoose 4.13.11
mongo
```
MongoDB shell version v3.4.4
git version: 888390515874a9debd1b6c5d36559ca86b44babd
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

**Comment by lineus** [comment]
I modified your example slightly:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('./lib/mdb')

let TestSchema = mongoose.Schema({
  foo: String,
  bar: Number,
  baz: Array
})

let TestModel = mongoose.model('test', TestSchema)

mongoose.connect('mongodb://localhost:27020/test', (response) => {
  let test = new TestModel({
    foo: 'oof',
    bar: 42,
    baz: []
  })

  test.save((err, original_v0) => {
    console.log('original_v0', original_v0)

    TestModel.findOne({ _id: original_v0._id }, (err, copy_v0) => {
      console.log('copy_v0', copy_v0)

      original_v0.baz.push('it')
      delete original_v0.__v
      original_v0.save((err, original_v1) => {
        console.log('original_v1', original_v1)

        copy_v0.baz.push('real')
        delete copy_v0.__v
        copy_v0.save((err, copy_v1) => {
          console.log('err', err)
          console.log('copy_v1', copy_v1)
          TestModel.find({}, (err, final) => {
            console.log('err', err)
            console.log('final', final)
            mongoose.connection.close()
          })
        })
      })
    })
  })
})
```
here is the output:
```
original_v0 { baz: [],
  _id: 5a7d8d5cd892377f570657b2,
  foo: 'oof',
  bar: 42,
  __v: 0 }
copy_v0 { baz: [],
  _id: 5a7d8d5cd892377f570657b2,
  foo: 'oof',
  bar: 42,
  __v: 0 }
original_v1 { baz: [ 'it' ],
  _id: 5a7d8d5cd892377f570657b2,
  foo: 'oof',
  bar: 42,
  __v: 1 }
err null
copy_v1 { baz: [ 'real' ],
  _id: 5a7d8d5cd892377f570657b2,
  foo: 'oof',
  bar: 42,
  __v: 1 }
err null
final [ { baz: [ 'it', 'real' ],
    _id: 5a7d8c4dccb52a7f235e800a,
    foo: 'oof',
    bar: 42,
    __v: 2 },
  { baz: [ 'it', 'real' ],
    _id: 5a7d8d5cd892377f570657b2,
    foo: 'oof',
    bar: 42,
    __v: 2 } ]
```
it seems like its updating the version to 2. @zpatterson614 I'm pretty new to all of this, can you elaborate on why you think it should throw a VersionError?

**Comment by ricjd** [comment]
@lineus I thought if you pushed on to an array with an old version of the document, then go to save the old document, you would get a VersionError?

**Comment by zpatterson614** [comment]
Here's an [explanation of why versioning was added to Mongoose](http://aaronheckmann.tumblr.com/post/48943525537/mongoose-v3-part-1-versioning). In summary, Mongoose access arrays within documents by index when using .save. If the array has changed since the last time the document was queried, Mongoose could be updating the wrong element in the array. It seems Mongoose determines if any actions performed on the doc could cause it to access the wrong element and only then throws an error. Example 2 triggers the error.

However, I would expect Mongoose to throw a VersionError because the script is trying to save an out of date document. This is a simplified example, but imagine two separate processes are modifying the same document. Example 1 shows when I would expect Mongoose throw an error instead of updating the document. Adding something that looks like version control, but is only version control in very specific instances is confusing.

Finally this behavior is different than what I would expect from Mongo. With Mongo, I would expect a last-in-wins. If Mongoose is using versioning, then I would expect a VersionError. If Mongoose is following Mongo, I would expect `final.baz` in the previous post to equal `['real']`. The mongo-like last-in-wins example would be the behavior I think would be the best solution to this edge case.

**Example 1**
```
'use strict';

const mongoose = require('mongoose');

let TestSchema = mongoose.Schema({
  foo: String,
  bar: Number,
  baz: Array
});

let TestModel = mongoose.model('test', TestSchema);

mongoose.connect('mongodb://localhost/test', (response) => {
  // console.log('response', response);
  let test = new TestModel({
    foo: 'oof',
    bar: 42,
    baz: []
  });

  test.save((err, original_v0) => {
    console.log('original_v0', original_v0);

    TestModel.findOne({ _id: original_v0._id }, (err, copy_v0) => {
      console.log('copy_v0', copy_v0);

      if (original_v0.baz.indexOf('exactlyOne') === -1){
        original_v0.baz.push('exactlyOne');
      }
      delete original_v0.__v;
      original_v0.save((err, original_v1) => {
        console.log('original_v1', original_v1); // .baz === ['exactlyOne']

        if (copy_v0.baz.indexOf('exactlyOne') === -1) {
          copy_v0.baz.push('exactlyOne');
          copy_v0.baz.push('exactlyOne');
          copy_v0.baz.pop();
        }
        delete copy_v0.__v;
        copy_v0.save((err, copy_v1) => {
          // err.name should be VersionError

          console.log('err', err); // Undefined
          console.log('copy_v1', copy_v1); // .baz === ['exactlyOne']
          TestModel.find({}, (err, final) => {
            console.log('final', final); // .baz === ['exactlyOne', 'exactlyOne']
            TestModel.deleteMany({}, () => {
              mongoose.connection.close();
            });
          })
        })
      });
    });
  });
});
```
The output
```
original_v0 { __v: 0,
  foo: 'oof',
  bar: 42,
  _id: 5a7dbdd7ba6fa10d9956b5b6,
  baz: [] }
copy_v0 { _id: 5a7dbdd7ba6fa10d9956b5b6,
  foo: 'oof',
  bar: 42,
  __v: 0,
  baz: [] }
original_v1 { __v: 1,
  foo: 'oof',
  bar: 42,
  _id: 5a7dbdd7ba6fa10d9956b5b6,
  baz: [ 'exactlyOne' ] }
err { Error
    at model.wrappedPointCut [as save] (/Users/zacharypatterson/test/mongoose-version-error/node_modules/mongoose/lib/services/model/applyHooks.js:131:29)
    at original_v0.save (/Users/zacharypatterson/test/mongoose-version-error/index2.js:40:17)
    at /Users/zacharypatterson/test/mongoose-version-error/node_modules/mongoose/lib/model.js:4074:16
    at /Users/zacharypatterson/test/mongoose-version-error/node_modules/mongoose/lib/services/model/applyHooks.js:170:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'No matching document found for id "5a7dbdd7ba6fa10d9956b5b6"',
  name: 'VersionError' }
copy_v1 undefined
final [ { _id: 5a7dbdd7ba6fa10d9956b5b6,
    foo: 'oof',
    bar: 42,
    __v: 1,
    baz: [ 'exactlyOne' ] } ]
```

**Example 2**
```
'use strict';

const mongoose = require('mongoose');

let TestSchema = mongoose.Schema({
  foo: String,
  bar: Number,
  baz: Array
});

let TestModel = mongoose.model('test', TestSchema);

mongoose.connect('mongodb://localhost/test', (response) => {
  // console.log('response', response);
  let test = new TestModel({
    foo: 'oof',
    bar: 42,
    baz: []
  });

  test.save((err, original_v0) => {
    console.log('original_v0', original_v0);

    TestModel.findOne({ _id: original_v0._id }, (err, copy_v0) => {
      console.log('copy_v0', copy_v0);

      if (original_v0.baz.indexOf('exactlyOne') === -1){
        original_v0.baz.push('exactlyOne');
      }
      delete original_v0.__v;
      original_v0.save((err, original_v1) => {
        console.log('original_v1', original_v1); // .baz === ['exactlyOne']

        if (copy_v0.baz.indexOf('exactlyOne') === -1) {
          copy_v0.baz.push('exactlyOne');
        }
        delete copy_v0.__v;
        copy_v0.save((err, copy_v1) => {
          // err.name should be VersionError

          console.log('err', err); // Undefined
          console.log('copy_v1', copy_v1); // .baz === ['exactlyOne']
          TestModel.find({}, (err, final) => {
            console.log('final', final); // .baz === ['exactlyOne', 'exactlyOne']
            TestModel.deleteMany({}, () => {
              mongoose.connection.close();
            });
          })
        })
      });
    });
  });
});
```

The output
```
original_v0 { __v: 0,
  foo: 'oof',
  bar: 42,
  _id: 5a7db40b281c49079a1824ef,
  baz: [] }
copy_v0 { _id: 5a7db40b281c49079a1824ef,
  foo: 'oof',
  bar: 42,
  __v: 0,
  baz: [] }
original_v1 { __v: 1,
  foo: 'oof',
  bar: 42,
  _id: 5a7db40b281c49079a1824ef,
  baz: [ 'exactlyOne' ] }
err null
copy_v1 { _id: 5a7db40b281c49079a1824ef,
  foo: 'oof',
  bar: 42,
  __v: 1,
  baz: [ 'exactlyOne' ] }
final [ { _id: 5a7db40b281c49079a1824ef,
    foo: 'oof',
    bar: 42,
    __v: 2,
    baz: [ 'exactlyOne', 'exactlyOne' ] } ]
```

**Comment by lineus** [comment]
@zpatterson614 thanks for taking the time to write such a thorough explanation!

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap :+1:

**Comment by vkarpov15** [comment]
This is by design, mongoose allows multiple `push()` calls without version conflicts because `push()` gets translated to [`$push` on the mongodb side](https://docs.mongodb.com/manual/reference/operator/update/push/), which doesn't overwrite previous `$push` operations. Versioning is specifically to prevent issues where deleting element i of an array conflicts with a previous operation that affected the length of an array.
