### ISSUE TITLE
TypeError: Cannot create property '_isAMomentObject' on number '1518982633564'

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#6150]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Getting these kind of errors after upgrading to 5.0.0, originating from mongoose utils:

```
TypeError: Cannot create property '_isAMomentObject' on number '1518982633564'
    at Object.exports.mergeClone (node_modules/mongoose/lib/utils.js:751:15)
    at Object.exports.mergeClone (node_modules/mongoose/lib/utils.js:773:17)
    at Object.exports.mergeClone (node_modules/mongoose/lib/utils.js:773:17)
    at model.Query.Query._mergeUpdate (node_modules/mongoose/lib/query.js:2436:11)
    at _update (node_modules/mquery/lib/mquery.js:2260:11)
    at model.Query.update (node_modules/mquery/lib/mquery.js:2070:10)
    at _update (node_modules/mongoose/lib/query.js:2914:25)
    at model.Query.Query.update (node_modules/mongoose/lib/query.js:2702:10)
    at _update (node_modules/mongoose/lib/model.js:2624:16)
    at Function.update (node_modules/mongoose/lib/model.js:2528:10)
    at Function.TransactionSchema.statics.payWithCredit (app/components/transaction/transaction.model.js:194:8)
    at <anonymous>
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Still trying to work out what is causing this

**What is the expected behavior?**
I assume a unix timestamp is being passed somewhere and it looks like Mongoose is treating it as a moment object. Expected behaviour is for no error to trigger.

**Please mention your node.js, mongoose and MongoDB version.**
Node 8.9.4
Mongoose 5.0.3
MongoDB 3.4.7

After updating to Mongoose 5.0.6 this appears to have been fixed, but wanted to report it anyway in case someone else runs into it.

**Comment by xjylyh** [comment]
I have the same problem with you. I want to ask your solution.

**Comment by adamreisnz** [comment]
What mongoose version are you using? It appears to have been fixed for me with Mongoose > 5.0.6

**Comment by xjylyh** [comment]
Yes, I also use Mongoose 5.0.3. I have upgraded to 5.0.6. Waiting for the deployment test, thank you for your suggestion.

**Comment by xjylyh** [comment]
Yes, I also use Mongoose 5.0.3. I have upgraded to 5.0.6. Waiting for the deployment test, thank you for your guidance.

**Comment by vkarpov15** [comment]
@xjylyh please open up a separate issue with code samples if the issue persists.
