### ISSUE TITLE
Mongoose swallowing up exceptions / errors

### ISSUE THREAD

**Issue by natanavra** [Automattic/mongoose#6178]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Mongoose swallows exceptions/errors when used inside asyncjs functions.

**If the current behavior is a bug, please provide the steps to reproduce.**
Consider the following code:
```js
async.waterfall([
    (cb) => {
        let obj = new MyModel({name: 'model'});
        obj.save(cb);
    },
    (model, cb2) => {
        MyModel.find({name: 'model'}, (err, models) => {
            cb2(err, models, model);
        });
    },
    (models, model, cb) => {
        let type = model.settings.type;
        cb(null, type);
    }

], callback);
```
A TypeError should occur on `model.settings.type`, something like `Cannot read property 'type' of undefined` instead the code execution is stuck.
On some execution jumps back to `cb2` and tries to invoke it again (which asyncjs throws an Error for calling the `cb2` twice).

Replacing `MyModel.find` with a simple `cb2(null, {}, {})` would throw an error just fine.

**NOTE** I tested it with promises syntax as well, using `find, then, catch`.

**What is the expected behavior?**
Errors, including Runtime errors should be thrown and handled by the application process.

**Please mention your node.js, mongoose and MongoDB version.**
- Mongoose v5.0.7
- MongoDB v3.4.0
- Node v6.9.2

**Comment by lineus** [comment]
@natanavra can you please include a complete example that demonstrates the problem you are seeing? Given the way that async.waterfall handles errors seeing your main callback at the very least is imperative. Feel free to share a promise based example instead.

**Comment by vkarpov15** [comment]
@natanavra also please post your schema. If `settings.type` is in your schema, `doc.settings.type` will not throw an exception because mongoose creates `.settings` implicitly for change tracking.

**Comment by bgSosh** [comment]
We've also noticed differences in error handing between mongoose v4 vs v5.

Please take a look at [this gist.](https://gist.github.com/bgSosh/34055ba6ce4285eda59cfdd43a53b044)

Executing in v4: the exception is thrown as expected.

Executing in v5: the exception is somehow caught, and returned in the callback on line 20.

**Comment by natanavra** [comment]
@lineus Note that you're producing a Mongoose error, I wanted to produce a TypeError that occurs after invoking a method from inside a mongoose `save` callback inside async.
@vkarpov15 The schema is identical to the model created, `Schema({name: {type: String}})`

Copy my code and you should see the behaviour I'm describing.

**Comment by lineus** [comment]
### here is a complete example that demonstrates what @natanavra is seeing:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('./lib/test_db')
const Schema = mongoose.Schema
const async = require('async')

const testSchema = new Schema({
  name: String
})

const Test = mongoose.model('test', testSchema)

const test = new Test({
  name: 'franz ferdinand'
})

const test2 = new Test({
  name: 'afghan whigs'
})

test.save(function (err, doc) {
  if (err) { return console.error(err) }
  try { // putting this in a try to continue execution
    let x = doc.someproperty.thatdoesntexist
    console.log('never going to see', x)
  } catch (e) {
    console.error('before waterfall:', e.message)

    async.waterfall([
      function one (cb1) {
        console.log('in callback 1')
        test2.save(function (err, saved) {
          if (err) { return cb1(err, 'cb1') }
          cb1(null, saved)
        })
      },
      function two (doc, cb2) {
        console.log('in callback 2')
        Test.find({ name: doc.name }, function (err, found) {
          if (err) { return cb2(err, 'cb2') }
          cb2(null, found)
        })
      },
      function three (arr, cb3) {
        console.log('in callback 3')
        let x = arr[0].someproperty.thatalsodoesntexist
        return cb3(null, 'found:' + x)
      }
    ], function waterfallCallBack (err, result) {
      if (err) { return console.error(err) }
      return console.log(result)
    })
  }
})
```
### output:
```
InspiredMacPro:mongoose5 lineus$ ./6178_3.js
before waterfall: Cannot read property 'thatdoesntexist' of undefined
in callback 1
in callback 2
in callback 3
^C // hangs here.
InspiredMacPro:mongoose5 lineus$ 
```
### As far as I can tell, the only way around this at the moment is to change:
```
      function three (arr, cb3) {
        console.log('in callback 3')
        try {
          let x = arr[0].someproperty.thatalsodoesntexist
          return cb3(null, 'found:' + x)
        } catch (e) {
          return cb3(e)
        }
      }
```
### output after change:
```
InspiredMacPro:mongoose5 lineus$ ./6178_3.js
before waterfall: Cannot read property 'thatdoesntexist' of undefined
in callback 1
in callback 2
in callback 3
TypeError: Cannot read property 'thatalsodoesntexist' of undefined
    at three (/Users/lineus/dev/Help/mongoose5/6178_3.js:48:39)
    at nextTask (/Users/lineus/dev/Help/mongoose5/node_modules/async/dist/async.js:5070:14)
    at /Users/lineus/dev/Help/mongoose5/node_modules/async/dist/async.js:5064:13
    at apply (/Users/lineus/dev/Help/mongoose5/node_modules/async/dist/async.js:21:25)
    at /Users/lineus/dev/Help/mongoose5/node_modules/async/dist/async.js:56:12
    at /Users/lineus/dev/Help/mongoose5/node_modules/async/dist/async.js:840:16
    at /Users/lineus/dev/Help/mongoose5/6178_3.js:42:11
    at /Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/model.js:3928:16
    at init (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/query.js:1452:16)
    at model.Document.init (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/document.js:370:5)
    at completeMany (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/query.js:1457:14)
    at cb (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/query.js:1316:11)
    at args.push (/Users/lineus/dev/Help/mongoose5/node_modules/mongodb/lib/utils.js:404:72)
    at handleCallback (/Users/lineus/dev/Help/mongoose5/node_modules/mongodb/lib/utils.js:128:55)
    at self.close (/Users/lineus/dev/Help/mongoose5/node_modules/mongodb/lib/cursor.js:934:60)
    at handleCallback (/Users/lineus/dev/Help/mongoose5/node_modules/mongodb/lib/utils.js:128:55)
^C
InspiredMacPro:mongoose5 lineus$ 
```
### it's worth noting that trying to do something similar without any other modules except async behaves differently:
```
#!/usr/bin/env node
'use strict'

const async = require('async')

const test = {
  somethings: ['thing1', 'thing2']
}

async.waterfall([
  function one (cb) {
    let x = test.somethings.doesnt.exist
    return cb(null, 'who knows?', x)
  }
], done)

function done (x) {
  return console.log('done:', x)
}
```
### output: 
```
InspiredMacPro:mongoose5 lineus$ ./6178_4.js
/Users/lineus/dev/Help/mongoose5/6178_4.js:12
    let x = test.somethings.doesnt.exist
                                   ^

TypeError: Cannot read property 'exist' of undefined
    at one (/Users/lineus/dev/Help/mongoose5/6178_4.js:12:36)
    at nextTask (/Users/lineus/dev/Help/mongoose5/node_modules/async/dist/async.js:5070:14)
    at Object.waterfall (/Users/lineus/dev/Help/mongoose5/node_modules/async/dist/async.js:5073:5)
    at Object.<anonymous> (/Users/lineus/dev/Help/mongoose5/6178_4.js:10:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
InspiredMacPro:mongoose5 lineus$ 
```
