### ISSUE TITLE
errors in version 5 vs. version 4

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6195]
I'm breaking out your comment from #6178 into it's own issue @bgSosh. #6178 didn't mention version 4 so I think we can bring the discussion into a separate issue.

here is a slightly modified version of the code from the gist mentioned in [the comment](https://github.com/Automattic/mongoose/issues/6178#issuecomment-369906957)
```
#!/usr/bin/env node
'use strict'

var mongoose = require('./lib/test_db')
mongoose.set('debug', true)
var AnimalSchema = new mongoose.Schema({
  name: String
})

AnimalSchema.statics.foo = function (callback) {
  var animalId = new mongoose.mongo.ObjectId('5a994cf7d5ae8a6fc32e72fd')

  this.findById(animalId, { name: 1 }, function (err, animal) {
    if (err) {
      return callback(new Error('findById returned error: ' + err.toString()))
    }

    throw new Error('This is a thrown exception')
  })
}

var Animal = mongoose.model('Animal', AnimalSchema)

Animal.foo(function (err) {
  if (err) {
    console.log('from callback: ', err) // added a string to illustrate how the error is handled.
  } else {
    console.log('OK!')
  }
})

```
## output mongoose4:
```
InspiredMacPro:mongoose4 lineus$ ./6178_2.js 
Mongoose: animals.findOne({ _id: ObjectId("5a994cf7d5ae8a6fc32e72fd") }, { fields: { name: 1 } })
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: This is a thrown exception
    at /Users/lineus/dev/Help/mongoose4/6178_2.js:18:11
    at model.Query.<anonymous> (/Users/lineus/dev/Help/mongoose4/node_modules/mongoose/lib/model.js:4074:16)
    at /Users/lineus/dev/Help/mongoose4/node_modules/kareem/index.js:273:21
    at /Users/lineus/dev/Help/mongoose4/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
## output mongoose5:
```
InspiredMacPro:mongoose5 lineus$ ./6178_2.js 
Mongoose: animals.findOne({ _id: ObjectId("5a994cf7d5ae8a6fc32e72fd") }, { fields: { name: 1 } })
from callback:  Error: findById returned error: Error: This is a thrown exception
    at /Users/lineus/dev/Help/mongoose5/6178_2.js:15:23
    at /Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/model.js:3928:16
    at _init (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/query.js:2003:14)
    at completeOne (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/query.js:1998:5)
    at Immediate.<anonymous> (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/query.js:1516:11)
    at Immediate.<anonymous> (/Users/lineus/dev/Help/mongoose5/node_modules/mquery/lib/utils.js:119:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
^C
InspiredMacPro:mongoose5 lineus$ cd ../mongoose4
```

**Comment by lineus** [comment]
when throwing an error within a model's static method in version 4, the error is immediately thrown, in version 5 the callback gets called with the error. @vkarpov15 is this something worth documenting either in the faq or migration guide?

**Comment by bgSosh** [comment]
Ok thanks @lineus.

In my opinion, this is pretty strange behavior, and I'd be interested to know if this is working as it is supposed to.   I don't really understand why an unhandled exception, in *my* code, *after* the db function has called back, should be caught and returned by code that comes *before* it.
