### ISSUE TITLE
findByIdAndUpdate & $pull on subdocuments cause ValidationError

### ISSUE THREAD

**Issue by JunyuanZheng** [Automattic/mongoose#6240]
**What is the current behavior?**

I have a schema like this:

```
const highlightSchema = new mongoose.Schema({
  _id: {
    type: String,
    required: true
  },
  color: {
    type: String,
    required: true
  },
  range: {
    start: {
      type: Number,
      required: true
    },
    end: {
      type: Number,
      required: true
    }
  }
});

const schema = new mongoose.Schema({
  _id: {
    type: String,
    required: true
  },
  highlights: [highlightSchema],
});
```

what I am trying to do is I want to remove some `highligh subdocuments` by using `findByIdAndUpdate` & `$pull`:

```
mongoose.findByIdAndUpdate(id, {
  $pull: {
    highlights: {
      _id: {
        $in:  ['1', '2', '3', '4']
      }
    }
  }
});
``` 
If I add `runValidators: true` to the function, it will throw error:

```
console.log dist/server/src/database/mongodb/models/user-lesson-schema/__tests__/highlight/pull.test.js:84
ValidationError: highlights._id: Path `_id` is required., highlights._id.$in: Path `_id` is required.
at Object.<anonymous> (/app/dist/server/src/database/mongodb/utilites/findByIdAndUpdate.js:39:27)
at Generator.throw (<anonymous>)
at rejected (/app/dist/server/src/database/mongodb/utilites/findByIdAndUpdate.js:16:40)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:118:7)
```

It works perfectly if I change `runValidators` to `false`

**What is the expected behavior?**
I am wondering what is causing this issue? Am I using the `$pull` function in a wrong way?

**Please mention your node.js, mongoose and MongoDB version.**
Node: 9.7.1
MongoDB: 3.4.10
mongoose: 5.0.10

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate :+1:

**Comment by JunyuanZheng** [comment]
Reproduce repo: https://github.com/JunyuanZheng/Mongoose6240

```
docker-compose build
docker-compose up
```

2 API endpoints to reproduce this issue:

Success DB update: `http://localhost:3000/success`
Fail DB update: `http://localhost:3000/fail` and you will see the error `"Validation failed: highlights._id: Path `_id` is required., highlights._id.$in: Path `_id` is required."`

**Comment by vkarpov15** [comment]
Here's the script I used to repro. In general, we strongly prefer repro scripts that don't require HTTP and refuse to accept repro scripts that require docker unless there's a docker-specific issue, so please keep that in mind for next time.

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh-6240`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const highlightSchema = new mongoose.Schema({
    _id: {
      type: String,
      required: true
    },
    color: {
      type: String,
      required: true
    },
    range: {
      start: {
        type: Number,
        required: true
      },
      end: {
        type: Number,
        required: true
      }
    }
  });

  const schema = new mongoose.Schema({
    _id: {
      type: String,
      required: true
    },
    highlights: [highlightSchema],
  });

  const Model = mongoose.model('gh6240', schema);

  const doc = await Model.create({ _id: '1', highlights: [{ _id: '1', color: 'green', range: { start: 1, end: 2 } }] });

  await Model.findByIdAndUpdate('1', {
    $pull: {
      highlights: {
        _id: {
          $in:  ['1', '2', '3', '4']
        }
      }
    }
  }, { runValidators: true });
}
```
