### ISSUE TITLE
Improve docs for `create()` params

### ISSUE THREAD

**Issue by reduxdj** [Automattic/mongoose#6242]
mongodb: 3.2.12
node: 9.6.1
mongoose: 5.0.10 / (observed in 5.03 too)

Unable to save a schema, i am in a bit of a whack-a-mole with a model save, new document's don't save, actually they save but they throw errors when they successfully insert.

Schema looks like...

```const PointsTransactionSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, required },
  type: { type: String, required },
  points: { type: Number, required },
  description: String
}, { timestamps })
```

Save method looks like:

```
await Points.create({ userId: 5a8a276ddfdw0a0983c6a8,
  points: 160,
  description: 'to keep customer happy',
  type: 'CUSTOMER_SATISIFACTION' }, { safe: false })
```

throws errors like:
```{ ValidationError: PointsTransaction validation failed: points: Path `points` is required., type: Path `type` is required., userId: Path `userId` is required.
    at ValidationError.inspect (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/error/validation.js:56:24)
    at formatValue (util.js:412:38)
    at inspect (util.js:302:10)
    at format (util.js:165:12)
    at Console.log (console.js:140:21)
    at resolve (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:18897:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  errors:
   { points:
      { ValidatorError: Path `points` is required.
    at new ValidatorError (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/error/validator.js:25:11)
    at validate (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:805:13)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:854:11
    at Array.forEach (<anonymous>)
    at SchemaNumber.SchemaType.doValidate (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:814:19)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/document.js:1618:9
    at process._tickCallback (internal/process/next_tick.js:150:11)
        message: 'Path `points` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'points',
        value: undefined,
        reason: undefined,
        '$isValidatorError': true },
     type:
      { ValidatorError: Path `type` is required.
    at new ValidatorError (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/error/validator.js:25:11)
    at validate (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:805:13)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:854:11
    at Array.forEach (<anonymous>)
    at SchemaString.SchemaType.doValidate (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:814:19)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/document.js:1618:9
    at process._tickCallback (internal/process/next_tick.js:150:11)
        message: 'Path `type` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'type',
        value: undefined,
        reason: undefined,
        '$isValidatorError': true },
     userId:
      { ValidatorError: Path `userId` is required.
    at new ValidatorError (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/error/validator.js:25:11)
    at validate (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:805:13)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:854:11
    at Array.forEach (<anonymous>)
    at ObjectId.SchemaType.doValidate (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/schematype.js:814:19)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/mongoose/lib/document.js:1618:9
    at process._tickCallback (internal/process/next_tick.js:150:11)
        message: 'Path `userId` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'userId',
        value: undefined,
        reason: undefined,
        '$isValidatorError': true } },
  _message: 'PointsTransaction validation failed',
  name: 'ValidationError' }
Debugger listening on ws://127.0.0.1:9229/0cef18fe-8a98-4e24-aa91-2c0fdebff0b4
For help see https://nodejs.org/en/docs/inspector
production
Name "__typename" must not begin with "__", which is reserved by GraphQL introspection. In a future release of graphql this will become a hard error.
    at assertValidName (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/graphql/utilities/assertValidName.js:37:19)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/graphql/type/definition.js:693:44
    at Array.forEach (<anonymous>)
    at GraphQLInputObjectType._defineFieldMap (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/graphql/type/definition.js:692:16)
    at GraphQLInputObjectType.getFields (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/graphql/type/definition.js:681:49)
    at typeMapReducer (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/graphql/type/schema.js:223:26)
    at Array.reduce (<anonymous>)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/graphql/type/schema.js:216:36
    at Array.forEach (<anonymous>)
    at typeMapReducer (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/graphql/type/schema.js:209:27)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/graphql/type/schema.js:97:34)
    at Object.defineProperty.value (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:15582:19)
    at __webpack_require__ (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:20:30)
    at Object.defineProperty.value (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:6668:37)
    at __webpack_require__ (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:20:30)
    at Object.<anonymous> (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:4858:12)
    at __webpack_require__ (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:20:30)
    at Object.defineProperty.value (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:4539:15)
    at __webpack_require__ (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:20:30)
    at Object.<anonymous> (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:4523:18)
    at __webpack_require__ (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:20:30)
    at /Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:63:18
    at Object.<anonymous> (/Users/patricklemiuex/projects/iflipd-admin-reactql/dist/server_dev.js:66:10)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3```

Removing safe false, produces this error:

{ DocumentNotFoundError: No document found for query "undefined"

**Comment by lineus** [comment]
Hi @reduxdj!
Are you really passing in an object literal to Model.create()? Or is that just an example of a model instance that's getting passed in, in your app? Can you create a standalone example that fails in the same way as your app?

I created this contrived example:
```
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  name: {
    type: String,
    required: true
  }
})

const Test = mongoose.model('tests', schema)

Test.create({
  name: 5                                                                       //
}).then((res) => {
  mongoose.connection.close()
  return console.log(res)
}).catch((err) => {
  mongoose.connection.close()
  return console.error(err)
})
```
output:
```
mongoose5: node ./6242.js 
{ name: '5', _id: 5aa8f626cf74cd0fd6aa30fb, __v: 0 }
mongoose5: 
```

**Comment by lineus** [comment]
Hi @reduxdj 

Can you please provide us with a minimal but complete example that demonstrates the behavior you're experiencing? 

for example:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  name: {
    type: String,
    required: true }
})

const Test = mongoose.model('tests', schema)

const tests = [
  new Test({ name: 'Becky' }),
  new Test({ name: 5 }),
  new Test({ name: 4 }),
  new Test({ name: true }),
  new Test({ name: false })
]

Test.create(tests).then((res) => {
  Test.find({}).then((res) => {
    mongoose.connection.close()
    return console.log(res)
  })
}).catch((err) => {
  mongoose.connection.close()
  return console.error(err)
})
```
outputs:
```
mongoose5: ./6242.js 
[ { _id: 5aa90460addaf51407b32ab9, name: 'Becky', __v: 0 },
  { _id: 5aa90460addaf51407b32aba, name: '5', __v: 0 },
  { _id: 5aa90460addaf51407b32abb, name: '4', __v: 0 },
  { _id: 5aa90460addaf51407b32abc, name: 'true', __v: 0 },
  { _id: 5aa90460addaf51407b32abd, name: 'false', __v: 0 } ]
mongoose5: 
```

**Comment by zleight1** [comment]
I'm also seeing something similar I'm getting a DocumentNotFoundError when doing this:

```
const createUserIdentityByIdAsync = async(userId, identity) => {
    const newIdentity = await Identity.create(identity);
    ...
};
```

```
const mongoose = require('mongoose');
const timestamps = require('mongoose-timestamp');

const { identityTypeList, countryList } = require('../user/user.enums');

const IdentitySchema = new mongoose.Schema({
    number: { // todo do we need to encrypt this?
        type: String,
        required: true,
        index: true,
    },
    type: {
        type: String,
        required: true,
        enum: identityTypeList,
    },
    country: {
        type: String,
        enum: countryList,
        required: true,
    },
    validUntil: { // todo discuss
        type: Date,
    },
});

IdentitySchema.plugin(timestamps);
const Identity = mongoose.model('Identity', IdentitySchema);

module.exports = {
    Identity,
};
```

What I'm saving:
```
{
	"number": "xyz",
	"type": "Passport",
	"country": "IL"
}
```

**Comment by reduxdj** [comment]
sure thanks for that snippit, i have confirmed that issue is between the mongoDB version and the new library, downgrading 4.13 things are working again. Here's the output. This ran fine against my local mongoDB, oh and my mongo 3.2.2 is a replicaset btw.

```[ { _id: 5aa9cc84aa13c4c23d381589, name: 'Becky', __v: 0 },
  { _id: 5aa9cc84aa13c4c23d38158b, name: '4', __v: 0 },
  { _id: 5aa9cc84aa13c4c23d38158a, name: '5', __v: 0 },
  { _id: 5aa9cc84aa13c4c23d38158c, name: 'true', __v: 0 },
  { _id: 5aa9cc84aa13c4c23d38158d, name: 'false', __v: 0 } ]
Patricks-MBP:test_project patricklemiuex$ node test.js
{ DocumentNotFoundError: No document found for query "undefined"
    at new DocumentNotFoundError (/Users/patricklemiuex/test_project/node_modules/mongoose/lib/error/notFound.js:31:11)
    at $__handleSave (/Users/patricklemiuex/test_project/node_modules/mongoose/lib/model.js:273:17)
    at /Users/patricklemiuex/test_project/node_modules/mongoose/lib/model.js:169:7
    at result (/Users/patricklemiuex/test_project/node_modules/mongodb/lib/utils.js:413:17)
    at executeCallback (/Users/patricklemiuex/test_project/node_modules/mongodb/lib/utils.js:404:35)
    at /Users/patricklemiuex/test_project/node_modules/mongodb/lib/collection.js:659:5
    at result (/Users/patricklemiuex/test_project/node_modules/mongodb/lib/utils.js:413:17)
    at executeCallback (/Users/patricklemiuex/test_project/node_modules/mongodb/lib/utils.js:405:9)
    at handleCallback (/Users/patricklemiuex/test_project/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/patricklemiuex/test_project/node_modules/mongodb/lib/bulk/unordered.js:560:16
    at handleCallback (/Users/patricklemiuex/test_project/node_modules/mongodb/lib/utils.js:128:55)
    at resultHandler (/Users/patricklemiuex/test_project/node_modules/mongodb/lib/bulk/unordered.js:456:5)
    at handler (/Users/patricklemiuex/test_project/node_modules/mongodb-core/lib/topologies/replset.js:1210:22)
    at /Users/patricklemiuex/test_project/node_modules/mongodb-core/lib/connection/pool.js:541:18
    at process._tickCallback (internal/process/next_tick.js:150:11)
  message: 'No document found for query "undefined"',
  name: 'DocumentNotFoundError',
  query: undefined }```

**Comment by lineus** [comment]
I spun up replica sets locally with 3.0.2, 3.2.10, 3.4.4, and 3.6.2:
the only change to my code above was:
```
mongoose.connect('mongodb://localhost:27031,localhost:27032,localhost:27033/test?replicaSet=testing123')
```

results for all 4 mongod versions were the same:
```
mongoose5: ./6242.js 
[ { _id: 5aaa474d39fff850e2d5df4f, name: 'Becky', __v: 0 },
  { _id: 5aaa474d39fff850e2d5df50, name: '5', __v: 0 },
  { _id: 5aaa474d39fff850e2d5df52, name: 'true', __v: 0 },
  { _id: 5aaa474d39fff850e2d5df51, name: '4', __v: 0 },
  { _id: 5aaa474d39fff850e2d5df53, name: 'false', __v: 0 } ]
  
mongoose5: mongo --port 27031
testing123:PRIMARY> db.tests.find()
{ "_id" : ObjectId("5aaa474d39fff850e2d5df4f"), "name" : "Becky", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df50"), "name" : "5", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df52"), "name" : "true", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df51"), "name" : "4", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df53"), "name" : "false", "__v" : 0 }
testing123:PRIMARY> 
bye

mongoose5: mongo --port 27032
testing123:SECONDARY> rs.slaveOk()
testing123:SECONDARY> db.tests.find()
{ "_id" : ObjectId("5aaa474d39fff850e2d5df4f"), "name" : "Becky", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df50"), "name" : "5", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df52"), "name" : "true", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df51"), "name" : "4", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df53"), "name" : "false", "__v" : 0 }
testing123:SECONDARY> 
bye

mongoose5: mongo --port 27033
testing123:SECONDARY> rs.slaveOk()
testing123:SECONDARY> db.tests.find()
{ "_id" : ObjectId("5aaa474d39fff850e2d5df4f"), "name" : "Becky", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df50"), "name" : "5", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df52"), "name" : "true", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df51"), "name" : "4", "__v" : 0 }
{ "_id" : ObjectId("5aaa474d39fff850e2d5df53"), "name" : "false", "__v" : 0 }
testing123:SECONDARY> 
bye
```
I'll see if I can find exact copies of the versions reported, and try again.

**Comment by zleight1** [comment]
Downgrading to 4.13.12 fixed this for me

**Comment by lineus** [comment]
I tried to find an official source for older versions, but I couldn't find 3.2.2. So I instead created a free atlas account and ran the following code against it based on @zleight1's example.
```
#!/usr/bin/env node
'use strict'

const uri = 'mongodb://uuuu:pppp@cscs.mongodb.net:27017,cscs.mongodb.net:27017,cscs.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin'
const mongoose = require('mongoose')
const timestamps = require('mongoose-timestamp')
mongoose.connect(uri)
const Schema = mongoose.Schema
const faker = require('faker')

const countryList = ['Latvia', 'Dominica', 'Chad']

const identityTypeList = ['widget', 'thingamabob', 'hooziewhatzit']

const IdentitySchema = new Schema({
  number: {
    type: String,
    required: true,
    index: true
  },
  type: {
    type: String,
    required: true,
    enum: identityTypeList
  },
  country: {
    type: String,
    enum: countryList,
    required: true
  },
  validUntil: {
    type: Date
  }
})

IdentitySchema.plugin(timestamps)

const User = mongoose.model('users', IdentitySchema)

const num = 1000

async function getCount () {
  let n = await User.count()
  if (n < num) {
    setTimeout(getCount, 1000)
  } else {
    console.log(`added ${n} of ${num} users.`)
    return mongoose.connection.close()
  }
}

async function createUser (userObject, lastOne) {
  await User.create(userObject)
  if (lastOne) {
    getCount()
  }
}

async function run () {
  await User.remove({})
  for (let i = 0; i < num; i++) {
    let id = faker.random.number({ min: 0, max: 2 })
    let co = faker.random.number({ min: 0, max: 2 })
    let last = (i === num - 1)
    createUser({
      number: String(faker.random.number(60)) + i,
      type: identityTypeList[id],
      country: countryList[co],
      validUntil: faker.date.future()
    }, last)
  }
}

run()
```
### output:
```
mongoose5: ./6242_2.js && ./6242_2.js && ./6242_2.js && ./6242_2.js && ./6242_2.js
added 1000 of 1000 users.
added 1000 of 1000 users.
added 1000 of 1000 users.
added 1000 of 1000 users.
added 1000 of 1000 users.
mongoose5: 
```
@zleight1 can you change the uri in my example and run it against your atlas cluster using mongoose 5@latest and see if it works? **beware** of the remove in my script. If you don't see any errors in my adaptation of your previous example, create a complete example like I did that does error for you and I'll give it a try against my cluster.

**Comment by vkarpov15** [comment]
I think the problem is that this syntax is wrong:

```javascript
await Points.create({ userId: 5a8a276ddfdw0a0983c6a8,
  points: 160,
  description: 'to keep customer happy',
  type: 'CUSTOMER_SATISIFACTION' }, { safe: false })
```

[`create()` assumes every parameter is a document that you're trying to insert](http://mongoosejs.com/docs/api.html#create_create), so it is creating a new document `{ safe: false }` and trying to save that, which obviously fails. In general, there is no way to pass options to `create()`.
