### ISSUE TITLE
[bug] Mongoose generate weird query when using find method.

### ISSUE THREAD

**Issue by dinhanhhuy** [Automattic/mongoose#6312]
**I want report this is a *bug***

**The current behavior:**
Can't find the matching documents.
When i run this code, with moongoose as debug mod
```javascript
const ids = _bots.map(e => core.Types.ObjectId(e.id));
return UserWalletSchema.find(
    { user_id : { $in : ids } }
).then(res => {
    console.log(res)
})
```
`console.log` say can't find any match document (empty array).
```bash
user_wallets.find({ user_id: { '$in': [ ObjectId("5ac4743c03d0a873cde5118d"), ObjectId("5ac4743c03d0a873cde5118b"), ObjectId("5ac4743c03d0a873cde5118c"), ObjectId("5ac47c0803d0a873cde5118f"), ObjectId("5ac4743c03d0a873cde5118e"), ObjectId("5ac47c0803d0a873cde51190") ] } }, { fields: {} })
[]
```
**The expected behavior:**
I don't know why`{ fields: {} }` exist in the query log.
When i put whole query log in `MongoDB` it's reponse error:
```
{
	"message" : ">1 field in obj: {}",
	"stack" : "MongoError: >1 field in obj: {}" +
              "at queryCallback (/Applications/NoSQLBooster for MongoDB.app/Contents/Resources/app.asar/node_modules/mongodb-core/lib/cursor.js:223:25)" +
              "at /Applications/NoSQLBooster for MongoDB.app/Contents/Resources/app.asar/node_modules/mongodb-core/lib/connection/pool.js:541:18" +
              "at _combinedTickCallback (internal/process/next_tick.js:131:7)" +
              "at process._tickCallback (internal/process/next_tick.js:180:9)",
	"name" : "MongoError",
	"ok" : 0,
	"errmsg" : ">1 field in obj: {}",
	"code" : 2,
	"codeName" : "BadValue"
}
```
When I remove that weird object, MongoDB returns 42 existing documents.

**Version:**
computer run node:
```
OS: MacOS 10.13.3
node v8.5.0
mongoose version 5.0.12.
```
computer host the database:
```
OS: 4.13.0-1011-gcp #15-Ubuntu SMP Mon Feb 12 16:29:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
MongoDB version v3.6.3
```

**Comment by dinhanhhuy** [comment]
I'm find that this issue cause by using many connection on 1 object moongose. Delete this.
