### ISSUE TITLE
Unexpected Model.count() behaviour

### ISSUE THREAD

**Issue by olnazx** [Automattic/mongoose#6323]
Mongoose throws `TypeError` on `Model.count()` I use object without prototype in the query.

```js
const Model = connection.model('Model');

let query = {
  key: 'value'
}

let priceQuery = Object.create(null);

priceQuery.$gte = 0;
priceQuery.$lte = 200;

Object.assign(query, { price: priceQuery });

Track.count(query).exec();

// =>
//
// TypeError: Cannot read property 'name' of undefined
//     at cast (/home/olnazx/beatgun/node_modules/mongoose/lib/cast.js:239:34)
//     at model.Query.Query.cast (/home/olnazx/beatgun/node_modules/mongoose/lib/query.js:3208:12)
//     at model.Query.Query._count (/home/olnazx/beatgun/node_modules/mongoose/lib/query.js:1628:10)
//     at process.nextTick (/home/olnazx/beatgun/node_modules/kareem/index.js:311:33)
//     at process._tickCallback (internal/process/next_tick.js:150:11)
//     at Function.Module.runMain (module.js:703:11)
//     at startup (bootstrap_node.js:193:16)
//     at bootstrap_node.js:617:3
```

```js
const Model = connection.model('Model');

let query = {
  key: 'value'
}

let priceQuery = Object.create(null);

priceQuery.$gte = 0;
priceQuery.$lte = 200;

Object.assign(query, { price: priceQuery });

Track.find(query).exec();

// => 'find' works fine
```
```js
const Model = connection.model('Model');

let query = {
  key: 'value'
}

let priceQuery = {};

priceQuery.$gte = 0;
priceQuery.$lte = 200;

Object.assign(query, { price: priceQuery });

Track.count(query).exec();

// => also works fine
```

**Node.js**: 9.4.0
**Mongoose**: 5.0.13
**MongoDB**: 3.6.3

**Comment by lineus** [comment]
confirmed with the following repro script:

### 6323.js
```js
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  key: String,
  price: Number
})

const Model = mongoose.model('test', schema)

const tests = []

for (let i = 0; i < 10; i++) {
  let p = i * 25
  tests.push(new Model({ key: 'value', price: p }))
}

let query = {
  key: 'value'
}

let priceQuery = Object.create(null)

priceQuery.$gte = 0
priceQuery.$lte = 200

Object.assign(query, { price: priceQuery })

console.log(query)
async function run () {
  await Model.remove({})
  await Model.create(tests)
  let count = await Model.count(query)
  console.log(count)
}

run().catch(console.error)
```
### output:
```
issues: ./6323.js
TypeError: Cannot read property 'name' of undefined
    at cast (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/cast.js:239:34)
    at model.Query.Query.cast (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/query.js:3210:12)
    at model.Query.Query._count (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/query.js:1628:10)
    at process.nextTick (/Users/lineus/dev/Help/mongoose5/node_modules/kareem/index.js:311:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
^C
issues:
```

**Comment by varunjayaraman** [comment]
yeah this looks like a bug

**Comment by vkarpov15** [comment]
:tada: love it when bugs are already fixed
