### ISSUE TITLE
Dubious Document `No document found for query "undefined"` saving on replica sets returns

### ISSUE THREAD

**Issue by reduxdj** [Automattic/mongoose#6356]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Documents don't save correctly often to replica sets, documents are created but a Document Not Found Error comes back where a result is expected, unless safe: false, this seems similar to a bug I had https://github.com/Automattic/mongoose/issues/6327. What's interesting is that the issue is very similar to this one, only seems to be a problem with replica sets now, as our staging instance didn't have any problems.

**If the current behavior is a bug, please provide the steps to reproduce.**

It's hard to reproduce the error, without giving you my source code, and i don't have a spare replica set.

**What is the expected behavior?**

The document needs to be replaced.

**Please mention your node.js, mongoose and MongoDB version.**

8.5, 5.14, 3.63 Replica set

 DocumentNotFoundError: No document found for query "undefined"
    at DocumentNotFoundError (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongoose/lib/error/notFound.js:31:11)
    at $__handleSave (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongoose/lib/model.js:279:17)
    at /Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongoose/lib/model.js:170:7
    at result (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:414:17)
    at session.endSession (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:400:37)
    at ClientSession.endSession (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb-core/lib/sessions.js:72:41)
    at executeCallback (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:397:17)
    at /Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/collection.js:659:5
    at result (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/bulk/unordered.js:560:16
    at handleCallback (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/utils.js:128:55)
    at resultHandler (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb/lib/bulk/unordered.js:456:5)
    at handler (/Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb-core/lib/topologies/replset.js:1209:22)
    at /Users/ckpalk/Documents/iFlipd/Repos/admin-reactql/node_modules/mongodb-core/lib/connection/pool.js:544:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  message: 'No document found for query "undefined"',
  name: 'DocumentNotFoundError',
  query: undefined }

**Comment by vkarpov15** [comment]
This bug report isn't really actionable, but I can suggest [not setting the `safe` option as I mentioned in the other issue you commented on](https://github.com/Automattic/mongoose/issues/6012#issuecomment-383648689). Also, are you sure this issue only occurs on replica sets?
