### ISSUE TITLE
{ model } doesn't work

### ISSUE THREAD

**Issue by matinkaboli** [Automattic/mongoose#6379]
Hi, I want to use 
`import { model, Schema } from 'mongoose';`

instead of

`import mongoose, { Schema } from 'mongoose';`

but when I replace that, I get this error

```
/home/matin/Workshop/projects/blog/node_modules/mongoose/lib/index.js:331
  if (!this.modelSchemas[name]) {
            ^

TypeError: Cannot read property 'modelSchemas' of undefined
    at Mongoose.model (/home/matin/Workshop/projects/blog/node_modules/mongoose/lib/index.js:331:13)
    at Object.defineProperty.value (/home/matin/Workshop/projects/blog/build/app.js:1450:39)
    at __webpack_require__ (/home/matin/Workshop/projects/blog/build/app.js:20:30)
    at Object.defineProperty.value (/home/matin/Workshop/projects/blog/build/app.js:4549:17)
    at __webpack_require__ (/home/matin/Workshop/projects/blog/build/app.js:20:30)
    at Object.defineProperty.value (/home/matin/Workshop/projects/blog/build/app.js:4525:20)
    at __webpack_require__ (/home/matin/Workshop/projects/blog/build/app.js:20:30)
    at Object.defineProperty.value (/home/matin/Workshop/projects/blog/build/app.js:4051:95)
    at __webpack_require__ (/home/matin/Workshop/projects/blog/build/app.js:20:30)
    at Object.<anonymous> (/home/matin/Workshop/projects/blog/build/app.js:1926:16)
    at __webpack_require__ (/home/matin/Workshop/projects/blog/build/app.js:20:30)
    at /home/matin/Workshop/projects/blog/build/app.js:63:18
    at Object.<anonymous> (/home/matin/Workshop/projects/blog/build/app.js:66:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
```

Mongo version = 3.6.3
Node version = 9.8.0
Mongoose version = ^5.0.1

**Comment by lineus** [comment]
There is already an open issue that addresses this problem, #6039. 

`import { model, Schema } from 'mongoose'` isn't supported yet.

For the time being you'll need to use `import mongoose from 'mongoose'`.

**Comment by vkarpov15** [comment]
@lineus is right, those import syntaxes are not currently supported.
