### ISSUE TITLE
sync error in pre hook

### ISSUE THREAD

**Issue by iofjuupasli** [Automattic/mongoose#6384]
Bug

Throwing sync error in pre hook should stop calling middlewares and return error.
Now it continues to call hooks, and returns without error

```js
const mongoose = require(`mongoose`);

const mySchema = new mongoose.Schema({
    host: {type: String}
});
mySchema.pre('save', function () {
    throw new Error('error');
});
mySchema.pre('save', function () {
    return Promise.resolve();// shouldn't be called
});
const MyModel = mongoose.model('User', mySchema);

// should fail
MyModel.create({host: `foo`})
    .then((data) => console.log(`data`, data))
    .catch((err) => console.log(`err`, err));
```

v5.0.15

**Comment by lineus** [comment]
Hey @iofjuupasli, thanks for the complete repro script!

If you don't supply your first pre-hook with at least one parameter, it must return a promise in order to call the next one with an error. 

### Passing a next parameter only

changing your example to:
```js
mySchema.pre('save', function (next) {
  throw new Error('error');
});
```

### or returning a promise:

either:
```
mySchema.pre('save', function () {
  return Promise.reject(new Error('error'));
});
```
```
mySchema.pre('save', async function () {
  throw new Error('error');
});
```

### all 3 examples above result in the error being handled correctly:
```
issues: ./6384.js
err Error: error
    at model.<anonymous> (/Users/lineus/dev/Help/mongoose5/issues/6384.js:10:9)
    at model.next (/Users/lineus/dev/Help/mongoose5/node_modules/kareem/index.js:63:31)
    at _next (/Users/lineus/dev/Help/mongoose5/node_modules/kareem/index.js:106:10)
    at process.nextTick (/Users/lineus/dev/Help/mongoose5/node_modules/kareem/index.js:427:38)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
issues:
```
