### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Decapitary** [Automattic/mongoose#6404]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
```
PROJECTPATH\node_modules\mongoose\lib\utils.js:214
        throw error;
        ^

RangeError: Maximum call stack size exceeded
    at clone (PROJECTPATH\node_modules\mongoose\lib\utils.js:153:3
1)
    at cloneObject (PROJECTPATH\node_modules\mongoose\lib\utils.js
:246:11)
    at clone (PROJECTPATH\node_modules\mongoose\lib\utils.js:172:1
6)
    at cloneObject (PROJECTPATH\node_modules\mongoose\lib\utils.js
:246:11)
    at clone (PROJECTPATH\node_modules\mongoose\lib\utils.js:172:1
6)
    at cloneObject (PROJECTPATH\node_modules\mongoose\lib\utils.js
:246:11)
    at clone (PROJECTPATH\node_modules\mongoose\lib\utils.js:172:1
6)
    at cloneObject (PROJECTPATH\node_modules\mongoose\lib\utils.js
:246:11)
    at clone (PROJECTPATH\node_modules\mongoose\lib\utils.js:172:1
6)
    at cloneObject (PROJECTPATH\node_modules\mongoose\lib\utils.js
:246:11)
    at clone (PROJECTPATH\node_modules\mongoose\lib\utils.js:172:1
6)
    at cloneObject (PROJECTPATH\node_modules\mongoose\lib\utils.js
:246:11)
    at clone (PROJECTPATH\node_modules\mongoose\lib\utils.js:172:1
6)
    at cloneObject (PROJECTPATH\node_modules\mongoose\lib\utils.js
:246:11)
    at clone (PROJECTPATH\node_modules\mongoose\lib\utils.js:172:1
6)
    at cloneObject (PROJECTPATH\node_modules\mongoose\lib\utils.js
:246:11)

```
**If the current behavior is a bug, please provide the steps to reproduce.**

```
//Schema is like
const BookSchema = mongoose.Schema ({
  authors: [{ type: Schema.Types.ObjectId, ref: 'Author' }],
},{ timestamps: { createdAt: 'created_at' , updatedAt: 'updated_at'} });
// Im trying to push new Author like this
let newAuthor = new Author({
  name: 'Frank'
});
newAuthor.save((err) => {
  console.log(err)
});
console.log('newAuthor generated', newAuthor);
book1.authors.push(newAuthor);  //ERROR OCCURES AT THIS PUSH!
book1.save();
console.log(book1)

```
**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
node 8.4
mongoose  5.6.0
mongoDB 3.6.3

**Comment by Decapitary** [comment]
nvm it seems like newAuthor wasnt saved. I move the push function in newAuthor callback and problem was solved!
