### ISSUE TITLE
Cannot assign to read only property 'remove' of object '[object Array]'

### ISSUE THREAD

**Issue by wesleimarinho** [Automattic/mongoose#6431]
I'm using MongoDB 3.6.4 Community, NodeJS 8.9.4 and Mongoose 5.0.17, on Windows 10 Professional

From time to time the following stack trace shows on console, stopping the application:

```
F:\Proj1\node_modules\mongoose\node_modules\mongodb\lib\utils.js:132
      throw err;
      ^

TypeError: Cannot assign to read only property 'remove' of object '[object Array]'
    at new MongooseDocumentArray (F:\Proj1\node_modules\mongoose\lib\types\documentarray.js:45:20)
    at DocumentArray.cast (F:\Proj1\node_modules\mongoose\lib\schema\documentarray.js:274:13)
    at DocumentArray.SchemaType.getDefault (F:\Proj1\node_modules\mongoose\lib\schematype.js:671:23)
    at $__applyDefaults (F:\Proj1\node_modules\mongoose\lib\document.js:298:22)
    at model.Document (F:\Proj1\node_modules\mongoose\lib\document.js:118:3)
    at model.Model (F:\Proj1\node_modules\mongoose\lib\model.js:62:12)
    at new model (F:\Proj1\node_modules\mongoose\lib\model.js:3776:13)
    at Object.createModel (F:\Proj1\node_modules\mongoose\lib\queryhelpers.js:106:10)
    at completeMany (F:\Proj1\node_modules\mongoose\lib\query.js:1467:22)
    at cb (F:\Proj1\node_modules\mongoose\lib\query.js:1328:11)
    at result (F:\Proj1\node_modules\mongoose\node_modules\mongodb\lib\utils.js:414:17)
    at executeCallback (F:\Proj1\node_modules\mongoose\node_modules\mongodb\lib\utils.js:406:9)
    at handleCallback (F:\Proj1\node_modules\mongoose\node_modules\mongodb\lib\utils.js:128:55)
    at self.close (F:\Proj1\node_modules\mongoose\node_modules\mongodb\lib\cursor.js:904:60)
    at handleCallback (F:\Proj1\node_modules\mongoose\node_modules\mongodb\lib\utils.js:128:55)
    at completeClose (F:\Proj1\node_modules\mongoose\node_modules\mongodb\lib\cursor.js:1043:14)
Waiting for the debugger to disconnect...
```

Is it a bug? It doesn't trace back to any of my project files.

**Comment by lineus** [comment]
@wesleimarinho can you provide a code sample based on your project ( preferably one that shows the error)? Alternatively, you can provide a link to your repo and I'll take a look at it.

**Comment by wesleimarinho** [comment]
@lineus, unfortunately my repository isn't public, and I consider difficult to isolate the behavior to make a simpler code base to reproduce the problem, because it happens apparently randomly and the output of the issue does not trace to any of my project files. Instead, could you please suggest some debugging info I could insert in the files mentioned in the stack trace, so we could get more information about the issue? I will try to figure out which conditions is triggering the issue as well.

**Comment by lineus** [comment]
@wesleimarinho In version 5.0.17, you *could* replace line 45 of lib/types/documentarray.js with:
```js
    try {
      arr[keysMA[j]] = MongooseArray.mixin[keysMA[j]];
    } catch(e) {
      console.error(values, path, doc)
      process.exit(1)
    }
```
this will show you the document, path, and values you're trying to save at the time of the next failure and hopefully lend some insight.

In the meantime, I'll see if I can come up with a way to replicate the issue. A schema mocking the one from your project with any proprietary info removed would certainly help with this task.

**Comment by wesleimarinho** [comment]
It is not an empty array, I printed its property remove and it is:

```
function (value, firstOnly)
    {
        var index = this.indexOf(value);
        if (index === -1)
            return false;
        if (firstOnly) {
            this.splice(index, 1);
            return true;
        }
        for (var i = index + 1, n = this.length; i < n; ++i) {
            if (this[i] !== value)
                this[index++] = this[i];
        }
        this.length = index;
        return true;
    }
```

The value it is trying to override on remove is:

```
function () {
    var values = [].map.call(arguments, this._cast, this);
    var cur = this._parent.get(this._path);
    var i = cur.length;
    var mem;

    while (i--) {
      mem = cur[i];
      if (mem instanceof Document) {
        var some = values.some(function(v) {
          return mem.equals(v);
        });
        if (some) {
          [].splice.call(cur, i, 1);
        }
      } else if (~cur.indexOf.call(values, mem)) {
        [].splice.call(cur, i, 1);
      }
    }

    if (values[0] instanceof EmbeddedDocument) {
      this._registerAtomic('$pullDocs', values.map(function(v) {
        return v._id || v;
      }));
    } else {
      this._registerAtomic('$pullAll', values);
    }

    this._markModified();

    // Might have modified child paths and then pulled, like
    // `doc.children[1].name = 'test';` followed by
    // `doc.children.remove(doc.children[0]);`. In this case we fall back
    // to a `$set` on the whole array. See #3511
    if (cleanModifiedSubpaths(this._parent, this._path) > 0) {
      this._registerAtomic('$set', this);
    }

    return this;
  }
```

**Comment by wesleimarinho** [comment]
@lineus Yes, I finally could isolated the problem. I will report how to reproduce the problem in a few minutes.  Do I reply here or should I open a new issue:

**Comment by lineus** [comment]
might as well reply here 👍

**Comment by wesleimarinho** [comment]
Steps to reproduce the issue:

1 - Create an empty application with express generator:

`express`

2 - Install Mongoose:

`npm install mongoose`

3 - Install Lighthouse:

`npm install lighthouse`

4 - Install dependencies:

`npm install`

5 - Add the following code to routes/index.js before `module.exports = router;`:


```
var mongoose = require('mongoose');
var s = mongoose.Schema({ 
  excluido: {  
    type: Boolean, 
    default: false 
  },
  field1: { 
    type: Number, 
    default: 5,
    required: true 
  },
  field2: { 
    type: String,
    required: true, 
    default: 'xxxx'
  },
  situacao: { 
    type: String, 
    enum: ['ativo', 'bloqueado', 'excluido'],
    default: 'ativo' 
  },
  resultados: [{
    a: String
  }]
});
var m = mongoose.model('S', s);
mongoose.connect('mongodb://localhost/test');

router.get('/insert', (req, res, next) => {
  m.create({}, (e, d) => {
    if (e)
      throw e;
    else
      res.send('ok');
  });
});

router.get('/crash', (req, res, next) => {
  const lighthouse = require('lighthouse');

  m.find({}, (e, data) => {
    res.send(JSON.stringify(data));
  });
});

```

6 - Run the application and access `http://localhost:3000/insert` and then `http://localhost:3000/crash`

**Comment by lineus** [comment]
express is superfluous, this can be replicated with just mongoose and lighthouse:
### 6431.js
```js
#!/usr/bin/env node
'use strict';

const lighthouse = require('lighthouse')
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const sub = new Schema({
  name: String
});

const schema = new Schema({
  arr: [sub]
});

const Test = mongoose.model('test', schema);

const test = new Test({
  arr: [{ name: 'test' }]
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  return conn.close();
}

run().catch(console.error);
```
### Outputs:
```
issues: ./6431.js
/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/types/documentarray.js:45
    arr[keysMA[j]] = MongooseArray.mixin[keysMA[j]];
                   ^

TypeError: Cannot assign to read only property 'remove' of object '[object Array]'
    at new MongooseDocumentArray (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/types/documentarray.js:45:20)
    at DocumentArray.cast (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/schema/documentarray.js:274:13)
    at DocumentArray.SchemaType.getDefault (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/schematype.js:671:23)
    at $__applyDefaults (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/document.js:298:22)
    at model.Document (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/document.js:118:3)
    at model.Model (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/model.js:62:12)
    at new model (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/model.js:3776:13)
    at Object.<anonymous> (/Users/lineus/dev/Help/mongoose5/issues/6431.js:20:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
issues:
```

**Comment by vkarpov15** [comment]
Step 1 is to put in a PR to the offending module to fix their code, that's bad practice on their part, but in case they're slow fixing this, I'll look into workarounds for mongoose. This is a good excuse to look into changing mongoose arrays to extend from native arrays using es6 extends, now that we dropped support for es5.

**Comment by vkarpov15** [comment]
Came up with a workaround, document arrays will use a `CoreMongooseArray` class that extends from `Array`, so clobbered array prototypes won't cause this issue anymore, at least with `remove()`. The `CoreMongooseArray` concept is very minimal right now because I want to make it easy to unwind this change in case it causes unforeseen issues. This change will be released with 5.1.2, ETA May 21.

**Comment by dickeylth** [comment]
I've encountered the same issue but with different error stack:

```
Details TypeError: Cannot assign to read only property 'remove' of object '[object Array]'
    at new MongooseArray (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/types/array.js:45:20)
    at SchemaArray.cast (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/schema/array.js:200:15)
    at SchemaArray.SchemaType.getDefault (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/schematype.js:710:25)
    at $__applyDefaults (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/document.js:322:22)
    at model.Document (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/document.js:104:3)
    at model.Model (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/model.js:90:12)
    at new model (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/model.js:4378:13)
    at Object.createModel (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/queryhelpers.js:130:10)
    at completeMany (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/helpers/query/completeMany.js:39:22)
    at http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/query.js:1750:9
    at Model.$wrapCallback (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/model.js:4529:16)
    at next (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/model.js:3557:5)
    at next (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/model.js:3691:7)
    at Model.$wrapCallback (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/model.js:4529:16)
    at (anonymous function).call (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/query.js:3800:7)
    at process.nextTick (http://midway/node_modules/_mongoose@5.3.12@mongoose/lib/helpers/query/completeMany.js:35:39)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I tried to debug and figured that the code at <https://github.com/Automattic/mongoose/blob/5.3.12/lib/types/array.js#L39> also may trigger the `Array.prototype.remove` issue.

**Comment by vkarpov15** [comment]
@dickeylth can you please provide some code samples and describe where you're running Mongoose? The `http://` in the stack trace makes me think you aren't running this in vanilla node
