### ISSUE TITLE
Bug: #document.populate() return parent id for empty result

### ISSUE THREAD

**Issue by lebinhchieu** [Automattic/mongoose#6435]
I got a bug on **#document.populate()**

I have two documents: Agent, CoopBrand and Product and relationship:
```
agent
|-- coopBrands (sub-doc)
    |-- products (doc)
```

Schemas:
```
// CoopBrand
const coopBrandSchema = new Schema({
    // ... Another fields
});
coopBrandSchema.virtual('products', {
    ref: 'Product',
    localField: '_id',
    foreignField: 'coopBrandId'
});

// Agent
const agentSchema = new Schema({
    coopBrands: {
        type: [coopBrandSchema]
    }
    // ... Another fields
});

// Product
const productSchema = new Schema({
    coopBrandId: {
        type: Schema.Types.ObjectId,
        index: true
    }
    // ... Another fields
});
```

The problem is:
- Get agents
`let agents = await Agent.find({});`
- Then populate products on 
```
for (let i in agents) {
    await agents[i].populate('coopBrands.products').execPopulate();
    for (let j = agents[i].coopBrands.length - 1; j >= 0; j--) {
        console.log(agents[i].coopBrands[j].products);
    }
}
```
- And this is what I got
```
[ { _id: 5ad85dd19dac2805c3241d8c,
    __v: 0 },
  { _id: 5aecb2ba8f54e9141276db68,
    coopBrandId: 5ad71f8f3d62240742456a42,
    __v: 0 } ]
[ 5ad7206abeedd907b111d02c ] // Problem here
```

The first `coopBrands[0].products` is fine
But the sencond `coopBrands[1].products` got problem. It didn't have any products, it contained `coopBrand._id` instead of `[]` (empty array)

**#Model.populate()** is okay (when I use `Agent.find({}).populate('coopBrands.products').exec())`

I am using
- mongoose@5.0.17
- node@8.11.1
- npm@5.6.0

Please check it. If the reason from me, please tell me know.
Thank you very much

**Comment by lineus** [comment]
@lebinhchieu I tried to put together a complete and reproducible example based on the information you provided.

### 6435.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const coopBrandSchema = new Schema({
  name: String
});

coopBrandSchema.virtual('products', {
  ref: 'Product',
  localField: '_id',
  foreignField: 'coopBrandId',
  justOne: false
});

const agentSchema = new Schema({
  coopBrands: {
    type: [coopBrandSchema]
  },
  name: String
});

const productSchema = new Schema({
  coopBrandId: {
    type: Schema.Types.ObjectId,
    index: true
  },
  name: String
});

const Agent = mongoose.model('Agent', agentSchema);
const Product = mongoose.model('Product', productSchema);

const billy = new Agent({
  name: 'Billy',
  coopBrands: [{ name: 'test1' }, { name: 'test2' }]
});

const sarah = new Agent({
  name: 'Sarah',
  coopBrands: [{ name: 'test3' }, { name: 'test4' }]
});

const product1 = new Product({
  coopBrandId: billy.coopBrands[0]._id,
  name: 'product1'
});

const product2 = new Product({
  coopBrandId: billy.coopBrands[1]._id,
  name: 'product2'
});

const product3 = new Product({
  coopBrandId: sarah.coopBrands[0]._id,
  name: 'product3'
});

const product4 = new Product({
  coopBrandId: sarah.coopBrands[1]._id,
  name: 'product4'
});

async function run() {
  await conn.dropDatabase();
  await Agent.create([billy, sarah]);
  await Product.create([
    product1,
    product2,
    product3,
    product4
  ]);

  let agents = await Agent.find({});
  for (let i in agents) {
    await agents[i].populate('coopBrands.products').execPopulate();
    for (let j = agents[i].coopBrands.length - 1; j >= 0; j--) {
      console.log(agents[i].coopBrands[j].products);
    }
  }
  return conn.close();
}

run();
```
### Outputs: 
```
issues: ./6435.js
[ { _id: 5af390caed4623755e31b330,
    coopBrandId: 5af390caed4623755e31b32b,
    name: 'product4',
    __v: 0 } ]
[ { _id: 5af390caed4623755e31b32f,
    coopBrandId: 5af390caed4623755e31b32c,
    name: 'product3',
    __v: 0 } ]
[ { _id: 5af390caed4623755e31b32e,
    coopBrandId: 5af390caed4623755e31b328,
    name: 'product2',
    __v: 0 } ]
[ { _id: 5af390caed4623755e31b32d,
    coopBrandId: 5af390caed4623755e31b329,
    name: 'product1',
    __v: 0 } ]
issues:
```

Can you compare this to your code and modify this example if necessary to demonstrate what you are seeing?

**Comment by lebinhchieu** [comment]
@lineus OK, let me do it.
Thanks for replying

**Comment by lebinhchieu** [comment]
@lineus I just update script, please see below

### Script

```javascript
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const coopBrandSchema = new Schema({
  name: String
});

coopBrandSchema.virtual('products', {
  ref: 'Product',
  localField: '_id',
  foreignField: 'coopBrandId',
  justOne: false
});

const agentSchema = new Schema({
  coopBrands: {
    type: [coopBrandSchema]
  },
  name: String
});

const productSchema = new Schema({
  coopBrandId: {
    type: Schema.Types.ObjectId,
    index: true
  },
  name: String
});

const Agent = mongoose.model('Agent', agentSchema);
const Product = mongoose.model('Product', productSchema);

const billy = new Agent({
  name: 'Billy',
  coopBrands: [{ name: 'Has product' }, { name: 'Has no product' }]
});

const product1 = new Product({
  coopBrandId: billy.coopBrands[0]._id,
  name: 'Product 1 for "Has product"'
});

const product2 = new Product({
  coopBrandId: billy.coopBrands[0]._id,
  name: 'Product 2 for "Has product'
});

async function run() {
  await conn.dropDatabase();
  await Agent.create(billy);
  await Product.create([
    product1,
    product2
  ]);

  let agents = await Agent.find({});
  for (let i in agents) {
    await agents[i].populate('coopBrands.products').execPopulate();
    for (let j = agents[i].coopBrands.length - 1; j >= 0; j--) {
      console.log(agents[i].coopBrands[j].products);
    }
  }
  return conn.close();
}

run();
```

### Output

```
[ 5af3d1dda797af047a6c61df ] # Look at this (for coop brand "Has no product" )
[ { _id: 5af3d1dda797af047a6c61e1,
    coopBrandId: 5af3d1dda797af047a6c61e0,
    name: 'Product 1 for "Has product"',
    __v: 0 },
  { _id: 5af3d1dda797af047a6c61e2,
    coopBrandId: 5af3d1dda797af047a6c61e0,
    name: 'Product 2 for "Has product',
    __v: 0 } ]
```

**Comment by lineus** [comment]
Here is a complete repro script that explicitly shows the expectation that document.populate and model.populate don't behave the same:

### 6435_2.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const coopBrandSchema = new Schema({
  name: String
});

coopBrandSchema.virtual('products', {
  ref: 'Product',
  localField: '_id',
  foreignField: 'coopBrandId',
  justOne: false
});

const agentSchema = new Schema({
  coopBrands: [coopBrandSchema],
  name: String
});

const productSchema = new Schema({
  coopBrandId: {
    type: Schema.Types.ObjectId,
    index: true
  },
  name: String
});

const Agent = mongoose.model('Agent', agentSchema);
const Product = mongoose.model('Product', productSchema);

const billy = new Agent({
  name: 'Billy',
  coopBrands: [
    { name: 'Has product' }, 
    { name: 'Has no product' }
  ]
});

const product1 = new Product({
  coopBrandId: billy.coopBrands[0]._id,
  name: 'Product 1 for "Has product"'
});

const product2 = new Product({
  coopBrandId: billy.coopBrands[0]._id,
  name: 'Product 2 for "Has product'
});

async function docPop() {
  let agent = await Agent.findOne({});
  return agent.populate(
    'coopBrands.products', 
    'name -_id'
  ).execPopulate();
}

function modelPop() {
  return Agent.findOne({}).populate('coopBrands.products');
}

async function run() {
  await conn.dropDatabase();
  await Agent.create(billy);
  await Product.create([
    product1,
    product2
  ]);

  let doc = await docPop();
  let mod = await modelPop();

  assert.strictEqual(
    doc.coopBrands[1].products, 
    mod.coopBrands[1].products
  );

  return conn.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return conn.close();
}
```
### Output: 
```
issues: ./6435_2.js
{ AssertionError [ERR_ASSERTION]: [ 5af419979f9c958841088dae ] === []
    at run (/Users/lineus/dev/Help/mongoose5/issues/6435_2.js:78:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: [ 5af419979f9c958841088dae ],
  expected: [],
  operator: '===' }
issues:
```
Thanks @lebinhchieu!

**Comment by lebinhchieu** [comment]
@lineus Thank you, hope to be fixed soon
