### ISSUE TITLE
RefPath problem in embedded schema when no items in array

### ISSUE THREAD

**Issue by valterkraemer** [Automattic/mongoose#6457]
When `references` in `post2` is commented out I get the following error: `Schema hasn't been registered for model ""`

```
const mongoose = require('mongoose');
mongoose.Promise = Promise
const Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/test');

const CommentSchema = new Schema({
  text: String,
  references: {
    type: [{
      item: {
        type: Schema.Types.ObjectId,
        refPath: 'comments.references.kind'
      },
      kind: {
        type: String,
        enum: ['Post', 'Comment']
      }
    }]
  }
});

const PostSchema = new Schema({
  text: String,
  comments: [CommentSchema]
});

const Post = mongoose.model('Post', PostSchema);

const post1 = {
  _id: mongoose.Types.ObjectId(),
  text: 'Post 1'
};

const post2 = {
  _id: mongoose.Types.ObjectId(),
  text: 'Post 2',
  comments: [{
    text: 'Comment',
    // references: [{
    //   item: post1._id,
    //   kind: 'Post'
    // }]
  }]
};

Post.remove()
  .then(() => Post.create([post1, post2]))
  .then(() => {
    return Post.findById(post2._id)
      .populate('comments.references.item')
  })
  .then(post => {
    console.log('references', post.comments[0].references);
  })
  .catch(err => {
    console.log('error', err);
  })
```

Gives the error:
```
MissingSchemaError: Schema hasn't been registered for model "".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at NativeConnection.Connection.model (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/connection.js:702:11)
    at getModelsMapForPopulate (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/model.js:3684:20)
    at populate (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/model.js:3218:15)
    at _populate (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/model.js:3186:5)
    at utils.promiseOrCallback.cb (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/model.js:3159:5)
    at Object.promiseOrCallback (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/utils.js:211:14)
    at Function.Model.populate (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/model.js:3158:16)
    at model.Query.Query._completeOne (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/query.js:1497:9)
    at Immediate.Query.base.findOne.call (/Users/valter/Development/mongoose-boilerplate/node_modules/mongoose/lib/query.js:1532:10)
    at Immediate._onImmediate (/Users/valter/Development/mongoose-boilerplate/node_modules/mquery/lib/utils.js:119:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  message: 'Schema hasn\'t been registered for model "".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
```

Mongoose: 5.1.0
MongoDB: 3.6.3
Node: 8.9.4

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap
