### ISSUE TITLE
?retryWrites=true causes "cyclic dependency detected" error

### ISSUE THREAD

**Issue by thaoula** [Automattic/mongoose#6469]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I am trying to add retryWrites to an existing connection string. My connection string looks like  'mongodb://mongo/app?retryWrites=true' 

After do this, my application started crashing with 'cyclic dependency detected' errors.

/home/app/node_modules/mongoose/lib/utils.js:429
        throw err;
        ^
2018-05-14T05:13:00.906964500Z 
Error: cyclic dependency detected
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:331:34)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:724:17)
    at serializeObject (/home/app/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/home/app/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at BSON.serialize (/home/app/node_modules/bson/lib/bson/bson.js:63:28)
    at Query.toBin (/home/app/node_modules/mongodb-core/lib/connection/commands.js:144:25)
    at serializeCommands (/home/app/node_modules/mongodb-core/lib/connection

When I check the database I see only a single collection is created. I have gone through the code looking for cyclic dependencies and I cannot find any. I finally track the issue down to adding retryWrites to the connection string.

We do not have this same issue when connecting to Atlas with this option specified.

Does this option require a replica set? In development, our app is connecting to a single mongodb server running as a docker container

**If the current behavior is a bug, please provide the steps to reproduce.**

1. add retryWrites to a connection.
2. start the node application and it will crash with cyclic dependency detected.
3. Removing the retryWrites=true will allow application to work as normal.

**What is the expected behavior?**
The application will connect and does not throw an error.

**Please mention your node.js, mongoose and MongoDB version.**
I am using the following 
Node 10
Mongoose 5.1.0
Mongo DB 3.6.4
Docker for Mac

**Comment by thaoula** [comment]
Requires replicaset

**Comment by vkarpov15** [comment]
@thaoula what was the issue?

**Comment by karthikiyengar** [comment]
I can confirm that a cyclic dependency error is indeed being returned with `retryWrites=true` on an Atlas replica set. Here were the additional options that I had provided to `mongoose.connect`

```javascript
{
    keepAlive: 1,
    reconnectTries: Number.MAX_VALUE
}
```

Strangely enough, I am able to connect perfectly fine without these options.

**Comment by wwwy3y3** [comment]
+1. Same issue with @karthikiyengar here. Using `retryWrites=true` with mongo atlas causes this error.

**Comment by lineus** [comment]
@wwwy3y3 what version of mongoose are getting this error with?

**Comment by vkarpov15** [comment]
This issue should be fixed with 5.1.8 and 5.2.0. Please upgrade and open up a new issue if the issue persists.
