### ISSUE TITLE
Index violation throws Error that causes app to crash

### ISSUE THREAD

**Issue by lafama** [Automattic/mongoose#6536]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?**
My collection has items that violate a unique index (added before the index was created). This was working in 4.x (Would produce a log message not throw and error on the same) but in version 5.1.3 produces the following error during startup
```

schema.index({'xxx':1,'xxxB':1},{unique:true,partialFilterExpression:{'xxxB':{$exists:true}}})
  

/Users/xxxxx/projectPath/node_modules/mongoose/lib/utils.js:440
        throw err;
MongoError: E11000 duplicate key error collection: db.collectionname index: xxx_1_xxx_1 dup key: { : ObjectId('xxxxxxxxxxxxxxxxxx'), : null }
    at /Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:598:61
    at authenticateStragglers (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:516:16)
    at Connection.messageHandler (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:552:5)
    at emitMessageHandler (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at TLSSocket.<anonymous> (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at TLSSocket.Readable.push (_stream_readable.js:217:10)
    at TLSWrap.onread (net.js:638:20)
Emitted 'error' event at:
    at done (/Users/xxxxx/projectPath/node_modules/mongoose/lib/model.js:1068:13)
    at /Users/xxxxx/projectPath/node_modules/mongoose/lib/model.js:1110:16
    at /Users/xxxxx/projectPath/node_modules/mongoose/lib/utils.js:435:16
    at err (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)
    at session.endSession (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:399:27)
    at ClientSession.endSession (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb-core/lib/sessions.js:72:41)
    at executeCallback (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:397:17)
    at err (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)
    at executeCallback (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:404:25)
    at err (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)
    at executeCallback (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:404:25)
    at handleCallback (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/db.js:1054:14
    at handleCallback (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/db.js:1626:21
    at err (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)
    at executeCallback (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:404:25)
    at handleCallback (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb/lib/db.js:335:21
    at operation.cb (/Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:1264:37)
    at /Users/xxxxx/projectPath/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:544:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Application has crashed!
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I think producing a log message or a way to catch It and still re-create the index would be ideal. I have also tried this
```
var xx = mongoose.model('xx');

    xx.on('index', function(error) {
      // "_id index cannot be sparse"
      console.log(error.message);
    });
```
**Please mention your node.js, mongoose and MongoDB version.**
```
node v10.1.0
mongodb v3.6.5
mongoosejs 5.1.3
```

**Comment by lafama** [comment]
I Believe this is not possible with mongodb
```
Restrictions
MongoDB cannot create a unique index on the specified index field(s) if the collection 
already contains data that would violate the unique constraint for the index.
```
[https://docs.mongodb.com/manual/core/index-unique/#restrictions](https://docs.mongodb.com/manual/core/index-unique/#restrictions)
