### ISSUE TITLE
RangeError: Maximum call stack size exceeded  (mongoose 5.0.16, node 8.10.0)

### ISSUE THREAD

**Issue by fider** [Automattic/mongoose#6540]
Same as here, but different scenario:
https://github.com/Automattic/mongoose/issues/5480

But error still occurs in using:
Mongoose v**5.0.16**
Node v**8.10.0**

This may be useful while fixing issue:
https://stackoverflow.com/questions/24466366/mongoose-rangeerror-maximum-call-stack-size-exceeded

**My code:**
```javascript
fieldsToSet = {
    data: [someClassInstance1, someClassInstance2]
};
conditions = { _id: ..., someFiled: ... }
...
// WHERE there can be another field with 2 possible values:
// 1)
conditions.$or = [
    { updateCount: { $exists: false } },
    { updateCount: { $eq: "0", $exists: true } }
];
// 2)
conditions.updateCount = 2; // or any other number
...
await myCollection.findOneAndUpdate(
    conditions,
    fieldsToSet,
    { new: true }  // Return modified document
).exec();
```

**Root cause here might be `someClassInstance` - it is TypeScript class transpiled to "target":"ES2016".**
**When i will change whole `fieldsToSet` object to Plain Old Javascript Object then problem do not occurs:**
```javascript
fieldsToSet = JSON.parse( JSON.stringify(fieldsToSet ) );
```

ES2016 have "class" syntax so I assume that with plain JS and "class" problem also occurs.

Log:
RangeError: Maximum call stack size exceeded
    at clone (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\utils.js:153:31)
    at EmbeddedDocument.Document.$toObject (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\document.js:2131:5)
    at EmbeddedDocument.Document.toObject (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\document.js:2339:15)
    at C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\types\documentarray.js:214:25
    at Array.map (<anonymous>)
    at Array.toObject (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\types\documentarray.js:213:17)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:20:31)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)

**Comment by lineus** [comment]
@fider can you please provide a code sample that demonstrates the issue?

**Comment by fider** [comment]
@lineus sorry, I edited something and not saved code before. Here it is

**Comment by lineus** [comment]
@fider Thanks for adding more info. Can you replace the class, schema, and behavior in this example with the ones from your code such that it demonstrates the error? 

### 6540.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

class Sub {
  constructor(x, y) {
    this.x = x;
    this.y = y;
  }
}

const sub = new Schema({
  x: String,
  y: Number
});

const schema = new Schema({
  updateCount: Number,
  data: [sub]
});

const Test = mongoose.model('test', schema);

const test = new Test;

async function run() {
  await conn.dropDatabase();
  await test.save();
  const cond = { 
    _id: test._id,
    $or: [
      { updateCount: { $exists: false } },
      { updateCount: { $eq: 0, $exists: true } }
    ]
  };
  const fieldData = new Sub('womp', 42);
  const update = { data: [fieldData], $inc: { updateCount: 1 } };
  const opts = { new: true };
  const updated = await Test.findOneAndUpdate(cond, update, opts);
  console.log(updated);
  return conn.close();
}

run();
```
### Output:
```sh
issues: ./6540.js
{ data: [ { x: 'womp', y: 42, _id: 5b13be753dc7e725009ecee7 } ],
  _id: 5b13be753dc7e725009ecee6,
  __v: 0,
  updateCount: 1 }
issues:
```

**Comment by fider** [comment]
Hi again.

My whole codebase is too big to paste it here but here is what I got.

1) I am still unable to reproduce error out of my project (in separate script).
2) Below you have more complete info from debugger so please take a look at this if you will find a moment:

Table of contents:
a) More details.
b) First call of `flatten` and its arguments.
c) Root cause of infinite recursive call:
d) Complete stack trace.

**a) More details:**
`fieldsToUpdate` object contains array of `EmbeddedDocument` objects, taken from another query result.
Funtion `findOneAndUpdate` is called with this `fieldsToUpdate` object.
Then internally `flatten` from common.js is called and there infinite recursive calls occurs.
** !! What I noticed is:**
1. Function `findOneAndUpdate` is called by me with `fieldsToUpdate` as second argument and:
`fieldsToUpdate.data[0] instanceof mongoose.Document  === true`
2. Function `flatten` is called internally by mongoose with `update` as first argument and:
`update.data[0] instanceof mongoose.Document  === false`
This second fact determines infinite recursive call (more details in point C ).


**b) First call of `flatten` and its arguments:**

flatten(update, path, options)
```javascript
// update argument:
Object {data: Array(1), keyId: "31647a3b-6a38-4614-b743-dbdc3e063c81--2018-06-04", type: "1"}
```

**This thing is important - EmbeddedDocument.**  
```javascript
// Where update.data:    
Array(1) [EmbeddedDocument, …]

// Where update.data[0]
EmbeddedDocument {__parentArray: Array(1), __parent: undefined, __index: 0, …}
__index:0
__parent:undefined
__parentArray:Array(1) [EmbeddedDocument, …]
_doc:Object {name: "a", value: "ykiQJl69WlaR0fjwowThLw==", iv: "UJ/MsTG/Hn7c1Yfdh74ULg=="}
$__:InternalCache {strictMode: true, selected: undefined, shardval: undefined, …}
$init:true
errors:undefined
id:null
isNew:false
iv:"UJ/MsTG/Hn7c1Yfdh74ULg=="
name:"a"
value:"ykiQJl69WlaR0fjwowThLw=="
__proto__:EmbeddedDocument {name: <accessor>, value: <accessor>, iv: <accessor>, …}

// path argument
undefined

// options argument
undeifned
```

**c) Root cause of infinite recursive call:**
Go to `flatten` in lib/services/common.js.
In second recursive call (third call) the `update` object is not properly recognized (here the`update` argument is in fact the `update.data[0]` of first `flatten` call). It is not properly recognized by function `utils.isMongooseObject` - it returns `undefined` (somehow `update.data[0]` is **not** instanceof `Document`). This causes that `keys` is taken from `keys = Object.keys(update || {})` so `__parentArray` key is listed in below loop and next `flatten` recursive call is called with this `__parentArray`.


**d) Complete stack trace (top to bottom):**
RangeError: Maximum call stack size exceeded
    at isSymbol (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lodash.get\index.js:871:18)
    at isKey (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lodash.get\index.js:558:24)
    at baseGet (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lodash.get\index.js:458:10)
    at get (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lodash.get\index.js:927:45)
    at EmbeddedDocument.Document.$toObject (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\document.js:2154:5)
    at EmbeddedDocument.Document.toObject (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\document.js:2339:15)
    at C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\types\documentarray.js:214:25
    at Array.map (<anonymous>)
    at Array.toObject (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\lib\types\documentarray.js:213:17)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:20:31)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
**[...] common.js:37:18 [...]**
    at flatten (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\common.js:37:18)
    at module.exports (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\services\updateValidators.js:53:18)
    at model.Query.Query._findAndModify (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\query.js:2328:20)
    at model.Query.Query._findOneAndUpdate (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\lcp-cs-utilities\node_modules\mongoose\lib\query.js:2152:8)
    at process.nextTick (C:\Users\wfide\work\Lenovo\repos\lcp-cs-vault\node_modules\mongoose\node_modules\kareem\index.js:311:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by fider** [comment]
I have one more thing :)
First read above comment, then what is below:

In first call of `flatten` function I can see that `update.data[0] instanceof mongoose.Document === true` but on the third call (second recursive call) we are calling `utils.isMongooseObject(update)` -> inside of this function `v instanceof Document` is `false` (just like local `Document` in this function is different than `mongoose.Document`

**Comment by fider** [comment]
Problem solved:
- I had different version of mongoose in dependent project, so module A created object that extends A.mongoose**V1**.Document and module B processed this object and evaluates internally something like A.mongoose**V1**.Document to B.mongoose**V2**.Document (that obviously are different objects, from two different modules).

@lineus thank you for your time!

**Comment by lineus** [comment]
I'm glad you sorted it out @fider, I tried several times to reproduce it but couldn't, now I know why! Nice job 👍
