### ISSUE TITLE
RangeError: Maximum call stack size exceeded when using $set

### ISSUE THREAD

**Issue by sibelius** [Automattic/mongoose#6580]
I have the following code that throws a Maximum call stack size exceeded:

```jsx
await MyModel.update({ user, company }, { $set: { readAt: new Date() } }, { multi: true });
```

```jsx
[ { line: 2, column: 3 } ]
RangeError: Maximum call stack size exceeded
    at Array.slice (<anonymous>)
    at model.$set (myserver/node_modules/mongoose/lib/document.js:792:23)
    at Document.set [as zipcode] (myserver/node_modules/mongoose/lib/services/document/compile.js:129:26)
    at merge (myserver/node_modules/mongoose/lib/utils.js:340:15)
    at merge (myserver/node_modules/mongoose/lib/utils.js:345:7)
    at merge (myserver/node_modules/mongoose/lib/utils.js:345:7)
    at merge (myserver/node_modules/mongoose/lib/utils.js:345:7)
    at merge (myserver/node_modules/mongoose/lib/utils.js:345:7)
    at merge (myserver/node_modules/mongoose/lib/utils.js:345:7)
    at merge (myserver/node_modules/mongoose/lib/utils.js:345:7)
    at merge (myserver/node_modules/mongoose/lib/utils.js:345:7)
    at merge (myserver/node_modules/mongoose/lib/utils.js:345:7)
```

it looks like there is a recursive problem on  `merge`

my model:

```jsx
const Schema = new mongoose.Schema(
  {
    company: {
      type: ObjectId,
      ref: 'Company',
      required: true,
      index: true,
    },
    user: {
      type: ObjectId,
      ref: 'User',
      index: true,
      required: false,
    },
    readAt: {
      type: Date,
      default: null
    },
  },
  {
    collection: 'mymodel',
    timestamps: {
      createdAt: 'createdAt',
      updatedAt: 'updatedAt',
    },
  },
);
```

**Comment by lineus** [comment]
@sibelius I tried to replicate your issue with the following code but I don't get the error on mongoose@5.1.5. What versions of mongoose, node, and mongodb are you using?

### 6580.js
```js
#!/usr/bin/env node
'use strict';
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;
const ObjectId = Schema.Types.ObjectId;

const schema = new Schema({
  company: {
    type: ObjectId,
    ref: 'Company',
    required: true,
    index: true,
  },
  user: {
    type: ObjectId,
    ref: 'User',
    index: true,
    required: false,
  },
  readAt: {
    type: Date,
    default: null
  },
},
{
  collection: 'mymodel',
  timestamps: {
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
  },
},
);

const MyModel = mongoose.model('mymodel', schema);

const companySchema = new Schema({
  name: String
});

const Company = mongoose.model('Company', companySchema);

const userSchema = new Schema({
  name: String
});

const User = mongoose.model('User', userSchema);

const user = new User({ name: 'Billy' });
const company = new Company({ name: 'someCo'});

const test = new MyModel({
  company: company._id,
  user: user._id
});

async function run() {
  await conn.dropDatabase();
  await user.save();
  await company.save();
  await test.save();
  let cond = { user, company };
  let update = { $set: { readAt: new Date() } };
  let opts = { multi: true };
  await MyModel.update(cond, update, opts);
  let doc = await MyModel.findOne({});
  console.log(doc);
  return conn.close();
}

run();
```

### Output:
```
issues: ./6580.js
{ readAt: 2018-06-14T10:37:34.559Z,
  _id: 5b22456e244d121881cb6c74,
  company: 5b22456e244d121881cb6c73,
  user: 5b22456e244d121881cb6c72,
  createdAt: 2018-06-14T10:37:34.553Z,
  updatedAt: 2018-06-14T10:37:34.562Z,
  __v: 0 }
issues:
```

**Comment by sibelius** [comment]
maybe it only happens when there a lot of itens on the database

we migrate to this one

```
await MyModel.collection.updateMany(
      { user: user._id, company: company._id, readAt: null },
      { $set: { readAt: new Date() } },
);
```

we tried this on node 8/10
"mongoose": "5.1.4",
mongodb: stable 3.6.5 (bottled)

we gonna try again with 5.1.5

tks

**Comment by sibelius** [comment]
We are having this issue again, we think this only happens when we have an embedded document that causes a circular dependency

so we have an `User` model that has a `FileSchema` embedded that represents the `logo` of her/his image, and inside `FileSchema` we have the `user` that uploaded this file, so this created a maximum call stack size

**Comment by vkarpov15** [comment]
@sibelius can you provide code samples please?

**Comment by sibelius** [comment]
I think we found the problem, we were passing an Object instead of a Mongoose Object to updateMany, moving to ObjectId or Mongoose Object it solved for us
