### ISSUE TITLE
parse string representation of booleans for mongodb operators such as $exists

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#6581]
Currently, mongoose doesn't parse string representation of booleans when it comes to MongoDB operators that use a boolean.

One of the use cases here would be receiving the query as a querystring in the HTTP request, which doesn't automatically parse string representation of booleans as booleans, and I believe we're already parsing string representation of numbers for things like `$gt` .

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

const userSchema = new Schema({ name: String });

const User = mongoose.model('User', userSchema);

mongoose.connect('mongodb://localhost/test');

let user = new User({ name: 'Hafez' });

const run = async () => {
  await user.save();

  let foundUser = await User.findOne({ name: { $exists: 'true' } });

  assert.ok(foundUser);
};

run().catch(console.error);
```

output
```
Error: $exists parameter must be a boolean!
    at SchemaString.module.exports (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\schema\operators\exists.js:9:11)
    at SchemaString.castForQuery (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\schema\string.js:508:20)
    at SchemaString.SchemaType.castForQueryWrapper (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\schematype.js:1077:17)
    at cast (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\cast.js:281:39)
    at model.Query.Query.cast (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\query.js:3319:12)
    at model.Query.Query._castConditions (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\query.js:1293:10)
    at model.Query.Query._findOne (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\query.js:1518:8)
    at process.nextTick (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\kareem\index.js:333:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Would also be nice if mongoose parses numbers to their string representation when text searching.

```js
const mongoose = require('mongoose');
const assert = require('assert');
const { Schema } = mongoose;

mongoose.connect('mongodb://localhost/test');

const userSchema = new Schema({ zipCode: String });

userSchema.index({ zipCode: 'text' });

const User = mongoose.model('User', userSchema);

let user = new User({ zipCode: '1234' });
let anotherUser = new User({ zipCode: 'A2345' })

const run = async () => {
  await user.save();

  let foundUser = await User.findOne({ $text: { $search: 1234 } });
  
  assert.ok(foundUser);
};

run().catch(console.error);
```

output:
```
{ MongoError: "$search" had the wrong type. Expected String, found NumberInt32
    at queryCallback (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\node_modules\mongodb-core\lib\cursor.js:244:25)
    at E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:544:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
  name: 'MongoError',
  message:
   '"$search" had the wrong type. Expected String, found NumberInt32',
  waitedMS: 0,
  ok: 0,
  errmsg:
   '"$search" had the wrong type. Expected String, found NumberInt32',
  code: 14 }
```

The idea is that we become more flexible with the types, so that queries coming from different sources can work flawlessly.

MongoDB v3.2.7
mongoose v5.1.4

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP.

**Comment by vkarpov15** [comment]
Fixed with https://github.com/Automattic/mongoose/commit/3b345be86763b6c8580e5a3748b046b42b5e4227 and https://github.com/Automattic/mongoose/commit/782faefdf116eb9ea27695191b34cbf6cbacbfa5, I typoed the issue number in the commit message. Fix will be in 5.1.6, ETA June 18.

**Comment by AbdelrahmanHafez** [comment]
Will we be parsing string representation of numbers in $text search as well?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez I don't understand the question, can you please clarify?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez yep we added a test case for that in https://github.com/Automattic/mongoose/commit/782faefdf116eb9ea27695191b34cbf6cbacbfa5
