### ISSUE TITLE
Pushing an object into a triple-nested array makes mongoose crash

### ISSUE THREAD

**Issue by mpsijm** [Automattic/mongoose#6602]
**Do you want to request a *feature* or report a *bug*?** Bug :bug: 

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**
Pushing an object into a triple-nested array makes mongoose crash. This is a follow-up of #6398, where pushing into a double-nested array was broken. Standalone example:
```javascript
var mongoose = require("mongoose");

var model = mongoose.model("TestModel", new mongoose.Schema({
	name: String,
	array: [[[{key: String, value: Number}]]]
}));

mongoose.connect("mongodb://localhost/test");

mongoose.connection.on("connected", async () => {
	await new model({name: "small", array: [[[
		{key: "answer", value: 42}
	]]]}).save();
	var doc = await model.findOne().exec();
	doc.array[0][0].push({key: "lucky", value: 7});
	process.exit(0);
});
```

This throws a TypeError at the same location as in #6398:
```
(node:30250) UnhandledPromiseRejectionWarning: TypeError: Right-hand side of 'instanceof' is not callable
    at Array._cast (/home/mpsijm/tmp/mongoose-test/node_modules/mongoose/lib/types/documentarray.js:122:15)
    at Array._mapCast (/home/mpsijm/tmp/mongoose-test/node_modules/mongoose/lib/types/array.js:302:17)
    at Arguments.map (<anonymous>)
    at Array.push (/home/mpsijm/tmp/mongoose-test/node_modules/mongoose/lib/types/array.js:316:25)
    at NativeConnection.mongoose.connection.on (/home/mpsijm/tmp/mongoose-test/index.js:15:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**What is the expected behavior?**
The document should be updated without throwing a TypeError.

**Please mention your node.js, mongoose and MongoDB version.**
```
$ grep mongoose package.json
    "mongoose": "^5.1.5"
$ node --version
v9.11.2
$ mongo --version
MongoDB shell version v3.6.5
git version: a20ecd3e3a174162052ff99913bc2ca9a839d618
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
```

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP.
