### ISSUE TITLE
Model Instances don't have access to their methods

### ISSUE THREAD

**Issue by Eksapsy** [Automattic/mongoose#6628]
- [ ] Feature
- [x] Bug

**What is the current behavior?**
Using the exact example in the docs, I wasn't able to get access to the model's static or non static methods.
[Docs](http://mongoosejs.com/docs/guide.html)
Error:
```bash
(node:7969) UnhandledPromiseRejectionWarning: TypeError: Animal.meow is not a function
    at _callee$ (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/index.js:41:10)
    at tryCatch (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/index.js:71:191)
    at /home/eksapsy/Desktop/JavaScript/.temp/bcrypt/index.js:71:437
    at new Promise (<anonymous>)
    at /home/eksapsy/Desktop/JavaScript/.temp/bcrypt/index.js:71:99
    at run (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/index.js:53:17)
    at Object.<anonymous> (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/index.js:44:1)
    at Module._compile (module.js:662:30)
    at loader (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/eksapsy/Desktop/JavaScript/.temp/bcrypt/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
(node:7969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7969) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Mongoose: animals.insertOne({ _id: ObjectId("5b336e71ca33621f21c59d6d"), name: 'fluff', type: 'cat', __v: 0 })
{ _id: 5b336e71ca33621f21c59d6d,
  name: 'fluff',
  type: 'cat',
  __v: 0 }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I used this code
```javascript
const animalSchema = new Schema({
    name: {
      type: String,
      required: false
    },
    type: {
      type: String,
      required: true
    }
  });

  animalSchema.statics.sayMow = function() {
    console.log('meeeeeoooooooooooow');
  }
  animalSchema.methods.meow = function () {
    console.log('meeeeeoooooooooooow');
  }
  
  const Animal = mongoose.model('Animal', animalSchema);

  const cat = new Animal({ name: 'fluff', type: 'cat' });

  cat.meow();    // Doesn't work
  Animal.sayMow(); // Doesn't work either
```

**What is the expected behavior?**
The methods should work when used from the instance and the static methods should work when used directly from the Model.

Is there any way to get around this?

**Please mention your node.js, mongoose and MongoDB version.**
```bash
nodejs --version
v8.10.0
 yarn info mongoose version
5.1.7
mongod --version            
db version v3.6.5
```

# UPDATE
My bad. The code I used was not exactly the same with the docs.
I had a `.save()` which I expected to return the instance itself. 

## Solution:
The solution is to not use `.save()` exactly in the instantiation.
```javascript
const cat = new Animal({type: "cat"});
cat.save();
cat.meow();
```

**Comment by lineus** [comment]
@Eksapsy In your code sample:
   1) cat is a pending promise when you call `.meow()`
   1) instance methods like `.meow()` in this case only exist on docs, so `Animal.meow()` shouldn't work

This can be seen with a `console.log()` statement:
### 6628.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const animalSchema = new Schema({
  name: {
    type: String,
    required: false
  },
  type: {
    type: String,
    required: true
  }
});

animalSchema.statics.sayMow = function () {
  console.log('meeeeeoooooooooooow');
};
animalSchema.methods.meow = function () {
  console.log('meeeeeoooooooooooow');
};


const Animal = mongoose.model('Animal', animalSchema);

const cat = new Animal({ name: 'fluff', type: 'cat' }) // changed this line.
  .save()
  .then(console.log)
  .then(() => {
    return conn.close();
  });
console.log(cat);
cat.meow();    // Doesn't work
Animal.meow(); // Doesn't work either
```
### Output:
```
issues: ./6628.js
Promise { <pending> } // this is cat's value when you call .meow()
/Users/lineus/dev/Help/mongoose5/issues/6628.js:37
cat.meow();    // Doesn't work
    ^

TypeError: cat.meow is not a function
    at Object.<anonymous> (/Users/lineus/dev/Help/mongoose5/issues/6628.js:37:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
issues:
```

## If you change your code slightly to:

### 6628.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const animalSchema = new Schema({
  name: {
    type: String,
    required: false
  },
  type: {
    type: String,
    required: true
  }
});

animalSchema.statics.sayMow = function () {
  console.log('meeeeeoooooooooooow');
};

animalSchema.methods.meow = function () {
  console.log('meeeeeoooooooooooow');
};


const Animal = mongoose.model('Animal', animalSchema);

new Animal({ name: 'fluffy', type: 'cat' })
  .save()
  .then((cat) => {
    cat.meow();
    Animal.sayMow();
  })
  .then(() => {
    return conn.close();
  });
```
### Output:
```
issues: ./6628.js
meeeeeoooooooooooow
meeeeeoooooooooooow
issues:
```

I'm pretty consistently hanging out in both of these chats:
[Gitter.im](https://gitter.im/Automattic/mongoose)
[Slack](https://mongoosejsteam.slack.com/)

Feel free to join either one and ping me anytime.
