### ISSUE TITLE
Error cannot find module mongoose please help

### ISSUE THREAD

**Issue by mirakuhl** [Automattic/mongoose#663]
C:\Users\Nick\Desktop\turntablefm\Bots\Super Bot>node bot.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'mongoose'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (C:\Users\Nick\Desktop\turntablefm\Bots\Super Bot\db.j
s:1:78)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)

i just used npm install mongoose it all worked fine but i get this error when using node any ideas thanks in advance

**Comment by lalehsbr** [comment]
The same problem here,
yes it is in node_modules directory

**Comment by lineus** [comment]
@lalehsbr This is probably an issue with your environment, can you join us in one of these communities so that we can help you out in real time:

[Gitter.im](https://gitter.im/Automattic/mongoose)
[Slack](https://mongoosejsteam.slack.com/)
