### ISSUE TITLE
Unhandled Exception: `TypeError: doc.toObject is not a function`

### ISSUE THREAD

**Issue by dbellavista** [Automattic/mongoose#6635]
**BUG**

When editing an existing document with an array. If I add a new element inside the array, but the `.save()` fails for another reason, then any consecutive fail will throw an unhandled exception:

```
/project/node_modules/mongoose/lib/types/documentarray.js:235
      return doc && doc.toObject(options) || null;
                        ^

TypeError: doc.toObject is not a function
    at /project/node_modules/mongoose/lib/types/documentarray.js:235:25
    at Array.map (<anonymous>)
    at Array.toObject (/project/node_modules/mongoose/lib/types/documentarray.js:234:17)
    at CoreMongooseArray.$__getAtomics (/project/node_modules/mongoose/lib/types/array.js:261:35)
    at handleAtomics (/project/node_modules/mongoose/lib/model.js:480:11)
    at model.Model.$__delta (/project/node_modules/mongoose/lib/model.js:601:7)
    at model.Model.$__handleSave (/project/node_modules/mongoose/lib/model.js:197:24)
    at model.Model.$__save (/project/node_modules/mongoose/lib/model.js:243:8)
    at /project/node_modules/kareem/index.js:278:20
    at _next (/project/node_modules/kareem/index.js:102:16)
    at process.nextTick (/project/node_modules/kareem/index.js:452:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

This gist will reproduce the error: https://gist.github.com/dbellavista/46df766acc09695f448be339ca96632e

**Please mention your node.js, mongoose and MongoDB version.**

Node 10 and 8.11, mongoose 5.1.6, mongoDB 3.4 and 3.6.

**Comment by evanhenke** [comment]
@dbellavista this should be fixed in 5.1.8, can you update and try again?

**Comment by dbellavista** [comment]
@evanhenke I tried with 5.2.0 and it works. However I had to modify the connection string due to #6647

**Comment by vkarpov15** [comment]
Glad it works :+1:

**Comment by evanhenke** [comment]
Sounds good!  Can you close the issue when you get the chance?

**Comment by bornagainraj7** [comment]
I'm getting the same error even in 5.5.2

**Comment by vkarpov15** [comment]
@bornagainraj7 please open a separate issue with code samples and follow the issue template.
