### ISSUE TITLE
Mongoose 5.2.0 fails to connect to an URL which specifies a DNS SRV record

### ISSUE THREAD

**Issue by ivanpadalko** [Automattic/mongoose#6656]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Mongoose returns an error when attempting to connect to an URL of the likes of: `mongodb+srv://username:password@host/database`

Error message:
```
{ MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name
    at connectCallback (/var/app/current/node_modules/mongodb/lib/operations/mongo_client_ops.js:236:23)
    at process.nextTick.err (/var/app/current/node_modules/mongodb/lib/operations/mongo_client_ops.js:436:7)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'MongoError',
  message: 'seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name' }
```
Possibly related to the issue: https://github.com/Automattic/mongoose/issues/6651

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');

mongoose.connect('mongodb+srv://user:password@host/database');
```

**What is the expected behavior?**

Mongoose should connect normally to this URL

**Please mention your node.js, mongoose and MongoDB version.**
Node: 9.11.1
Mongoose: 5.2.0
MongoDB: 3.6

**Comment by lineus** [comment]
I was able to verify that this is due to the same bug as #6651 with the following script that uses the native driver directly:
### 6656_native.js
```js
#!/usr/bin/env node --no-deprecation
'use strict';

const { ATLASSRV } = require('/Users/lineus/.env');
const sharable = ATLASSRV
  .replace(/[\w]+:[\w]+@/, 'xxx:yyy@')
  .replace(/[a-z0-9.]+mon/, 'host.mon');

console.log(sharable);
const { MongoClient } = require('mongodb');
const dbName = 'test';
const colName = 'test';

let unup = false;
if (process.argv[2] === 'true') {
  unup = true;
}

MongoClient.connect(ATLASSRV, { useNewUrlParser: unup })
  .then((client) => {
    return client.db(dbName);
  })
  .then((db) => {
    return db.createCollection(colName);
  })
  .then((col) => {
    return col.insertOne({ test: 'hello world' });
  })
  .then((res) => {
    console.log(res.result);
    process.exit(0);
  })
  .catch((err) => {
    console.error(err.message);
    process.exit(1);
  });

```
### running with a falsey value for `useNewUrlParser`:
the code works
```
6656: ./6656_native.js
mongodb+srv://xxx:yyy@cluster0-host.mongodb.net/test?retryWrites=true
{ n: 1,
  opTime:
   { ts: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1530639319 },
     t: 5 },
  electionId: 7fffffff0000000000000005,
  ok: 1,
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1530639319 },
  '$clusterTime':
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1530639319 },
     signature: { hash: [Object], keyId: [Object] } } }
```
### running with a truthy value for `useNewUrlParser`:
the code fails
```
6656: ./6656_native.js true
mongodb+srv://xxx:yyy@cluster0-host.mongodb.net/test?retryWrites=true
seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name
``` 
### Installing the patched version of the native driver:
both the old and new url parsers handle the srv connection string correctly:
```
6656: npm install https://github.com/mongodb/node-mongodb-native.git >/dev/null 2>&1
6656: ./6656_native.js
mongodb+srv://xxx:yyy@cluster0-host.mongodb.net/test?retryWrites=true
{ n: 1,
  opTime:
   { ts: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1530639356 },
     t: 5 },
  electionId: 7fffffff0000000000000005,
  ok: 1,
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1530639356 },
  '$clusterTime':
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1530639356 },
     signature: { hash: [Object], keyId: [Object] } } }
6656: ./6656_native.js true
mongodb+srv://xxx:yyy@cluster0-host.mongodb.net/test?retryWrites=true
{ n: 1,
  opTime:
   { ts: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1530639360 },
     t: 5 },
  electionId: 7fffffff0000000000000005,
  ok: 1,
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1530639360 },
  '$clusterTime':
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1530639360 },
     signature: { hash: [Object], keyId: [Object] } } }
6656:
```
