### ISSUE TITLE
countDocuments throws TypeError

### ISSUE THREAD

**Issue by jackytck** [Automattic/mongoose#6668]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Calling countDocuments() on a query that should result in 0 would throw a TypeError. But calling count() with the same query works.
```bash
Uncaught TypeError: Cannot read property 'n' of undefined
  at result.toArray (node_modules/mongodb/lib/operations/collection_ops.js:237:46)
  at result (node_modules/mongodb/lib/utils.js:414:17)
  at executeCallback (node_modules/mongodb/lib/utils.js:406:9)
  at handleCallback (node_modules/mongodb/lib/utils.js:128:55)
  at cursor.close (node_modules/mongodb/lib/operations/cursor_ops.js:218:62)
  at handleCallback (node_modules/mongodb/lib/utils.js:128:55)
  at completeClose (node_modules/mongodb/lib/cursor.js:887:14)
  at AggregationCursor.Cursor.close (node_modules/mongodb/lib/cursor.js:906:10)
  at cursor._next (node_modules/mongodb/lib/operations/cursor_ops.js:218:23)
  at handleCallback (node_modules/mongodb-core/lib/cursor.js:202:5)
  at _setCursorNotifiedImpl (node_modules/mongodb-core/lib/cursor.js:560:38)
  at self._endSession (node_modules/mongodb-core/lib/cursor.js:568:46)
  at AggregationCursor.Cursor._endSession (node_modules/mongodb-core/lib/cursor.js:193:5)
  at AggregationCursor.Cursor._endSession (node_modules/mongodb/lib/cursor.js:226:59)
  at _setCursorNotifiedImpl (node_modules/mongodb-core/lib/cursor.js:568:17)
  at setCursorNotified (node_modules/mongodb-core/lib/cursor.js:560:3)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
model.find({ '$or':
   [ { starshipClass: 'yacht', _id: [Object] },
     { starshipClass: [Object] } ]
}).countDocuments()
```

**What is the expected behavior?**
Should work as if calling count(). If count is zero, should return 0, not throwing.

**Please mention your node.js, mongoose and MongoDB version.**
node: v10.5.0
mongoose: v5.2.1
mongo: v3.2.9

**Comment by lineus** [comment]
There's [an existing bug](https://jira.mongodb.org/projects/NODE/issues/NODE-1543?filter=recentlyviewed) in the current version of the native driver that breaks countDocuments with results of 0 length. The fix will ship in a future release of mongoose when the patched driver is available.

**Comment by vkarpov15** [comment]
Fixed by https://github.com/Automattic/mongoose/commit/41ec904c5afd4bcb87822a6216c73183c16668d0, will release 5.2.2 later this weekend with the fix.
