### ISSUE TITLE
.toObject() on CoreMongooseArray fails

### ISSUE THREAD

**Issue by civilatio** [Automattic/mongoose#6715]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If i set the array of a document new, i get the following error:

> [12:31:06] - error: Unexpected internal server error (500): TypeError: b.toObject is not a function
>     at deepEqual (...\node_modules\mongoose\lib\utils.js:99:11)
>     at model.Document.$__shouldModify (...\node_modules\mongoose\lib\document.js:961:8)
>     at model.Document.$__set (...\node_modules\mongoose\lib\document.js:989:27)
>     at model.$set (...\node_modules\mongoose\lib\document.js:880:10)
>     at model.set [as phases] (...\node_modules\mongoose\lib\helpers\document\compile.js:124:26)
>     at Function._callee14$ (.../server/api/project/project.service.js:424:9)

The failing line in my coding is the following: newProject is a new Mongoose object. Phases are nested mongoose objects, not populated ones.

`newProject.phases = newProject.phases.filter((item) => item._id.toString() !== phaseId.toString());`

I made breakpoints in the coding and it looks like the MongooseArray lacks the toObject() function if it has more than one entry (i looked into proto and so on).

![grafik](https://user-images.githubusercontent.com/17002131/42628656-11810e3c-85d1-11e8-8c2b-2ac78f38b098.png)

![grafik](https://user-images.githubusercontent.com/17002131/42628660-148265d6-85d1-11e8-91e4-b1c2d65f9eb9.png)

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS: 8.9.4, mongoose: 5.2.3, MongoDB: 4.0.0

**Comment by civilatio** [comment]
I am sorry. newProject got cloned with the lodash function and that was not correct.
