### ISSUE TITLE
Transaction Error .Only the first command in a transaction may specify a readConcern

### ISSUE THREAD

**Issue by xxxman2008** [Automattic/mongoose#6739]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
1.   connection options  assigned readConcern -      readConcern: {level: 'majority'}, 
2.  run an  transaction
3.  will get error :   
"error_message" : "Only the first command in a transaction may specify a readConcern", 
    "event_stack" : "MongoError: Only the first command in a transaction may specify a readConcern\n    at queryCallback (/opt/********/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:247:25)\n    at /opt/**********/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:531:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)", 

**If the current behavior is a bug, please provide the steps to reproduce.**

see above

**What is the expected behavior?**
no error

**Please mention your node.js, mongoose and MongoDB version.**
node.js  version  v8.9.4
mongoose version 5.2.2
MongoDB version  V4.0.0 ( run on debian 8.9)
MongoDB nodejs driver version 3.1.1

**Comment by lineus** [comment]
@xxxman2008 I think that this is [addressed here in the mongodb docs](https://docs.mongodb.com/manual/core/transactions/#read-preference) for transactions. Have you tried setting a different readConcern in your session options?
