### ISSUE TITLE
Error: server instance pool was destroyed | after Mlab update

### ISSUE THREAD

**Issue by Pensarfeo** [Automattic/mongoose#6759]
Hi, I got the following error after Mlab update to mongodb 3.6 on the free tier with mongoose version 5.0.0-rc2.

```
HANDLER ERROR:  { MongoError: server instance pool was destroyed
    at basicWriteValidations (/home/ubuntu/server/node_modules/mongodb-core/lib/topologies/server.js:636:41)
    at Server.insert (/home/ubuntu/server/node_modules/mongodb-core/lib/topologies/server.js:737:16)
    at Server.insert (/home/ubuntu/server/node_modules/mongodb/lib/topologies/topology_base.js:313:25)
    at executeBatch (/home/ubuntu/server/node_modules/mongodb/lib/bulk/unordered.js:479:23)
    at executeBatches (/home/ubuntu/server/node_modules/mongodb/lib/bulk/unordered.js:514:5)
    at executeOperation (/home/ubuntu/server/node_modules/mongodb/lib/utils.js:408:22)
    at UnorderedBulkOperation.execute (/home/ubuntu/server/node_modules/mongodb/lib/bulk/unordered.js:609:10)
    at bulkWrite (/home/ubuntu/server/node_modules/mongodb/lib/collection.js:620:8)
    at executeOperation (/home/ubuntu/server/node_modules/mongodb/lib/utils.js:408:22)
    at Collection.insertMany (/home/ubuntu/server/node_modules/mongodb/lib/collection.js:505:10)
    at Collection.insert (/home/ubuntu/server/node_modules/mongodb/lib/collection.js:777:15)
    at NativeCollection.(anonymous function) [as insert] (/home/ubuntu/server/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:130:28)
    at model.Model.$__handleSave (/home/ubuntu/server/node_modules/mongoose/lib/model.js:145:21)
    at model.Model.$__save (/home/ubuntu/server/node_modules/mongoose/lib/model.js:214:8)
    at /home/ubuntu/server/node_modules/kareem/index.js:276:8
    at _next (/home/ubuntu/server/node_modules/kareem/index.js:102:16)
  name: 'MongoError',
  message: 'server instance pool was destroyed' }
```
The problem was solved by simply updating the server; so I assume the error was due to the connection beeing closed by Mlab.

Is this issue solved in new versions?
Or Is there a suggested way to handle this error?

**Comment by vkarpov15** [comment]
There's a lot of potential causes for this issue, most likely that you closed a connection while an operation was in progress. If this is still an issue in Mongoose 5.x please provide some code samples.

**Comment by svyandun** [comment]
I had the same issue after an mLab version upgrade (https://docs.mlab.com/201807-maintenance-event/) and some maintenance windows. AFAIK, this only happens in Sandbox databases. 

I would also be interested in a way to handle this properly. 🙂

**Comment by NewEraCracker** [comment]
mongoose version 5.0.0-rc2...
You should update that to at least 5.1.8

Also, what settings are being used to connect to the database.
Have you modified poolSize from the default of 5 to something else?

**Comment by Pensarfeo** [comment]
HI, I am using a super vanilla setting
```js
mongoose.connect(dbUrl, {}).then(() => {
  console.log('connected to mongolab')
})
```

**Comment by Pensarfeo** [comment]
and, just like svyandun, we are also using the Sandbox.

**Comment by vkarpov15** [comment]
How long approximately does it take for mlab to upgrade? You might need to configure [`reconnectTries` and `reconnectInterval`](http://mongoosejs.com/docs/connections.html#options) to allow Mongoose to automatically reconnect if the upgrade takes a long time and requires downtime.

**Comment by Pensarfeo** [comment]
@vkarpov15 Good point, I have no Idea how much downtime there was. I'll check on that!

**Comment by Pensarfeo** [comment]
So, got feedback from mlab. For the free sandbox version they do not want to set any maximum downtime. .. So it's basically up to us to set up very high reconnect Tries and Interval :)

**Comment by vkarpov15** [comment]
In that case, just set `reconnectTries` to `Number.MAX_VALUE` and you should be fine in the future. If the downtime takes longer than 30 seconds, the MongoDB driver will give up trying to reconnect unless you tweak `reconnectTries`.

**Comment by Pazitos10** [comment]
I'm having this issue but in a local installation of the latest version of mongoose (5.3.14). I've made a script to populate the database that is similar to this:

```js
const dbURI = 'mongodb://localhost/my_database'
mongoose.connect(dbURI, { useNewUrlParser: true})

const customSchema = new mongoose.Schema({
  fieldA: String,
  fieldB: String,
  fieldC: String
});

const customModel = mongoose.model('customModel', customSchema);

// ...
const saveInDB = (valueA,valueB, valueC) => {

  const newModel = new customModel()
  newModel.fieldA = valueA
  newModel.fieldB = valueB
  newModel.fieldC = valueC
  
  newModel.save(err => {
    if (err) { console.log(err) }
  })
}
```
Then, inside a map callback function I call `saveInDB()` with the real data as I am creating it. 
After the loop ends, if I try to close the connection using `mongoose.connection.close()`, something goes wrong and I get a lot of messages like this:

```
{ MongoError: server instance pool was destroyed
    at basicWriteValidations (/home/user/project/app/node_modules/mongodb-core/lib/topologies/server.js:700:41)
    at Server.insert (/home/user/project/app/node_modules/mongodb-core/lib/topologies/server.js:805:16)
    at Server.insert (/home/user/project/app/node_modules/mongodb/lib/topologies/topology_base.js:321:25)
    at insertDocuments (/home/user/project/app/node_modules/mongodb/lib/operations/collection_ops.js:821:19)
    at insertOne (/home/user/project/app/node_modules/mongodb/lib/operations/collection_ops.js:851:3)
    at executeOperation (/home/user/project/app/node_modules/mongodb/lib/utils.js:420:24)
    at Collection.insertOne (/home/user/project/app/node_modules/mongodb/lib/collection.js:463:10)
    at NativeCollection.(anonymous function) [as insertOne] (/home/user/project/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:146:28)
    at NativeCollection.Collection.doQueue (/home/user/project/app/node_modules/mongoose/lib/collection.js:126:30)
    at immediate (/home/user/project/app/node_modules/mongoose/lib/collection.js:86:24)
    at process.internalTickCallback (internal/process/next_tick.js:70:11) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
```
In addition, the script execution ends abruptly and nothing is written in the database. Whereas if I do not call `mongoose.connection.close()`, the data is saved successfully but my script never ends. 

How should I do the disconnection? Is there something I'm doing wrong?

Thanks in advance!
