### ISSUE TITLE
TypeError: utf8 is not a function

### ISSUE THREAD

**Issue by sirdiamond** [Automattic/mongoose#6769]
Hi there,

I'm unable to connect to mongodb.
With a simple connection:

```
const mongoose = require('mongoose')
mongoose.connect('mongodb://user:password@111.111.111.111:27017/dbname',  { useNewUrlParser: true })
```
is throwing this error:
```
......node_modules/mongodb-core/lib/auth/scram.js:189
      Buffer.from('n=', 'utf8'),
             ^

TypeError: utf8 is not a function
    at Function.from (native)
    at Function.from (native)
    at executeScram (....node_modules/mongodb-core/lib/auth/scram.js:189:14)
    at ......node_modules/mongodb-core/lib/auth/scram.js:361:7
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

Any ideas what it can be? 

Mongoose: Version 5.2.5
MongoDB shell version: 3.2.20

**Comment by sirdiamond** [comment]
The problem was my node version... after I've updated, fixed the issue.
