### ISSUE TITLE
Mongoerror: authentication failed.

### ISSUE THREAD

**Issue by unrealgio** [Automattic/mongoose#6788]
hi, i would appreciate if anyone could help me. im getting this error when i try to connect using the URL:

03:20:21.08 <ERROR> { MongoError: Authentication failed.
    at Function.MongoError.create (C:\Users\unkno\node_modules\mongodb-core\lib\error.js:31:11)
    at C:\Users\unkno\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (C:\Users\unkno\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (C:\Users\unkno\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at Socket.<anonymous> (C:\Users\unkno\node_modules\mongodb-core\lib\connection\connection.js:333:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed',
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1533018007 },
  '$clusterTime':
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1533018007 },
     signature: { hash: [Object], keyId: [Object] } } } (in loginDBConnection.js:9)

**Comment by vladretca** [comment]
@unrealgio Did you find a solution for this? I'm experiencing the same issue. Maybe an older version of mongoose?

**Comment by vkarpov15** [comment]
Without any code samples there's nothing I can do to help debug this, other than tell you to make sure your username and password are correct.

**Comment by riyagarg47** [comment]
I am facing the same issue, can someone plz help asap?
