### ISSUE TITLE
Errors can't be traced back to the application code

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#6803]
I am getting errors like the following:

```
ObjectParameterError: Parameter "obj" to Document() must be an object, got 555bee3e4527879d33c7b33a
    at new ObjectParameterError (node_modules/mongoose/lib/error/objectParameter.js:23:11)
    at SingleNested.Document (node_modules/mongoose/lib/document.js:66:11)
    at SingleNested.Subdocument (node_modules/mongoose/lib/types/subdocument.js:18:12)
    at new SingleNested (node_modules/mongoose/lib/schema/embedded.js:57:17)
    at Embedded.castForQuery (node_modules/mongoose/lib/schema/embedded.js:218:10)
    at Embedded.SchemaType.castForQueryWrapper (node_modules/mongoose/lib/schematype.js:1082:15)
    at cast (node_modules/mongoose/lib/cast.js:303:32)
    at model.Query.Query.cast (node_modules/mongoose/lib/query.js:3751:12)
    at model.Query.Query._castConditions (node_modules/mongoose/lib/query.js:1549:10)
    at model.Query.Query._find (node_modules/mongoose/lib/query.js:1564:8)
    at process.nextTick (node_modules/kareem/index.js:333:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
From previous event:
    at Object.promiseOrCallback (node_modules/mongoose/lib/utils.js:233:10)
    at model.Query.exec (node_modules/mongoose/lib/query.js:3549:16)
    at model.Query.Query.then (node_modules/mongoose/lib/query.js:3576:15)
```

Even with `Error.stackTraceLimit = Infinity;` we can't get more out of these errors or figure out what call they are originating from, because all stack trace lines refer to the mongoose library and not to our own app source code. This makes debugging our code very hard, especially since this error message is not very helpful. For example, I have no idea what Schema this relates to or what Model, or perhaps what sub schema, etc.

Is it possible to clarify this a bit better or provide a full strack trace with these errors so we can pinpoint what calls triggered them?

**Comment by adamreisnz** [comment]
In this particular case I tracked down the error to trying to filter on `{membership: ObjectId()}` while the schema had changed, so I needed to filter on `{'membership._id': ObjectId()}` instead.

So a clearer error message might have been `Path 'membership' in 'Subscription' schema expects a document, but got XXXXX instead`.

**Comment by vkarpov15** [comment]
Thanks for reporting this, will fix ASAP.

**Comment by adamreisnz** [comment]
Thanks for looking into this!
