### ISSUE TITLE
mongoose.connect() not working, mongoose 5.2.9

### ISSUE THREAD

**Issue by Cesarcs7** [Automattic/mongoose#6902]
Im running with this issue again, i did everything possible that i found in the previous issues and in the mongoose website. I dont know if im missing something.

`const mongoose = ('mongoose');

mongoose.strike('debug', true);
mongoose.Promise = Promise;
mongoose.connect('mongodb://localhost:27017/mydb', { useNewUrlParser: true });

module.exports.Firma = require('./firma.js');`

**output: **

`C:\Users\Cesar\Desktop\Code\washStraßeServer\models\index.js:5
mongoose.connect('mongodb://localhost:27017/mydb', { useNewUrlParser: true });
         ^

TypeError: mongoose.connect is not a function
    at Object.<anonymous> (C:\Users\Cesar\Desktop\Code\washStraßeServer\models\index.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Cesar\Desktop\Code\washStraßeServer\handlers\auth.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)`

Node version - 10.9.0
Mongoose version - 5.2.9
MongoDB version - 4.0.1

**Comment by Cesarcs7** [comment]
Missed some code XD...

**Comment by Akaronte** [comment]
> Missed some code XD...
> 
> const mongoose = require('mongoose');

thats relsove my problem
