### ISSUE TITLE
Schema hasn't been registered for model "[object Object]"

### ISSUE THREAD

**Issue by vdakalov** [Automattic/mongoose#6915]
In my case:

I have **platform** model
```javascript
const PlatformSchema = new Mongoose.Schema({
  name: String
});
const PlatformModel = Mongoose.model('platform', PlatformSchema);
```
also I have **place** model. Which reference to platform
```javascript
const PlaceSchema = new Mongoose.Schema({
  name: String,
  platform: {
    type: Mongoose.Schema.Types.ObjectId,
    ref: PlatformSchema
  }
});
const PlaceModel = Mongoose.model('place', PlaceSchema);
```

Then I trying request **place** with populated platform path
```javascript
PlaceModel
      .findOne({ _id: '5b7f97894e43f174cb0f42cc' })
      .populate({ path: 'platform' })
```
and receive error
```
{ MissingSchemaError: Schema hasn't been registered for model "[object Object]".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/path/to/my/project/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at NativeConnection.Connection.model (/path/to/my/project/node_modules/mongoose/lib/connection.js:791:11)
    at getModelsMapForPopulate (/path/to/my/project/node_modules/mongoose/lib/model.js:4000:20)
    at populate (/path/to/my/project/node_modules/mongoose/lib/model.js:3502:21)
    at _populate (/path/to/my/project/node_modules/mongoose/lib/model.js:3472:5)
    at utils.promiseOrCallback.cb (/path/to/my/project/node_modules/mongoose/lib/model.js:3445:5)
    at Object.promiseOrCallback (/path/to/my/project/node_modules/mongoose/lib/utils.js:231:14)
    at Function.Model.populate (/path/to/my/project/node_modules/mongoose/lib/model.js:3444:16)
    at model.Query.Query._completeOne (/path/to/my/project/node_modules/mongoose/lib/query.js:1814:9)
    at Immediate.Query.base.findOne.call (/path/to/my/project/node_modules/mongoose/lib/query.js:1851:10)
    at Immediate._onImmediate (/path/to/my/project/node_modules/mquery/lib/utils.js:117:16)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
  message: 'Schema hasn\'t been registered for model "[object Object]".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
```
As I understand it, problem with Mongoose unable receive model object (namely `PlatformModel`) from available `PlatformSchema` (available because it specified in PlaceSchema in platform property). So Mongoose can't receive related model for populate _platform_ property of _place_ document and ask me give it model into populate options as `.populate({ path: 'platform', model: PlatformModel })`.

I should be give model for populate every time?
Quote from file `mongoose/libs/model.js` at define `Model.populate`

```
3421. // Note that we didn't need to specify the Weapon model because
3422. // it is in the schema's ref
```
Why Mongoose can't extract model from available schema?

**Comment by lineus** [comment]
the value of the ref option on your schema path should be the name of the model ( the first argument when you created the model with `mongoose.model()` ), not the schema object.

```js
  platform: {
    type: Mongoose.Schema.Types.ObjectId,
    ref: 'platform'
  }
```

> Why Mongoose can't extract model from available schema?

The Schema gets compiled into a Model, thus the model is aware of the schema, but schemas can be used in multiple other schemas (embedded) or used for multiple models, so it wouldn't be practical to mutate the schema with the model information when compiling it into a model.

**Comment by vdakalov** [comment]
Thanx for detailed answer :smile:

**Comment by vdakalov** [comment]
I take this opportunity to ask why it is impossible to specify the model itself as the value of the ref property? The model has the name which required to this property

**Comment by vkarpov15** [comment]
@vdakalov specifying the model object as a ref should be ok, we can support that if necessary. Schemas and models are two separate things though.

**Comment by poojapareek1** [comment]
this issue existed at my end cause i created model outside the folder where controller exists.
