### ISSUE TITLE
$push object with array into array property fails

### ISSUE THREAD

**Issue by ramyhhh** [Automattic/mongoose#6952]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If we have a document with an array property and we are trying to push a new object that also contains array property using $push operator the bug will show up. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Suppose we have a document in database
```
{ array1 : [ ... ] }
```
and we want to push into array1 a new object like this:
```
var toBePushedObj = { array2 : [] }
```
using $push operator like this:
```
model.findByIdAndUpdate(id,{ $push: {array1:toBePushedObj}})
```
The update will fail with an error message "Cannot read property 'caster' of undefined"

Here is stack trace:
```
    at walkUpdatePath (/node_modules/mongoose/lib/helpers/query/castUpdate.js:264:26)
    at walkUpdatePath (/node_modules/mongoose/lib/helpers/query/castUpdate.js:209:20)
    at castUpdate (/node_modules/mongoose/lib/helpers/query/castUpdate.js:79:18)
    at model.Query._castUpdate (/node_modules/mongoose/lib/query.js:3688:10)
    at castDoc (/node_modules/mongoose/lib/query.js:3715:18)
    at model.Query.Query._findAndModify (/node_modules/mongoose/lib/query.js:2941:19)
    at model.Query.Query._findOneAndUpdate (/node_modules/mongoose/lib/query.js:2650:8)
```
I tried to somehow dig into this, I found that the local variable schematype for the array path is undefined even though the code is trying to get it from schema._getSchema(...) and getEmbeddedDiscriminatorPath(...)

**What is the expected behavior?**
No bug, it should push the object into the array property

**Please mention your node.js, mongoose and MongoDB version.**
Node: 8.11.1
mongoose: 5.2.9
MongoDB: 3.6.5

**Comment by lineus** [comment]
@ramyhhh I tried to reproduce this with the following script, but it behaves as expected. Can you edit this example to show the behavior you are seeing?

### 6952.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.set('useFindAndModify', false);
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  outer: [{
    inner: [{ x: String }]
  }]
});

const Test = mongoose.model('test', schema);

const test = new Test;

async function run() {
  await conn.dropDatabase();
  await test.save();
  let cond = { _id: test._id };
  let toBePushedObj = { inner: { x: 'test' } };
  let update = { $push: { outer: toBePushedObj } };
  await Test.findOneAndUpdate(cond, update);
  let found = await Test.findOne({});
  console.log(JSON.stringify(found, null, 2));
  return conn.close();
}

run();
```
### Output:
```
issues: ./6952.js
{
  "_id": "5b8c07ec1bd35329c5b4914a",
  "outer": [
    {
      "inner": [
        {
          "_id": "5b8c07ec1bd35329c5b4914c",
          "x": "test"
        }
      ],
      "_id": "5b8c07ec1bd35329c5b4914b"
    }
  ],
  "__v": 0
}
issues:
```

**Comment by ramyhhh** [comment]
@lineus I edited your code to reproduce the error, the differences are:

* I used MixedType schema
* Created the outer object using Model.create method

```
const mongoose = require('mongoose');
mongoose.set('useFindAndModify', false);
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema(Schema.Types.Mixed, { strict: false });

const Test = mongoose.model('test', schema);


async function run() {
  await conn.dropDatabase();
  let outer = await Test.create({ outerArray: [] })
  let toBePushedObj = { innerArray: [] };
  let update = { $push: { outerArray: toBePushedObj } };
  await Test.findOneAndUpdate({ _id: outer._id }, update);
  let found = await Test.findOne({});
  console.log(JSON.stringify(found, null, 2));
  return conn.close();
}

run();
```

**Comment by lineus** [comment]
Thanks for clarifying @ramyhhh. I'll put in a PR for this ASAP.
