### ISSUE TITLE
Cannot read property 'String' of undefined

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [Automattic/mongoose#6958]
I have a component that customizes a specific type of string, but after updating the mongoose came to introduce me this error

```js
[nodemon] restarting due to changes...
[nodemon] starting `node dist/main.js`
~/webservice3/dist/lib/mongoose-devise/types/email.js:28
Object.setPrototypeOf(Email.prototype, mongoose.SchemaTypes.String.prototype);
                                                            ^

TypeError: Cannot read property 'String' of undefined
    at Object.<anonymous> (~/webservice3/dist/lib/mongoose-devise/types/email.js:28:61)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~/webservice3/dist/lib/mongoose-devise/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[nodemon] app crashed - waiting for file changes before starting...
```
the source is here
```js
import * as mongoose from 'mongoose'

const regex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/

export interface EmailOptions {
  required?: Function,
  allowBlank?: Boolean
}

export function isEmail (val: string, options: EmailOptions): boolean {
  const required = (typeof options.required === 'function') ? options.required() : options.required
  const passedAllowBlank = options.allowBlank && (val === '' || val === null)
  if (passedAllowBlank && !required) {
    return true
  }
  return regex.test(val)
}

function Email (path: string, options: any): void {
  mongoose.SchemaTypes.String.call(this, path, options)

  function isValid (val) {
    return isEmail(val, options)
  }

  this.validate(isValid, options.message || 'invalid email address')
}

Object.setPrototypeOf(Email.prototype, mongoose.SchemaTypes.String.prototype)

mongoose.Schema.Types.Email = Email
mongoose.Types.Email = String

module.exports = Email
```

### environment
"node": "v10.6.0",
"npm": "6.4.0",
"mongoose": "^5.2.12",
"@types/mongoose": "^5.2.9",

**Comment by carvalhoviniciusluiz** [comment]
Sorry for the issue, I should have done this on stackoverflow. The problem is with library import
to correct, just do

```js
import mongoose = require('mongoose')
```

**Comment by vkarpov15** [comment]
The recommended import syntax is `import mongoose from 'mongoose';` . The `import * from` syntax is *not* supported and will *not* work.

**Comment by carvalhoviniciusluiz** [comment]
I do not know what could have happened but it was what solved for me
