### ISSUE TITLE
Allow overwriting `localField` and `foreignField` when populating virtuals

### ISSUE THREAD

**Issue by lcw0622** [Automattic/mongoose#6963]
```javascript
Project.virtual('userInfo', {  
  ref: 'User',  
  localField: 'username',  
  foreignField: 'username',  
  justOne: true  
})  
projectModel.find().populate('userInfo')  
```
It return without `userInfo` field, but if I change `foreignField` to `_id`, it will report an error like:
`CastError: Cast to ObjectId failed for value "username" at path "_id" for model "User".`
Mongoose: 4.12.3
MongoDB: 2.2.34
NodeJS: 8.11.2

**Comment by lineus** [comment]
@lcw0622 The following complete example shows that population works. Can you edit it to show the error you are seeing?

### 6963.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost:27017/test', { useMongoClient: true});
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const userSchema = new Schema({
  name: String,
  username: String
});

const projectSchema = new Schema({
  name: String,
  username: String
});

projectSchema.virtual('userInfo', {
  ref: 'user',
  localField: 'username',
  foreignField: 'username',
  justOne: true
});

const User = mongoose.model('user', userSchema);
const Project = mongoose.model('project', projectSchema);

const user = new User({ name: 'Billy', username: 'quickdraw' });
const project = new Project({ name: 'Outlaw', username: user.username });

async function run() {
  assert.strictEqual(mongoose.version, '4.12.3');
  await conn.dropDatabase();
  await user.save();
  await project.save();
  let doc = await Project.findOne({}).populate('userInfo');
  assert.strictEqual(doc.userInfo.name, 'Billy');
  console.log('Assertions passed.');
  return conn.close();
}

run();
```
### Output:
```
issues: ./6963.js
Assertions passed.
issues:
```

**Comment by lcw0622** [comment]
@lineus thanks, I had try your code, but it will report error if I  do some change like this:
```javascript
const projectSchema = new Schema({
  name: String,
  erp: String
});

projectSchema.virtual('userInfo', {
  ref: 'user',
  localField: 'erp',
  foreignField: 'username',
  justOne: true
});
```
error: `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null`
It seems I had to use a same field name to populate？

**Comment by lineus** [comment]
did you also change the creation of the project doc to reflect the new field `erp` instead of `username`? 

Here is the same code as above but with the Project path `erp` instead of `username`.

### 6963.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost:27017/test', { useMongoClient: true});
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const userSchema = new Schema({
  name: String,
  username: String
});

const projectSchema = new Schema({
  name: String,
  erp: String // changed
});

projectSchema.virtual('userInfo', {
  ref: 'user',
  localField: 'erp', // changed
  foreignField: 'username',
  justOne: true
});

const User = mongoose.model('user', userSchema);
const Project = mongoose.model('project', projectSchema);

const user = new User({ name: 'Billy', username: 'quickdraw' });
const project = new Project({ name: 'Outlaw', erp: user.username }); // changed

async function run() {
  assert.strictEqual(mongoose.version, '4.12.3');
  await conn.dropDatabase();
  await user.save();
  await project.save();
  let doc = await Project.findOne({}).populate('userInfo');
  assert.strictEqual(doc.userInfo.name, 'Billy');
  console.log('Assertions passed.');
  return conn.close();
}

run();
```
### Output:
```
issues: ./6963.js
Assertions passed.
issues:
```

**Comment by lcw0622** [comment]
Thanks, In fact I use `toObject` to output result document, and then I found the `model.toObject` function seems doesn't handle the `virtual populate` field.
```javascript
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost:27017/test', { useMongoClient: true});
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const userSchema = new Schema({
  name: String,
  username: String
});

const projectSchema = new Schema({
  name: String,
  username: String
});

projectSchema.virtual('userInfo', {
  ref: 'user',
  localField: 'username',
  foreignField: 'username',
  justOne: true
});

const User = mongoose.model('user', userSchema);
const Project = mongoose.model('project', projectSchema);

const user = new User({ name: 'Billy', username: 'quickdraw' });
const project = new Project({ name: 'Outlaw', username: user.username });

async function run() {
  assert.strictEqual(mongoose.version, '4.12.3');
  await conn.dropDatabase();
  await user.save();
  await project.save();
  let doc = await Project.findOne({}).populate('userInfo');
  let plainObj = doc.toObject()
  assert.strictEqual(plainObj.userInfo.name, 'Billy');
  console.log('Assertions passed.');
  return conn.close();
}

run();
```
### Output:
```
(node:76898) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at run (/Users/liuchengwei/Work/work/talos-backend/mongo.js:41:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:76898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:76898) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by lineus** [comment]
@lcw0622 you need to set the toObject virtuals option on the project schema to true in order to get virtual fields in the output of toObject().

```js
const projectSchema = new Schema({
  name: String,
  username: String
}, { toObject: { virtuals: true } });
```
or 
```js
const projectSchema = new Schema({
  name: String,
  username: String
});

projectSchema.set('toObject', { virtuals: true });
```

**Comment by lcw0622** [comment]
@lineus It take effect!  Thanks a lot~ Maybe I need ready API docs more careful T_T

**Comment by lcw0622** [comment]
@lineus By the way, may I ask for why not add `foreignFiled` for Schema reference definition or in `populate` option? thanks
```javascript
var personSchema = Schema({
  _id: Schema.Types.ObjectId,
  name: String,
  age: Number,
  stories: [{ type: String, ref: 'Story', foreignField: 'storyName' }]
});
```
### or
```javascript
Person.
  findOne({ name: 'Ian Fleming' }).
  populate({
path: 'stories',
foreignField: 'storyName'
}).
```

**Comment by vkarpov15** [comment]
Re: setting `foreignField` in the schema and in `populate()`, that's an interesting idea, we'll consider that for a future release.

**Comment by lcw0622** [comment]
Thanks ,@lineus and @vkarpov15 ~
I think it will be very helpful for SQL users translate such sql:
```sql
SELECT
  FIELD_A, 
  (SELECT T_B.FIELD_B FROM T_B WHERE T_B.FIELD_A = T_A.FIELD_A) AS FIELD_B
FROM T_A
WHERE T_A='SOME OTHER CONDITIONS'
```

**Comment by vkarpov15** [comment]
@lcw0622 unlikely to happen anytime soon, but thanks for the suggestion
