### ISSUE TITLE
[BUG] Double populates array then array.field should make field as an object (not an array)

### ISSUE THREAD

**Issue by amelon** [Automattic/mongoose#6978]
**What is the current behavior?**
When once populates an array (eg: `comments`) and then populates a field within the array (eg: `comments.author`), populated field (`comments[x].author`) is an array.

**Steps to reproduce.**
Full code is in the repo: [mongoose-populate-5213-issue](https://github.com/amelon/mongoose-populate-5213-issue)

**What is the expected behavior?**
When you populate an array (eg: `comments`) and then populate a field of the array (eg: `comments.author`), populated field (`comments[x].author`) should be an object.

````
...
async function findPopulatedComments() {
  const posts = await PostMod.find()
  await PostMod.populate(posts, { path: 'comments', model: 'Comment' })
  await PostMod.populate(posts, { path: 'comments.author', model: 'User' })

  assert(Array.isArray(posts[0].comments[0].author) === false)
}
...
````

It works as expected on mongoose 5.2.10.

**Versions**
node: v8.9.1
mongodb: v3.4.9
mongoose: v5.2.13, v5.2.12, v5.2.11

**Comment by lineus** [comment]
confirmed with:

### 6978.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const authorSchema = new Schema({
  name: String
});

const commentSchema = new Schema({
  text: String,
  author: {
    type: Schema.Types.ObjectId,
    ref: 'author'
  }
});

const postSchema = new Schema({
  content: String,
  comments: [{
    type: Schema.Types.ObjectId,
    ref: 'comment'
  }]
});

const Post = mongoose.model('post', postSchema);
const Comment = mongoose.model('comment', commentSchema);
const Author = mongoose.model('author', authorSchema);

const authors = '123'.split('').map(n => { 
  return new Author({ name: `author${n}`});
});

const comments = 'abc'.split('').map((l,i) => {
  let id = authors[i]._id;
  return new Comment({ text: `comment_${l}`, author: id });
});

const test = new Post({
  content: 'hey look ma! no hands!',
  comments
});

async function run() {
  await conn.dropDatabase();
  await Author.create(authors);
  await Comment.create(comments);
  await test.save();
  let post = await Post.findOne({});
  post = await Post.populate(post, { path: 'comments' });
  post = await Post.populate(post, { path: 'comments.author', model: 'author'});
  post.comments.forEach(c => {
    assert.ok(!Array.isArray(c.author), 'author is an array');
  });
  return conn.close();
}

run().catch(e => { console.error(e); return mongoose.disconnect(); });
```
### Output:
```
issues: ./6978.js
{ AssertionError [ERR_ASSERTION]: author is an array
    at post.comments.forEach.c (/Users/lineus/dev/Help/mongoose5/issues/6978.js:57:12)
    at Array.forEach (<anonymous>)
    at run (/Users/lineus/dev/Help/mongoose5/issues/6978.js:56:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
issues:
```
