### ISSUE TITLE
MongoError: Failed to call method

### ISSUE THREAD

**Issue by jcindex** [Automattic/mongoose#6986]
```js
{ MongoError: Failed to call method
    at queryCallback (D:\microservices\wechat\node_modules\mongodb-core\lib\cursor.js:223:25)
    at D:\microservices\wechat\node_modules\mongodb-core\lib\connection\pool.js:541:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  name: 'MongoError',
  message: 'Failed to call method',
  ok: 0,
  errmsg: 'Failed to call method',
  code: 1,
  codeName: 'InternalError' }
```
请问大神们，这个问题怎样解决呢？我在搜索不到解决方案

**Comment by lineus** [comment]
@jcindex Can you please include a reproducible code sample that demonstrates the issue? There isn't enough information here for us to help.

**Comment by lineus** [comment]
@jcindex I'm closing this for now. Please provide a code sample that demonstrates the issue for you if it comes back up.
