### ISSUE TITLE
[BUG] Array of Maps Not Casting

### ISSUE THREAD

**Issue by MikeShi42** [Automattic/mongoose#6995]
**Current Behavior:** Mongoose fails creating a new document with an array of maps. `CastError: Cast to [undefined] failed for value "[{"a":"1"}]" at path "val"`. Not sure if expected behavior?

**Repro Script:**

```javascript
const mongoose = require('mongoose');
mongoose.Promise = Promise;
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const { Schema } = mongoose;

const ArrMapSchema = new Schema({
    val: [Map],
});

mongoose.model('ArrMap', ArrMapSchema);

const ArrMap = mongoose.model('ArrMap');

ArrMap.create({
    val: [{'a': '1'}],
}).catch(error => console.log(error.errors.val.reason));
```

**Expected Behavior**

Document should create successfully and look like
```
{
  val: [{'a': '1'}]
}
```

**Versions**
```
node --version         v8.11.3
mongoose@5.2.13
db.version()            3.6.5
```

Full Error Trace:

```
{ CastError: Cast to [undefined] failed for value "[{"a":"1"}]" at path "val"
    at new CastError (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/error/cast.js:29:11)
    at SchemaArray.cast (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/schema/array.js:207:15)
    at SchemaArray.SchemaType.applySetters (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/schematype.js:755:12)
    at model.$set (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/document.js:922:18)
    at model._handleIndex (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/document.js:740:14)
    at model.$set (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/document.js:697:22)
    at model.Document (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/document.js:114:12)
    at model.Model (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/model.js:72:12)
    at new model (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/model.js:4294:13)
    at toExecute.push.callback (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/model.js:2501:22)
    at /Users/michaelshi/Projects/caster-array-repro/node_modules/async/internal/parallel.js:31:39
    at eachOfArrayLike (/Users/michaelshi/Projects/caster-array-repro/node_modules/async/eachOf.js:65:9)
    at exports.default (/Users/michaelshi/Projects/caster-array-repro/node_modules/async/eachOf.js:9:5)
    at _parallel (/Users/michaelshi/Projects/caster-array-repro/node_modules/async/internal/parallel.js:30:5)
    at parallelLimit (/Users/michaelshi/Projects/caster-array-repro/node_modules/async/parallel.js:88:26)
    at utils.promiseOrCallback.cb (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/model.js:2511:5)
  message: 'Cast to [undefined] failed for value "[{"a":"1"}]" at path "val"',
  name: 'CastError',
  stringValue: '"[{"a":"1"}]"',
  kind: '[undefined]',
  value: '[{"a":"1"}]',
  path: 'val',
  reason: TypeError: this.caster.cast is not a function
    at SchemaArray.cast (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/schema/array.js:203:34)
    at SchemaArray.SchemaType.applySetters (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/schematype.js:755:12)
    at model.$set (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/document.js:922:18)
    at model._handleIndex (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/document.js:740:14)
    at model.$set (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/document.js:697:22)
    at model.Document (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/document.js:114:12)
    at model.Model (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/model.js:72:12)
    at new model (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/model.js:4294:13)
    at toExecute.push.callback (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/model.js:2501:22)
    at /Users/michaelshi/Projects/caster-array-repro/node_modules/async/internal/parallel.js:31:39
    at eachOfArrayLike (/Users/michaelshi/Projects/caster-array-repro/node_modules/async/eachOf.js:65:9)
    at exports.default (/Users/michaelshi/Projects/caster-array-repro/node_modules/async/eachOf.js:9:5)
    at _parallel (/Users/michaelshi/Projects/caster-array-repro/node_modules/async/internal/parallel.js:30:5)
    at parallelLimit (/Users/michaelshi/Projects/caster-array-repro/node_modules/async/parallel.js:88:26)
    at utils.promiseOrCallback.cb (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/model.js:2511:5)
    at Promise (/Users/michaelshi/Projects/caster-array-repro/node_modules/mongoose/lib/utils.js:246:5) }
```

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP
