### ISSUE TITLE
UnhandledPromiseRejectionWarning when DB service is not available

### ISSUE THREAD

**Issue by kolbma** [Automattic/mongoose#6997]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

```
(node:14728) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Users\makolb\Source\Repos\easyIAM\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (C:\Users\makolb\Source\Repos\easyIAM\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (C:\Users\makolb\Source\Repos\easyIAM\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:14728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Stop mongodb and start application which calls `mongoose.connect(..., (err)=>{...})`

**What is the expected behavior?**
Should handle promise rejections.

**Please mention your node.js, mongoose and MongoDB version.**
v8.11.4
mongoose@5.2.13

**Comment by vkarpov15** [comment]
Can you pley provide more substantial code samples? I don't understand your issue.

**Comment by lineus** [comment]
### 6997.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
const URI = 'mongodb://localhost:27016/test'; // nothing on 27016
const OPTS = { useNewUrlParser: true };
mongoose.connect(URI, OPTS, function(err) {
  if (err) { return console.error('failed');}
}); 
```
### Output:
```
issues: ./6997.js
failed
(node:2349) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server[localhost:27016] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27016]
    at Pool.<anonymous> (/Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:2349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2349) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
issues:
```

**Comment by kolbma** [comment]
Should be clarified. ;-) Thanks @lineus

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP

**Comment by BRMC888** [comment]
Any update on this? The same thing happens in 5.6.0

```
(node:34) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
     at Pool.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:431:11)
     at emitOne (events.js:116:13)
     at Pool.emit (events.js:211:7)
     at connect (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:557:14)
     at makeConnection (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connect.js:39:11)
     at callback (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connect.js:261:5)
     at Socket.err (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connect.js:286:7)
     at Object.onceWrapper (events.js:315:30)
     at emitOne (events.js:116:13)
     at Socket.emit (events.js:211:7)
     at emitErrorNT (internal/streams/destroy.js:66:8)
     at _combinedTickCallback (internal/process/next_tick.js:139:11)
     at process._tickCallback (internal/process/next_tick.js:181:9)
 (node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

using:

```
const options = {
        useNewUrlParser: true
};

mongoose.connect(mongoConnectionString, options);

mongoose.connection.on('error', (err)=>{
        console.log('>> Failed to connect to MongoDB, retrying...');

        setTimeout( () => {
                mongoose.connect(mongoConnectionString, options);
        }, 5000);
});
```

**Comment by vkarpov15** [comment]
@BRMC888 that's because you're using `on('error')` as opposed to `.catch()` or passing a callback to `mongoose.connect()`. [The MongoDB node driver handles errors in initial connection differently from errors after initial connection succeeded](https://thecodebarbarian.com/managing-connections-with-the-mongodb-node-driver.html). An `on('error')` handler will get called whether the error happened during initial connection or after initial connection, so it isn't an appropriate place to handle initial connection errors.

We should improve this error message though, or at least add something to the docs about this.

**Comment by aryan6098** [comment]
I'm also facing the same issue can you please tell me where I'm wrong.



(node:1636) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: 
true } to MongoClient.connect.
(node:1636) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Server is running on port: 8789
Error connecting to MongoDB MongoNetworkError: failed to connect to server [localhost:2706] on first connect [Error: connect ECONNREFUSED 127.0.0.1:2706
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\topologies\server.js:438:11)
    at Pool.emit (events.js:311:20)
    at C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\pool.js:561:14
    at C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\pool.js:994:11
    at C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\connect.js:31:7
    at callback (C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\connect.js:264:5) 
    at Socket.<anonymous> (C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\connect.js:294:7)
    at Object.onceWrapper (events.js:418:26)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)   
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}
(node:1636) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:2706] on first connect [Error: connect ECONNREFUSED 127.0.0.1:2706
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\topologies\server.js:438:11)
    at Pool.emit (events.js:311:20)
    at C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\pool.js:561:14
    at C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\pool.js:994:11
    at C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\connect.js:31:7
    at callback (C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\connect.js:264:5) 
    at Socket.<anonymous> (C:\Users\Raj\Desktop\nodews\codeial\node_modules\mongodb\lib\core\connection\connect.js:294:7)
    at Object.onceWrapper (events.js:418:26)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)   
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1636) UnhandledPromiseRejectionWarning: Unhandled 
promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.




const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:2706/codeial_development');

const db = mongoose.connection;

db.on('error', console.error.bind(console, "Error connecting to MongoDB"));


db.once('open', function(){
    console.log('Connected to Database :: MongoDB');
});


module.exports = db;
