### ISSUE TITLE
Nested populate and lean used together always return an array

### ISSUE THREAD

**Issue by toniov** [Automattic/mongoose#7052]
Hi there, 

I'm using Mongoose version `5.2.17`.

When I populate in a nested way a leaned query, it always returns an array, even if it's not specified as an array in the schema.

It can be reproduced with this script:

```js
const ownerSchema = new Schema({ name: String, age: Number, dogs: [{ type: Schema.Types.ObjectId, ref: 'dog' }] });
const dogSchema = new Schema({ name: String, trick: { type: Schema.Types.ObjectId, ref: 'trick' } });
const trickSchema = new Schema({ description: String });

const Owner = mongoose.model('owner', ownerSchema);
const Dog = mongoose.model('dog', dogSchema);
const Trick = mongoose.model('trick', trickSchema);

(async () => {
  const owner = await Owner.find().lean().exec();
  let populated = await Owner.populate(owner, [{ path: 'dogs', model: 'dog', options: { lean: true } }]);
  populated = await Owner.populate(owner, [{ path: 'dogs.trick', model: 'trick', options: { lean: true } }]);
})()
```
`populated` is going to contain something like this:

```
[
  {
    "_id": "5baaf5ec15bfc7dd302a6e6c",
    "name": "Manolo",
    "age": 35,
    "dogs": [
      {
        "_id": "5ba9fefb15bfc7dd302a6e67",
        "name": "Bob",
        "trick": [
          {
            "_id": "5ba9f5d9a86e164b46fab1a5",
            "description": "Jump"
          }
        ]
      }
    ]
  }
]
```

According to the schema, `trick` should be an object, not an array. By the way, If `.lean()` is not used in the first query, it returns an object (correct behavior).

It was working properly until version 5.2.10, so I guess it's related to this [commit](https://github.com/Automattic/mongoose/commit/bf2bea74492ebebbb49778a08728263ebbd3aa22).

Furthermore, to the resultant object a property `[Symbol(mongoose:lean_populate)]` has been added. I'm using `lean` because I want to receive _clean_ objects, so I think this shouldn't be there either. 

```
MongoDB version: 3.2.16
Nodejs version: 8.11.3
```

Thanks!

**Comment by lineus** [comment]
@toniov Thanks for reporting this!

complete repro script:

### 7052.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const GH = 'gh7052';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const ownerSchema = new Schema({ 
  name: String, 
  age: Number, 
  dogs: [{ 
    type: Schema.Types.ObjectId, 
    ref: 'dog' 
  }] 
});

const dogSchema = new Schema({ 
  name: String,
  trick: { 
    type: Schema.Types.ObjectId, 
    ref: 'trick'
  } 
});

const trickSchema = new Schema({ description: String });

const Owner = mongoose.model('owner', ownerSchema);
const Dog = mongoose.model('dog', dogSchema);
const Trick = mongoose.model('trick', trickSchema);

const t = new Trick({ description: 'roll over'});
const d = new Dog({ name: 'Fido', trick: t._id });
const o = new Owner({ name: 'Bill', age: 10, dogs: [ d._id ] });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Promise.all([t.save(), d.save(), o.save()]);
  const owner = await Owner.findOne({}).lean(); // remove lean and test passes.
  let populated = await Owner.populate(owner, [{ path: 'dogs', model: 'dog', options: { lean: true } }]);
  populated = await Owner.populate(owner, [{ path: 'dogs.trick', model: 'trick', options: { lean: true } }]);
  assert.ok(!Array.isArray(populated.dogs[0].trick));
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return connection.close();
}
```
### Output ( with .lean() )
```
issues: ./7052.js
{ AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!Array.isArray(populated.dogs[0].trick))

    at run (/Users/lineus/dev/node/mongoose/issues/7052.js:45:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
issues: ./7052.js
issues: gv mongoose
  "version": "5.3.0"
issues:
```
### Output ( without .lean() )
```
issues: ./7052.js
All Assertions Pass.
issues:
```

**Comment by lineus** [comment]
I took another look at this when I had some more time this morning, and **if you simplify the 2 populate calls down to 1 by nesting the 2nd populate call in the 1st, the error goes away.** 

*The code that follows is the same as my last comment with only 1 call to populate, and it works as expected:*

### 7052.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const GH = 'gh7052';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const ownerSchema = new Schema({ 
  name: String, 
  age: Number, 
  dogs: [{ 
    type: Schema.Types.ObjectId, 
    ref: 'dog' 
  }] 
});

const dogSchema = new Schema({ 
  name: String,
  trick: { 
    type: Schema.Types.ObjectId, 
    ref: 'trick'
  } 
});

const trickSchema = new Schema({ description: String });

const Owner = mongoose.model('owner', ownerSchema);
const Dog = mongoose.model('dog', dogSchema);
const Trick = mongoose.model('trick', trickSchema);

const t = new Trick({ description: 'roll over'});
const d = new Dog({ name: 'Fido', trick: t._id });
const o = new Owner({ name: 'Bill', age: 10, dogs: [ d._id ] });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Promise.all([t.save(), d.save(), o.save()]);
  const owner = await Owner.findOne({}).lean(); //  works with/without lean()
  const popObj = { 
    path: 'dogs',
    options: { lean: true },
    populate: {
      path: 'trick',
      options: { lean: true }
    }
  };
  let populated = await Owner.populate(owner, popObj);
  assert.ok(!Array.isArray(populated.dogs[0].trick));
  assert.strictEqual(populated.dogs[0].name, 'Fido');
  assert.strictEqual(populated.dogs[0].trick.description, 'roll over');
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return connection.close();
}

```
### Output (with .lean() ):
```
issues: ./7052.js
All Assertions Pass.
issues:
```

**Comment by noname2534** [comment]
ในวันที่ อา. 30 ก.ย. 2018 16:19 น. Kev <notifications@github.com> เขียนว่า:

**Comment by toniov** [comment]
Thanks for the workarounds!

**Comment by toniov** [comment]
I tried with newest version (5.3.4) and it's not working properly for me.

**Comment by lineus** [comment]
@toniov this script adapted from your example shows that it's working now for me. Can you adapt it to demonstrate that there is still a problem?

### 7052.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const GH = 'gh7052';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const ownerSchema = new Schema({ 
  name: String, 
  age: Number, 
  dogs: [{ 
    type: Schema.Types.ObjectId, 
    ref: 'dog' 
  }] 
});

const dogSchema = new Schema({ 
  name: String,
  trick: { 
    type: Schema.Types.ObjectId, 
    ref: 'trick'
  } 
});

const trickSchema = new Schema({ description: String });

const Owner = mongoose.model('owner', ownerSchema);
const Dog = mongoose.model('dog', dogSchema);
const Trick = mongoose.model('trick', trickSchema);

const t = new Trick({ description: 'roll over'});
const d = new Dog({ name: 'Fido', trick: t._id });
const o = new Owner({ name: 'Bill', age: 10, dogs: [ d._id ] });

async function run() {
  assert.strictEqual(mongoose.version, '5.3.4');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Promise.all([t.save(), d.save(), o.save()]);
  const owner = await Owner.findOne({}).lean();//  now passes with lean()
  let populated = await Owner.populate(owner, { path: 'dogs', options: { lean: true } });
  populated = await Owner.populate(owner, { path: 'dogs.trick', options: { lean: true } });
  assert.ok(!Array.isArray(populated.dogs[0].trick));
  assert.strictEqual(populated.dogs[0].name, 'Fido');
  assert.strictEqual(populated.dogs[0].trick.description, 'roll over');
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return connection.close();
}
```
### Output:
```
issues: ./7052.js
All Assertions Pass.
issues:
```

**Comment by shengzheng1981** [comment]
@toniov rollback to 5.2.10. this feature is very unfriendly. 
justOne: optional boolean, if true Mongoose will always set path to an array. Inferred from schema by default.
true for an array？ why? 
5.6.11 is still not work.

**Comment by shengzheng1981** [comment]
@lineus check this schema
const LayerGroupSchema = new Schema({
    name: String,
    symbol: {
        type : ObjectId,
        ref  : 'Symbol'
    },
    layers: [{
        name: String,
        meta: {
            type : ObjectId,
            ref  : 'Meta'
        }
    }]
},{ collection: 'layergroups' });
5.6.11  symbol is ok, meta is an array, why?  cause nested in array?
5.2.10  all work.

**Comment by vkarpov15** [comment]
@shengzheng1981 the below script works as expected in 5.7.1: `meta` is a single object, not an array. Please modify the below script to demonstrate the issue you're seeing.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7052`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true });
  await mongoose.connection.dropDatabase();

  const LayerGroupSchema = new Schema({
    name: String,
    symbol: {
        type : mongoose.ObjectId,
        ref  : 'Symbol'
    },
    layers: [{
        name: String,
        meta: {
            type : mongoose.ObjectId,
            ref  : 'Meta'
        }
    }]
  },{ collection: 'layergroups' });

  const LayerGroup = mongoose.model('LayerGroup', LayerGroupSchema);
  const Meta = mongoose.model('Meta', Schema({ name: String }));

  const metas = await Meta.create([{ name: 'test1' }, { name: 'test2' }]);
  const layerGroup = await LayerGroup.create({
    layers: [{ meta: metas[0]._id }, { meta: metas[1]._id }]
  });

  const doc = await LayerGroup.findOne().populate('layers.meta');
  console.log(doc.layers);
}
```

**Comment by salvatore-inclusion4** [comment]
@ghost https://nodejser.space/questions/retrieve-all-documents-in-mongoose-using-populate
