### ISSUE TITLE
noCursorTimout flag doensn't work on Aggregate

### ISSUE THREAD

**Issue by rrlevy** [Automattic/mongoose#7056]
I'm trying to make an aggregate query on a Model with the noCursorTimeout option.

However, the documented function addCursorFlag doesn't work.

I tried both:

` let cursor = Startup.aggregate(pipeline).cursor({batchSize: 100}).exec();
  cursor.addCursorFlag('noCursorTimeout', true);`
 
and 

` let cursor = Startup.aggregate(pipeline).cursor({batchSize: 100}).addCursorFlag('noCursorTimeout', true).exec();`

and they both result in the error "unrecognized field 'noCursorTimeout'"

**Comment by rrlevy** [comment]
Mongodb Version: 3.6.4 (cluster hosted on mLab)
Mongoose version: 5.2.17 (error first found on 5.1.1 before upgrading to latest) 
Nodejs version: 8.12.0 (error first found on 8.11.1 before upgrading to latest)

Stack trace: 
`
Trace: { MongoError: unrecognized field 'noCursorTimeout'
    at queryCallback (/Users/rafaellevy/repos/app-backend/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /Users/rafaellevy/repos/app-backend/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1538064381 },
  ok: 0,
  errmsg: 'unrecognized field \'noCursorTimeout\'',
  code: 9,
  codeName: 'FailedToParse',
  '$clusterTime':
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1538064381 },
     signature: { hash: [Object], keyId: [Object] } },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
    at /Users/rafaellevy/repos/app-backend/server.js:197:13
    at Layer.handle_error (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:315:13)
    at /Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:275:10)
    at /Users/rafaellevy/repos/app-backend/server.js:186:3
    at Layer.handle_error (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:315:13)
    at /Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:315:13)
    at /Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/rafaellevy/repos/app-backend/node_modules/express/lib/router/index.js:335:12)
`

**Comment by cristiprg** [comment]
@vkarpov15 that jira ticket seems fixed now

**Comment by vkarpov15** [comment]
@cristiprg I'm pretty certain the title of that issue changed from what it was when I originally linked to it. The fix for that issue was to disable cursor timeout for cursors that belong to a session, not adding a 'noCursorTimeout' flag to aggregation cursors.
