### ISSUE TITLE
TypeError: crypto.randomFillSync is not a function

### ISSUE THREAD

**Issue by jwerre** [Automattic/mongoose#7060]
I'm getting the following error:

```
TypeError: crypto.randomFillSync is not a function
    at module.exports (node_modules/nanoid/random.js:5:10)
    at module.exports (node_modules/nanoid/format.js:35:17)
    at generate (node_modules/shortid/lib/generate.js:14:21)
    at build (node_modules/shortid/lib/build.js:37:17)
    at model.generate (node_modules/shortid/lib/index.js:53:10)
    at SchemaString.SchemaType.getDefault (node_modules/mongoose/lib/schematype.js:644:27)
    at model.Document.$__buildDoc (node_modules/mongoose/lib/document.js:280:22)
    at model.Document (node_modules/mongoose/lib/document.js:73:20)
    at model.Model (node_modules/mongoose/lib/model.js:56:12)
    at new model (node_modules/mongoose/lib/model.js:3936:13)
    at Object.createModel (node_modules/mongoose/lib/queryhelpers.js:75:10)
    at completeMany (node_modules/mongoose/lib/query.js:1476:22)
    at cb (node_modules/mongoose/lib/query.js:1337:13)
    at handleCallback (node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at node_modules/mongoose/node_modules/mongodb/lib/cursor.js:861:16
    at handleCallback (node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorDeadAndNotified (node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:505:3)
    at nextFunction (node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:660:7)
    at Cursor.next [as _next] (node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:701:3)
    at fetchDocs (node_modules/mongoose/node_modules/mongodb/lib/cursor.js:857:10)
    at node_modules/mongoose/node_modules/mongodb/lib/cursor.js:880:7
    at handleCallback (node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:171:5)
    at nextFunction (node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:691:5)
    at node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:602:7
    at queryCallback (node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:232:18)
    at node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

```

Looks like `crypto.randomFillSync`  wasn't added until `v7.10.0`. I'm using Node `v6.10`. Which version of monoose is compatible with Node v6?

**Please mention your node.js, mongoose and MongoDB version.**
Node: v6.10.3
Mongoose: v4.13.15
MongoDB: v3.4.14

**Comment by jwerre** [comment]
I've switch to mongoose `v4.11.14` & `v4.12.6` still running into the same issue.

**Comment by lineus** [comment]
@jwerre Mongoose 4 and 5 both work on node 6, it's your dependency nanoid that is calling `crypto.randomFillSync()` and hence is incompatible with node 6.

**Comment by jwerre** [comment]
My fault, I guess I should have looked at mongoose dependancies instead of just the stack trace. This is coming from me using `shortId` on one of my schemas:

        shortId = require('shortid')

	let schema = new Schema({
	  id: {
	    type: String,
	    unique: true,
	    "default": shortId.generate
	  }
	});

**Comment by lineus** [comment]
Oh yeah, that makes sense. It looks like older versions of shortid don't pull in nanoid, you might be able to get away with shortid@2.1 below or upgrade to a newer version of node.
