### ISSUE TITLE
Cyclic dependency detected, no fix found 

### ISSUE THREAD

**Issue by BaileyJM02** [Automattic/mongoose#7067]
**Do you want to request a *feature* or report a *bug*?**
Report Bug

**What is the current behavior?**
It doesn't work: `Unhandled rejection at: Promise  [object Promise] reason:  Error: cyclic dependency detected`
**If the current behavior is a bug, please provide the steps to reproduce.**

```js
  let newGuild = await new GuildModel({
    id: guild.id,
    shard: guild.shard.id,
    joinedAt: guild.joinedAt,
    channels: guild.channels,
    members: guild.members,
    roles: guild.roles,
    name: guild.name,
    region: guild.region,
    ownerID: guild.ownerID,
    iconURL: guild.iconURL,
    hidden: false
  });
  
  newGuild.save()
  .then(doc => {
    process.send({name:"info", msg:`${doc}`})
  })
```
On ` newGuild.save()` is when it seems to error.

**What is the expected behavior?**
Save to the collection.

**Please mention your node.js, mongoose and MongoDB version.**
Node.js: 10
Mongoose: 5.3.0
MongoDB: 3.1.6 (latest NPM release)

**Comment by lineus** [comment]
@BaileyJM02 There's nothing obviously wrong in the snippet above, unless `GuildModel` is just a Model constructor created with `mongoose.model` in which case the await isn't necessary ( this isn't the cause of your issue though ). A simple script that creates a new instance and saves it works as expected ( see below ).

Can you share a more complete example that demonstrates the error and include the stack trace? 

Here's an example example:

### 7067.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const GH = 'gh7067';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

async function run() {
  assert.strictEqual(mongoose.version, '5.3.0');
  assert.strictEqual(process.version, 'v10.11.0');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const test = new Test({ name: 'test1' });
  let doc = await test.save();
  assert.ok(doc);
  assert.strictEqual(doc.name, 'test1');
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```
### Output:
```
issues: ./7067.js
All Assertions Pass.
issues:
```

**Comment by BaileyJM02** [comment]
I’ll upload the rest of my code in a minute 👍

**Comment by BaileyJM02** [comment]
## mongo.js
```js
const mongoose = require('mongoose');

const args = process.argv.slice(2);
const environment = args[0] ? args[0].toLowerCase() : console.log("No Environment") & process.exit();
const config = require(`../Config/config.${environment}`).mongo;

mongoose.customURL = `mongodb://${config.username}:${config.password}@${config.host}:27017/${config.database}`;


module.exports = mongoose;
```
## hue.js
```js
const mongoose = require('../Utilities/mongo');
[...]
await mongoose.connect(`${mongoose.customURL}`, {useNewUrlParser: true, keepAlive: true, keepAliveInitialDelay: 300000, autoIndex: false}, function (err, database) {
        if(err) {
          process.send({name: "error", msg: "Database error!"+err});
          throw err;
        };
        process.send({name: "info", msg: "Database ready!"});
      });
```
## guild.js
```js
const mongoose = require('mongoose')
const Schema = mongoose.Schema;

let guildSchema = new Schema({
  id:  String,
  shard: Number,
  joinedAt: Number,
  channels: Schema.Types.Mixed,
  members: Schema.Types.Mixed,
  roles: Schema.Types.Mixed,
  name: String,
  region: String,
  ownerID: String,
  iconURL: String,
  hidden: Boolean,
  stats: {
    members: Number,
  },
});

module.exports = mongoose.model('Guild', guildSchema);
```
## guildCreate.js
(event)
```js
const GuildModel = require('../../Utilities/models/guild');

module.exports = async (bot, guild) => {
  process.send({name:"info", msg:`${guild}`})

  let newGuild = await new GuildModel({
    id: guild.id,
    shard: guild.shard.id,
    joinedAt: guild.joinedAt,
    channels: guild.channels,
    members: guild.members,
    roles: guild.roles,
    name: guild.name,
    region: guild.region,
    ownerID: guild.ownerID,
    iconURL: guild.iconURL,
    hidden: false
  });
  
  newGuild.save()
  .then(doc => {
    process.send({name:"info", msg:`${doc}`})
  })
};
```

**Comment by BaileyJM02** [comment]
## Stack Trace
```prolog
Unhandled rejection at: Promise  [object Promise] reason:  Error: cyclic dependency detected
    at serializeObject (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:334:34)
    at serializeInto (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:836:17)
    at serializeObject (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/home/bailey/Documents/Code/Node.js/Hue/Utilities/node_modules/bson/lib/bson/parser/serializer.js:728:17)
```

**Comment by lineus** [comment]
@BaileyJM02 what are you passing into the function that guildCreate.js exports? Can you provide the data that causes the error?

**Comment by BaileyJM02** [comment]
It just exports the code as a function so it can be binded to the event guildCreate.

**Comment by lineus** [comment]
@BaileyJM02 I've got some time to look at this, but the example you provided isn't quite enough to go on **for me**. 

>It just exports the code as a function so it can be binded to the event guildCreate.

Knowing what gets passed in as the value of `guild` when this event fires and fails might help get us closer to an answer.

**Comment by BaileyJM02** [comment]
Sure, I’ll get the now 👍

**Comment by BaileyJM02** [comment]
@lineus this is the object passed into `guild`
```js
Guild {
  id: '476386947913351168',
  shard: [Object],
  joinedAt: 1533652881562,
  channels: [Object],
  members: [Object],
  memberCount: 12,
  roles: [Object],
  name: 'Hue',
  region: 'london',
  ownerID: '398197113495748626',
  icon: 'e028b7b9e619ba0f7a4709c169ec10c8',
  features: [],
  emojis: [],
  afkTimeout: 300,
  defaultNotifications: 1,
  systemChannelID: '481868770986688522' }
```

**Comment by lineus** [comment]
@BaileyJM02 You're using `process.send()` from both hue.js and guildCreate.js, those IPC calls suggest that you're using one or more child processes to run this. Rather than make guesses as to how you have that setup, it would be easier if you could share the code that runs all of this. Is that possible?

**Comment by BaileyJM02** [comment]
@lineus Please see [my repo](https://github.com/BaileyJM02/Hue/tree/Bot). I have moved `../../Utilities/mongo.js` etc. to the base to make it simpler.

**Comment by lineus** [comment]
@BaileyJM02 [Here is a gist](https://gist.github.com/lineus/f37bc994bf2bb4a1926c2417c967a300) that shows it working for me. 

I had to guess at some of your input data, and I didn't use eris/eris-sharder as I'm not sure how to start reproducing this in a reasonable way using those packages. I substituted just using a child process wrapper around index.js instead.

It's probably intentional, but I didn't see hue.js in the repo, so there could be some more stuff going on there? I'm not sure.

**Comment by vkarpov15** [comment]
I would do a close `require('util').inspect()` on the object you're passing in to guildModel, there's likely a circular object in there somewhere. 

Also, you don't need to do `await new guildModel`, calling the mongoose model constructor is synchronous, `save()` is async

**Comment by BaileyJM02** [comment]
**Update:** Turns out this was an error with the data I was passing into the schema, not an error with the package 👍
