### ISSUE TITLE
Timestamps error when updating document field

### ISSUE THREAD

**Issue by tsybinAndrey** [Automattic/mongoose#7086]
```javascript
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

run().catch(error => console.error(error.stack));

async function run() {
  const connection = await mongoose.createConnection('mongodb://localhost:27017/test');
  await connection.dropDatabase();

  const userSchema = new Schema({
    email: { type: String },
    info: {
      name: {type: String}
    }
  },
  { timestamps: true });
  const User = connection.model('User', userSchema);

  await User.create({ email: 'test' });

  const found = await User.findOne()
  found.info.name ="New User Name"
  await found.save()

  console.log('done');
}
```

_Originally posted by @vkarpov15 in https://github.com/Automattic/mongoose/issues/7084#issuecomment-426448395_

It's strange but when I run it from one file everything work OK.
I've got User.js
```javascript
const { Schema } = require('mongoose');
const { connection } = require('./db').someDb;

const userSchema = new Schema({
  email: { type: String }
}, { timestamps: true });

function addUser() {
  return this.save();
}
function getUserByEmail(email) {
  return this.findOne({ email });
}

userSchema.statics.getUserByEmail = getUserByEmail;
userSchema.methods.addUser = addUser;

const User = connection.model('User', userSchema);

module.exports = User;
```
And your script
```javascript
const User = require('./User');

const run = async () => {
  const u = await new User({
    email: 'email@email',
  }).addUser();

  const found = await User.getUserByEmail('email@email');
  found.email = 'New User';
  await found.save();

  console.log('done');
};

run().catch(error => console.error(error.stack));
```
it throws 
```
INFO Connection to MongoDb established
TypeError: (intermediate value)(intermediate value)(intermediate value).constructor.base.now is not a function
    at model.<anonymous> (/node_modules/mongoose/lib/schema.js:865:24)
    at callMiddlewareFunction (/node_modules/kareem/index.js:474:23)
    at model.next (/node_modules/kareem/index.js:58:7)
    at _next (/node_modules/kareem/index.js:106:10)
    at process.nextTick (/node_modules/kareem/index.js:499:38)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by lineus** [comment]
@tsybinAndrey what's in your `./db` file? This example works for me on `@5.3.1`:

### index.js
```js
#!/usr/bin/env node
'use strict';

const User = require('./user');

const run = async () => {
  await new User({
    email: 'email@email',
  }).addUser();

  const found = await User.getUserByEmail('email@email');
  found.email = 'New User';
  await found.save();

  console.log('done');
};

run().catch(error => console.error(error.stack));
```
### user.js
```js
'use strict';

const { Schema } = require('mongoose');
const { connection } = require('./db');

const userSchema = new Schema({
  email: { type: String }
}, { timestamps: true });

function addUser() {
  return this.save();
}
function getUserByEmail(email) {
  return this.findOne({ email });
}

userSchema.statics.getUserByEmail = getUserByEmail;
userSchema.methods.addUser = addUser;

const User = connection.model('User', userSchema);

module.exports = User;
```
### db.js
```js
'use strict';

const mongoose = require('mongoose');
const URL = 'mongodb://localhost:27017/gh7086';
const OPTS = { useNewUrlParser: true };
module.exports = {
  connection: mongoose.createConnection(URL, OPTS)
};

```

### Output:
```
7086: ./index.js
done
^C
7086:
```

**Comment by tsybinAndrey** [comment]
I've got something like this
### db.js
```javascript
const mongoose = require('mongoose');
const config = require('./config');

mongoose.Promise = global.Promise;

class MongoClass {
  constructor(config) {
    this.url = `mongodb://${config.host}:${config.port}/${config.db}`;
    this.options = {
      w: 1,
      poolSize: config.poolSize || 5,
      autoReconnect: true,
      authSource: config.authSource && config.authSource,
      useNewUrlParser: true,
      auth: {
        user: config.user && config.user,
        password: config.password && config.password,
      },
    };
    this.connection = mongoose.createConnection(this.url, this.options);
  }
}

function startDbs() {
  const Db = new MongoClass(config.mongo);
  console.info('INFO', 'Connection to MongoDb fizkultMongoDb established');
  return {
    Db,
  };
}
module.exports = startDbs();
```

**Comment by tsybinAndrey** [comment]
Worked it out. Problem was in project structure.
