### ISSUE TITLE
Update command with timestamps on parent schema against an array nested in array throws exception

### ISSUE THREAD

**Issue by jakesjews** [Automattic/mongoose#7106]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running an update command against a double nested array when the parent schema uses timestamps throws an exception `TypeError: Cannot read property 'schema' of undefined` The bug appeared in version 5.3.0.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
      const subSub = new Schema({
        x: String
      });

      const sub = new Schema({
        name: String,
        subArr: [subSub]
      });

      const schema = new Schema({
        name: String,
        arr: [sub]
      }, { timestamps: true });

      const Test = db.model('gh6532', schema);

      const test = {
        name: 'Xyz',
        arr: [{
          name: 'abc',
          subArr: [{ x: 'a' }]
        }]
      };

      const cond = { name: 'Xyz', arr: { $elemMatch: { name: 'abc' } } };
      const set = { $set: { 'arr.$.subArr': [{ x: 'b' }] } };

      Test.create(test).
        then(function() {
          return Test.updateOne(cond, set);
        }).
        then(function() {
          return Test.collection.findOne({});
        }).
        then(function(found) {
          assert.ok(Array.isArray(found.arr));
          assert.strictEqual(found.arr[0].subArr[0].x, 'b');
          done();
        }).
        catch(done);
```

**What is the expected behavior?**
The update doesn't throw an exception

**Please mention your node.js, mongoose and MongoDB version.**
Node 10.11.0, Mongoose 5.3.2, MongoDB 4.0.2

**Comment by lineus** [comment]
confirmed with:

### 7106.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '7106';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const subSub = new Schema({
  x: String
});

const sub = new Schema({
  name: String,
  subArr: [subSub]
});

const schema = new Schema({
  name: String,
  arr: [sub]
}, { timestamps: true });

const Test = mongoose.model('test', schema);

const test = {
  name: 'Xyz',
  arr: [{
    name: 'abc',
    subArr: [{ x: 'a' }]
  }]
};

const cond = { name: 'Xyz', arr: { $elemMatch: { name: 'abc' } } };
const set = { $set: { 'arr.$.subArr': [{ x: 'b' }] } };

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Test.create(test).
    then(function () {
      return Test.updateOne(cond, set);
    }).
    then(function () {
      return Test.collection.findOne({});
    }).
    then(function (found) {
      assert.ok(Array.isArray(found.arr));
      assert.strictEqual(found.arr[0].subArr[0].x, 'b');
      console.log('All Assertions Pass.');
    });
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return connection.close();
}
```
### Output:
```
issues: ./7106.js
TypeError: Cannot read property 'schema' of undefined
    at applyTimestampsToChildren (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/helpers/update/applyTimestampsToChildren.js:67:40)
    at model.Query._setTimestampsOnUpdate (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/schema.js:906:5)
    at callMiddlewareFunction (/Users/lineus/dev/node/mongoose/node_modules/kareem/index.js:474:23)
    at next (/Users/lineus/dev/node/mongoose/node_modules/kareem/index.js:58:7)
    at Kareem.execPre (/Users/lineus/dev/node/mongoose/node_modules/kareem/index.js:86:8)
    at Kareem.wrap (/Users/lineus/dev/node/mongoose/node_modules/kareem/index.js:265:8)
    at model.Query._updateOne (/Users/lineus/dev/node/mongoose/node_modules/kareem/index.js:375:11)
    at _update (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3660:20)
    at model.Query.Query.updateOne (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3557:10)
    at utils.promiseOrCallback (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3779:19)
    at Promise (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/utils.js:246:5)
    at new Promise (<anonymous>)
    at Object.promiseOrCallback (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/utils.js:245:10)
    at model.Query.exec (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3773:16)
    at model.Query.Query.then (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3807:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
issues:
```
