### ISSUE TITLE
Document SchemaType Object not working as expected

### ISSUE THREAD

**Issue by Daniel-M** [Automattic/mongoose#7109]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The documentation for mongoose schema types [states that for mixed schema types](https://mongoosejs.com/docs/schematypes.html):

> Mixed
> An "anything goes" SchemaType, its flexibility comes at a trade-off of it being harder to maintain. Mixed is available either through Schema.Types.Mixed or by passing an empty object literal. The following are equivalent:
> 
> var Any = new Schema({ any: {} });
> var Any = new Schema({ any: Object });
> var Any = new Schema({ any: Schema.Types.Mixed });

I'm working with a document schemaType which goes like this,

```
const myDocSchema = new mongoose.Schema(
{
   ...
    'AField' : [ Object ],
   ...
})
```

When doing, after a `myDocSchema.findById(...)`

```
myDocSchemaInstance.AField = ArrayOfValidThings
```

I get an error,

```
{ ValidationError: Student validation failed: AField: Cast to Array failed for value "[ { field: 'value' } ]" at path "AField"
    at ValidationError.inspect (/home/daniel/Sandbox/student_api_mongodb/node_modules/mongoose/lib/error/validation.js:59:24)
    at formatValue (util.js:400:38)
    at inspect (util.js:294:10)
    at format (util.js:161:12)
    at Console.log (console.js:130:21)
    at putStudentByID (/home/daniel/Sandbox/student_api_mongodb/routes/students.js:305:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  errors: 
   { AFiel: 
      { CastError: Cast to Array failed for value "[ { field: 'value' } ]" at path "AField"
    at new CastError (/home/daniel/Sandbox/student_api_mongodb/node_modules/mongoose/lib/error/cast.js:29:11)
    at model.$set (/home/daniel/Sandbox/student_api_mongodb/node_modules/mongoose/lib/document.js:931:7)
    at model.set [as AField] (/home/daniel/Sandbox/student_api_mongodb/node_modules/mongoose/lib/helpers/document/compile.js:124:26)
    at putStudentByID (/home/daniel/Sandbox/student_api_mongodb/routes/students.js:290:31)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
        message: 'Cast to Array failed for value "[ { field: \'value\' } ]" at path "AField"',
        name: 'CastError',
        stringValue: '"[ { field: \'value\' } ]"',
        kind: 'Array',
        value: [Array],
        path: 'AField',
        reason: [Object] } 
```

 unless I change the schema to 

```
const myDocSchema = new mongoose.Schema(
{
   ...
    'AField' : [ Schema.Types.Mixed ],
   ...
})
```
So the operation
```
myDocSchemaInstance.AField = ArrayOfValidThings
```
works as expected, updating the underlying array of Objects

**What is the expected behavior?**
Update the underlying array of object

**Please mention your node.js, mongoose and MongoDB version.**
* NodeJS 8.10 with NVM 0.33.11
* mongoose 5.2.13
* Mongo v3.6.5

Is this a bug or I did something wrong?

**Comment by lineus** [comment]
confirmed with

### 7109.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '7109';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const schema = new Schema({
  arr1: [Schema.Types.Mixed],
  arr2: [{}],
  arr3: [Object]
});

const Test = mongoose.model('test', schema);

const test = new Test({ 
  arr1: [ 'test1', { two: 'three'}, [ 4, 'five', 6 ] ],
  arr2: [ 'test2', { three: 'four' }, [5, 'six', 7] ],
  arr3: [ 'test3', { four: 'five' }, [6, 'seven', 8] ]
});

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  doc.arr1 = [ '111', { twotwotwo: 333 }, [ '444', 555, '666' ] ];
  await doc.save();
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e.message);
  return connection.close();
}
```
### Output:
```
issues: ./7109.js
test validation failed: arr3: Cast to Array failed for value "[ 'test3', { four: 'five' }, [ 6, 'seven', 8 ] ]" at path "arr3"
issues:
```
