### ISSUE TITLE
Error in castUpdate when updating Map type field

### ISSUE THREAD

**Issue by farwayer** [Automattic/mongoose#7111]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

```js
const Account = new mongoose.Schema({
  balance: Number,
});

const Schema = new mongoose.Schema({
  accounts: {type: Map, of: Account},
});

const User = mongoose.model('User', Schema);

(async () => {
  await User.update(
    {},
    {accounts: {'USD': {balance: 100}}});
})();
```

```js
TypeError: Cannot read property 'selected' of undefined
    at Embedded.cast (node_modules/mongoose/lib/schema/embedded.js:170:47)
    at Embedded.SchemaType.applySetters (node_modules/mongoose/lib/schematype.js:757:12)
    at Map.set (node_modules/mongoose/lib/types/map.js:60:11)
    at Map.$__runDeferred (node_modules/mongoose/lib/types/map.js:104:12)
    at new MongooseMap (node_modules/mongoose/lib/types/map.js:21:10)
    at SchemaMap.cast (node_modules/mongoose/lib/schema/map.js:25:12)
    at SchemaMap.SchemaType.applySetters (node_modules/mongoose/lib/schematype.js:757:12)
    at SchemaMap.SchemaType._castForQuery (node_modules/mongoose/lib/schematype.js:1143:15)
    at SchemaMap.SchemaType.castForQuery (node_modules/mongoose/lib/schematype.js:1133:15)
    at SchemaMap.SchemaType.castForQueryWrapper (node_modules/mongoose/lib/schematype.js:1112:15)
    at castUpdateVal (node_modules/mongoose/lib/helpers/query/castUpdate.js:411:19)
    at walkUpdatePath (node_modules/mongoose/lib/helpers/query/castUpdate.js:180:22)
    at castUpdate (node_modules/mongoose/lib/helpers/query/castUpdate.js:79:18)
    at model.Query._castUpdate (node_modules/mongoose/lib/query.js:3852:10)
    at castDoc (node_modules/mongoose/lib/query.js:3880:18)
    at model.Query._updateThunk (node_modules/mongoose/lib/query.js:3235:17)
    at model.Query.Query._execUpdate (node_modules/mongoose/lib/query.js:3296:23)
    at process.nextTick (node_modules/kareem/index.js:369:33)
```

**What is the expected behavior?**

Look like invalid number of arguments passed to `castUpdateVal()` in `lib/helpers/query/castUpdate.js`.
```js
obj[key] = castUpdateVal(schematype, val, op, context, prefix + key);
...
function castUpdateVal(schema, val, op, $conditional, context, path) {
...
```
`context` is string instead of Query in result.

**Please mention your node.js, mongoose and MongoDB version.**

```
node v10.11.0
mongoose@5.3.2
```

**Comment by lineus** [comment]
@farwayer I wasn't able to replicate the **exact** error you saw, I do however get a different error with the following script. Can you edit this script to reproduce the error you're seeing? As a workaround, it looks like using dot notation in the query works. ( if you comment out the failing query below and uncomment the query with dot notation the tests pass. )

### 7111.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '7111';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const accountSchema = new Schema({
  balance: Number
});

const schema = new Schema({
  accounts: {
    type: Map,
    of: accountSchema
  }
});

const Test = mongoose.model('test', schema);

const test = new Test({ accounts: { USD: { balance: 345 }} });

async function run() {
  assert.strictEqual(mongoose.version, '5.3.2');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.strictEqual(doc.accounts.get('USD').balance, 345);

  await Test.updateOne({}, { accounts: { USD: { balance: 8 } } });
  // await Test.updateOne({}, { 'accounts.USD.balance': 8 });
  let updated = await Test.findOne({ _id: doc._id });
  assert.strictEqual(updated.accounts.get('USD').balance, 8);

  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return connection.close();
}
```
### Output:
```
issues: ./7111.js
TypeError: this.$__parent.invalidate is not a function
    at Map.set (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/types/map.js:62:24)
    at Map.$__runDeferred (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/types/map.js:104:12)
    at new MongooseMap (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/types/map.js:21:10)
    at SchemaMap.cast (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/schema/map.js:25:12)
    at SchemaMap.SchemaType.applySetters (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/schematype.js:757:12)
    at SchemaMap.SchemaType._castForQuery (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/schematype.js:1143:15)
    at SchemaMap.SchemaType.castForQuery (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/schematype.js:1133:15)
    at SchemaMap.SchemaType.castForQueryWrapper (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/schematype.js:1112:15)
    at castUpdateVal (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/helpers/query/castUpdate.js:411:19)
    at walkUpdatePath (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/helpers/query/castUpdate.js:180:22)
    at castUpdate (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/helpers/query/castUpdate.js:79:18)
    at model.Query._castUpdate (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3852:10)
    at castDoc (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3880:18)
    at model.Query._updateThunk (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3235:17)
    at model.Query.Query._updateOne (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/query.js:3318:23)
    at process.nextTick (/Users/lineus/dev/node/mongoose/node_modules/kareem/index.js:369:33)
issues:
```

**Comment by farwayer** [comment]
@lineus you got cascade error from `catch` block https://github.com/Automattic/mongoose/blob/5.3.2/lib/types/map.js#L62
Initial error is from `applySetters` in `try`
