### ISSUE TITLE
Multiple Queries one the same object sometimes do not give a result

### ISSUE THREAD

**Issue by TheTaz25** [Automattic/mongoose#7146]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Using `find(...)` on a Model causes not to find something while executing multiple queries on the same search
**If the current behavior is a bug, please provide the steps to reproduce.**
Schema> Ingredients.js:
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

const ingredientSchema = new Schema({
  _id: Schema.Types.ObjectId,
  name: String
});

mongoose.model('ingredients', ingredientSchema);
```
Schema> User.js:
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

const userSchema = new Schema({
  _id: Schema.Types.ObjectId,
  passwordHash: String,
  userName: String,
  shoppingList: [{_id: Schema.Types.ObjectId,
    name: String,
    amount: Number,
    unit: String}]
});

mongoose.model('users', userSchema);
```
When a user tries to add an Ingredient to their shoppingList, my Backend checks the Ingredient-Database if the name is already used, by Querying for `{name: req.body.ingredient_name}`. If I fire multiple events, the search ends up empty and thus creating a new Ingredient that is already in the database but with a new ID and saves the new Ingredient-ID into the array of the user causing multiple Ingredients with the same name showing up in the list.
I initiate the mongoose connection in my index.js file with `mongoose.connect(...)`;
Repo is under: https://github.com/TheTaz25/ShoppingList , however here is the query in question:
```js
  // Put Ingredients to my shopping list
  app.put('/ingredients', async (req, res) => {
    // console.log(req.session.userName);
    // console.log("Received Put!");
    let user;
    await User.findOne({userName: req.session.userName}, (err, data) => {
      // console.log(err);
      // console.log(data);
      if(!err){
        user = data;
      } else {
        // console.log("User not found!");
        res.status(400).send("User not found!");
        return;
      }
    });
    // console.log("User is: " + user);
    const ingredient_name = req.body.ingredient.toLowerCase();
    const ingredient_id = req.body.ingredient_id;
    const amount = req.body.amount;
    const unit = req.body.unit;
    let newID = ingredient_id;
    let foundIngredient;
    if(!ingredient_id){
      console.log("User did not know ingredientID");
      try {
        await Ingredient.findOne({name: ingredient_name}, (err, data) => {
          if(!err && data){
            foundIngredient = data;
          } else {
            console.log(err);
            console.log(data);
          }
        });
      }catch(e){console.log(e);}
      if(!foundIngredient){
        // create new Ingredient and remember it's ID
        newID = mongoose.Types.ObjectId();
        const newIngredient = new Ingredient({
          _id: newID,
          name: ingredient_name
        });
        await newIngredient.save();
      } else {
        newID = foundIngredient._id;
      }
    }
    console.log("107:" + newID);
    const tmp = {
      _id: newID,
      name: ingredient_name,
      amount: amount,
      unit: unit
    };
    let alreadyInList = false;
    let c;
    console.log("116:" + tmp.ingredient);
    console.log("117:" + user.shoppingList);
    console.log("118:" + tmp.id);
    for(c = 0; c < user.shoppingList.length; c++){
      console.log("ID: " + user.shoppingList[c]._id + ' of ' + user.shoppingList[c].name);
      try {
        if(user.shoppingList[c]._id.toString() == tmp._id.toString()){
          alreadyInList = true;
          break;
        }
      } catch(e){
        console.log(e);
      };
    }
    console.log(ingredient_name + " Already in List: " + alreadyInList);
    if(alreadyInList && tmp._id){ // Ingredient is already in List
      if(user.shoppingList[c].unit !== tmp.unit){ // Units do not match
        let newAmount = recalcUnit(tmp.unit, user.shoppingList[c].unit, tmp.amount);
        user.shoppingList[c].amount = parseInt(user.shoppingList[c].amount) + parseInt(newAmount);
      } else { // Units do match
        user.shoppingList[c].amount = parseInt(user.shoppingList[c].amount) + parseInt(tmp.amount);
      }
    } else if(tmp._id){ // Ingredient is new in List
      user.shoppingList.push(tmp);
    } else {
      console.log("Missing ID!");
    }
    // console.log(user.shoppingList);
    user.save(function(err, user){
      // console.log(user.shoppingList);
      res.send(user.shoppingList)
    });
  });
```

**What is the expected behavior?**
`Ingredients.find(...)` should return an element that is already in the database but is not. (Under "heavy" use --> multiple requests per second)
**Please mention your node.js, mongoose and MongoDB version.**
Node: 10.11.0
mongoose: 5.3.4
MongoDB: Using for development reasons a Docker-Container from the docker-library (docker pull mongo). Using tag "LATEST"

**Comment by lineus** [comment]
@TheTaz25 You are using both the promise and callback simultaneously in many places, e.g. here:
```js
    let user;
    await User.findOne({userName: req.session.userName}, (err, data) => {
      // console.log(err);
      // console.log(data);
      if(!err){
        user = data;
      } else {
        // console.log("User not found!");
        res.status(400).send("User not found!");
        return;
      }
    });
```
The promise may resolve before the callback runs, resulting in unexpected behavior. In addition, using the promise and the callback will send 2 queries each time to the db.

Instead use **either** the callback or the promise, something like:
```js
    let user = await User.findOne({userName: req.session.userName});
    if(!user){
      // console.log("User not found!");
      res.status(400).send("User not found!");
    }
    ...
```

Also, If you're going to use asynchronous route handlers in express you might want to [check out this blog post](https://thecodebarbarian.com/introducing-await-js-express-async-support-for-express-apps.html) and [the corresponding library](https://github.com/vkarpov15/awaitjs-express).

**Comment by lineus** [comment]
Here is a script that shows what I mean by using the callback and promise simultaneously has unpredictable results:

### promiseAndCallback.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = 'promiseAndCallback';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const schema = new Schema({
  name: String
});

let findOneOps = 0;

schema.pre('findOne', function() {
  findOneOps++;
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

// The idea behind resultsHasTwoInARow is that using the promise and callback
// simultaneously is unpredictable. If this returns true looping
// over the 100 queries, then the order of completion (promise vs callback)
// changed from one run to the next.

const results = [];
function resultsHasTwoInARow() {
  let last;
  let twoInARow = false;
  results.forEach((r, i) => {
    if (i === 0) {
      last = r;
      return;
    } else {
      if (last === r) {
        twoInARow = true;
      }
      last = r;
    }
  });
  return twoInARow;
}

async function fiftyQueries() {
  const junk = ' '.repeat(50).split('');
  for (let _ of junk) {
    await Test.findOne({}, callback).then(promise).catch(error);
  }
  return Promise.resolve(true);
}

function callback() {
  results.push('callback');
}

function promise() {
  results.push('promise');
}

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  await fiftyQueries();

  // despite the assumption that we're only
  // sending 50 queries, because we're using the
  // promise and callback simultaneously, We're actually
  // sending 100 queries to the db.
  assert.strictEqual(findOneOps, 100);
  
  // verify that each callback and promise updated the results array.
  assert.strictEqual(results.length, 100);

  // I expect that at some point during the 50 calls to Model.findOne,
  // at least one of the promises will return before the callback.
  // This assertion passes a little over 75% of the time ( 16/20 runs passed. )
  assert.strictEqual(resultsHasTwoInARow(), true);

  console.log('All Assertions Pass.');
  await connection.close();
}


run().catch(error);

function error(e) {
  console.error(e.stack);
  return connection.close();
}
```
### Output 75% of the time:
```
ideas: ./promiseAndCallback.js
All Assertions Pass.
ideas:
```
### Output 25% of the time:
```
ideas: ./promiseAndCallback.js
AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- false
+ true
    at run (/Users/lineus/dev/node/mongoose/ideas/promiseAndCallback.js:82:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ideas:
```

**Comment by TheTaz25** [comment]
Thank you for the feedback @lineus . Currently rewriting a lot of the code and also saving some lines (so far everything works smooth :D)
Had a look at awaitjs but it seems I'm doing something wrong with that lib, however I did not have problems with raw async in express so far, so I'll leave that as is.

Thank you a lot for the help and have a nice day!
