### ISSUE TITLE
Bug: Model.ReplaceOne() fails to update timestamps

### ISSUE THREAD

**Issue by teddis** [Automattic/mongoose#7152]
I'm using replaceOne() for the first time and timestamps are being stripped and not added to the document even though the Schema specifies the timestamps property:

     await RestModel.replaceOne({_id: rest.id}, rest.toObject()).exec();

I would expect Mongoose/MongoDB to respect this setting and properly update createdAt and updatedAt fields.

Using Mongoose 5.3.4, MongoDB 3.6.6, Typegoose 5.4.1, Typescript 3.1.1, and Node 10.11.0 on Mac OS X Mojave.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate. Can you post your schema please? That will help move this along

**Comment by teddis** [comment]
Sure, I hope this helps, though the Schema is generated by Typegoose. 

```
import * as mongoose from 'mongoose';
import * as findOrCreate from 'mongoose-findorcreate';
import {instanceMethod, InstanceType, plugin, post, pre, prop, staticMethod, Typegoose} from "typegoose";

@plugin(findOrCreate)

export class Rest extends Typegoose {
    @prop()
    public _id: string;

    // virtual property
    @prop()
    get id(this: TRest) {
        return this._id;
    }

    set id(this: TRest, i) {
        this._id = i;
    }

    // Merchant App Id
    @prop({default: ''})
    public merchantId: string;

    // Merchant App Name
    @prop({default: ''})
    public merchantName: string;

    @prop()
    public createdAt?: Date;

    @prop()
    public updatedAt?: Date;

    public static findOrCreate: (condition: object, doc?: object, options?: object) => Promise<{ doc: InstanceType<Rest>, created: boolean }>;
}

export type TRest = InstanceType<Rest>;

export const RestModel = new Rest().getModelForClass(Rest, {
    existingMongoose: mongoose,
    schemaOptions: {
        collection: 'rests',
        emitIndexErrors: true,
        timestamps: {createdAt: true, updatedAt: true},
        minimize: false,
        versionKey: false
    }
});
RestModel.createIndexes();
```

**Comment by teddis** [comment]
Also, I was wondering why the Mongoose replaceOne() method doesn't appear to accept options where MonoDB's does.

**Comment by lineus** [comment]
@vkarpov15 Here's a repro script for this.
@teddis The second `replaceOne` call below shows an example using options, [these are the relevant ones](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#replaceOne). What option were you having trouble with?

### 7152.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '7152';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };
const errors = [];
const schema = new Schema({
  name: String
}, { timestamps: true });

schema.methods.testForTimestamps = function() {
  try{
    assert.ok(this.createdAt && this.updatedAt, 'replaceOne did not add timestamps');
  }catch(e) {
    errors.push({ name: this.name, err: e });
  }
};

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Test.create(test);

  let doc = await Test.findOne({ name: 'test1' });
  assert.ok(doc);
  doc.testForTimestamps();

  await Test.replaceOne({ name: 'test1' }, { name: 'test2'});
  doc = await Test.findOne({ name: 'test2' });
  assert.strictEqual(doc.name, 'test2');
  doc.testForTimestamps();

  await Test.replaceOne({ name: 'test1' }, { name: 'test3' }, { upsert: true });
  doc = await Test.findOne({ name: 'test3' });
  assert.strictEqual(doc.name, 'test3');
  doc.testForTimestamps();
  
  if (!errors.length) {
    console.log('All Assertions Pass.');
  } else {
    errors.forEach(o => {
      console.error(`${o.name}:`, o.err);
    });
  }
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e.stack);
  return connection.close();
}
```
### Output:
```
issues: ./7152.js
test2: { AssertionError [ERR_ASSERTION]: replaceOne did not add timestamps
    at model.schema.methods.testForTimestamps (/Users/lineus/dev/node/mongoose/issues/7152.js:17:12)
    at run (/Users/lineus/dev/node/mongoose/issues/7152.js:37:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '==' }
test3: { AssertionError [ERR_ASSERTION]: replaceOne did not add timestamps
    at model.schema.methods.testForTimestamps (/Users/lineus/dev/node/mongoose/issues/7152.js:17:12)
    at run (/Users/lineus/dev/node/mongoose/issues/7152.js:41:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '==' }
issues:
```

**Comment by vkarpov15** [comment]
Just FYI, Mongoose does **not** support `import * as mongoose from 'mongoose'` in general. [Use `import mongoose from 'mongoose'` instead](https://www.npmjs.com/package/mongoose#importing). See [FAQ](https://mongoosejs.com/docs/faq.html#destructured-imports).

**Comment by teddis** [comment]
Terrific. Btw, I get `Error:(2, 8) TS1192: Module '"mongoose"' has no default export` when using import mongoose from 'mongoose'.
