### ISSUE TITLE
setName from ismaster does not match provided connection setName

### ISSUE THREAD

**Issue by jonaswindey** [Automattic/mongoose#7167]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Connection to a replica cluster gives error
`setName from ismaster does not match provided connection setName [475bfca3040d4b3dac793cf5bb68612a] != [475]`

What's weird is that it tries to compare the guid with 475, like it has been split up.

Full stack:

```{ MongoError: setName from ismaster does not match provided connection setName [475bfca3040d4b3dac793cf5bb68612a] != [475]
    at ReplSetState.update (/Users/jonas/Development/lexusnet/node_modules/mongodb-core/lib/topologies/replset_state.js:403:14)
    at /Users/jonas/Development/lexusnet/node_modules/mongodb-core/lib/topologies/replset.js:809:45
    at applyAuthenticationContexts (/Users/jonas/Development/lexusnet/node_modules/mongodb-core/lib/topologies/replset.js:731:12)
    at Server.<anonymous> (/Users/jonas/Development/lexusnet/node_modules/mongodb-core/lib/topologies/replset.js:802:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at /Users/jonas/Development/lexusnet/node_modules/mongodb-core/lib/topologies/server.js:508:16
    at /Users/jonas/Development/lexusnet/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Connect to a replica cluster like the following:
mongodb://***:***@lon5-c11-0.mongo.objectrocket.com:43304,lon5-c11-1.mongo.objectrocket.com:43304,lon5-c11-2.mongo.objectrocket.com:43304/test?replicaSet=475bfca3040d4b3dac793cf5bb68612a

**What is the expected behavior?**
It should connect as in v4

**Please mention your node.js, mongoose and MongoDB version.**
node v8.11.3 / mongoDB 3.4.10

**Comment by lineus** [comment]
@jonaswindey, I am able to reproduce this using only the native driver,  `useNewUrlParser: true `, and passing your replicaSet name in the connection string. This appears to be a bug in the new url parser. I will either open an issue with the driver folks or submit a patch.

In the meantime, passing your replicaSet name in the connection options instead of the connection string is probably the best workaround. 

# This Fails

### 7167.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const L = 'localhost';
const D = '7167';
const R = '475bfca3040d4b3dac793cf5bb68612a';
const URI = `mongodb://${L}:27017,${L}:27018,${L}:27019/${D}?replicaSet=${R}`;

const OPTS = { family: 4, useNewUrlParser: true };

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e.stack);
  return connection.close();
}
```
### Output:
```
issues: ./7167.js
MongoError: no primary found in replicaset or invalid replica set name
    at /Users/lineus/dev/node/mongoose/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/replset.js:636:11
    at Server.<anonymous> (/Users/lineus/dev/node/mongoose/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/replset.js:357:9)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at /Users/lineus/dev/node/mongoose/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:508:16
    at /Users/lineus/dev/node/mongoose/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
issues:
```
# This Works

### 7167.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const L = 'localhost';
const D = '7167';
const R = '475bfca3040d4b3dac793cf5bb68612a';
const URI = `mongodb://${L}:27017,${L}:27018,${L}:27019/${D}`;

const OPTS = {
  family: 4,
  useNewUrlParser: true,
  replicaSet: R
};

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e.stack);
  process.exit(1);
}
```
### Output:
```
issues: ./7167.js
All Assertions Pass.
issues:
```

### my local replicaSet for posterity's sake:
```
issues: mongo --quiet
475bfca3040d4b3dac793cf5bb68612a:PRIMARY> db.serverStatus().version
3.4.10
475bfca3040d4b3dac793cf5bb68612a:PRIMARY> rs.isMaster()
{
        "hosts" : [
                "127.0.0.1:27017",
                "127.0.0.1:27018",
                "127.0.0.1:27019"
        ],
        "setName" : "475bfca3040d4b3dac793cf5bb68612a",
        "setVersion" : 1,
        "ismaster" : true,
        "secondary" : false,
        "primary" : "127.0.0.1:27017",
        "me" : "127.0.0.1:27017",
        "electionId" : ObjectId("7fffffff0000000000000001"),
        "lastWrite" : {
                "opTime" : {
                        "ts" : Timestamp(1540745743, 1),
                        "t" : NumberLong(1)
                },
                "lastWriteDate" : ISODate("2018-10-28T16:55:43Z")
        },
        "maxBsonObjectSize" : 16777216,
        "maxMessageSizeBytes" : 48000000,
        "maxWriteBatchSize" : 1000,
        "localTime" : ISODate("2018-10-28T16:55:47.681Z"),
        "maxWireVersion" : 5,
        "minWireVersion" : 0,
        "readOnly" : false,
        "ok" : 1
}
475bfca3040d4b3dac793cf5bb68612a:PRIMARY>
issues:
```

**Comment by lineus** [comment]
Here's my native driver script

### 7167_native.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const { MongoClient } = require('mongodb');

const L = 'localhost';
const D = 'gh-7167';
const R = '475bfca3040d4b3dac793cf5bb68612a';
const URI = `mongodb://${L}:27017,${L}:27018,${L}:27019/${D}?replicaSet=${R}`;
const OPTS = { family: 4, useNewUrlParser: true };

const pkg = require.resolve('mongodb').replace(/\/[^/]*$/, '/package.json');
const ver = require(pkg).version;
const client = new MongoClient(URI, OPTS);

async function run() {
  console.log(`version: ${ver}`);
  await client.connect();
  const db = client.db('gh-7167');
  await db.dropDatabase();
  const coll = db.collection('tests');
  await coll.insertOne({ name: 'Billy' });
  const found = await coll.findOne({});
  assert.ok(found);
  assert.strictEqual(found.name, 'Billy');
  return client.close();
}

run().catch(error);

function error(e) {
  console.error(e.stack);
  process.exit(1);
}
```
### Output:
```
issues: ./7167_native.js
version: 3.1.8
MongoError: no primary found in replicaset or invalid replica set name
    at /Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/topologies/replset.js:636:11
    at Server.<anonymous> (/Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/topologies/replset.js:357:9)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at /Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/topologies/server.js:508:16
    at /Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
issues:
```
*Moving the replicaSet name to the options here also works*
**This shows that even the latest version 3.1.8 of the native driver is still effected by this.**

**Comment by MasterProgrammer200** [comment]
We are still having this issue in mongoose v5.4.19

**Comment by vkarpov15** [comment]
@MasterProgrammer200 it looks like your replica set name is wrong, and it also looks like you're connecting to a sharded cluster rather than a replica set. Why do you have `replicaSet: 'rs'` in your options? Try removing that.

**Comment by MasterProgrammer200** [comment]
@vkarpov15 replicaSet: 'rs' came from a tutorial that used run-rs to create local replica sets. I guess I didn't realize it wasn't needed for MongoDb Atlas. Removing it fixed the problem. Thanks!

**Comment by vkarpov15** [comment]
Ah ok. Can you point me to the tutorial you were looking at?

**Comment by MasterProgrammer200** [comment]
@vkarpov15 of course!

https://thecodebarbarian.com/a-node-js-perspective-on-mongodb-4-transactions.html 

// Boilerplate: connect to DB
const mongoose = require('mongoose');
const uri = 'mongodb://localhost:27017,localhost:27018,localhost:27019/txn';
await mongoose.connect(uri, { replicaSet: 'rs' });
