### ISSUE TITLE
Can't find any possibility to handle UnhandledPromiseRejectionWarning after reconection period

### ISSUE THREAD

**Issue by andrew-polyansky** [Automattic/mongoose#7265]
**Do you want to request a *feature* or report a *bug*?**

Looks like bug

**What is the current behavior?**
1. Mongoose successfully connected to MongoDB
2. Mongoose lost connection 
3. Mongoose try to reconnect
4. After `reconnectTries` by `reconnectInterval` if connection still losted - throw `UnhandledPromiseRejectionWarning`:
```
 (node:2388) UnhandledPromiseRejectionWarning: MongoError: failed to reconnect after 30 attempts with interval 1000 ms
     at Connection.<anonymous> (/usr/src/app/node_modules/winston-mongodb/node_modules/mongodb-core/lib/connection/pool.js:318:15)
     at Connection.emit (events.js:182:13)
     at Socket.<anonymous> (/usr/src/app/node_modules/winston-mongodb/node_modules/mongodb-core/lib/connection/connection.js:189:49)
     at Object.onceWrapper (events.js:273:13)
     at Socket.emit (events.js:182:13)
     at emitErrorNT (internal/streams/destroy.js:82:8)
     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
     at process._tickCallback (internal/process/next_tick.js:63:19)
 (node:2388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
5. This error doesn't trigger `.on('error')` event
**If the current behavior is a bug, please provide the steps to reproduce.**

*Code:*
```js
   let odm = mongoose.createConnection(...odmConnectingParams);

    mongoose.connection.on('error', (err) => {
        logger.info('Mongoose level error');
        logger.error(err);
    });

    odm.on('connecting', () => logger.info(`MongoDB connecting to ${odm.host}:${odm.port}`));

    odm.on('error', (err) => {
         logger.error(err);
    });

    odm.on('close', (err) => {
        logger.info('MongoDB connection closed');
        logger.error(err);
    });

    odm.on('connected', () => logger.info(`MongoDB connected successfully to ${odm.host}:${odm.port}`));

    odm.once('open', () => logger.info(`MongoDB opened successfully on ${odm.host}:${odm.port}`));

    odm.on('reconnected', () => logger.info(`MongoDB reconnected to ${odm.host}:${odm.port}.`));

    odm.on('timeout', () => logger.warn(`MongoDB timeout on ${odm.host}:${odm.port}.`));

    odm.on('disconnected', () => logger.warn(`MongoDB connection lost to ${odm.host}:${odm.port}.`));
```

**What is the expected behavior?**
The error should trigger `.on('error')` event

**Please mention your node.js, mongoose and MongoDB version.**
NodeJs: 10.13.0
mongoose: 5.3.12
mongo: 4.0

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap

**Comment by vkarpov15** [comment]
Looking more closely, the stack trace shows this is an issue with winston-mongodb, not mongoose. I don't get any unhandled rejections with the below:

```javascript
const winston = require('winston');

const mongoose = require('mongoose');

require('winston-mongodb');

mongoose.connect('mongodb://bad.domain:27017').catch(err => console.log(err));

winston.add(new winston.transports.MongoDB({ db: mongoose.connection }));
```

```
$ node gh-7265.js 
(node:5255) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
winston-mongodb: error initialising logger from promise { MongoNetworkError: failed to connect to server [bad.domain:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND bad.domain bad.domain:27017]
    at Pool.<anonymous> (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
{ MongoNetworkError: failed to connect to server [bad.domain:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND bad.domain bad.domain:27017]
    at Pool.<anonymous> (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
```

**Comment by vkarpov15** [comment]
Can you please clarify your version of winston-mongodb and provide more detailed code samples?
