### ISSUE TITLE
Error: server instance pool was destroyed

### ISSUE THREAD

**Issue by Pazitos10** [Automattic/mongoose#7285]
I'm having this issue in a local installation of the latest version of mongoose (5.3.14). I've made a script to populate a database that is similar to this:

```js
const dbURI = 'mongodb://localhost/my_database'
mongoose.connect(dbURI, { useNewUrlParser: true})

const customSchema = new mongoose.Schema({
  fieldA: String,
  fieldB: String,
  fieldC: String
});

const customModel = mongoose.model('customModel', customSchema);

// ...
const saveInDB = (valueA,valueB, valueC) => {

  const newModel = new customModel()
  newModel.fieldA = valueA
  newModel.fieldB = valueB
  newModel.fieldC = valueC
  
  newModel.save(err => {
    if (err) { console.log(err) }
  })
}
```
Then, inside a map callback function I call `saveInDB()` with the real data as I am creating it. 
After the loop ends, if I try to close the connection using `mongoose.connection.close()`, something goes wrong and I get a lot of messages like this:

```
{ MongoError: server instance pool was destroyed
    at basicWriteValidations (/home/user/project/app/node_modules/mongodb-core/lib/topologies/server.js:700:41)
    at Server.insert (/home/user/project/app/node_modules/mongodb-core/lib/topologies/server.js:805:16)
    at Server.insert (/home/user/project/app/node_modules/mongodb/lib/topologies/topology_base.js:321:25)
    at insertDocuments (/home/user/project/app/node_modules/mongodb/lib/operations/collection_ops.js:821:19)
    at insertOne (/home/user/project/app/node_modules/mongodb/lib/operations/collection_ops.js:851:3)
    at executeOperation (/home/user/project/app/node_modules/mongodb/lib/utils.js:420:24)
    at Collection.insertOne (/home/user/project/app/node_modules/mongodb/lib/collection.js:463:10)
    at NativeCollection.(anonymous function) [as insertOne] (/home/user/project/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:146:28)
    at NativeCollection.Collection.doQueue (/home/user/project/app/node_modules/mongoose/lib/collection.js:126:30)
    at immediate (/home/user/project/app/node_modules/mongoose/lib/collection.js:86:24)
    at process.internalTickCallback (internal/process/next_tick.js:70:11) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
```
In addition, the script execution ends abruptly and nothing is written in the database. Whereas if I do not call `mongoose.connection.close()`, the data is saved successfully but my script never ends so I have to kill it using `ctrl+c`. 

Is there something I'm doing wrong? How should I do the disconnection? 

Thanks in advance!

**Comment by mhombach** [comment]
Can you please provide a complete script for reproducing this issue? I have a feeling that the problem lies within some asynchronous codeexecution issue, wich i can't verify without a complete script with the part where you call the `saveInDb` and where you close the db-connection.

**Comment by Pazitos10** [comment]
@mhombach thanks for replying, I edited my first comment with more code. I think you are right about my asynchronous code execution issue and I share your opinion.

**Comment by mhombach** [comment]
Yep, as i thought, you are not handling async actions very well ;)
You might want to have a look at `Promises` (JS) and `async/await` (JS). Just search for some youtube tutorial. I would suggest that you first try to understand `Promises` in JS and after that learning `async/await` syntax. This will also help you in other places. You are using a synchronous filewrite in your code for example, with correct async syntax you get much more performance.
Please don't forget to close this issue if you don't have any other question :)
