### ISSUE TITLE
Nested property named `get` is not throwing an error

### ISSUE THREAD

**Issue by Yaty** [Automattic/mongoose#7316]
Hello,

Thanks for mongoose !

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`RangeError: Maximum call stack size exceeded` when using `save()`, i.e : 

```
RangeError: Maximum call stack size exceeded
      at Document.get (...\node_modules\mongoose\lib\helpers\document\compile.js:120:20)
      ...
      at docReducer (...\node_modules\mongoose\lib\document.js:2342:27)
      at ...\node_modules\mongoose\lib\document.js:2372:18
      at Array.reduce (<anonymous>)
      at docReducer (...\node_modules\mongoose\lib\document.js:2371:33)
      at ...\node_modules\mongoose\lib\document.js:2381:12
      at Array.reduce (<anonymous>)
      at model.Document.$__getAllSubdocs (...\node_modules\mongoose\lib\document.js:2380:42)
      at model.$session (...\node_modules\mongoose\lib\document.js:654:26)
      at _init (...\node_modules\mongoose\lib\query.js:2578:12)
      at model.Document.init (...\node_modules\mongoose\lib\document.js:435:5)
      at completeOne (...\node_modules\mongoose\lib\query.js:2568:12)
      at model.Query.Query._completeOne (...\node_modules\mongoose\lib\query.js:1901:7)
      at Immediate.Query.base.findOne.call (...\node_modules\mongoose\lib\query.js:1943:10)
      at Immediate._onImmediate (...\node_modules\mquery\lib\utils.js:116:16)
      at runCallback (timers.js:785:20)
      at tryOnImmediate (timers.js:747:5)
      at processImmediate [as _immediateCallback] (timers.js:718:5)
```

```js
const schema = new mongoose.Schema({
  http: {
    get: {
      type: Number,
      required: true,
    },
  },
});
```

**What is the expected behavior?**

To have an error when booting to warn me about the reserved key I'm using.

**Please mention your node.js, mongoose and MongoDB version.**
Node 8.8.1
mongoose 5.3.13
MongoDB 3.4.9

**Comment by Yaty** [comment]
Oh I found : https://mongoosejs.com/docs/api.html#schema_Schema.reserved
No error is thrown to warn me when it's nested, I'm renaming this issue.

**Comment by vkarpov15** [comment]
The [`Schema.reserved` property you mentioned](https://mongoosejs.com/docs/api.html#schema_Schema.reserved) only applies to the top level of the schema. It is perfectly fine to have a nested property named `save`. With :point_up: , you should be fine to have a nested property named `get` as well.

**Comment by Yaty** [comment]
Thanks ! :+1:
