### ISSUE TITLE
TypeError: process.nextTick is not a function

### ISSUE THREAD

**Issue by adityaraval** [Automattic/mongoose#7320]
I am using     `"mongoose": "^5.3.15"`

```
TypeError: process.nextTick is not a function
    at model.Query._findOne (/Users/e9ine/Desktop/test-app/node_modules/kareem/index.js:369:15)
    at model.Query.Query.findOne (/Users/e9ine/Desktop/test-app/node_modules/mongoose/lib/query.js:2027:8)
    at Function.findOne (/Users/e9ine/Desktop/test-app/node_modules/mongoose/lib/model.js:1874:13)
    at startupJobs (/Users/e9ine/Desktop/test-app/cron/startup/StartUpJobs.js:9:13)
    at Object.<anonymous> (/Users/e9ine/Desktop/test-app/server.js:37:1)
    at Module._compile (internal/modules/cjs/loader.js:651:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by mhombach** [comment]
We need your code snippet to help you. Without code, nobody can help you.
Also: Please make sure that the error you get is mongoose/mongoDB related. `process.nextTick()` is a native nodeJS function, which itself has nothing to do with the framework/ORM you are posting this issue to :)

**Comment by adityaraval** [comment]
```
module.exports = function (listOfUsers) {
	User.findOne({}, (err, user) => {
		if (err || !user) {
			console.log(err);
		} else {
			for (let key in listOfUsers) {
				if (listOfUsers.hasOwnProperty(key)) {
					initUser(user, 'Schedule');
				}
			}
		}
	})
}
```


When I am calling this function in my main file(express server.js) it gives me above error on findOne.

**Comment by mhombach** [comment]
@adityaraval Can you also provide the code-snippet where you call that function? And also please list all mongoose-plugins/-middleware you are using, if any :)

**Comment by adityaraval** [comment]
server.js

```
let express = require('express');
let bodyParser = require('body-parser');
let mongoose = require('mongoose');
let path = require('path');
let cors = require('cors');
let methodOverride = require('method-override');

require('dotenv').config();

let app = express();
let port = process.env.PORT;

app.use(bodyParser.urlencoded({
    extended: true,
    limit: '50mb'
}));
app.use(bodyParser.json({
    limit: '50mb'
}));

app.use(express.static(path.join(__dirname, 'public')));

app.use(methodOverride('X-HTTP-Method-Override'));

app.use(cors());

mongoose.connect(process.env.DATABASE, {
    useNewUrlParser: true
});

global.mongoose = mongoose;

app.listen(port, () => {
    console.log('Application started at PORT ' + port);

});

var startupUsers = require('./cron/startup/StartUpUsers');
startupJobs();

exports = module.exports = app;
```

package.json

```
{
  "name": "test-app",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.18.3",
    "cors": "^2.8.5",
    "cron": "^1.6.0",
    "dotenv": "^6.2.0",
    "express": "^4.16.3",
    "kue": "^0.11.6",
    "method-override": "^3.0.0",
    "mongoose": "^5.3.15",
    "request": "^2.88.0"
  }
}

```
