### ISSUE TITLE
Bson serialization error introduced in version 5.2.9

### ISSUE THREAD

**Issue by RasmusFredensborg** [Automattic/mongoose#7345]
Hi,
Thank you for an amazing framework! 
I recently did an update from 5.0.3 to 5.3.14, and started seeing a **bug** on $set queries using the dot notation, e.g.:
```
return Course.findByIdAndUpdate(courseId,
            {
                $set: {
                    "engagement.lastActive": moment.now()
                }
            });
```
The error I get is this:
```
Error: key engagement.lastActive must not contain '.'
    at serializeInto (/emento/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:914:19)
    at serializeObject (/emento/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/emento/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at serializeObject (/emento/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/emento/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:728:17)
    at serializeObject (/emento/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:348:18)
    at serializeInto (/emento/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:938:17)
    at BSON.serialize (/emento/node_modules/mongodb-core/node_modules/bson/lib/bson/bson.js:63:28)
    at Query.toBin (/emento/node_modules/mongodb-core/lib/connection/commands.js:145:25)
    at serializeCommands (/emento/node_modules/mongodb-core/lib/connection/pool.js:1044:43)
    at Pool.write (/emento/node_modules/mongodb-core/lib/connection/pool.js:1260:3)
    at executeWrite (/emento/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:147:10)
    at WireProtocol.insert (/emento/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:158:3)
    at Server.insert (/emento/node_modules/mongodb-core/lib/topologies/server.js:815:35)
    at Server.insert (/emento/node_modules/mongodb/lib/topologies/topology_base.js:321:25)
    at insertDocuments (/emento/node_modules/mongodb/lib/operations/collection_ops.js:822:19)
    at insertOne (/emento/node_modules/mongodb/lib/operations/collection_ops.js:852:3)
    at executeOperation (/emento/node_modules/mongodb/lib/utils.js:420:24)
    at Collection.insertOne (/emento/node_modules/mongodb/lib/collection.js:463:10)
    at NativeCollection.(anonymous function) [as insertOne] (/emento/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:143:28)
    at model.Model.$__handleSave (/emento/node_modules/mongoose/lib/model.js:182:21)
    at model.Model.$__save (/emento/node_modules/mongoose/lib/model.js:251:8)
    at /emento/node_modules/kareem/index.js:278:20
    at _next (/emento/node_modules/kareem/index.js:102:16)
    at process.nextTick (/emento/node_modules/kareem/index.js:452:38)
    at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) {}
```
I've isolated the version where the bug was introduced by trial and error, and I found that the bug is introduced in version 5.2.9, as version 5.2.8 is the latest version where I do not get the error. I've verified that the bug is present from version 5.2.9 all the way up to version 5.4.0. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Do a $set query using the dot notation (to update a nested object) using Mongoose v. >= 5.2.9

**What is the expected behavior?**
The nested object is updated correctly and no exception is thrown
**Please mention your node.js, mongoose and MongoDB version.**
- node.js: v8.11.2
- mongoose: v5.2.9
- MongoDB: v3.4

**Comment by vkarpov15** [comment]
Can you please post your schema for `engagement` as well?

**Comment by vkarpov15** [comment]
The below script works without error:

```javascript
const assert = require('assert');
const moment = require('moment');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7345`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    engagement: {
      lastActive: Date
    }
  });
  const Test = mongoose.model('Test', schema);

  const doc = await Test.create({ engagement: { lastActive: new Date() } });

  await Test.findByIdAndUpdate(doc._id, {
    $set: {
      'engagement.lastActive': moment.now()
    }
  });
}
```

Output:

```
$ node gh-7345.js 
(node:4269) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Mongoose: tests.insertOne({ _id: ObjectId("5c3a9ed93beed810adbdf980"), engagement: { lastActive: new Date("Sun, 13 Jan 2019 02:13:45 GMT") }, __v: 0 })
Mongoose: tests.findAndModify({ _id: ObjectId("5c3a9ed93beed810adbdf980") }, [], { '$set': { 'engagement.lastActive': new Date("Sun, 13 Jan 2019 02:13:45 GMT") } }, { new: false, upsert: false, projection: {} })
(node:4269) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
done
^C
$ 
```

Please modify the above script to repro your issue.

**Comment by raha1923** [comment]
Hi @vkarpov15, I have this problem too and I can't fix it right now. you can use this schema:
```
const schema = new Schema({
    engagement: {
      lastActive: Date
    },
    test: PropSchema.Types.Mixed
  });
```
Then you can try to save the following doc:

```
await Test.findByIdAndUpdate(doc._id, {
    $set: {
      'engagement.lastActive': moment.now(),
      test: {
        'first.name': 'data'
      }
    }
  });
```

**Comment by mhombach** [comment]
@raha1923 Can you add the exact errormessage you are getting?

**Comment by mhombach** [comment]
@raha1923 I assume your issue is solved already, otherwise I guess you would have responded here to get further help.

**Comment by vkarpov15** [comment]
@raha1923 please open a new issue and follow the issue template.
