### ISSUE TITLE
[has tests] virtual field { count: true } populated with populate().execPopulate() is null unless .toJSON() is called before

### ISSUE THREAD

**Issue by the-vampiire** [Automattic/mongoose#7380]
**Please mention your node.js, mongoose and MongoDB version.**
MongoDB: `v4.0.3`
Mongoose: `v5.4.0`
NodeJS: `v10.1.0`

**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the expected behavior?**
I expected the virtual `{ count: true }` field to be accessible via dot syntax on the populated document resolved by `populate().execPopulate()`.

**What is the current behavior?**
populating a virtual count field with `count: true` returns `null` on the populated document unless it is first converted to JSON with `.toJSON()`. This behavior is unlike populating the related documents themselves which are accessible on the populated document without transformation.

**If the current behavior is a bug, please provide the steps to reproduce.**

## Here is a test script that shows the discrepancy in behaviors:
- requires a test database URI in `process.env.TEST_DB_URI`

I have presented two simple models `Parent` and `Child`. 
Parent has two virtual fields
- `children` related children documents themselves
- `childrenCount` a `count: true` virtual for the count of related children documents. 

Parent has 4 methods to illustrate the discrepencies. All 4 methods begin with `this.populate().execPopulate()` and differ in how they attempt to return the value. I did this to ensure the issue was not caused by native JS:
- `getChildren()`: returns the populated `children` field [Child]
  - returns: `.then(populatedDoc => populatedDoc.children)`
- `getCountThen()`: populates the `childrenCount` field and attempts to return its value in a `.then()`
  - returns: `.then(populatedDoc => populatedDoc.childrenCount)`
- `getCountAsync()`: populates the `childrenCount` field using `async/await` and attempts to return its field value on the awaited document
  - returns: `populatedDoc.childrenCount`
- `getCountAfterJSON()`: populates the `childrenCount` field and returns its value after converting the populated document using `.toJSON()`
  - returns: `populatedDoc.toJSON().childrenCount`
```js
require('dotenv').config();
const mongoose = require('mongoose');

const parentSchema = new mongoose.Schema({
  name: String,
});

parentSchema.virtual('children', {
  ref: 'children',
  localField: '_id',
  foreignField: 'parent',
});

parentSchema.virtual('childrenCount', {
  ref: 'children',
  localField: '_id',
  foreignField: 'parent',
  count: true,
});

parentSchema.methods.getChildren = function getChildren() {
  return this.populate('children').execPopulate()
    .then(populatedDoc => populatedDoc.children);
}

parentSchema.methods.getCountThen = function getCountThen() {
  return this.populate('childrenCount').execPopulate()
    .then(populatedDoc => populatedDoc.childrenCount);
}

parentSchema.methods.getCountAsync = async function getCountAsync() {
  const populatedDoc = await this.populate('childrenCount').execPopulate();
  return populatedDoc.childrenCount;
}

parentSchema.methods.getCountAfterJSON = async function getCountAfterJSON() {
  const populatedDoc = await this.populate('childrenCount').execPopulate();
  return populatedDoc.toJSON().childrenCount;
}

const Parent = mongoose.model('parents', parentSchema);

const childSchema = new mongoose.Schema({
  parent: { type: mongoose.SchemaTypes.ObjectId, ref: 'parents' },
});
const Child = mongoose.model('children', childSchema);

describe('virtual field population unexpected behavior', () => {
  let parent;
  let childrenCount;
  let thenResult;
  let asyncResult;
  let jsonResult;
  let childrenResult;
  beforeAll(async () => {
    mongoose.connect(process.env.TEST_DB_URI, { useNewUrlParser: true });
    
    parent = await Parent.create({ name: 'hubert' });
    
    childrenCount = 3;
    await Promise.all(
      Array(childrenCount)
        .fill(null)
        .map(() => Child.create({ parent })),
    );

    thenResult = await parent.getCountThen();
    asyncResult = await parent.getCountAsync();
    jsonResult = await parent.getCountAfterJSON();
    childrenResult = await parent.getChildren();
  });

  afterAll(() => mongoose.connection.close());

  describe('virtual count field { count: true }', () => {
    test(
      `getCountThen(): returns the number of children documents [${childrenCount}]`,
      () => expect(thenResult).toBe(childrenCount),
    );
  
    test(
      `getCountAsync(): returns the number of children documents [${childrenCount}]`,
      () => expect(asyncResult).toBe(childrenCount),
    );
  
    test(
      `getCountAfterJSON(): returns the number of children documents [${childrenCount}]`,
      () => expect(jsonResult).toBe(childrenCount),
    );
  });

  describe('virtual documents field { count: undefined }', () => {
    test('getChildren(): returns an Array of Child documents', () => {
      expect(childrenResult.length).toBe(childrenCount);
    });
  });
});
```

## Jest Output:
```sh
FAIL  ./sample.test.js
  virtual field population unexpected behavior
    virtual count field { count: true }
      ✕ getCountThen(): returns the number of children documents [3] (10ms)
      ✕ getCountAsync(): returns the number of children documents [3] (1ms)
      ✓ getCountAfterJSON(): returns the number of children documents [3]
    virtual documents field { count: undefined }
      ✓ getChildren(): returns an Array of Child documents

  ● virtual field population unexpected behavior › virtual count field { count: true } › getCountThen(): returns the number of children documents [3]

    expect(received).toBe(expected) // Object.is equality

    Expected: 3
    Received: null

    Difference:

      Comparing two different types of values. Expected number but received null.

      75 |     test(
      76 |       `getCountThen(): returns the number of children documents [${childrenCount}]`,
    > 77 |       () => expect(thenResult).toBe(childrenCount),
         |                                ^
      78 |     );
      79 |
      80 |     test(

      at Object.toBe (sample.test.js:77:32)

  ● virtual field population unexpected behavior › virtual count field { count: true } › getCountAsync(): returns the number of children documents [3]

    expect(received).toBe(expected) // Object.is equality

    Expected: 3
    Received: null

    Difference:

      Comparing two different types of values. Expected number but received null.

      80 |     test(
      81 |       `getCountAsync(): returns the number of children documents [${childrenCount}]`,
    > 82 |       () => expect(asyncResult).toBe(childrenCount),
         |                                 ^
      83 |     );
      84 |
      85 |     test(

      at Object.toBe (sample.test.js:82:33)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        1.02s, estimated 2s
Ran all test suites matching /sample.test.js/i.
```

**Comment by the-vampiire** [comment]
this is in contrast to the [documentation example](https://github.com/Automattic/mongoose/commit/0bfe622e57bf995aae66a71f2f63246f05565f41)
```js
  BandSchema.virtual('numMembers', {
      ref: 'Person', // The model to use
      localField: 'name', // Find people where `localField`
      foreignField: 'band', // is equal to `foreignField`
      count: true // And only get the number of docs
    });

    // Later
    const doc = await Band.findOne({ name: 'Motley Crue' }).
      populate('numMembers');
    doc.numMembers; // 2
```

although to be fair this may be because I am populating an existing document vs populating on the Query object as in the example
