### ISSUE TITLE
Mongoose Multi-Document Transactions not Working

### ISSUE THREAD

**Issue by skatestyle** [Automattic/mongoose#7387]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am using mongoose transactions for handling a payment.

However, my problem is, that my implementation of Promise.all() doesn't seem to work with mongoose transactions. The issue probably comes from using multiple Schemas with one session or creating an array of documents.

**Here is how my current implementation looks like.**

```
const session = await mongoose.startSession()
session.startTransaction()
try {
    const udpated = await Schema1.findByIdAndUpdate(
        'id', { $set: { /* ... */ } }, { session }
    )
    const array = await Promise.all(
        updated.array.map(async item => {
            const doc = await Schema2.findById(item.someId)
            const payload = { /* ... */ }
            return Schema3.createa(payload, { session })
        })
    )
    await session.commitTransaction()
    session.endSession()
} catch (err) {
    await session.abortTransaction()
    session.endSession()
    throw err
}

I am getting errors, that the validation of Schema3 failed for some required paths. Even though payload is found when console.log it.

```
**What is the expected behavior?**
When refactoring the code without using mongoose transactions, everything works just fine:

```
try {
    const udpated = await Schema1.findByIdAndUpdate(
        'id', { $set: { /* ... */ } }
    )
    const array = await Promise.all(
        updated.array.map(async item => {
            const doc = await Schema2.findById(item.someId)
            const payload = { /* ... */ }
            return Schema3.createa(payload)
        })
    )
} catch (err) {
    throw err
}
```

**Please mention your node.js, mongoose and MongoDB version.**
mongoose": "^5.3.15
mongodb: sorry I don't know (I use mongodb atlas, so I guess it's the newest version)

**Comment by vkarpov15** [comment]
Ah I see the issue. Do `return new Schema3(payload).save({ session })` or `return Schema3.create([payload], { session }).then(res => res[0])` instead. [`Model.create()` does not allow you to pass in options if you're passing a spread of documents](https://mongoosejs.com/docs/api.html#model_Model.create), when you do `Model.create(a, { session })` Mongoose thinks you're trying to create 2 docs.

**Comment by skatestyle** [comment]
That certainly changes something. But now I am getting a timeout error:
```
{
    MongoError: internal atlas error checking things: Failure getting dbStats: read tcp 192.168.254.116:52242->192.168.254.116:27000: i/o timeout
    at /some-path/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/some-path/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/some-path/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/some-path/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at TLSSocket.<anonymous> (/some-path/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:597:20)
  ok: 0,
  errmsg: 'internal atlas error checking things: Failure getting dbStats: read tcp 192.168.254.116:52242->192.168.254.116:27000: i/o timeout',
  code: 8000,
  codeName: 'AtlasError',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
× Unexpected error occured MongoError: internal atlas error checking things: Failure getting dbStats: read tcp 192.168.254.116:52242->192.168.254.116:27000: i/o timeout
    at /some-path/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/some-path/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/some-path/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/some-path/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at TLSSocket.<anonymous> (/some-path/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:597:20)
```

**Comment by vkarpov15** [comment]
That is very strange, looks like an error in MongoDB Atlas. Did you also change `await Schema2.findById(item.someId)` to `await Schema2.findById(item.someId, null, { session })`? That's another bug.
