### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Guts** [Automattic/mongoose#7392]
**bug or bad usage**

**What is the current behavior?**

Launching the application (expressjs) crashes the node process and write a redundant exception. I've already read about the [similar issues](https://github.com/Automattic/mongoose/issues?utf8=%E2%9C%93&q=is%3Aissue+Maximum+call+stack+size+exceeded) but I can't find any solution.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm connecting to the database using this module:

```js
const logger = require("./logger")(module);
const mongoose = require("mongoose");
const uriFormat = require('mongodb-uri');

mongoose.Promise = global.Promise;

// ensure URI encoding
function encodeMongoURI(urlString) {
    if (urlString) {
        let parsed = uriFormat.parse(urlString);
        urlString = uriFormat.format(parsed);
    }
    return urlString;
}

module.exports = function (options) {

    const mongoOptions = {
        appname: "WebApp",
        dbName: options.mongodbAppDb,
        autoIndex: false, // Don't build indexes
        useNewUrlParser: true,   // use recomended mongodb URI format
        useCreateIndex: true,
        keepAlive: true,
        keepAliveInitialDelay: 300000,
        connectTimeoutMS: 30000,
        auto_reconnect: true,
        reconnectTries: 30, // Retry up to 30 times
        reconnectInterval: 500, // Reconnect every 500ms
        poolSize: 15, // Maintain up to 15 socket connections
        bufferMaxEntries: 0 // If not connected, return errors immediately rather than waiting for reconnect
    };

    // open connection
    mongoose.connect(encodeMongoURI(options.mongodbUrl), mongoOptions, function (err) {
        if (err) return logger.error(err);
        logger.info("Connection to the database passed: " + options.mongodbUrl );
    });

    require('./models/subscription')(options);
    require('./models/dataset')(options);
    require('./models/pdataset')(options);
    require('./models/geodatabase')(options);
    require('./models/request')(options);
    require('./models/entry-point')(options);

};
```

```log
error: uncaughtException: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at clone (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:183:31)
    at cloneObject (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:294:11)
    at clone (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:202:16)
    at cloneObject (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:294:11)
    at clone (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:202:16)
    at cloneObject (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:294:11)
    at clone (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:202:16)
    at cloneObject (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:294:11)
    at clone (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:202:16)
    at cloneObject (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:294:11)
    at clone (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:202:16)
    at cloneObject (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:294:11)
    at clone (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:202:16)
    at cloneObject (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:294:11)
    at clone (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:202:16)
    at cloneObject (C:\Users\nodapps\webapp\node_modules\mongoose\lib\utils.js:294:11)
```

**What is the expected behavior?**

Do not crash the process or a more comprehensive error message.

**Environment**

* node.js 8.11.1
* mongoose 5.4.2
* MongoDB 3.6.6 (MMAPv1)

**Comment by vkarpov15** [comment]
What does `encodeMongoURI()` return? Also, have you tried commenting out the individual `require(/*...*/)(options)` calls to see if the error is coming from one of those? Generally this issue comes from passing in a circular object to Mongoose as a doc or as options.

**Comment by Guts** [comment]
Ups sorry, I just realized that I forgot to answer. Really sorry, I found out the problem: it was an infinite loop into a model update func.
