### ISSUE TITLE
webpack warnign after upgrading to 5.4.5

### ISSUE THREAD

**Issue by huineng** [Automattic/mongoose#7433]
node: v11.7.0
"webpack": "^4.28.4",
"webpack-cli": "^3.2.1"
 "mongoose": "^5.4.5",
"@types/mongoose": "^5.3.8",

following warning happens after upgrading from  "mongoose": "^5.4.4" to  "mongoose": "^5.4.5",

```js
WARNING in /myapplication/mongoose/lib/index.js 8:26-62
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/myapplication/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/myapplication/webpack/lib/Compilation.js:1354:24)
    at Compilation.finish (/myapplication/webpack/lib/Compilation.js:1165:9)
    at hooks.make.callAsync.err (/myapplication/webpack/lib/Compiler.js:548:17)
    at _err0 (eval at create (/myapplication/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (/myapplication/webpack/lib/Compilation.js:1093:12)
    at processModuleDependencies.err (/myapplication/webpack/lib/Compilation.js:1005:9)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

**Comment by huineng** [comment]
gone after reinstall
