### ISSUE TITLE
When closing a change stream, the native mongodb driver included with mongoose throws an error.

### ISSUE THREAD

**Issue by pgkehle** [Automattic/mongoose#7462]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

When closing a change stream, the native mongodb driver included with mongoose throws an error.

**If the current behavior is a bug, please provide the steps to reproduce.**

In startup():

```ts
      this._changeStream = Model.collection.watch(pipeline, { fullDocument: 'updateLookup' });
      this._changeStream
        .on('change', next => {
          const { fullDocument, documentKey, operationType } = next;
          const id = documentKey ? documentKey : documentKey._id;
          if (!fullDocument || !operationType) return;

          this._runHandler(id, operationType);
        });
```

In destroy():

```ts
      await this._changeStream.close();
```

Error Output:
```
/srv/securityportal/node_modules/mongoose/node_modules/mongodb/lib/change_stream.js:372
  const options = changeStream.cursor.options;
                                      ^
TypeError: Cannot read property 'options' of undefined
    at processNewChange (/srv/securityportal/node_modules/mongoose/node_modules/mongodb/lib/change_stream.js:372:39)
    at Cursor.<anonymous> (/srv/securityportal/node_modules/mongoose/node_modules/mongodb/lib/change_stream.js:272:5)
    at Cursor.emit (events.js:182:13)
    at next (/srv/securityportal/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:1013:14)
    at err (/srv/securityportal/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)
    at executeCallback (/srv/securityportal/node_modules/mongoose/node_modules/mongodb/lib/utils.js:404:25)
    at handleCallback (/srv/securityportal/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)
    at cursor._next (/srv/securityportal/node_modules/mongoose/node_modules/mongodb/lib/operations/cursor_ops.js:186:21)
    at handleCallback (/srv/securityportal/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:203:5)
    at /srv/securityportal/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:659:16
    at queryCallback (/srv/securityportal/node_modules/mongoose/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:280:21)
    at /srv/securityportal/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Looks like the issue is fixed [here](https://github.com/mongodb/node-mongodb-native/blob/master/lib/change_stream.js#L365), but requires mongoose to update the native driver as part of the release package.

**What is the expected behavior?**
Clean Shutdown

**Please mention your node.js, mongoose and MongoDB version.**

```
node: v10.15.0
mongoose v5.4.7
 + mongodb v3.1.10 
 + mongodb-core v3.1.9

MongoDB is a cluster running v4.0.2
```

**Comment by vkarpov15** [comment]
Upgrade to Mongoose 5.4.10 for the fix. MongoDB driver 3.1.13 includes this fix: https://github.com/mongodb/node-mongodb-native/blob/master/HISTORY.md#3113-2019-01-23 and Mongoose upgraded to that version in #7488

**Comment by pgkehle** [comment]
Thank you @vkarpov15, that does fix the issue.
