### ISSUE TITLE
Throw an error if using updateOne/updateMany with overwrite: true

### ISSUE THREAD

**Issue by guischdi** [Automattic/mongoose#7475]
**Bug**:

`Model.updateOne()` with options `{ overwrite: true, upsert: true }` throws this error:
`MongoError: the update operation document must contain atomic operators.`

**Reprodruce**:

```javascript
const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/test', { useNewUrlParser: true });
mongoose.set('debug', true);

const Schema = new mongoose.Schema({ a: Number, b: Number, c: Number });
const Model = mongoose.model('test', Schema);

Model.deleteMany({})
  .then(() => Model.insertMany([{ a: 1, b: 1 }]))
  .then(() => Model.updateOne({ a: 1 }, { a: 1, c: 1 }, { upsert: true, overwrite: true, new: true }))
  .catch(console.error)
  .then(() => process.exit());
```

Leads to the following output:

```shell
Mongoose: tests.deleteMany({}, {})
Mongoose: tests.insertMany([ { _id: 5c543af34fb84afbe4f92d81, a: 1, b: 1, __v: 0 } ], {})
Mongoose: tests.updateOne({ a: 1 }, { a: 1, c: 1, __v: 0 }, { upsert: true, overwrite: true, new: true })
{ MongoError: the update operation document must contain atomic operators.
    at Function.create (/tmp/node_modules/mongodb-core/lib/error.js:43:12)
    at toError (/tmp/node_modules/mongodb/lib/utils.js:149:22)
    at checkForAtomicOperators (/tmp/node_modules/mongodb/lib/operations/collection_ops.js:161:12)
    at Collection.updateOne (/tmp/node_modules/mongodb/lib/collection.js:722:15)
    at NativeCollection.(anonymous function) [as updateOne] (/tmp/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:146:28)
    at NodeCollection.updateOne (/tmp/node_modules/mquery/lib/collection/node.js:82:19)
    at model.Query._updateThunk (/tmp/node_modules/mongoose/lib/query.js:3514:23)
    at model.Query.<anonymous> (/tmp/node_modules/mongoose/lib/query.js:3548:23)
    at model.Query._wrappedThunk [as _updateOne] (/tmp/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/tmp/node_modules/kareem/index.js:369:33)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
  driver: true,
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
```

**Expected behavior**

The document with `{ a: 1, b: 1, __v: 0 }` should have been updated to `{ a: 1, c: 1, __v: 0 }`.

**Versions**

```shell
$ node -v
v11.9.0
$ npm view mongoose version
5.4.8
$ mongo
MongoDB shell version v3.6.5
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 4.0.5
```

**Comment by vkarpov15** [comment]
This is expected behavior unfortunately. The MongoDB server replaced `update()` with `updateOne()` for several reasons, one being to disallow accidentally overwriting a doc by doing `update()` without any atomics. Mongoose already has `overwrite` for that. 

You should use [`replaceOne()`](https://mongoosejs.com/docs/api.html#query_Query-replaceOne) if you want to use `updateOne()` with `overwrite: true`. See [docs for upgrading from `update()` to `updateOne()`](https://mongoosejs.com/docs/deprecations.html#-update-).

In the meantime, we should throw an error if you pass `overwrite: true` to `updateOne()` or `updateMany()`. Hypothetically we could support `updateOne()` + `overwrite: true` by converting to `replaceOne()`, but there's no way to do that for `updateMany()` because there's no `replaceMany()`.

**Comment by guischdi** [comment]
Alright, I missed, that mongoDB deprecated `updateOne()` with `overwrite: true`. So an Error in this case would be an appropriate solution for me.
Thanks so much for having a look into this and scheduling it for next week already!
