### ISSUE TITLE
this.constructor._checkRequired is not a function

### ISSUE THREAD

**Issue by tusharf5** [Automattic/mongoose#7486]
**BUG**

When I save a document with some required attributes I get `this.constructor._checkRequired is not a function`

Link to repro - https://github.com/tusharf5/mogoose-validation-bug

```
import MFloat from 'mongoose-float';
import uuidv4 from 'uuid/v4';

const Float = MFloat.loadType(mongoose, 2);

const generateId = () => {
  return uuidv4().replace(/-/g, '');
};

const transformer = (doc, ret) => {
  delete ret._id;
  return ret;
};

const schema = new mongoose.Schema(
  {
    _id: { type: String, default: generateId },
    amount: {
      type: Float,
      required: true,
      min: 1,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true, transform: transformer },
    toObject: { virtuals: true, transform: transformer },
  }
);

export default mongoose.model('Invoice', schema);
```

```
const invoice = new Invoice({
      amount,
 });

await invoice.save();
```

The error I get is 

```
ValidationError: amount: this.constructor._checkRequired is not a function,
at new ValidationError (/path/to/app/node_modules/mongoose/lib/error/validation.js:30:11)
at model.Document.invalidate (/path/to/app/node_modules/mongoose/lib/document.js:2071:32)
at p.doValidate.skipSchemaValidators (/path/to/app/node_modules/mongoose/lib/document.js:1934:17)
```

**What is the expected behavior?**

When I switch the version to `~5.2.12`. It doesn't give any error.

MongoDB - `4.0.0`
Mongoose -  `5.4.7`
Node- `10.15.0`

**Comment by mhombach** [comment]
To reproduce this, we need the missing pieces:
- where does the schema-type "Float" come from?
- where is the code of "generateId()"?
- where is the code of "transformer"?

**Comment by tusharf5** [comment]
@mhombach Updated issue with the missing information.

**Comment by mhombach** [comment]
I cannot find your library `uuid/v4`.
Also:
`const invoice = new Invoice({
      amount,
 });`
You are not assigning any value to the "amount"-property.

If i "fix" those things mentioned, i get no error:
```js
//import uuidv4 from 'uuid/v4';

const mongoose = require('mongoose');
var Float = require('mongoose-float').loadType(mongoose, 2);
const DB = 'test_db';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };


const generateId = () => {
  //return uuidv4().replace(/-/g, '');
  return "test";
};

const transformer = (doc, ret) => {
  delete ret._id;
  return ret;
};

const schema = new mongoose.Schema(
  {
    _id: { type: String, default: generateId },
    amount: {
      type: Float,
      required: true,
      min: 1,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true, transform: transformer },
    toObject: { virtuals: true, transform: transformer },
  }
);

let Invoice = mongoose.model('Invoice', schema);

const invoice = new Invoice({
  amount: 1.5 // 1.5 gets validated, "0.5" would cause a validation-error (which is correct)
});

invoice.save().then((a,b) => {
    // ...
});
```

Can you try my code and tell me if this works for you?

**Comment by tusharf5** [comment]
Sorry for the delay. I've created a minimal repo which reproduces this issue with Instructions.

https://github.com/tusharf5/mogoose-validation-bug
