### ISSUE TITLE
Nested virtual errors

### ISSUE THREAD

**Issue by Ncifra** [Automattic/mongoose#7491]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Actually identified more than one while using virtuals.
1. Having a property defined in the schema like:
```
a: {
            b: {
                type: Boolean,
                default: false
            },
            c: Date,
            d: {},
            e: {
                type: String,
                enum: ["a", "b"]
            }
        },
```
or like
```
a: {
     type: {
            b: {
                type: Boolean,
                default: false
            },
            c: Date,
            d: {},
            e: {
                type: String,
                enum: ["a", "b"]
            }
       }
   },
```
Declaring a nested virtual like so:
```
userDataSchema.path("a").schema.virtual("f").get(function () {
    return ...;
});
```
throws an: `TypeError: Cannot read property 'schema' of undefined` on startup of the project.

Having the property as an array like below doesn't throw the error:
```
a: {
     type: [{
            b: {
                type: Boolean,
                default: false
            },
            c: Date, //not less than 24 hours from the current server time
            d: {},
            e: {
                type: String,
                enum: ["a", "b"]
            }
       }
   }],
```
I put the full nested document just in case there is a problem with a certain field.

2. Having a nested property declared like (and we can take the property `a` declaration as in the above first case):

```
userDataSchema.virtual("a.f").get(function () {
     return true; //or whatever, it doesn't matter what the return value is but there must be a return value
});
```
if we try to do a `find()` without including property `a` in the projection part, like
`User.find({_id:id}, {_id: 1})`, 
we get thrown an error:
`TypeError: Cannot set property 'f' of undefined`

mongoose: 5.4.5
MongoDB: 3.4
Node.js: 8.12.0

**Comment by vkarpov15** [comment]
The schema definition in 1.2 won't work as you expect, see these docs: https://mongoosejs.com/docs/schematypes.html#mixed

The schema definition in 1.1 won't have a schema path `a` because a nested object isn't a full schematype currently, see #7408 for more information.

Will look into point 2)

**Comment by Ncifra** [comment]
One thing to notice that maybe I left to be taken for granted: we have also added the `toJSON: {virtuals: true}` option inside the schema.

**Comment by vkarpov15** [comment]
The below script works without error for me, please modify the below script to demonstrate issue (2):

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7491`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    a: {
      b: {
        type: Boolean,
        default: false
      },
      c: Date,
      d: {},
      e: {
        type: String,
        enum: ["a", "b"]
      }
    }
  }, { toObject: { virtuals: true } });

  schema.virtual("a.f").get(function () {
     return true; //or whatever, it doesn't matter what the return value is but there must be a return value
  });

  const M = mongoose.model('Test', schema);

  await M.create({});

  const doc = await M.find().select({ a: 0 }).then(res => res[0]);

  console.log(doc.toObject({ virtuals: true }));
}
```

Output:

```
$ node gh-7491.js 
(node:30483) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Mongoose: tests.insertOne({ a: { b: false }, _id: ObjectId("5c66c6e0c82cd27713fa3eb5"), __v: 0 })
Mongoose: tests.find({}, { projection: { a: 0 } })
{ _id: 5c66c6e0c82cd27713fa3eb5,
  __v: 0,
  a: { f: true },
  id: '5c66c6e0c82cd27713fa3eb5' }
done
^C
$ 
```

**Comment by Ncifra** [comment]
All right, will try to replicate

**Comment by Ncifra** [comment]
So this is the simplified code I am using, by adding some things that may shed some light, but also without bloating it:

```
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7491`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;
const {Schema} = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
    const db = await mongoose.connect(connectionString);
    const db2 = mongoose.createConnection(`mongodb://localhost:27017/1001`);
    await mongoose.connection.dropDatabase();

    const schema = mongoose.Schema({
        a: {
            b: {
                type: Boolean,
                default: false
            },
            c: Date,
            d: {},
            e: {
                type: String,
                enum: ["a", "b"]
            }
        },
        h: String

    }, {timestamps: true,
        usePushEach: true,
        versionKey: "_userVersioning",
        toObject: {
            virtuals: true
        },
        toJSON: {
            virtuals: true
        }});

    schema.virtual("a.f").get(function () {
        return true; //or whatever, it doesn't matter what the return value is but there must be a return value
    });

    const schema2 = mongoose.Schema({
        g: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Test",
            required: true
        },
        i: String
    });

    const M = db.model('Test', schema);
    const N = db2.model('Test2', schema2);

    let m = await M.create({h: "Test", a:{b: true, c: new Date()}});
    let n = await N.create({g: m._id, i: "Test2"});

    const doc = await N.find({_id: n._id.toString()}, {i: 1, g: 1})
        .populate("g", "_id h", M)
        .exec();

    console.log(doc[0].toObject());
}
```

It is a populate with projection on another database schema. Depending on query arguments in the request we create projection objects for the main model and also the secondary populated one, and when we miss the field with the nested virtual in the populate query the error throws. It does work in this test case, but strangely enough it still doesn't work in my use case. I tried to simplify my use case by removing a lot of intermediary code, so as to be sure that I wasn't breaking anything along the way, and the error still throws with the following stacktrace:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'checkMandatoryConsensus' of undefined
    at applyGetters (C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\document.js:2774:28)
    at model.Document.get (C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\document.js:1290:12)
    at Document.value (C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\helpers\document\compile.js:91:28)
    at clone (C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\utils.js:194:18)
    at applyGetters (C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\document.js:2764:11)
    at model.Document.$toObject (C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\document.js:2528:5)
    at model.Document.toJSON (C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\document.js:2828:15)
    at JSON.stringify (<anonymous>)
    at stringify (C:\xampp\htdocs\hsAPI\node_modules\express\lib\response.js:1119:12)
    at ServerResponse.json (C:\xampp\htdocs\hsAPI\node_modules\express\lib\response.js:260:14)
    at User.find.populate.exec (C:\xampp\htdocs\hsAPI\api\users\patients\apiPatientCTRL.js:879:48)
    at C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\model.js:4659:16
    at C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\utils.js:255:16
    at _hooks.execPost (C:\xampp\htdocs\hsAPI\node_modules\mongoose\lib\query.js:4065:11)
    at C:\xampp\htdocs\hsAPI\node_modules\kareem\index.js:135:16
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
```

So `checkMandatoryConsensus` is `f` in our case and `a` is the undefined one. The error throws when calling the doc.toObject() if that may be of any help. I don't know what else I can do now to replicate this since I thought it was a pretty straightforward use case. Of course we have a lot of other data in the schemas but I don't think they would be of any help.

**Comment by vkarpov15** [comment]
Without the ability to repro this issue we can't really attempt to fix this issue on our end. Here's an idea though: try declaring a [nested schema](https://mongoosejs.com/docs/subdocs.html)

```javascript
const nestedSchema = new Schema({
  a: String
});

nestedSchema.virtual('f').get(() => true);

const schema = mongoose.Schema({
        a: nestedSchema,
        h: String
});
```

That might help.

**Comment by Ncifra** [comment]
Actually I made it as a post init field that I previously added to the schema. As long as we don't send it in the request, it won't get saved in the collection document, and I can also just filter it out in the pre save hook. I can't remember now why I opted against the nested schema, maybe due to certain dependent isModified() fields between the main schema and nested one that were making coding logic a bit difficult.

I usually post the problems over here not as something that I am not able to work around, because usually time hasn't permitted us to halt development, but just wanting to make this sort of passive contribution (because one thing is pointing out bugs, and one other thing solving them) in the improvement of mongoose that has proved to be a huge time saver for us.

Since I have a lot of hooks in my actual schema, I'll try cleaing out that part a bit and do tests to see if something is related to those.

**Comment by vkarpov15** [comment]
Can you please provide some code samples of what you're doing with post init? Prose descriptions of code are generally not very helpful

**Comment by Ncifra** [comment]
Yes, I've left this one and the other related to the virtual problem open because I haven't had the time to do some clean tests with the current existing schemas. You can either close these or put them on hold and I will return with some test examples for them.

**Comment by Ncifra** [comment]
Okay, so this is the code. What I am trying to do is to get the nested data from the populated object and set it as virtuals on the main object. As you can see with the following, you will get the error mentioned:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7491`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;
const {Schema} = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
    const db = await mongoose.connect(connectionString);
    const db2 = mongoose.createConnection(`mongodb://localhost:27017/1001`);
    await mongoose.connection.dropDatabase();

    const schema = mongoose.Schema({
        a: {
            b: {
                type: Boolean,
                default: false
            },
            c: Date,
            d: {},
            e: {
                type: String,
                enum: ["a", "b"]
            }
        },
        h: String

    }, {timestamps: true,
        usePushEach: true,
        versionKey: "_userVersioning",
        toObject: {
            virtuals: true
        },
        toJSON: {
            virtuals: true
        }});

    schema.virtual("a.f").get(function () {
        return true; //or whatever, it doesn't matter what the return value is but there must be a return value
    });

    const schema2 = mongoose.Schema({
        g: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Test",
            required: true
        },
        i: String
    }, {
        toObject: {
            virtuals: true
        },
        toJSON: {
            virtuals: true
        }
    });

    schema2.virtual("a").get(function () {
        if (this.g && this.g.a) {
            return this.g.a;
        } else {
            return undefined;
        }
    });

    const M = db.model('Test', schema);
    const N = db2.model('Test2', schema2);

    let m = await M.create({h: "Test", a:{b: true, c: new Date()}});
    let n = await N.create({g: m._id, i: "Test2"});

    const doc = await N.find({_id: n._id.toString()}, {i: 1, g: 1})
        .populate("g", "_id h", M)
        .exec();

    console.log(doc[0].toObject());
}
```
