### ISSUE TITLE
"TypeError: Invalid value for schema path `select`" when `select : false`

### ISSUE THREAD

**Issue by abdielou** [Automattic/mongoose#7512]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Related to: https://github.com/Automattic/mongoose/commit/1b1acd5e3d9c78a67ce0bd65f5af5ac7c814f2be#r32269366

```
/var/app/current/node_modules/mongoose/lib/schema.js:403
      throw new TypeError('Invalid value for schema path `' + prefix + key + '`');
      ^

TypeError: Invalid value for schema path `select`
    at Schema.add (/var/app/current/node_modules/mongoose/lib/schema.js:403:13)
    at new Schema (/var/app/current/node_modules/mongoose/lib/schema.js:117:10)
    at Schema.interpretAsType (/var/app/current/node_modules/mongoose/lib/schema.js:705:29)
    at Schema.path (/var/app/current/node_modules/mongoose/lib/schema.js:566:27)
    at Schema.add (/var/app/current/node_modules/mongoose/lib/schema.js:426:12)
    at new Schema (/var/app/current/node_modules/mongoose/lib/schema.js:117:10)
    at Object.<anonymous> (/var/app/current/.........<MY MODEL - REMOVED>.....)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/.........<MY APP - REMOVED>.....)
    at Module._compile (module.js:653:30)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
This is my schema:

```
const SomeSchema = new mongoose.Schema({
   someProp: [
    {
      key: { type: String },
      value: { type: String },
      select: false, // THIS IS WHERE IT BREAKS
    },
  ],
});
```

**What is the expected behavior?**
Should process schema correctly.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 10.15.0
Mongoose: 5.4.11
MongoDB: 4.0.6

**Comment by briantanner** [comment]
We're having the same issue with 5.4.11 and keys that default to false. Reverting to 5.4.10 resolved the issue for us.
```
TypeError: Invalid value for schema path `moderation.channel.default`
```

```
channel: { default: false }
```

**Comment by vkarpov15** [comment]
@abdielou in your case, this error message is correct. Your schema doesn't do what you expect, you're creating a `select` property of type [Mixed](https://mongoosejs.com/docs/schematypes.html#mixed) in your array:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7512`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const SomeSchema = new mongoose.Schema({
     someProp: [
      {
        key: { type: String },
        value: { type: String },
        select: false, // THIS IS WHERE IT BREAKS
      },
    ],
  });

  console.log(SomeSchema.path('someProp').schema.path('select')); // Prints "Mixed { ... }"
}
```

If you want to de-select `someProp` by default, use this instead:

```javascript
  const SomeSchema = new mongoose.Schema({
    someProp: {
      type: [{
        key: { type: String },
        value: { type: String },
      }],
      select: false
    },
  });
```
