### ISSUE TITLE
Issue with arrayFilters on update since 5.4.4

### ISSUE THREAD

**Issue by AssafMalki** [Automattic/mongoose#7540]
**Do you want to request a *feature* or report a *bug*?**
 report a bug

**What is the current behavior?**
Issue with arrayFilters on update since 5.4.4
I have downgraded to 5.4.3 and this functionality works

I'm getting the following 

```
TypeError: Cannot read property 'castForQueryWrapper' of undefined
    at castFilterPath (lib\helpers\query\castFilterPath.js:45:31)
    at castArrayFilters (lib\helpers\update\castArrayFilters.js:57:26)
    at _castArrayFilters (lib\query.js:1738:5)
    at model.Query._updateThunk (lib\query.js:3403:3)
    at model.Query.<anonymous> (lib\query.js:3484:23)
    at model.Query._wrappedThunk [as _execUpdate] (lib\helpers\query\wrapThunk.js:16:8)
    at process.nextTick (kareem\index.js:369:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

I think it got something to do with this commit:
https://github.com/Automattic/mongoose/commit/c53a52a50cabc87b1a292cf96f218458f58027d1#diff-9cc02494c1b881b48d722bf517323774

**If the current behavior is a bug, please provide the steps to reproduce.**
I have the following structure:

```
	"_id": "5c66b062f2b8a936b124218f",
	"doctorsAppointment": {
		"queries": [{
				"isValid": true,
				"isDeleted": false,
				"isNewUpdates": false,
				"key": "vyJu4NVf",
				"hmo": "Filler",
				"speciality": "Filler",
				"cities": ["Filler"],
				"currentAppointmentDate": "2019-03-27T00:00:00.000Z",
				"suggestedAppointment": [{
						"date": "2019-03-06T09:00:00.000Z",
						"doctorsName": "Filler",
						"city": "Filler",
						"isDeleted": false,
						"key": "9qSAb"
					}
				]
			}
		],
```
And I'm doing the following

```
  const query = {
    _id: req.payload._id
  };

  const updateQuery = {
    $set: {
      "doctorsAppointment.queries.$[].suggestedAppointment.$[update].isDeleted": true
    }
  };

  const options = { arrayFilters: [{ "update.key": { $eq: req.body.key } }] };

  User.update(query, updateQuery, options, err => {
    if (err) {
      res.status(404).end();
    } else {
      res.status(200).end();
    }
  });
```

**What is the expected behavior?**

Not to throw an error

**Please mention your node.js, mongoose and MongoDB version.**

MongoDB 4.0.6 Community
"mongoose": "^5.4.14"
node.js v10.15.1

**Comment by AssafMalki** [comment]
Is their a guideline for a repro script?
Isn't the code in the initial message enough?
Thanks,
Assaf
