### ISSUE TITLE
TypeError: Cannot read property 'castForQueryWrapper' of undefined

### ISSUE THREAD

**Issue by eldhoseelias** [Automattic/mongoose#7577]
TypeError: Cannot read property 'castForQueryWrapper' of undefined
    at castFilterPath (/Users/user/Desktop/node/node_modules/mongoose/lib/helpers/query/castFilterPath.js:46:31)
    at castArrayFilters (/Users/user/Desktop/node/node_modules/mongoose/lib/helpers/update/castArrayFilters.js:57:26)
    at _castArrayFilters (/Users/user/Desktop/node/node_modules/mongoose/lib/query.js:1736:5)
    at model.Query._updateThunk (/Users/user/Desktop/node/node_modules/mongoose/lib/query.js:3449:3)
    at model.Query.<anonymous> (/Users/user/Desktop/node/node_modules/mongoose/lib/query.js:3535:23)
    at model.Query._wrappedThunk [as _execUpdate] (/Users/user/Desktop/node/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at /Users/user/Desktop/node/node_modules/kareem/index.js:278:20
    at _next (/Users/user/Desktop/node/node_modules/kareem/index.js:102:16)
    at process.nextTick (/Users/user/Desktop/node/node_modules/kareem/index.js:499:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by vkarpov15** [comment]
Please provide code samples. We fixed a related bug in 5.4.17, please upgrade to 5.4.17 and see if this issue goes away.
