### ISSUE TITLE
Bug of editing single nested subdocument

### ISSUE THREAD

**Issue by lutherman** [Automattic/mongoose#7681]
Hi,

I find that the result is wrong after modified the single nested subdocument of existing document.

Below is my test case:
```javascript
var chai = require("chai");
var expect = chai.expect;

const mongoose = require('mongoose');
const Schema = mongoose.Schema;
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });

const singleNestedSchema = new Schema({
  name: String,
  value: Number,
});

const testModel = mongoose.model('test', new Schema({
  title: String,
  data: singleNestedSchema,
}));

let sampleDocumentId;

describe('test', () => {
  before('Clear collection and add sample document', () => {
    return testModel.deleteMany({})
      .then(() => {
        const testDocument = new testModel({
          title: 'test',
          data: {
            name: 'first',
            value: 100,
          }
        });

        return testDocument.save();
      })
      .then(result => {
        sampleDocumentId = result._id;
      });
  });
  after('DB disconnect', () => {
    mongoose.disconnect();
  });
  it('Edit single nested subdocument', () => {
    return testModel.findById(sampleDocumentId)
      .then(result => {
        result.data = {
          name: 'second',
          value: 200,
        };

        expect(result.data.value).to.equal(200);
        expect(result.data.name).to.equal('second');
      });
  });
});
```

And the test result is:
```
$ mocha index.js


  test
    1) Edit single nested subdocument


  0 passing (63ms)
  1 failing

  1) test
       Edit single nested subdocument:

      AssertionError: expected 'first' to equal 'second'
      + expected - actual

      -first
      +second
      
      at testModel.findById.then.result (index.js:50:37)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
The results show that field **result.data.value** can pass the test, but field **result.data.name** cannot.

------------------------------
nodejs: 10.12.0
mongoose: 5.4.21
mongodb: 3.6.5
chai: 4.2.0
mocha: 6.0.2

**Comment by vkarpov15** [comment]
Fix will be in 5.5.1 re: #7660, thanks for reporting :+1:
