### ISSUE TITLE
UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect despite never trying to connect to localhost

### ISSUE THREAD

**Issue by Shwiedmaier** [Automattic/mongoose#7686]
Bug

**What is the current behavior?**
When I first start my app I get 
`(node:19064) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Users\shwie\Documents\ScottBott\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:189:13)
    at Connection.<anonymous> (C:\Users\shwie\Documents\ScottBott\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:277:13)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (C:\Users\shwie\Documents\ScottBott\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:19064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
**If the current behavior is a bug, please provide the steps to reproduce.**
I just simply forcequit mongodb on my local machine and run my app. 

**What is the expected behavior?**
This shouldnt appear at all as im not even trying to use localhost

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
    "mongodb": "^3.2.2",
    "mongoose": "^5.4.22",
    node 10.15.3 
Here is my app, if you want to take a look at whats causing the issue. 
I am hosting my mongodb on atlas 
https://github.com/Shwiedmaier/ScottBott
I want to be clear though. Despite this error the app works. It writes to the atlas database and pulls from it just fine. I am just getting this error whenever I start the app. Also before I force close mongodb locally the app would write to local instead of my database on atlas.

**Comment by vkarpov15** [comment]
You're connecting to localhost in [`commands/report.js`](https://github.com/Shwiedmaier/ScottBott/blob/3e8b9d672d051f886df5f1dd3b5cf91d0e521661/commands/report.js#L2).

In general, don't call `mongoose.connect()` at the top of every file.You're better off having one file that exports the result of `mongoose.connect()` and requiring that in.
