### ISSUE TITLE
Maximum call stack size exceeded in model.set() (node10, mongoose:^5.12.17)

### ISSUE THREAD

**Issue by mnosuk** [Automattic/mongoose#7725]
I've found an indescribable behavior about `model.set` that I'll provide the code below.

```javascript
LeadSchema.methods.createInvoiceModel = async function createInvoiceModel(packageBody, discount, withACT, userId) {
  const additionalBody = {
    WithACT: withACT || undefined,
    Discount: discount,
  }
  const invoice = new Invoice({
    PackageDetail: packageBody,
    CreatedBy: userId,
    ...additionalBody,
  })
  console.log('this', this)
  // this.Invoice = invoice
  this.set({
     ...this,
     Invoice: invoice,
   })
  const [leadResult] = await Promise.all([this.save(), invoice.save()])
  return leadResult
}
```
at first, please ignore the `this.Invoice = invoice`  comment, that's a possible way I've found to solve this problem. but I just want to know why can't I use set() function

```javascript
const LeadSchema = new Schema({
 blabla: ....
 ...
  Invoice: {
    type: ObjectId, ref: 'invoices',
  },

  CreatedDate: { type: Date, default: Date.now },
  UpdatedDate: { type: Date, default: Date.now },
  CompletedDate: { type: Date },
  CancelledDate: { type: Date },
})
```

and this is an error that nodejs provided to me.

```
web_1  | RangeError: Maximum call stack size exceeded
web_1  |     at String.split (<anonymous>)
web_1  |     at getPositionalPathType (/var/www/node_modules/mongoose/lib/schema.js:1073:25)
web_1  |     at getPositionalPath (/var/www/node_modules/mongoose/lib/schema.js:1142:3)
web_1  |     at Schema.path (/var/www/node_modules/mongoose/lib/schema.js:557:9)
web_1  |     at model.Document.$__path (/var/www/node_modules/mongoose/lib/document.js:1382:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:817:16)
web_1  |     at model.$set (/var/www/node_modules/mongoose/lib/document.js:788:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:821:12)
web_1  |     at model.$set (/var/www/node_modules/mongoose/lib/document.js:788:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:821:12)
web_1  |     at model.$set (/var/www/node_modules/mongoose/lib/document.js:788:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:821:12)
web_1  |     at model.$set (/var/www/node_modules/mongoose/lib/document.js:788:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:821:12)
web_1  |     at model.$set (/var/www/node_modules/mongoose/lib/document.js:788:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:821:12)
web_1  |     at model.$set (/var/www/node_modules/mongoose/lib/document.js:788:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:821:12)
web_1  |     at model.$set (/var/www/node_modules/mongoose/lib/document.js:788:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:821:12)
web_1  |     at model.$set (/var/www/node_modules/mongoose/lib/document.js:788:22)
web_1  |     at model._handleIndex (/var/www/node_modules/mongoose/lib/document.js:821:12)
```

need to find an answer.

**Comment by mnosuk** [comment]
a simple question,

what is the best practice to update model. Does my code below good? or not? and why? 

```
model.key = value
model.save()
```

**Comment by TrejGun** [comment]
```
model.set("key", value)
model.save()
```

**Comment by mnosuk** [comment]
> ```
> model.set("key", value)
> model.save()
> ```

what if we try to set 2 keys?
Is it okay to use

```
model.set('key1', val)
model.set('key2', val2)
model.save()
```

**Comment by vkarpov15** [comment]
@mnosuk yes. You can also do `doc.set({ key1: val, key2: val2 })`.

Your original code is perfectly fine:

```javascript
model.key = value
model.save()
```

The above code is almost equivalent to `model.set('key', value); model.save()`.

**Comment by Fonger** [comment]
I think it's caused by the object spread operator with `this`

`this` has other properties for the mongoose model other than the data properties so you get infinite self-reference until maximum call stack size exceeded.

**Comment by vkarpov15** [comment]
I believe @Fonger is right. I'm unable to repro this using the below script with Mongoose 5.2.17, but I suspect this may be related to #7645. The question is, why are you doing `doc.set({ ...this })`? That's completely unnecessary, and, worse, can add meaningful performance overhead. See the [`Document#set()` docs](https://mongoosejs.com/docs/api.html#document_Document-set).

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7725`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;
console.log(mongoose.version);

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const LeadSchema = new Schema({
    Invoice: {
      type: Schema.ObjectId, ref: 'invoices',
    },

    CreatedDate: { type: Date, default: Date.now },
    UpdatedDate: { type: Date, default: Date.now },
    CompletedDate: { type: Date },
    CancelledDate: { type: Date },
  });
  const Lead = mongoose.model('Lead', LeadSchema);

  const doc = new Lead({ CompletedDate: new Date(), CancelledDate: new Date() });

  doc.set({ ...doc, Invoice: new mongoose.Types.ObjectId() });
  await doc.save();
}
```
