### ISSUE TITLE
Adding another text index causes Promise rejection / uncaught exception

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#7730]
Upon changing this:

```diff
const Analytics = new mongoose.Schema({
  // ...
});

// ...

Analytics.index(
-  { 'context.page.url': 'text' },
+  { 'context.page.url': 'text', 'context.page.referrer': 'text' },
  { background: true }
);
```

I get the following error:

```sh
MongoError: Index: { v: 2, key: { _fts: "text", _ftsx: 1 }, name: "context.page.url_text_context.page.referrer_text", ns: "production.analytics", background: true, weights: { context.page.referrer: 1, context.page.url: 1 }, default_language: "english", language_override: "language", textIndexVersion: 3 } already exists with different options: { v: 2, key: { _fts: "text", _ftsx: 1 }, name: "context.page.url_text", ns: "production.analytics", background: true, weights: { context.page.url: 1 }, default_language: "english", language_override: "language", textIndexVersion: 3 }
5|app      |     at Function.MongoError.create (/var/www/production/source/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
5|app      |     at /var/www/production/source/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:497:72
5|app      |     at authenticateStragglers (/var/www/production/source/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:443:16)
5|app      |     at Connection.messageHandler (/var/www/production/source/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:477:5)
5|app      |     at Socket.<anonymous> (/var/www/production/source/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:331:22)
5|app      |     at emitOne (events.js:116:13)
5|app      |     at Socket.emit (events.js:211:7)
5|app      |     at addChunk (_stream_readable.js:263:12)
5|app      |     at readableAddChunk (_stream_readable.js:250:11)
5|app      |     at Socket.Readable.push (_stream_readable.js:208:10)
5|app      |     at TCP.onread (net.js:607:20)
```

And the only way to fix the error is:

```sh
mongo
use production
db.analytics.dropIndexes()
```

And restart the app processes with `pm2 restart all`.

**Comment by vkarpov15** [comment]
That's expected behavior right now. [A collection can only have one text index](https://docs.mongodb.com/manual/core/link-text-indexes/), so you need to drop your text index before modifying it.
