### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined & TypeError: Cannot read property 'valueOf' of undefined

### ISSUE THREAD

**Issue by Zagonine** [Automattic/mongoose#7756]
I have got this two errors in production make the application crash.  
I can't know which of my `save()` is triggered with the stacktrace...
I think it's because I have an `undefined` in one of elements of an array but I don't even know the collection concerned and the property too. 
This two errors did not triggered in same time.

**First error:** 
```
TypeError: Cannot read property 'value' of undefined
at /var/app/current/node_modules/mongoose/lib/document.js:2471:15
at Array.forEach (<anonymous>:null:null)
at model.Document.$__dirty (/var/app/current/node_modules/mongoose/lib/document.js:2461:7)
at model.Model.$__delta (/var/app/current/node_modules/mongoose/lib/model.js:636:22)
at model.Model.$__handleSave (/var/app/current/node_modules/mongoose/lib/model.js:288:24)
at model.Model.$__save (/var/app/current/node_modules/mongoose/lib/model.js:328:8)
at /var/app/current/node_modules/kareem/index.js:278:20
at /var/app/current/node_modules/kareem/index.js:45:20
at process.nextTick (/var/app/current/node_modules/kareem/index.js:499:38)
at Shim.applySegment (/var/app/current/node_modules/newrelic/lib/shim/shim.js:1387:20)
at wrapper (/var/app/current/node_modules/newrelic/lib/shim/shim.js:2022:17)
at process._tickCallback (internal/process/next_tick.js:61:11)
```
**Second error:** 
```
TypeError: Cannot read property 'valueOf' of undefined
at CoreMongooseArray.$__getAtomics (/var/app/current/node_modules/mongoose/lib/types/array.js:270:22)
at handleAtomics (/var/app/current/node_modules/mongoose/lib/model.js:576:11)
at model.Model.$__delta (/var/app/current/node_modules/mongoose/lib/model.js:697:7)
at model.Model.$__handleSave (/var/app/current/node_modules/mongoose/lib/model.js:288:24)
at model.Model.$__save (/var/app/current/node_modules/mongoose/lib/model.js:328:8)
at /var/app/current/node_modules/kareem/index.js:278:20
at _next (/var/app/current/node_modules/kareem/index.js:102:16)
at process.nextTick (/var/app/current/node_modules/kareem/index.js:499:38)
at Shim.applySegment (/var/app/current/node_modules/newrelic/lib/shim/shim.js:1387:20)
at wrapper (/var/app/current/node_modules/newrelic/lib/shim/shim.js:2022:17)
at process._tickCallback (internal/process/next_tick.js:61:11)
```
Mongoose version : 5.5.4
Node version : 10.15.3
MongoDB version : 3.6.12

**Comment by vkarpov15** [comment]
The only way I could repro this issue is by having an array property called 'undefined' in my schema:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7756`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({ arr: [String] });
  const Model = mongoose.model('Test', schema);

  const doc = await Model.create({ arr: ['foo'] });

  doc.arr = void 0;
  await doc.save();
}
```

It is possible that's what was causing your issue, but not 100% certain. I added a couple checks that should help us avoid this error.
