### ISSUE TITLE
BUG: TypeError: this.validate is not a function

### ISSUE THREAD

**Issue by Acksell** [Automattic/mongoose#7783]
**Do you want to request a *feature* or report a *bug*?**
Bug report.
**What is the current behavior?**
When running https://github.com/Acksell/KONSol at commit 937277bdc48c54f
and trying to save a document using the following snippet as part of [this model file](https://github.com/Acksell/KONSol/blob/937277bdc48c54f2a0a48963e4b15f0c4baa99d8/models/slide.js):

    slideSchema.statics.save = function (requestBody, remotely_hosted, filename) {
        // unpack variables to avoid users setting `created` field.
        const {_id, url, fullscreen, visible, start, end, caption, tags} = requestBody
        if (_id) {
            // if id specified, try to find and update
            return this.findOne({_id}).then(slide=>{
                slide.set({url, fullscreen, visible, start, end, caption, tags})
                return slide.save() // this triggers the pre('save',...) call
            })
        }
        // No existing id, create new slide.
        return this.create({url, fullscreen, visible, start, end, caption, tags, remotely_hosted, filename})
    }

You get the following traceback; 

    TypeError: this.validate is not a function
        at Function.<anonymous> (/konsol/node_modules/mongoose/lib/plugins/validateBeforeSave.js:35:12)
        at callMiddlewareFunction (/konsol/node_modules/kareem/index.js:474:23)
        at next (konsol/node_modules/kareem/index.js:58:7)
        at Kareem.execPre (/konsol/node_modules/kareem/index.js:86:8)
        at utils.promiseOrCallback.callback (/konsol/node_modules/mongoose/lib/helpers/model/applyStaticHooks.js:29:17)
        at Promise (/konsol/node_modules/mongoose/lib/utils.js:270:5)
        at new Promise (<anonymous>)
        at Object.promiseOrCallback (/konsol/node_modules/mongoose/lib/utils.js:269:10)
        at Function.model.(anonymous function) [as save] (/konsol/node_modules/mongoose/lib/helpers/model/applyStaticHooks.js:28:22)
        at Object.exports.save (/konsol/controllers/slide.js:23:15)
        at /konsol/server.js:154:19
        at Immediate._onImmediate (/konsol/node_modules/multer/lib/make-middleware.js:53:37)
        at runCallback (timers.js:798:20)
        at tryOnImmediate (timers.js:752:5)
        at processImmediate [as _immediateCallback] (timers.js:729:5)

If I `console.log("this:", this)` and  `console.log("this.validate:", this.validate)` by modifying the code in `node_modules` at [mongoose/lib/plugins/validateBeforeSave.js](https://github.com/Automattic/mongoose/blob/master/lib/plugins/validateBeforeSave.js) I get the following result:

    this: function model(doc, fields, skipId) {
        model.hooks.execPreSync('createModel', doc);
        if (!(this instanceof model)) {
            return new model(doc, fields, skipId);
        }
        const discriminatorKey = model.schema.options.discriminatorKey;

        // If discriminator key is set, use the discriminator instead (gh-7586)
        if (model.discriminators != null &&
            doc != null &&
            doc[discriminatorKey] != null &&
            model.discriminators[doc[discriminatorKey]] != null) {
            return new model.discriminators[doc[discriminatorKey]](doc, fields, skipId);
        }

        // Otherwise, just use the top-level model
        Model.call(this, doc, fields, skipId);
        }
    this.validate:  undefined

**If the current behavior is a bug, please provide the steps to reproduce.**
Clone above repo, run npm install in project dir and in project dir `/client`. Run `npm run-script build && mkdir build/img` in the `/client` dir to build the react app. Export the following envvar `export KONSOL_NODE_ENV=production`, and run `npm start` in the root project directory. 

Open the app in http://localhost:8888, now as you try and upload an image and click save ( triggering the above code snippet), it displays the traceback.

**What is the expected behavior?**
The expected behavior is to successfully save the document with the updated values. That is, to not break.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Tested on Mongoose v5.4.19 and v5.5.6 and it breaks on both.
`mongo --version`
`MongoDB shell version: 2.6.10`
but also tested on 
`MongoDB shell version: 3.6.3`
It used to work on node version 9.10.1 but after experiencing problems on a clean install of node 8.10.0 I switched to test locally and could reproduce the issue. After trying to switch back to 9.10.1 it now no longer worked. I also tried the latest install of node 10.15.3. So try any node version you like and it should probably break.

**Comment by Acksell** [comment]
Resolved by changing the name of the function `slideSchema.statics.save` to `slideSchema.statics.saveSlide`. Should give some kind of error like the one if you override the hook schema.pre('validate')
