### ISSUE TITLE
TypeError: Cannot read property 'Decimal128' of null

### ISSUE THREAD

**Issue by mapleeit** [Automattic/mongoose#7866]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Throw `TypeError: Cannot read property 'Decimal128' of null` at `mongoose/lib/types/decimal128.js:13:44`

Stack:

```shell
master_1     | 2019-06-04 07:53:48.702 [ERRO] [53 cpu2 1] [/app/master] [warning.js:18] (node:53) TypeError: Cannot read property 'Decimal128' of null
master_1     | 2019-06-04 07:53:48.703 [WARN] [53 cpu2 1] [/app/master] [master.js:54] TypeError: Cannot read property 'Decimal128' of null
master_1     |     at Object.<anonymous> (/node_modules/orange-ci/node_modules/mongoose/lib/types/decimal128.js:13:44)
master_1     |     at Module._compile (internal/modules/cjs/loader.js:701:30)
master_1     |     at Module._compile (/TSW/bin/tsw/loader/seajs/lib/sea-node.js:43:25)
master_1     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
master_1     |     at Module.load (internal/modules/cjs/loader.js:600:32)
master_1     |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
master_1     |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
master_1     |     at Module.require (internal/modules/cjs/loader.js:637:17)
master_1     |     at require (internal/modules/cjs/helpers.js:22:18)
master_1     |     at Object.<anonymous> (/node_modules/orange-ci/node_modules/mongoose/lib/utils.js:7:17)
master_1     |     at Module._compile (internal/modules/cjs/loader.js:701:30)
master_1     |     at Module._compile (/TSW/bin/tsw/loader/seajs/lib/sea-node.js:43:25)
master_1     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
master_1     |     at Module.load (internal/modules/cjs/loader.js:600:32)
master_1     |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
master_1     |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Should work well.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v10.16.0
Mongoose: 5.5.12
MongoDB: 4.0.10

**Comment by vkarpov15** [comment]
Please provide code samples.

**Comment by mapleeit** [comment]
It seems that I required multiple times of mongoose. And delete the `require.cache`. 

I solved this by stop deleting `require.cache`
