### ISSUE TITLE
MongoError: Use of expired sessions is not permitted , when insertMany

### ISSUE THREAD

**Issue by naxiaoguang** [Automattic/mongoose#7920]
"mongoose": "^5.6.0"
"@types/mongoose": "^5.3.7",
"koa": "^2.6.2",
"mongoose-acid": "^0.11.0",

return await Paragraph.insertMany([{
     type:1,
     createTime:'2019-03-22'
}], { session });

two functions , add and update , it work in add function , but in update function throw error ;

(node:38740) UnhandledPromiseRejectionWarning: MongoError: Use of expired sessions is not permitted
    at executeOperation (/Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongodb/lib/utils.js:388:13)
    at Collection.insertMany (/Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongodb/lib/collection.js:489:10)
    at NativeCollection.(anonymous function) [as insertMany] (/Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:158:28)
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongoose/lib/model.js:3167:22
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/async/internal/parallel.js:39:9
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/async/internal/once.js:12:16
    at iterateeCallback (/Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/async/internal/eachOfLimit.js:48:24)
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/async/internal/parallel.js:36:13
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongoose/lib/model.js:3138:9
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongoose/lib/utils.js:264:16
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongoose/lib/document.js:1908:5
    at complete (/Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongoose/lib/document.js:2104:5)
    at p.doValidate.skipSchemaValidators (/Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongoose/lib/document.js:2142:20)
    at /Users/naxiaoguang/File/projects/Server-TypeSet/node_modules/mongoose/lib/schematype.js:1029:11
    at process._tickCallback (internal/process/next_tick.js:61:11)
warning.js:18
(node:38740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:38740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vkarpov15** [comment]
How many documents are you inserting? Also, what do you mean by "update function"?
