### ISSUE TITLE
"minimize: false" in subdocument causes error when getting documents from database

### ISSUE THREAD

**Issue by ionian-wind** [Automattic/mongoose#7935]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
```
~/node_modules/mongoose/lib/document.js:981
cur = cur[parts[i]];
^

TypeError: Cannot read property 'list' of undefined
at SingleNested.$set (~/node_modules/mongoose/lib/document.js:981:14)
at SingleNested.$set (~/node_modules/mongoose/lib/document.js:815:16)
at SingleNested._handleIndex (~/node_modules/mongoose/lib/document.js:856:12)
at SingleNested.$set (~/node_modules/mongoose/lib/document.js:821:22)
at SingleNested._handleIndex (~/node_modules/mongoose/lib/document.js:856:12)
at SingleNested.$set (~/node_modules/mongoose/lib/document.js:821:22)
at SingleNested._handleIndex (~/node_modules/mongoose/lib/document.js:856:12)
at SingleNested.$set (~/node_modules/mongoose/lib/document.js:821:22)
at SingleNested.Document (~/node_modules/mongoose/lib/document.js:124:12)
at SingleNested.Subdocument (~/node_modules/mongoose/lib/types/subdocument.js:34:12)
at new SingleNested (~/node_modules/mongoose/lib/schema/embedded.js:61:17)
at Embedded.cast (~/node_modules/mongoose/lib/schema/embedded.js:174:12)
at Embedded.SchemaType.getDefault (~/node_modules/mongoose/lib/schematype.js:895:25)
at $__applyDefaults (~/node_modules/mongoose/lib/document.js:359:22)
at model.Document (~/node_modules/mongoose/lib/document.js:111:5)
at model.Model (~/node_modules/mongoose/lib/model.js:97:12)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const mongoose = require('mongoose');

const subdoc = new mongoose.Schema({
    list: {
        type: [String],
        default: ['a']
    }
}, { minimize: false });

const TestSchema = new mongoose.Schema({
    lists: {
        type: subdoc,
        default: subdoc
    }
});

const Test = mongoose.model('test', TestSchema);

mongoose.connect('mongodb://localhost/test')
    .then(() => Test.create({}))
    .then(() => Test.find({})) // <---- error rises here
    .then(console.log)
    .catch(console.log);
```

**What is the expected behavior?**
no TypeError when finding documents

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js v10.16.0
Mongoose 5.6.1
MongoDB v4.0.10

mongoose@5.5.2 - error reproduces starting this version

**Comment by vkarpov15** [comment]
We fixed the issue, but there's also an issue with your code: why are you setting the subdoc default to a schema? There's no reason to do that, and doing so may be dangerous depending on your schema.
