### ISSUE TITLE
TypeError: Cannot read property 'discriminatorMapping' of undefined     at discriminator

### ISSUE THREAD

**Issue by DwayneGit** [Automattic/mongoose#7957]
children.js

    const mongoose = require("mongoose")
    const testModel = require("./testSchema")
    module.exports.Owner = new testModel.discriminator('Owner',
	    new mongoose.Schema({
			        Job : String
                }, ))
    module.exports.Janitor = new testModel.discriminator('Janitor',
	    new mongoose.Schema({
      			        Family_count : Number
                }, ))

testSchema.js

    const mongoose = require("mongoose")
    var testSchema = new mongoose.Schema({
			    Name : String,
			    Age : Number
		    }, {
			    collection: "testToo",
			    discriminatorKey: "role"
		    })
    module.exports = mongoose.model("testModel",testSchema)

using the modules above i get the following error:

`TypeError: Cannot read property 'discriminatorMapping' of undefined
    at discriminator (/home/dwayne/Desktop/Workspace/PhantomDBM/phantom/database/js/node_modules/mongoose/lib/helpers/model/discriminator.js:23:20)
    at new Model.discriminator (/home/dwayne/Desktop/Workspace/PhantomDBM/phantom/database/js/node_modules/mongoose/lib/model.js:1084:12)
    at Object.<anonymous> (/home/dwayne/Desktop/Workspace/PhantomDBM/phantom/database/js/src/schemas/test_test/testChildSchemas.js:4:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/dwayne/Desktop/Workspace/PhantomDBM/phantom/database/js/src/dao/mongoose_dao.js:14:57
    at Array.forEach (<anonymous>)
    at new mongooseDOA (/home/dwayne/Desktop/Workspace/PhantomDBM/phantom/database/js/src/dao/mongoose_dao.js:13:40)
    at Object.<anonymous> (/home/dwayne/Desktop/Workspace/PhantomDBM/phantom/database/js/index.js:21:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)`

Does anyone one know what may cause this.

**Comment by DwayneGit** [comment]
Found the issue. new should not be used in the when creating the discriminators. 

    module.exports.Janitor = testModel.discriminator('Janitor',
    new mongoose.Schema({
  			        Family_count : Number
            }, ))

**Comment by Yunus0or1** [comment]
> Found the issue. new should not be used in the when creating the discriminators.
> 
> ```
> module.exports.Janitor = testModel.discriminator('Janitor',
> new mongoose.Schema({
> 		        Family_count : Number
>         }, ))
> ```

what should be used then? Schema throws error if **new** word is not used
