### ISSUE TITLE
Conflicting mongoose once function (this.once is not a function)

### ISSUE THREAD

**Issue by venkateshwarlu-bavandla** [Automattic/mongoose#7958]
I have "once" field in my model doc. Which is conflicting while updating the existing doc, But while saving fresh doc am not getting.

Code:
```javascript
var mongoose = require('mongoose')

var options = {discriminatorKey: 'kind'};

var eventSchema = new mongoose.Schema({once: {
    booleanField: {type: String}
  }}, options)



var Event = mongoose.model('Event', eventSchema);

// ClickedLinkEvent is a special type of Event that has
// a URL.
var ClickedLinkEvent = Event.discriminator('ClickedLink',
  new mongoose.Schema({lookups: {
    type: [
      {
        hi: { type: String }
      }
    ]},url: String}, options));

var clickedEvent =
  new ClickedLinkEvent({
    once: {booleanField: true},
    lookups: [
    {
      hi: 'address1',
      name: 'address2',
    }], url: 'google.com'});

console.log(clickedEvent)
```
While updating existing doc am getting below error:
```javascript
Uncaught TypeError: this.once is not a function
      at model.Document (/node_modules/mongoose/lib/document.js:127:10)
      at model.Model (/node_modules/mongoose/lib/model.js:93:12)
      at new model (/node_modules/mongoose/lib/model.js:4542:13)
      at Object.createModel (/node_modules/mongoose/lib/queryhelpers.js:130:10)
      at completeOne (/node_modules/mongoose/lib/query.js:2663:26)
      at model.Query.Query._completeOne (/node_modules/mongoose/lib/query.js:1951:7)
      at Immediate.Query.base.findOne.call (node_modules/mongoose/lib/query.js:1993:10)
      at Immediate.<anonymous> (/node_modules/mquery/lib/utils.j
```

Can anybody suggest how can resolve this issue.

**Comment by vkarpov15** [comment]
Found the issue and fixed it in master, fix will be in 5.6.4.

In the future, if you provide a code sample, can you please make sure the code sample demonstrates your issue? A code sample that works correctly and doesn't throw the error you indicated is not very helpful.
