### ISSUE TITLE
Cast to embedded failed for value

### ISSUE THREAD

**Issue by jevonsofcode** [Automattic/mongoose#8054]
Upgrading to 5.6.7 is causing an error to be thrown:

CastError: Cast to Embedded failed for value  
`type: [{diploma: { type: Number, enum: [1, 2, 3, 4, 5] }}]`,

and v5.4.20 causing the error too

and I think the reason to `type in type`
 
Any idea what is causing this?

**Comment by vkarpov15** [comment]
Can you please provide a more detailed code sample? Just providing an error message isn't actionable, show me the code please :+1:

**Comment by jevonsofcode** [comment]
error info:
```
{
    "stack": "CastError: Cast to embedded failed for value \"{ diploma: \\'12w\\' }\" at path \"educations\"\n    at new CastError (/Users/mac/Desktop/.../node_modules/mongoose/lib/error/cast.js:29:11)\n    at DocumentArray.cast (/Users/mac/Desktop/.../node_modules/mongoose/lib/schema/documentarray.js:408:19)\n    at DocumentArray.SchemaType.applySetters (/Users/mac/Desktop/.../node_modules/mongoose/lib/schematype.js:948:12)\n    at DocumentArray.SchemaType._castForQuery (/Users/mac/Desktop/.../node_modules/mongoose/lib/schematype.js:1362:15)\n    at DocumentArray.SchemaType.castForQueryWrapper (/Users/mac/Desktop/.../node_modules/mongoose/lib/schematype.js:1329:17)\n    at castUpdateVal (/Users/mac/Desktop/.../node_modules/mongoose/lib/helpers/query/castUpdate.js:451:19)\n    at walkUpdatePath (/Users/mac/Desktop/.../node_modules/mongoose/lib/helpers/query/castUpdate.js:278:22)\n    at castUpdate (/Users/mac/Desktop/.../node_modules/mongoose/lib/helpers/query/castUpdate.js:80:18)\n    at model.Query._castUpdate (/Users/mac/Desktop/.../node_modules/mongoose/lib/query.js:4406:10)\n    at castDoc (/Users/mac/Desktop/.../node_modules/mongoose/lib/query.js:4434:18)\n    at model.Query.Query._findAndModify (/Users/mac/Desktop/...node_modules/mongoose/lib/query.js:3401:19)\n    at model.Query.<anonymous> (/Users/mac/Desktop.../node_modules/mongoose/lib/query.js:2949:8)\n    at model.Query._wrappedThunk [as _findOneAndUpdate] (/Users/mac/Desktop/...(/Users/mac/Desktop.../node_modules/kareem/index.js:369:33)\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
    "message": "Cast to embedded failed for value \"{ diploma: \\'12w\\' }\" at path \"educations\"",
    "name": "CastError",
    "stringValue": "\"{ diploma: \\'12w\\' }\"",
    "kind": "embedded",
    "value": "{ diploma: '12w' }",
    "path": "educations",
    "reason": {
        "message": "Cast to Number failed for value \"12w\" at path \"diploma\"",
        "name": "CastError",
        "stringValue": "\"12w\"",
        "kind": "Number",
        "value": "12w",
        "path": "diploma",
        "reason": {
            "message": "Cast to number failed for value \"12w\" at path \"diploma\"",
            "name": "CastError",
            "stringValue": "\"12w\"",
            "kind": "number",
            "value": "12w",
            "path": "diploma"
        }
    },
    "status": 500
}
```

Causing such code:
```
{
	"educations": [{
		"diploma": "12w" // type: number
	}]
}
```

Schema:
```
educations: {
        type: [{
            diploma: { type: Number, enum: [1, 2, 3, 4, 5] }
        }]
    },
```

**Comment by jevonsofcode** [comment]
sorry, this is not a mongoose problem, it is a verification problem of koa's `ctx.verifyParams`...
