### ISSUE TITLE
pre 'save' without a callback function fails with cryptic error message

### ISSUE THREAD

**Issue by ameyanekar** [Automattic/mongoose#8087]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
*Throws an error from the kareem library. Error does not refer to the pre save line of code.*

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Register a pre save hook without any callback: userSchema.pre('save');
2. Execute model.save();

**What is the expected behavior?**
Error message should be descriptive providing the line of code of the pre save line

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v10.16.0
mongoose@5.6.9
MongoDB v3.4.18

Complete Error Message Below:

```
/xxx/xxx/xxx/api-server/node_modules/kareem/index.js:51
    } else if (pre.fn.length > 0) {
                      ^

TypeError: Cannot read property 'length' of undefined
    at model.next (/xxx/api-server/node_modules/kareem/index.js:51:23)
    at _next (/xxx/api-server/node_modules/kareem/index.js:106:10)
    at process.nextTick (/xxx/api-server/node_modules/kareem/index.js:499:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by ameyanekar** [comment]
Thank you for the swift action @vkarpov15
