### ISSUE TITLE
can not connect mongodb atlas database

### ISSUE THREAD

**Issue by huangyanxiong01** [Automattic/mongoose#8154]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
can not connected database
```shell
{ MongoNetworkError: failed to connect to server [cluster0-shard-00-02-vrrxq.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-02-vrrxq.mongodb.net:27017 closed]
    at Pool.<anonymous> (/root/navtool-backend/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (/root/navtool-backend/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at callback (/root/navtool-backend/node_modules/mongodb-core/lib/connection/connect.js:109:5)
    at runCommand (/root/navtool-backend/node_modules/mongodb-core/lib/connection/connect.js:129:7)
    at Connection.errorHandler (/root/navtool-backend/node_modules/mongodb-core/lib/connection/connect.js:321:5)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:198:13)
    at Socket.<anonymous> (/root/navtool-backend/node_modules/mongodb-core/lib/connection/connection.js:350:12)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
```
**If the current behavior is a bug, please provide the steps to reproduce.**

1. create database in  mongodb atlas 
simple example code. according to this file [link](https://github.com/sundaycrafts/strapi/blob/e45b823385a43ca80196c21365d6a6d35b0733fe/packages/strapi-hook-mongoose/lib/index.js)

```javascript
const mongoose = require('mongoose');
const Mongoose = mongoose.Mongoose;
const instance = new Mongoose();
let connectOptions = {
  user: 'xxx',
  pass: 'xxxx',
  authSource: 'admin',
  ssl: false,
  useNewUrlParser: true,
  dbName: 'navtool',
  useCreateIndex: true
};
instance.connect('mongodb+srv://user:passwd@cluster0-vrrxq.mongodb.net/navtool',
  connectOptions,
).then((su) => {
  console.info(su);
}).catch(err => {
  console.info(err);
});
```
and I have try other way connect  mongodb, It work well
```javascript
mongoose.connect('mongodb+srv://user:pass@cluster0-vrrxq.mongodb.net/', {useNewUrlParser: true});
mongoose.connection.on('error', console.error.bind(console, 'connection error:'));
mongoose.connection.once('open', () => {
  console.info(`🚀  mongodb server connected to ${'mongodb+srv://user:passwd@cluster0-vrrxq.mongodb.net'}`)
});
```
**What is the expected behavior?**
Correct connection to the database
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongodb: 4.0.12
node: v10.15.0

mongoose: 5.6.13

**Comment by huangyanxiong01** [comment]
This is my mistake. close issue
