### ISSUE TITLE
password must be a string

### ISSUE THREAD

**Issue by chakhalyan1** [Automattic/mongoose#8176]
**Do you want to request a *feature* or report a *bug*?**
I want report a *bug*
**What is the current behavior?**

>  MongoError: password must be a string

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
MongoDB:  v4.2.0,
Mongoose: 5.7.1,
Node.js: v10.16.3

Hi All.  I have using following versions of mongod, mongoose and node.js.
mongod:  v4.2.0,
mongoose: 5.7.1,
node.js: v10.16.3

I have problem authenticate to mongod when i try connect via mongoose.
I have get following Error. 
`{ MongoError: password must be a string
    at passwordDigest (/home/armen/WebstormProjects/digitalOceanTest/node_modules/mongodb/lib/core/auth/scram.js:33:43)
    at ScramSHA1._executeScram (/home/armen/WebstormProjects/digitalOceanTest/node_modules/mongodb/lib/core/auth/scram.js:147:29)
    at AsyncWrap.crypto.randomBytes (/home/armen/WebstormProjects/digitalOceanTest/node_modules/mongodb/lib/core/auth/scram.js:240:19)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
`
I am using following code.
`const mongoose = require('mongoose');
(async () => {
    const con = await mongoose.createConnection('mongodb://server1:27017,server2:27017,server3:27017/myDB?replicaSet=db1', {
        auth: {
            authSource: "admin",
            user: "username123",
            pass: "password123"
        },
        useNewUrlParser: true,
        useUnifiedTopology: true
    });

    console.log(con);
})().catch(error => console.log(error) );
`

**Comment by vkarpov15** [comment]
You need to do `auth.password`, not `auth.pass`. What makes you think that `auth.password` is the way to set the password?
