### ISSUE TITLE
Improve stack traces for MongoErrors

### ISSUE THREAD

**Issue by rvillane** [Automattic/mongoose#8259]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

 "mongoose": "5.7.1",

**What is the current behavior?**

I randomly get this error below

the connection code uses these settings:

```
mongoose.connect(dbURI, {
    reconnectTries: Number.MAX_VALUE,
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
});
```
any recommendations ?

MongoError: server instance pool was destroyed
    at basicWriteValidations (/dist/node_modules/mongodb/lib/core/sdam/server.js:388:12)
    at executeWriteOperation (/dist/node_modules/mongodb/lib/core/sdam/server.js:415:17)
    at Server.insert (/dist/node_modules/mongodb/lib/core/sdam/server.js:337:5)
    at topology.selectServer (/dist/node_modules/mongodb/lib/core/sdam/topology.js:998:15)
    at selectServers (/dist/node_modules/mongodb/lib/core/sdam/topology.js:394:9)
    at selectServers (/dist/node_modules/mongodb/lib/core/sdam/topology.js:816:12)
    at NativeTopology.selectServer (/dist/node_modules/mongodb/lib/core/sdam/topology.js:381:5)
    at executeWriteOperation (/dist/node_modules/mongodb/lib/core/sdam/topology.js:966:12)
    at NativeTopology.insert (/dist/node_modules/mongodb/lib/core/sdam/topology.js:535:5)
    at NativeTopology.insert (/dist/node_modules/mongodb/lib/topologies/native_topology.js:58:11)
    at insertDocuments (/dist/node_modules/mongodb/lib/operations/common_functions.js:260:19)
    at InsertOneOperation.execute (/dist/node_modules/mongodb/lib/operations/insert_one.js:26:5)
    at executeOperation (/dist/node_modules/mongodb/lib/operations/execute_operation.js:83:26)
    at Collection.insertOne (/dist/node_modules/mongodb/lib/collection.js:476:10)
    at NativeCollection.(anonymous function) [as insertOne] (/dist/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:166:28)
    at model.Model.$__handleSave (/dist/node_modules/mongoose/lib/model.js:262:33)
    at model.Model.$__save (/dist/node_modules/mongoose/lib/model.js:320:8)
    at /dist/node_modules/kareem/index.js:278:20
    at _next (/dist/node_modules/kareem/index.js:102:16)
    at process.nextTick (/dist/node_modules/kareem/index.js:507:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by lukasburns** [comment]
Happens to me as well with same version of mongoose,

**Comment by vkarpov15** [comment]
This error generally occurs when you lose connectivity to the database. Can you clarify whether you're connecting to a standalone mongodb instance, replica set, sharded cluster, or MongoDB Atlas? And are there any connectivity issues, server resets, etc. around the time when you experience this issue?

**Comment by rvillane** [comment]
Hello, I'm connecting against a mongoDB replica set.  Someone peculiar is that multiple apps share the same connection string (using the same kubernetes secret) and they use the same mongoose version and connection settings, however only one of them is getting this error.

**Comment by antony** [comment]
I'm not using mongoose, just the raw mongo driver (3.2.2), with Atlas. I do seem to be seeing this a lot in the last couple of weeks. Just in case it's useful.

**Comment by blasterbug** [comment]
@antony  Did you see that error too?cloud
```
MongoTimeoutError: Server selection timed out after 30000 ms
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/topology.js:850:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by antony** [comment]
@blasterbug Yeah - that and one about topology sometimes.

**Comment by thihathit** [comment]
happens to me as well. I also set `useUnifiedTopology` to avoid warning message

**Comment by evancauwenberg** [comment]
I have the same issue, will subscribe to this one. 
Removed the "useUnifiedTopology" for now to check if that will solve it.
