### ISSUE TITLE
We're getting the error on our production server after enabling useUnifiedTopology.

### ISSUE THREAD

**Issue by Rockolin** [Automattic/mongoose#8263]
```
MongoTimeoutError: Server selection timed out after 30000 ms
    at Timeout.setTimeout [as _onTimeout] (/opt/app/node_modules/mongodb/lib/core/sdam/topology.js:850:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by esetnik** [comment]
This might be related to #5169 #8209

**Comment by OP-Klaus** [comment]
@Rockolin what was the solution?
