### ISSUE TITLE
AssertionError [ERR_ASSERTION]: mongoose.Promise must be a function, got undefined

### ISSUE THREAD

**Issue by rhazz** [Automattic/mongoose#8366]
receive AssertionError [ERR_ASSERTION]: mongoose.Promise must be a function, got undefined
 exemple usage
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });

const Cat = mongoose.model('Cat', { name: String });

const kitty = new Cat({ name: 'Zildjian' });
kitty.save().then(() => console.log('meow'));

**Comment by AbdelrahmanHafez** [comment]
Please follow the template to fill an issue.

**Comment by rhazz** [comment]
Linux xNot 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

MongoDB shell version v3.6.8
node v13.1.0 (npm v6.12.1)

.env
PORT =3000


server.js

const express = require('express')
app = express()
require("dotenv-safe").config();

var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/financeiro', {
    useUnifiedTopology: true,
    useNewUrlParser: true
});

const Cat = mongoose.model('Cat', { name: String });

const kitty = new Cat({ name: 'Zildjian' });
kitty.save().then(() => console.log('meow'));


app.listen(process.env.PORT, function () {
    console.log(`Server is running on port:${process.env.PORT}`)
})


ERROR
AssertionError [ERR_ASSERTION]: mongoose.Promise must be a function, got undefined
    at Object.store.set (/mnt/5406B73E06B71FC2/api/node_modules/mongoose/lib/promise_provider.js:37:10)
    at Object.<anonymous> (/mnt/5406B73E06B71FC2/api/node_modules/mongoose/lib/promise_provider.js:47:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/5406B73E06B71FC2/api/node_modules/mongoose/lib/utils.js:10:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/5406B73E06B71FC2/api/node_modules/mongoose/lib/options/SchemaTypeOptions.js:3:15) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by AbdelrahmanHafez** [comment]
Can not reproduce. Please close this issue, and open a new one if you can consistently reproduce it, and provide a reproduction script, mentioning all versions you are using. MongoDB, mongoose, and Node.

```js
const express = require('express');
const app = express();

const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/financeiro', { useUnifiedTopology: true, useNewUrlParser: true });

const Cat = mongoose.model('Cat', { name: String });

const kitty = new Cat({ name: 'Zildjian' });
kitty.save().then(() => console.log('meow'));

app.listen(process.env.PORT, function () {
  console.log('Server is running on port: 3000');
});
```

logs:
```
Server is running on port: 3000
meow 
```

Windows 10 x64
Node v13.2.0 (and tested on v12.13.0 as well)
mongoose v5.7.11

**Comment by Its-Just-Nans** [comment]
I had the same problem but my error was that I override the `global` variable : /
