### ISSUE TITLE
Mongoose 5.7.13 TypeError: Cannot read property 'activePaths' of undefined

### ISSUE THREAD

**Issue by d4rth-v4d3r** [Automattic/mongoose#8392]
Bug

My code was working fine until update 5.7.13

```
2019-12-01T17:34:06.345999168Z TypeError: Cannot read property 'activePaths' of undefined
2019-12-01T17:34:06.346008167Z     at Object.Document.modifiedPaths (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/document.js:1674:52)
2019-12-01T17:34:06.346017932Z     at Object.Document.isModified (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/document.js:1745:44)
2019-12-01T17:34:06.346030897Z     at SingleNested.Subdocument.isModified (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/types/subdocument.js:128:29)
2019-12-01T17:34:06.346042057Z     at _init (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/document.js:633:17)
2019-12-01T17:34:06.346050904Z     at init (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/document.js:587:5)
2019-12-01T17:34:06.346059520Z     at SingleNested.Document.$__init (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/document.js:517:3)
2019-12-01T17:34:06.346068570Z     at SingleNested.syncWrapper [as $__init] (/home/node/app/ne-route-droker-api/node_modules/kareem/index.js:234:23)
2019-12-01T17:34:06.346077293Z     at SingleNested.Document.init (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/document.js:485:8)
2019-12-01T17:34:06.346086108Z     at SingleNestedPath.cast (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/schema/SingleNestedPath.js:170:12)
2019-12-01T17:34:06.346094942Z     at SingleNestedPath.SchemaType.applySetters (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/schematype.js:969:12)
2019-12-01T17:34:06.346103914Z     at SingleNestedPath.SchemaType.getDefault (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/schematype.js:916:25)
2019-12-01T17:34:06.346112984Z     at /home/node/app/ne-route-droker-api/node_modules/mongoose/lib/helpers/setDefaultsOnInsert.js:84:33
2019-12-01T17:34:06.346121593Z     at Schema.eachPath (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/schema.js:944:5)
2019-12-01T17:34:06.346130137Z     at /home/node/app/ne-route-droker-api/node_modules/mongoose/lib/helpers/setDefaultsOnInsert.js:78:25
2019-12-01T17:34:06.346138830Z     at Schema.eachPath (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/schema.js:944:5)
2019-12-01T17:34:06.346149197Z     at module.exports (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/helpers/setDefaultsOnInsert.js:71:10)
2019-12-01T17:34:06.346158249Z     at model.Query.Query._findAndModify (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/query.js:3450:22)
2019-12-01T17:34:06.346167078Z     at model.Query.<anonymous> (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/query.js:3002:8)
2019-12-01T17:34:06.346177040Z     at model.Query._wrappedThunk [as _findOneAndUpdate] (/home/node/app/ne-route-droker-api/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
2019-12-01T17:34:06.346188146Z     at /home/node/app/ne-route-droker-api/node_modules/kareem/index.js:278:20
2019-12-01T17:34:06.346215611Z     at _next (/home/node/app/ne-route-droker-api/node_modules/kareem/index.js:102:16)
2019-12-01T17:34:06.346225405Z     at process.nextTick (/home/node/app/ne-route-droker-api/node_modules/kareem/index.js:507:38)
2019-12-01T17:34:06.346234009Z     at process._tickCallback (internal/process/next_tick.js:61:11)
2019-12-01T17:34:06.377675206Z error Command failed with exit code 1.

```

I did not make any changes to my source code, just update package. It should work fine. I rolled back to package 5.7.1 and everything works.

Mongo 4.1
Node 10 LTS
Mongoose version 5.7.13

**Comment by vkarpov15** [comment]
What does your code look like? Stack trace might help in this case but may not be enough.
