### ISSUE TITLE
Map + Splice on CoreDocumentArray throws TypeError

### ISSUE THREAD

**Issue by nbcraft** [Automattic/mongoose#8399]
**Do you want to request a *feature* or report a *bug*?**

Bug
Might be related to #8312

**What is the current behavior?**

In 5.7.12 (but also 5.7.7) calling `.map().splice()` on a `CoreDocumentArray` errors this out:
```
     TypeError: Cannot read property 'casterConstructor' of undefined
      at CoreDocumentArray._cast (node_modules/mongoose/lib/types/documentarray.js:46:47)
      at CoreDocumentArray.splice (node_modules/mongoose/lib/types/core_array.js:759:16)
      at CoreDocumentArray.splice (node_modules/mongoose/lib/types/documentarray.js:234:30)
```

Notes:
- Also happens in 5.6.13 - Seems to be CoreMongooseArray then
- Looks fine in 5.5.15 - Still CoreMongooseArray
- Looks fine in 5.0.18 - Is a a regular JS Array then though, so that makes sense.

**If the current behavior is a bug, please provide the steps to reproduce.**
- make a collection with nested array
- create a document with array values (no need to save)
- run `.map().splice()` on the nested array

(see script below https://github.com/Automattic/mongoose/issues/8399#issuecomment-561464630)

**What is the expected behavior?**
Splice like any array

**What are the versions of Node.js, Mongoose and MongoDB you are using?** 
MongoDB 3.6.12
Mongoose 5.7.12
Node 8.11.1

cc @vkarpov15

**Comment by nbcraft** [comment]
While writing a script to reproduce, realised that it was only happening after running `map()` on the `CoreDocumentArray`.

Here is the script:
```js
const mongoose = require('mongoose');

const MyModel = mongoose.model(
  'MyModel',
  new mongoose.Schema({
    myArray: [
      {
        name: { type: String }
      }
    ]
  })
);

const run = async () => {
  try {
    let { myArray } = new MyModel({
      myArray: [{ name: 'a' }, { name: 'b' }, { name: 'c' }]
    });

    // if you skip this map, it won't crash
    myArray = myArray.map(b => ({
      name: `${b.name} mapped`
    }));

    console.dir(myArray, { depth: null });

    myArray.splice(1, 1, { name: 'd' });

    console.dir(myArray, { depth: null });

    process.exit(0);
  } catch (error) {
    console.error('ERROR:');
    console.dir(error, { depth: null });
    process.exit(1);
  }
};

if (require.main === module) run();

```
