### ISSUE TITLE
cannot write to `xxx`

### ISSUE THREAD

**Issue by ahmedisam99** [Automattic/mongoose#8408]
**What is the current behavior?**
```
(node:23820) UnhandledPromiseRejectionWarning: MongoError: cannot write to 'jurny-stg.system.indexes'
    at Function.MongoError.create (/home/ahmedisam99/repos/personal/Jurny_backend_Admin/node_modules/mongodb-core/lib/
error.js:31:11)
    at /home/ahmedisam99/repos/personal/Jurny_backend_Admin/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/home/ahmedisam99/repos/personal/Jurny_backend_Admin/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/home/ahmedisam99/repos/personal/Jurny_backend_Admin/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/home/ahmedisam99/repos/personal/Jurny_backend_Admin/node_modules/mongodb-core/lib/connection/connection.js:363:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
- Nodejs: `v10.16.3`
- Mongoose: `v4.4.19`
- MongoDB: `v4.2.1`

**Comment by vkarpov15** [comment]
What does your code look like? The stack trace isn't enough to debug what's happening here.
