### ISSUE TITLE
Problem when trying to save / add new document!!!!!

### ISSUE THREAD

**Issue by ananbetak** [Automattic/mongoose#8431]
Cast to ObjectId failed for value "add" at path "_id" for model "shipwrecks"
i tried everything possible in the world !
all the options , types , everything.. nothing is working !

i am using "mongoose": "^5.8.1",

Thank you !!!

**Comment by ananbetak** [comment]
const mongoose = require('mongoose');

const Schema = mongoose.Schema;
const ObjectId = Schema.ObjectId;

const shipwrecks = new Schema({
  recrd: String,
  vesslterms: String,
  feature_type: String,
  chart: String,
  latdec: Number,
  londec: Number,
  gp_quality: String,
  depth: String,
  sounding_type: String,
  history: String,
  quasou: String,
  watlev: String,
  coordinates: Array
});

module.exports = mongoose.model('shipwrecks', shipwrecks);


router.post('/shipwrecks/add', (req, res) => {
  newShip = new shipwrecks();
  newShip.recrd = 'anan';
  newShip.vesslterms = 'kassis';
  newShip.feature_type = 'testing';
  newShip.chart = '1';
  newShip.latdec = 1;
  newShip.londec = 1;
  newShip.gp_quality = '1';
  newShip.depth = '1';
  newShip.sounding_type = '1';
  newShip.history = '1';
  newShip.quasou = '1';
  newShip.watlev = '1';
  newShip.coordinates = [1, 2, 3, 4, 5];
  newShip.insertOne((err, inserted) => {
    if (err) {
      console.log('error');
    } else {
      res.json(inserted);
    }
  })
});

**Comment by AbdelrahmanHafez** [comment]
One problem I could notice is you're using `newShip.insertOne(...)` which is not a function, you probably wanna use `newShip.save(...)`.

You might wanna give the [documentation](https://mongoosejs.com/docs/index.html) a visit, and familiarize yourself a little bit more on the mongoose API.

The code below works:
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.connect('mongodb://127.0.0.1:27017/test');

const shipwrecksSchema = new Schema({
  recrd: String,
  vesslterms: String,
  feature_type: String,
  chart: String,
  latdec: Number,
  londec: Number,
  gp_quality: String,
  depth: String,
  sounding_type: String,
  history: String,
  quasou: String,
  watlev: String,
  coordinates: Array
});

const shipwrecks = mongoose.model('shipwrecks', shipwrecksSchema);

const newShip = new shipwrecks();
newShip.recrd = 'anan';
newShip.vesslterms = 'kassis';
newShip.feature_type = 'testing';
newShip.chart = '1';
newShip.latdec = 1;
newShip.londec = 1;
newShip.gp_quality = '1';
newShip.depth = '1';
newShip.sounding_type = '1';
newShip.history = '1';
newShip.quasou = '1';
newShip.watlev = '1';
newShip.coordinates = [1, 2, 3, 4, 5];
newShip.save((err, inserted) => {
  if (err) {
    console.log('error');
  } else {
    console.log(inserted);
  }
});
```

**Comment by ananbetak** [comment]
Hello
no ..
that is not working..
i was using save before, and changed it , because i was out of hope ...

i changed to save , and tried .. same problem

i am not using local database though ..
i am using mlab ,and yes , i was able to get data..
so it is not a connection error.

can you please re check ?



MongooseError [CastError]: Cast to ObjectId failed for value "add" at path "_id" for model "shipwrecks"
    at new CastError (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\error\cast.js:39:11)
    at ObjectId.cast (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schema\objectid.js:246:11)
    at ObjectId.SchemaType.applySetters (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schematype.js:975:12)
    at ObjectId.SchemaType._castForQuery (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schematype.js:1389:15)
    at ObjectId.SchemaType.castForQuery (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schematype.js:1379:15)
    at ObjectId.SchemaType.castForQueryWrapper (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schematype.js:1358:15)
    at cast (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\cast.js:315:32)
    at model.Query.Query.cast (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\query.js:4697:12)
    at model.Query.Query._castConditions (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\query.js:1876:10)
    at model.Query.<anonymous> (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\query.js:2131:8)
    at model.Query._wrappedThunk [as _findOne] (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at C:\Projects\MEAN\ngApp\node_modules\kareem\index.js:369:33
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  stringValue: '"add"',
  kind: 'ObjectId',
  value: 'add',
  path: '_id',
  reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
      at new ObjectID (C:\Projects\MEAN\ngApp\node_modules\bson\lib\bson\objectid.js:59:11)
      at castObjectId (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at ObjectId.cast (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schema\objectid.js:244:12)
      at ObjectId.SchemaType.applySetters (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schematype.js:975:12)
      at ObjectId.SchemaType._castForQuery (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schematype.js:1389:15)
      at ObjectId.SchemaType.castForQuery (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schematype.js:1379:15)
      at ObjectId.SchemaType.castForQueryWrapper (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\schematype.js:1358:15)
      at cast (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\cast.js:315:32)
      at model.Query.Query.cast (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\query.js:4697:12)
      at model.Query.Query._castConditions (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\query.js:1876:10)
      at model.Query.<anonymous> (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\query.js:2131:8)
      at model.Query._wrappedThunk [as _findOne] (C:\Projects\MEAN\ngApp\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
      at C:\Projects\MEAN\ngApp\node_modules\kareem\index.js:369:33
      at processTicksAndRejections (internal/process/task_queues.js:75:11),
  message: 'Cast to ObjectId failed for value "add" at path "_id" for model "shipwrecks"',
  name: 'CastError',
  model: Model { shipwrecks }

**Comment by ananbetak** [comment]
maybe it is the : i am using "mongoose": "^5.8.1", ???

**Comment by AbdelrahmanHafez** [comment]
I don't think the mongoose version is the issue. 
From what I can see in here, you are trying to assign the document an _id of the string "add".

`document._id` should be an object id (24 hexadecimal characters).

**Comment by ananbetak** [comment]
Hello
This is my code

router.post('/shipwrecks/add', (req, res) => {
  newShip = new shipwrecks();
  newShip.recrd = 'anan';
  newShip.vesslterms = 'kassis';
  newShip.feature_type = 'testing';
  newShip.chart = '1';
  newShip.latdec = 1;
  newShip.londec = 1;
  newShip.gp_quality = '1';
  newShip.depth = '1';
  newShip.sounding_type = '1';
  newShip.history = '1';
  newShip.quasou = '1';
  newShip.watlev = '1';
  newShip.coordinates = [1, 2, 3, 4, 5];
  newShip.save((err, inserted) => {
    if (err) {
      console.log('error');
    } else {
      console.log(inserted);
      res.json(inserted);
    }
  })
});

so , where is the "add" as id ?
Thanks

**Comment by AbdelrahmanHafez** [comment]
I am sorry, I can not reproduce your issue, and can't really do much without being able to reproduce it.

However, this is what the error means. With no more information or being unable to reproduce the issue, I can't provide any further assistance.

**Comment by ananbetak** [comment]
can you join me on anydesk to check it live please ?

**Comment by AbdelrahmanHafez** [comment]
Sorry, I can't do that.

**Comment by ananbetak** [comment]
Okey .. i found the problem ...
it only happened, when i import default mock data from atlas cluster...
i don't know what is the reason for that .. but it is good to check that ..
Thank you anyways

**Comment by AbdelrahmanHafez** [comment]
Glad to know you figured it out!
