### ISSUE TITLE
Unable to create a stable read-only connection when useMongoClient: true

### ISSUE THREAD

**Issue by jync** [Automattic/mongoose#8484]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the connection string has `&readPreference=secondary&readPreferenceTags=nodeType:ANALYTICS`

- Calling `mongoose.connect` hangs when `socketTimeoutMS` is set to 30,000 (seems to be ok when it is set to 300. The default is 360,000)
- If `socketTimeoutMS` is 300, connect works, but queries fail intermittently with:

```
TypeError: Cannot read property 'wireProtocolHandler' of null
    at nextFunction (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongodb-core/lib/cursor.js:577:32)
    at Cursor.next [as _next] (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongodb-core/lib/cursor.js:701:3)
    at fetchDocs (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:857:10)
    at toArray (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:884:3)
    at Cursor.toArray (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:837:44)
    at /Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mquery/lib/collection/node.js:30:14
    at handleCallback (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at Collection.find (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongoose/node_modules/mongodb/lib/collection.js:384:44)
    at NativeCollection.(anonymous function) [as find] (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:130:28)
    at NodeCollection.find (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mquery/lib/collection/node.js:26:19)
    at model.Query.Query._find (/Users/theuser/Documents/projects/project1/backend/api-project/node_modules/mongoose/lib/query.js:1353:27)
    at /Users/theuser/Documents/projects/project1/backend/api-project/node_modules/kareem/index.js:250:8
    at /Users/theuser/Documents/projects/project1/backend/api-project/node_modules/kareem/index.js:23:7
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoUrl = "mongodb://user:password@a0.server.net:27017,a1.server.net:27017,a2.server.net:27017,a3.server.net:27017/mydb?ssl=true&replicaSet=rs-9399530&authSource=admin&w=majority&readPreference=secondary&readPreferenceTags=nodeType:ANALYTICS";

const options = {
        useMongoClient: true,
        autoReconnect: true,
        keepAlive: true,
        socketTimeoutMS: 30000
}

// this hangs unless socketTimeoutMS is 300
await mongoose.connect(mongoUrl, options);

const User = mongoose.model('User');

// this intermittently fails with "TypeError: Cannot read property 'wireProtocolHandler' of null"
// if socketTimeoutMS is set to 300. Sometimes this succeeds.
const users = await User.find({});
```

**What is the expected behavior?**

- `mongoose.connect` should not hang and/or an error is reported
- calling `find` should not intermittently fail

Setting `useMongoClient` to `false` "fixes" this.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 4.13.19
MongoDB driver: 3.4.1
MongoDB server: 3.4.23
NodeJS: 10.16.0

----

Whilst I understand the above isn't Mongoose 5.x, I'm concerned that this issue is in the 5.x version given `useMongoClient` has been removed and is now the default. Trying understand what might be causing the above will really help.

Is there any flags, tips or logs that I can enable / look at to investigate why

1. having a high `socketTimeoutMS` causes `connect` to hang when connecting to secondaries?
2. when `socketTimeoutMS` is low, why queries would intermittently fail with `Cannot read property 'wireProtocolHandler' of null`

Just looking for some guidance / help to point me in the right direction.

**Comment by vkarpov15** [comment]
I haven't seen either of these errors happen before, I'll investigate more this week and get back to you.

**Comment by vkarpov15** [comment]
I'm unable to repro this locally, the below script works fine for me:

```javascript
const mongoose = require('mongoose');

const mongoUrl = "mongodb://localhost:27017,localhost:27018,localhost:27019/mydb?replicaSet=rs&w=majority&readPreference=secondary&type=type:ANALYTICS";

const options = {
        useMongoClient: true,
        autoReconnect: true,
        keepAlive: true,
        socketTimeoutMS: 300
}

run().catch(err => console.log(err));

async function run() {
// this hangs unless socketTimeoutMS is 300
await mongoose.connect(mongoUrl, options);

const User = mongoose.model('User', mongoose.Schema({ name: String }));

// this intermittently fails with "TypeError: Cannot read property 'wireProtocolHandler' of null"
// if socketTimeoutMS is set to 300. Sometimes this succeeds.
const users = await User.find({});

console.log('done');
}
```

Below is my `rs.conf()`:

```
rs:PRIMARY> rs.conf()
{
	"_id" : "rs",
	"version" : 2,
	"protocolVersion" : NumberLong(1),
	"writeConcernMajorityJournalDefault" : true,
	"members" : [
		{
			"_id" : 1,
			"host" : "localhost:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 2,
			"host" : "localhost:27018",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 3,
			"host" : "localhost:27019",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				"type" : "ANALYTICS"
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	],
	"settings" : {
		"chainingAllowed" : true,
		"heartbeatIntervalMillis" : 2000,
		"heartbeatTimeoutSecs" : 10,
		"electionTimeoutMillis" : 10000,
		"catchUpTimeoutMillis" : -1,
		"catchUpTakeoverDelayMillis" : 30000,
		"getLastErrorModes" : {
			
		},
		"getLastErrorDefaults" : {
			"w" : 1,
			"wtimeout" : 0
		},
		"replicaSetId" : ObjectId("5e20ab92b408227a2b0d42f6")
	}
}
```

Can you please paste the output of `rs.conf()` so I can see the status of your replica set?

For low `socketTimeoutMS`, it could be that your queries are timing out. 300ms is generally too low if you aren't running MongoDB locally, one round trip with a slightly slow query could cause the connection to time out.

Could it be that you're connecting when the primary is down? Try setting the `connectWithNoPrimary` option to `true` in `mongoose.connect()` and see if that helps.
