### ISSUE TITLE
ValidationError how to handle the callback?

### ISSUE THREAD

**Issue by bidetaggle** [Automattic/mongoose#8560]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I catch a validation error, `console.log(err.errors)` gives me this output:
```
{
  dateOfBirth: MongooseError [ValidatorError]: Sorry mate, you're too young.
      at new ValidatorError (/home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/error/validator.js:29:11)
      at validate (/home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/schematype.js:1061:13)
      at /home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/schematype.js:1115:11
      at Array.forEach (<anonymous>)
      at SchemaDate.SchemaType.doValidate (/home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/schematype.js:1070:14)
      at /home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/helpers/updateValidators.js:155:22
      at module.exports (/home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/helpers/updateValidators.js:217:7)
      at /home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/query.js:3762:9
      at Object.promiseOrCallback (/home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/utils.js:261:12)
      at model.Query.validate (/home/bidetaggle/Desktop/boxbeat-media-server/node_modules/mongoose/lib/query.js:3757:16)
      at /home/bidetaggle/Desktop/boxbeat-media-server/node_modules/kareem/index.js:369:33
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
    message: "Sorry mate, you're too young.",
    name: 'ValidatorError',
    properties: {
      validator: [Function (anonymous)],
      message: "Sorry mate, you're too young.",
      type: 'max',
      max: 1012907600009,
      path: 'dateOfBirth',
      value: 2015-09-12T00:00:00.000Z
    },
    kind: 'max',
    path: 'dateOfBirth',
    value: 2015-09-12T00:00:00.000Z,
    reason: undefined,
    [Symbol(mongoose:validatorError)]: true
  }
}
```
The validators work when it comes to catch a validation error (and prevent to write in the db) but if I `console.log(err.errors['dateOfBirth'].message)`, here is what I get:

```
(node:24382) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dateOfBirth' of undefined
    at /home/bidetaggle/Desktop/boxbeat-media-server/api/controllers/user.js:51:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24382) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24382) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is my schema:
```
new Schema({
  phoneNumber: {
    type: String,
    trim: true,
    match: [/^[0-9]{10,11}$/ , 'phoneNumber is not valid'] //between 10 and 11 numbers
  },
  dateOfBirth: {
    type: Date,
    required: true,
    max: [
      new Date().setFullYear(new Date().getFullYear() - CONFIG.rules.legalAge), // forbidden for younger than a certain age
      "Sorry mate, you're too young."
    ]
  },
session: {
    id: {
      type: String,
      required: false
    }
  }
});
```
Here is the query
```
Users.updateOne(
  { 'session.id': decoded.sessionID },
  { $set: { dateOfBirth: req.body.dateOfBirth } },
  { runValidators: true }
)
.then((result) => {
  // if it modifies an user
  if(result.n == 1){
    res.json({
      Error: false,
    });
  }
  // if no user has been modified, it means a wrong phone number and/or sessionID from the token
  else{
    res.json({
      Error: {
        name: 'invalidDataFromToken',
        message: "The phone number and/or the sessionID doesn't match with the server record"
      }
    });
  }
}).catch((err) => {
  console.log(err.errors);                      // <- first output given above
  console.log(err.errors['dateOfBirth']); // <- second output given above (Cannot read property 'dateOfBirth' of undefined)
  res.json({
    Error: {
      name: 'db',
      message: err.errors
    }
  });
});
```

**What is the expected behavior?**

`console.log(err.errors['dateOfBirth'].message);` should gives `"Sorry mate, you're too young."`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v13.7.0
Mongoose: 5.8.11
MongoDB: 4.2

**Comment by bidetaggle** [comment]
I don't know what happened, it works again. I was making a series of tests and I probably mixed up the outputs. I cannot even find again how I got this bug. Anyway in case of a `CastError`, `err.errors` doesn't exist so I test it in the code now. Although my first problem was about `ValidatorError`.
I post the piece of code that I edited, maybe it could help someone someday:
```
...
.catch(async (err) => {
  res.json({
    Error: {
      name: err.name,
      message: err.errors ? err.errors['dateOfBirth'].message : err.message
    }
  });
});
...
```
