### ISSUE TITLE
Mongoose Document { undefined }

### ISSUE THREAD

**Issue by Puwka** [Automattic/mongoose#8565]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Just migrated to `mongoose@5.8.11` from `mongoose@5.4.4` and `Document.set` method fails

**If the current behavior is a bug, please provide the steps to reproduce.**
I have 3 models with schemas like these: 
```javascript
const widgetSessionSchema = new mongoose.Schema({
  plaid: {
    nestedKey: String
  }
})
```

```javascript
const subscriptionSchema = new mongoose.Schema({
  plaid: {
    nestedKey: String
  }
})
```

```javascript
const chargeSchema = new mongoose.Schema({
  plaid: {
    nestedKey: String
  }
})
```

when Im trying to inherit `plaid` into `charge` document in this way: 
```javascript
// widgetSession could either contain plaid or not
const widgetSession = new WidgetSession({});

console.log(widgetSession.plaid) // {}

const subscription = new Subscription({ plaid: widgetSession.plaid });

console.log(subscription.plaid) // MongooseDocument { undefined }

const charge = new Charge({});

charge.set({
  plaid: subscription.plaid
});
```
Im getting an error: 

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at model.$set (node_modules/mongoose/lib/document.js:867:21)
    at model._handleIndex (node_modules/mongoose/lib/document.js:915:12)
    at model.$set (node_modules/mongoose/lib/document.js:879:22)
    at Context.<anonymous> (tests/unittests/models/subscription.spec.js:152:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
```

**What is the expected behavior?**
`charge.set` method does not end up in failure

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: 12.14.1
Mongoose: 5.8.11
MongoDB: 4.2.0

**Comment by Puwka** [comment]
`rerpo script`

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/test', {useNewUrlParser: true, useUnifiedTopology: true})

const widgetSessionSchema = new mongoose.Schema({
    plaid: {
        nestedKey: String
    }
});
const subscriptionSchema = new mongoose.Schema({
    plaid: {
        nestedKey: String
    }
});
const chargeSchema = new mongoose.Schema({
    plaid: {
        nestedKey: String
    }
});

const WidgetSession = mongoose.model('WidgetSession', widgetSessionSchema);
const Subscription = mongoose.model('Subscription', subscriptionSchema);
const Charge = mongoose.model('Charge', chargeSchema);

const widgetSession = new WidgetSession({});

console.log(widgetSession.plaid); // {}

const subscription = new Subscription({ plaid: widgetSession.plaid });

console.log(subscription.plaid); // MongooseDocument { undefined }

const charge = new Charge({});

charge.set({
    plaid: subscription.plaid
});

```
