### ISSUE TITLE
[new bug since 5.5.3, HAS REPRO SCRIPT] problems with single nested subdoc/ subdoc arrays

### ISSUE THREAD

**Issue by marcelh-gh** [Automattic/mongoose#8585]
I had reported a bug related to this broader issue before (#7601). That was fixed in 5.4.21.
Unfortunately a new bug was introduced later causing validation errors when writing back deeply nested documents to the db after getting them from the db prior to that.

It took quite some work to narrow down when exactly the error was introduced: it was **5.5.3**.
Specifically the changes to **documentarray.js**.

Since then a lot of additional changes have been made to that file and the particular loc, none of them resolving the issue. (i have tracked and checked the changes up until the current 5.8.11)

Below is a stripped down repro script taking away all of the complexities of the scenario where the error occurred: the issue is there even for a fairly simple schema structure.

It seems getters/setters are called appropriately when single primitive properties of schemas are accessed, but they are not if access is via an entire subschema.  

Node 12.13.0
MongoDB 4.2.1
Mongoose 5.5.2 -> 5.8.11

```
import { Schema, model } from "mongoose";

import Decimal from "decimal.js";
import { DateTime } from "luxon";

import { Decimal128 } from "mongodb";

const util = require("util");
const logObject = (obj) => console.log(util.inspect(obj, { showHidden: false, depth: null }));


const DateTimeAsDate = (value) => value.toJSDate();
const DateAsDateTime = (value) => DateTime.fromJSDate(value);

const Dec128AsDec = (value) =>
    value !== undefined ? new Decimal(value.toString()) : undefined;
const DecAsDec128 = (value) =>
    value !== undefined ? Decimal128.fromString(value.valueOf()) : undefined;

const requiredDate =
{
    type: Date, required: true,
    get: DateAsDateTime, set: DateTimeAsDate
};

const requiredDecimal =
{
    type: Schema.Types.Decimal128, required: true,
    set: DecAsDec128, get: Dec128AsDec
};


const ChildDetails = new Schema({
    date: requiredDate,
    value: requiredDecimal
});

const Child = new Schema(
    {
        details: { type: [ChildDetails] },
        value: requiredDecimal
    }
);

const Repro = new Schema(
    {
        ID: String,
        child: { type: Child },
        timestamp: requiredDate
    }
);

const reproTestDetails =
{
    details: [
        {
            date: DateTime.local(),
            value: new Decimal(34.2)
        }
    ],
    value: new Decimal(45.7)
};


const reproModel = model("repro", Repro);
const repro1 = new reproModel();
repro1.ID = "ID1";
repro1.timestamp = DateTime.local();
repro1.child = reproTestDetails;
await reproModel.create(repro1);


const reproFromDB = await reproModel.findOne({ ID: "ID1" }).exec();

// logObject(reproFromDB.timestamp);
// logObject(reproFromDB.child.details[0].date);

const ChildFromRepro1 = reproFromDB.child;
// logObject(ChildFromRepro1);

const repro2 = new reproModel();
repro2.ID = "ID2";
repro2.timestamp = DateTime.local();
repro2.child = ChildFromRepro1;

// This fails in Mongoose >= 5.5.3 with validation errors because of casting problems
// works fine in 5.5.2
const reproInDB2 = await reproModel.create(repro2);
```

**Comment by marcelh-gh** [comment]
I greatly appreciate the plans to unify single nested docs and subdoc arrays (#8554 ).
I think some of the difficulties of keeping things in order regarding these things will go away.

**Comment by vkarpov15** [comment]
What is the exact error message you get? The below script works fine for me on 5.5.3, although it does start failing on 5.8.1:

```javascript
const { Schema, model, connect } = require("mongoose");
const Decimal = require("decimal.js");
const { DateTime } = require("luxon");
const Decimal128 = require("mongoose").Types.Decimal128;
const util = require("util");

const logObject = (obj) => console.log(util.inspect(obj, { showHidden: false, depth: null }));
const DateTimeAsDate = (value) => value.toJSDate();
const DateAsDateTime = (value) => DateTime.fromJSDate(value);

const Dec128AsDec = (value) =>
    value !== undefined ? new Decimal(value.toString()) : undefined;
const DecAsDec128 = (value) =>
    value !== undefined ? Decimal128.fromString(value.valueOf()) : undefined;

const requiredDate = {
  type: Date, required: true,
  get: DateAsDateTime, set: DateTimeAsDate
};
const requiredDecimal = {
  type: Schema.Types.Decimal128, required: true,
  set: DecAsDec128, get: Dec128AsDec
};

const ChildDetails = Schema({ date: requiredDate, value: requiredDecimal });
const Child = Schema({ details: [ChildDetails], value: requiredDecimal });
const Repro = Schema({ ID: String, child: Child, timestamp: requiredDate });

const reproTestDetails = {
  details: [{
    date: DateTime.local(),
    value: new Decimal(34.2)
  }],
  value: new Decimal(45.7)
};

run().catch(err => console.log(err));

async function run() {
  await connect('mongodb://localhost:27017/test');

  const reproModel = model("repro", Repro);
  const repro1 = new reproModel();
  repro1.ID = "ID1";
  repro1.timestamp = DateTime.local();
  repro1.child = reproTestDetails;
  await reproModel.create(repro1);


  const reproFromDB = await reproModel.findOne({ ID: "ID1" }).exec();

  const ChildFromRepro1 = reproFromDB.child;

  const repro2 = new reproModel();
  repro2.ID = "ID2";
  repro2.timestamp = DateTime.local();
  repro2.child = ChildFromRepro1;

  // This fails in Mongoose >= 5.5.3 with validation errors because of casting problems
  // works fine in 5.5.2
  const reproInDB2 = await reproModel.create(repro2);

  console.log('done');
}
```

Gives me the below error starting on v5.8.1:

```
{ ValidationError: repro validation failed: child.value: Cast to Decimal128 failed for value "Decimal128 {
  _bsontype: 'Decimal128',
  bytes: <Buffer c9 01 00 00 00 00 00 00 00 00 00 00 00 00 3e 30> }" at path "value", child: Validation failed: value: Cast to Decimal128 failed for value "Decimal128 {
  _bsontype: 'Decimal128',
  bytes: <Buffer c9 01 00 00 00 00 00 00 00 00 00 00 00 00 3e 30> }" at path "value"
    at ValidationError.inspect (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/error/validation.js:61:24)
    at formatValue (internal/util/inspect.js:491:31)
    at inspect (internal/util/inspect.js:189:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (console.js:191:15)
    at Console.log (console.js:202:31)
    at run.catch.err (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-8585.js:65:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errors:
   { 'child.value':
      { CastError: Cast to Decimal128 failed for value "Decimal128 {
        _bsontype: 'Decimal128',
        bytes: <Buffer c9 01 00 00 00 00 00 00 00 00 00 00 00 00 3e 30> }" at path "value"
          at new CastError (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/error/cast.js:39:11)
          at SingleNested.$set (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:1195:9)
          at SingleNested._handleIndex (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:934:14)
          at SingleNested.$set (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:878:22)
          at SingleNested.Document (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:136:12)
          at SingleNested.Subdocument (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/types/subdocument.js:34:12)
          at new SingleNested (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/schema/SingleNestedPath.js:75:17)
          at SingleNestedPath.cast (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/schema/SingleNestedPath.js:190:12)
          at SingleNestedPath.SchemaType.applySetters (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/schematype.js:975:12)
          at model.$set (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:1167:20)
          at model.set [as child] (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/helpers/document/compile.js:148:26)
          at run (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-8585.js:89:16)
          at process._tickCallback (internal/process/next_tick.js:68:7)
        stringValue:
         '"Decimal128 {\n  _bsontype: \'Decimal128\',\n  bytes: <Buffer c9 01 00 00 00 00 00 00 00 00 00 00 00 00 3e 30> }"',
        kind: 'Decimal128',
        value: [Decimal128],
        path: 'value',
        reason:
         TypeError: string.trim is not a function
             at Function.Decimal128.fromString (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/bson/lib/bson/decimal128.js:238:19)
             at SingleNested.DecAsDec128 (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-8585.js:19:38)
             at Decimal128.SchemaType._applySetters (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/schematype.js:944:22)
             at Decimal128.SchemaType.applySetters (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/schematype.js:968:16)
             at SingleNested.$set (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:1167:20)
             at SingleNested._handleIndex (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:934:14)
             at SingleNested.$set (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:878:22)
             at SingleNested.Document (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:136:12)
             at SingleNested.Subdocument (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/types/subdocument.js:34:12)
             at new SingleNested (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/schema/SingleNestedPath.js:75:17)
             at SingleNestedPath.cast (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/schema/SingleNestedPath.js:190:12)
             at SingleNestedPath.SchemaType.applySetters (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/schematype.js:975:12)
             at model.$set (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/document.js:1167:20)
             at model.set [as child] (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/helpers/document/compile.js:148:26)
             at run (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-8585.js:89:16)
             at process._tickCallback (internal/process/next_tick.js:68:7),
        message:
         'Cast to Decimal128 failed for value "Decimal128 {\n  _bsontype: \'Decimal128\',\n  bytes: <Buffer c9 01 00 00 00 00 00 00 00 00 00 00 00 00 3e 30> }" at path "value"',
        name: 'CastError' },
     child:
      { ValidationError: Validation failed: value: Cast to Decimal128 failed for value "Decimal128 {
        _bsontype: 'Decimal128',
        bytes: <Buffer c9 01 00 00 00 00 00 00 00 00 00 00 00 00 3e 30> }" at path "value"
          at ValidationError.inspect (/home/val/Workspace/MongoDB/troubleshoot-mongoose/node_modules/mongoose/lib/error/validation.js:61:24)
          at formatValue (internal/util/inspect.js:491:31)
          at formatProperty (internal/util/inspect.js:1071:11)
          at formatRaw (internal/util/inspect.js:727:11)
          at formatValue (internal/util/inspect.js:509:10)
          at formatProperty (internal/util/inspect.js:1071:11)
          at formatRaw (internal/util/inspect.js:727:11)
          at formatValue (internal/util/inspect.js:509:10)
          at formatValue (internal/util/inspect.js:497:18)
          at inspect (internal/util/inspect.js:189:10)
          at Object.formatWithOptions (util.js:84:12)
          at Console.(anonymous function) (console.js:191:15)
          at Console.log (console.js:202:31)
          at run.catch.err (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-8585.js:65:28)
          at process._tickCallback (internal/process/next_tick.js:68:7)
        errors: [Object],
        _message: 'Validation failed',
        name: 'ValidationError' } },
  _message: 'repro validation failed',
  name: 'ValidationError' }
^C

```

I'll work on figuring out why this error started in v5.8.1, but can you please confirm what error message you're seeing? Thanks :+1:

**Comment by vkarpov15** [comment]
Upon further investigation I'm going to have to close this as intentional behavior. The solution is to make your setters support passing in instances of `Decimal128` and `DateTime`, instead of assuming they always get strings. Fix is shown below:

```javascript
const DateTimeAsDate = (value) => {
  return value instanceof DateTime ? value.toJSDate() : value;
};
const DateAsDateTime = (value) => DateTime.fromJSDate(value);

const Dec128AsDec = (value) =>
    value !== undefined ? new Decimal(value.toString()) : undefined;
const DecAsDec128 = (value) =>
    value !== undefined ? Decimal128.fromString(value.toString()) : undefined;
```

Before 5.8.1, we had a bug (#8400) that meant Mongoose wouldn't make a copy of a single nested subdoc when setting, which lead to incorrect `parent` references. After v5.8.1, we now create a new single nested subdoc when you set `doc1.singleNestedSubdoc = doc2.singleNestedSubdoc`, which means your setters need to handle the values in `doc2.singleNestedSubdoc`. Mongoose could work around this by calling getters on `doc2.singleNestedSubdoc` subpaths first, but that sounds risky right now.
