### ISSUE TITLE
Cannot read property 'refPath' of undefined

### ISSUE THREAD

**Issue by bookyo** [Automattic/mongoose#8586]
this my schema and models:
```
var mongoose = require("mongoose")
var Schema = mongoose.Schema
var VipuserSchema = new Schema({
  title: String,
  permission: Number,
  createAt: {
    type: Date
  }
})
VipuserSchema.pre("save", function(next) {
  if (!this.createAt) {
    this.createAt = Date.now()
  }
  next()
})
var Vipuser = mongoose.model("Vipuser", VipuserSchema)
module.exports = Vipuser


var mongoose = require("mongoose")
var Schema = mongoose.Schema
var VipbuySchema = new Schema({
  duration: Number,
  group: { type: Schema.Types.ObjectId, ref: 'Vipuser' },
  score: Number,
  createAt: {
    type: Date
  }
})
VipbuySchema.pre("save", function(next) {
  if (!this.createAt) {
    this.createAt = Date.now()
  }
  next()
})
module.exports = VipbuySchema
var Vipbuy = mongoose.model("Vipbuy", VipbuySchema)
module.exports = Vipbuy
```
my controller code:
```
exports.adminvip = async (req, res) => {
  const vipbuys = await Vipbuy.findOne().populate('group');
  res.render('admin/vipbuy', {
    title: 'vipbuy items',
    vipbuys,
  });
};
```

show error:
```
Cannot read property 'refPath' of undefined
    at getModelsMapForPopulate (/mnt/d/www/express-ffmpeg-vip/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:53:75)
    at populate (/mnt/d/www/express-ffmpeg-vip/node_modules/mongoose/lib/model.js:4272:21)
    at _populate (/mnt/d/www/express-ffmpeg-vip/node_modules/mongoose/lib/model.js:4242:5)
    at /mnt/d/www/express-ffmpeg-vip/node_modules/mongoose/lib/model.js:4217:5
    at promiseOrCallback (/mnt/d/www/express-ffmpeg-vip/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
    at Function.Model.populate (/mnt/d/www/express-ffmpeg-vip/node_modules/mongoose/lib/model.js:4215:10)
    at model.Query.Query._completeOne (/mnt/d/www/express-ffmpeg-vip/node_modules/mongoose/lib/query.js:2097:9)
    at Immediate.<anonymous> (/mnt/d/www/express-ffmpeg-vip/node_modules/mongoose/lib/query.js:2136:10)
    at Immediate.<anonymous> (/mnt/d/www/express-ffmpeg-vip/node_modules/mquery/lib/utils.js:116:16)
```
what happening?
i update mongoose to 5.8.12 and cause this error.

**Comment by bookyo** [comment]
my all ref connot use populte query like:
group: { type: Schema.Types.ObjectId, ref: "Group" },

**Comment by bookyo** [comment]
can fix it change getModelsMapForPopulate.js:
```
let normalizedRefPath = null;
···
and work fine!!

**Comment by vkarpov15** [comment]
I'm unable to repro this issue, the below script executes without error for me:

```javascript
var mongoose = require("mongoose")
var Schema = mongoose.Schema
var VipuserSchema = new Schema({
  title: String,
  permission: Number,
  createAt: {
    type: Date
  }
})
VipuserSchema.pre("save", function(next) {
  if (!this.createAt) {
    this.createAt = Date.now()
  }
  next()
})
var Vipuser = mongoose.model("Vipuser", VipuserSchema)


var VipbuySchema = new Schema({
  duration: Number,
  group: { type: Schema.Types.ObjectId, ref: 'Vipuser' },
  score: Number,
  createAt: {
    type: Date
  }
})
VipbuySchema.pre("save", function(next) {
  if (!this.createAt) {
    this.createAt = Date.now()
  }
  next()
})
var Vipbuy = mongoose.model("Vipbuy", VipbuySchema)

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const user = await Vipuser.create({ title: 'test' });
  const buy = await Vipbuy.create({ group: user._id, score: 10 });

  const res = await Vipbuy.findOne({ _id: buy._id }).populate('group');
  console.log(res);
}

```

Can you please modify the above script to demonstrate your issue?

In the meantime, I'll make a quick fix to reduce the likelihood of this issue happening

**Comment by bookyo** [comment]
console.log(_firstWithRefPath) will print -1.  can help you?

**Comment by vkarpov15** [comment]
@bookyo that sounds like you have a monkeypatched `Array.prototype.find()`, JavaScript's built-in `find()` function returns either a value in the array or `undefined`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find.

Can you please print out `console.log(Array.prototype.find.toString())` ? It should look like this: `function find() { [native code] }`.

**Comment by bookyo** [comment]
console.log(Array.prototype.find.toString()) will print:
```
function (value, equals) {
    equals = equals || this.contentEquals || Object.equals;
    for (var index = 0; index < this.length; index++) {
        if (index in this && equals(value, this[index])) {
            return index;
        }
    }
    return -1;
}
```

**Comment by vkarpov15** [comment]
Ah ok so the issue is that your JavaScript environment is broken, that implementation is incompatible with Node.js' `Array#find()`. Are you using some library that patches `find()`?

**Comment by tgoorden** [comment]
@bookyo Did you happen to figure out what caused this monkey patching? We're seeing exactly the same weird issue in a Meteor environment...
