### ISSUE TITLE
Mongoose transaction: TypeError: Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by linus-hologram** [Automattic/mongoose#8637]
Hey there,

if my mongoose transaction returns an empty, rejected Promise, I get the following error:

`TypeError: Cannot read property 'code' of undefined`

**Example code:**

```
const transactionSession = await mongoose.startSession()
await transactionSession.withTransaction(async (tSession) => {
try {
     // Transaction writes & reads removed for brevity

     console.log("Successfully performed transaction!")
     return Promise.resolve()
     } catch (error) {
     console.log("Transaction aborted due to error:", error)
     cb(error)

     return Promise.reject() // this causes the error, an empty promise
     // return Promise.reject(4) // this would work
     }
})
```

**These is the exact error output:**

```
TypeError: Cannot read property 'code' of undefined
    at isMaxTimeMSExpiredError (/Users/myapi/auth/node_modules/mongodb/lib/core/sessions.js:308:9)
    at maybeRetryOrThrow (/Users/myapi/auth/node_modules/mongodb/lib/core/sessions.js:376:13)
    at session.abortTransaction.then (/Users/myapi/auth/node_modules/mongodb/lib/core/sessions.js:387:54)
    at process._tickCallback (internal/process/next_tick.js:68:7)

TypeError: Cannot read property 'code' of undefined
    at isMaxTimeMSExpiredError (/Users/myapi/auth/node_modules/mongodb/lib/core/sessions.js:308:9)
    at maybeRetryOrThrow (/Users/myapi/auth/node_modules/mongodb/lib/core/sessions.js:376:13)
    at session.abortTransaction.then (/Users/myapi/auth/node_modules/mongodb/lib/core/sessions.js:387:54)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**My question:** Is it expected that there's an unhandled type error if the returned Promise does not have data attached to it?

Is it mandatory to pass a "code" to a rejected promise?

_The current mongoose version I'm using is 5.9.1_

**Comment by vkarpov15** [comment]
This is a bug that we'll fix.

However, I must tell you that [rejecting a promise with a value that isn't an error is generally an anti-pattern](https://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html), and some modules like [mocha](https://stackoverflow.com/questions/32899946/how-to-debug-error-promise-rejected-with-no-or-falsy-reason-in-mocha-tests) will error out if you do `Promise.reject()` with no arguments. Please do `Promise.reject(new Error('message here'))` instead.

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 I assume this one is fixed by the PR above, closing this.
