### ISSUE TITLE
useUnifiedTopology option impacts disconnection/reconnection events

### ISSUE THREAD

**Issue by tibeoh** [Automattic/mongoose#8643]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
useUnifiedTopology option has an impact on some mongodb events

**If the current behavior is a bug, please provide the steps to reproduce.**
To understand and reproduce this bug, I created this script and executed on a replicaset  (Mongodb Atlas) and a standalone server (local).
Process: Change the useUnifiedTopology option, waiting for the connection is ready, switch off wifi, waiting 1 minute, and switch on wifi to catch reconnection events.
But it does not work every time...
```javascript
const mongoose = require('mongoose');
// Replica : mongodb+srv://username:password@xxxxxx-ltlpg.mongodb.net/database
// Standalone : mongodb://username:password@xx.xx.xx.xxx:port/database
const url = ''

// Init options
const options = {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  useFindAndModify: false,
  useCreateIndex: true,
};

console.log('useUnifiedTopology', options.useUnifiedTopology);
// Create new Mongodb connection
let mongodbConnection = mongoose.createConnection(url, options);

// Init each events
['connecting', 'connected', 'open', 'disconnecting', 'disconnected', 'close', 'reconnected', 'error', 'fullsetup'].forEach(name => {
  mongodbConnection.on(name, err => {
    console.log(new Date().toISOString(), `Mongoose event: ${name} ${err || ''}`);
  });
});

// Every 2s, try to get nb of collections in database and print or print error
setInterval(() => {
  mongodbConnection.db.listCollections().toArray(function(err, collections) {
    if (err) console.log(new Date().toISOString(), 'err', err);
    if (collections) console.log(new Date().toISOString(), 'collections.length', collections.length);
  });
}, 2000);
```

My results:
|            | useUnifiedTopology | reconnection event | disconnection event | setInterval continue |
|:----------:|:------------------:|:------------------:|:-------------------:|:--------------------:|
| Replicaset |        `true`        |                    |                     |           x          |
| Replicaset |        `false`       |          x         |          x          |           x          |
| Standalone |        `true`        |          x         |          x          |                      |
| Standalone |        `false`       |                    |                     |                      |

Why events are not catched sometimes? And why the setInterval stopped with an error too when the connection is back?

Details logs with action of switch on/off wifi. Please take a look on the time!

### Replicaset and useUnifiedTopology `true`:
First try:
```
useUnifiedTopology true
16:34:54.994 Mongoose event: connected 
16:34:54.994 Mongoose event: open 
16:34:56.863 collections.length 23
16:34:58.617 collections.length 23
16:35:00.726 collections.length 23
16:35:02.648 collections.length 23
--------------- WIFI SWITCH OFF ---------------
16:35:36.597 err MongoServerSelectionError: getaddrinfo ENOTFOUND xxxxxx-00-01-ltlpg.mongodb.net
16:35:38.593 err MongoServerSelectionError: getaddrinfo ENOTFOUND xxxxxx-00-01-ltlpg.mongodb.net
16:35:40.602 err MongoServerSelectionError: getaddrinfo ENOTFOUND xxxxxx-00-01-ltlpg.mongodb.net
...
16:35:54.620 err MongoServerSelectionError: getaddrinfo ENOTFOUND xxxxxx-00-01-ltlpg.mongodb.net
16:35:56.625 err MongoServerSelectionError: getaddrinfo ENOTFOUND xxxxxx-00-01-ltlpg.mongodb.net
--------------- WIFI SWITCH ON ---------------
/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:87
    throw e;
    ^

TypeError: Cannot read property 'Symbol(cancelled)' of undefined
    at processWaitQueue (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:1001:24)
    at NativeTopology.selectServer (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:438:5)
    at executeWithServerSelection (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:137:12)
    at executeOperation (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:75:7)
    at CommandCursor._initializeCursor (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/cursor.js:545:7)
    at CommandCursor._initializeCursor (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/cursor.js:185:11)
    at Object.callback (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/cursor.js:438:14)
    at processWaitQueue (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:1030:21)
    at NativeTopology.selectServer (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:438:5)
    at executeWithServerSelection (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:137:12)
    at executeOperation (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:75:7)
    at CommandCursor._initializeCursor (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/cursor.js:545:7)
    at CommandCursor._initializeCursor (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/cursor.js:185:11)
    at Object.callback (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/cursor.js:438:14)
    at processWaitQueue (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:1030:21)
    at NativeTopology.selectServer (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:438:5)
```
Any idea why I have this issue (but keep focus on events issue, maybe new ticket?)
The replica server called is  xxxxxx-00-01-ltlpg.mongodb.net.

Second try:
```
useUnifiedTopology true
16:56:30.214 Mongoose event: connected 
16:56:30.214 Mongoose event: open 
16:56:32.153 collections.length 23
16:56:33.896 collections.length 23
16:56:35.956 collections.length 23
--------------- WIFI SWITCH OFF ---------------
16:57:09.866 err MongoServerSelectionError: getaddrinfo ENOTFOUND xxxxxx-00-00-ltlpg.mongodb.net
...
16:57:23.882 err MongoServerSelectionError: getaddrinfo ENOTFOUND xxxxxx-00-00-ltlpg.mongodb.net
16:57:25.884 err MongoServerSelectionError: getaddrinfo ENOTFOUND xxxxxx-00-00-ltlpg.mongodb.net
16:57:27.884 err MongoServerSelectionError: connection 1 to xx.xx.xx.xx:27017 closed
--------------- WIFI SWITCH ON ---------------
16:57:31.129 collections.length 23
16:57:31.132 collections.length 23
16:57:31.152 collections.length 23
16:57:31.165 collections.length 23
...
16:57:31.269 collections.length 23
16:57:31.979 collections.length 23
16:57:33.983 collections.length 23
16:57:35.989 collections.length 23
16:57:37.987 collections.length 23
...
```

### Replicaset and useUnifiedTopology `false`:
```
useUnifiedTopology false
(node:28467) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
16:31:22.536 Mongoose event: connected 
16:31:22.536 Mongoose event: open 
16:31:22.537 Mongoose event: fullsetup [object Object]
16:31:24.267 collections.length 23
16:31:26.272 collections.length 23
16:31:28.271 collections.length 23
16:31:30.279 collections.length 23
--------------- WIFI SWITCH OFF ---------------
16:31:50.612 err MongoError: no connection available to server xxxxxx-00-00-ltlpg.mongodb.net:27017
16:31:50.616 Mongoose event: disconnected 
16:31:52.551 err MongoError: Pool was force destroyed
16:31:52.552 err MongoError: Pool was force destroyed
...
16:31:52.555 err MongoError: Pool was force destroyed
16:31:52.555 err MongoError: Pool was force destroyed
16:31:52.573 err MongoError: Pool was force destroyed
16:32:02.276 err MongoError: no primary server available
16:32:04.277 err MongoError: no primary server available
...
16:32:16.299 err MongoError: no primary server available
16:32:18.301 err MongoError: no primary server available
16:32:20.302 err MongoError: no primary server available
--------------- WIFI SWITCH ON ---------------
16:32:20.427 collections.length 23
16:32:21.142 collections.length 23
16:32:21.145 collections.length 23
16:32:21.374 collections.length 23
16:32:21.378 collections.length 23
16:32:22.343 collections.length 23
16:32:22.588 Mongoose event: connected 
16:32:22.588 Mongoose event: reconnected 
16:32:24.343 collections.length 23
16:32:26.353 collections.length 23
16:32:28.363 collections.length 23
16:32:30.354 collections.length 23
16:32:32.364 collections.length 23
16:32:34.362 collections.length 23
...
```

### Standalone and useUnifiedTopology `true`:
```
useUnifiedTopology true
16:47:54.587 Mongoose event: connected 
16:47:54.587 Mongoose event: open 
16:47:56.576 collections.length 1
16:47:58.488 collections.length 1
16:48:00.490 collections.length 1
16:48:02.477 collections.length 1
16:48:04.538 collections.length 1
--------------- WIFI SWITCH OFF ---------------
16:48:08.477 Mongoose event: disconnected 
16:48:38.478 err MongoServerSelectionError: connect ENETUNREACH 192.168.1.9:27018 - Local (0.0.0.0:50650)
16:48:40.478 err MongoServerSelectionError: connect ENETUNREACH 192.168.1.9:27018 - Local (0.0.0.0:50653)
...
16:48:56.501 err MongoServerSelectionError: connect ENETUNREACH 192.168.1.9:27018 - Local (0.0.0.0:50680)
16:48:58.496 err MongoServerSelectionError: connect ENETUNREACH 192.168.1.9:27018 - Local (0.0.0.0:50683)
16:49:00.497 err MongoServerSelectionError: connection 1 to 192.168.1.9:27018 closed
16:49:02.498 err MongoServerSelectionError: connect ENETUNREACH 192.168.1.9:27018 - Local (0.0.0.0:50689)
...
16:49:12.526 err MongoServerSelectionError: connect ENETUNREACH 192.168.1.9:27018 - Local (0.0.0.0:50701)
--------------- WIFI SWITCH ON ---------------
16:49:13.535 Mongoose event: connected 
16:49:13.535 Mongoose event: reconnected 
/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:87
    throw e;
    ^

TypeError: Cannot read property 'Symbol(cancelled)' of undefined
    at processWaitQueue (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:1001:24)
    at NativeTopology.selectServer (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:438:5)
    at executeWithServerSelection (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:137:12)
    at executeOperation (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:75:7)
    at CommandCursor._initializeCursor (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/cursor.js:545:7)
    at CommandCursor._initializeCursor (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/cursor.js:185:11)
    at Object.callback (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/cursor.js:438:14)
    at processWaitQueue (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:1030:21)
    at NativeTopology.selectServer (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:438:5)
    at executeWithServerSelection (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:137:12)
    at executeOperation (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/operations/execute_operation.js:75:7)
    at CommandCursor._initializeCursor (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/cursor.js:545:7)
    at CommandCursor._initializeCursor (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/cursor.js:185:11)
    at Object.callback (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/cursor.js:438:14)
    at processWaitQueue (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:1030:21)
    at NativeTopology.selectServer (/Users/xxxx/mongoose-error/node_modules/mongodb/lib/core/sdam/topology.js:438:5)`
```
Same issue but on each try...

### Standalone and useUnifiedTopology `false`:
```
useUnifiedTopology false
(node:28816) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
16:44:33.787 Mongoose event: connected 
16:44:33.787 Mongoose event: open 
16:44:35.717 collections.length 1
16:44:37.818 collections.length 1
--------------- WIFI SWITCH OFF ---------------
16:45:13.631 err MongoError: pool is draining, new operations prohibited
16:45:15.632 err MongoError: pool is draining, new operations prohibited
16:45:17.632 err MongoError: pool is draining, new operations prohibited
...
16:46:11.637 err MongoError: pool is draining, new operations prohibited
16:46:13.637 err MongoError: pool is draining, new operations prohibited
16:46:15.636 err MongoError: pool is draining, new operations prohibited
16:46:17.637 err MongoError: pool is draining, new operations prohibited
--------------- WIFI SWITCH ON ---------------
16:46:18.681 collections.length 1
16:46:18.783 collections.length 1
16:46:18.784 collections.length 1
16:46:19.131 collections.length 1
16:46:19.132 collections.length 1
16:46:19.132 collections.length 1
16:46:19.451 collections.length 1
16:46:19.452 collections.length 1
16:46:19.452 collections.length 1
16:46:19.452 collections.length 1
16:46:19.452 collections.length 1
16:46:19.452 collections.length 1
16:46:19.452 collections.length 1
16:46:19.452 collections.length 1
16:46:19.453 collections.length 1
16:46:19.453 collections.length 1
16:46:19.453 collections.length 1
--------------- SETINTERVAL DOES NOT CONTINUE ---------------
```

**What is the expected behavior?**
Whenever we should have disconnection/reconnection events catched.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 13.5.0
mongoose 5.9.3
mongodb 4.0.16

**Comment by AbdelrahmanHafez** [comment]
Probably related to [this issue](https://github.com/Automattic/mongoose/issues/8604)
As specified in [this comment](https://github.com/Automattic/mongoose/issues/8604#issuecomment-592208601)

>That's what the useUnifiedTopology option does. The underlying mongodb driver no longer tracks the current state of the connection, it keeps trying to send each operation for serverSelectionTimeoutMS milliseconds.

**Comment by vkarpov15** [comment]
You're right about the issue with replica sets. We added a fix that will make mongoose emit 'disconnected' if it loses connectivity to every member of a replica set, and 'connected' when it gets one connection back.

I haven't been able to repro the behavior you mentioned for standalone servers with `useUnifiedTopology: false`, I get the below output when I shut off a standalone with `useUnifiedTopology: false`:

```
val@musashi:~/Workspace/MongoDB/troubleshoot-mongoose$ node gh-8643.js 
(node:8678) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
2020-03-15T19:45:53.794Z Mongoose event: connected 
2020-03-15T19:45:53.795Z Mongoose event: open 
2020-03-15T19:45:55.796Z collections.length 0
2020-03-15T19:45:57.794Z collections.length 0
2020-03-15T19:45:59.768Z Mongoose event: disconnected 
2020-03-15T19:46:08.801Z Mongoose event: connected 
2020-03-15T19:46:08.802Z Mongoose event: reconnected 
2020-03-15T19:46:08.806Z collections.length 0
2020-03-15T19:46:08.810Z collections.length 0
2020-03-15T19:46:08.810Z collections.length 0
2020-03-15T19:46:08.813Z collections.length 0
2020-03-15T19:46:08.814Z collections.length 0
2020-03-15T19:46:09.797Z collections.length 0
2020-03-15T19:46:11.800Z collections.length 0
2020-03-15T19:46:13.800Z collections.length 0
2020-03-15T19:46:15.803Z collections.length 0
```

**Comment by tibeoh** [comment]
> I haven't been able to repro the behavior you mentioned for standalone servers with `useUnifiedTopology: false`

Did you closed the mongod process or shut down the connectivity between mongod and node process?

Because I agree with you when you shut down mongod, events are catched. My issue were only when I turned off wifi.

**Comment by vkarpov15** [comment]
So when I turn off wifi when connecting to a standalone and `useUnifiedTopology: false`, here's what I get:

```
$ node gh-8643.js 
(node:31353) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
2020-03-30T15:37:49.426Z Mongoose event: connected 
2020-03-30T15:37:49.426Z Mongoose event: open 
2020-03-30T15:37:49.883Z collections.length 4
2020-03-30T15:37:51.878Z collections.length 4
2020-03-30T15:37:53.969Z collections.length 4
2020-03-30T15:38:04.422Z Mongoose event: timeout 
2020-03-30T15:38:24.129Z collections.length 4
2020-03-30T15:38:24.439Z collections.length 4
2020-03-30T15:38:24.440Z collections.length 4
2020-03-30T15:38:24.749Z collections.length 4
2020-03-30T15:38:24.751Z collections.length 4
2020-03-30T15:38:25.051Z collections.length 4
2020-03-30T15:38:25.055Z collections.length 4
2020-03-30T15:38:25.057Z collections.length 4
2020-03-30T15:38:25.058Z collections.length 4
2020-03-30T15:38:25.356Z collections.length 4
2020-03-30T15:38:25.358Z collections.length 4
2020-03-30T15:38:25.359Z collections.length 4
2020-03-30T15:38:25.360Z collections.length 4
2020-03-30T15:38:25.361Z collections.length 4
2020-03-30T15:38:25.362Z collections.length 4
2020-03-30T15:38:25.885Z collections.length 4
2020-03-30T15:38:27.887Z collections.length 4
```

Looks like with `useUnifiedTopology: false`, the MongoDB driver emits a 'timeout' event, which Mongoose then bubbles up.

```javascript
// Notice I added 'timeout' to the list
['connecting', 'connected', 'open', 'disconnecting', 'disconnected', 'close', 'reconnected', 'error', 'fullsetup', 'timeout'].forEach(name => {
  mongoose.connection.on(name, err => {
    console.log(new Date().toISOString(), `Mongoose event: ${name} ${err || ''}`);
  });
});
```

Unfortunately this is a limitation in the MongoDB driver, and one of the reasons for `useUnifiedTopology`. With a `timeout` event, Mongoose doesn't have a good way of telling whether it was just a long running operation or it actually lost connectivity to the server. And the MongoDB driver doesn't have a good way that I can find to determine when it regains connectivity after a timeout.

Is there anything blocking you from using `useUnifiedTopology`? `useUnifiedTopology: false` is going away in 6.0 anyway.

**Comment by tibeoh** [comment]
> Is there anything blocking you from using `useUnifiedTopology`? `useUnifiedTopology: false` is going away in 6.0 anyway.

@vkarpov15 Everything sounds good when I use `useUnifiedTopology:true` parameter! Thank you!
