### ISSUE TITLE
CoreMongooseArray throw exception when trying to push a new string

### ISSUE THREAD

**Issue by tomerb15** [Automattic/mongoose#8655]
USING version 5.9.4

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
I tried to use the native javascript Array.push on a CoreMongooseArray and received an exception

**If the current behavior is a bug, please provide the steps to reproduce.**

1. have a CoreMongooseArray of strings.
2. `var cloned = aCoreMongooseArrayOfStrings.slice()`
3. `cloned.push("2222");`
4. exception:
```
TypeError: Cannot read property '$set' of undefined
    at CoreMongooseArray._registerAtomic (/opt/nodejs/node_modules/mongoose/lib/types/core_array.js:341:34)
    at CoreMongooseArray.push (/opt/nodejs/node_modules/mongoose/lib/types/core_array.js:693:10)
```

**What is the expected behavior?**
That the push will work without exception

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 10.14.2
mongo 4.0.12
mongoose 5.9.4

**Comment by lineus** [comment]
repro script: 

### 8655.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '8655';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };

const schema = new Schema({
  names: [String]
});

const Test = mongoose.model('test', schema);

const test = new Test({ names: ['test1', 'test2', 'test3'] });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  const evens = doc.names.slice(1, 2);
  evens.push('test4');
  assert.ok(evens.includes('test2') && evens.includes('test4'));
  await connection.close();
}

run().catch(console.error);
```

### Output:
```
➜  issues ./8655.js 
TypeError: Cannot read property '$set' of undefined
    at CoreMongooseArray._registerAtomic (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/types/core_array.js:341:34)
    at CoreMongooseArray.push (/Users/lineus/dev/node/mongoose/node_modules/mongoose/lib/types/core_array.js:693:10)
    at run (/Users/lineus/dev/node/mongoose/issues/8655.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
^C
➜  issues 
```

**Comment by AbdelrahmanHafez** [comment]
I changed the reproduction script a little bit so it doesn't use a connection
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('./');
const { Schema} = mongoose;

const schema = new Schema({ names: [String]});
const Test = mongoose.model('test', schema);

const test = new Test({ names: ['test1', 'test2', 'test3'] });

const evens = test.names.slice(1, 2);
evens.push('test4');
assert.ok(evens.includes('test2') && evens.includes('test4'));
```
