### ISSUE TITLE
MongooseError [ObjectParameterError]: Parameter "obj" to Document() must be an object, got 

### ISSUE THREAD

**Issue by webenot** [Automattic/mongoose#8669]
When trying to find document by query:

`SomeModel.find({
  field: {
    $nin: ['']
  }
})`

we get error:

` error: MongooseError [ObjectParameterError]: Parameter "obj" to Document() must be an object, got
      at new ObjectParameterError (node_modules\mongoose\lib\error\objectParameter.js:25:11)
      at EmbeddedDocument.Document (node_modules\mongoose\lib\document.js:88:11)
      at EmbeddedDocument [as constructor] (mongoose\lib\types\embedded.js:42:12)
      at new EmbeddedDocument (mongoose\lib\schema\documentarray.js:115:17)
      at DocumentArrayPath.SchemaArray.castForQuery (node_modules\mongoose\lib\schema\array.js:470:13)
      at node_modules\mongoose\lib\schematype.js:1363:18
      at Array.map (<anonymous>)
      at DocumentArrayPath.handle$in (node_modules\mongoose\lib\schematype.js:1359:14)
      at DocumentArrayPath.SchemaArray.castForQuery (node_modules\mongoose\lib\schema\array.js:421:19)
      at DocumentArrayPath.SchemaType.castForQueryWrapper (node_modules\mongoose\lib\schematype.js:1388
:17)
      at cast (node_modules\mongoose\lib\cast.js:296:39)
      at model.Query.Query.cast (node_modules\mongoose\lib\query.js:4685:12)
      at model.Query.Query._castConditions (node_modules\mongoose\lib\query.js:1862:10)
      at model.Query.<anonymous> (node_modules\mongoose\lib\query.js:1889:8)
      at model.Query._wrappedThunk [as _find] (node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:
8)
      at node_modules\kareem\index.js:369:33 {
    message: 'Parameter "obj" to Document() must be an object, got ',
    name: 'ObjectParameterError'`

Mongoose 5.9.4
MongoDB 4.2.1
NodeJS 12.14.0

**Comment by AbdelrahmanHafez** [comment]
Could you provide a reproduction script? Something like the one in https://github.com/Automattic/mongoose/issues/8371#issuecomment-565731275

Also, possibly related to this issue: https://github.com/Automattic/mongoose/issues/7242

**Comment by webenot** [comment]
Sorry, my mistake, I'm trying to find the field with object data array like:
`list: [{
    name: String,
    cost: Number,
    quantity: Number
  }]`
 by string value, that is not good, I should request it like this:
`SomeModel.find({ list: { $nin: [ null, undefined, [] ] } })`

It related to this issue: #7242

Thank you. I close this issue

**Comment by C0braD3v** [comment]
Seems im getting this error too. I have this in my schema:

```js
        tickets: [{
            _id: String,
            userID: String
        }],
        ticketUsers: [{
            _id: String,
            ticketCount: Number
        }]
```

And when creating a new doc, i have this:
```js
                            tickets: [],
                            ticketUsers: []
```

Error im getting is:
```
(node:23908) UnhandledPromiseRejectionWarning: ValidationError: guild validation failed: ticketUsers: Parameter "obj" to Document() must be an object, got 
    at new ValidationError (C:\Users\Chris\Desktop\Site current\SeismicCore.wtf\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (C:\Users\Chris\Desktop\Site current\SeismicCore.wtf\node_modules\mongoose\lib\document.js:2461:32)
    at p.doValidate.skipSchemaValidators (C:\Users\Chris\Desktop\Site current\SeismicCore.wtf\node_modules\mongoose\lib\document.js:2310:17)
    at DocumentArrayPath.doValidate (C:\Users\Chris\Desktop\Site current\SeismicCore.wtf\node_modules\mongoose\lib\schema\documentarray.js:202:12)
    at C:\Users\Chris\Desktop\Site current\SeismicCore.wtf\node_modules\mongoose\lib\document.js:2303:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Not sure why it must be an object, when in the schema its supposed to be an array of objects.

**Comment by webenot** [comment]
Could you show a script that throws this error? May be you try to make a query like this: `SomeModel.find({ ticketUsers: '' })` ? If you want to find a document with empty array you should do something like this: `SomeModel.find({ ticketUsers: [] })`.

**Comment by vkarpov15** [comment]
@C0braD3v please open a new issue and follow the issue template.
