### ISSUE TITLE
Unable to populate array subdocument refPath for field in parent doc

### ISSUE THREAD

**Issue by chipallen2** [Automattic/mongoose#8742]
BUG

This used to work in Mongoose 4 and broke with upgrade to Mongoose 5.

I have a schema like this where refPath inside a subDoc array points to a parent field.

```
   {
        name: String,
        detailType: String, //the name of the model
        details: [
            {
                relatedTo: { type: ObjectId, refPath: 'detailType' }, //A dynamic reference to populate
                description: String
            },
        ],
    }

    this.populate('details.relatedTo')
```

The problem goes away if I move the detailType column down into the subDocument like this.

```
{
        name: String,
        details: [
            {
                relatedTo: { type: ObjectId, refPath: 'detailType' }, //A dynamic reference to populate
                description: String,
                detailType: String, //the name of the model
            },
        ],
    }
```

I'm updating my docs to look like this but it isn't ideal cause I duplicate the detailType over and over - before I only wrote it once.

This throws the following error:

```
TypeError: Cannot read property '0' of undefined
    at markArraySubdocsPopulated (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/document.js:559:48)
    at model.Document.$__init (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/document.js:519:3)
    at model.syncWrapper [as $__init] (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/kareem/index.js:234:23)
    at model.Document.init (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/document.js:485:8)
    at completeMany (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/helpers/query/completeMany.js:41:14)
    at /Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/query.js:1952:9
    at /Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4766:16
    at /Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/utils.js:276:16
    at /Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4787:21
    at next (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4237:5)
    at populate (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4346:12)
    at _populate (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4227:5)
    at utils.promiseOrCallback.cb (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4202:5)
    at Object.promiseOrCallback (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/utils.js:261:12)
    at Function.Model.populate (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4200:16)
    at cb (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/query.js:1948:17)
    at result (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/utils.js:129:55)
    at cursor.close (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/operations/to_array.js:36:13)
    at handleCallback (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/utils.js:129:55)
    at completeClose (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/cursor.js:859:16)"TypeError: Cannot read property '0' of undefined
    at markArraySubdocsPopulated (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/document.js:559:48)
    at model.Document.$__init (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/document.js:519:3)
    at model.syncWrapper [as $__init] (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/kareem/index.js:234:23)
    at model.Document.init (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/document.js:485:8)
    at completeMany (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/helpers/query/completeMany.js:41:14)
    at /Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/query.js:1952:9
    at /Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4766:16
    at /Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/utils.js:276:16
    at /Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4787:21
    at next (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4237:5)
    at populate (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4346:12)
    at _populate (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4227:5)
    at utils.promiseOrCallback.cb (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4202:5)
    at Object.promiseOrCallback (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/utils.js:261:12)
    at Function.Model.populate (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/model.js:4200:16)
    at cb (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongoose/lib/query.js:1948:17)
    at result (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/utils.js:129:55)
    at cursor.close (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/operations/to_array.js:36:13)
    at handleCallback (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/utils.js:129:55)
    at completeClose (/Users/callen/Documents/git/ViewInFocus-Server/node_modules/mongodb/lib/cursor.js:859:16)
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node 10.16.0
Mongoose 5.9.6

**Comment by chipallen2** [comment]
Seems related to this issue which is about a virtual. But same problem where the code doesn't appear to be walking up to get the parent doc field.

https://github.com/Automattic/mongoose/issues/8277

**Comment by vkarpov15** [comment]
I'm unable to repro, below script works fine on mongoose@5.9.6:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = Schema({
    name: String,
    detailType: String, //the name of the model
    details: [{
      relatedTo: { type: mongoose.ObjectId, refPath: 'detailType' },
      description: String
    }]
  });
  const Model = mongoose.model('Test', schema);

  const Child = mongoose.model('Child', Schema({ name: String }));
  const c = await Child.create({ name: 'test' });

  await Model.create({
    name: 'foo',
    detailType: 'Child',
    details: [{
      relatedTo: c,
      description: 'bar'
    }]
  });

  const doc = await Model.findOne().populate('details.relatedTo').exec();
  console.log(doc);
}
```

Output:

```
$ node gh-8742.js 
{ _id: 5e8c80c4fa493a30f464e7b2,
  name: 'foo',
  detailType: 'Child',
  details:
   [ { _id: 5e8c80c4fa493a30f464e7b3,
       relatedTo: [Object],
       description: 'bar' } ],
  __v: 0 }
^C
```

Can you please modify the above script to demonstrate your issue?

Also, can you please double-check your Mongoose version? Your stack trace says the error occurred in a line that's an empty comment in mongoose@5.9.6: https://github.com/Automattic/mongoose/blob/1883bc086d172a8c79252649c46a8b1ac168b13b/lib/document.js#L559
