### ISSUE TITLE
Warning: Accessing non-existent property in Node.js 14

### ISSUE THREAD

**Issue by kyrylkov** [Automattic/mongoose#8757]
mongoose 5.9.7 

Node.js 14.0.0-rc.1 / V8 8.1.307.20-node.11

```
(node:17316) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(node:17316) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:17316) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:17316) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
```

**Comment by kyrylkov** [comment]
Please close.  Driver issue: https://jira.mongodb.org/browse/NODE-2536


```

(node:1716) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
--
at emitCircularRequireWarning (internal/modules/cjs/loader.js:838:11)
at Object.get (internal/modules/cjs/loader.js:849:5)
at Object.<anonymous> (C:\Users\kyryl\dev\entriwise\server\node_modules\mongodb\lib\operations\db_ops.js:16:42)
at Module._compile (internal/modules/cjs/loader.js:1202:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1222:10)
at Module.load (internal/modules/cjs/loader.js:1051:32)
at Function.Module._load (internal/modules/cjs/loader.js:947:14)
at Module.require (internal/modules/cjs/loader.js:1091:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (C:\Users\kyryl\dev\entriwise\server\node_modules\mongodb\lib\operations\collection_ops.js:5:23)
(node:1716) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
at emitCircularRequireWarning (internal/modules/cjs/loader.js:838:11)
at Object.get (internal/modules/cjs/loader.js:849:5)
at Object.<anonymous> (C:\Users\kyryl\dev\entriwise\server\node_modules\mongodb\lib\operations\db_ops.js:17:44)
at Module._compile (internal/modules/cjs/loader.js:1202:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1222:10)
at Module.load (internal/modules/cjs/loader.js:1051:32)
at Function.Module._load (internal/modules/cjs/loader.js:947:14)
at Module.require (internal/modules/cjs/loader.js:1091:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (C:\Users\kyryl\dev\entriwise\server\node_modules\mongodb\lib\operations\collection_ops.js:5:23)
(node:1716) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
at emitCircularRequireWarning (internal/modules/cjs/loader.js:838:11)
at Object.get (internal/modules/cjs/loader.js:849:5)
at Object.<anonymous> (C:\Users\kyryl\dev\entriwise\server\node_modules\mongodb\lib\operations\db_ops.js:18:43)
at Module._compile (internal/modules/cjs/loader.js:1202:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1222:10)
at Module.load (internal/modules/cjs/loader.js:1051:32)
at Function.Module._load (internal/modules/cjs/loader.js:947:14)
at Module.require (internal/modules/cjs/loader.js:1091:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (C:\Users\kyryl\dev\entriwise\server\node_modules\mongodb\lib\operations\collection_ops.js:5:23)
(node:1716) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
at emitCircularRequireWarning (internal/modules/cjs/loader.js:838:11)
at Object.get (internal/modules/cjs/loader.js:849:5)
at Object.<anonymous> (C:\Users\kyryl\dev\entriwise\server\node_modules\mongodb\lib\operations\db_ops.js:19:46)
at Module._compile (internal/modules/cjs/loader.js:1202:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1222:10)
at Module.load (internal/modules/cjs/loader.js:1051:32)
at Function.Module._load (internal/modules/cjs/loader.js:947:14)
at Module.require (internal/modules/cjs/loader.js:1091:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (C:\Users\kyryl\dev\entriwise\server\node_modules\mongodb\lib\operations\collection_ops.js:5:23)
```

**Comment by kyrylkov** [comment]
Closed
