### ISSUE TITLE
validation `required` in subdocuments false positive

### ISSUE THREAD

**Issue by danielplascencia** [Automattic/mongoose#8767]
**Do you want to request a *feature* or report a *bug*?**

Report a Bug

**What is the current behavior?**

Based on the provided example script the insertion of a document containig nested maps is failling when required flag is enabled, the weirdest part is that this fails only when the subdocument contains another subdocument field which is not initialized as `new Schema` (check the line with the comment "<- this block produces the failure.").

Current output:

```
Error [ValidationError]: Main validation failed: level1.0.level2.$*.level3: Path `level3` is required., level1.1.level2.$*.level3: Path `level3` is required., level1.0.level2.0002: Validation failed: level3: Path `level3` is required., level1.1.level2.0001: Validation failed: level3: Path `level3` is required.
    at ValidationError.inspect (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/error/validation.js:61:24)
    at formatValue (internal/util/inspect.js:563:31)
    at inspect (internal/util/inspect.js:221:10)
    at formatWithOptions (internal/util/inspect.js:1693:40)
    at Object.Console.<computed> (internal/console/constructor.js:277:10)
    at Object.warn (internal/console/constructor.js:287:61)
    at /mnt/c/Users/dapr_/workspace/mongoosetest/index.js:78:11
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  errors: {
    'level1.0.level2.$*.level3': MongooseError [ValidatorError]: Path `level3` is required.
        at new ValidatorError (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/error/validator.js:29:11)
        at validate (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/schematype.js:1096:13)
        at /mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/schematype.js:1150:11
        at Array.forEach (<anonymous>)
        at Map.SchemaType.doValidate (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/schematype.js:1105:14)
        at /mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/document.js:2366:9
        at processTicksAndRejections (internal/process/task_queues.js:76:11) {
      message: 'Path `level3` is required.',
      name: 'ValidatorError',
      properties: [Object],
      kind: 'required',
      path: 'level3',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    'level1.1.level2.$*.level3': MongooseError [ValidatorError]: Path `level3` is required.
        at new ValidatorError (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/error/validator.js:29:11)
        at validate (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/schematype.js:1096:13)
        at /mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/schematype.js:1150:11
        at Array.forEach (<anonymous>)
        at Map.SchemaType.doValidate (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/schematype.js:1105:14)
        at /mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/document.js:2366:9
        at processTicksAndRejections (internal/process/task_queues.js:76:11) {
      message: 'Path `level3` is required.',
      name: 'ValidatorError',
      properties: [Object],
      kind: 'required',
      path: 'level3',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    'level1.0.level2.0002': Error [ValidationError]: Validation failed: level3: Path `level3` is required.
        at ValidationError.inspect (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/error/validation.js:61:24)
        at formatValue (internal/util/inspect.js:563:31)
        at formatProperty (internal/util/inspect.js:1406:11)
        at formatRaw (internal/util/inspect.js:785:9)
        at formatValue (internal/util/inspect.js:591:10)
        at formatProperty (internal/util/inspect.js:1406:11)
        at formatRaw (internal/util/inspect.js:785:9)
        at formatValue (internal/util/inspect.js:591:10)
        at formatValue (internal/util/inspect.js:568:18)
        at inspect (internal/util/inspect.js:221:10)
        at formatWithOptions (internal/util/inspect.js:1693:40)
        at Object.Console.<computed> (internal/console/constructor.js:277:10)
        at Object.warn (internal/console/constructor.js:287:61)
        at /mnt/c/Users/dapr_/workspace/mongoosetest/index.js:78:11
        at processTicksAndRejections (internal/process/task_queues.js:94:5) {
      errors: [Object],
      _message: 'Validation failed',
      name: 'ValidationError'
    },
    'level1.1.level2.0001': Error [ValidationError]: Validation failed: level3: Path `level3` is required.
        at ValidationError.inspect (/mnt/c/Users/dapr_/workspace/mongoosetest/node_modules/mongoose/lib/error/validation.js:61:24)
        at formatValue (internal/util/inspect.js:563:31)
        at formatProperty (internal/util/inspect.js:1406:11)
        at formatRaw (internal/util/inspect.js:785:9)
        at formatValue (internal/util/inspect.js:591:10)
        at formatProperty (internal/util/inspect.js:1406:11)
        at formatRaw (internal/util/inspect.js:785:9)
        at formatValue (internal/util/inspect.js:591:10)
        at formatValue (internal/util/inspect.js:568:18)
        at inspect (internal/util/inspect.js:221:10)
        at formatWithOptions (internal/util/inspect.js:1693:40)
        at Object.Console.<computed> (internal/console/constructor.js:277:10)
        at Object.warn (internal/console/constructor.js:287:61)
        at /mnt/c/Users/dapr_/workspace/mongoosetest/index.js:78:11
        at processTicksAndRejections (internal/process/task_queues.js:94:5) {
      errors: [Object],
      _message: 'Validation failed',
      name: 'ValidationError'
    }
  },
  _message: 'Main validation failed',
  name: 'ValidationError'
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

How to reproduce:

```js
const mongoose = require("mongoose");

const { Schema } = mongoose;

const SERVERS = "localhost:27017";
const DB_NAME = "mongoosetest";
const DATABASE_URI = `mongodb://${ SERVERS }/${ DB_NAME }`;

async function connectMongoose() {
  await mongoose.connect(DATABASE_URI);

  console.info(`Database connection established with ${ DATABASE_URI }`);

  const { connection } = mongoose;
  connection.on("error", console.warn);
  connection.on("close", connection.removeAllListeners);
}

async function main() {
  await connectMongoose();

  const SubSchema1 = new Schema({
    level2 : {
      type : Map,
      of   : new Schema({
        level3 : {
          type     : Map,
          of       : Number,
          required : true,
        },
      }),
    },
    subdocField : {  // 
      a : Boolean, // <- this block produces the failure.
    }                // 
  });

  const MainSchema = new Schema({
    level1 : {
      type     : [SubSchema1],
      required : true,
    },
  });

  const Main = mongoose.model("Main", MainSchema);

  const testRecord = new Main({
    level1 : [
      {
        level2 : {
          "0001" : {
            level3 : {
              "aaa1" : 1
            }
          }
        }
      },
      {
        level2 : {
          "0002" : {
            level3 : {
              "aaa2" : 1
            }
          }
        }
      }
    ]
  });

  console.log(JSON.stringify(testRecord.toObject({ flattenMaps : true }), null, 2));

  await testRecord.save();
  console.info("success");
}

main().then(console.info)
  .catch(err => {
    console.error(err);
    return -1;
  })
  .then(process.exit);
```

**What is the expected behavior?**

* this insertion should work without raise any error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

* Node: v12.14.1
* mongoose: v5.9.7

P.S.

As a workaround I defined `subdocField` as follows:

``` js
subdocField : new Schema({
   a : Boolean,
}, { ... }),
```

**Comment by vkarpov15** [comment]
Thanks for the detailed repro. This is an odd bug that only happens with maps that have different keys, because our logic that was running validation on document array subdocs had a bug where it would actually pull paths to validate from _all_ subdocs in the array, not just the one being validated. So the first subdoc would try to validate `level2.0002.level3.aaa2` and get a `required` error.
