### ISSUE TITLE
tests failing 2.x and master branches

### ISSUE THREAD

**Issue by timoxley** [Automattic/mongoose#879]
I'm trying to get the test suite running for #821. I'm not sure if I should be working on master or the 2.x branch, guessing 2.x since it's most recently updated?

Is there something special I need to do or should I simply ignore these?

node 0.6.16, 2.x branch:

```
npm test                                                                                                                                           !10512

> mongoose@2.6.1 test .../mongoose
> make test

The "sys" module is now called "util". It should have a similar interface.

 You're not testing replica sets! 
 Please set the MONGOOSE_SET_TEST_URI env variable. 
 e.g: `mongodb://localhost:27017/db,mongodb://localhost…` 


 You're not testing shards! 
 Please set the MONGOOSE_SHARD_TEST_URI env variable. 
 e.g: `mongodb://localhost:27017/database 
 Sharding must already be enabled on your database 

   uncaught: AssertionError: {} === null
    at .../mongoose/test/index.test.js:148:14
    at .../mongoose/lib/connection.js:191:5
    at .../mongoose/node_modules/mongodb/lib/mongodb/db.js:251:16
    at [object Object].<anonymous> (.../mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:408:7)
    at [object Object].emit (events.js:88:20)
    at [object Object].<anonymous> (.../mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:96:15)
    at [object Object].emit (events.js:70:17)
    at Socket.<anonymous> (.../mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:385:10)
    at Socket.emit (events.js:67:17)
    at Array.18 (net.js:301:14)


   uncaught: AssertionError: expected false to equal true
    at Object.equal (.../mongoose/node_modules/should/lib/should.js:306:10)
    at NativeConnection.<anonymous> (.../mongoose/test/model.test.js:4307:69)
    at NativeConnection.emit (events.js:67:17)
    at .../mongoose/lib/connection.js:184:14
    at .../mongoose/node_modules/mongodb/lib/mongodb/db.js:251:16
    at [object Object].<anonymous> (.../mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:408:7)
    at [object Object].emit (events.js:88:20)
    at [object Object].<anonymous> (.../mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:96:15)
    at [object Object].emit (events.js:70:17)
    at Socket.<anonymous> (.../mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:385:10)

^C┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Stat                  ┃ Time (ms)     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━┫
┃ Queries run           ┃ 335           ┃
┣━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━┫
┃ Time ellapsed         ┃ 170375        ┃
┣━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━┫
┃ Connections opened    ┃ 0             ┃
┣━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━┫
┃ Connections closed    ┃ 0             ┃
┗━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━┛

   collection.test.js test buffering of commands until connection is established: AssertionError: expected false to be true
    at Object.true (.../mongoose/node_modules/should/lib/should.js:262:10)
    at .../mongoose/test/collection.test.js:26:26
    at Array.0 (.../mongoose/support/expresso/bin/expresso:773:37)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:804:35)
    at EventEmitter.<anonymous> (events.js:88:20)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:869:10)
    at report (.../mongoose/support/expresso/bin/expresso:815:13)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:866:9)
    at EventEmitter.exit (node.js:350:17)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:855:17)


   index.test.js test connecting to the demo database: AssertionError: expected false to be true
    at Object.true (.../mongoose/node_modules/should/lib/should.js:262:10)
    at .../mongoose/test/index.test.js:21:26
    at Array.18 (.../mongoose/support/expresso/bin/expresso:773:37)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:804:35)
    at EventEmitter.<anonymous> (events.js:88:20)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:869:10)
    at report (.../mongoose/support/expresso/bin/expresso:815:13)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:866:9)
    at EventEmitter.exit (node.js:350:17)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:855:17)


   index.test.js test default connection: AssertionError: expected false to be true
    at Object.true (.../mongoose/node_modules/should/lib/should.js:262:10)
    at .../mongoose/test/index.test.js:37:26
    at Array.19 (.../mongoose/support/expresso/bin/expresso:773:37)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:804:35)
    at EventEmitter.<anonymous> (events.js:88:20)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:869:10)
    at report (.../mongoose/support/expresso/bin/expresso:815:13)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:866:9)
    at EventEmitter.exit (node.js:350:17)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:855:17)


   index.test.js test disconnection of all connections: AssertionError: expected 0 to equal 2
    at Object.eql (.../mongoose/node_modules/should/lib/should.js:291:10)
    at .../mongoose/test/index.test.js:104:26
    at Array.21 (.../mongoose/support/expresso/bin/expresso:773:37)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:804:35)
    at EventEmitter.<anonymous> (events.js:88:20)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:869:10)
    at report (.../mongoose/support/expresso/bin/expresso:815:13)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:866:9)
    at EventEmitter.exit (node.js:350:17)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:855:17)


   index.test.js test disconnection of all connections callback: AssertionError: expected false to be true
    at Object.true (.../mongoose/node_modules/should/lib/should.js:262:10)
    at .../mongoose/test/index.test.js:123:23
    at Array.22 (.../mongoose/support/expresso/bin/expresso:773:37)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:804:35)
    at EventEmitter.<anonymous> (events.js:88:20)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:869:10)
    at report (.../mongoose/support/expresso/bin/expresso:815:13)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:866:9)
    at EventEmitter.exit (node.js:350:17)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:855:17)


   model.ref.test.js test populating subdocuments partially with empty array: AssertionError: expected false to be true
    at Object.true (.../mongoose/node_modules/should/lib/should.js:262:10)
    at .../mongoose/test/model.ref.test.js:999:23
    at Array.23 (.../mongoose/support/expresso/bin/expresso:773:37)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:804:35)
    at EventEmitter.<anonymous> (events.js:88:20)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:869:10)
    at report (.../mongoose/support/expresso/bin/expresso:815:13)
    at EventEmitter.emit (.../mongoose/support/expresso/bin/expresso:866:9)
    at EventEmitter.exit (node.js:350:17)
    at EventEmitter.<anonymous> (.../mongoose/support/expresso/bin/expresso:855:17)


   Failures: 8


make: *** [test] Error 8
```

**Comment by QuotableWater7** [comment]
@timoxley this issue is actually what saved me
