### ISSUE TITLE
Error: Cannot find module 'mongodb' when using v5.9.9

### ISSUE THREAD

**Issue by rvillane** [Automattic/mongoose#8801]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I started using mongoose v5.9.9 and then I get the following error when the app is loading:

```
Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/dist/node_modules/mongoose/lib/drivers/node-mongodb-native/binary.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/dist/node_modules/mongoose/lib/drivers/node-mongodb-native/index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/dist/node_modules/mongoose/lib/index.js:15:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```
**What is the expected behavior?**
I was expecting the app to load without having this error, as a workaround, I just downgraded to mongoose v5.9.7 and the app is loading fine now

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: v5.9.9
node: v10.17.0
mongoDB: v3.6.9

**Comment by rvillane** [comment]
@AbdelrahmanHafez what exactly is needed in this case ?

**Comment by AbdelrahmanHafez** [comment]
Can you provide a minimal script that reproduces the issue?
It's difficult to help without being able to reproduce the issue.

For example, can you modify the script below to reproduce the issue?
```js
// 8801
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String }
  });

  const User = mongoose.model('User', userSchema);

  const user = await User.create({ name: 'Hafez' });
  assert.equal(mongoose.version, '5.9.9');
  assert.equal(user.name, 'Hafez');
  console.log('Done.');
}
```

**Comment by vkarpov15** [comment]
Can you please try doing `rm -rf node_modules && npm install`? If that doesn't work, try `rm ./package-lock.json && rm -rf node_modules && npm install`. This issue is indicative of something wrong with `npm install`, because mongodb is a dependency of mongoose.

**Comment by rvillane** [comment]
using mongoose 5.9.10 fixes the problem
