### ISSUE TITLE
[Bug] reserved schema keys don't throw when type is nested object

### ISSUE THREAD

**Issue by valiant1x** [Automattic/mongoose#8869]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

Passing the Schema constructor an object with the key `errors` causes a very obscure, non-obvious error to be thrown only once an associated Document is `save()`d or `create()`d, producing an error about priorDoc being undefined:

```
(node:6930) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'priorDoc' of undefined
    at /home/node/qproxy-api/node_modules/mongoose/lib/document.js:1118:27
    at model.$set (/home/node/qproxy-api/node_modules/mongoose/lib/document.js:1125:5)
    at model.set [as errors] (/home/node/qproxy-api/node_modules/mongoose/lib/helpers/document/compile.js:137:20)
    at model.Document (/home/node/qproxy-api/node_modules/mongoose/lib/document.js:85:15)
    at model.Model (/home/node/qproxy-api/node_modules/mongoose/lib/model.js:105:12)
    at new model (/home/node/qproxy-api/node_modules/mongoose/lib/model.js:4669:15)
    at /home/node/qproxy-api/node_modules/mongoose/lib/model.js:3106:22
    at /home/node/qproxy-api/node_modules/mongoose/lib/model.js:3142:7
    at Array.forEach (<anonymous>)
    at /home/node/qproxy-api/node_modules/mongoose/lib/model.js:3141:15
    at /home/node/qproxy-api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/node/qproxy-api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/node/qproxy-api/node_modules/mongoose/lib/model.js:3076:10)
    at Object.<anonymous> (/home/node/qproxy-api/test.js:11:7)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
(node:6930) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6930) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const Phone = new Schema({
  name: String,
  errors: {
      numErrors: Number,
      lastError: Date
   }
}, {timestamps: true});
var Phone = mongoose.model('Phone', Phone);
Phone.create({ name: 'test' });
```

**What is the expected behavior?**

Ideally, the user should see an error indicating that a restricted keyword was used, or indicate some issue in the Schema constructor. It was very hard to track down the underlying issue in the current format. Searching docs and even google for `priorDoc` undefined yields nothing useful. After scouring the docs I noticed `prototype.errors` being some sort of reserved keyword.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose 5.9.10
NodeJS 12.16.1
MongoDB 4.2.6

**Comment by AbdelrahmanHafez** [comment]
`errors` is a [reserved keyword](https://mongoosejs.com/docs/api/schema.html#schema_Schema.reserved), you're right, the error should be thrown. on compiling the schema, I just tested, and it works with flat types, but not with nested objects.

```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('assert');

assert.throws(
  buildInvalidSchema,
  { name: 'Error', message: /`errors` may not be used as a schema pathname/ }
);

function buildInvalidSchema() {
  new Schema({
    errors: {
      nested: String
    }
  });
}
```

@vkarpov15 can we change the issue title to `[Bug] reserved schema keys don't throw when type is nested object`?
