### ISSUE TITLE
Virtual population with discriminator: TypeError: Cannot read property 'options' of null 

### ISSUE THREAD

**Issue by andreialecu** [Automattic/mongoose#8924]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

See the repro below, here's the error:

```
/home/aandrei/mongoosebug/node_modules/mongoose/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: Cannot read property 'options' of null
    at getModelsMapForPopulate (/home/aandrei/mongoosebug/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:280:34)
    at populate (/home/aandrei/mongoosebug/node_modules/mongoose/lib/model.js:4313:21)
    at _populate (/home/aandrei/mongoosebug/node_modules/mongoose/lib/model.js:4283:5)
    at /home/aandrei/mongoosebug/node_modules/mongoose/lib/model.js:4258:5
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
"use strict";
const mongoose = require("mongoose");
const { Schema } = mongoose;
const assert = require("assert");

mongoose.set("debug", true);

run()
  .then(process.exit)
  .catch(console.error);

async function run() {
  await mongoose.connect(
    "mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=rs",
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    },
  );

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({ name: { type: String } });

  const User = mongoose.model("User", userSchema);

  const postSchema = new Schema({
    title: String,
    userId: { type: Schema.ObjectId },
  });
  postSchema.virtual("user", {
    ref: "User",
    localField: "userId",
    foreignField: "_id",
    justOne: true,
  });

  const Post = mongoose.model("Post", postSchema);

  const otherUserSchema = new mongoose.Schema({
    postId: { type: Schema.ObjectId },
  });
  otherUserSchema.virtual("post", {
    ref: "Post",
    localField: "postId",
    foreignField: "_id",
    justOne: true,
  });

  const OtherUser = User.discriminator("OtherUser", otherUserSchema);

  await User.init();

  const user = await User.create({ name: "User" });
  const post = await Post.create({ title: "JS 2020", userId: user._id });

  const user2 = await OtherUser.create({
    name: "Other User",
    postId: post._id,
  });

  const results = await User.find().populate({
    path: "post",
    populate: {
      path: "user",
    },
  });

  console.log(
    JSON.stringify(
      results.map(res => res.toJSON({ virtuals: true })),
      null,
      2,
    ),
  );
}
```

**What is the expected behavior?**

I'm not sure if there is any reason this wouldn't be supported.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node 13.7.0
mongoose 5.9.10

**Comment by andreialecu** [comment]
Note that replacing:

```
  const results = await User.find().populate({
```

with 

```
  const results = await OtherUser.find().populate({
```

Results in the code running properly.

However, since `OtherUser` is just a variant of `User`, I would expect this to work from `User` as well.

**Comment by AbdelrahmanHafez** [comment]
I agree, it would be neat if mongoose could just infer that this virtual belongs to that child discriminator.

But what if the parent model has two child discriminators, where both have a virtual `post`? Which one should it work with? I actually have been facing a similar situation lately, opened up https://github.com/Automattic/mongoose/issues/8881, but there are too many scenarios that would just be impossible for mongoose to decide what to do.

Meanwhile, I put in a PR with a fix that will just silently ignore the populate on `post` since it doesn't exist directly on `User`.

**Comment by andreialecu** [comment]
@AbdelrahmanHafez if you modify the test to the following, to remove the virtual and instead define the `ref` as part of the schema directly, it will run correctly:

```js
"use strict";
const mongoose = require("mongoose");
const { Schema } = mongoose;
const assert = require("assert");

mongoose.set("debug", true);

run()
  .then(process.exit)
  .catch(console.error);

async function run() {
  await mongoose.connect(
    "mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=rs",
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    },
  );

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({ name: { type: String } });

  const User = mongoose.model("User", userSchema);

  const postSchema = new Schema({
    title: String,
    userId: { type: Schema.ObjectId, ref: "User" },
  });

  const Post = mongoose.model("Post", postSchema);

  const otherUserSchema = new mongoose.Schema({
    postId: { type: Schema.ObjectId, ref: "Post" },
  });

  const OtherUser = User.discriminator("OtherUser", otherUserSchema);

  await User.init();

  const user = await User.create({ name: "User" });
  const post = await Post.create({ title: "JS 2020", userId: user._id });

  const user2 = await OtherUser.create({
    name: "Other User",
    postId: post._id,
  });

  const results = await User.find().populate({
    path: "postId",
    populate: {
      path: "userId",
    },
  });

  console.log(
    JSON.stringify(
      results.map(res => res.toJSON({ virtuals: true })),
      null,
      2,
    ),
  );
}
```

So I think mongoose does indeed do some magic to decide what to do about discriminators.

**Comment by andreialecu** [comment]
Does the PR fix it though? it just prevents the error, but doesn't fix the usage.
