### ISSUE TITLE
Issue in mongoose connect 

### ISSUE THREAD

**Issue by sandeepkj90** [Automattic/mongoose#8935]
/Volumes/Macintosh HD/XD/article_api/node_modules/mongoose-legacy-pluralize/index.js:85
  str = str.toLowerCase();
            ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at pluralize (/Volumes/Macintosh HD/XD/article_api/node_modules/mongoose-legacy-pluralize/index.js:85:13)
    at Object.exports.toCollectionName (/Volumes/Macintosh HD/XD/article_api/node_modules/mongoose/lib/utils.js:44:12)
    at Mongoose.model (/Volumes/Macintosh HD/XD/article_api/node_modules/mongoose/lib/index.js:552:13)
    at Object.<anonymous> (/Volumes/Macintosh HD/XD/article_api/src/model/article-schema.js:25:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Volumes/Macintosh HD/XD/article_api/src/dao/article-dao.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Volumes/Macintosh HD/XD/article_api/src/service/article-service.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by sandeepkj90** [comment]
no reason

**Comment by Phalguna2125** [comment]
Hi Sandeep, whats the resolution for this?
