### ISSUE TITLE
[BUG] Cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by alexcaglairi** [Automattic/mongoose#8948]
Hi all,

i', using latest Mongoose (5.9.12) with nodeJs 13.3.0 runnung on Ubuntu 18 on an AWS EC2 vps.
I'm running a simple: 
`model.find({ownerId:'xx'}).where(filters)`
where "filters" is a filter object.

Suddendly, generally after a lot of positive queries, i get this exception:

```
TypeError: Cannot read property 'hasOwnProperty' of null
0|CDS  |     at cast (/var/www/html/customerdata-service/node_modules/mongoose/lib/cast.js:36:11)
0|CDS  |     at cast (/var/www/html/customerdata-service/node_modules/mongoose/lib/cast.js:60:18)
0|CDS  |     at cast (/var/www/html/customerdata-service/node_modules/mongoose/lib/cast.js:60:18)
0|CDS  |     at model.Query.Query.cast (/var/www/html/customerdata-service/node_modules/mongoose/lib/query.js:4718:12)
0|CDS  |     at model.Query.<anonymous> (/var/www/html/customerdata-service/node_modules/mongoose/lib/query.js:2256:10)
0|CDS  |     at model.Query._wrappedThunk [as _countDocuments] (/var/www/html/customerdata-service/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
0|CDS  |     at /var/www/html/customerdata-service/node_modules/kareem/index.js:369:33
0|CDS  |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
What it can be? Is it a common bug?

In "cast.js" file at row 36 i have this if statement:

```
// bson 1.x has the unfortunate tendency to remove filters that have a top-level
  // `_bsontype` property. But we should still allow ObjectIds because
  // `Collection#find()` has a special case to support `find(objectid)`.
  // Should remove this when we upgrade to bson 4.x. See gh-8222, gh-8268
  if (obj.hasOwnProperty('_bsontype') && obj._bsontype !== 'ObjectID') {
    delete obj._bsontype;
  }
```

**Comment by jvdsande** [comment]
@alexcaglairi ,

This recently happened to me. Make sure that, if your `filters` object contains any `$and` clauses or similar, none of the entries of those arrays is either `null` or `undefined`.

**Comment by vkarpov15** [comment]
Thanks for the guidance @jvdsande , we added a check for this in f1e4201 so passing `null` to `$and` will result in a `CastError`.

@alexcaglairi I think this is the cause of your issue, your stack trace points to some logic that handles `$and` and `$or`.
