### ISSUE TITLE
Mongo/Mongoose slows down randomly and then crashes.

### ISSUE THREAD

**Issue by harshmandan** [Automattic/mongoose#8950]
I use PM2 to manage my Node instance on a VPS.

From past 7 days I'm experiencing a weird crashing behavior on my server.

The server randomly maxes out its CPU, IO to the point where I can't even SSH in the server.

I'm using mongoose version `"mongoose": "^5.9.7"`
I'm on mongod version ` 4.2.6`.

Here are some logs I'm getting:
This is my Digital Ocean graph, look how it jumps at 7:45AM even when there is no traffic at all:
![graph](https://i.ibb.co/dPdKg7v/graph.png)

During this time I can't even SSH in. So I manually power it off from DO dashboard and power it on again to log in. These are my error logs from PM2:
```
2020-05-08 07:55 AM: (node:12776) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connection timed out
2020-05-08 07:55 AM:     at new MongooseServerSelectionError (/home/live/node_modules/mongoose/lib/error/serverSelection.js:24:11)
2020-05-08 07:55 AM:     at Function.Model.$wrapCallback (/home/live/node_modules/mongoose/lib/model.js:4901:32)
2020-05-08 07:55 AM:     at promiseOrCallback (/home/live/node_modules/mongoose/lib/query.js:4353:21)
2020-05-08 07:55 AM:     at Promise (/home/live/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
2020-05-08 07:55 AM:     at new Promise (<anonymous>)
2020-05-08 07:55 AM:     at promiseOrCallback (/home/live/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
2020-05-08 07:55 AM:     at model.Query.exec (/home/live/node_modules/mongoose/lib/query.js:4352:10)
2020-05-08 07:55 AM:     at model.Query.Query.then (/home/live/node_modules/mongoose/lib/query.js:4433:15)
2020-05-08 07:55 AM:     at process._tickCallback (internal/process/next_tick.js:68:7)
```
And the same error is now logged repeatedly till 8:01 AM hundreds of times.
At 8:01 AM:

```
Killed
2020-05-08 08:02 AM: npm
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: ERR!
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: code ELIFECYCLE
2020-05-08 08:02 AM: ERR!
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: errno
2020-05-08 08:02 AM:  137
2020-05-08 08:02 AM: npm
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: ERR!
2020-05-08 08:02 AM:  LIVE@1.0.0 start: `node index.js`
2020-05-08 08:02 AM: npm
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: ERR!
2020-05-08 08:02 AM:  Exit status 137
2020-05-08 08:02 AM: npm
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: ERR!
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: npm
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: ERR!
2020-05-08 08:02 AM:  Failed at the LIVE@1.0.0 start script.
2020-05-08 08:02 AM: npm
2020-05-08 08:02 AM:
2020-05-08 08:02 AM: ERR!
2020-05-08 08:02 AM:  This is probably not a problem with npm. There is likely additional logging output above.
```

At this point I also restarted the server manually.

I am completely clueless so I also took a look at my normal logs to see if any specific requests were causing this behavior. Up until 7:30AM all the requests were being processed normally.
But after 7:30AM, the response time for all the requests went staggeringly high:
```
2020-05-08 07:33 AM: POST /auth2/login 401 98.529 ms
2020-05-08 07:33 AM: POST /auth2/login 200 106.372 ms
2020-05-08 07:36 AM: POST /auth2/login 200 100.910 ms
2020-05-08 07:43 AM: POST /batches_alt/s 200 133.028 ms
2020-05-08 07:43 AM: GET /lc_alt 200 135.952 ms
2020-05-08 07:43 AM: GET /store_alt/list 200 113.665 ms
2020-05-08 07:43 AM: GET /lc_alt 200 101.191 ms
2020-05-08 07:43 AM: POST /auth2/reset-password - - ms
2020-05-08 07:43 AM: POST /batches_alt/s 200 667.088 ms
2020-05-08 07:44 AM: GET /att/batches 200 196.614 ms
2020-05-08 07:44 AM: GET /user_alt/profile 200 361.384 ms
2020-05-08 07:44 AM: GET /fees_alt/payments 200 144.341 ms
2020-05-08 07:44 AM: GET /user_alt/profile 200 337.401 ms
2020-05-08 07:44 AM: POST /auth2/login 200 539.502 ms
2020-05-08 07:44 AM: GET /notifications 200 91.560 ms
2020-05-08 07:44 AM: POST /user/update 200 106.472 ms
2020-05-08 07:44 AM: GET /user/profile 200 94.922 ms
2020-05-08 07:44 AM: POST /material_alt 200 151.331 ms
2020-05-08 07:44 AM: POST /auth2/login 200 344.296 ms
2020-05-08 07:44 AM: GET /user/profile 200 248.179 ms
2020-05-08 07:44 AM: GET /user/profile 200 242.584 ms
2020-05-08 07:44 AM: GET /user/profile 200 210.989 ms
2020-05-08 07:44 AM: GET /user_alt/home 200 1985.627 ms
2020-05-08 07:44 AM: GET /user_alt/home 200 1912.284 ms
2020-05-08 07:44 AM: GET /user_alt/home 200 2050.428 ms
2020-05-08 07:44 AM: POST /batches_alt/s 200 991.414 ms
2020-05-08 07:44 AM: POST /material_alt 200 367.037 ms
2020-05-08 07:44 AM: GET /store_alt/list 200 343.228 ms
2020-05-08 07:44 AM: POST /material_alt 200 176.758 ms
2020-05-08 07:44 AM: GET /notifications 200 441.276 ms
2020-05-08 07:45 AM: POST /batches_alt/s - - ms
2020-05-08 07:45 AM: []
2020-05-08 07:45 AM: GET /user_alt/onboarding 200 5951.309 ms
2020-05-08 07:45 AM: POST /material_alt 200 2823.745 ms
2020-05-08 07:45 AM: POST /auth2/login 200 4903.762 ms
2020-05-08 07:45 AM: GET /lc_alt 200 4789.527 ms
2020-05-08 07:45 AM: POST /submit-test 200 209.598 ms
2020-05-08 07:45 AM: POST /batches_alt/s 200 1934.353 ms
2020-05-08 07:45 AM: GET /user_alt/apps 200 3.689 ms
2020-05-08 07:48 AM: GET / 200 889.265 ms
2020-05-08 07:48 AM: GET /user_alt/home 200 38041.102 ms
2020-05-08 07:48 AM: GET /user_alt/home 200 31704.876 ms
2020-05-08 07:48 AM: GET / 200 597.379 ms
2020-05-08 07:48 AM: GET /user_alt/profile 200 1655.146 ms
2020-05-08 07:48 AM: GET / 200 937.056 ms
2020-05-08 07:48 AM: GET / 200 7.145 ms
2020-05-08 07:48 AM: GET / 200 111.831 ms
2020-05-08 07:48 AM: GET /user_alt/apps 200 0.863 ms
2020-05-08 07:48 AM: GET / 200 494.499 ms
2020-05-08 07:48 AM: POST /user_alt/update 200 5227.993 ms
2020-05-08 07:48 AM: GET /user_alt/profile 200 7420.828 ms
2020-05-08 07:48 AM: GET /user_alt/home 200 20014.286 ms
2020-05-08 07:48 AM: GET / 200 38.214 ms
2020-05-08 07:49 AM: GET /user_alt/home 200 23530.113 ms
```

Solutions I've tried using:
Updating the MongoDB server.
Updating Mongoose.
Setting `useNewUrlParser:false`

I'm very clueless about everything. I don't have any idea why this keeps happening. Can anyone help?

**Comment by harshmandan** [comment]
Update: I've installed and configured `atop` as to isolate the issue if it is caused by something else.

**Comment by harshmandan** [comment]
Here's an atop file from 12:00AM to 11:00AM. Its night time when I expect least traffic if not at all.
You can take a look at it:
[Download](https://www.mediafire.com/file/qr04psrk044i5zg/atop_20200509/file)

It's in 10 seconds intervals

**Comment by harshmandan** [comment]
Here's my last 24h usage preview:
[Graphs](https://i.ibb.co/vP6bfsN/graphs.png)

**Comment by vkarpov15** [comment]
Realistically, without looking at your codebase, there isn't much we can do to debug this. My best guess is that you have an extremely slow query somewhere, that would explain the high CPU usage, high disk I/O, and 'connection timed out' error. Try setting a [global `maxTimeMS`](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-set) as suggested in [this blog post on slow queries](https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs)

```javascript
mongoose.set('maxTimeMS', 3000); // Error out if a query has been running longer than 3 sec
```
