### ISSUE TITLE
discrepancy in deprecation docs

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#8979]
https://mongoosejs.com/docs/deprecations.html says:

```
// Make Mongoose use `findOneAndUpdate()`. Note that this option is `true`
// by default, you need to set it to false.
mongoose.set('useFindAndModify', false);
```

This implies that mongoose.get('useFindAndModify') is true by default, but it 
 is undefined by default which could be misleading.

### newIssue.js
```
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const useFindAndModify = mongoose.get('useFindAndModify');
assert.strictEqual(useFindAndModify, true);
```

### output
```
issues: ./newIssue.js 
assert.js:100
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ undefined
- true
    at Object.<anonymous> (/home/lineus/old_dev/node/BE/mongoose/issues/8886_2.js:7:8)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: 'strictEqual'
}
issues: 
```

Mongoose's behavior is to treat the option as true by default

**Comment by lineus** [comment]
This actually holds true for all of the defaults for mongoose global options.

### 8979.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');

const shouldBes = {
  bufferCommands: true,
  useCreateIndex: false,
  useFindAndModify: true,
  useNewUrlParser: false,
  useUnifiedTopology: false,
  cloneSchemas: false,
  applyPluginsToDiscriminators: false,
  applyPluginsToChildSchemas: true,
  objectIdGetter: true,
  runValidators: false,
  toObject: { transform: true, flattenDecimals: true },
  toJSON: { transform: true, flattenDecimals: true },
  strict: true,
  selectPopulatedPaths: true,
  typePojoToMixed: true,
  autoIndex: true
};

Object.keys(shouldBes).map(key => {
  try {
    if (typeof shouldBes[key] === 'boolean') {
      assert.strictEqual(mongoose.get(key), shouldBes[key]);
    } else {
      assert.deepEqual(g(key), shouldBes[key]);
    }
    console.log(`${key} passed.`);
  } catch (e) {
    console.log(`${key} failed.`);
  }
});

```
### Output:
```
issues: ./8979.js 
bufferCommands failed.
useCreateIndex failed.
useFindAndModify failed.
useNewUrlParser failed.
useUnifiedTopology failed.
cloneSchemas failed.
applyPluginsToDiscriminators failed.
applyPluginsToChildSchemas failed.
objectIdGetter failed.
runValidators failed.
toObject failed.
toJSON failed.
strict failed.
selectPopulatedPaths failed.
typePojoToMixed failed.
autoIndex failed.
issues:
```

is this something that needs to be changed in code? or should we update the docs somehow?

**Comment by vkarpov15** [comment]
That's a fair point @lineus . I think we should to avoid confusion.

The reason why we did it this way is to make it easier to tell when the user explicitly set the option, because we've had a lot of headache with schema options: schema options do get default values, but we need to support falling back to connection-level and global options if the user doesn't set the schema option, and it's tricky to tell whether the user has set it or not. Hence the `Schema#_userProvidedOptions` property.

But with global options, there is no fallback. So we don't necessarily have to worry about that.
