### ISSUE TITLE
Mongoose is validating over old values

### ISSUE THREAD

**Issue by aletorrado** [Automattic/mongoose#9080]
Hi! I upgraded mongoose from 5.9.9 to 5.9.16 and I noticed that mongoose is validating documents over old setted values.

For example, I have a model with a field like this:

```
...
tags: [ { type: mongoose.Schema.Types.ObjectId, required: true, ref: 'Tag' } ],
...
```

If I do this:
```
document.tags = ["hey"];
document.tags = [];
await document.save();
```
I will get an error like this:
`Article validation failed: tags.0: Cast to ObjectId failed for value "hey" at path "tags", tags: Cast to Array failed for value "[ 'hey' ]" at path "tags"`

I don't know much about mongoose internals. What might be happening?

**Comment by AbdelrahmanHafez** [comment]
Interesting...
### 9080.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


const userSchema = new Schema({
  tags: [Schema.ObjectId]
});

const User = mongoose.model('User', userSchema);

const user = new User({ tags: ['hey'] });

user.tags = [];

const err = user.validateSync();


console.log(`Trying with mongoose v${mongoose.version}`);
assert.ifError(err);
console.log('All assertions passed.');
```

### 5.9.11 output
```
Trying with mongoose v5.9.11
All assertions passed.
```

### 5.9.12 output
```
AssertionError [ERR_ASSERTION]: ifError got unwanted exception: User validation failed: tags.0: Cast to ObjectId failed for value "hey" at path "tags", tags: Cast to Array failed for value "[ 'hey' ]" at path "tags"
    at Object.<anonymous> (mongoose\test.js:21:8)
    at new ValidationError (mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (mongoose\lib\document.js:2563:32)
    at model.$set (mongoose\lib\document.js:1238:12)
    at model._handleIndex (mongoose\lib\document.js:978:14)
    at model.$set (mongoose\lib\document.js:919:22)
    at model.Document (mongoose\lib\document.js:136:12)
    at model.Model (mongoose\lib\model.js:105:12)
    at new model (mongoose\lib\model.js:4708:15)
    at Object.<anonymous> (mongoose\test.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: [MongooseError],
  expected: null,
  operator: 'ifError'
}
```
