### ISSUE TITLE
Problem on the save hook in bi-directional Document mapping.

### ISSUE THREAD

**Issue by amolsr** [Automattic/mongoose#9082]
```
var mongoose = require("mongoose");
var Student = require('./Student');
var Schema = mongoose.Schema;

var entrySchema = new Schema({
    stdNo: {
        type: String
    },
    name: {
        type: String
    },
    branch: {
        type: String
    },
    year: {
        type: Number
    },
    location: {
        type: String
    },
    student: { type: Schema.Types.ObjectId, ref: "Student" }
}, { timestamps: true });

entrySchema.index({ createdAt: 1 }, { expireAfterSeconds: 15552000 });
entrySchema.pre('save', async function (next) {
    var entry = this;
    await Student.updateOne({
        stdNo: entry.stdNo
    }, {
        $inc: { lateCount: 1 },
        $push: { entry: entry._id }
    }).then(result => {
        if (result.nModified > 0) {
            next()
        }
    })
});
entrySchema.pre('deleteOne', { document: true, query: false }, async function (next) {
    await Student.updateOne({
        stdNo: this.stdNo
    }, {
        $inc: { lateCount: -1 }
    }).then(result => {
        if (result.nModified > 0) {
            next()
        }
    })
});

module.exports = mongoose.model("Entry", entrySchema);
```

```
var mongoose = require("mongoose");
var Entry = require('./Entry')
var Schema = mongoose.Schema;

var studentSchema = new Schema({
    name: {
        type: String
    },
    stdNo: {
        type: String
    },
    year: {
        type: Number
    },
    email: {
        type: String
    },
    mobile: {
        type: Number
    },
    branch: {
        type: String
    },
    lateCount: {
        type: Number,
        default: 0
    },
    fineCount: {
        type: Number,
        default: 0
    },
    img: {
        type: String
    },
    entry: [{ type: Schema.Types.ObjectId, ref: "Entry" }]
}, { timestamps: true });

studentSchema.index({ stdNo: 1, name: 1 });
studentSchema.pre('updateOne', async function (next) {
    var condition = this._conditions
    var query = this._update.$set
    if (!(query.name || query.stdNo || query.branch || query.year)) next();
    Entry.updateMany({ student: condition._id }, {
        $set: {
            stdNo: query.stdNo,
            branch: query.branch,
            year: query.year,
            name: query.name
        }
    }).then(result => {
        if (result.nModified > 0) {
            next()
        }
    })
});

studentSchema.pre('deleteOne', { document: true, query: false }, async function (next) {
    await Entry.deleteMany({
        stdNo: this.stdNo
    }).then(result => {
        if (result.deletedCount > 0) {
            next()
        }
    })
});

module.exports = mongoose.model("Student", studentSchema);
```

When calling save on Entry it is showing-- <br />

error 
```
TypeError: Student.updateOne is not a function
    at model.<anonymous> (F:\Projects\Late-Entry-Portal\models\Entry.js:27:19)
    at callMiddlewareFunction (F:\Projects\Late-Entry-Portal\node_modules\kareem\index.js:482:23)
    at model.next (F:\Projects\Late-Entry-Portal\node_modules\kareem\index.js:58:7)
    at _next (F:\Projects\Late-Entry-Portal\node_modules\kareem\index.js:106:10)
    at process.nextTick (F:\Projects\Late-Entry-Portal\node_modules\kareem\index.js:507:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by amolsr** [comment]
Query:-
```
Entry.create({
        stdNo: student.stdNo,
        name: student.name,
        branch: student.branch,
        year: student.year,
        location: location,
        student: student._id
    }).then(entry => {
        console.log("success")
    }).catch(err => {
        console.log(err);
    });
```

**Comment by vkarpov15** [comment]
You have a circular `require()`, student requires entry and entry requires student. See https://techsparx.com/nodejs/howto/circular-dependencies.html .

Use `mongoose.model('Student').updateOne()` instead of `Student.updateOne()` and your issue should be fixed.
