### ISSUE TITLE
model.save() is not working and is causing an error

### ISSUE THREAD

**Issue by nspeedzy** [Automattic/mongoose#9103]
**Do you want to request a *feature* or report a *bug*?**

report a *bug*

**What is the current behavior?**

The following error pops up:
```
MongooseServerSelectionError: Authentication failed.
(node:17012) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: Authentication failed.
    at NativeConnection.Connection.openUri (C:\Surya\projects\mongo_app\node_modules\mongoose\lib\connection.js:823:32)
    at Mongoose.connect (C:\Surya\projects\mongo_app\node_modules\mongoose\lib\index.js:333:15)
    at Object.<anonymous> (C:\Surya\projects\mongo_app\mongo.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Defined a simple schema
2. Created a `User` model out of it
3. executed `user.save()`

**What is the expected behavior?**

Mongoose should have saved a new record to the database.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Nodejs: 13.8.0
MongoDB: 4.2.6
Mongoose: 5.9.17

**Comment by nspeedzy** [comment]
Ok guys! Looks like i have found the error, I should have added the `authSource=admin` flag to the end of my connection string. Thanks!
