### ISSUE TITLE
Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by NishargShah** [Automattic/mongoose#9134]
**Do you want to request a *feature* or report a *bug*?**

A Bug

**What is the current behavior?**

Got an error

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a model called `cart` and `product`, now cart model has `ref` id of the product model and it works fine but when I try to select a property of `populate` it gives me an error

in select property `-<field>` works fine but I only want `title` and `image` field from a product model and that gives me an error, I used a specific selection of field in a lot of projects but in this model, I can't get specific fields. I research it but I can't find a solution of it.

**cartModel.js**
```
const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
    product: {
        type: mongoose.Schema.ObjectId,
        ref: 'Product',
        required: [true, 'Cart must belong to a product']
    }
}, {
    timestamp: true,
    versionKey: false
})

const cartSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.ObjectId,
        ref: 'User',
        unique: true,
        required: [true, 'Cart must belong to a user']
    },
    cart: [productSchema]
}, {
    versionKey: false
});

cartSchema.pre(/^find/, function (next) {
    this.populate({
        path: 'cart.product',
        select: 'image title'
    });
    next();
});

const Cart = new mongoose.model('Cart', cartSchema);

module.exports = Cart;
```

**productModel.js**

```
const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.ObjectId,
        ref: 'User',
        required: [true, 'Product must belong to a user']
    },
    title: {
        type: String,
        trim: true,
        required: [true, 'Please provide product title']
    },
    image: {
        type: String,
        trim: true,
        required: [true, 'Please provide product image']
    },
    images: [{
        type: String,
        trim: true,
        required: [true, 'Please provide atleast one product image']
    }]
}, {
    timestamps: true,
    versionKey: false
});

const Product = new mongoose.model('Product', productSchema);

module.exports = Product;
```

**What is the expected behavior?**

Got a specific selected property

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: 11.2.0
Mongoose: 5.9.14
MongoDB: 4.2.2

**Comment by vkarpov15** [comment]
What is the error message you get? And can you provide a code sample demonstrating how you're calling `Cart.find()`?

**Comment by NishargShah** [comment]
Its simple `findOne()` calling

```
exports.getCart = async (req, res, next) => {
    const cart = await Cart.findOne({user: req.user._id});
    res.status(200).json({
        status: 'success',
        cart
    });
}
```

**Comment by vkarpov15** [comment]
@NishargShah what error message do you get?

**Comment by NishargShah** [comment]
Error: `Cannot read property 'reduce' of undefined`

**Comment by vkarpov15** [comment]
Stack trace?

**Comment by NishargShah** [comment]
{ TypeError: Cannot read property 'reduce' of undefined
    at model.<anonymous> (mypathOfComputer\server\models\productModel.js:107:23)
    at VirtualType.applyGetters (mypathOfComputer\server\node_modules\mongoose\lib\virtualtype.js:142:25)
    at model.Document.get (mypathOfComputer\server\node_modules\mongoose\lib\document.js:1527:19)
    at applyVirtuals (mypathOfComputer\server\node_modules\mongoose\lib\document.js:3294:20)
    at model.Document.$toObject (mypathOfComputer\server\node_modules\mongoose\lib\document.js:3032:5)
    at model.Document.toObject (mypathOfComputer\server\node_modules\mongoose\lib\document.js:3217:15)
    at clone (mypathOfComputer\server\node_modules\mongoose\lib\helpers\clone.js:47:16)
    at cloneObject (mypathOfComputer\server\node_modules\mongoose\lib\helpers\clone.js:114:17)
    at clone (mypathOfComputer\server\node_modules\mongoose\lib\helpers\clone.js:53:16)
    at EmbeddedDocument.Document.$toObject (mypathOfComputer\server\node_modules\mongoose\lib\document.js:30
21:13)
    at EmbeddedDocument.Document.toObject (mypathOfComputer\server\node_modules\mongoose\lib\document.js:321
7:15)
    at clone (mypathOfComputer\server\node_modules\mongoose\lib\helpers\clone.js:47:16)
    at cloneArray (mypathOfComputer\server\node_modules\mongoose\lib\helpers\clone.js:133:14)
    at clone (mypathOfComputer\server\node_modules\mongoose\lib\helpers\clone.js:35:12)
    at cloneObject (mypathOfComputer\server\node_modules\mongoose\lib\helpers\clone.js:114:17)
    at clone (mypathOfComputer\server\node_modules\mongoose\lib\helpers\clone.js:53:16) statusCode: 500, sta
tus: 'ERROR' }

**Comment by NishargShah** [comment]
Solved, I am using one controller to show the only error message and status code, So I never look it in error trace.

The problem is in my code at line `productModel.js:107:23`.

Thanks.
