### ISSUE TITLE
Error: cyclic dependency detected

### ISSUE THREAD

**Issue by ObertoIsOBS** [Automattic/mongoose#9139]
Firstly here is a gist of my code.
[Epic Gist](https://gist.github.com/ObertoIsOBS/5bea72831a359eaadb19774d548443d4)

The error I am getting is one involving circular dependencies. I could not find any. The error I get from mongo is below.

```
(node:22860) UnhandledPromiseRejectionWarning: Error: Unable to save timeout to mongodb: Error: cyclic dependency detected
    at C:\Users\tgumb\Desktop\mongo setTimeout\index.js:48:24
    at C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\mongoose\lib\model.js:4887:16
    at C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\mongoose\lib\helpers\promiseOrCallback.js:16:11  
    at C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\mongoose\lib\model.js:4910:21
    at C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\mongoose\lib\model.js:495:16
    at C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\kareem\index.js:246:48
    at next (C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\kareem\index.js:167:27)
    at next (C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\kareem\index.js:169:9)
    at Kareem.execPost (C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\kareem\index.js:217:3)
    at _handleWrapError (C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\kareem\index.js:245:21)        
    at _cb (C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\kareem\index.js:304:16)
    at C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\mongoose\lib\model.js:345:9
    at C:\Users\tgumb\Desktop\mongo setTimeout\node_modules\kareem\index.js:135:16
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(node:22860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am using version 5.9.19 of mongoose. The file I am running is `test.js`, the only issue I am having is that it will not let me save anything to my model. I have seen many of this same error but they all seem to involve the serializer while mine does not. If this is not a bug I would love advice on how to fix this error.

**Comment by vkarpov15** [comment]
The issue is that you're trying so save a [Node.js Timeout class](https://nodejs.org/api/timers.html#timers_class_timeout) to MongoDB, which turns out to be a circular object:

```
$ node
Welcome to Node.js v12.13.1.
Type ".help" for more information.
> console.log(JSON.stringify(setTimeout(() => {}, 100)))
Thrown:
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
> 
```

There isn't much purpose to serializing a timeout object, because AFAIK [`clearInterval()`](https://nodejs.org/api/timers.html#timers_clearinterval_timeout) looks up the timeout by reference, so even if you were to store a Timeout object in the database, you wouldn't be able to use `clearInterval()` on it.

If you're looking to build a durable task scheduler with MongoDB, check out [agenda](http://thecodebarbarian.com/node.js-task-scheduling-with-agenda-and-mongodb.html).
