### ISSUE TITLE
Transaction to create multiple documents not working

### ISSUE THREAD

**Issue by esanchezvz** [Automattic/mongoose#9142]
### Do you want to request a feature or report a bug?
Bug

### What is the current behavior?
I want to use mongoose transactions to create multiple documents at once and if one document fails validation or throws an error, I don't want the others to save to the database.

However, whenever I pass the session to `Schema.create([], {session})` it throws the folloing error: 
```
TypeError: options.session.inTransaction is not a function
at applyWriteConcern (D:\<root-directory>\node_modules\mongodb\lib\utils.js:468:42)
at insertDocuments (D:\<root-directory>\node_modules\mongodb\lib\operations\common_functions.js:250:18)
at InsertOneOperation.execute (D:\<root-directory>\node_modules\mongodb\lib\operations\insert_one.js:26:5)
at executeOperation (D:\<root-directory>\node_modules\mongodb\lib\operations\execute_operation.js:77:17)
at Collection.insertOne (D:\<root-directory>\node_modules\mongodb\lib\collection.js:516:10)
at NativeCollection.<computed> [as insertOne] (D:\<root-directory>\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:171:28)
at model.Model.$__handleSave (D:\<root-directory>\node_modules\mongoose\lib\model.js:273:33)
at model.Model.$__save (D:\<root-directory>\node_modules\mongoose\lib\model.js:337:8)
at D:\<root-directory>\node_modules\kareem\index.js:278:20
at _next (D:\<root-directory>\node_modules\kareem\index.js:102:16)
at D:\<root-directory>\node_modules\kareem\index.js:507:38
at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
My current implementation for this is using `Promise.all()` which works fine if I don't pass the session to the Schema. I am using: 
- `typescript: ^3.8.3`
- `node: 12.6.1`
- `npm: 6.13.4`
- `mongoose: ^5.9.7`
- `mongo: 4.2.5`

This is what my current implementation looks like:
```typescript
import { startSession } from 'mongoose';

// This is inside my controller
const reqDocuments = req.body;
const session = startSession();
(await session).startTransaction();

try {
  const documents = await Promise.all(
    reqDocuments.map(async (doc) => {
      const { payload } = doc;
      return await MySchema.create(
        [
          {
            payload,
          },
        ],
        { session }
      );
    })
  );

  (await session).commitTransaction();
  (await session).endSession();

  res.status(200).json({
    success: true,
    data: documents,
  });
} catch (error) {
  (await session).abortTransaction();
  (await session).endSession();
  return next();
}
```

**Comment by esanchezvz** [comment]
I found the problem, it was not a bug but an error on my part.

To fix I replaced `const session = startSession();` for  `const session = await startSession();`
and `(await session)` for `session`
