### ISSUE TITLE
on lean queries, projecting an array with $elemMatch: { filter } should return an empty array if no items found

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9149]
Not sure if this is by design or a bug, but the following test fails, if we remove `.lean()` it works correctly. 

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({ friends: [{ name: String }] });

  const User = mongoose.model('User', userSchema);

  const createdUser = await User.create({ friends: [{ name: 'A' }, { name: 'B' }] });

  const user = await User.findOne({ _id: createdUser._id }).select({
    friends: { $elemMatch: { name: 'I do not exist' } }
  }).lean();


  assert.deepEqual(user.friends, []);

  console.log('All assertions passed.');
}
```

### Output
```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
                                                                         
undefined                                                                
                                                                         
should loosely deep-equal                                                
                                                                         
[]                                                                       
```

**Comment by vkarpov15** [comment]
This is by design. [Arrays implicitly have a default value](https://mongoosejs.com/docs/schematypes.html#arrays) of `[]`. When you use `lean()`, Mongoose doesn't apply defaults, so you don't get an empty array. If this is an issue for you, you may want to use [mongoose-lean-defaults](https://www.npmjs.com/package/mongoose-lean-defaults), or give your array a default value of undefined:

```javascript
const userSchema = new Schema({
  friends: {
    type: [{ name: String }],
    default: void 0
  }
});
```

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 I see, if you're referring to setting defaults on creation, then `friends` is already an array on the database at this point, the issue occurs only when we all of the following are true:

A) `.select(..)` with `$elemMatch`.
B) No elements in that array found matching `$elemMatch`.
C) Using lean.

mongoose-lean-defaults and mongoose-lean-virtuals didn't help either:

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

const leanVirtuals = require('mongoose-lean-virtuals');
const leanDefaults = require('mongoose-lean-defaults');

mongoose.plugin(leanVirtuals);
mongoose.plugin(leanDefaults);

run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({ friends: [{ name: String }] });

  const User = mongoose.model('User', userSchema);

  const createdUser = await User.create({ friends: [{ name: 'A' }, { name: 'B' }] });

  const user = await User.findOne({ _id: createdUser._id }).select({
    friends: { $elemMatch: { name: 'I do not exist' } }
  }).lean({ virtuals: true, defaults: true });


  assert.deepEqual(user.friends, []);

  console.log('All assertions passed.');
}
```

### Output
```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:          
                                                                                   
undefined                                                                          
                                                                                   
should loosely deep-equal                                                          
                                                                                   
[]                                                                                 
    at run (test.js:31:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {          
  generatedMessage: true,                                                          
  code: 'ERR_ASSERTION',                                                           
  actual: undefined,                                                               
  expected: [],                                                                    
  operator: 'deepEqual'                                                            
}                                                                                  
                                                                                   
```

**Comment by vkarpov15** [comment]
I put in a PR with mongoose-lean-defaults, this is an issue with how that plugin handles non-defining projections.

**Comment by AbdelrahmanHafez** [comment]
Thanks!
