### ISSUE TITLE
BUG when querying an array of sub documents with find() on model.

### ISSUE THREAD

**Issue by mouimet-infinisoft** [Automattic/mongoose#9193]
**What is the current behavior?**
When querying my model I get the following error:

> RangeError: Maximum call stack size exceeded
>     at MetadataStorage.getAncestors (C:\Projects\rqrsda-v2\src\metadata\MetadataStorage.ts:221:5)
>     at MetadataStorage.findMetadata (C:\Projects\rqrsda-v2\src\metadata\MetadataStorage.ts:191:37)
>     at MetadataStorage.findTypeMetadata (C:\Projects\rqrsda-v2\src\metadata\MetadataStorage.ts:95:21)
>     at TransformOperationExecutor.getReflectedType (C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:319:45)
>     at _loop_1 (C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:214:73)
>     at TransformOperationExecutor.transform (C:\Projects\rqrsda-v2\node_modules\class-transformer\TransformOperationExecutor.js:260:17)
>     at C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:62:40
>     at CoreDocumentArray.forEach (<anonymous>)
>     at TransformOperationExecutor.transform (C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:41:30)
>     at _loop_1 (C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:244:43)
>     at TransformOperationExecutor.transform (C:\Projects\rqrsda-v2\node_modules\class-transformer\TransformOperationExecutor.js:260:17)
>     at C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:62:40
>     at CoreDocumentArray.forEach (<anonymous>)
>     at TransformOperationExecutor.transform (C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:41:30)
>     at _loop_1 (C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:244:43)
>     at TransformOperationExecutor.transform (C:\Projects\rqrsda-v2\node_modules\class-transformer\TransformOperationExecutor.js:260:17)
>     at C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:62:40
>     at CoreDocumentArray.forEach (<anonymous>)
>     at TransformOperationExecutor.transform (C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:41:30)
>     at _loop_1 (C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:244:43)
>     at TransformOperationExecutor.transform (C:\Projects\rqrsda-v2\node_modules\class-transformer\TransformOperationExecutor.js:260:17)
>     at C:\Projects\rqrsda-v2\src\TransformOperationExecutor.ts:62:40

**If the current behavior is a bug, please provide the steps to reproduce.**
This is my CaseService querying the model.

```
export class CaseService implements ICaseService {
    private readonly caseModel: ModelType<ICase>;

    constructor() {        
        this.caseModel = getModelForClass(Case);
    }
    public findAllIncompleteCaseOpen(): any {    
        return this.caseModel.find( { parents: { $elemMatch: { isCaseOpenComplete: true } } } );
    }
}

export interface ICase extends IBaseInsideOrg {
    serviceRequestId: mongoose.Types.ObjectId;
    organizationId: mongoose.Types.ObjectId;
    state: CaseState;
    caseNumber: string;
    parents: ICaseParent[];
    children: mongoose.Types.ObjectId[];
    deliveredService: DeliveredService[];
    observationReport: ObservationReport[];
    history: HistoryEvent[];
}

export interface ICaseParent {
    parentId?: mongoose.Types.ObjectId;
    isCaseOpenComplete: boolean;
    survey?: SignedDocument;
    rules?: SignedDocument;
    agreement?: SignedDocument;
    disclosure?: SignedDocument;
}

export class Case implements ICase {      
    @prop()
    _id: mongoose.Types.ObjectId;
    @prop()
    _v: number;
    @prop()
    _t: string;
    @prop({ default: Date.now })
    createdAt: Date;
    @prop({ default: Date.now })
    updatedAt: Date;
    @prop()
    serviceRequestId: mongoose.Types.ObjectId;
    @prop()
    organizationId: mongoose.Types.ObjectId;  
    @prop({
        enum: CaseState,
        default: CaseState.opened
    })
    state: CaseState;
    @prop()
    caseNumber: string;
    @arrayProp({ items: CaseParent })
    parents: CaseParent[];
    @arrayProp({ items: mongoose.Types.ObjectId })
    children: mongoose.Types.ObjectId[];
    @arrayProp({ items: DeliveredService })
    deliveredService: DeliveredService[];
    @arrayProp({ items : ObservationReport })
    observationReport: ObservationReport[];
    @arrayProp({ items: HistoryEvent })
    history: HistoryEvent[];
}
```

**What is the expected behavior?**
Get the array of matching documents.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node = v12.18.0
Mongoose = 5.9.7
MongoDB = 4.2.0

**Sample document**

> {
>     "_id": {
>         "$oid": "5efd8d8acafbe528301abb01"
>     },
>     "state": 0,
>     "children": [{
>         "$oid": "5efd8d8acafbe528301abab1"
>     }, {
>         "$oid": "5efd8d8acafbe528301abab2"
>     }, {
>         "$oid": "5efd8d8acafbe528301abab3"
>     }],
>     "serviceRequestId": {
>         "$oid": "5efd8d8acafbe528301abad8"
>     },
>     "caseNumber": "Savings Account",
>     "organizationId": {
>         "$oid": "5efd8d8acafbe528301aba53"
>     },
>     "parents": [{
>         "isCaseOpenComplete": true
>     }, {
>       "isCaseOpenComplete": true
>     }],
>     "createdAt": {
>         "$date": "2020-07-02T07:32:27.375Z"
>     },
>     "updatedAt": {
>         "$date": "2020-07-02T07:32:27.375Z"
>     },
>     "deliveredService": [],
>     "observationReport": [],
>     "history": [],
>     "__v": 0
> }

**Comment by mouimet-infinisoft** [comment]
It was not a bug related to mongoose.
