### ISSUE TITLE
Single nested sub-document field is going wrong in a schema syntax 

### ISSUE THREAD

**Issue by lutherman** [Automattic/mongoose#9205]
Hi,

I find that the result is wrong if define a single nested sub-document field by syntax as shown below. 
1. Unknown fields are defined in the sub-document.
1. Wrong type value can be input to the field of sub-document.

Below is the test code to reproduce the problem:
```javascript
const chai = require("chai");
const expect = chai.expect;

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const testModel = mongoose.model('test', new Schema({
  singleNested: {
    type: {
      field1: Boolean,
      field2: Boolean
    },
    default: {
      field1: false,
      field2: false
    }
  },
}));

describe('test', () => {
  it('Should not define fields that not exist', () => {
    expect(testModel.schema.path('singleNested.fgfggsdfgdf')).to.undefined;
    expect(testModel.schema.path('singleNested.sfdfsfds')).to.undefined;
    expect(testModel.schema.path('singleNested.dsfsfdsf')).to.undefined;
  });
  it('Should not allow set the wrong type value', () => {
    const testDoc = new testModel();

    testDoc.singleNested.field1 = 'String value to boolean field';
    testDoc.validateSync('singleNested');

    expect(testDoc.errors['singleNested.field1']).to.be.an('Error');
  });
});
```

And the test result is:
```
$ mocha index.js


  test
    1) Should not define fields that not exist
    2) Should not allow set the wrong type value


  0 passing (30ms)
  2 failing

       Should not define fields that not exist:
     AssertionError: expected { Object (path, instance, ...) } to be undefined
      at Context.<anonymous> (index.js:24:65)
      at processImmediate (internal/timers.js:456:21)

  2) test
       Should not allow set the wrong type value:
     TypeError: Cannot read property 'singleNested.field1' of undefined
      at Context.<anonymous> (index.js:34:26)
      at processImmediate (internal/timers.js:456:21)
```

------------------------------
nodejs: 12.18.2
mongoose: 5.9.21
chai: 4.2.0
mocha: 8.0.1

**Comment by vkarpov15** [comment]
That isn't how you define a single nested subdocument. You're actually defining `singleNested` as a mixed path: https://mongoosejs.com/docs/schematypes.html#mixed

We're changing this behavior in 6.0 with #7181 because this is likely at least the 100th time someone has reported this behavior as a bug, and I agree this behavior is exceedingly confusing.

As a workaround, you can do:

```javascript
const testModel = mongoose.model('test', new Schema({
  singleNested: {
    type: new Schema({
      field1: Boolean,
      field2: Boolean
    }),
    default: {
      field1: false,
      field2: false
    }
  },
}));
```

Or, set the `typePojoToMixed` option.

```javascript
const testModel = mongoose.model('test', new Schema({
  singleNested: {
    type: {
      field1: Boolean,
      field2: Boolean
    },
    default: {
      field1: false,
      field2: false
    }
  },
}, { typePojoToMixed: false }));
```

Sorry for the inconvenience!

**Comment by lutherman** [comment]
Oh, I see. Thank you for your explanation.
