### ISSUE TITLE
MongoDB connection drops from Express app after about 30 seconds

### ISSUE THREAD

**Issue by hparicha** [Automattic/mongoose#9214]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When I run my app, it seems to get a connection - but then after about 30 seconds it gets kicked out with the error below...

**If the current behavior is a bug, please provide the steps to reproduce.**

Recently upgraded a server-side app to
node v14.4.0
MongoDB 4.2.6 Community

All recent packages
{ …
“express”: “^4.17.1”,
“mongodb”: “^3.5.9”,
“mongoose”: “^5.9.20”,
}

Simple setup:

const gooseoptions = {
  tls: true,
  tlsCAFile: '..my.crt',
  sslValidate: true,
  useNewUrlParser: true,
  useUnifiedTopology: true
};
When I run the app, it seems to get a connection - but then after about 30 seconds it gets kicked out with the error below...

$ node --trace-deprecation myapp.js
Express server listening on secure port 3000 in development mode
DB connnection successful!
/home/ec2-user/myapp/node_modules/mongodb/lib/utils.js:725
          throw error;
          ^

MongoServerSelectionError: connection <monitor> to 169.46.17.86:30911 closed
    at Timeout._onTimeout (/home/ec2-user/myapp/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(2) {
      '....mydb1' => [ServerDescription],
      '....mydb2' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}

Note: the same error is posted on ASP.net forum here on Jun 29, 2020:
https://forums.asp.net/t/2168573.aspx?node+js+db+connection

**What is the expected behavior?**
Connection doesn't get dropped(?)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v14.4.0
MongoDB 4.2.6 Community
mongoose.version 5.9.20

All recent packages
{ …
“express”: “^4.17.1”,
“mongodb”: “^3.5.9”,
“mongoose”: “^5.9.20”,
}

**Comment by hparicha** [comment]
I've tried leaving off **"useUnifiedTopology: true"** to no avail - same thing happens:
MongoServerSelectionError: connection <monitor> to <mydbip:port> closed
    at Timeout._onTimeout (/home/ec2-user/myapp/node_modules/mongodb/lib/core/sdam/topology.js:430:30)

**Comment by vkarpov15** [comment]
Just a guess, but it might be that either the MongoDB server you're connected to isn't configured to use SSL, or there's some other SSL-related issue. Can you try connecting to your MongoDB server with the mongo shell with your SSL options and verify that it works as expected?
