### ISSUE TITLE
$type not working with $ne operator

### ISSUE THREAD

**Issue by bhrigushr** [Automattic/mongoose#9216]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
CastError error is thrown
```
{ CastError: Cast to string failed for value "{ '$type': 10 }" at path "name" for model "Test"
    at model.Query.exec (/Users/bh/Documents/work/db/test-mongoose/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/bh/Documents/work/db/test-mongoose/node_modules/mongoose/lib/query.js:4443:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  messageFormat: undefined,
  stringValue: '"{ \'$type\': 10 }"',
  kind: 'string',
  value: { '$type': 10 },
  path: 'name',
  reason: null }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript

const mongoose = require('mongoose');
mongoose.set('debug', true);

const connectionString = 'mongodb://localhost:27017/test_db';
const { Schema } = mongoose;
console.log('version:: ', mongoose.version)
run()
    .then(() => console.log('done'))
    .catch(error => console.error(error))
    .finally(() => {
        process.exit(1)
    })

async function run() {
    await mongoose.connect(connectionString);
    await mongoose.connection.dropDatabase();

    const schema = new Schema(
        {
            name: {
                type: String,
                default: null
            },
            age: {
                type: Number
            }
        },
        {
            timestamps: true
        }
    )
    const M = mongoose.model('Test', schema);

    const data = [
        { name: 'test1', age: 10 },
        { name: 'test2', age: 11 },
        { age: 12 }
    ]
    await M.create(data)
    await M.find({
        name: { '$ne': { '$type': 10 } }
    })
}

```
**What is the expected behavior?**
Should not error out and return matching documents

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v10.15.3
MongoDB: v4.0.9
Mongoose: v5.9.19

**Note**:- 
If I replace `$ne `with `$not` query works fine
```javascript
  await M.find({ name: { '$not': { '$type': 10 } } }) // this  work

  await M.find({ name: { '$ne': { '$type': 10 } } }) // this don't work(throws error)
```

**Comment by vkarpov15** [comment]
This is by design, the `$ne` operator doesn't support operators. So `M.find({ name: { '$ne': { '$type': 10 } } })` will find documents whose `name` property is not equal to the object `{ $type: 10 }`  if you bypass Mongoose casting.

You should use the `$not` approach as described in this SO post: https://stackoverflow.com/questions/20744123/query-with-type-not-equal-in-mongodb
