### ISSUE TITLE
Mongoose connection timeout

### ISSUE THREAD

**Issue by SHwan93** [Automattic/mongoose#9234]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

We're working on a crawling project.
Occasionally, errors occur that are disconnected.

```
mongoose.connect(URL, {
      useNewUrlParser: true,
      useUnifiedTopology: true, // False by default. Set to true to opt in to using the MongoDB driver's new connection management engine. You should set this option to true, except for the unlikely case that it prevents you from maintaining a stable connection.
      useFindAndModify: false,
      socketTimeoutMS: 1000 * 60 * 110, // Close sockets after 110mins. of inactivity. 기본 30000ms
    });
```

I've set up a socketTimeoutMS parameter, and it's happening.
My network can't handle the load?

I wonder why.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

"mongoose": "^5.9.10",
MongoDB shell version v4.2.8

**Comment by vkarpov15** [comment]
Not enough information to provide any sort of advice. What does "errors occur that are disconnected" - can you provide error messages and stack traces?

**Comment by SHwan93** [comment]
It happens occasionally, so when it happens,
I'll give you an answer.

Thanks

**Comment by SHwan93** [comment]
connection timed out
    at _callee5$ (/home/mysterico/workspace/social-monitor-analytics/service/index.js:163:11)
    at tryCatch (/home/mysterico/workspace/social-monitor-analytics/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/mysterico/workspace/social-monitor-analytics/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as throw] (/home/mysterico/workspace/social-monitor-analytics/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/mysterico/workspace/social-monitor-analytics/service/index.js:26:103)
    at _throw (/home/mysterico/workspace/social-monitor-analytics/service/index.js:28:291)

**Comment by SHwan93** [comment]
I wonder if it is because this Error message is 'serverSelectionTimeoutMS' or 'connectionTimeoutMS' or 'socketTimeoutMS' or 'wtimeout'

**Comment by SHwan93** [comment]
MongoNetworkError: connection timed out
    at connectionFailureError (/home/mysterico/workspace/social-monitor-analytics/node_modules/mongodb/lib/core/connection/connect.js:406:14)
    at Socket.<anonymous> (/home/mysterico/workspace/social-monitor-analytics/node_modules/mongodb/lib/core/connection/connect.js:294:16)
    at Object.onceWrapper (events.js:416:28)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}

**Comment by vkarpov15** [comment]
I suspect this is due to an [OS-level timeout](https://stackoverflow.com/questions/3586760/how-do-i-set-a-timeout-for-client-http-connections-in-node-js), also see this SO: https://stackoverflow.com/questions/1045964/how-to-view-change-socket-connection-timeout-on-linux . 110 minutes is a very long `socketTimeoutMS`, if you have operations that you expect to take that long, you may need to configure your OS to support that.

Also, out of curiousity, why are you using babel/regenerator for Node.js code?

**Comment by SHwan93** [comment]
No errors are yet occurring after changing `socketTimeoutMS ` to 0

I'm using a babel to use es6 grammar and set the setting to preset.
is there a problem?

I have a question.

Is it a good way to connect passively and close the connection after processing every time do a query?

**Comment by vkarpov15** [comment]
If you're using Mongoose 5, you're already running a version of node that has native support for generators. Not really a problem, just curiosity on my part.

And closing connection after every operation is not a good idea. I don't think it would help with this issue either - usually, `socketTimeoutMS` kicks in because one single operation is running for way too long.

**Comment by sw360cab** [comment]
Sorry If I comment here, but I think is better than opening a fresh new issuse...

@vkarpov15 may this have something to do with **Debugging**?

Now when I debug my application using:
* Mongoose: 5.10.11
* Mongo: 4.4

Everytime I encounter this

    MongooseServerSelectionError: connection <monitor> to 127.0.0.1:27017 timed out

whether I wait to long, while analyzing for debugging purposes.
Is there any parameter I should change in Mongoose connection configuration respect to the past.
Never had this issue before, but now I keep on going throught that.

**Comment by vkarpov15** [comment]
@sw360cab what do you mean by "debugging"? Are you turning on Mongoose's debug mode, or are you using some sort of debugger. Probably best to open up a new issue.

**Comment by yaboylino** [comment]
Doesn anybody know what i can do about this problem:

2021-08-30T19:48:00.113Z	61802d5a-0311-4cbd-b877-30d016b90049	ERROR	MongoDB connection error: MongooseServerSelectionError: connection timed out
    at NativeConnection.Connection.openUri (/var/task/node_modules/mongoose/lib/connection.js:846:32)
    at Mongoose.createConnection (/var/task/node_modules/mongoose/lib/index.js:291:17)
    at Object.8111 (/var/task/.next/server/chunks/8111.js:21:12)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at Object.555 (/var/task/.next/server/pages/api/auth/[...nextauth].js:28:10)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/api/auth/[...nextauth].js:133:52)
    at /var/task/.next/server/pages/api/auth/[...nextauth].js:134:80
    at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:108:21)
    at /var/task/.next/server/pages/api/auth/[...nextauth].js:134:47
    at Object.<anonymous> (/var/task/.next/server/pages/api/auth/[...nextauth].js:137:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { '85.215.82.240:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
RequestId: 75404e6e-2b35-4aa4-8f1a-970e603375ab Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by sw360cab** [comment]
Hi @yaboylino.

First: IMHO I don't think commenting a closed issue is a good way to go. I would rather comment/post on smt like StackOverflow.
Anyway, are you able to post your monggose configuration? 
Then can you describe your environment? Are you using a single server config, a replicated one?
