### ISSUE TITLE
Can't customize discriminator option pluralization (can only modify toJSON, toObject, _id, id)

### ISSUE THREAD

**Issue by lulucious** [Automattic/mongoose#9238]
Hello, 

In file messageModel.js
```
`
const mongoose = require('mongoose')
const SmsSchema = new mongoose.Schema({ senderNumber: { type: String } })
const EmailSchema = new mongoose.Schema({  fromEmailAddress: {type: String} })
const messageSchema = new mongoose.Schema(
  {  method: { type: String, enum: ['email', 'sms'], required: true }  },
  { discriminatorKey: 'method' }
)

const Message = mongoose.model('Message', messageSchema)
Message.discriminator('email', EmailSchema)
Message.discriminator('sms', SmsSchema)
module.exports = Message`
```
in another file

```
const mongoose = require('mongoose')
const MessageModel = require('./MessageModel')
const schema = new mongoose.Schema({   actions: [ActionSchema] })

const ActionSchema = new mongoose.Schema({}, { discriminatorKey: 'kind', _id: false })
const actions = schema.path('actions')
actions.discriminator('message', MessageModel.schema)
module.exports = schema
```
I am encountering the following error : 
```
[worker] /node_modules/mongoose/lib/helpers/model/discriminator.js:144
[worker]           throw new Error('Can\'t customize discriminator option ' + _key +
[worker]           ^
[worker] 
[worker] Error: Can't customize discriminator option pluralization (can only modify toJSON, toObject, _id, id)
[worker]     at merge (/node_modules/mongoose/lib/helpers/model/discriminator.js:144:17)
[worker]     at discriminator (/node_modules/mongoose/lib/helpers/model/discriminator.js:167:3)
```
Any idea of what is happening or if I am missing something ? 

Thanks a lot for your help
++

---
mongoose 5.6.13,
node v12.16.1

**Comment by lulucious** [comment]
hi @vkarpov15 , how can I provide you more of that script ? Can you please guide me on what you need ? Thanks a lot

**Comment by vkarpov15** [comment]
@lulucious our general rule of thumb is that we need a standalone script, not multiple files. My best guess is that your script should be enough to repro this, just haven't had time to look at it yet.
