### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by CripBoy** [Automattic/mongoose#9274]
**Do you want to request a *feature* or report a *bug*?**
bug at connection function

**What is the current behavior?**
when i try to connect into the cluster the app returns the error bellow (i'm using a vps and my whitelist are opened for all ip's).
This error are not present on heroku host, just on vps host

**What is the expected behavior?**
connect into cluster (atlas)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
latest both

**Problem**
```
erro MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason isthat you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at NativeConnection.Connection.openUri (/root/cpanel3-skel/public_html/node_modules/mongoose/lib/connection.js:828:32)
    at Mongoose.connect (/root/cpanel3-skel/public_html/node_modules/mongoose/lib/index.js:335:15)
    at Object.<anonymous> (/root/cpanel3-skel/public_html/file.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map {
      'cluster0-shard-00-02.wzku8.mongodb.net:27017' => [ServerDescription],
      'cluster0-shard-00-01.wzku8.mongodb.net:27017' => [ServerDescription],
      'cluster0-shard-00-00.wzku8.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```
**My connection code**
```js
const mongoose = require("mongoose");
const uri = "mongodb+srv://...";

mongoose.connect(uri, {
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true
})
.then(d => console.log("good", d))
.catch(e => console.log("bad", e));

```

**Comment by CripBoy** [comment]
Solved: Disable all VPS firewall
