### ISSUE TITLE
DeprecationWarning isue

### ISSUE THREAD

**Issue by AkashPrsd** [Automattic/mongoose#9302]
i set or mention in conn line useCreateIndex: true but why i got same error now: (node:35556) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

const conn = mongoose.createConnection(url,
{ useUnifiedTopology: true, useNewUrlParser: true, useFindAndModify: false, useCreateIndex: true,},
  () => console.log("connected to db"));

mongoose.set('useCreateIndex', true);

My full code is:=>

```javascript
const express = require('express');
const bodyParser = require('body-parser');
const path = require('path');
const crypto = require('crypto');
const mongoose = require('mongoose');
const multer = require('multer');
const GridFsStorage = require('multer-gridfs-storage');
const Grid = require('gridfs-stream');
const methodOverride = require('method-override');
const config = require('./config');


const app = express();
mongoose.set('useCreateIndex', true);
mongoose.set('useFindAndModify', false);


//Middleware
app.use(bodyParser.json());
app.use(methodOverride('_method'));
app.set('view engine', 'ejs');


//Mongo URI
retryWrites=true&w=majority';
const url = config.mongoURI;

//Create mongo connection
const conn = mongoose.createConnection(url,
{ useUnifiedTopology: true, useNewUrlParser: true, useFindAndModify: false, useCreateIndex: true,},
  () => console.log("connected to db"));

//Init gfs
let gfs;

conn.once('open', () => {
//Init stream
 gfs = Grid(conn.db, mongoose.mongo);
 gfs.collection('uploads');
  })

  //create storage engine
  const storage = new GridFsStorage({
    url: config.mongoURI,
    options: { useNewUrlParser: true, useUnifiedTopology: true },

    file: (req, file) => {
      return new Promise((resolve, reject) => {
        crypto.randomBytes(16, (err, buf) => {
          if (err) {
            return reject(err);
          }
          const filename = buf.toString('hex') + path.extname(file.originalname);
          const fileInfo = {
            filename: filename,
            bucketName: 'uploads'
          };
          resolve(fileInfo);
        });
      });
    }
  });
  const upload = multer({ storage });

//@route GET /
//@desc Loads form
  app.get('/', (req, res) =>{
    gfs.files.find().toArray((err, files) =>{
        // check if files
        if(!files || files.length === 0){
            res.render('index', {files: false});
        }else{
           files.map(file =>{
           if(file.contentType === 'image/jpeg' || file.contentType === 'image/png')
           {
                file.isImage = true;
           }else{
               file.isImage = false;
           }
           }); 
           res.render('index', {files: files});
        }

    });
});

//@route POST /upload
//@desc Uploads file to DB
app.post('/upload', upload.single('file'), (req,res) =>{
    //res.json({file: req.file});
    res.redirect('/');
});

// @route GET/files
//@desc Display all files in JSON
app.get('/files', (req, res) => {
    gfs.files.find().toArray((err, files) =>{
        // check if files
        if(!files || files.length === 0){
            return res.status(404).json({
                err: 'no files exist'
            });
        }

        //Files exist
        return res.json(files);
    });
});


// @route GET/files/:filename
//@desc Display single file object
app.get('/files/:filename', (req, res) => {
    gfs.files.findOne({filename: req.params.filename}, (err, file) =>{
         // check if files
         if(!file || file.length === 0){
            return res.status(404).json({
                err: 'no file exists'
            });
        }
        //File exists
        return res.json(file);
    });
});

// @route GET/image/:filename
//@desc Display Image
app.get('/image/:filename', (req, res) => {
    gfs.files.findOne({filename: req.params.filename}, (err, file) =>{
         // check if files
         if(!file || file.length === 0){
            return res.status(404).json({
                err: 'no file exists'
            });
        }
        
        //check if image
        if(file.contentType === 'image/jpeg' || file.contentType === 'img/png'){
            //Read output to browser
            const readstream = gfs.createReadStream(file.filename);
            readstream.pipe(res);
        }else{
            res.status(404).json({
                err:'Not an image'
            })
        }
    });
});

//@route DELETE /files/:id
//@desc Delete file
app.delete('/files/:id', (req, res) => {
    gfs.remove({_id: req.params.id, root: 'uploads'}, (err, gridStore) => {
        if(err){
            return res.status(404).json({ err: err});
        }
        res.redirect('/');
    });
});

const port = 5000;

app.listen(port, () => console.log(`Server started on port ${port}`));
```

**Comment by vkarpov15** [comment]
Can you please try running Node with the [`--trace-deprecation` flag set](https://nodejs.org/api/cli.html#cli_trace_deprecation) so we can see where this deprecation warning is coming from? Your code isn't creating any Mongoose models, so Mongoose shouldn't be printing this error because there's no indexes to build.

**Comment by jesselawson** [comment]
Here's the result from the `--trace-deprecation` flag: 

```
/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:180:28)
    at NativeCollection.create 
(/node_modules/mongoose/lib/model.js:1650:33)
    at NativeCollection.Collection.doQueue 
(/node_modules/mongoose/lib/collection.js:120:17)
    at /node_modules/mongoose/lib/collection.js:82:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Hope that helps.

**Comment by vkarpov15** [comment]
@jesselawson  so it looks like this is coming from Mongoose. Can you please post the code that causes this deprecation warning?

**Comment by jesselawson** [comment]
@vkarpov15 Here is a stripped down version of what I am using that produces the warning. Since some things come from `.env`, this isn't technically a MWE:

```js
//...
const PORT = 3000;
const MONGO_DB_USER = process.env.MONGO_DB_USER;
const MONGO_DB_PASSWORD = process.env.MONGO_DB_PASSWORD;
const MONGO_DB_HOST = process.env.MONGO_DB_HOST;
const MONGO_DB_NAME = 'users';
const MONGO_DB_URL = `mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}/${MONGO_DB_NAME}?          retryWrites=true&w=majority`
  
mongoose.connect(MONGO_DB_URL, {useNewUrlParser: true, useUnifiedTopology: true});
//mongoose.connect(MONGO_DB_URL); // Tried without params as well; same warning.
 
mongoose.connection.on('error', error => console.log(error));

app.listen(PORT, () => {
     console.log(`listening on port ${PORT}`)
});

```

@AkashPrsd are you doing anything significantly different than what I have above? If so, please include that. Thanks!

**Comment by AndreasBBS** [comment]
@vkarpov15 While bootstrapping a project I ran into the same Warning and intantly came to the Issue list to check if this was an opened Issue as I quickly realised it was indeed a Warning coming from Mongoose.
It's a really stripped down boilerplate at this moment so I decided to save it as a boilerplate repo in my public gitlab. 
If you want to replicate the bug feel free to use my boilerplate repo, it's very little code and you should not have any problem running it and reading it, only Docker needs to be installed in your machine to startup the boilerplate.
Link to boilerplate: https://gitlab.com/AndreasBBS/sweet_stack/-/tree/server-only

**Comment by lineus** [comment]
@AkashPrsd, 

**For the original issue**, the cause is in the multer-gridfs-storage's implementation of the mongodb driver. 

The options object being passed in to the 'multer-gridfs-storage' constructor is subsequently passed to the **MongoClient connect method** *as opposed to* the **MongoClient constructor**. [The docs for multer-gridfs-storage elude to this briefly here](https://github.com/devconcept/multer-gridfs-storage#options), but you can see it explicitly [in their source code here](https://github.com/devconcept/multer-gridfs-storage/blob/master/lib/gridfs.js).

The distinction between passing the deprecation options to the MongoClient constructor vs the connect method can be explored with the following example:

### Options passed to the MongoClient Constructor ( no warnings )
```js
#!/usr/bin/env node
'use strict';

const { MongoClient } = require('mongodb');

const url = 'mongodb://localhost:27017';

const options = {
  useUnifiedTopology: true,
  useNewUrlParser: true
};


run();

async function run() {
  const mc = new MongoClient(url, options);
  const conn = await mc.connect();
  const db = conn.db('test');
  const coll = db.collection('ing');
  await coll.insertOne({ test: 'ing' });
  let inserted = await coll.findOne({ test: 'ing' });
  console.log(inserted);
  return mc.close();
}
```
### Output: 
```
❯ ./index.js
{ _id: 5f4e99b9e9277defefa6604a, test: 'ing' }
```

### Options passed to the MongoClient connect method ( deprecation warnings present )

```js
 #!/usr/bin/env node
'use strict';

const { MongoClient } = require('mongodb');

const url = 'mongodb://localhost:27017';

const options = {
  useUnifiedTopology: true,
  useNewUrlParser: true
};


run();

async function run() {
  const mc = new MongoClient(url); // the only change was to move options from here
  const conn = await mc.connect(options); // to here.
  const db = conn.db('test');
  const coll = db.collection('ing');
  await coll.insertOne({ test: 'ing' });
  let inserted = await coll.findOne({ test: 'ing' });
  console.log(inserted);
  return mc.close();
}
```

### Output
```
❯ ./index.js
(node:192550) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-deprecation ...` to show where the warning was created)
{ _id: 5f4e99b9e9277defefa6604a, test: 'ing' }
```

If you are going to continue to use the [multer-gridfs-storage](https://github.com/devconcept/multer-gridfs-storage) package, you might want to consider trying to convince the maintainers to pass the deprecation options to the MongoClient constructor, though there is at least one closed issue in their queue that makes this outcome seem unlikely.

**Comment by AndreasBBS** [comment]
@AkashPrsd I noticed you don't pass the option "useCreateIndex: true" in the GridFsStorage constructor:
`//create storage engine
  const storage = new GridFsStorage({
    url: config.mongoURI,
    options: { useNewUrlParser: true, useUnifiedTopology: true },
`
Can you please add the option and see if you still get the Warning?

**Comment by vkarpov15** [comment]
@jesselawson you would also need to do `mongoose.set('useCreateIndex', true)` as described here: https://mongoosejs.com/docs/deprecations.html

**Comment by vkarpov15** [comment]
@AndreasBBS you would also need to do mongoose.set('useCreateIndex', true) as described here: https://mongoosejs.com/docs/deprecations.html
