### ISSUE TITLE
 MongoError: Index with name: expires_1 already exists with different options

### ISSUE THREAD

**Issue by zhengtulymGh** [Automattic/mongoose#9323]
Mongo v3.4.4 
connect url: mongodb://user:password@host:port/db
work fine

Mongo v3.4.10
connect url: mongodb://user:password@host1:port1,host2:port2/db?replicaSet=set_name
get error
```
2020-08-13 22:14:50: [2020-08-13 22:14:50] MongoError: Index with name: expires_1 already exists with different options
2020-08-13 22:14:50:     at Connection.<anonymous> (/data/project/code/project_d53ccb3d805e2a616d9fh4c5b85681c/bin/node_modules/mongodb/lib/core/connection/pool.js:466:61)
2020-08-13 22:14:50:     at Connection.emit (events.js:314:20)
2020-08-13 22:14:50:     at processMessage (/data/project/code/project_d53ccb3d805e2a616d9fh4c5b85681c/bin/node_modules/mongodb/lib/core/connection/connection.js:364:10)
2020-08-13 22:14:50:     at Socket.<anonymous> (/data/project/code/project_d53ccb3d805e2a616d9fh4c5b85681c/bin/node_modules/mongodb/lib/core/connection/connection.js:533:15)
2020-08-13 22:14:50:     at Socket.emit (events.js:314:20)
2020-08-13 22:14:50:     at addChunk (_stream_readable.js:303:12)
2020-08-13 22:14:50:     at readableAddChunk (_stream_readable.js:279:9)
2020-08-13 22:14:50:     at Socket.Readable.push (_stream_readable.js:218:10)
2020-08-13 22:14:50:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
2020-08-13 22:14:50:   ok: 0,
2020-08-13 22:14:50:   errmsg: 'Index with name: expires_1 already exists with different options',
2020-08-13 22:14:50:   code: 85,
2020-08-13 22:14:50:   codeName: 'IndexOptionsConflict',
2020-08-13 22:14:50:   [Symbol(mongoErrorContextSymbol)]: {}
2020-08-13 22:14:50: }
```

**Comment by Akumzy** [comment]
@zhengtulymGh Please how did you solve this issue?

**Comment by mariohandsome** [comment]
> @zhengtulymGh Please how did you solve this issue?

try delete indexese
