### ISSUE TITLE
Aggregate command: The key is too long

### ISSUE THREAD

**Issue by fberrez** [Automattic/mongoose#9324]
# Bug

An `aggregate` command returns the following error:
 
```sh
{ MongoError: The key is too long
    at MessageStream.messageHandler (/Users/xxx/workspace/src/xxx/node_modules/mongodb/lib/cmap/connection.js:263:20)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/Users/xxx/workspace/src/xxx/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/Users/xxx/workspace/src/xxx/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (_stream_readable.js:708:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) ok: 0, code: 17280, codeName: 'KeyTooLong', name: 'MongoError' }
```

The `aggregate` command: 

```js
// fromDate: "2019-12-05T11:00:00.000Z"
// toDate: "2019-12-05T13:00:00.000Z"
myModel.aggregate([{ $match: { from: { $gte: fromDate }, to: { $lte: toDate } } }, { $group: { _id: null, total: { $sum: '$duration' } } }])
        .then(durationsMs => {
          return resolve(durationMs);
        })
        .catch(err => {
          return reject(err);
        });
```

the targeted collection index: 

```json
{
    "from" : 1,
    "to" : 1
}
```

# Expected Behavior

It should returns the following object:

```json
{
    "_id" : null,
    "total" : 75854415000
}
```

> Note: the aggregate command **works** with [robomongo](https://robomongo.org/)

**What are the versions of Node.js, Mongoose and MongoDB you are using?**
- mongoose version: 5.9.28
- mongodb: 4.4.0
- nodejs: 10.17.0

**Comment by vkarpov15** [comment]
The below script works as expected. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  
  const schema = mongoose.Schema({ from: Date, to: Date, duration: Number });
  const Model = mongoose.model('Test', schema);
  
  await mongoose.connection.dropDatabase();
  
  await Model.create({ from: '2019-06-01', to: '2019-06-02', duration: 25 });

  const fromDate = new Date('2019-01-01');
  const toDate = new Date('2020-01-01');
  const res = await Model.aggregate([
    { $match: { from: { $gte: fromDate }, to: { $lte: toDate } } },
    { $group: { _id: null, total: { $sum: '$duration' } } }
  ]);
  console.log(res);
}
```

Also, are you sure this error is because of your `aggregate()`? [This SO post](https://stackoverflow.com/questions/27792706/cannot-create-index-in-mongodb-key-too-large-to-index) seems to indicate this error only occurs on writes.

**Comment by fberrez** [comment]
Thank you for your answer.

I tried your script and it works as expected. However I found a difference between your `$match` and mine. 

In my script, I use `moment` objects as following:

```js
const momenttz = require('moment-timezone');
const moment = require('moment');

...

const fromDate = momenttz.tz(from, 'Europe/Paris');
const toDate = momenttz.tz(to, 'Europe/Paris');

myModel.aggregate([{ $match: { from: { $gte: fromDate }, to: { $lte: toDate } } }, { $group: { _id: null, total: { $sum: '$duration' } } }])
        .then(durationsMs => {
          return Promise.resolve(durationMs);
        })
        .catch(err => {
          return Promise.reject(err);
        });
```

Now, if I convert my `moment` objects to Javascript `Date` using [toDate()](https://momentjs.com/docs/#/displaying/as-javascript-date/), it works as expected.

**Comment by vkarpov15** [comment]
@fberrez yep that's expected. Moment objects don't have a `toBSON()` object, so MongoDB doesn't know how to convert them. You can either manually convert using `toDate()` or you can use a library like [mongodb-moment](https://www.npmjs.com/package/mongodb-moment)

**Comment by fberrez** [comment]
I just want to let you know that using a `moment` object (without any `toDate()`) works with a `find()`.

**Comment by vkarpov15** [comment]
@fberrez that's correct, because Mongoose casts `find()` calls to the correct type. But Mongoose can't reliably cast `aggregate()` calls because `aggregate()` can change the structure of documents.
