### ISSUE TITLE
Missing Schema Error when Populating null references

### ISSUE THREAD

**Issue by dataclear** [Automattic/mongoose#9340]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When populating a model with a refPath that hasn't been registered, mongoose gives a schema error even if the reference ID contains no values. This wasn't giving an error up until mongoose@5.8.4

**If the current behavior is a bug, please provide the steps to reproduce.**

The script below works up to mongoose 5.8.3 and fails for any versions beyond.

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/schemaerror');
var db = mongoose.connection;
db.on('error', console.error.bind(console,'MongoDB connection error:'));

const firstSchema = new Schema({
  ref: String,
  linkedId: {
    type: Schema.ObjectId,
    refPath: 'ref'
  }
});

const firstModel = mongoose.model('first', firstSchema);

const secondSchema = new Schema({
  foo: String
});

const secondModel = mongoose.model('second', secondSchema);

const displayError = async () => {

  try {
    let newSecond = await secondModel.create({foo: 'bar'});
    let populatedFirst = await firstModel.create({ref: 'second', linkedId: newSecond._id});
    let unpopulatedFirst = await firstModel.create({ref: 'third'});
    let result = await firstModel.find({}).populate('linkedId').exec();
    console.log('success');
    process.exit;
  } catch (error) {
    console.error(error);
  }

}

displayError();
```
The following error is produced:

```
MissingSchemaError: Schema hasn't been registered for model "third".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (...\node_modules\mongoose\lib\connection.js:1192:11)
    at getModelsMapForPopulate (...\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:283:59)
    at populate (...\node_modules\mongoose\lib\model.js:4309:21)
```

**What is the expected behavior?**
No errors when populating empty references.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 12.18.3
Mongoose: 5.10.0
MongoDB: 4.2.7

**Comment by kyle-belle** [comment]
Anything been done about this yet?

**Comment by Uzlopak** [comment]
Do you want to report a regression?
