### ISSUE TITLE
cyclic dependency detected

### ISSUE THREAD

**Issue by Stanys-dev** [Automattic/mongoose#9352]
**Do you want to request a *feature* or report a *bug*?**
Bug
Related to this issue: [6109](https://github.com/Automattic/mongoose/issues/6109)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v12.18.3
Mongoose: 5.10.0
MongoDB: 3.6.0

I tried to delete URI option `retryWrites: true`, my models doesn't have any indexes on `_id`

This bug causes server crash: 

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6A1E65EBF napi_wrap+114095
 2: 00007FF6A1E10B46 v8::base::CPU::has_sse+66998
 3: 00007FF6A1E11946 v8::base::CPU::has_sse+70582
 4: 00007FF6A2626E4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6A260EF21 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF6A24DB18C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF6A24E63C0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF6A24E2EE4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF6A24D86E3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF6A24DEF74 v8::internal::Heap::GlobalSizeOfObjects+212
11: 00007FF6A251507B v8::internal::StackGuard::HandleInterrupts+907
12: 00007FF6A225F999 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+7737
13: 00007FF6A2A7B3BD v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 000000C6241D1C1E

**Comment by vkarpov15** [comment]
Can you please post the stack trace of the "cyclic dependency detected" error?

**Comment by Stanys-dev** [comment]
Error: cyclic dependency detected
    at serializeObject (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:333:34)
    at serializeInto (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:941:17)
    at serializeObject (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
    at serializeInto (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:941:17)
    at serializeObject (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
    at serializeInto (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:941:17)
    at serializeObject (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
    at serializeInto (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:941:17)
    at serializeObject (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
    at serializeInto (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:941:17)
    at serializeObject (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
    at serializeInto (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:727:17)
    at serializeObject (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
    at serializeInto (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:941:17)
    at BSON.serialize (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\node_modules\bson\lib\bson\bson.js:64:28)
    at Msg.serializeBson (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\core\connection\msg.js:126:22)
    at Msg.makeDocumentSegment (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\core\connection\msg.js:118:33)
    at Msg.toBin (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\core\connection\msg.js:104:25)
    at MessageStream.writeCommand (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\cmap\message_stream.js:55:28)
    at Connection.write (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\cmap\connection.js:366:26)
    at _command (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\core\wireprotocol\command.js:120:10)
    at command (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\core\wireprotocol\command.js:28:5)
    at writeCommand (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\core\wireprotocol\write_command.js:47:3)
    at Object.insert (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\core\wireprotocol\index.js:6:5)
    at Connection.insert (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\cmap\connection.js:185:8)
    at C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\core\sdam\server.js:483:13
    at Object.callback (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\cmap\connection_pool.js:351:7)
    at processWaitQueue (C:\Users\mailb\OneDrive\Desktop\DST\data-feed\node_modules\mongodb\lib\cmap\connection_pool.js:474:23)

**Comment by vkarpov15** [comment]
Not much we can do to debug this without seeing your code. This error usually occurs when you try to insert a self-referencing document into MongoDB, like:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const circular = { answer: 42 };
  circular.circular = circular;

  await mongoose.connection.db.collection('Test').insertOne(circular);
}
```

I'd recommend taking a look at your code and seeing if you have a self-referencing object somewhere.
