### ISSUE TITLE
Make `autoIndex` and `autoCreate` default to `false` if connection's read preference is 'secondary' or 'secondaryPreferred'

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#9374]
**Do you want to request a *feature* or report a *bug*?**
Help
**What is the current behavior?**
when I set the readPreference to secondayPreferred in my app I get a mongo error:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:                                                                
MongoError: not master                                                                                                                                        
    at MessageStream.messageHandler (/home/jcmunoz/.yarn/berry/cache/mongodb-npm-3.6.0-1deea15e1a-3.zip/node_modules/mongodb/lib/cmap/connection.js:266:20)   
    at MessageStream.emit (events.js:314:20)                                                                                                                  
    at processIncomingData (/home/jcmunoz/.yarn/berry/cache/mongodb-npm-3.6.0-1deea15e1a-3.zip/node_modules/mongodb/lib/cmap/message_stream.js:144:12)        
    at MessageStream._write (/home/jcmunoz/.yarn/berry/cache/mongodb-npm-3.6.0-1deea15e1a-3.zip/node_modules/mongodb/lib/cmap/message_stream.js:42:5)         
    at writeOrBuffer (_stream_writable.js:352:12)                                                                                                             
    at MessageStream.Writable.write (_stream_writable.js:303:10)                                                                                              
    at TLSSocket.ondata (_stream_readable.js:713:22)                                                                                                          
    at TLSSocket.emit (events.js:314:20)                                                                                                                      
    at addChunk (_stream_readable.js:303:12)                                                                                                                  
    at readableAddChunk (_stream_readable.js:279:9)                                                                                                           
    at TLSSocket.Readable.push (_stream_readable.js:218:10)                                                                                                   
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)                                                                                          
```
I tested it like in #9309 and it works fine, but as the stack doesn't provide any useful info I can't trace the error.
is there a way to increase the stack trace so I can figure out where is my problem? 

If I avoid the readPreference config I works ok, and I made a little plugin in the **pre /find/ hook** to set the readPreference in the query and it also works fine, so obviously it's not a mongoose problem, but I can't trace it.

It should come from another module or an error from myself, but it's weird because the driver should take care of doing insert or updates in the primary and querying in secondary. 
**If the current behavior is a bug, please provide the steps to reproduce.**

 too much code involve...
**What is the expected behavior?**
To be able to trace the error so I can fix it.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 14.8.0
mongoose: 5.10.2
mongodb atlas 4.2.8

**Comment by vkarpov15** [comment]
How are you setting the readPreference?

Also, can you make sure you didn't typo in your app, not "secondayPreferred"?

**Comment by chumager** [comment]
hi, in the URL: mongodb+srv://user:pass@srv/database?retryWrites=true&w=majority&readPreference=secondaryPreferred&maxStalenessSeconds=120

As my app has a lot of async functions, the logs get printed without any related sequence, and I don't write anything to the DB unless an endpoint send an insert or update.

It happens between the schema definition and the model creation, but AFAIK I could write into de DB without problems even if I set secondaryPreferred, the configuration name is **readPreference** so I don't know why it could happens.

Regards.

**Comment by vkarpov15** [comment]
Do your models define indexes? For example, do you use `unique: true` or `index: true` in your schema definitions?

**Comment by chumager** [comment]
Hi, yes indeed I've lots of unique and other indexes.

Regards.

**Comment by vkarpov15** [comment]
I'd disable `autoIndex` on this connection, `mongoose.connect('mongodb+srv://user:pass@srv/database?retryWrites=true&w=majority&readPreference=secondaryPreferred&maxStalenessSeconds=120', { autoIndex: false })`

That will prevent Mongoose from trying to build indexes on this connection. MongoDB won't let you build indexes when you're connected to a secondary, so that's the most likely cause of this error.

For a future release, we should consider making `autoIndex` default to `false` if the read preference is secondary or secondaryPreferred, to avoid errors like this.

**Comment by chumager** [comment]
Thanks for the advice, but in this case, how do I build an index if I'm connected with secondary or secondaryPreferred? 

Please tell me if I'm wrong but AFAIK this setting is only for querying. Do you know if this behavior is  from mongo driver or is from mongoose?

Regards.

**Comment by vkarpov15** [comment]
The MongoDB server doesn't allow you to build indexes or do anything other than read-only operations when you're connected to a secondary. This error is from the MongoDB server, not the MongoDB node driver or Mongoose.

**Comment by Rossh87** [comment]
@vkarpov15 Interested in a PR for this?

**Comment by vkarpov15** [comment]
@Rossh87 yes, please base the PR against the 6.0 branch.
