### ISSUE TITLE
@nathlvz please open up a new issue with code samples.

### ISSUE THREAD

**Issue by SumiSastri** [Automattic/mongoose#9382]
@nathlvz please open up a new issue with code samples.

_Originally posted by @vkarpov15 in https://github.com/Automattic/mongoose/issues/4860#issuecomment-516019813_

Mongoose Schema
```
const mongoose = require("mongoose");

const Schema = mongoose.Schema;

module.exports = UserModel = new Schema({
  _id:{
    type:String,
  },
  firstName: {
    type: String,
    default: "Jane or John",
    required: false,
  },
  lastName: {
    type: String,
    default: "Doe",
    required: false,
  },
  email: {
    type: String,
    default: "email@email.com",
    required: true,
  },
  phone: {
    type: Number,
    default: 1234,
    required: false,
  },
  created_date: {
    type: Date,
    default: Date.now,
  },
});

```
The controllers for the routes 
```
const mongoose = require("mongoose");
mongoose.Promise = require("bluebird");
const UserModel = require("../../data/data-models/userModel");

const User = mongoose.model("User", UserModel);

module.exports = addNewUser = (req, res, next) => {
  let addUser = new User(req.body);
  addUser.save().then(function (savedUser) {
    res.send(savedUser);
  });
  next().catch((err) =>
    res.status().res.json(err, { message: "successfuly added user" })
  );
};

module.exports = getUsers = (req, res, next) => {
  User.find({}).then(function (userList) {
    res.send(userList);
  });
  next().catch((err) =>
    res.status().res.json(err, { message: "successfuly fetched user list " })
  );

  // Ids not recognised - logs null/ blank

  module.exports = getUserById = (req, res) => {
    console.log(req.params.userId, "check id"); // to check the id
    User.findById({ _id: req.params.userId }, { $set: req.body.userInfo })
      .exec()
      .then(function (getUser) {
        console.log("Response from mongo ", getUser);
        res.send(getUser);
      })
      .catch((err) =>
        res
          .status()
          .res.json(err, { message: "successfully fetched user by id " })
      );
  };

  module.exports = updateUser = (req, res, next) => {
    //   .route("/api-users/:userId")
    User.findByIdAndUpdate({ _id: req.params.userId }, req.body, {
      new: true,
      useFindAndModify: false,
      omitUndefined: false,
    })
      .exec()
      .then(function (updatedUser) {
        res.send(updatedUser);
      })
      .catch((err) =>
        res
          .status()
          .res.json(err, { message: "successfully updated user by id " })
      );
  };

  // DELETE works but conflicts with GET - the 2 dont work together
  module.exports = deleteUser = (req, res) => {
    // .route("/api-users/:userId")
    User.findByIdAndRemove(
      { _id: req.params.id },
      {
        new: true,
        useFindAndModify: false,
      }
    )
      .exec()
      .then(function (deletedUser) {
        res.send(deletedUser);
      })
      .catch((err) =>
        res
          .status()
          .res.json(err, { message: "successfully deleted user by id " })
      );
  };
};
```
Config for the routes
```
const addNewUser = require("../routes-control/crmControllers");
const getUsers = require("../routes-control/crmControllers");
const getUserById = require("../routes-control/crmControllers");
const updateUser = require("../routes-control/crmControllers");
const deleteUser = require("../routes-control/crmControllers");

const crmRoutes = (app) => {
  app
    .route("/api-users")
    .get((req, res, next, end) => {
      console.log(`Request from: ${req.originalUrl}`);
      console.log(`Request type: ${req.method}`);
      next();
    }, getUsers)
    .post(addNewUser);


  app
    .route("/api-users/:userId")
    .get((req, res, next) => {
      console.log(`Request from: ${req.originalUrl}`);
      console.log(`Request type: ${req.method}`);
      next();
    }, getUserById)
    .put(updateUser)
    .delete(deleteUser);

};

module.exports = crmRoutes;
```

Express server
```
/*jshint esversion: 6 */
require("dotenv").config();

const express = require("express");
const app = express();
const PORT = process.env.PORT || 5000;
// file paths static files
const path = require("path");
// Site security
const cors = require("cors");
const mongoose = require("mongoose");
const bodyParser = require("body-parser");
const helmet = require("helmet");
// middleware
app.use(helmet());
app.use(cors());
app.use(express.json());

app.use(
  bodyParser.urlencoded({
    extended: true,
  })
);
// serve static files
app.use("/", express.static(path.join(__dirname, "../public")));
app.get("/favicon.ico", (req, res) => res.sendStatus(204));

const playerRoutes = require("./apis/routes-config/playerRoutes");
playerRoutes(app);

const crmRoutes = require("./apis/routes-config/crmRoutes");
crmRoutes(app);

// mongoDb setup
const dBUri = process.env.DB_CONNECTION;
mongoose.connect(
  dBUri,
  {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
  },
  (error) => {
    if (!error) {
      console.log("mongo-db connection working");
    } else {
      console.log("check mongo-db connection", error);
    }
  }
);
mongoose.Promise = global.Promise;
app.listen(PORT, () => console.log(`your-app listening on ${PORT}`));
```
Downgrading to mongoose 4.7.2 result in connection to mongoDb crashing

Node console error:
```
check mongo-db connection Error: Invalid mongodb uri "mongodb+srv://music-manager-user:password@cluster0.iqhpj.mongodb.net/test". Must begin with "mongodb://"
    at muri (/Users/ssbt/Documents/GitHub/music-manager/server/node_modules/muri/lib/index.js:28:11)
    at NativeConnection.Connection._handleOpenArgs (/Users/ssbt/Documents/GitHub/music-manager/server/node_modules/mongoose/lib/connection.js:199:16)
    at NativeConnection.<anonymous> (/Users/ssbt/Documents/GitHub/music-manager/server/node_modules/mongoose/lib/connection.js:309:37)
    at NativeConnection.deprecated [as open] (internal/util.js:69:15)
    at Mongoose.connect (/Users/ssbt/Documents/GitHub/music-manager/server/node_modules/mongoose/lib/index.js:268:47)
    at Object.<anonymous> (/Users/ssbt/Documents/GitHub/music-manager/server/server.js:41:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
(node:3658) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
your-app listening on 5000
Unhandled rejection Error: Invalid mongodb uri "mongodb+srv://music-manager-user:jEdp8uJb5u2fmprK@cluster0.iqhpj.mongodb.net/test". Must begin with "mongodb://"
    at muri (/Users/ssbt/Documents/GitHub/music-manager/server/node_modules/muri/lib/index.js:28:11)
    at NativeConnection.Connection._handleOpenArgs (/Users/ssbt/Documents/GitHub/music-manager/server/node_modules/mongoose/lib/connection.js:199:16)
    at NativeConnection.<anonymous> (/Users/ssbt/Documents/GitHub/music-manager/server/node_modules/mongoose/lib/connection.js:309:37)
    at NativeConnection.deprecated [as open] (internal/util.js:69:15)
    at Mongoose.connect (/Users/ssbt/Documents/GitHub/music-manager/server/node_modules/mongoose/lib/index.js:268:47)
    at Object.<anonymous> (/Users/ssbt/Documents/GitHub/music-manager/server/server.js:41:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by vkarpov15** [comment]
That's by design. You need to use at least Mongoose 5.0.0 to connect to MongoDB Atlas because Atlas only supports MongoDB 3.6 and higher. See version compatibility: https://mongoosejs.com/docs/compatibility.html
