### ISSUE TITLE
Mongoose does not fetch nested subdocuments

### ISSUE THREAD

**Issue by Jeordy** [Automattic/mongoose#9408]
I would like to report a bug, or I guess it's a bug;

I'm using:
- Node 12.18.3
- Mongoose 5.10.3
- MongoDB 4.2.8 in a docker container
- On macOS 10.15.6 Catalina

I've created a Model with multiple nested subdocuments, somewhat like:

```javascript

const customerSchema = new mongoose.Schema({
  customerNumber: Number,
  customerName: String,
  ....: ....
})

const shippingSchema = new mongoose.Schema({
  company: String,
  address: String,
  ....: ....
})

const subJobSchema = new mongoose.Schema({
  shippingInfo: [shippingSchema]
})

// This is the 'root' document
const JobSchema = new mongoose.Schema({
  field: {type: String},
  customerInfo: [customerSchema],
  subJob: [subJobSchema]
})
```

When I create a new document, mongoose is returning the fully created document, with its nested subdocuments. But, when I use findAll, findById or findBy, the subJob returns as an empty array. Only the subdocuments that are one level deep, like the customerInfo, will show. Nested subdocuments don't.

With MongoDB Compass, I can see the document has been created completely, with all subdocuments.

Is it a new feature in the new mongoose version? Because I've never seen this behavior.

**Comment by Jeordy** [comment]
console.log output after using: Job.find() to retrieve all jobs (there are only 3). As you can see, the subJob is an empty array.

```javascript
[
  {
    createdAt: 2020-09-09T13:07:12.679Z,
    _id: 5f58d3b2ee73d9a5209fb051,
    orderNumber: '12345596',
    deliveryAt: 2020-09-13T00:00:00.000Z,
    customerInfo: [ [Object] ],
    file: [ [Object], [Object], [Object] ],
    subJob: []
  },
  {
    createdAt: 2020-09-09T13:11:56.247Z,
    _id: 5f58d5172f7286a61cee9561,
    orderNumber: '12345597',
    deliveryAt: 2020-09-13T00:00:00.000Z,
    customerInfo: [ [Object] ],
    file: [ [Object], [Object], [Object] ],
    subJob: []
  },
  {
    createdAt: 2020-09-10T08:22:20.601Z,
    _id: 5f59e40eb41c89d7dab0a1a9,
    orderNumber: '12345598',
    deliveryAt: 2020-09-13T00:00:00.000Z,
    customerInfo: [ [Object] ],
    file: [ [Object], [Object], [Object] ],
    subJob: []
  }
]
```

**Comment by Jeordy** [comment]
Okay, after some trial and error I am able to get the full document using find().lean(). However, I've never ever had to use the lean() function before.

**Comment by AbdelrahmanHafez** [comment]
Please modify the script below to demonstrate the issue you're facing:
### 9408.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const customerSchema = new Schema({
    customerNumber: Number,
    customerName: String
  });

  const shippingSchema = new Schema({
    company: String,
    address: String
  });

  const subJobSchema = new Schema({
    shippingInfo: [shippingSchema]
  });


  const jobSchema = new Schema({
    field: { type: String },
    customerInfo: [customerSchema],
    subJob: [subJobSchema]
  });

  const Job = mongoose.model('Job', jobSchema);

  const jobToCreate = {
    field: 'I am a field',
    customerInfo: [
      { customerNumber: 1234, customerName: 'Jane' },
      { customerNumber: 5678, customerName: 'John' }
    ],
    subJob: [
      {
        shippingInfo: [
          { company: 'A', address: 'Address A' },
          { company: 'B', address: 'Address B' }
        ]
      },
      {
        shippingInfo: [
          { company: 'C', address: 'Address C' },
          { company: 'D', address: 'Address D' }
        ]
      }
    ]
  };

  await Job.create(jobToCreate);

  const foundJob = await Job.findOne();

  assert.equal(foundJob.subJob[1].shippingInfo[1].address, 'Address D');

  console.log('All assertions passed.');
}
```

### Output
```
All assertions passed.
```

**Comment by Jeordy** [comment]
Dear Hafez,

Thank you for your reply and willingness to help me out. I’ve adjusted the file and the output is:

TypeError: Cannot read property 'shipInfo' of undefined
    at run (/Users/jeordy/Projecten/PressFer/development/apps/pressfer-api/test/test.js:377:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


I’ve attached the edited test js script, hope this will help.


Met vriendelijke groet / Yours sincerely,

Jeordy

GrafiStore
print automation
Jeordy Bouck
Software Engineer, CTO
———————————————
Aadijk 35a, 7602 PP Almelo
+31 (0) 546 85 02 31
in<https://www.linkedin.com/in/jeordybouck/>


Op 10 sep. 2020, om 14:22 heeft Hafez <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



Please modify the script below to demonstrate the issue you're facing:

9408.js

'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const customerSchema = new Schema({
    customerNumber: Number,
    customerName: String
  });

  const shippingSchema = new Schema({
    company: String,
    address: String
  });

  const subJobSchema = new Schema({
    shippingInfo: [shippingSchema]
  });


  const jobSchema = new Schema({
    field: { type: String },
    customerInfo: [customerSchema],
    subJob: [subJobSchema]
  });

  const Job = mongoose.model('Job', jobSchema);

  const jobToCreate = {
    field: 'I am a field',
    customerInfo: [
      { customerNumber: 1234, customerName: 'Jane' },
      { customerNumber: 5678, customerName: 'John' }
    ],
    subJob: [
      {
        shippingInfo: [
          { company: 'A', address: 'Address A' },
          { company: 'B', address: 'Address B' }
        ]
      },
      {
        shippingInfo: [
          { company: 'C', address: 'Address C' },
          { company: 'D', address: 'Address D' }
        ]
      }
    ]
  };

  await Job.create(jobToCreate);

  const foundJob = await Job.findOne();

  assert.equal(foundJob.subJob[1].shippingInfo[1].address, 'Address D');

  console.log('All assertions passed.');
}

Output

All assertions passed.

**Comment by Jeordy** [comment]
```javascript
'use strict'
const mongoose = require('mongoose')
const assert = require('assert')

const subJobShipSchema = new mongoose.Schema(
  {
    company: String,
    address: {
      type: String,
      required: [true, 'Please provide address'],
    },
    address2: {
      type: String,
    },
    zipcode: {
      type: String,
      required: [true, 'Please provide zipcode'],
    },
    city: {
      type: String,
      required: [true, 'Please provide city'],
    },
    state: {
      type: String,
    },
    country: {
      type: String,
      required: [true, 'Pleae provide country'],
    },
    countryCode: {
      type: String,
      minlength: 2,
      maxlength: 2,
    },
    email: {
      type: String,
    },
    phone: {
      type: String,
    },
    quantity: {
      type: Number,
      required: [true, 'Please provide quantity'],
    },
    meta: {
      type: Object,
    },
  },
  {
    toJSON: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
    toObject: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
  },
)

const customerSchema = new mongoose.Schema(
  {
    customerNumber: {
      type: String,
    },
    companyName: {
      type: String,
      required: [
        true,
        'Company name is required. When missing, use contact name',
      ],
    },
    contact: {
      type: String,
      required: [true, 'Contact is required'],
    },
    address: {
      type: String,
      required: [true, 'Address is required'],
    },
    zipcode: {
      type: String,
      required: [true, 'Zipcode is required'],
    },
    city: {
      type: String,
      required: [true, 'City is required'],
    },
    country: {
      type: String,
      required: [true, 'Country is required'],
    },
    countryCode: {
      type: String,
      minlength: 2,
      maxlength: 2,
      required: [true, 'Country code (2 chars) is required'],
    },
  },
  {
    toJSON: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
    toObject: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
  },
)

const subJobAttributesSchema = new mongoose.Schema(
  {
    fileUrl: {
      type: String,
    },
    fileType: {
      type: String,
      enum: [
        'printfile',
        'picklist',
        'invoice',
        'packingslip',
        'deliveryreceipt',
        'purchaseorder',
      ],
      default: 'printfile',
    },
    fileSize: Number,
    fileName: String,
    mimeType: String,
  },
  {
    toJSON: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
    toObject: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
  },
)

const subJobFileSchema = new mongoose.Schema(
  {
    fileUrl: {
      type: String,
    },
    fileType: {
      type: String,
      enum: [
        'printfile',
        'picklist',
        'invoice',
        'packingslip',
        'deliveryreceipt',
        'purchaseorder',
      ],
      default: 'printfile',
    },
    fileSize: Number,
    fileName: String,
    mimeType: String,
  },
  {
    toJSON: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
    toObject: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
  },
)

const subJobSchema = new mongoose.Schema(
  {
    deliveryAt: {
      type: Date,
      required: [true, 'Delivery date required.'],
    },
    shippingAt: {
      type: Date,
      default: function () {
        let date = new Date(Date.parse(this.deliveryAt))
        return date.setDate(date.getDate() - 1)
      },
    },
    productionAt: {
      type: Date,
      default: function () {
        let date = new Date(Date.parse(this.shippingAt))
        return date.setDate(date.getDate() - 1)
      },
    },
    reference: {
      type: String,
    },
    jobType: {
      type: String,
      required: [
        true,
        'Job type is required. Example: Books/Businesscards/Brochures/etc.',
      ],
      index: true,
    },
    jobName: {
      type: String,
      required: [true, 'Job name is required.'],
      index: true,
    },
    subJobAttributes: {
      type: [subJobAttributesSchema],
    },
    finish: [
      {
        type: String,
        description: String,
      },
    ],
    shipInfo: [subJobShipSchema],
  },
  {
    toJSON: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
    toObject: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
  },
)

const jobSchema = new mongoose.Schema(
  {
    orderNumber: {
      type: String,
      required: [true, 'Order number is required'],
      index: true,
    },
    customerInfo: [customerSchema],
    createdAt: {
      type: Date,
      default: Date.now(),
    },
    orderedAt: {
      type: Date,
    },
    deliveryAt: {
      type: Date,
      required: [true, 'Delivery date is required'],
    },
    reference: {
      type: String,
    },
    subJob: {
      type: [subJobSchema],
    },
    file: [subJobFileSchema],
  },
  {
    toJSON: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
    toObject: {
      transform: function (doc, ret) {
        delete ret.__v
      },
    },
  },
)

const Job = mongoose.model('Job', jobSchema)

run().catch(console.error)

async function run() {
  await mongoose.connect(
    'mongodb://user:password@localhost:27017/database?authSource=admin&readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false',
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    },
  )

  await mongoose.connection.dropDatabase()

  const jobToCreate = {
    orderNumber: '12345569',
    customerInfo: [
      {
        companyName: 'Customer',
        contact: 'John Doe',
        address: 'Street 33',
        zipcode: '12125',
        city: 'City',
        country: 'Country',
        countryCode: 'CT',
      },
    ],
    deliveryAt: '2020-09-13',
    subJob: [
      {
        jobType: 'Businesscards',
        jobName:
          'Businesscards 55 x 85 mm - 350 gr. mat mc - round corners - full color 4/4',
        deliveryAt: '2020-09-15',
        subJobAttributes: [
          {
            productType: 'Generic',
            productName:
              'Businesscards 55 x 85 mm - 350 gr. mat mc - round corners - full color 4/4',
            quantity: 500,
            media: '350 gr. woodfree mat mc',
            widthNet: 85,
            heightNet: 55,
            numberOfPages: 2,
            colors: '4/4',
            printMethod: 'offset',
            finish: [
              {
                description: 'Round corners',
              },
            ],
            file: [
              {
                fileUrl: 'https://download.com/businesscard.pdf',
                fileName: 'businesscard.pdf',
                fileType: 'printfile',
              },
            ],
          },
        ],
        shipInfo: {
          company: 'Company',
          address: 'Address 233',
          zipcode: '44032',
          city: 'City',
          country: 'Country',
          countryCode: 'CT',
          quantity: 500,
        },
      },
    ],
    file: [
      {
        fileUrl: 'https://download.com/businesscard.pdf',
        fileType: 'purchaseorder',
      },
      {
        fileUrl: 'https://download.com/businesscard.pdf',
        fileType: 'deliveryreceipt',
      },
      {
        fileUrl: 'https://download.com/businesscard.pdf',
        fileType: 'invoice',
      },
    ],
  }

  const newJob = await Job.create(jobToCreate)

  console.log(newJob)

  const foundJob = await Job.findOne()

  assert.equal(foundJob.subJob[0].shipInfo[0].address, 'Address D')

  console.log('All assertions passed.')
}
```

**Comment by AbdelrahmanHafez** [comment]
I simplified the script a bit, the issue seems to have something to do with `this` referring to an empty object in the default function for `shippingAt`.
### 9408_2.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();


  const jobSchema = new Schema({
    deliveryAt: Date,
    subJob: [{
      deliveryAt: Date,
      shippingAt: {
        type: Date,
        default () {
          const date = new Date(Date.parse(this.deliveryAt)); // <== `this` is an empty object
          return date.setDate(date.getDate() - 1);
        }
      },
      shipInfo: [{ address: String }]
    }]
  });

  const Job = mongoose.model('Job', jobSchema);

  const jobToCreate = {
    deliveryAt: '2020-09-13',
    subJob: [
      {
        deliveryAt: '2020-09-15',
        shippingAt: '2020-01-01',
        shipInfo: [{ address: 'Address 233' }]
      }
    ]
  };

  const createdJob = await Job.create(jobToCreate);

  assert.strictEqual(createdJob.subJob[0].shipInfo[0].address, 'Address 233');
  console.log('Passed creation assertion successfully.');

  const foundJob = await Job.findOne();

  assert.strictEqual(foundJob.subJob[0].shipInfo[0].address, 'Address 233');
  console.log('Passed all assertions successfully.');
}
```

### Output
```
Passed creation assertion successfully.
TypeError: Cannot read property 'shipInfo' of undefined
    at run (/test.js:53:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Jeordy** [comment]
Thank you very much for your help.

**Comment by supermar1010** [comment]
I have a similiar problem with retrieving nested properties, so I guess this is not completely fixed.

My document according to mongo express looks like this:

```json
{
    _id: ObjectId('5fb55a6653549930c3430edd'),
    title: 'Test1',
    someArray: [
        {
            someName: 'Mario',
            availableTimes: [
                {
                    someNumber: '1605729569',
                    someOtherNumber: '1605729569'
                },
                {
                    someNumber: '1605729569',
                    someOtherNumber: '1605729569'
                }
            ]
        },
        {
            someName: 'Max',
            availableTimes: [
                {
                    someNumber: '1605749569',
                    someOtherNumber: '1605749569'
                },
                {
                    someNumber: '1605749569',
                    someOtherNumber: '1605749569'
                }
            ]
        }
    ],
    createdAt: ISODate('2020-11-18T17:31:18.825Z'),
    updatedAt: ISODate('2020-11-18T17:31:18.825Z'),
    __v: 0
}
```


when retrieving by mongoose, it is missing the availableTimes:

```json
{
    "_id": "5fb55a6653549930c3430edd",
    "title": "TestSurvey1",
    "someArray": [
        {
            "someName": "Mario"
        },
        {
            "someName": "Max"
        }
    ],
    "createdAt": "2020-11-18T17:31:18.825Z",
    "updatedAt": "2020-11-18T17:31:18.825Z",
    "__v": 0
}
```
