### ISSUE TITLE
In a Schema, defining a key named 'set' while using the 'timestamps' option for that Schema causes create operations to throws an error

### ISSUE THREAD

**Issue by toinetoine** [Automattic/mongoose#9428]
**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?**
Despite not being on the Mongoose API's [list of reserved words](https://mongoosejs.com/docs/api.html#schema_Schema.reserved) for Schemas, defining a key named 'set' in a Schema while using the 'timestamps' option (both `timestamps: true` or `timestamps: {createdAt: 'created', updatedAt: 'updated'}` trigger this) causes the following error to be thrown when creating a document on a Model using that schema:

```javascript
TypeError: this.set is not a function
    at model.<anonymous> (xxx/node_modules/mongoose/lib/schema.js:1201:12)
    at callMiddlewareFunction (xxx/node_modules/kareem/index.js:482:23)
    at model.next (xxx/node_modules/kareem/index.js:58:7)
    at _next (xxx/node_modules/kareem/index.js:106:10)
    at xxx/node_modules/kareem/index.js:507:38
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

The error is thrown from [this](https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L1217) line in lib/schema.js:
[https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L1217](https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L1217)

______________

A create on a Model using the following Schema works fine:
```javascript
var Something = new Schema({
    set: String
});
```

But when you add the `timestamps` option (both the `bool` and `object` value trigger this) and perform a create on a Model using it, the error mentioned above is thrown:
```javascript
var Something = new Schema({
    set: String
}, {
    timestamps: true
});
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js v14.8.0, Mongoose v5.9.29, MongoDB v3.6.3

**Comment by toinetoine** [comment]
https://github.com/Automattic/mongoose/commit/9faa7305e3596a5dbae4f4823b6a9d503f1090dc
