### ISSUE TITLE
SSL connection docs

### ISSUE THREAD

**Issue by Sujay-shetty** [Automattic/mongoose#9443]
Hi,

This is bug related to SSL connection to MongoDB.

I'm trying to connect to mongodb with requireSSL flag enabled from mongod while running mongo instance.

Using Mongoose V5.10.6 driver for connecting to above setup with below options.

```
var ca = fs.readFileSync(<path to certificate.pem file>);
var mongoose = require("mongoose");
var options = {
    sslValidate: true,
    sslCA: ca,
    useCreateIndex: true,
    useNewUrlParser: true,
    mongos: true,
    autoReconnect: true,
    reconnectTries: 1000,
    reconnectInterval: 30000,
    dbName: "test"
}

mongoose.connect("mongodb://<username>:<password>@<mongodb_server_name>:<mongodb_port>/adminDb?authSource=admin&ssl=true");
```

But from MongoDB server side where connection accepts only ssl above code is throwing error

```
Failed to connect to mongo on startup - retrying in 5 sec { MongoNetworkError: failed to connect to server [<server_name>:<server_ip>] on first connect [MongoNetworkError: connection 5 to <server_name>:<server_ip> closed]
at Pool.<anonymous> (/home/test/node_modules/mongoose/node_modules/mongodb/lib/core/topologies/server.js:438:11)
at Pool.emit (events.js:198:13)
at createConnection (/home/test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:562:14)
at connect (/home/test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:995:11)
at callback (/home/test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:97:5)
at runCommand (/home/test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:124:7)
at _callback (/home/test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:349:5)
at Connection.errorHandler (/home/test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:365:5)
at Object.onceWrapper (events.js:286:20)
at Connection.emit (events.js:198:13)
at Socket.<anonymous> (/home/test/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:370:12)
at Object.onceWrapper (events.js:286:20)
at Socket.emit (events.js:198:13)
at TCP._handle.close (net.js:606:12) name: 'MongoNetworkError' }
```

Tried to change options parameter to include server as like below, but still it throwed same error.

```
var options = {
    server: {
        sslValidate: true,
        sslCA: ca,
    }
    useCreateIndex: true,
    useNewUrlParser: true,
    mongos: true,
    autoReconnect: true,
    reconnectTries: 1000,
    reconnectInterval: 30000,
    dbName: "test"
}
```

From official documentation there is no information related to how to connect using SSL.
https://mongoosejs.com/docs/connections.html

**Comment by vkarpov15** [comment]
Move `sslValidate` and `sslCA` to top-level as shown here: http://mongodb.github.io/node-mongodb-native/3.6/api/MongoClient.html

```javascript
var options = { sslValidate: true, sslCA: ca, useCreateIndex: true, useNewUrlParser: true, mongos: true, autoReconnect: true, reconnectTries: 1000, reconnectInterval: 30000, dbName: "test" }
```

**Comment by Sujay-shetty** [comment]
@vkarpov15 first time it is tried in top-level as mentioned by you. Please check first block of code in above comment

**Comment by vkarpov15** [comment]
@Sujay-shetty are you able to connect using the `mongo` shell? This may be a connectivity issue.

Also, try removing `sslCA`. If that works, that means the `ca.pem` file doesn't include the mongodb server's certificate.
