### ISSUE TITLE
Problem with nested schemas and $elemMatch

### ISSUE THREAD

**Issue by peteboere** [Automattic/mongoose#9481]
**Do you want to request a *feature* or report a *bug*?**
bug

**If the current behavior is a bug, please provide the steps to reproduce.**

When using a nested Schema querying with $elemMatch results in an error:
  
````
const schema = Schema({
    audience: {
        default: undefined,
        type: Schema({
            _id: false,
            group: String,
        }),
    },
}, {
    strict: 'throw',
    versionKey: false,
});

Model.findOne({
    audience: {
        $elemMatch: {
            group: 'a',
        },
    },
});
````

````
Error: Can't use $elemMatch
      at SingleNestedPath.castForQuery
      at SingleNestedPath.SchemaType.castForQueryWrapper 
      at cast (node_modules/mongoose/lib/cast.js:310:39)
      at model.Query.Query.cast (node_modules/mongoose/lib/query.js:4781:12)
      at model.Query.Query._castConditions (node_modules/mongoose/lib/query.js:1873:10)
      at model.Query.<anonymous> (node_modules/mongoose/lib/query.js:2130:8)
      at model.Query._wrappedThunk [as _findOne] (node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
      at node_modules/kareem/index.js:369:33
      at processTicksAndRejections (internal/process/task_queues.js:75:11)
````

I can just use a plain nested object but this gives no validation at all:  
````
const schema = Schema({
    audience: {
        default: undefined,
        type: {
            _id: false,
            group: String,
        },
    },
}, {
    strict: 'throw',
    versionKey: false,
});
````

**What is the expected behavior?**
Should not error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose@5.10.9
node v12.12.0

**Comment by peteboere** [comment]
Please ignore. My error
