### ISSUE TITLE
"clusterTime" had the wrong type

### ISSUE THREAD

**Issue by silenceu** [Automattic/mongoose#9495]
Hi, first thasks for your work.

We are connectiong to mongo4.2.1 replica-set with three node, then I found an occasional error.

Here is the error message: 
```
MongoError: "clusterTime" had the wrong type. Expected timestamp, found string
    at MessageStream.messageHandler (/microservice/develop/microserver_logic_taped_dev/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:223:5)
    at processIncomingData (/microservice/develop/microserver_logic_taped_dev/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/microservice/develop/microserver_logic_taped_dev/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at MessageStream.Writable.write (_stream_writable.js:309:11)
    at Socket.ondata (_stream_readable.js:728:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

And here is my environment:

- NodeJS 12.15.0
- mongoose 5.9.20, 5.10.9(latest version)
- mongodb 4.2.1 replica-set with three node

I find a sam issue from nodeclient issue list #https://github.com/nosqlclient/nosqlclient/issues/523, the author of nodeclient has fix the bug by upgrade bson. I think mongooose also has the same problem.

**Comment by vkarpov15** [comment]
What operation is triggering this error? Are you using [change streams](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html)?

**Comment by silenceu** [comment]
No, I don't use change streams. I'm not sure which operation trigger this error, because this error is not very regular.

**Comment by silenceu** [comment]
I try switch to mongodb 3.4, the only different is mongo version, then the error no longer occurs. I can offer you more detailed log and my connect options tomorrow, hope it can help you.
