### ISSUE TITLE
VersionError: No matching document found for id "5f954cd916000c622a3e196e" version 32 modifiedPaths "warn, warn.0, warn.0.time, warn.0.reason"

### ISSUE THREAD

**Issue by CutieCat6778** [Automattic/mongoose#9506]
I can't save document like normaly. 
In my database i save a lots of object in an array.
I get an Object from array using `.find()` and then modifie it.

**Model**
```js
warn: [
        { "userId": String, "time": Number, "reason": String }
    ],
```

**Code**
```js
    const guild = await require("../tools/getGuild")(client, message.guild.id);
    const targetData = guild.warn.find(t => t.userId == target.id);
    if (!targetData) {
        const object = {
            userId: target.id, time: 0, reason: " "
        }
        guild.warn.push(object);
        await guild.save();
        return message.channel.send("That user has no warns");
    }
    if (targetData.time == 0) return message.channel.send("That user don't have any warns to delete");
    targetData.time--;
    targetData.reason = `Deleted one warn for reason __${reason}__`;
    console.log(targetData);
    await guild.save()
    return message.channel.send(`One warn has been removed from **${target.user.username}**`)
```
**Full error**
```console
VersionError: No matching document found for id "5f954cd916000c622a3e196e" version 32 modifiedPaths "warn, warn.0, warn.0.time, warn.0.reason"
    at generateVersionError (D:\ModeratorBot\node_modules\mongoose\lib\model.js:421:10)    
    at model.Model.save (D:\ModeratorBot\node_modules\mongoose\lib\model.js:478:28)        
    at warn (D:\ModeratorBot\functions\deletewarn.js:17:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9) {
  version: 32,
  modifiedPaths: [ 'warn', 'warn.0', 'warn.0.time', 'warn.0.reason' ]
```

**Comment by vkarpov15** [comment]
The error message indicates that the 2nd `await guild.save()` is what causes this error, because it lists `time` and `reason` as modified paths. Most likely this issue is due to either the `guild` document being deleted, or modified in an incompatible way. Do you have code that overwrites the `warn` array or calls `pull()` on the `warn` array?

**Comment by Abhinav2004-1** [comment]
Code:
router.post('/', (req, res)=>{
    const MyName = req.body.MyName;
    const RequestName = req.body.RequestName;
    RegisterModel.findOne({ Username: MyName }).exec().then((profile)=>{
        const Requests = profile.Requests.filter(element=> element.sender !== RequestName)
        profile.Requests = Requests;
        profile.save().then(()=>{
            cache.set(`friend-req/${MyName}`, JSON.stringify(Requests), ()=>{
                return res.json({request_removed: true});
            })
        })
    }).catch(()=>{
        return res.json({error: true});
    })
})

The error this code is throwing is:
[0] (node:6184) UnhandledPromiseRejectionWarning: VersionError: No matching document found for id "6006c072e95c741828ec467d" version 1 modifiedPaths "Requests"
[0]     at generateVersionError (C:\Users\dependra\Desktop\Projects\MemeTinder\server\node_modules\mongoose\lib\model.js:421:10)
[0]     at model.Model.save (C:\Users\dependra\Desktop\Projects\MemeTinder\server\node_modules\mongoose\lib\model.js:478:28)
[0]     at file:///C:/Users/dependra/Desktop/Projects/MemeTinder/server/Routes/friend-request.js:58:17
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0] (node:6184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[0] (node:6184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vkarpov15** [comment]
@Abhinav2004-1 please open a new issue and follow the issue template.
