### ISSUE TITLE
Infinite loop when use `toJSON` with `getters: true`

### ISSUE THREAD

**Issue by orblazer** [Automattic/mongoose#9712]
**Do you want to request a *feature* or report a *bug*?** I think this is an bug

**What is the current behavior?**
When i use not working schema (said bellow) this make an infinite loop when i use `toJSON` with `{ getters: true }`.
The error :
```
RangeError: Internal Server Error
    at minimize (/app/node_modules/mongoose/lib/document.js:3378:18)
    at minimize (/app/node_modules/mongoose/lib/document.js:3390:18)
    at minimize (/app/node_modules/mongoose/lib/document.js:3390:18)
    at minimize (/app/node_modules/mongoose/lib/document.js:3390:18)
    ...
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The project (work) : https://gist.github.com/orblazer/eed83eafbac565d1556815680e7bec6f
And not working schemas :
```js
const dataSchema = new Schema(
  {
    locale: {
      required: true,
      type: String
    },
    balance: {
      required: true,
      type: Number
    },
    websiteLinked: {
      required: true,
      type: Boolean
    },
    subscription: {
      required: true,
      type: String,
      enum: ['BRONZE', 'EMERALD', 'DIAMOND']
    },
    subscriptionEndDate: {
      required: false,
      type: Date
    },
    serverData: {
      type: Map,
      of: {
        type: Map,
        of: Schema.Types.Mixed
      }
    }
  },
  {
    _id: false
  }
)
const statisticsSchema = new Schema(
  {
    played: {
      required: true,
      type: Number
    },
    data: {
      type: Map,
      of: Schema.Types.Mixed
    }
  },
  {
    _id: false
  }
)
const accountSchema = new Schema(
  {
    _id: {
      required: true,
      type: Buffer,
      subtype: Binary.SUBTYPE_UUID,
      get: (val) => (val instanceof Buffer ? uuid.fromBuffer(val) : val),
      set: (val) => (val instanceof Buffer ? val : uuid.toBuffer(val))
    },
    username: {
      required: true,
      type: String,
      unique: true,
      trim: true
    },
    createdAt: {
      required: true,
      type: Date
    },
    createdIp: {
      required: true,
      type: String
    },
    data: {
      required: false,
      type: dataSchema
    },
    statistics: {
      type: Map,
      of: statisticsSchema
    }
  },
  {
    id: false,
    toObject: { getters: true },
    toJSON: { getters: true }
  }
)
```

**What is the expected behavior?**
Return right plained object.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- Node.JS : 14.15.1 (Alpine 3.11, docker image : https://github.com/nodejs/docker-node/blob/41ea0562287bbf98693572c9228edc1beb7fd709/14/alpine3.11/Dockerfile)
- Mongoose : 5.11.7
- MongoDB : 4.4.2 Community

**Comment by vkarpov15** [comment]
Can you try running `npm list | grep "bson"`? It might be that you have different versions of bson.

Otherwise, the below script works fine if I just `npm install mongoose uuid` in a new directory. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';

const mongoose = require('mongoose');
const { Binary } = require('bson');
const { v4 } = require('uuid');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  const dataSchema = new Schema({
    locale: {
      required: true,
      type: String
    },
    balance: {
      required: true,
      type: Number
    },
    websiteLinked: {
      required: true,
      type: Boolean
    },
    subscription: {
      required: true,
      type: String,
      enum: ['BRONZE', 'EMERALD', 'DIAMOND']
    },
    subscriptionEndDate: {
      required: false,
      type: Date
    },
    serverData: {
      any: {
        type: Map,
        of: Schema.Types.Mixed
      }
    }
  },
  {
    _id: false
  });

  const statisticsSchema = new Schema({
    played: {
      required: true,
      type: Number
    },
    data: {
      any: {
        type: Schema.Types.Mixed
      }
    }
  }, { _id: false });

  const accountSchema = new Schema({
    _id: {
      required: true,
      type: Buffer,
      subtype: Binary.SUBTYPE_UUID,
      get: (val) => (val instanceof Buffer ? uuid.fromBuffer(val) : val),
      set: (val) => (val instanceof Buffer ? val : uuid.toBuffer(val))
    },
    username: {
      required: true,
      type: String,
      unique: true,
      trim: true
    },
    createdAt: {
      required: true,
      type: Date
    },
    createdIp: {
      required: true,
      type: String
    },
    data: {
      required: false,
      type: dataSchema
    },
    statistics: {
      any: {
        type: statisticsSchema
      }
    }
  },
  {
    id: false,
    toObject: { getters: true },
    toJSON: { getters: true }
  });

  const Account = mongoose.model('Test', accountSchema, 'accounts');

  const account = await Account.findById('2df03368-a4c6-4b05-8807-fca12ab50134');
  console.log(account);
  console.log(JSON.stringify(account));

  console.log('Done');  
}

const UUIDRegex = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/
const trimmedUUIDRegex = /^[0-9a-fA-F]{12}4[0-9a-fA-F]{3}[89abAB][0-9a-fA-F]{15}$/
const EMPTY_UUID = '00000000-0000-0000-0000-000000000000'

function toBuffer(uuid) {
  if (uuid !== EMPTY_UUID && !UUIDRegex.test(uuid)) {
    throw new TypeError('The uuid is not valid UUID v4')
  }
  return Buffer.from(uuid.replace(/-/g, ''), 'hex')
}

const uuid = {
  emptyUUID: toBuffer(EMPTY_UUID),

  fromBuffer(buffer) {
    if (buffer.length !== 16) {
      throw new TypeError('Expected length to be 16, not ' + buffer.length)
    }
    if (this.emptyUUID.equals(buffer)) {
      return EMPTY_UUID
    }
    return v4({ random: buffer })
  },
  toBuffer,

  fromTrimmed(uuid) {
    return (
      uuid.substring(0, 8) +
      '-' +
      uuid.substring(8, 12) +
      '-' +
      uuid.substring(12, 16) +
      '-' +
      uuid.substring(16, 20) +
      '-' +
      uuid.substring(20, 32)
    ).toUpperCase()
  }
};
```

Output:

```
{
  statistics: { INVASION: { data: [Object], played: 4823638998 } },
  _id: '2df03368-a4c6-4b05-8807-fca12ab50134',
  createdAt: 2020-12-13T13:36:45.922Z,
  createdIp: '127.0.0.1',
  data: {
    serverData: { BUNGEECORD: [Object] },
    balance: 0,
    group: 5eff6671dbfd878ce10365db,
    locale: 'en_US',
    subscription: 'BRONZE',
    websiteLinked: false
  },
  name: 'orblazer',
  username: 'orblazer'
}
{"statistics":{"INVASION":{"data":{"wave":1},"played":4823638998}},"_id":"2df03368-a4c6-4b05-8807-fca12ab50134","createdAt":"2020-12-13T13:36:45.922Z","createdIp":"127.0.0.1","data":{"serverData":{"BUNGEECORD":{"canWhispered":true,"mentionSound":true}},"balance":0,"group":"5eff6671dbfd878ce10365db","locale":"en_US","subscription":"BRONZE","websiteLinked":false},"name":"orblazer","username":"orblazer"}
Done
^C

```

**Comment by orblazer** [comment]
@vkarpov15 i have bson `1.1.5`. And yes the schema work because you have only get it on my gist, below the link i have that the bugged schema.

**Comment by vkarpov15** [comment]
@orblazer do you have multiple bson versions installed?

Below script also works fine, with the bugged schema you posted. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';

const mongoose = require('mongoose');
const { Binary } = require('bson');
const { v4 } = require('uuid');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  const dataSchema = new Schema({
    locale: {
      required: true,
      type: String
    },
    balance: {
      required: true,
      type: Number
    },
    websiteLinked: {
      required: true,
      type: Boolean
    },
    subscription: {
      required: true,
      type: String,
      enum: ['BRONZE', 'EMERALD', 'DIAMOND']
    },
    subscriptionEndDate: {
      required: false,
      type: Date
    },
    serverData: {
      type: Map,
      of: Schema.Types.Mixed
    }
  },
  {
    _id: false
  });

  const statisticsSchema = new Schema({
    played: {
      required: true,
      type: Number
    },
    data: {
      any: {
        type: Schema.Types.Mixed
      }
    }
  }, { _id: false });
  const accountSchema = new Schema({
    _id: {
      required: true,
      type: Buffer,
      subtype: Binary.SUBTYPE_UUID,
      get: (val) => (val instanceof Buffer ? uuid.fromBuffer(val) : val),
      set: (val) => (val instanceof Buffer ? val : uuid.toBuffer(val))
    },
    username: {
      required: true,
      type: String,
      unique: true,
      trim: true
    },
    createdAt: {
      required: true,
      type: Date
    },
    createdIp: {
      required: true,
      type: String
    },
    data: {
      required: false,
      type: dataSchema
    },
    statistics: {
      type: statisticsSchema
    }
  },
  {
    id: false,
    toObject: { getters: true },
    toJSON: { getters: true }
  });

  const Account = mongoose.model('Test', accountSchema, 'accounts');

  const account = await Account.findById('2df03368-a4c6-4b05-8807-fca12ab50134');
  console.log(account);
  console.log(JSON.stringify(account));

  console.log('Done');
}
```

**Comment by knyuwork** [comment]
I have the same issue. My schema is like this.

```
const BrandProfile = new Schema(
  {
    description: { type: String },
  },
  { _id: false, timestamps: false, versionKey: false, toJSON: { getters: true } }
);

const LocaleSetting = new Schema(
  {
    profile: BrandProfile,
  },
  { _id: false, timestamps: false, versionKey: false, toJSON: { getters: true } }
);

const Brand = new Schema(
  {
    profile: { type: BrandProfile, required: true },
    locales: {
      type: Map,
      of: LocaleSetting,
    },
  },
  { timestamps: true, versionKey: false, toJSON: { getters: true } }
);
```

**Comment by knyuwork** [comment]
> I have the same issue. My schema is like this.
> 
> ```
> const BrandProfile = new Schema(
>   {
>     description: { type: String },
>   },
>   { _id: false, timestamps: false, versionKey: false, toJSON: { getters: true } }
> );
> 
> const LocaleSetting = new Schema(
>   {
>     profile: BrandProfile,
>   },
>   { _id: false, timestamps: false, versionKey: false, toJSON: { getters: true } }
> );
> 
> const Brand = new Schema(
>   {
>     profile: { type: BrandProfile, required: true },
>     locales: {
>       type: Map,
>       of: LocaleSetting,
>     },
>   },
>   { timestamps: true, versionKey: false, toJSON: { getters: true } }
> );
> ```
> 
> The issue occurs when I do `Brand.findById(brandId)`

I found the solution.
My error is like this
at minimize (/Users/xxx/Documents/project/project-backend/node_modules/mongoose/lib/document.js:3489:18)

so, after I update  `toJSON: { getters: true }` to  `toJSON: { getters: true, minimize: false }`
the problem solved
