### ISSUE TITLE
Cyclic dependency error 

### ISSUE THREAD

**Issue by pgamerxdev** [Automattic/mongoose#9716]
Ok so My schema file is this 
```js
const mongoose = require('mongoose');

const setwelcome = new mongoose.Schema({
    status: {
        type: String
    },
    channel: {
        type: String
    },
    message: {
        type: String
    },
    GuildID: String
});

const MessageModel = module.exports = mongoose.model('welcome setting', setwelcome);
```
My index code is 
```js
if(command === "welcome"){
  if(!message.member.hasPermission("MANAGE_SERVER")) return message.react(":no_entry_sign:")

  if(args[1] === "set"){
  
  const welcome = await welcomeinfo.findOne({
    guildID: message.guild
  })
  
  if(!welcome){
 let channel = null
 let welcomemsg = null
    const botMessage = await message.channel.send("Alright It's time to choose the channel ! Kindly mention the channel or provide the channel ID");
    MessageCollector.question({
        botMessage,
        user: message.author.id,
        onMessage: async (botMessage, reply) => { // Every message sent by user will trigger this function.
         if(reply.mentions.channels.first()){
           let bruh = reply.mentions.channels.first().id
           channel = bruh
       reply.channel.send(`Alright ! ${reply.content} has been set as channel for welcome message`)
return
         }else if(!reply.mentions.channels.first()){
         let guild = reply.guild.channels.cache.get(reply.content)
          if(!guild) return reply.channel.send(`Couldn't find the channel . Are you sure ID is correct?`)
          channel = reply.content
          reply.channel.send(`Alright ! <#${reply.content}> has been set as channel for welcome message`)

         }
        }
    });

    let messagechoose = new Discord.MessageEmbed()
    .setTitle(`Time to set the Message!`)
    .setDescription(`
Kindly send the message which you would like to set as welcome message . 
    **PlaceHolders** -
 1.` + " ` " + `{mention}` + " ` " + " - Mentions the user. For eg - @PGamerX "+
`2.` + " ` " + `{usertag}` + " ` " + " - Writes the username along with tag . For eg - PGamerX#7851 "
`3.` + " ` " + `{memberCount}` + " ` " + " - Writes the member count " )
.setColor("GREEN")


    const botMessage2 = await message.channel.send(messagechoose)
    MessageCollector.question({
        botMessage2,
        user: message.author.id,
        onMessage: async (botMessage2, reply) => { 
 
      if(reply){
        welcomemsg = reply.content
        let final = new Discord.MessageEmbed()
        .setTitle(`Setup Done! Welcome Message is`)
        .setDescription(welcomemsg)
        addField(`Welcome Channel` , channel)
        reply.channel.send(final)
      }          

        } })

        let newData = new welcomeinfo({
          GuildID: reply.guild.id,
          status: "yes" , 
          channel: channel , 
          message: welcomemsg
      })
      newData.save()
  }

  else if(welcome)
  {
    return message.channel.send(`Hey ! You already have a welcome message set ! Firstly you need to remove it using ${PREFIX}welcome delete`)
}
}

else if(args[1] === "delete"){
  await welcomeinfo.findOneAndRemove({
    GuildID: msg.guild.id
})

}

}
```
My error 
```
0|index  | Error: cyclic dependency detected
0|index  |     at serializeObject (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:333:34)
0|index  |     at serializeInto (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:941:17)
0|index  |     at serializeObject (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|index  |     at serializeInto (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:837:17)
0|index  |     at serializeObject (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|index  |     at serializeInto (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:941:17)
0|index  |     at serializeObject (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|index  |     at serializeInto (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:941:17)
0|index  |     at serializeObject (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|index  |     at serializeInto (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:941:17)
0|index  |     at serializeObject (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|index  |     at serializeInto (/root/Black Sheep/node_modules/bson/lib/bson/parser/serializer.js:941:17)
0|index  |     at BSON.serialize (/root/Black Sheep/node_modules/bson/lib/bson/bson.js:64:28)
0|index  |     at Msg.serializeBson (/root/Black Sheep/node_modules/mongodb/lib/core/connection/msg.js:126:22)
0|index  |     at Msg.makeDocumentSegment (/root/Black Sheep/node_modules/mongodb/lib/core/connection/msg.js:118:33)
0|index  |     at Msg.toBin (/root/Black Sheep/node_modules/mongodb/lib/core/connection/msg.js:104:25)
0|index  |     at MessageStream.writeCommand (/root/Black Sheep/node_modules/mongodb/lib/cmap/message_stream.js:55:28)
0|index  |     at Connection.write (/root/Black Sheep/node_modules/mongodb/lib/cmap/connection.js:368:26)
0|index  |     at _command (/root/Black Sheep/node_modules/mongodb/lib/core/wireprotocol/command.js:120:10)
0|index  |     at command (/root/Black Sheep/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)
0|index  |     at Object.query (/root/Black Sheep/node_modules/mongodb/lib/core/wireprotocol/query.js:57:3)
0|index  |     at Connection.query (/root/Black Sheep/node_modules/mongodb/lib/cmap/connection.js:175:8)
0|index  |     at /root/Black Sheep/node_modules/mongodb/lib/core/sdam/server.js:309:12
0|index  |     at Object.callback (/root/Black Sheep/node_modules/mongodb/lib/cmap/connection_pool.js:345:7)
0|index  |     at processWaitQueue (/root/Black Sheep/node_modules/mongodb/lib/cmap/connection_pool.js:468:23)
0|index  |     at /root/Black Sheep/node_modules/mongodb/lib/cmap/connection_pool.js:236:28
0|index  |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
Kindly Support 
Thanks

**Comment by edgesinghkataria** [comment]
@pgamerxdev are you still facing this issue? 
Thanks

**Comment by gustavo0197** [comment]
I faced this error, I updated to the version 5.11.8 and everything is working well.

You can also set autoIndex to false in the connection options

```js
mongoose.connect('mongodb://localhost:27017/test', { autoIndex: false });
```

**Comment by pgamerxdev** [comment]
Thanks you guys for your help 
I was being dumb as I was pushing an object in a parameter I had set as a string in schema

**Comment by pgamerxdev** [comment]
Thanks you guys for your help
I was being dumb as I was pushing an object in a parameter I had set as a string in schema
