### ISSUE TITLE
Cannot read property '_promiseOrCallback' of undefined at model.Model.save (/node_modules/mongoose/lib/model.js:482:23) 

### ISSUE THREAD

**Issue by msiraj56** [Automattic/mongoose#9793]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
document.save(opts) is resulting in following error (with stack trace):
at model.Model.save (/node_modules/mongoose/lib/model.js:482:23) 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v10.23.0
Mongoose: v5.11.11
Mongodb: v4.4.2

**Comment by msiraj56** [comment]
Apparently there was a schema path 'db' which is causing some mongoose framework code to break. 

However, when I reverted to mongoose 5.7.13 the last working version, it reported error on schema construction itself, 5.10.9 onwards breaks later at runtime. Will resolve schema path to not use 'db' as it seems to be a reserved word for mongoose library.

**Comment by msiraj56** [comment]
Believe mongoose.Schema.reserved should list 'db' as a reserved name so that it is not used in path names.
