### ISSUE TITLE
mongoose crashes with CastError for a number

### ISSUE THREAD

**Issue by rmmenon** [Automattic/mongoose#9810]
mongoose version (just upgraded to) : 5.11.11

This is a bug

**What is the current behavior?**

mongoose crashes with a cast error - the stack trace of which looks as follows:

```
/Users/<directories>/node_modules/mongoose/lib/query.js:4358
  const castError = new CastError();
                    ^
  
CastError: Cast to Number failed for value "undefined" at path "tradeYear" for model "Trade"
    at model.Query.exec (/Users/<directories>/node_modules/mongoose/lib/query.js:4358:21)
    at model.Query.Query.then (/Users/<directories>/node_modules/mongoose/lib/query.js:4450:15) {
  messageFormat: undefined,
  stringValue: '"undefined"',
  kind: 'Number',
  value: 'undefined',
  path: 'tradeYear',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      
    assert.ok(!isNaN(val))
      
      at castNumber (/Users/<directories>/node_modules/mongoose/lib/cast/number.js:28:10)
      at SchemaNumber.cast (/Users/<directories>/node_modules/mongoose/lib/schema/number.js:399:12)
      at SchemaNumber.SchemaType.applySetters (/Users/<directories>/node_modules/mongoose/lib/schematype.js:1109:12)
      at SchemaNumber.SchemaType._castForQuery (/Users/<directories>/node_modules/mongoose/lib/schematype.js:1544:15)
      at SchemaNumber.castForQuery (/Users/<directories>/node_modules/mongoose/lib/schema/number.js:453:14)
      at SchemaNumber.SchemaType.castForQueryWrapper (/Users/<directories>/node_modules/mongoose/lib/schematype.js:1511:20)
      at cast (/Users/<directories>/node_modules/mongoose/lib/cast.js:331:32)
      at model.Query.Query.cast (/Users/<directories>/node_modules/mongoose/lib/query.js:4759:12)
      at model.Query.Query._castConditions (/Users/<directories>/node_modules/mongoose/lib/query.js:1841:10)
      at model.Query.<anonymous> (/Users/<directories>/node_modules/mongoose/lib/query.js:1868:8)
      at model.Query._wrappedThunk [as _find] (/Users/<directories>/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
      at /Users/<directories>/node_modules/kareem/index.js:370:33
      at processTicksAndRejections (node:internal/process/task_queues:75:11) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  }
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I am not sure how to reproduce this. I can not get into the debugging since this happens before any of my code runs and the stack trace is not complete (I dont know where and why this happens in my code).

From the stack trace last line, I think this is the same bug as in https://github.com/Automattic/mongoose/issues/8711
Not sure if the above has been fixed and merged

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

All of the packages were upgraded just now:
├── axios@0.21.1
├── bluebird@3.7.2
├── bunyan@1.8.15
├── env-cmd@10.1.0
├── express@4.17.1
├── hbs@4.1.1
├── jest@26.6.3
├── jsonwebtoken@8.5.1
├── moment@2.29.1
├── mongodb@3.6.3
├── mongoose@5.11.11
├── nodemon@2.0.7
├── postman-request@2.88.1-postman.28
├── qs@6.9.5
├── redis@3.0.2

**Comment by rmmenon** [comment]
@vkarpov15 - you asked me to create a separate bug so I did. Thank you

**Comment by vkarpov15** [comment]
Best I can tell this looks like it is caused by you calling `find()` with a string `'undefined'`. The below code gives me the same output:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = Schema({ tradeYear: Number });
  const Test = mongoose.model('Test', schema);

  const doc = await Test.find({ tradeYear: 'undefined' }).exec();
  console.log('Done', doc);
}
```

Output:

```
CastError: Cast to Number failed for value "undefined" at path "tradeYear" for model "Test"
    at model.Query.exec (/home/val/Workspace/MongoDB/mongoose/lib/query.js:4358:21)
    at run (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-9810.js:22:59)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  messageFormat: undefined,
  stringValue: '"undefined"',
  kind: 'Number',
  value: 'undefined',
  path: 'tradeYear',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert.ok(!isNaN(val))
  
      at castNumber (/home/val/Workspace/MongoDB/mongoose/lib/cast/number.js:28:10)
      at SchemaNumber.cast (/home/val/Workspace/MongoDB/mongoose/lib/schema/number.js:399:12)
      at SchemaNumber.SchemaType.applySetters (/home/val/Workspace/MongoDB/mongoose/lib/schematype.js:1090:12)
      at SchemaNumber.SchemaType._castForQuery (/home/val/Workspace/MongoDB/mongoose/lib/schematype.js:1525:15)
      at SchemaNumber.castForQuery (/home/val/Workspace/MongoDB/mongoose/lib/schema/number.js:453:14)
      at SchemaNumber.SchemaType.castForQueryWrapper (/home/val/Workspace/MongoDB/mongoose/lib/schematype.js:1492:20)
      at cast (/home/val/Workspace/MongoDB/mongoose/lib/cast.js:331:32)
      at model.Query.Query.cast (/home/val/Workspace/MongoDB/mongoose/lib/query.js:4759:12)
      at model.Query.Query._castConditions (/home/val/Workspace/MongoDB/mongoose/lib/query.js:1841:10)
      at model.Query.<anonymous> (/home/val/Workspace/MongoDB/mongoose/lib/query.js:1868:8)
      at model.Query._wrappedThunk [as _find] (/home/val/Workspace/MongoDB/mongoose/lib/helpers/query/wrapThunk.js:16:8)
      at /home/val/Workspace/MongoDB/mongoose/node_modules/kareem/index.js:370:33
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  }
}
```

Without more information, I would have to chalk this one up to an [unhandled rejection](https://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html) that your code should handle. Look for anywhere you're doing `find({ tradeYear })` and make sure you're handling errors.

**Comment by rmmenon** [comment]
Thanks - just saw this. Unfortunately, there is no way for me to debug. I ended up deciding to switch to a different db (postgres). Thank you for your help.

**Comment by Jericho-mouseclick-event** [comment]
> Best I can tell this looks like it is caused by you calling `find()` with a string `'undefined'`. The below code gives me the same output:
> 
> 'use strict';
>   
> const mongoose = require('mongoose');
> 
> mongoose.set('useFindAndModify', false);
> 
> const { Schema } = mongoose;
> 
> run().catch(err => console.log(err));
> 
> async function run() {
>   await mongoose.connect('mongodb://localhost:27017/test', {
>     useNewUrlParser: true,
>     useUnifiedTopology: true
>   });
> 
>   await mongoose.connection.dropDatabase();
> 
>   const schema = Schema({ tradeYear: Number });
>   const Test = mongoose.model('Test', schema);
> 
>   const doc = await Test.find({ tradeYear: 'undefined' }).exec();
>   console.log('Done', doc);
> }
> Output:
> 
> ```
> CastError: Cast to Number failed for value "undefined" at path "tradeYear" for model "Test"
>     at model.Query.exec (/home/val/Workspace/MongoDB/mongoose/lib/query.js:4358:21)
>     at run (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-9810.js:22:59)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   messageFormat: undefined,
>   stringValue: '"undefined"',
>   kind: 'Number',
>   value: 'undefined',
>   path: 'tradeYear',
>   reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
>   
>     assert.ok(!isNaN(val))
>   
>       at castNumber (/home/val/Workspace/MongoDB/mongoose/lib/cast/number.js:28:10)
>       at SchemaNumber.cast (/home/val/Workspace/MongoDB/mongoose/lib/schema/number.js:399:12)
>       at SchemaNumber.SchemaType.applySetters (/home/val/Workspace/MongoDB/mongoose/lib/schematype.js:1090:12)
>       at SchemaNumber.SchemaType._castForQuery (/home/val/Workspace/MongoDB/mongoose/lib/schematype.js:1525:15)
>       at SchemaNumber.castForQuery (/home/val/Workspace/MongoDB/mongoose/lib/schema/number.js:453:14)
>       at SchemaNumber.SchemaType.castForQueryWrapper (/home/val/Workspace/MongoDB/mongoose/lib/schematype.js:1492:20)
>       at cast (/home/val/Workspace/MongoDB/mongoose/lib/cast.js:331:32)
>       at model.Query.Query.cast (/home/val/Workspace/MongoDB/mongoose/lib/query.js:4759:12)
>       at model.Query.Query._castConditions (/home/val/Workspace/MongoDB/mongoose/lib/query.js:1841:10)
>       at model.Query.<anonymous> (/home/val/Workspace/MongoDB/mongoose/lib/query.js:1868:8)
>       at model.Query._wrappedThunk [as _find] (/home/val/Workspace/MongoDB/mongoose/lib/helpers/query/wrapThunk.js:16:8)
>       at /home/val/Workspace/MongoDB/mongoose/node_modules/kareem/index.js:370:33
>       at processTicksAndRejections (internal/process/task_queues.js:79:11) {
>     generatedMessage: true,
>     code: 'ERR_ASSERTION',
>     actual: false,
>     expected: true,
>     operator: '=='
>   }
> }
> ```
> 
> Without more information, I would have to chalk this one up to an [unhandled rejection](https://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html) that your code should handle. Look for anywhere you're doing `find({ tradeYear })` and make sure you're handling errors.





https://malakaicutoff.github.io/hank7/
