### ISSUE TITLE
Map of Schemas throws error with DocumentDB

### ISSUE THREAD

**Issue by KensingtonTech** [Automattic/mongoose#9811]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using Mongoose with DocumentDB 4.0, when adding a single value of type Schema to a Map, the following error is thrown when using Model.save().  I know that DocumentDB isn't officially supported, but I believe the problem to be a bad $unset operation in the updateOne() call which, if fixed, should resolve the problem.

```
MongoError: The dollar ($) prefixed field '$*' in '$*' is not valid for storage.
    at Function.create (/app/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/app/node_modules/mongodb/lib/utils.js:123:22)
    at /app/node_modules/mongodb/lib/operations/common_functions.js:379:39
    at handler (/app/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at /app/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/app/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (node:events:376:20)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:395:12)
    at MessageStream.Writable.write (node:internal/streams/writable:340:10)
    at TLSSocket.ondata (node:internal/streams/readable:748:22)
    at TLSSocket.emit (node:events:376:20) {
  driver: true,
  index: 0,
  code: 52
}
```

I turned on debugging which yielded this:

`Mongoose: test.updateOne({ _id: ObjectId("5fffb8e23b5eb0624551979e") }, { '$unset': { 'myMap.$*.myValue': 1 }, '$set': { 'myMap.abc': { myValue: 'some value' } }}, { session: null })`

Notice the $unset operation here containing a '$*'.  I don't think this belongs here.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');

const SubSchema = mongoose.Schema({
  myValue: {
    type: String
  }
}, {_id: false});

const Schema = mongoose.Schema({
  myMap: {
    type: Map,
    of: {
      type: SubSchema
    },
    // required: true
  }
}, {minimize: false, collection: 'test'});

const Model = mongoose.model('TestModel', Schema);

const initMongoose = async () => {
  const mongooseUrl = `mongodb://myuser:mypassword@host:27017/`;
  try {
    mongoose.set('debug', true);
    await mongoose.connect(mongooseUrl, {
      tls: true,
      tlsAllowInvalidHostnames: true,
      tlsAllowInvalidCertificates: true,
      replicaSet: 'rs0',
      readPreference: 'secondaryPreferred',
      useUnifiedTopology: true,
      useNewUrlParser: true,
      promiseLibrary: global.Promise,
      useFindAndModify: false,
      retryWrites: false,
      connectTimeoutMS: 5000,
      socketTimeoutMS: 5000,
      serverSelectionTimeoutMS: 5000
    });
  }
  catch (err) {
    console.error(err);
    process.exit(1);
  }
  console.log('Connected');
};

const test = async () => {
  await Model.deleteMany({}); // remove all existing documents
  const newModel = {
    myMap: new Map()
  };
  const doc = await Model.create(newModel);
  console.log('Created doc');
  
  console.log('Setting a map value');
  doc.myMap.set('abc', {myValue: 'some value'});
  
  console.log('Saving document');
  await doc.save().catch( (error) => {
    console.error(error);
    process.exit(1);
  }); // will throw error with DocumentDB
};

const main = async () => {
  await initMongoose();
  await test();
};

main();
```

### Produces the following output:
```
Connected
Mongoose: test.deleteMany({}, {})
Mongoose: test.insertOne({ _id: ObjectId("5fffb8e23b5eb0624551979e"), myMap: Map(0) {}, __v: 0 }, { session: null })
Created doc
Setting a map value
Saving document
Mongoose: test.updateOne({ _id: ObjectId("5fffb8e23b5eb0624551979e") }, { '$unset': { 'myMap.$*.myValue': 1 }, '$set': { 'myMap.abc': { myValue: 'some value' } }}, { session: null })
MongoError: The dollar ($) prefixed field '$*' in '$*' is not valid for storage.
    at Function.create (/Users/me/src/map-bug/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/Users/me/src/map-bug/node_modules/mongodb/lib/utils.js:123:22)
    at /Users/me/src/map-bug/node_modules/mongodb/lib/operations/common_functions.js:379:39
    at handler (/Users/me/src/map-bug/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at /Users/me/src/map-bug/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/Users/me/src/map-bug/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/Users/me/src/map-bug/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/Users/me/src/map-bug/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/Users/me/src/map-bug/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.ondata (_stream_readable.js:717:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9) {
  driver: true,
  index: 0,
  code: 52
}
```

**What is the expected behavior?**
There should be no $unset in updateOne() when the only thing that should be happening is a $set.  This should mitigate the error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 15.5.1
Mongoose: 5.11.11
MongoDB: Amazon DocumentDB 4.0.

**Comment by vkarpov15** [comment]
Fixed by https://github.com/Automattic/mongoose/pull/9842/
