### ISSUE TITLE
Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by gauri194** [Automattic/mongoose#9819]
Can't really pinpoint what the error is as I am only starting to learn this.

```javascript
//Accessing package
const  mongoose=require('mongoose');

//Database connection
mongoose.Promise=global.Promise;
mongoose.connect('mongodb://localhost:27017/library',{useNewUrlParser:true})
.then(()=>console.log('connection successful'))
.catch((err)=>console.log(err))

//Schema definition
const Schema = mongoose.Schema;

const BookSchema = new Schema({
    title: String,
    author:String,
    genre:String,
    publisher:String,
    img:String
});

//Model Definition
var Bookdata = mongoose.model('bookdata',BookSchema);


module.exports =Bookdata;
```

The error I am getting is 

```
TypeError: Cannot read property 'title' of undefined
    at C:\Users\dexteroy\Desktop\LibraryApp\src\routes\adminRoutes.js:19:26
    at Layer.handle [as handle_request] (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (C:\Users\dexteroy\Desktop\LibraryApp\node_modules\serve-static\index.js:121:7)
```

**Comment by YC** [comment]
The code which you attached above seems fine. 
Take a look at `at C:\Users\dexteroy\Desktop\LibraryApp\src\routes\adminRoutes.js:19:26` instead.

**Comment by gauri194** [comment]
> The code which you attached above seems fine.
> Take a look at `at C:\Users\dexteroy\Desktop\LibraryApp\src\routes\adminRoutes.js:19:26` instead.

I'll the adminRoutes code as well:

const express=require('express');
const adminRouter=express.Router();
const Bookdata =require('../model/Bookdata');


function router(nav){
    adminRouter.get('/',function(req,res){
        res.render('addBook',{
            nav,
            title:'Library'
        })
    }) 


adminRouter.get('/addBook',function(req,res){
   
    var item = {
        
        title: res.query.title,
        author: res.query.author,
        genre:  res.query.genre,
        publisher:  res.query.publisher,
        img:    res.query.img
    }
    

    var book = Bookdata(item);
    book.save();
    res.redirect('/books');
    
})
return adminRouter;

}

module.exports=router;

**Comment by YC** [comment]
This is outside the scope of `mongoose`, but it should be `req.query` (i.e. the query parameters come from the request).

**Comment by vkarpov15** [comment]
@YC is right, change to `req.query.title`, `req.query.author`, etc. and it should work :+1:
