### ISSUE TITLE
Current topology does not support sessions in aws lambda

### ISSUE THREAD

**Issue by phpedinei** [Automattic/mongoose#9924]
Hi!
I'm using mongoose with the following connection setup: 

```
let conn = null

async function connectToDatabase () {
  if (conn === null) {
    const database = await mongoose.connect(MONGO_CONNECT_STRING, {
      useUnifiedTopology: true,
      useNewUrlParser: true,
      useCreateIndex: true,
      serverSelectionTimeoutMS: 5000
    })
    conn = database.connections[0].readyState
  }
}
```
And, about 30% of the time I get an error when starting a transaction: 

```
{
    "errorType": "MongoError",
    "errorMessage": "Current topology does not support sessions",
    "name": "MongoError",
    "stack": [
        "MongoError: Current topology does not support sessions",
        "    at MongoClient.startSession (/var/task/node_modules/mongodb/lib/mongo_client.js:459:11)",
        "    at NativeConnection.startSession (/var/task/node_modules/mongoose/lib/connection.js:440:31)",
        "    at /var/task/node_modules/mongoose/lib/connection.js:582:16",
        "    at processTicksAndRejections (internal/process/task_queues.js:75:11)"
    ]
}
```

What am I doing wrong? 

Serverless 
AWS Lambda
Node 14.x
Mongoose 5.11.15
MongoDB - Atlas 4.4.3

**Comment by gaoxiaoliangz** [comment]
I'm getting the same error, while using mongodb nodejs driver. I checked the log, found that the error came from client.startSession, even with the same client instance, it has the chance to get the error. Cannot reproduce this in local. And I also found this issue <https://jira.mongodb.org/browse/NODE-2794>.

**Comment by radAragon** [comment]
I'm also receiving the same error sometimes in a Lambda connecting to Atlas MongoDB, although my configuration is more like:
```
{
    uri: 'uri',
    options: {
      user: 'user',
      pass: 'pass',
      dbName: 'dbName',
      // See https://mongoosejs.com/docs/deprecations.html
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
      useFindAndModify: false,
      autoIndex: false
    }
  }
```

**Comment by gaoxiaoliangz** [comment]
> I'm also receiving the same error sometimes in a Lambda connecting to Atlas MongoDB, although my configuration is more like:
> 
> ```
> {
>     uri: 'uri',
>     options: {
>       user: 'user',
>       pass: 'pass',
>       dbName: 'dbName',
>       // See https://mongoosejs.com/docs/deprecations.html
>       useNewUrlParser: true,
>       useUnifiedTopology: true,
>       useCreateIndex: true,
>       useFindAndModify: false,
>       autoIndex: false
>     }
>   }
> ```
> 
> Same setup from OC, except:
> `"mongoose": "5.10.4"`

After debugging for quite some time, I found that I can reproduce the error from local when I suspend and wait 20s then resume the main process. And most importantly I used the connect option `useUnifiedTopology`, after set this option to `false`, everything went well.

**Comment by michaelgutierrez0** [comment]
Looks similar to my issue:
https://github.com/Automattic/mongoose/issues/9943

**Comment by vkarpov15** [comment]
I tried running the below script with [stopping and starting the process in linux](https://ostechnix.com/suspend-process-resume-later-linux/). No luck repro-ing thus far, will try again in a few days on Lambda.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  let conn = null

async function connectToDatabase () {
  if (conn === null) {
    const database = await mongoose.connect('mongodb+srv://OMITTED@cluster0.xvnqv.mongodb.net/myFirstDatabase?retryWrites=true&w=majority', {
      useUnifiedTopology: true,
      useNewUrlParser: true,
      useCreateIndex: true,
      serverSelectionTimeoutMS: 5000
    })
    conn = database.connections[0].readyState
  }
}

  conn = await connectToDatabase();

  const Test = mongoose.model('Test', Schema({ name: String }));

  while (true) {
    console.log('Start');
    await mongoose.connection.transaction(async function(session) {
      await Test.findOne({}, null, { session });
    });
    console.log('End');
    await new Promise(resolve => setTimeout(resolve, 1000));
  }
}

```

**Comment by irfan-anwar** [comment]
Same issue, bump

**Comment by vkarpov15** [comment]
No luck reproing this, even in AWS lambda. Below script succeeds without error even with a cold start.

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

exports.handler = async function(event, context) {
  context.callbackWaitsForEmptyEventLoop = false;
    await connectToDatabase();
  
  const session = await mongoose.startSession();
  await Test.findOne({}, null, { session });
  session.endSession();
    
  return { ok: 1 };
};

let conn = null;
let Test;
async function connectToDatabase () {
  if (conn === null) {
    const database = await mongoose.connect('mongodb+srv://OMITTED@cluster0.OMITTED.mongodb.net/myFirstDatabase?retryWrites=true&w=majority', {
      useUnifiedTopology: true,
      useNewUrlParser: true,
      useCreateIndex: true,
      serverSelectionTimeoutMS: 5000
    });
    conn = database.connections[0].readyState;
    
    Test = database.model('Test', Schema({ name: String }));
  }
  
  return conn;
}
```

Are you using field level encryption? If so, it may be a result of this issue: https://developer.mongodb.com/community/forums/t/automatic-client-field-level-encryption-with-aws-lambda/8548

**Comment by harveyconnor** [comment]
Hi we just got this in our production server when the server was under high load:
```js
2021-08-30T01:46:39.542782640Z /app/node_modules/mongodb/lib/mongo_client.js:458
2021-08-30T01:46:39.542786340Z     throw new MongoError('Current topology does not support sessions');
2021-08-30T01:46:39.542789840Z     ^
2021-08-30T01:46:39.542793240Z
2021-08-30T01:46:39.542796640Z MongoError: Current topology does not support sessions
2021-08-30T01:46:39.542800140Z     at MongoClient.startSession (/app/node_modules/mongodb/lib/mongo_client.js:458:11)
2021-08-30T01:46:39.542803640Z     at NativeConnection.startSession (/app/node_modules/mongoose/lib/connection.js:419:31)
2021-08-30T01:46:39.542807040Z     at /app/node_modules/mongoose/lib/connection.js:559:14
2021-08-30T01:46:39.542810440Z     at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-08-30T01:46:39.672354357Z npm ERR! code ELIFECYCLE
2021-08-30T01:46:39.672373557Z npm ERR! errno 1
2021-08-30T01:46:39.672378357Z npm ERR! api@1.0.0 start: `node ./dist/index.js`
2021-08-30T01:46:39.672381757Z npm ERR! Exit status 1
2021-08-30T01:46:39.672384857Z npm ERR!
2021-08-30T01:46:39.672387957Z npm ERR! Failed at the api@1.0.0 start script.
2021-08-30T01:46:39.672391357Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This resulted in our server crashing. Any idea?

**Comment by vkarpov15** [comment]
@harveyconnor hard to tell without more information. One possibility is that one or more of your MongoDB servers were down when this `startSession()` call happened, or there was some intermittent network issue that prevented your server from connecting to your MongoDB server

**Comment by harveyconnor** [comment]
Thanks @vkarpov15 for the insight, we'll take a deeper look and see if we can get more information.
