### ISSUE TITLE
Warning: Accessing non-existent property 'MongoError'

### ISSUE THREAD

**Issue by s1bp** [Automattic/mongoose#9953]
**Do you want to request a *feature* or report a *bug*?**

**Bug**

**What is the current behavior?**
```
(node:9653) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:698:11)
    at Object.get (node:internal/modules/cjs/loader:712:5)
    at Object.<anonymous> (/USER/backend/node_modules/mongodb/lib/operations/operation.js:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/USER/backend/node_modules/mongodb/lib/operations/execute_operation.js:4:16)
(node:9653) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
    at _setClient (/USER/backend/node_modules/mongoose/lib/connection.js:932:10)
    at /USER/backend/node_modules/mongoose/lib/connection.js:839:7
    at /USER/backend/node_modules/mongodb/lib/utils.js:693:5
    at /USER/backend/node_modules/mongodb/lib/mongo_client.js:227:7
    at connectCallback (/USER/backend/node_modules/mongodb/lib/operations/connect.js:366:5)
    at /USER/backend/node_modules/mongodb/lib/operations/connect.js:602:5
    at connectHandler (/USER/backend/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at cb (/USER/backend/node_modules/mongodb/lib/core/sdam/topology.js:681:26)
    at /USER/backend/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/USER/backend/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/USER/backend/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (node:events:378:20)
    at processIncomingData (/USER/backend/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/USER/backend/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:400:12)
    at _write (node:internal/streams/writable:341:10)
``` 
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install mongoose package
2. Initialize connection to database using 
``` mongoose.connect(`mongodb://localhost:27017/DATABASE`, { useNewUrlParser: true, useUnifiedTopology: true })```
3. Run the servers it shows above warnings.

**What is the expected behavior?**

Connect to local or cloud-base mongoDB, without errors or warnings.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js version`15.8.0` 

Mongoose version `5.11.17`

**Comment by jumoog** [comment]
see #9935
