### ISSUE TITLE
Cannot create property 'clusterTime'

### ISSUE THREAD

**Issue by mspapant** [Automattic/mongoose#9955]
Hello, i use the version `5.6.4` and occasionaly i take the following error:

```uncaughtException: Cannot create property 'clusterTime' on string '[Circular]'
TypeError: Cannot create property 'clusterTime' on string '[Circular]'
 at Connection.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:429:37)
 at Connection.emit (events.js:198:13)
 at Connection.EventEmitter.emit (domain.js:448:20)
 at processMessage (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:364:10)
 at TLSSocket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:533:15)
 at TLSSocket.emit (events.js:198:13)
 at TLSSocket.EventEmitter.emit (domain.js:448:20)
 at addChunk (_stream_readable.js:288:12)
 at readableAddChunk (_stream_readable.js:269:11)
 at TLSSocket.Readable.push (_stream_readable.js:224:10)
 at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
               "stack": "TypeError: Cannot create property 'clusterTime' on string '[Circular]'
 at Connection.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:429:37)
 at Connection.emit (events.js:198:13)
 at Connection.EventEmitter.emit (domain.js:448:20)
 at processMessage (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:364:10)
 at TLSSocket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:533:15)
 at TLSSocket.emit (events.js:198:13)
 at TLSSocket.EventEmitter.emit (domain.js:448:20)
 at addChunk (_stream_readable.js:288:12)
 at readableAddChunk (_stream_readable.js:269:11)
 at TLSSocket.Readable.push (_stream_readable.js:224:10)
 at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Does anyone know what is the problem? The db is on Atlas

**Comment by vkarpov15** [comment]
@mspapant do you have any idea on what operation this happens? The async stack trace isn't particularly helpful unfortunately.

**Comment by mspapant** [comment]
@vkarpov15 this is happened when trying to update a document in database. Don't you want any other information?

**Comment by vkarpov15** [comment]
@mspapant yes please. Any code samples you can provide would be very helpful since there's quite a few ways to [update a document in Mongoose](https://masteringjs.io/tutorials/mongoose/update).

**Comment by vkarpov15** [comment]
The only thing I can tell from the stack trace is that `self.topology` is a string in this line: https://github.com/mongodb-js/mongodb-core/blob/8192f8fdb85feedf8181ab727f6dc460d1e34e2c/lib/connection/pool.js#L429 . Which would indicate that either here: https://github.com/mongodb-js/mongodb-core/blob/8192f8fdb85feedf8181ab727f6dc460d1e34e2c/lib/topologies/server.js#L473 or here: https://github.com/mongodb-js/mongodb-core/blob/8192f8fdb85feedf8181ab727f6dc460d1e34e2c/lib/sdam/server.js#L121 that `this` is a string, which doesn't seem possible because `this.s.pool` would throw first.

Without more info, not much we can do to try to track this down. Can you please provide a more thorough code sample?
