### ISSUE TITLE
TypeError: doc.$__reset is not a function

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#9967]
mongoose v5.11.17

```sh
4|app     | TypeError: doc.$__reset is not a function
4|app     |     at /var/www/staging/source/node_modules/mongoose/lib/document.js:2872:13
4|app     |     at Array.forEach (<anonymous>)
4|app     |     at model.reset [as $__reset] (/var/www/staging/source/node_modules/mongoose/lib/document.js:2865:6)
4|app     |     at model.Model.$__handleSave (/var/www/staging/source/node_modules/mongoose/lib/model.js:337:10)
4|app     |     at model.Model.$__save (/var/www/staging/source/node_modules/mongoose/lib/model.js:348:8)
4|app     |     at /var/www/staging/source/node_modules/kareem/index.js:279:20
4|app     |     at /var/www/staging/source/node_modules/kareem/index.js:78:15
4|app     |     at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

No information other than that - and it's on a `.save()` query.

**Comment by niftylettuce** [comment]
Might be related to https://github.com/Automattic/mongoose/issues/9011 - it's an Array of Arrays though I'm calling with `splice`

**Comment by niftylettuce** [comment]
100% CONFIRMED BUG when calling `splice` on a nested subdocument array causes this error, this is a core major bug

**Comment by niftylettuce** [comment]
I also confirmed that using `slice` instead fixes the issue.

e.g. `items[x].nested_items.splice(20)` (doesn't work) whereas `items[x].nested_items = items[x].nested_items.slice(0, 20)` (DOES work)

**Comment by vkarpov15** [comment]
I'm unable to repro, the below script executes without any error. Please modify the below script to demonstrate your issue.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    items: [{
      nestedItems: [{ name: String }]
    }]
  });
  const Test = mongoose.model('Test', schema);

  const doc = await Test.create({
    items: [
      { nestedItems: [{ name: '00' }, { name: '01' }] },
      { nestedItems: [{ name: '10' }] }
    ]
  });

  doc.items[0].nestedItems.splice(0, 1);
  await doc.save();

  console.log(doc.items[0]);
}
```

**Comment by niftylettuce** [comment]
I think you need to have `nestedItems` be a sub schema, like `nestedItems: [ [NestedItem] ]`

```
const OtherStuff = new Schema({
  foo: String
});

const ItemSchema = new Schema({
  items: [
    {
      other_stuff: [ [ OtherStuff ] ]
    }
  ]
});

const schema = new Schema({
  items: [ItemSchema]
});
```

This schema setup should mirror my issue that I faced in production.

**Comment by IslandRhythms** [comment]
I can't reproduce it either
```
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const OtherStuff = new Schema({
    foo: String
  });
  
  const ItemSchema = new Schema({
    items: [
      {
        other_stuff: [[ OtherStuff ]]
      }
    ]
  });
  
  const schema = new Schema({
    items: [ItemSchema]
  });
  const Test = mongoose.model('Test', schema);
  const Test2 = mongoose.model('Test2', ItemSchema);
  const Test3 = mongoose.model('Test3', OtherStuff);


  const doc = await Test.create({
    items: [
      {items: [
      { other_stuff: [{ foo: '00' }, { foo: '01' }] },
      { other_stuff: [{ foo: '10' }] }
    ]}
  ]
  });

  doc.items[0].items[0].other_stuff.splice(0, 1);
  await doc.save();

  console.log(doc.items[0]);
}
```
